### ISSUE TITLE
Removing image from grid field

### ISSUE THREAD

**Issue by amatochristopher** [ExpressionEngine/ExpressionEngine#100]
**Description of the problem**
When you have a grid field and are using an image field within it. I am experiencing deleting the image and uploading a new one. It will display an error an error saying that the field is required even though the image has been uploaded. Thus you will not be able to save the entry. You can get around this by removing the entire row and creating a new row and uploading a new image.

**How To Reproduce**

1. Open an existing entry with a grid using an image field.
2. Remove the image from the grid (This will prompt "This field is required")
3. Upload new image or choose existing image.
4. Try to save entry.

**Screenshots / Videos / Template Code**
Before you remove the image:
<img width="1153" alt="screen shot 2019-01-18 at 3 56 40 pm" src="https://user-images.githubusercontent.com/5550114/51412463-afead780-1b39-11e9-9192-d6b1a1318c98.png">

When you remove the image:
<img width="723" alt="screen shot 2019-01-18 at 3 47 46 pm" src="https://user-images.githubusercontent.com/5550114/51412176-b7f64780-1b38-11e9-9137-ef8ae6ad189a.png">

After adding a new image:
<img width="1153" alt="screen shot 2019-01-18 at 3 55 51 pm" src="https://user-images.githubusercontent.com/5550114/51412432-8e89eb80-1b39-11e9-9e26-30577fe33097.png">

**Environment Details:**
 - Version: 5.1.2
 - PHP Version 7.0.33
 - MySQL Version 5.0.12
 - OS: Linux
 - Web Server: Apache

**Possible Solution**
You can get around this by removing the entire row and creating a new row and uploading a new image.

**Comment by kevincupp** [comment]
Thanks, @amatochristopher, and sorry for the trouble. It looks like this is already fixed in the stability branch by 8d4d946ed9061c336521a474d80993b10534f8a5, look for a release soon.

As for the styling of "uploading to Default", it looks like some styles for `td.invalid` may be overriding that, pinging @jmathias for that.
