### ISSUE TITLE
PATH_THIRD vs PATH_MOD

### ISSUE THREAD

**Issue by meshucs** [ExpressionEngine/ExpressionEngine#1003]
Should the PATH_THIRD be updated to PATH_MOD for complete integrations with javascript (and css) package loading? I have some failures as PATH_THIRD would references the legacy third party addon location. 

https://github.com/ExpressionEngine/ExpressionEngine/blob/36581fd1243c5845c125056bf8cf63406cd4d9d4/system/ee/legacy/controllers/cp/javascript.php#L105

**Comment by intoeetive** [comment]
While `PATH_MOD` is still defined, it is legacy constant from old old times (and is not listed in the [docs](https://docs.expressionengine.com/latest/development/constants.html#constants-reference))

`PATH_THIRD` is correctly referencing `/system/user/addons/` directory.

I am going to close this issue as irrelevant. If you have any specific problem that you think represents a bug, please open new issue.
