### ISSUE TITLE
Rich Text Editor media embed doesn’t render embed code

### ISSUE THREAD

**Issue by regmtait** [ExpressionEngine/ExpressionEngine#1006]
The RTE media button in the toolbar accepts full URLs to media assets, such as a YouTube or Vimeo video. The embedded video shows in the editor as I might expect.

However in the front end it renders like this—in an `oembed` tag:

`<figure class="media"><oembed url="https://www.youtube.com/watch?v=abcdef"></oembed></figure>`

Nothing in the docs about how to transform into embed code… or if it’s a bug.

ExpressionEngine 6.0.3 / PHP 7.0.33

**Comment by intoeetive** [comment]
For the time being, please refer to one of these solutions: https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html#displaying-embedded-media-on-your-website

We will see if we can provide anything better / easier to use.

**Comment by robsonsobral** [comment]
If there isn't a correct output, the input shouldn't be converted to oEmbed.

The [commit](https://github.com/ExpressionEngine/ExpressionEngine/commit/9f148b47b38766d4baaa696629e7ee18892a17b3) causes more harm than good.

**Comment by intoeetive** [comment]
I'm not sure I follow.

Can you give an example where this had made things worse @robsonsobral ?

**Comment by robsonsobral** [comment]
As I gave the user the opportunity to insert the media **and see it** at the editor, the media should render. It's better to not have the button at all than to give them false expectations.

**Comment by robsonsobral** [comment]
[OEmbed All](https://github.com/kudago/oembed-all) is a heavy lib ([44kB](https://bundlephobia.com/package/oembed-all@1.2.0)), but... In case somebody need it:

```js
const Oembed = require('oembed-all/oembed');

export default (() => {
  const elements = document.querySelectorAll('oembed');

  for (let i = 0; i < elements.length; i += 1) {
    const oembedEl = elements[i];
    const newElement = document.createElement('a');
    newElement.href = oembedEl.getAttribute('url');
    oembedEl.parentNode.replaceChild(newElement, oembedEl);

    // eslint-disable-next-line no-new
    new Oembed(newElement, { includeHandle: false });
  }
});
```
