### ISSUE TITLE
Local dev with public urls

### ISSUE THREAD

**Issue by 8cylinder** [ExpressionEngine/ExpressionEngine#1014]
Several local docker development tools use a real domain name for dns.  These work fine except for plugins that are strict about functioning on public sites without a licence.

[Lando](https://docs.lando.dev/) and [DDEV](https://ddev.readthedocs.io/en/stable/) are two popular ones and they use `lndo.site` and `ddev.site`. 

It would be nice if `lndo.site` and `ddev.site` were added to the whitelist of allowed urls, or alternatively a couple more fields added to the EEHarbor add-on edit page so dev urls could be manually set.

A temporary solution is to set the staging url in our account settings to one of the public urls, ie. `newproject.lndo.site`, but that won't work when staging gets setup.

**Comment by obfuscode** [comment]
Thank you for suggesting this. It's not technically an ExpressionEngine issue but I've gone ahead and added `lndo.site` and `ddev.site` to our whitelisted PAAS domain list. If you run into any issues with these sites going forward or have any questions, feel free to DM me directly in the ExpressionEngine Slack group.
