### ISSUE TITLE
Grid Image field MSM throws an error

### ISSUE THREAD

**Issue by reinos** [ExpressionEngine/ExpressionEngine#102]
**Description of the problem**
In my MSM setup i added the Grid File field. On the main site, the fieldtype is working but on any other MSM site the field is not working. It throws an error:

**How To Reproduce**
1. Create field with Grid File Field
2. Edit an entry on an other MSM site (not the main one) and try to add files to the Grid File field

**Error Messages**

<pre><code>

TypeError: "e is undefined"
	value http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php?S=0&D=cp&C=javascript&M=combo_load&plugin=ui.touch.punch,ee_table_reorder&file=cp/global_end,cp/date_picker,cp/files/picker,fields/relationship/mutable_relationship,fields/relationship/relationship,cp/grid,fields/file/cp,fields/file/file_field_drag_and_drop,fields/file/concurrency_queue,fields/file/file_upload_progress_table,fields/file/drag_and_drop_upload,fields/grid/file_grid&v=1546531004:127:2561
	t http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php?S=0&D=cp&C=javascript&M=combo_load&plugin=ui.touch.punch,ee_table_reorder&file=cp/global_end,cp/date_picker,cp/files/picker,fields/relationship/mutable_relationship,fields/relationship/relationship,cp/grid,fields/file/cp,fields/file/file_field_drag_and_drop,fields/file/concurrency_queue,fields/file/file_upload_progress_table,fields/file/drag_and_drop_upload,fields/grid/file_grid&v=1546531004:127:1751
cms.php:171:11989
yn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:171:11989
Cn/n.callback
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:171:15591
Mt
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:170:26239
Ot
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:170:26037
jn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:171:31381
Bn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:171:26729
Vn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:171:26339
Mn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:171:25097
qn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:1186
Gn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:1257
nr.prototype.render
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:27633
lr/<
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:3088
$n
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:304
lr
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:3023
render
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:28637
value/<
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:100:1159
each
http://shop.maisondelabonnevie.nl.duniqueserver.nl/themes/ee/asset/javascript/compressed/jquery/jquery.js:2:14734
each
http://shop.maisondelabonnevie.nl.duniqueserver.nl/themes/ee/asset/javascript/compressed/jquery/jquery.js:2:12700
value
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:100:1061
e
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:91:1040
<anonymous>
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:91:1305
l
http://shop.maisondelabonnevie.nl.duniqueserver.nl/themes/ee/asset/javascript/compressed/jquery/jquery.js:3:6472
fireWith
http://shop.maisondelabonnevie.nl.duniqueserver.nl/themes/ee/asset/javascript/compressed/jquery/jquery.js:3:7245
ready
http://shop.maisondelabonnevie.nl.duniqueserver.nl/themes/ee/asset/javascript/compressed/jquery/jquery.js:3:9059
s
http://shop.maisondelabonnevie.nl.duniqueserver.nl/themes/ee/asset/javascript/compressed/jquery/jquery.js:2:942

TypeError: e is undefined[Learn More] cms.php:127:2561
value
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:127:2561
t
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:127:1751
sn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:171:3982
vn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:171:8980
In
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:171:21849
Rn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:171:22202
Bn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:171:26691
Vn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:171:26339
Mn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:171:25097
qn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:1186
Gn
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:1257
nr.prototype.render
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:27633
lr/<
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:3088
$n
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:304
lr
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:3023
render
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:172:28637
value/<
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:100:1159
each
http://shop.maisondelabonnevie.nl.duniqueserver.nl/themes/ee/asset/javascript/compressed/jquery/jquery.js:2:14734
each
http://shop.maisondelabonnevie.nl.duniqueserver.nl/themes/ee/asset/javascript/compressed/jquery/jquery.js:2:12700
value
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:100:1061
e
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:91:1040
<anonymous>
http://shop.maisondelabonnevie.nl.duniqueserver.nl/cms.php:91:1305
l
http://shop.maisondelabonnevie.nl.duniqueserver.nl/themes/ee/asset/javascript/compressed/jquery/jquery.js:3:6472
fireWith
http://shop.maisondelabonnevie.nl.duniqueserver.nl/themes/ee/asset/javascript/compressed/jquery/jquery.js:3:7245
ready
http://shop.maisondelabonnevie.nl.duniqueserver.nl/themes/ee/asset/javascript/compressed/jquery/jquery.js:3:9059
s
http://shop.maisondelabonnevie.nl.duniqueserver.nl/themes/ee/asset/javascript/compressed/jquery/jquery.js:2:942

</code></pre>

**Screenshots / Videos / Template Code**
![image](https://user-images.githubusercontent.com/633730/51471214-65a26a00-1d76-11e9-8854-2e11c36702d3.png)

**Environment Details:**
 - Version: 5.1.2
 - PHP Version 7.2
 - OS: Linux,
 - Web Server: Apache,

**Comment by reinos** [comment]
Problem found, it seems all `Allowed Directory` settings where wiped out...

![image](https://user-images.githubusercontent.com/633730/51476121-d781b000-1d84-11e9-86d5-30296f743e94.png)

After resetting them, all the entries are working as supposed to.

**Comment by kevincupp** [comment]
Sorry for your trouble! I think this is related to #78
