### ISSUE TITLE
http header addon - add permission option parameter for FLoC

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#1027]
**Is your feature request related to a problem? Please describe.**
Google is implementing FLoC and one way to prevent them tracking people's browser history is to add a http header permission policy. FLoC also isn't (yet) GDPR compatible, hence why they haven't rolled it out to the EU yet.

**Describe the solution you'd like**
Add an option to the http header addon to allow setting "Permissions-Policy: interest-cohort=()".

**Describe alternatives you've considered**
You can set it via .htaccess but it'd be good to have this as part of the addon so it can be applied per template or sitewide.

**Teachability, Documentation, Adoption, Migration Strategy**
Update docs to add details of the new parameter option.

**Comment by dougblackjr** [comment]
@blue-dreamer Added a PR for this [here](https://github.com/ExpressionEngine/ExpressionEngine/pull/1031)

**Comment by TomJaeger** [comment]
@dougblackjr Any chance you can add a config override option for this one as well?

**Comment by dougblackjr** [comment]
@TomJaeger What kind of config override would be helpful here?

**Comment by blue-dreamer** [comment]
@TomJaeger @dougblackjr looking at what other CMS's and browsers are doing - everyone seems to be denying FLoC by default, so IMHO EE should deny FLoC by default, then the config override would allow it. This approach presumes privacy by default, then it's down to the developer/site owner to enable it.

**Comment by dougblackjr** [comment]
@TomJaeger I updated the PR to:
- Send `interest_cohort=()` by default
- Allow for a config override to remove that default header

**Comment by intoeetive** [comment]
Closing this as referenced PR has been merged
