### ISSUE TITLE
Channel entry tag values not showing when updating 3.5.10 to 5.1.2

### ISSUE THREAD

**Issue by Havsvik** [ExpressionEngine/ExpressionEngine#103]
Hi,

When we update our site from 3.5.10 to 5.1.2 some channel entry tags does not display their values at all. We haven't been able to identify any pattern for which tags that doesn't display anything, as some tags display their information as expected.

When dumping the data returned from `$this->query()` at the end of `Channel::entries()` the `result_object` shows that some field values that should contain data are NULL. Although all data is found when when we run the exact same query in Sequel Pro. And all fields are populated as expected in backend.

The query mentioned above:
```mysql
SELECT t.entry_id, t.channel_id, t.forum_topic_id, t.author_id, t.ip_address, t.title, t.url_title, t.status, t.view_count_one, t.view_count_two, t.view_count_three, t.view_count_four, t.allow_comments, t.comment_expiration_date, t.sticky, t.entry_date, t.year, t.month, t.day, t.edit_date, t.expiration_date, t.recent_comment_date, t.comment_total, t.site_id as entry_site_id, w.channel_title, w.channel_name, w.channel_url, w.comment_url, w.comment_moderate, w.channel_html_formatting, w.channel_allow_img_urls, w.channel_auto_link_urls, w.comment_system_enabled, m.username, m.email, m.screen_name, m.signature, m.sig_img_filename, m.sig_img_width, m.sig_img_height, m.avatar_filename, m.avatar_width, m.avatar_height, m.photo_filename, m.photo_width, m.photo_height, m.group_id, m.member_id, wd.*, md.* , exp_member_data_field_14.*, exp_member_data_field_15.*, exp_member_data_field_16.*, exp_member_data_field_17.*, exp_member_data_field_18.* FROM exp_channel_titles	AS t LEFT JOIN exp_channels AS w ON t.channel_id = w.channel_id LEFT JOIN exp_channel_data	AS wd ON t.entry_id = wd.entry_id LEFT JOIN exp_members	AS m ON m.member_id = t.author_id LEFT JOIN exp_member_data	AS md ON md.member_id = m.member_id LEFT JOIN	exp_member_data_field_14 ON m.member_id = exp_member_data_field_14.member_id LEFT JOIN	exp_member_data_field_15 ON m.member_id = exp_member_data_field_15.member_id LEFT JOIN	exp_member_data_field_16 ON m.member_id = exp_member_data_field_16.member_id LEFT JOIN	exp_member_data_field_17 ON m.member_id = exp_member_data_field_17.member_id LEFT JOIN	exp_member_data_field_18 ON m.member_id = exp_member_data_field_18.member_id WHERE t.entry_id IN (54)ORDER BY FIELD(t.entry_id, 54)
```

**Environment Details:**
 - Version: 5.1.2
 - PHP Version 7.0.32

We have tried updating the same site both locally and on the live server, with the same result.

Do you have any idea why this is happening?

**Comment by kevincupp** [comment]
Sorry for your trouble, no I haven't seen anything like this before. It may be best to open a support ticket and have someone take a look at your install. Or if you're able to pinpoint the issue or have solid steps to reproduce, put them here in the issue. The string`result_object` doesn't appear in `mod.channel.php`, so I'd be curious about that. Maybe try disabling extensions, too.

**Comment by Havsvik** [comment]
Thanks for the reply! :)

I don't think there is a nice an easy way to reproduce this I'm afraid, since some fields may have been created with EE2 and so on. And the `result_object` is a key in the `$this->query()`, sorry about the confusion. You could dump the `$this->query->result_array()` instead.

We also tried updating to 4.3.8 and disabling all extensions, without any luck.

But, we recently discovered that the tags returns values as expected if no member fields needs to be parsed within the channel:entries tags. This also works when disable="member_data" on the channel:entries tag.

Do you recognise this behaviour?

**Comment by kevincupp** [comment]
Interesting development! My first thought is some member field columns might be overwriting your channel field columns, but I don't see how that could happen, and I figured we'd have heard about it by now if it were that simple. Do the columns missing data happen to have the same field IDs as the member fields that are brought in?

**Comment by Havsvik** [comment]
They actually have the same ID, and when looking closer at my query result from the query above, some column names appears twice :O

The fields that we noticed this behaviour with all have low ID's, just like the member fields. The column `field_id_2` for example, appears once around the other entry colums (with the correct data) and then another one with the member fields for some reason.

When looking closer at the `exp_member_data`, I noticed that it contains columns that aren't prepended with `m_`, is this normal? They only contains null values

Looks like this (field_id_2, field_id_5 and so on): 
![screen shot 2019-01-22 at 16 28 29](https://user-images.githubusercontent.com/46523493/51545707-d1620100-1e62-11e9-8701-785a1c6cd392.png)

As a side note, we have used the User addon on this site for a while.

**Comment by kevincupp** [comment]
No all the fields should be prefixed with `m_`. Maybe try altering those columns to match.

**Comment by Havsvik** [comment]
Well, I dropped all columns without a prefix (except member_id), and now it is working :D

Thanks for the help! :)

**Comment by derekjones** [comment]
I've seen this one other time on an installation in support (member columns without the `m_`), did not discover a cause. I don't suppose you noticed in your upgrade attempts if those columns were already there before running the ExpressionEngine update, after, or after running the third-party User module update?

**Comment by derekjones** [comment]
Just speculation as I don't have access to the other install I saw this in once, but perhaps it was from the User module. ¯\_(ツ)_/¯

If you encounter it again, please just reopen this issue with the details and maybe the source will be discoverable. Thanks!
