### ISSUE TITLE
Fluid field container data-field-count attribute not updating?

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1037]
I was looking at adding an "empty fluid field" state via custom CSS. I thought I could use the `data-field-count` attribute on `div.fluid` to detect when the user hasn't added content to a fluid field yet, but adding content doesn't update the value. I thought maybe it would update after a save and page reload, but no.

I expected the value of `data-field-count` to increase each time the user clicks a button to add content to the fluid field (and of course decrease when they remove content).

**How To Reproduce**

1. Create a fluid field with at least one button.
2. Inspect the field in the publish form and note that `data-field-count` has a value of 0.
3. Add content to the fluid field and note that the value hasn't changed.
4. Save and reload the page, and note that the value hasn't changed.

<img width="566" alt="Screen Shot 2021-04-20 at 12 49 35 PM" src="https://user-images.githubusercontent.com/308752/115435537-f1b2ce80-a1d7-11eb-912e-4ac7801fb36c.png">

**Comment by murtaugh** [comment]
Bumping this, I keep tripping over it.

**Comment by intoeetive** [comment]
@Yulyaswan FYI
