### ISSUE TITLE
Menu manager won't add member groups

### ISSUE THREAD

**Issue by philsgud** [ExpressionEngine/ExpressionEngine#1038]
I tried to add a member group to the default menu and it won't add.

**Comment by intoeetive** [comment]
@philsgud is this same issue that https://github.com/ExpressionEngine/ExpressionEngine/issues/935 or a different one?

**Comment by philsgud** [comment]
Yes same issue

**Comment by intoeetive** [comment]
Thank you. Closing as duplicate of #935 then
