### ISSUE TITLE
urlSlug text formatter does not strip pipe characters, even though they are disallowed

### ISSUE THREAD

**Issue by amphibian** [ExpressionEngine/ExpressionEngine#104]
**Description of the problem**
When submitting an entry with a channel form, and including a pipe (|) character in the title, the URL title returns with an error.

**How To Reproduce**
1. Create a channel form.
2. Submit an entry with a pipe character in the title.

**Environment Details:**
 - Version: 4.3.6
 - PHP Version: 7.0.32
 - MySQL Version: 5.0.12
 - OS: Linux
 - Web Server: Apache

**Possible Solution**
On line 591 of the Text formatter, change:

    // replace whitespace and forward slashes with the separator
    '#\s+|/+#i' => $options['separator'],

With:

    // replace whitespace, forward slashes, and pipes with the separator
    '#\s+|/+|\|+#i' => $options['separator'],

**Additional context**
Theoretically this regex line:

    // only allow low ascii letters, numbers, dash, dot, underscore, and emoji
    '#[^a-z0-9\-\._'.$this->getConfig('emoji_regex').']#iu' => '',

... should remove pipes, but something in the `emoji_regex` string is preventing that (as removing the `emoji_regex` portion of the regex resolves the issue).

**Comment by amphibian** [comment]
Note that this issue doesn't appear in a regular entry form, as the URL title there is generated via JS, where the pipes are correctly removed.

**Comment by kevincupp** [comment]
Thanks, @amphibian! I like the suggested solution. Altering the emoji regex looks tricky, would need to find a way to say "not these regular character ranges and also not these alternative sequences of characters", which it's trying to do, but misinterpreting that pipe. But if we just replace the pipes with the separator, it'll get sorted out by the separator de-duplicator later. So, I'll make this change. Thanks again!

**Comment by amphibian** [comment]
👍
