### ISSUE TITLE
Ability to center image when performing resize_crop on-the-fly manipulation

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#1049]
The [resize_crop on-the-fly image manipulation](https://docs.expressionengine.com/latest/fieldtypes/file.html#resize_crop) isn't working correctly in that it's not cropping to the center of the image like you get when using regular directory manipulations.  For example:

```<img src="{image_1:resize_crop resize:width='510' resize:height='10000' crop:height='220' crop:maintain_ratio='n'}">```

does resize the image to 510px wide _**then**_ crop to 220px high, but the crop is not vertically centered, eg the top here is the generated image and the bottom is the original:

![image](https://user-images.githubusercontent.com/8193519/116100090-d88f9f00-a669-11eb-96af-82a38a0952bd.png)

On a separate (but related) note, I don't think the 'resize' should require both width and height values - both aren't required in regular directory manipulations.  In my example above, you must specify the `resize:height` parameter otherwise the aspect ratio isn't maintained and the image is stretched to the specified width but keeps the original image's height (even though `resize:maintain_raito` is defaulted to 'yes').  I believe this is also why I have to specify `crop:maintain_ratio='n'` in my example to get the right output since I'm not specifying `crop:width`.  IMO, the behaviors should mirror the regular directory manipulations and we should be able to use something like:

```<img src="{image_1:resize_crop resize:width='510' crop:height='220'>```

to first resize to 510px wide whilst maintaining the aspect ratio, then cropping to 220 tall but vertically centered.

**Comment by intoeetive** [comment]
@pyrobob83 sorry it took so long to get to this!

Looking at our resize_crop docs, I does not look like centering the image is supported. You can specify offset, but you can't really center.

Adding more cababilities for image management is certainly on our roadmap, but for the time being what we did with these new modifiers is that we exposed the functionality that already existed in our image manipulation library to the template tags. We will do more, but that would be larger undertake, so just not happening right now. Qualifying this as feature request for now
