### ISSUE TITLE
EXIF data causing file upload issues on orientation of image

### ISSUE THREAD

**Issue by ataucher** [ExpressionEngine/ExpressionEngine#105]
Images are being rotated on upload to the file manager based on the interpretation of EXIF data on iOS captured images. For instance, the image my appear to be in portrait mode on local computer, but when uploaded to EE, it rotates to landscape because of what’s interpreted from the EXIF data.

Upload an image to file manager that has EXIF data (like in the screenshot provided). Upon upload, notice it automatically rotates it clockwise 90º.

![image003](https://user-images.githubusercontent.com/1093815/51688371-6af3f480-1fc2-11e9-9909-2a08ddd34b55.png)

Environment Details: - Version: [4.3.1] - PHP Version [7.0.33] - MySQL Version [5.6.23] - OS: [macOS] - Web Server: [Apache]

**Comment by kevincupp** [comment]
Sorry for your trouble, that's annoying. But EE doesn't read image EXIF data, it leaves displaying the image up to the browser. Here's a little more on why this happens:

https://www.howtogeek.com/254830/why-your-photos-dont-always-appear-correctly-rotated/

There are JavaScript libraries that could read the EXIF data and fix this in the control panel only, but then you're still left with having to implement a solution on the front-end. I personally always open photos in Preview and re-save them so they appear in the correct orientation everywhere.

**Comment by ataucher** [comment]
Ok thanks for that quick response!
It's tough to explain to a client that has no idea about this. The image looks fine in portrait mode on their computer (as well as mine when testing). But upon uploading, it rotates to landscape. So you're saying this is interpreted by the browser and has nothing to do with EE? I guess the only resolution for them would be to open in Photoshop or something similar and resave it w/out meta data on it.

**Comment by kevincupp** [comment]
Yes, unfortunately, EE just uploads it unaltered and displays it via an `img` tag unaltered, unless you're referring to the generated thumbnails or other image manipulations, in which case PHP is resizing those, and _maybe_ something can be done there, but something would still need to be done to correct the original image on the front-end. You can probably test by manually uploading an image via FTP and then having an HTML file display it. It might vary by browser too, like Safari might be more up-to-date on reading their phones' orientation data.

**Comment by ataucher** [comment]
I see, thanks for the extra clarity on it. I tested the image like you mentioned in Safari ,FF and Chrome and they all had the same result – rotated landscape, not how it is viewed in preview (in portrait). I'll let them know, thank you.

**Comment by kevincupp** [comment]
Sure thing. You can also rotate images via the File Manager if that's helpful, and I think we might have plans to add rotation controls to the publish form, too, so be on the lookout there.
