### ISSUE TITLE
EE Upgrade with Multiple Site Manager- Content Administrators when logging in "You are not authorized to perform this action..."

### ISSUE THREAD

**Issue by melbazany** [ExpressionEngine/ExpressionEngine#1055]
Upgraded from 5.4.2 to 6.0.3. Content Administrators could log into all three of the managed sites and create channel entries. When attempting to log into one of the two 'extra sites' (site IDs of 2 and 3) by toggling the top left navigation option to either of the alternative sites, they're prompted with "You are not authorized to perform this action".

The exp_permissions database table shows 'can_access_cp' for their role_id and site_id, and the only way I've been able to work around is bumping them to an Admin.

Could this be a Member to Role upgrade issue?

**Comment by intoeetive** [comment]
@melbazany are you attempting to switch the site inside CP, or perform "fresh" login in other site's CP URL?

**Comment by melbazany** [comment]
@intoeetive I'm attempting to switch within CP. I'm logged into the 'main' site (id of 1), and then am attempting to switch to the other 'sub-sites' via the top left dropdown menu from within CP.

**Comment by melbazany** [comment]
> @intoeetive I'm attempting to switch within CP. I'm logged into the 'main' site (id of 1), and then am attempting to switch to the other 'sub-sites' via the top left dropdown menu from within CP.

And even if I do log into the CP for the other 'sub-sites', and then attempt to use the dropdown to access the 'main site' (id of 1) which they have the ability to add/edit/etc no problem when they log in directly to that site's CP, they receive the same authorization error message.

**Comment by intoeetive** [comment]
@melbazany it seems that you have already reported this: https://github.com/ExpressionEngine/ExpressionEngine/issues/908 so I'm going to close this issue as duplicate.

The fix has been made, but not released, in https://github.com/ExpressionEngine/ExpressionEngine/pull/992. If you are feeling comfortable to be on 'cutting edge' then feel free to check out that PR and use it.

**Comment by melbazany** [comment]
I guess I did and didn’t mark it in my notes, my apologies. Thanks so much!

Melissa Bazany | Associate Web Developer
Full Circle
616.301.3400 x24

Check out our website at:
thinkfullcircle.com<http://www.thinkfullcircle.com/>

[signature_988511149]


From: Yuri Salimovskiy ***@***.***>
Date: Monday, May 3, 2021 at 8:50 AM
To: ExpressionEngine/ExpressionEngine ***@***.***>
Cc: Melissa Bazany ***@***.***>, Mention ***@***.***>
Subject: Re: [ExpressionEngine/ExpressionEngine] EE Upgrade with Multiple Site Manager- Content Administrators when logging in "You are not authorized to perform this action..." (#1055)

@melbazany<https://github.com/melbazany> it seems that you have already reported this: #908<https://github.com/ExpressionEngine/ExpressionEngine/issues/908> so I'm going to close this issue as duplicate.

The fix has been made, but not released, in #992<https://github.com/ExpressionEngine/ExpressionEngine/pull/992>. If you are feeling comfortable to be on 'cutting edge' then feel free to check out that PR and use it.
