### ISSUE TITLE
CP Entry Manager not retaining sorted columns on pagination links

### ISSUE THREAD

**Issue by maxbato** [ExpressionEngine/ExpressionEngine#1057]
**Description of the problem**
Losing column sort after clicking pagination links in the CP entry manager.

**How To Reproduce**
Go to Entry Manager for channel with more than 25 entries
Sort by any column (i.e. Status)
Click Page 2
Notice your list is no longer sorted

**Environment Details:**
 - Version: [5.4.2]
 - PHP Version [7.4]
 - MySQL Version [5.6.43]
 - OS: [Linux]
 - Web Server: [Apache]

**Possible Solution**
Need to retain the sort paramter within the $link variable when outputting the pagination urls.
The following actually works:
1st sorted url on page 1 (sorted by status):
/system/index.php?/cp/publish/edit&search_in=titles&perpage=25&search=&sort_col=column_status&sort_dir=asc

If i simply append "&page=2" to that url, it works. i.e.:
/system/index.php?/cp/publish/edit&search_in=titles&perpage=25&search=&sort_col=column_status&sort_dir=asc&page=2

Default page2 or any page link url without doing the above is:
/system/index.php?/cp/publish/edit&search_in=titles&perpage=25&search=&sort_col=column_entry_date&sort_dir=desc

See the difference?

Hopefully this is an easy fix?

**Comment by ops-andy** [comment]
Duplicated of #111

**Comment by maxbato** [comment]
This should not be closed. It isnt a duplicate of #111 as that is a feature request of something that got left out of version 2. This issue is a bug clearly if you read the problem.

**Comment by ops-andy** [comment]
ah. I see. thanks. I mis-read that as "sorted columns or pagination links" . The CP not retaining filters has been an overall issue that we've been reviewing.

**Comment by ops-andy** [comment]
@maxbato can you replicate this in the latest version (6.0.3)? I was unable to in my attempts.

**Comment by maxbato** [comment]
Too scared to upgrade to 6 yet. I have custom salesforce stuff going on. I’ll make a 6 sandbox tonight.

**Comment by ops-andy** [comment]
ha. I understand that. 
Please let me know the result of your tests.
Just as a note: at this point, we aren't releasing any more bug fixes or new features for v5, only security updates. So if this is a v5 issue only there will not be a fix from the EE team. However, any community members are welcome to submit PRs for v5 and we'll be happy to review them.

**Comment by maxbato** [comment]
This is fixed on EE 6.0.3. Nice job on the UI btw :)

**Comment by ops-andy** [comment]
since this is resolved in the latest released version. I'm going to close this issue now.
