### ISSUE TITLE
Relationships Field not searching for entries outside initial list of entries

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#1058]
Steps to replicate: 

1. Add a relationship field to any channel
2. Set any limit to Maximum entries (10, for example)
3. Try to relate entry that is not in initial 10 entries in a list

EE version: 6.0.3 build 20210217

**Comment by PaulBaileyAtChan** [comment]
I'm seeing this issue in 6.0.3 also: in the CP, if the list of related entries shown at first is limited in number, the Relate Entry search box appears only to search the initial set of entries, and not all entries in that relationship. This makes all other related entries inaccessible.

**Comment by robinsowell** [comment]
Confirmed.  I'm not sure when that snuck in, it had been an ajax search across records.  Definitely want to get that fixed asap.

**Comment by shbchk** [comment]
Just a reminder, there is another issue with relationship search for entries:

Relationship search doesn't search diacritics https://github.com/ExpressionEngine/ExpressionEngine/issues/1321
