### ISSUE TITLE
EE6 and Multiple sites - can only successfully display one site's pages without 404 at a time

### ISSUE THREAD

**Issue by melbazany** [ExpressionEngine/ExpressionEngine#1063]
![Screen Shot 2021-05-06 at 3 08 38 PM](https://user-images.githubusercontent.com/75503142/117352420-fdabbb00-ae7c-11eb-8dd4-da019eaaa7bb.png)
** I have reported this to EEHarbor... I don't know if it's necessarily an EE issue or a Transcribe module issue. **

I've installed the EEHarbor add-on Transcribe onto an already existing site that has multiple sites enabled. For reference, they are 1. Desktop and 2. Mobile.
 
The issue is this: 
1. When I save out any of my entries on my Desktop site, say the “About” page entry (in Structure), then try and simply go to another page on my Mobile site – say “Contact Us”, I receive a 404 error along with the EE error “The page you requested was not found.” 
2. I’ve been able to resolve this ‘error’ by logging into EE and saving the “Contact Us” entry without actually making any changes. When I try and load the Contact Us page on the mobile site, it loads as expected. 
3. Now, however, if I try and load any page (including the “About”) page on my Desktop site – the OTHER site – I am hit with the 404 error along with the EE error “The page you requested was not found” again.
 
I have a feeling that there’s some overwriting occurring within the database when saving the Mobile site (any entry) and then saving the Desktop site (any entry). It must have to do with the encrypted relationship contents within the database; some sort of overwriting of the base url of the site..
 
I’m running EE 6.0.3 with Structure 4.7.0 and Transcribe 3.6.1. The sites both already existed (utilizing Structure) prior to my installation and integration of the Transcribe module.

See attached screenshot for debugging output.

**Comment by robinsowell** [comment]
Right now I think it's a Transcribe+Structure issue with regard to how Transcribe is calculating the structure URLS.  We'll poke some more and make sure, but I don't think this is EE.

**Comment by melbazany** [comment]
Robin,

I appreciate it. In the case that it is the conflict between the add-ons, would you want me to create a new bug report or would you loop in the necessary folks to have this be addressed?

Thanks again for all of your help.

Melissa Bazany | Associate Web Developer
Full Circle
616.301.3400 x24

Check out our website at:
thinkfullcircle.com<http://www.thinkfullcircle.com/>

[signature_582518759]


From: robinsowell ***@***.***>
Date: Monday, May 10, 2021 at 5:28 PM
To: ExpressionEngine/ExpressionEngine ***@***.***>
Cc: Melissa Bazany ***@***.***>, Author ***@***.***>
Subject: Re: [ExpressionEngine/ExpressionEngine] EE6 and Multiple sites - can only successfully display one site's pages without 404 at a time (#1063)

Right now I think it's a Transcribe+Structure issue with regard to how Transcribe is calculating the structure URLS. We'll poke some more and make sure, but I don't think this is EE.

**Comment by melbazany** [comment]
@robinsowell Any further poking been done on this issue quite yet?

**Comment by robinsowell** [comment]
It's not in EE, it has to do with Transcribe and caching URLs per site.

I've got a bug report in for that and a fix should be in the next release.  For the short term, try turning off structure url caching via config https://eeharbor.com/transcribe/documentation/caching and let's see if that gets it working for you.

**Comment by melbazany** [comment]
> It's not in EE, it has to do with Transcribe and caching URLs per site.
> 
> I've got a bug report in for that and a fix should be in the next release. For the short term, try turning off structure url caching via config https://eeharbor.com/transcribe/documentation/caching and let's see if that gets it working for you.

Right– we do have those caching settings added to our config, and based on your previous changes tested within the /admin/user/addons/transcribe/libraries/Transcribe_structure.php on our site, we seem to be working just fine on our production site to date. Thanks again.

**Comment by robinsowell** [comment]
Glad we got it figured out- it was weird!
