### ISSUE TITLE
Remove "Export Templates" from template options in dropdown.

### ISSUE THREAD

**Issue by ops-andy** [ExpressionEngine/ExpressionEngine#1068]
**Is your feature request related to a problem? Please describe.**
When selecting a template, users are presented with the option to delete the selected template or Export Templates. Export Templates does not make any sense here and is confusing as the export functionality has it's own icon, as of v6, in the top of the Template Manager and exports all templates not just the selected one.

**Describe the solution you'd like**
Remove "Export Templates" from the template options dropdown.

![image](https://user-images.githubusercontent.com/55093827/117690404-d14bb380-b188-11eb-88bc-60b77d22d4f9.png)

**Comment by amazingpitbull** [comment]
This was removed from the Templates screen, but still exists under Template Variables, Partials, and Routes.

**Comment by ops-andy** [comment]
@amazingpitbull that's because exporting individual variables and partials are available via their respective listings. I don't believe Routes have checkboxes/bulk actions as seen in the attached screenshot:
![image](https://user-images.githubusercontent.com/55093827/120498744-783cfd00-c38d-11eb-8620-ecfb433e81f1.png)

**Comment by amazingpitbull** [comment]
Hi @ops-andy 

Sorry, I don't actually have any routes so just added that one in case. 

But export is still on the dropdown for partials and variables when you use the check box - and weirdly, it actually works as it should there. I checked two out of my 8 template variables, and hitting submit downloaded a .zip file with ONLY those two templates in it. 

So now I'm wondering why it didn't work that way on a regular template group listing?  I know you went ahead and removed it from the dropdown, but variables and partials shows that it CAN work as it was intended, there was just something wrong with the code on that page.

**Comment by ops-andy** [comment]
yeah. it's something we can look in to for the future. Since refactoring how that works wasn't on the current list, I'd rather remove something that just doesn't work so that it doesn't continue to confuse users.
