### ISSUE TITLE
EE Website Add-ons section and Licensing tracking update suggestions

### ISSUE THREAD

**Issue by aasun** [ExpressionEngine/ExpressionEngine#1073]
I would LOVE to see some development on the EE site re: add-ons and license management..  

Two main areas: 

1. The add-ons listing page. I'd love to see the current version listed in the summary.  And, since there is a "Recently updated" sort option, how about displaying the date of that current version.   Would make it easier to track for add-ons that I'm watching/waiting.  I'd also like to see the EE version compatibility listed here as little EE4, EE5, EE6 icons, etc.  Sure, you can click the "Compatibility" filter..  But, it still helps to be able to see that info / icon when browsing the lists, as I find that compounding filters (version and category with sort) doesn't always work reliably in Safari.  So, just adding that info for easy "Scan-ability"  would be useful.

2. The account area.  Now that EE is really starting to be a key location to purchase and manage add-on licenses, there needs to be a much better interface built out to support managing add-ons and licenses.  Purchases is fine as just a record of invoices.  But, that shouldn't be the primary interface, in my opinion.  Managing licenses is painful here because it's just a simple list of purchases sorted by date.  I'd like to see a separate "Licenses" page that lists licenses sorted (or grouped) by  add-on name.  Additionally, for active licenses I'd like it to display the current version, and the date of that current version.  And if the license is an annual license, the date started or expiration date for renewal.  Along with quick buttons to "renew" or "upgrade" (if that's available).  Additionally, I think there should be some user-editable notes so we can add in the domain name or other notes for us to help keep track of the use of the license.

As a comparison, I think EE Harbor's site is much closer to what I'd like to see.  Though, even on EE Harbor, I'd like to see the current EE Version compatibility on the home page in the card/info box of each add-on.  The account section, though, on EE Harbor is excellent!  Lists licenses by add-on name, the license key, status and valid until date, the EE Version and download link, as well as notes/domain name for my added tracking.

**Comment by intoeetive** [comment]
Move into internal issue in EE website repo.

Thank you for the ideas, @aasun !
