### ISSUE TITLE
Channel Settings page doesn't correctly preserve the selected default author in some cases with over 100 Members in the site

### ISSUE THREAD

**Issue by CreativePoweredGeek** [ExpressionEngine/ExpressionEngine#1074]
**Description of the problem**
 I discovered this when I was having an issue with a Channel Form on the Front-end of my site.
I have a site with thousands of users.  In the Channel Settings, if I set a specific Default author and save the form everything is fine. However, when I look at the Channel Settings tab again, I do not see the author I set, but rather the first one is selected in the list (presumably of 100).  If I make any other change on that page and save it, then that first member is now set as the default author. 

**How To Reproduce**
on a site with a LOT (over 100) of users:
1. Create a Channel form and place it on the front end of the site
2. Go to the Channel Settings tab for that form and select an author that has access to that Channel and is **NOT** within the default first 100 members shown (THIS IS IMPORTANT)
3. Save the Form
4. Go back & look at the default Author field and you should see that author selected is NOT the one you set, but rather the first one in the list. (It is important to note that as long as the Member you originally selected IS in the First 100, the correct member will be displayed)
5. Make an edit to anything else in the form & save, and that first selected member will NOW be the Default member for that channels entries. 
6. If this member is in a Member Group that DOES NOT have access to the form, your channel group will not display on the front end (Although this is just a side effect of the real issue)

**Error Messages**

<pre><code>

</code></pre>

**Screenshots / Videos / Template Code**
https://drive.google.com/file/d/1u5XgVzk-IN7XgHSFcEawxQ5kUqqWlLdm/view?usp=sharing
In the Video,  Russell Kern is a Super Admin,  all otf the others are members that do NOT have access to that channel.

**Environment Details:**
 - Version: 5.4.2
 - PHP Version 7.4
 - MySQL Version 10.3.29-MariaDB
 - OS: Linux
 - Web Server: Apache

**Possible Solution**

**Additional context**

**Comment by intoeetive** [comment]
This has been fixed in EE6
