### ISSUE TITLE
Members as options

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1080]
**Is your feature request related to a problem? Please describe.**
Last year, I did a website for journalists and they asked me to have more than one author for some articles.

**Describe the solution you'd like**
It would be great to [populate a select field type](https://docs.expressionengine.com/latest/fieldtypes/select.html#populate-from-channel-field) from a members list.

**Describe alternatives you've considered**
Even better, would be to be able to use a field group as members custom fields. Or to have a default pre-created channel for members. Both solutions, I guess, are harder to implement.

**Teachability, Documentation, Adoption, Migration Strategy**
After to choose a path, we can write a documentation / specification.

**Comment by intoeetive** [comment]
This is getting released in EE 7.4.0
