### ISSUE TITLE
Rich Text Editor isn't rendering HTML as entered by user

### ISSUE THREAD

**Issue by andyfoote** [ExpressionEngine/ExpressionEngine#109]
**Description of the problem**
ExpressionEngine 5.1.2. I'm using the Rich Text Editor to paste in some content from an API manual. Due to it being an API manual, the content contains markup to format it correctly - using `<pre>` tags around code blocks and a table. The Rich Text Editor won't render the content correctly - see screenshot for an example.

**How To Reproduce**
1. In a Rich Text Editor field click the 'view code' button (top right hand side of the editor).
2. Paste in the following HTML: `<div id="panel-api-search-request" class="panel-body" style="padding:0;"> <table class="table" style="table-layout: fixed;"> <tbody> <tr style="border-top:1px solid #ddd;"> <th colspan="2">Request</th> </tr> <tr> <td> <pre> GET /search<strong>?token=param&foo/cas=bar&type=baz</strong> HTTP/1.1 Host: https://example.com </pre> </td> <td> <pre> POST /search HTTP/1.1 Host: https://example.com Content-Type: application/x-www-form-urlencoded <strong>{ "token" : param, "foo||bar" : param, "type" : param }</strong></pre> </td> </tr> </tbody> </table></div>`
3. Press Save
4. Observe how the editor shows the content - it is formatted as per the screenshot below. This can't be viewed by the end-user correctly. It is unusable as far as the end-user is concerned. 

**Error Messages**
There are no error messages.

**Screenshots / Videos / Template Code**
<img width="1200" alt="screenshot 2019-01-28 at 11 38 26" src="https://user-images.githubusercontent.com/35595432/51834114-4022dc80-22f1-11e9-84fc-a668b5e96943.png">

**Environment Details:**
 - Version: 5.2.1
 - PHP Version  7.0.33
 - MySQL Version: 5.5.60 MariaDB
 - OS: MacOS
 - Web Server:  CentOS, Apache

**Possible Solution**
Unknown. This is a real problem because users should be able to paste HTML into an editor and still work with it. The HTML used here is valid - it does not contain syntax errors - and therefore this is a problem with how the EE editor is rendering/displaying it. Many CMS's have suffered with this type of problem in the past and it's a real negative as far as users are concerned since if they can't store content as they define in an editor, it's unusable as a CMS platform.

**Additional context**
There seem to be problems in general with the editor where it's modifying markup entered by the user. As a second example paste the following into the 'view code' part of the editor: `<span class="glyphicon glyphicon-star" aria-hidden="true" style="color:#449d44;"></span>`. It will strip the inline style so you get this: `<span class="glyphicon glyphicon-star" aria-hidden="true"></span>`. This is different to what the user has entered. Essentially the editor should leave the markup alone; if users want to save markup in a particular way they should be allowed to do this!

**Comment by kevincupp** [comment]
To be clear, EE is outputting the markup just fine, you just don't like that the control panel CSS is being applied to it. But even if you save it, it's going to strip some of the markup. The RTE is pretty bad for things like this, I'd recommend Wygwam as it tends to leave things alone.

**Comment by andyfoote** [comment]
This seems to be a major downside to EE. In my view there are 2 options:

1. Developers should have the ability to modify the Admin panel CSS and/or editor, in an upgrade-safe way. This means they should be able to provide their own "overrides" to any of the defaults. These should not be overwritten when doing an upgrade. _(As an example, systems like Magento handle this by separating developer and core code into separate files/directories)._

2. The editor needs modifying so that it doesn't manipulate user's HTML. Why should it do that anyway? 

If users are required to buy a paid add-on to replace EE's editor, that really suggests it isn't good enough in the first place.

**Comment by kevincupp** [comment]
>Developers should have the ability to modify the Admin panel CSS and/or editor, in an upgrade-safe way.

They do, you can write an extension to this. But it seems the heavy-duty WYSIWYGs use an iframe to separate styles, that might be more preferable to chasing down CSS selectors.

> The editor needs modifying so that it doesn't manipulate user's HTML. Why should it do that anyway?

I'm not totally sure, I think it tries to do some cleanup of some sort.

> If users are required to buy a paid add-on to replace EE's editor, that really suggests it isn't good enough in the first place.

"Good enough" is subjective. If you need to enter random markup and have it stick, then sure. But if you just need 90% of text formatting needs, it's fine. ExpressionEngine tries to encourage separating data from presentation as much as possible, there could be another way to achieve what you're after.

**Comment by ops-andy** [comment]
With the release of version 6 (currently 6.0.3) we will only be releasing updates and patches for version 5 that are related to the application's security. Since the RTE for v6 was re-written and no longer allows for the editing of the source, I'm closing this issue.
