### ISSUE TITLE
New Field Select - display bug. (v6.0.5)

### ISSUE THREAD

**Issue by liamcrean** [ExpressionEngine/ExpressionEngine#1091]
New Field Select  (choose field type)

Tested in Firefox (running latest on Mac OSX Big Sur) 

_.select__dropdown-item_ Height being inherited from somewhere else 

```
.button__within-dropdown, .dropdown__link, .select__dropdown-item {
height:auto; /* auto not inherit fixes this */
}
```

**Comment by ops-andy** [comment]
confirmed. 
![Peek 2021-05-20 15-56](https://user-images.githubusercontent.com/55093827/119040927-fc51b680-b983-11eb-8eec-d1f7b7e7f861.gif)
