### ISSUE TITLE
[EEv6.0.6] Mislabeled Category radio button in Channel Settings when Channel Duplicated.

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#1098]
<img width="299" alt="Screen Shot 2021-05-22 at 1 25 36 PM" src="https://user-images.githubusercontent.com/6145078/119241195-85dec100-bb09-11eb-83a3-35e76201f83b.png">

1. Create a new channel
2. Under the Channel tab, Duplicate an existing channel.
3. Under the Categories tab, choose a group with more than one existing category 
4. Hit Save
5. Now look under the Settings tab and scroll down to "Category assigned to all new entries in this channel."

The first option should be labeled "None" but it shows "Plain Text" instead.

6. Hit Save and Close and it went back to "None". Glad I got a screenshot of it or you would never believe I actually saw it.

**Comment by intoeetive** [comment]
I'm not replicating this in latest `6.dev` codebase (and I also have a feeling that we have seen this issue before and got it fixed, but I can't find relevant code changes)

Keeping this open until someone is able to replicate
