### ISSUE TITLE
[EEv6.0.6] File Menu Width Remains Too Narrow

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#1099]
Related to / follow up on: https://github.com/ExpressionEngine/ExpressionEngine/issues/709

<img width="980" alt="Screen Shot 2021-05-22 at 2 51 27 PM" src="https://user-images.githubusercontent.com/6145078/119241747-9e50da80-bb0d-11eb-9d69-bec4da255dd9.png">

From left-to-right in the image above are EE v6.0.6 - v6.0.0 - v3.x.x

We appreciate that the line-wrap issue has been corrected in the latest build of EE, but for many of my clients that work in complex industries like health care, EE's new file menus are still falling short of the mark. 

The older file menu styling worked much better as it allowed for file directories with longer names. EE v6.x.x, so far at least, has made publishing files into the correct directories a major pain point for several of my clients over the last five months since we upgraded clients into EE v6. Even with the corrected linewrap, these file menus are not working for my clients.

Could we adopt the menu-width strategy of the old UI, that allowed more width so there was less line wrapping?

Many of my clients have been waiting months now for the "fix" that was just released and when we saw it, our hearts sank.

Below is a screenshot showing what one of my client's file directory lists looks like. Now try to imagine scrolling through that in the current file menu within the file upload modal. 

<img width="212" alt="Screen Shot 2021-05-22 at 2 49 25 PM" src="https://user-images.githubusercontent.com/6145078/119241760-b32d6e00-bb0d-11eb-80c9-710e9900af0f.png">

Thanks for listening and for anything you can do to help me make EE work as good as it used to for my larger clients.

- Kurt

**Comment by TomJaeger** [comment]
@PDXMan1 Any updated thoughts on this in V7?

**Comment by PDXMan1** [comment]
In v7.2.12 It looks like a "search field" has been roughed in, but it's not labeled, and it's nonfunctional (either automatically, or by pressing return). The scroll feature within the menu isn't immediately apparent to some of my newer clients who don't realize there are more options in the list. Also, the right-angle brackets are displayed as HTML characters.

The client whose site I used as an example in the original post from a couple of years ago left us, partially because they got tired of waiting for things like this that they use several times a day to get resolved.

The file selection modal that's used from the publish page still needs some work. 

<img width="295" alt="Screenshot 2023-03-28 at 8 41 15 AM" src="https://user-images.githubusercontent.com/6145078/228293073-5aa73031-c7fe-42d6-8d1d-eb2afdb7f713.png">

**Comment by Yulyaswan** [comment]
`the right-angle brackets are displayed as HTML characters` fixed here #3027

**Comment by PDXMan1** [comment]
THANK YOU! for fixing this one for us Yulyaswan. Just tried it out and its working great!
