### ISSUE TITLE
[EEv6.0.6] Grid Field > Copy Field > not including Formatting Buttons

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#1100]
<img width="299" alt="Screen Shot 2021-05-23 at 2 10 11 PM" src="https://user-images.githubusercontent.com/6145078/119276801-f4d31d00-bbd0-11eb-89c1-5418086ee152.png">

While setting up a new, or adding to an existing, grid field, under Field Tools, the Show Formatting Buttons check-box value is not getting passed to a copied/duplicated field. All other values appear to be copied as expected.

**Comment by mcfarlandonline** [comment]
+1
