### ISSUE TITLE
No such property: 'logger' on ExpressionEngine\Legacy\Facade

### ISSUE THREAD

**Issue by DalizPR** [ExpressionEngine/ExpressionEngine#1104]
After updating to 6.0.2 -> 6.0.6 running PHP 8.0.2

I get an error page with te message

InvalidArgumentException Caught
No such property: 'logger' on ExpressionEngine\Legacy\Facade
Facade.php:128

This wil happen after a member changes some member-data like changing a password natively or a some Visitor custom fields.
It won't occur when user us Super Admin 

Template code for User Reset Password

`{exp:member:reset_password_form
            return="inloggen"}
                                
                  <div class="form-group ">
                    <div class="input-group">
                        <div class="input-group-addon"><i class="fa fa-key"></i></div>
                        <input  type="password" name="password" value="" placeholder="nieuw wachtwoord" class="form-control">
                          </div>
                </div>
                
                
                <div class="form-group ">
                  <div class="input-group">
                      <div class="input-group-addon"><i class="fa fa-key"></i></div>
                      <input  type="password" name="password_confirm"  value="" placeholder="herhaal nieuw wachtwoord" class="form-control">
                
                  </div>
              </div>
                  
             <div class="form-group ">
             <input type="submit" name="submit" value="Verander mijn wachtwoord" class=" btn-success btn-block">
              </div>
    
      {/exp:member:reset_password_form}`

**Comment by intoeetive** [comment]
I can't point to the exact changelog record, but we had this fixed a while ago
