### ISSUE TITLE
Discussion Login Form Validation Issues

### ISSUE THREAD

**Issue by VarenSwaab** [ExpressionEngine/ExpressionEngine#1106]
The login form for the discussion forum add-on appears to be hardwired to allow only 6 characters despite the minimum user name setting being set to 5 characters. So EE will allow someone to create an account with the name Roger but the forum login form won't ever allow them to login because it's validator only accepts 6 or more characters.

In a very similar nature, the same form won't allow email addresses to be used as user names. Several modules, including Solspaces' User allow members to use email addresses for user names. So if a member were to use their email address they would never be allowed to login into the discussion form. 

Pics below:

<img width="504" alt="Screen Shot 2021-05-24 at 11 24 01" src="https://user-images.githubusercontent.com/5083862/119390985-a4b49300-bc82-11eb-925e-3dd86abf1db0.png">

<img width="511" alt="Screen Shot 2021-05-24 at 11 23 47" src="https://user-images.githubusercontent.com/5083862/119390988-a54d2980-bc82-11eb-9b66-adc00da61f3d.png">

Using: 

EE 6.06
PHP 7.3

**Comment by intoeetive** [comment]
I am unable to find similar validation messages inside EE. My suspection is that you have custom validation script connected to this page
