### ISSUE TITLE
Login Errors in Forum

### ISSUE THREAD

**Issue by VarenSwaab** [ExpressionEngine/ExpressionEngine#1107]
Upon login using the discussion forum login form I get the following errors. These errors show even if error reporting is off. (EE 6.06, php 7.3, mySQL 5.0.12)

https://***.***/forums/member/login/

Exception Caught

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'in_forum' in 'field list':
UPDATE `proa_online_users` SET `member_id` = 4, `name` = 0, `ip_address` = '24.113.10.68', `in_forum` = 'y', `date` = 1621881031, `anon` = 'y', `site_id` = 1 WHERE `ip_address` = '888.999.333.222' AND `member_id` = 4

ee/legacy/database/drivers/mysqli/mysqli_connection.php:114

Stack Trace: Please include when reporting this error

#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('UPDATE `proa_on...')
#1 ee/legacy/database/DB_driver.php(260): CI_DB_mysqli_driver->_execute('UPDATE `proa_on...')
#2 ee/legacy/database/DB_driver.php(175): CI_DB_driver->simple_query('UPDATE `proa_on...')
#3 ee/legacy/database/DB_active_rec.php(1382): CI_DB_driver->query('UPDATE `proa_on...')
#4 ee/ExpressionEngine/Addons/member/mod.member_auth.php(416): CI_DB_active_record->update('online_users', Array)
#5 ee/ExpressionEngine/Addons/member/mod.member_auth.php(272): Member_auth->_update_online_user_stats()
#6 ee/ExpressionEngine/Addons/member/mod.member_auth.php(155): Member_auth->_do_auth('user', '***********...')
#7 ee/ExpressionEngine/Addons/member/mod.member.php(883): Member_auth->member_login()
#8 ee/legacy/libraries/Actions.php(175): Member->member_login()
#9 ee/legacy/libraries/Core.php(522): EE_Actions->__construct(true, Object(Closure))
#10 ee/legacy/controllers/ee.php(51): EE_Core->generate_action(true)
#11 [internal function]: EE->index()
#12 ee/ExpressionEngine/Core/Core.php(251): call_user_func_array(Array, Array)
#13 ee/ExpressionEngine/Core/Core.php(111): ExpressionEngine\Core\Core->runController(Array)
#14 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#15 index.php(164): require_once('...')
#15 index.php(164): require_once('...')

**Comment by intoeetive** [comment]
It looks like DB table is corrupt. `in_forum` column should exist in `online_users` table.

It is declared like this: 
> in_forum char(1) NOT NULL default 'n',
