### ISSUE TITLE
resize & webp on-the-fly image manipulations do not respect maintain_ratio parameter

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#1108]
Was hard to test this until worked out that the webp manipulation was getting duped by presence of other file manipulations (which is issue #854).

If you clear the existing manipulations and delete the webp / _thumb and /_manipulation directories from the folder storing the image, and then try a webp on-the-fly manipulation with just a width or height specified, the image is distorted to deliver an image with the nominated axis changed, but the length of the other axis unchanged.

This should not happen - the [documentation](https://docs.expressionengine.com/latest/fieldtypes/file.html#webp) indicates that 'maintain_ratio' default is to 'y' (i.e. the image ratio should be maintained through the transform).

Explicitly setting the `maintain_ratio` parameter does not affect the outcome.

e.g for an original image with dimensions 3000x1307

```{primary_image:webp height='1090' maintain_ratio='yes'}``` gives an image with dimensions 3000x1090
```{primary_image:webp height='2500' maintain_ratio="yes" master_dim='width'}``` gives an image with dimensions 2500x1307

Checked and get similar results if I replace the `:webp` maniuplation with `:resize`.

EE6.0.6

**Comment by intoeetive** [comment]
The image library that EE relies on is requiring both width and height, so the docs were wrong on that part - however I completely see the case when you care only about one dimention and want to completely ignore the other one, so added support for that. `master_dim` would be required to set to something that's not `auto` in case if one of dimentions is skipped though
