### ISSUE TITLE
Entry Manager should return to same filter/pagination settings on Save & Close

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#111]
**Is your feature request related to a problem? Please describe.**
When using the Entry Manager to edit each of a filtered set of entries, because the EM doesn't retain most of the filter settings on Save & Close, filtering/pagination must be recreated each time, increasing the time taken for the task, making it harder to track progress, and therefore increasing the chance of errors.

Other than the channel filter, which is retained on Save & Close (and which is *added* as a filter if it wasn't already there), other filters and pagination settings are discarded.

**Describe the solution you'd like**
The Entry Manager should retain all filter/pagination settings on Save & Close, returning the user to the same page of results, and the same entry filtering.

**Describe alternatives you've considered**
An alternative to retaining filter/pagination settings on Save & Close by default would be to provide an alternate version of Save & Close — perhaps "Save & Return".

**Comment by ic360-com** [comment]
My clients have a big need for this one. Some of them are managing hundreds of Product entries, so having to re-filter the list each time is painful!
It worked well in EE2, so please bring back.

**Comment by adster101** [comment]
:+1:

**Comment by paulcripps** [comment]
+1

**Comment by creativearc-paul** [comment]
👍

**Comment by bsrweb** [comment]
+1 Having this feature back would be really nice.
