### ISSUE TITLE
Newly added Fluid Field children cannot see field_data_id on Entry Save

### ISSUE THREAD

**Issue by RK311y** [ExpressionEngine/ExpressionEngine#1113]
## Problem Overview

The `Fluid Field` Fieldtype ([ft.fluid_field.php](https://github.com/ExpressionEngine/ExpressionEngine/blob/1b28b8572ea479b7a5d0a282da4e664be3eb3849/system/ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php)) is currently saving its child fields before adequately updating necessary information in the database. To successfully identify a `Fluid Field`'s child field, certain information is necessary. The most crucial being `field_data_id` in the `exp_fluid_field_data` table.

### Getting Specific

When a child of a `Fluid Field` is saved, the parent field invokes `save($data)` and `post_save($data)` on each of its children. Information about the child's parent is exposed in the child field's settings (`$this->settings['fluid_field_data_id']`).

The `fluid_field_data_id` is used to identify the corresponding row in the `exp_fluid_field_data` table. But what if we wanted to know more about the current child field? How would we identify the location in which the current child field's data is being saved? 

Using the `fluid_field_data_id`, we could look up the `field_data_id` from the `exp_fluid_field_data` table. This would provide us with the primary key of the row in the current child field's table.

Something like:
![ChannelField-FluidField-ER](https://user-images.githubusercontent.com/65210753/120263693-74a85980-c259-11eb-83f7-11687052e899.png)

_Note_: We are after the `id` in `exp_channel_data_field_#`.

Here's the problem. The `field_data_id` for a new row in a `Fluid Field` is not updated until after `save()` and `post_save()` are called on the child field. This means that a new child field has no way of knowing the unique row it will be saved in.

Typically this is not an issue for standard channel fields because only one row is used per entry in a `exp_channel_data_field_#` table. Therefore, the `entry_id` can be used to locate it's corresponding row. However, the `entry_id` for `Fluid Field` children is 0.

### Real World Discovery

I am creating a custom field. The custom field adds a few columns in the `exp_channel_data_field_#` table. To appropriately save data to these columns, it needs to know where to save it. Whithout the `field_data_id`, this is not possible for `Fluid Field` children.

## How to Reproduce

I have a few options for you.

### Option 1

- **Addon One** : [test.zip](https://github.com/ExpressionEngine/ExpressionEngine/files/6573371/test.zip)
  - Takes a few less clicks to see what I see.
  -  Upon installation, a new Channel ("TEST Channel") will be created and a `Fluid Field` will be added with the custom field as a child
  - Will delete the channel and fields unpon uninstall
- **Addon Two**: [test.zip](https://github.com/ExpressionEngine/ExpressionEngine/files/6573311/test.zip)
  - Has _only_ the custom field, you will have to add it to a fluid field

**Note**: Go to the `test` addon's controller page in the CP to view the log.
Simply, some text info is saved in cache after a channel entry is saved and the cached data is displayed on the index page of the controller.

You are looking at the `field_data_id`.

### Option 2

1. Create a custom field
2. Add the custom field to a fluid field
3. Monitor and log database values when custom field is saved: `save($data)` and `post_save($data)`
4. Confirm you see what I see

### Option 3

Trust me, I've looked into it.

## Environment Details

 - Version: 6.0.6 - but I originally had this issue in v5
 - PHP Version: 7.4
 - MySQL Version: 8.0.25-0ubuntu0.20.04.1 for Linux on x86_64
 - OS: Ubuntu
 - Web Server: Apache

## Possible Solution

Considering that we are talking about new rows to the Fluid Field, it would depend on whether: We want the `field_data_id` available for `save()` and `post_save()` or just `post_save()`.

I have make a commit on my own forked branch, [HERE](https://github.com/RK311y/ExpressionEngine/commit/bd97a4fd45cee659ec8709d5a19140fc4630ad6b), but I have not created a pull request because I am only somewhat familiar with how fields become related on the facade. I was hoping someone would double check this would not break anything. As far as I can tell, it works.

**Comment by intoeetive** [comment]
Sorry there has been no response on this issue since 2021 :(

I feel like it's not relevant anymore - we currently have `fluid_field_update_field` and `fluid_field_add_field` extension hooks that are likely closing the gap
