### ISSUE TITLE
Wide tables overflow in entries

### ISSUE THREAD

**Issue by blairliikala** [ExpressionEngine/ExpressionEngine#1114]
Tables that become too wide for the container should show a horizontal scroll bar, however if they are a child of a **fieldset** element, they will spill-out of their container, and not flip to a scroll bar.

EE v6.06

**To quickly reproduce:**
1. Create a grid field with a few columns.
2. Open devtools and change the parent div element (class=grid-field, id=field_id_xxx) to fieldset.
3. Shrink the browser window.

The more practical problem is for add-ons that use tables since they are contained in a fieldset.

1. Create a custom field.
2. Add the table markup:
```
<div class="table-responsive table-responsive--collapsible">
    <table>
       <!-- add a few columns -->
     </table>
</div>
```
3. Shrink the browser window.

**Suggested solution:**
Why exactly that is, I'm not sure, but found a solution.  Add display:contents to remove fieldset from the box model.
```
fieldset {
  display:contents;
}
```
However this will adjust styling in other forms, probably in a less preferred way.

**Comment by Yulyaswan** [comment]
this is not an issue anymore after we added options for different display layouts (for both versions 6 and 7). if grid doesn't `the fields within the grid will be placed in a horizontal row on bigger screens, and stacked vertically on smaller screens or when there is not enough space on the page.`
https://docs.expressionengine.com/latest/fieldtypes/grid.html#grid-layout
