### ISSUE TITLE
Entry not searchable unless saved

### ISSUE THREAD

**Issue by giganticdesign** [ExpressionEngine/ExpressionEngine#112]
**Description of the problem**

**Quick Description.** Entries added via Datagrab have a grid field that is not being indexed in search. You have to go into that entry and Save it for the those grid fields to be search parameter on achannel entries tag.

Entries added to Expression Engine via Datagrab. Those entries have a grid field for photos.

When we use the Channel Entries Tag search parameter... **{exp:channel:entries channel="mychannel" search:images_grid_field="not IS_EMPTY"}**

Entries will not show up unless they are actually "saved" in Expression Engine entry detail page.

**Environment Details:**
 - Version: [e.g. 5.1.3]

**Comment by kevincupp** [comment]
Sorry for your trouble. We would consider this a bug in Datagrab though, it should be conforming to the data structure for searchable data if it's going to be subverting our APIs and inserting raw data on its own. We have a search re-indexing utility slated for EE6 though that should help with these sorts of problems, though.

**Comment by giganticdesign** [comment]
Kevin,
Is there anything I can do on my end to get those added back into the searchable data? I've checked the docs and can't find anything documentation speaking on that.

Any insight you have is much appreciated! I am following up with datagrab as well.

Thanks!

**Comment by kevincupp** [comment]
Nothing convenient until EE6 comes out, unfortunately. If you're savvy with PHP scripts or similar automation, you basically need to select all the searchable columns' data for each entry out of the `channel_grid_field_x` tables and then implode them into a pipe-delimited list, then put that into the Grid field's `field_id_x` column in either the `channel_data` table or the Grid's `channel_data_field_x` table, whichever it has. And of course put the data with the appropriate entry ID.
