### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by yiodranis** [ExpressionEngine/ExpressionEngine#1126]
Hi all. I have update some sites from ver 1 or 2 to the latest versions with no problem. This morning I notice that when I update the php to ver 7.3 or 7.4 the site is not working. I am getting blank page and I can not even login to my admin.

If I use PHP Version 5.6.38 it is working superfine…..

So please tell me if there is a solution for that.

In some casesI get:

Exception Caught

There was a database connection error or a problem with a query. Log in as a super admin or enable debugging for more information.

mysqli_connection.php:114

**Comment by omejelle** [comment]
I think toy have to enable mysqli or pdo_mysqli or something similar

**Comment by yiodranis** [comment]
Thanks omejelle  for that, but no luck. They are enabled

**Comment by yiodranis** [comment]
While reviewing the issue, I found that The database password and the password in config.php were different for some reason. I have reset the password for the database  and now your website is loading fine.
