### ISSUE TITLE
Add a true numeric field as an option for channel entries to enable numeric sorting

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#1127]
**Is your feature request related to a problem? Please describe.**
Currently numeric fields are stored as `TEXT` fields with [an over-ride](https://docs.expressionengine.com/latest/fieldtypes/text.html#allowed-content) to limit content to a type of numeric value.  As a result when the field is used to sort values in a channel entries tag the output is sorted alphanumerically (e.g. 1, 11, 12... 2, 20, 21... ) not numerically (1, 2, 3...).

This issue appears to be driven by how the field is stored in the MySQL database - such entries being given type TEXT in the database.

**Describe the solution you'd like**
There is an informal fix to this - which is to cast the sort field as an EE date field (which gets coded in MySQL as an INT field) and sort on that.  A better solution would be to add a new field type ("true integer"??) that allows the definition of an integer field via the EE Field CP panel which then would be created as MySQL INT type field.  This new EE field type could co-exist along side the current TEXT with constraints option.

**Describe alternatives you've considered**
It works if you change the MySQL type of a TEXT+constraint variable in MySQL directly - but this is not easy for average users to do, and runs risk of breaking if EE does an update to the database structure.

**Teachability, Documentation, Adoption, Migration Strategy**
How this works would be dependent on fix chosen, but if it is simply adding one more option to the choices for a new field then documentation / accessability to new users should be fairly simple.

- [x ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by litzinger** [comment]
I'm pretty sure it already sets the column type to INT. I have code in Publisher specifically to look for this change and to keep them in sync with the native tables. I just made a new custom field and it makes it an INT column type.

![Screen Shot 2021-06-08 at 8 01 23 AM](https://user-images.githubusercontent.com/53965/121189448-bd4eac80-c82f-11eb-936b-bbd4da4c298b.png)
![Screen Shot 2021-06-08 at 8 00 32 AM](https://user-images.githubusercontent.com/53965/121189466-c0e23380-c82f-11eb-9038-cc508b43e2d2.png)

**Comment by jcogs-design** [comment]
Interesting, and helpful - then it would appear that if you have a text field that is not set to Integer initially and then change it, the MySQL type is not updated.

**Comment by litzinger** [comment]
I don't think that is true either. I just edited this same field, changed it to All context type, and it was changed to TEXT. I changed it back to Integer type, and the column type is now INT again. I think this is working as expected.

**Comment by jcogs-design** [comment]
Hmm.  OK - do you think it might have been fixed in EE6 update - I was using an EE 5 site for this and it certainly wasn't working then...  or maybe it doesn't do the change if there is content already in the field?

**Comment by litzinger** [comment]
I added support for this in Publisher back in EE3... so it's been like this for awhile :)

If it's not working for you in an existing environment for some reason, I'd setup a new/fresh EE install and see if it works there. And if it works in the new/fresh install, then there might be something happening in your existing env. If it doesn't work in the new/fresh install, then it could be worth reporting a bug.

**Comment by jcogs-design** [comment]
OK - I'll do some more digging on the problem site and file it as a bug if the behavour persists.
