### ISSUE TITLE
When paginating in Entry Manager a fieldtype's save_settings method is called

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#1129]
EE 6.0.6, PHP 7.0 (I know...)

We encountered something that is very strange when paginating entries in the new Entry Manger. The `save_settings` method is called on a custom fieldtype file. This seems to be an odd place to call `save_settings`, and of course our code is failing because it is a GET request, not a POST request, which causes the pagination to fail without any visible errors (the next page of entries just is not displayed to the user and it never advances to the next page).

If I add `public $entry_manager_compatible = false;` to the ft file, this does not happen. I was under the assumption that entry manager compatibility was opt-in, not opt-out? Regardless of the opt-in/out scenario... it's calling a method that it shouldn't be calling.

![entry-manager-pagination](https://user-images.githubusercontent.com/53965/121234871-ceacae80-c859-11eb-8233-8d7bf04d4b53.png)

![confused](https://user-images.githubusercontent.com/53965/121235250-44b11580-c85a-11eb-9c46-7af1835a24ae.jpg)

**Comment by intoeetive** [comment]
@litzinger thanks for reporting, that was a tricky one to manage!
