### ISSUE TITLE
Date Format setting not working

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#1133]
I have just updated an MSM site from EE5.4.0 to EE6.06

I have the Date Format set to dd/mm/yyyy but this isn't being honoured when listing Entries or when viewing the Entry Date when editing an Entry.

**Comment by intoeetive** [comment]
I haven't been able to replicate this.

Is the date formatting preference set globally ot per user? If it's globally, then via CP or config file?

Is it just the secondary site that has the date formatting wrong, or all sites?

**Comment by ic360-com** [comment]
OK I think I have found the problem.
The overall system date format was set to dd/mm/yyyy but my own Member Date & Time Settings was set to mm/dd/yyyy ("Use site default" switched off).
So, it was my own fault, sorry.

In this case, I wonder if it might be worth adding a note and link, from the System Date/Time Settings in the CP, to say something like:
"You can also set Date/Time display preferences per Member"
and then link to here:
/system/index.php?/cp/members/profile/date&id=<currently logged in member id>

Just a thought.
Thanks for your time.  :-)
