### ISSUE TITLE
Setting cookie_secure to y in site confirm generates no cookies.

### ISSUE THREAD

**Issue by iammattmartin** [ExpressionEngine/ExpressionEngine#1135]
Debugging https://expressionengine.com/forums/topic/253095/secure-cookies-form-failures more, it appears the reason this may be failing as that no cookies are being set.

When the option is set as per the configuration:
```
 $assign_to_config['cookie_secure'] = 'y';
```

No cookie appears. Even if we assume that option can't be set per site, like it can for cookie_sameside or cookie_prefix, setting globally also causes the issue.

I have removed all cookies for the site when that was not enabled (i.e insecure). Reloaded the page and nothing is generated. I set back to n (by removing the line) and cookies immediately appear.

Nginx, EE 6.0.6 (although happened before), PHP 7.4, MariaDB 10, Ubuntu 18.

**Comment by intoeetive** [comment]
@iammattmartin I wasn't able to replicate this on the latest code in `6.dev` branch.
What are the other cookie/session related config values that you have? I wonder if that's specific combination of those that is causing the issue

**Comment by iammattmartin** [comment]
All the ones we've set per site as below.

```
 $assign_to_config['site_name']  = 'msm-name';
 $assign_to_config['cp_url'] = 'https://site-address/admin.php';
 $assign_to_config['site_url'] = 'https://msm-site-address';
 $assign_to_config['cookie_domain']  = 'msm-site-address';
 $assign_to_config['cookie_prefix']  = 'xy_';
 $assign_to_config['cookie_samesite']  = 'Strict';
 $assign_to_config['cookie_secure'] = 'n';
```

I'll test again on a new install of the dev instead of just changing our existing base and will see if this changes at all.

**Comment by iammattmartin** [comment]
Obviously setting `cookie_secure` to `y` causes it to not generate cookies at all.

**Comment by intoeetive** [comment]
Thank you, knowing that this is MSM site is really important! Does this happen with all MSM sites, or just the non-primary ones?

**Comment by iammattmartin** [comment]
We don't use the primary hostname for a site (it's just an internal name for accessing EE).

I will do some further testing though.

**Comment by iammattmartin** [comment]
@intoeetive I can confirm the main site does generate cookies in line with the `cookie_secure` setting.

Only when on an MSM site does it seem to cause issues with set to `y` either via the config option per site, or via the GUI.

`n` or off in GUI generates insecure cookies as expected.

**Comment by intoeetive** [comment]
@iammattmartin would you be able to run this PHP code on your MSM site and let me know what it returns?
```
<?php
var_dump($_SERVER['HTTPS']);
?>
```

**Comment by iammattmartin** [comment]
OK this makes a bit more sense now now I know what it is looking for.

Our normal sites are behind a proxy/load balancer which does the SSL termination and passes that data to the local host which isn't SSL'd.

So that script returns `NULL`, but was returning `string(2) "on"` when tested on the root/main site as that does not go via that device.

Is there a way to better handle this as I am sure we won't be the only ones using a similar setup and there isn't any need to enable https on the backend site but we still want to use the secure cookies.

**Comment by intoeetive** [comment]
How about these two? `$_SERVER['REQUEST_SCHEME']` and `$_SERVER['HTTP_X_FORWARDED_PROTO']`
Does any of those return `true`?

**Comment by iammattmartin** [comment]
OK this makes a bit more sense now now I know what it is looking for.

Both sites sit behind a nginx LB/proxy. 

On the main EE admin site we have `fastcgi_param   HTTPS   on;` set but not on the others, so that will account for what is happening.

Although maybe there is a better way to handle the secure cookie generation generally for such proxy setups.

I will test further.

(deleted earlier comment as needed to correct the statement)

**Comment by iammattmartin** [comment]
@intoeetive It appears that adding the hard-set https param has "fixed" this.

Let me know if you need the output to `$_SERVER['REQUEST_SCHEME']` and `$_SERVER['HTTP_X_FORWARDED_PROTO']`?

I wonder if there is any form of error/warning you can add for a site where EE believes it is non-https and `cookie_secure` is set to `y`?

**Comment by intoeetive** [comment]
@iammattmartin yes I would like to see output of those. In general we have more modern code relying on those variables that should work, I just wonder what are the values for you?

**Comment by iammattmartin** [comment]
Sure.

On a site that I have not yet changed:

```
string(4) "http"
string(4) "http"
NULL 
```

and on a site that I have which works

```
string(4) "http"
string(4) "http"
string(2) "on" 
```

It looks like we're not setting those, so will review.

**Comment by intoeetive** [comment]
So seems like the update I pushed will not work for you :(
Let me know if you're setting some other $_SERVER variable that we can check - we'll consider adding that into core functions

**Comment by iammattmartin** [comment]
I think it is.

We are now seeing a secure cookie being generated when before there wasn't one at all. We only saw insecure cookies even when `cookie_secure` was set to `y`.

**Comment by iammattmartin** [comment]
Form submission also appears to now work, which it didn't when it was set to `y`.

It won't help given what the changes do. I will see what other ways there are to pass the protocol through although setting the `fastcgi_param   HTTPS   on;` will work with the original code.

**Comment by iammattmartin** [comment]
Maybe just to conclude this, we are also able to set HTTP_X_FORWARDED_PROTO easily, so have set both now. 

I'll leave this open if you want to consider a better way to do this, or even just a warning in the UI, or log when EE detects it is set but isn't able to find the header confirming it.

**Comment by intoeetive** [comment]
So generally this is the matter of server configuration. Despite the code change suggested might be good, it still reqiures that the server sets ar least one variable to indicate that https is supported

I'll keep the issue open for now until we either just merge the change or find a better solution

**Comment by dgowing95** [comment]
Just wanted to add a similar issue we're having on one of our sites. We're using Cloudflare followed by https termination at an AWS load balancer, the traffic is then http between the load balancer and the webservers behind it.

Setting cookie_secure to 'y' stops cookies being set, and then we're unable to submit forms or login to the control panel.

The output of 
```
<?php
var_dump($_SERVER['HTTPS']);
var_dump($_SERVER['REQUEST_SCHEME']);
var_dump($_SERVER['HTTP_X_FORWARDED_PROTO']);
?>
```

is: 
```
undefined index: HTTPS
"http"
"https"
```

From a bit of digging it looks like the _set_cookie function, around line 200 of system/ee/legacy/core/input.php may be responsible?
```
        if ($data['secure_cookie']) {
            $req = isset($_SERVER['HTTPS']) ? $_SERVER['HTTPS'] : false;

            if (!$req || $req === 'off') {
                return false;
            }
        }
```

Would it be possible to add an additional check for https in $_SERVER['HTTP_X_FORWARDED_PROTO'] before returning false?

**Comment by iammattmartin** [comment]
You might be able to create a workaround ahead of any code changes with [header transformations](https://blog.cloudflare.com/transform-http-request-headers/) at CF?

**Comment by intoeetive** [comment]
@dgowing95 looks like the fix I published above will work for you. We will also include into into one of future releases
