### ISSUE TITLE
{encode} function not working?

### ISSUE THREAD

**Issue by karlosb** [ExpressionEngine/ExpressionEngine#1137]
Seem to be having issues with the `{encode}` function in EE6? For example I have the following `{encode="joe@bloggs.com" title="joe@bloggs.com"}` and I get a template output of: `<span data-eeencemail_mztfwqhwwo="1"><a href="mailto:joe@bloggs.com">joe@bloggs.com</a></span>` . I’m pretty sure the ‘joe@bloggs.com ’ part of that output should be encrypted in the template html output? I’ve noticed this now on several ee6.x sites that I have running.

**Comment by jcogs-design** [comment]
Just to confirm that I've tried this on an EE6 site and get identical results.
On an EE5 site it also does not work - the output of the tag `{encode="joe@bloggs.com" title="joe@bloggs.com"}` being: 
```
<span data-eeencemail_xdshepzfcd="1">
    <a href="mailto:joe@bloggs.com">joe@bloggs.com</a>
</span>
<script>
    /*<![CDATA[*/var out = '',el = document.getElementsByTagName('span'),l = ['>','a','/','<',' 109',' 111',' 99',' 46',' 115',' 103',' 103',' 111',' 108',' 98',' 64',' 101',' 111',' 106','>','\"',' 109',' 111',' 99',' 46',' 115',' 103',' 103',' 111',' 108',' 98',' 64',' 101',' 111',' 106',':','o','t','l','i','a','m','\"','=','f','e','r','h','a ','<'],i = l.length,j = el.length;while (--i >= 0)out += unescape(l[i].replace(/^\s\s*/, '&#'));while (--j >= 0)if (el[j].getAttribute('data-eeEncEmail_xdsHePZfcD'))el[j].innerHTML = out;/*]]>*/
</script>
```
Which I think is functionally identical to the broken output produced by EE6.

**Comment by geoffcowan** [comment]
This all lurking some fairly old code `system/ee/legacy/Typography.php`  -- `public function encode_email($email, $title = '', $anchor = true)`

**Comment by obfuscode** [comment]
Make sure you're viewing the actual source of the page. If you're viewing it through the Developer Console, it is most likely being rendered to display there. This screenshot is what I see using your code in EE 6.0.4 in both the console and raw source view in Chrome latest; do you see the same thing?

![image](https://user-images.githubusercontent.com/2160089/122081423-150b8b80-cdcd-11eb-91c8-fe5090527f5b.png)

**Comment by karlosb** [comment]
Just to re-confirm I was getting the same output as @jcogs-design but... this morning when I re-checked I get the correct encryopted output as @obfuscode's above! In all instances I have been checking the acutal browser 'view source' output and **not** the browser code inspector. Really strange!

**Comment by intoeetive** [comment]
Since this looks like not an issue with EE, but misuse of browser code inspector, closing this out. Please reopen, if you spot the issue when using "view source"
