### ISSUE TITLE
Homonymous templates of different types

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1143]
Hi!

I just discovered that homonymous templates of different types don't get recognized by the template parser neither show on control panel. Some samples I tested:

- `main.css` and `main.js`
- `index.css`, `index.js` and `index.html`

The first one to be created is recognized on the control panel and the `.html` is used by the template parser.

Running on Docker:

- PHP Version 7.4.20
- redis:6.2 (unused)
- mariadb:10.5.10
- nginx
- apache

Thank you!

**Comment by intoeetive** [comment]
I think we will need to call it limitation and not a bug.

If the system would allow templates with same name in same group (e.g. `site/index.html` and `site/index.css`) the users might get unexpected output when accessing the templates by URL `site/index`

We probably need to add a note in user guide on this though
