### ISSUE TITLE
Memory Cache within DB Drivers

### ISSUE THREAD

**Issue by maneeshblr** [ExpressionEngine/ExpressionEngine#1145]
**Is your feature request related to a problem? Please describe.**
It is related to performance. Often, I see 70, 80 or more queries for one page. All of these hit the MySQL server. For busy sites, the MySQL Server recommends to turn off internal query cache and use an external driver.

**Describe the solution you'd like**
The ideal solution would do a hash of every query and use the memory cache (Memcache, Redis) for this purpose. 

**Describe alternatives you've considered**
We have already implemented Redis/Memcache for our custom add-ons. The performance there is just fantastic. 

**Teachability, Documentation, Adoption, Migration Strategy**
Migration would be very easy. Those who enable the cache get the benefit and those who do not, will not. It requires no change anywhere except a enable option, and a cache configuration (which is already there). 

- [ ] I am capable and would like to work on implementation of this feature if it is considered.
Yes, we can help test.

**Comment by robsonsobral** [comment]
Any instructions, @maneeshblr ?

**Comment by maneeshblr** [comment]
1. When we look in the "query log" below the page (for super admins), we can see 2x and 3x in front of the MySQL queries. This means, same queries are being run by EE to serve a page. Almost every page load requires EE to fetch sites, template groups, templates, variables, embedded templates, and if the user is logged in, the session details, user profile details, user roles etc. Clearly MySQL server is getting a lot of identical queries. For busy sites, this would be an inefficiency that can be reduced. First is to avoid duplicate queries. Second way is to use application level cache. We already have a Memcache in EE for template and tag cacheing. It can be enhanced by adding query cache to it. 
2. Adding a hash to a query and storing data into Memcache is not complex. But removing the keys from memcache when any of the cached tables/rows after a write is quite a challenge. We use application cache in our application level add-ons. The results of almost every select operation are cached. And upon a change, the cache key associated with the results of the query is deleted as the add-on is aware of the table structure and the queries. In other words, let's say the "template" Model manages the writes to templates table, and also the read operations. In that case, if the model can cache the results from SELECT operation, and invalidate at the time of write to the templates table, then this would work. 

I do agree that when I submitted this enhancement, it seemed to me that this could be done in the DB driver. But that is not right. It would have to be done in every model where this is to be done. Thanks.

**Comment by intoeetive** [comment]
In EE 7.1 and 6.4 we rolled in a lot of optimization changes, which includes model query caching and reducing duplicate queries.

It is also possible to set Redis or Memcached as caching in EE preferences.

I believe that with these changes this request is not relevant and can be closed
