### ISSUE TITLE
Ability to remove all cookies

### ISSUE THREAD

**Issue by maneeshblr** [ExpressionEngine/ExpressionEngine#1146]
**Is your feature request related to a problem? Please describe.**
It seems there is no way to disable tracker, last visit and last activity cookies. These are together quite large and are transported back and forth with HTTP request and response. If we could disable this through settings, it will be great. 

**Describe the solution you'd like**
Add an option to remove each of these cookies in Control Panel. 

**Describe alternatives you've considered**
We have explored commenting out the relevant section of the EE Source Code to remove these cookies. 

**Teachability, Documentation, Adoption, Migration Strategy**
It is quite easy for users - they would be able to toggle these cookies and they will get turned off/on. 

- [ ] I am capable and would like to work on implementation of this feature if it is considered.
Yes, we can help test this feature.

**Comment by iammattmartin** [comment]
https://github.com/ExpressionEngine/ExpressionEngine/pull/1009/commits/ff1c2b560993797cbed1d66bc152e4a7ca668caa might be of use in part if not using the forum.

**Comment by intoeetive** [comment]
In EE 7 (and EE 6 with Pro) we have reviewed the list of cookies that is being set, reducing the list of those that are needed. We also added the ability to manage the cookie lifetime in Control Panel.

The changes make this feature request mostly irrelevant. Closing out, if you have specific request related to cookie management in EE 7, please submit as new GitHub issue
