### ISSUE TITLE
Channel Layout show/hide tab icon overlays tab title

### ISSUE THREAD

**Issue by obfuscode** [ExpressionEngine/ExpressionEngine#115]
**Description of the problem**
If a Channel Layout tab that can be hidden is set as the first tab, the show/hide icon covers part of the tab's name. This happens on both first and third-party tabs.

**How To Reproduce**
1. Create Channel
2. Create Channel Layout
3. Drag a tab with a show/hide icon to the first position
4. Save Channel Layout

**Screenshots / Videos / Template Code**
<img width="264" alt="screen shot 2019-02-02 at 7 33 45 pm" src="https://user-images.githubusercontent.com/2160089/52170949-de63d780-2721-11e9-945c-3871778e120e.png">

**Environment Details:**
 - Version: 5.1.3
 - PHP Version: 7.2
 - MySQL Version: 5.7
 - OS:  macOS
 - Web Server: nginx

**Comment by jmathias** [comment]
We have new UI that fixes this issue and many more with tabs that hasn't been implemented, but I wanted to let you know this is known, and will be fixed when that UI is implemented.

**Comment by intoeetive** [comment]
Closing this out as the issue in non-existent in new EE6 UI
