### ISSUE TITLE
consent:has_responded tag with OR conditional seems to not working properly if consent has been given via consent_grant_url

### ISSUE THREAD

**Issue by pixiwooh** [ExpressionEngine/ExpressionEngine#1151]
Template issue :

I use this code on a template to ask for consent only if the user has not responded yet to any consent request.
```
{if  ! consent:has_responded:ee:cookies_functionality OR ! consent:has_responded:ee:cookies_performance OR ! consent:has_responded:ee:cookies_targeting}
{exp:consent:requests}
<div id="consents__list">
    <h1>{consent_title}</h1>
    <div>{consent_request}</div>

    <ul>
      <li><a href="{consent_grant_url}">Allow</a></li>
      <li><a href="{consent_withdraw_url}">Decline</a></li>
    </ul>
  {/exp:consent:requests}
{/if} 
```
If the user gives his consent via exp:consent:form (lets say on an other template for example), my div #consents__list won't show but if he gives his consent via  {consent_grant_url} #consents__list will still show. So the "OR" conditional seems to work in one case but not in the other one.

EE 6.0.6

**Comment by intoeetive** [comment]
@pixiwooh in terms of performing check, there is no difference if consent was granted through form or URL.
Are there any extra differences? Like, the user being logged in vs logged out, superadmin vs regular user etc.

**Comment by pixiwooh** [comment]
@intoeetive I don't know the reason why this is happening but there is nothing special. This is on a fresh new local EE install without any addon installed. I made my tests with logged out user.

here is my complete code : 
```
{if ! consent:has_responded:ee:cookies_functionality OR ! consent:has_responded:ee:cookies_performance OR ! consent:has_responded:ee:cookies_targeting}
    {exp:consent:form}
        {if no_results}
            <p>No Consent Requests to Display</p>
        {/if}
        <fieldset>
            {consents}
            <input type="checkbox" name="{consent_short_name}" id="{consent_short_name}" value="y" {if consent_granted}checked{/if}>
            <label for="{consent_short_name}">{consent_title}</label>
            {/consents}
        </fieldset>
        <fieldset>
            <button type="submit">Grant the selection</button>
        </fieldset>
    {/exp:consent:form}
{/if}

<div>
    {exp:consent:requests}
    <h2>{consent_title}</h2>
    <div>{consent_request}</div>
      {if consent_granted}
      <a href="{consent_withdraw_url}">Withdraw consent</a>
      {if:else}
      <a href="{consent_grant_url}">Grant consent</a>
      {/if}
    {/exp:consent:requests}
</div>
```

I made a screencast of the issue : https://drive.google.com/file/d/1-kUhN3eIoknI1sGRs4YCFWFxZ6SC2Sl1/view

Between 0:11 and 0:27 I just clear browser's history (caches, cookies,...) and accept exception for my local MAMP self-signed ssl certificate.

**Comment by intoeetive** [comment]
I have watched your screencast, experimented with this locally and re-read the docs and all I can say is that this is expected behaviour.

`consent:has_responded` variables are used to indicate whether the user has given ANY response to the consent - either accepting it or denying it.

When clicking the URL, one consent at a time is being accepted or withdrawn.

Now when you submit a form, you have all 3 consents in it. So even if you have just one checkbox checked, technically you have responded to all 3 consents and so `consent:has_responded` is returning `true`

**Comment by pixiwooh** [comment]
Thanks for pointing me that out. I have a better understanding of it now.

Following what you said I achieved my goal by doing the contrary: 

```
{if consent:has_responded:ee:cookies_functionality OR consent:has_responded:ee:cookies_performance OR consent:has_responded:ee:cookies_targeting}
{if:else}
  {exp:consent:form}
          {if no_results}
              <p>No Consent Requests to Display</p>
          {/if}
          <fieldset>
              {consents}
              <input type="checkbox" name="{consent_short_name}" id="{consent_short_name}" value="y" {if consent_granted}checked{/if}>
              <label for="{consent_short_name}">{consent_title}</label>
              {/consents}
          </fieldset>
          <fieldset>
              <button type="submit">Grant the selection</button>
          </fieldset>
      {/exp:consent:form}
{/if}
```

Sorry for bothered you with this then.
