### ISSUE TITLE
[EEv6.0.6] "Delete entries, by others" Channel Access Setting Ignored

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#1153]
Role Groups > Channel Access > Channel Name > Delete entries, by others = setting is ignored by EE.

Our client currently has to open an entry, click on the Options tab, assign herself as an entry's author, save the entry and navigate back to the Entries Manager before she can delete the entry.

She should be able to delete any entry regardless of which author is listed under the Options tab.

PHP Version 7.3.28 / MySQL 5.7.34

**Comment by intoeetive** [comment]
@PDXMan1 just to confirm, this is in EE6?

**Comment by PDXMan1** [comment]
Yes, EE v6.0.6. And this was a new site that was started in v6 a couple of months ago; if that helps.

**Comment by PDXMan1** [comment]
Hm... so it looks like this was slated for v6.1.0, but for some reason, it just didn't make it?

**Comment by TomJaeger** [comment]
Thanks for mentioning this. We'll review, the PR.. if it's in good shape we'll aim to get it into 6.1.2 (which we're planning to have out pretty soon)
