### ISSUE TITLE
Jump Menu Log Links Reversed

### ISSUE THREAD

**Issue by blairliikala** [ExpressionEngine/ExpressionEngine#1154]
The Jump menu Consent and Control Panel locations are backwards.

Jump Menu, type log, click Control Panel and it goes to Consent.
Jump Menu, type log, click Consent and it goes to Control Panel.

EE 6.0.6

**Comment by intoeetive** [comment]
This has been fixed in https://github.com/ExpressionEngine/ExpressionEngine/commit/a0520c4dfa62681483c69ad7e3a8b5848ae706ce and will be released in EE 6.1.0
