### ISSUE TITLE
Add timestamp to "Entry Updated" alert after saving an entry

### ISSUE THREAD

**Issue by swierczek** [ExpressionEngine/ExpressionEngine#1157]
**Is your feature request related to a problem? Please describe.**
If I'm editing/saving an entry multiple times in a row, it's not clear if I have saved my most recent changes or not because it's not clear if the green "Entry Updated" alert is related to my previous save or if I just saved it successfully.

Current:
![image](https://user-images.githubusercontent.com/2423727/123152166-e8d5b780-d429-11eb-9ca3-332153ae6f55.png)

**Describe the solution you'd like**
I would prefer if the copy includes a timestamp indicating when the entry was last successfully saved. Something like "The entry Test Entry has been updated at 3:01 PM." (or some variant like "6/23/2021 3:01 PM") I assume this timestamp would be formatted like any other (localized?) timestamp across the CMS.

Proposal:
![image](https://user-images.githubusercontent.com/2423727/123152219-f9862d80-d429-11eb-9d38-c81882bf5cea.png)

**Describe alternatives you've considered**
An alternative process for me would be manually closing the Alert (by clicking the "x") every time the page reloads, but that adds overhead to the editing process, and if I forget to close the Alert I'm back to the original problem of not easily knowing when it was last saved.

**Teachability, Documentation, Adoption, Migration Strategy**
This would be a self-explanatory update for clarity when editing entries.

- [ ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
@swierczek this sounds like very good addition.

If you feel you're capable to work on it, please go ahead and submit PR into our repo.

In case you're not familiar, we have some [contributing guidelines](https://github.com/ExpressionEngine/ExpressionEngine/blob/6.dev/CONTRIBUTING.md#contributing-code) written down as well as there has been [EEConf presentation](https://www.youtube.com/watch?v=a9x_17PU1s0) recently covering EE Core Contribution.
