### ISSUE TITLE
Display channel name on Edit Entry page

### ISSUE THREAD

**Issue by swierczek** [ExpressionEngine/ExpressionEngine#1159]
**Is your feature request related to a problem? Please describe.**
When editing an entry, it's not apparent which Channel this entry is in. I believe EE 5 listed the Channel name as part of breadcrumb-type navigation above the form, but this seems to have disappeared with EE 6.

![image](https://user-images.githubusercontent.com/2423727/123156080-7e734600-d42e-11eb-9758-4a13df3e736f.png)

**Describe the solution you'd like**
Add `> <channel name>` to the existing header navigation (which would also link back to `/cp/publish/edit&filter_by_channel=<channel_id>`)

**Teachability, Documentation, Adoption, Migration Strategy**
This functionality would be self-explanatory to make it more apparent which Channel this Entry is in.

- [ ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
This has been implemented and will be released in EE 6.1.0
