### ISSUE TITLE
New 5.1 upgrade with Drag/Drop/Bulk uploads not working in IE

### ISSUE THREAD

**Issue by sburris777** [ExpressionEngine/ExpressionEngine#116]
In IE version 11 the new drag/drop/bulk upload image fields are showing "loading..." (see screenshot) and not working. When I am using Chrome and Firefox the fields work just fine, but our client uses IE and cannot upload images.

The site is on EE version 5.1.3.

![image010](https://user-images.githubusercontent.com/24320851/52172798-09abee00-2745-11e9-98ab-d72d4a15e6a9.png)

**Comment by jmathias** [comment]
Hi, 

Sorry for the trouble, however version 5 doesn't support IE. https://docs.expressionengine.com/latest/installation/requirements.html#control-panel-browser-requirements
