### ISSUE TITLE
Colour Picker UI hidden in Grid field

### ISSUE THREAD

**Issue by liamcrean** [ExpressionEngine/ExpressionEngine#1167]
See image below - it's an overflow issue.

<img width="310" alt="Screenshot 2021-06-27 at 18 45 40" src="https://user-images.githubusercontent.com/2526645/123554829-dafd9a80-d779-11eb-9153-38e8a648928b.png">

The following fixes it - but may impact other fields... 

```
.table-responsive, .tbl-wrap {
overflow-x: visible;
}
```

**Comment by liamcrean** [comment]
Can I get an update on this? Is it on the radar for next release? It's a bug I'm hacking in the CMS for a current client build but know it'll be overwritten...

**Comment by intoeetive** [comment]
This is fixed in recent EE versions
