### ISSUE TITLE
`Undefined offset: 1` when `$config['site_url'] = '/';`

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1168]
Hi!

To keep consistency between domains of different environments, I set `$config['site_url'] = '/';`, but there's a domain checking triggering a warning on `$configured_site_url[1]`, `ee/ExpressionEngine/Controller/Publish/AbstractPublish.php`, line 519.

```php
$configured_site_url = explode('//', ee()->config->item('site_url'));
$configured_domain = explode('/', $configured_site_url[1]);

if (($_SERVER['HTTP_HOST'] != strtolower($configured_domain[0])) || ($configured_site_url[0] != '' && ((ee('Request')->isEncrypted() && strtolower($configured_site_url[0]) != 'https:') || (!ee('Request')->isEncrypted() && strtolower($configured_site_url[0]) == 'https:')))) {
    $has_preview_button = false;
}
```

**Comment by intoeetive** [comment]
Thanks for the catch!

However, in EE 6.1.0 we'll be implementing this differently, so this error will not be relevant anymore.
