### ISSUE TITLE
[EE6] Select dropdown fields within grid and file grid fields should default to unselected

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#1172]
When creating a new channel entry, standalone select dropdown fields default to being unselected — with an additional "Choose wisely" meta-option added to show this.

Select dropdown fields within grid and file grid fields, on the other hand, default to the first actual option. This behaviour is inconsistent with the above, and, in the absence of a prompt which directs users to make a selection, makes it more likely that default selections will be left in place, perhaps incorrectly.

For consistency, and to enforce a conscious selection, select dropdown fields within grid and file grid fields should also default to being unselected.

(A possible extension to this would be to allow a default selection to be specified for select dropdowns. But defaulting in practice to the first option is unhelpful UI.)

EE6.0.6

**Comment by blue-dreamer** [comment]
This would be useful for SELECT fields because:

a) setting a value can be optional
b) it allows a NULL/blank default value by default, useful for template coding and can negate the need for extra conditionals to work out if the field has a "proper" value or not.
