### ISSUE TITLE
Allow static use of `exp:category_heading`

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1181]
**Is your feature request related to a problem? Please describe.**
A lot of time I need to get a category metadata, but I can't use `exp:category_heading`, I need to write a custom query.

**Describe the solution you'd like**
As `exp:channel` allows us to override URL detection, the same could be valid for `exp:category_heading`.

**Describe alternatives you've considered**
Without this feature, I need to write a custom query.

**Teachability, Documentation, Adoption, Migration Strategy**
The documentation is pending on a [pull request](https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/199)

- [x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by robinsowell** [comment]
This has been on my  personal todo list forever- love to see it added!

**Comment by robsonsobral** [comment]
> 
> 
> This has been on my personal todo list forever- love to see it added!

Really? I'm felling so important now! Wow!
