### ISSUE TITLE
Diacritics being shown as HTML entities on CP tables

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1184]
I gonna try to fix it.

![image](https://user-images.githubusercontent.com/931642/124046007-5b750300-d9e7-11eb-9d66-24814fd529b7.png)

**Comment by robsonsobral** [comment]
Hi, @intoeetive . I've found another case. It's on batch editor.


![Screenshot 2021-07-28 at 11-11-48 Editar Publicações do Canal ExpressionEngine](https://user-images.githubusercontent.com/931642/127374839-f258a515-8095-408b-853c-72484c50f5e6.png)

**Comment by intoeetive** [comment]
@robsonsobral this is working fine in referenced branch (you can pull it in, if you need the fix straigh away)
