### ISSUE TITLE
RTE - Youtube videos with nocookie url

### ISSUE THREAD

**Issue by adlix** [ExpressionEngine/ExpressionEngine#1191]
Hi,
I'm using EE6.0.6 with RTE in full mode. 
Video inserting with nocoookie URL https://www.youtube-nocookie.com/embed/29GxKL4_EIo
througths an error message "This media is not supported". 

Pasting videos by HTML-view is also not possible. HTML-Button is missing. Is there a possibility for HTML view?

So inserting videos in GDPR mode is not possible.  

Thanks for help,

Matthias

**Comment by intoeetive** [comment]
@adlix RTE field in EE 6.0.6 is utilizing CKEditor, which supports following media providers:
'dailymotion',
'spotify',
'youtube',
'vimeo'.
'instagram',
'twitter',
'googleMaps',
'flickr',
'facebook'

If you need to have more added, please address the request to CKEditor developers: https://github.com/ckeditor/ckeditor5/issues

Having said that, EE 6.0.6 has 'HTMl Embed' button in RTE. If it's not visible for you, please check the toolbar configuration in RTE settings - it might be enabled.

**Comment by adlix** [comment]
Hi,
Thanks for fast answer.
Are you joking? :-D
Which button? I’ve  checked all of them twice.
HTML view is not there, is it?



I wrote a ticket for CKEditor and ask them to add  
www.youtube-nocookie.com/embed
to a YouTube-Nocookie configuration and added it as hotfix to my ckeditor.js

{name:"youtube-nocookie",url:[/^(?:m\.)?youtube-nocookie\.com\/watch\?v=([\w-]+)/,/^(?:m\.)?youtube-nocookie\.com\/v\/([\w-]+)/,/^youtube-nocookie\.com\/embed\/([\w-]+)/],html:t=>`<div style="position: relative; padding-bottom: 100%; height: 0; padding-bottom: 56.2493%;"><iframe src="https://www.youtube-nocookie.com/embed/${t[1]}" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0;" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>`}

It’s also possible by api https://ckeditor.com/docs/ckeditor5/latest/api/module_media-embed_mediaembed-MediaEmbedConfig.html#member-providers <https://ckeditor.com/docs/ckeditor5/latest/api/module_media-embed_mediaembed-MediaEmbedConfig.html#member-providers>

Many thanks,
Matthias

**Comment by intoeetive** [comment]
Hi @adlix -
I was going to say GitHub is no place for joking, but just found out how wrong I was!
Appears this feature was not released, and will only be released in EE 6.1.0 (which we expect to be out soon)

Here's how it will look like:
![image](https://user-images.githubusercontent.com/752126/124863440-be563380-dfbf-11eb-984d-e3755b707ff9.png)

If you need this feature straigt away and do not want to wait until release, you may as well check out `6.dev` branch from the repo.

Sorry for misleading you here!

**Comment by adlix** [comment]
Everything is fine. Many thanks. 
So I will update as soon as possible.
Great
