### ISSUE TITLE
Categories problem in entry editor

### ISSUE THREAD

**Issue by adlix** [ExpressionEngine/ExpressionEngine#1192]
Hi,
we are using EE6.0.6 with 10.0.38-MariaDB-0ubuntu0.16.04.1 and PHP7.1.33 
The reported error is also appearing in version 5.4, too.
We are
- selecting entry list for channel "News".
- filtering list by category e.g. "Collaborative Robots"
- clicking on edit for any entry
- selecting the tab "Category"
-  no category is selected.

Error is not depending on a special browser.

The category has been set, it was found by filter, but in the tab view it is missing.

Thanks for help,

Matthias

**Comment by adlix** [comment]
Sorry. The categories are shown and checkable.
After selecting and saving categories doesn't appear, too.
Selection is saved in table category_posts.

**Comment by intoeetive** [comment]
@adlix I am unable to replicate this, and the general description make me wonder if something in corrupt in your database - or there is an add-on that's interfering here.

Can you record a screencast demonstrating what you are doing? Also, are categories shown for the entries on frontend, when using `{exp:channel:entries}` and `{categories}`?

**Comment by adlix** [comment]
Hi,
find an error description in this video

https://youtu.be/XzDJ8Rqf3sg <https://youtu.be/XzDJ8Rqf3sg>

Best regards,

Matthias

**Comment by intoeetive** [comment]
Closing this as we weren't able to replicate in any way
