### ISSUE TITLE
Parse {exp:search:total_results} as any other template tag

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1193]
**Is your feature request related to a problem? Please describe.**
Currently. despite `{exp:search:total_results}` can be used as a variable pair, it has no difference from a single variable

**Describe the solution you'd like**

I would like to be able to code something like:

```
{exp:search:total_results}
    <p>
        {total_results} found.
    </p>
    {if no_results}
        <p>No results found.</p>
    {/if}
{/exp:search:total_results}
```

- [x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
Making this available as tag pair would be nice little addition!

@robsonsobral if you feel good about it, please go ahead and implement. Thank you!

**Comment by intoeetive** [comment]
@robsonsobral thanks for implementing this!
