### ISSUE TITLE
Add information on template processed to hook: template_post_parse

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#1195]
**Is your feature request related to a problem? Please describe.**
EE provides a hook [template_post_parse($final_template, $is_partial, $site_id)](https://docs.expressionengine.com/latest/development/extension-hooks/global/template.html#template_post_parsefinal_template-is_partial-site_id) that provides access to the parsed template output once processing is complete.
The hook includes a variable `$is_partial` described thusly: **TRUE if the current template is an embed or a layout**
This suggests that the output could relate to a partially processed template yet for that use case the hook does not provide any information about *which* template it is relating to... which makes it less useful.

**Describe the solution you'd like**
Either amend the documentation to explain the purpose of the `$is_partial` parameter, or amend the hook to include information about which template the parse step that has completed was applied to.

The second option would be more helpful - as it would potentially allow the intercept of content after a partial template has been processed.

**Describe alternatives you've considered**
?

**Teachability, Documentation, Adoption, Migration Strategy**
Depends on what solution is available.

- [X] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
@jcogs-design I think passing and array/object of information about the template currently being parsed as another parameter is the way to go.

Thank you for willing to contribute on this!
