### ISSUE TITLE
Bootstrap 5 similar like Joomla 4 ?

### ISSUE THREAD

**Issue by ssnobben** [ExpressionEngine/ExpressionEngine#1197]
Hi I wonder if I can use Bootstrap 5/native js similar like for Joomla 4? 

Is that supported?

**Comment by intoeetive** [comment]
@ssnobben we tend to keep GitHub issues for bug reports and feature requests.

Please feel free to ask questions like this in our [Slack community](https://expressionengine.com/blog/join-us-in-slack#join-us-on-slack) or on [StackExchange](https://expressionengine.stackexchange.com/).
