### ISSUE TITLE
Problem with channel layouts

### ISSUE THREAD

**Issue by kippenblinky** [ExpressionEngine/ExpressionEngine#12]
When selecting layouts in channel manager this error appears.
Fresh update to 5.0.1
(https://user-images.githubusercontent.com/45204314/48778457-7f232900-ecd5-11e8-9545-c20db0807c03.png)

**Comment by derekjones** [comment]
Can you make sure that _this file_ exists on your server? If you deployed with FTP it's possible that it missed some files.

**Comment by derekjones** [comment]
If you click the eye icon next to the Categories tab, you can remove it from the publish page entirely for a given channel.

**Comment by kippenblinky** [comment]
Thats the thing. Clicking on the eye does nothing?

**Comment by derekjones** [comment]
Do you have any JavaScript errors in your console? I am unable to reproduce that on a fresh install. Perhaps you're missing some files still, or the layout is somehow corrupted from earlier. If the latter, then deleting the layout or creating a new one should work for you.

**Comment by kippenblinky** [comment]
No errors. Creating a new layout fixes the problem. Thank you :)

**Comment by derekjones** [comment]
You're welcome!
