### ISSUE TITLE
Use mobile/device grid view when using preview

### ISSUE THREAD

**Issue by liamcrean** [ExpressionEngine/ExpressionEngine#1209]
Preview is very clunky on pages with grids over a certain number of columns. 

Really anything over 2 or 3 depending on content. But there's already a nice responsive grid UI for screen widths under 768px. 

Would it be possible to remove the constraints somewhat? and allow resizing of the preview pane with grid view media queries for mobile looking for the editing window width, rather than the full viewport width.

**Comment by liamcrean** [comment]
Adding to this request.

`overflow-x:auto`; on the grid container `.live-preview__form` fixes this issue (would need to be referenced for windows over a certain width I guess as a media query).

**Comment by intoeetive** [comment]
In latest EE 6 and 7 the Grid is responsive, so will now also work good with live preview
