### ISSUE TITLE
File fields can't be shared among sites

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1211]
Hi!

Due to the fact that directories can't be shared among sites, to share a file field results in a bug that blocks new entries publishing. Total showstopper!

I'm running ExpressionEngine 6.0.6

**Comment by robsonsobral** [comment]
Relationship fields neither!

**Comment by intoeetive** [comment]
I believe this is duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/78

Closing now, - the relationships though might be different thing. Feel free to open separate issue  with more details (errors that you get, prerequisites etc)
