### ISSUE TITLE
relationships tag not compatible with php 8.0 in Expression Engine 6.0.4

### ISSUE THREAD

**Issue by Fred2341** [ExpressionEngine/ExpressionEngine#1212]

**Comment by intoeetive** [comment]
@Fred2341 can you add some info on this? What is the error that you get, when you get it etc.

**Comment by Fred2341** [comment]
Thanks for getting back to me, Yuri.

I thought I had added the error.

When I add following relationship within a channel entries loop:

{tag_name}
	{tag_name:title}
{/tag_name}

I get following warning when applying php 8.0:



With php 7.4 no warning occurs.

I hope you can shed some light on this.

Regards

Fred Geiger

**Comment by intoeetive** [comment]
@Fred2341 looks like you had a screenshot but it did not come through (often happens when you use email to post the comment to GitHub without visiting) - can you post it?

**Comment by Fred2341** [comment]
I will post it as pdf, see also attached.


Fred Geiger
M: 06 1092 8658

**Comment by intoeetive** [comment]
@Fred2341 there's no attachment. You'll need to visit https://github.com/ExpressionEngine/ExpressionEngine/issues/1212 directly to add comment

**Comment by Fred2341** [comment]
the attached screenshot
[php warning.pdf](https://github.com/ExpressionEngine/ExpressionEngine/files/6891089/php.warning.pdf)

**Comment by intoeetive** [comment]
Thank you - I was able to replicate and working on a fix
