### ISSUE TITLE
Incorrect error message - CP Settings for Add-on Module

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#1215]
If you register an add-on with the setting `'settings_exist' => 'y'` and fail to cause a value for `$vars['_module_cp_body']` to be set on the settings page (e.g. if **mcp.addon.php** is empty) EE6 returns the error `requested_module_not_installed`.  Vis line 765 of **syste/ee/ExpressionEngine/Controller/Addons/Addons.php**:
```
765        if (! isset($vars['_module_cp_body'])) { 
766            show_error(lang('requested_module_not_installed') . NBS . $addon);
767        }
```
This is not the correct error - since the add-on can be installed with `'settings_exist' => 'y'` and an empty mcp file (so the add-on is 'installed' - it is just incomplete).

Either the add-on installer should cross check that `$vars['_module_cp_body']` would not be empty on install when `'settings_exist' => 'y'` is specified, or a different error message should be displayed (e.g. `unable_to_open_settings_page` with suitable text).

**Comment by intoeetive** [comment]
@jcogs-design based on the docs, `mcp.` file should not be empty, but have class definition at the minimum: https://docs.expressionengine.com/latest/development/modules.html#the-control-panel-file-mcpmodule_namephp

**Comment by jcogs-design** [comment]
Sure - but the issue is not that an error occurs, but that the error message generated is the wrong one.

**Comment by intoeetive** [comment]
I have looked at this again and I believe the error message is correct for the end user. It might misguide if you're add-on developer, but for the general user if settings should exist but you can't set those - this means the add-on is not functional.

It might be worth to have some "sanity check" script for add-on developers, but that would be a whole different thing
