### ISSUE TITLE
Auto-Search for Entries Interferes With Multiple Keyword Phrases

### ISSUE THREAD

**Issue by projectnoontide** [ExpressionEngine/ExpressionEngine#1219]
Search an entry slowly or type more than two words and the auto search eats the last word of the keyword phrase.

Desired behavior:
Remove auto-search.  Search upon keyboard return.

Environment:
EE 6.0.6, PHP 7.4, MySQL 8, AWS/EC2 Ubuntu 20.04.

**Comment by intoeetive** [comment]
The search-as-you-type feature in Entry Manager has been improved since this has been reported. In some edge cases (like if you type exactly 1 character in a second) there might be some issues, but generally we consider this fixed
