### ISSUE TITLE
file wrap parameter outputs incorrect alt content

### ISSUE THREAD

**Issue by bwydev** [ExpressionEngine/ExpressionEngine#122]
**File Grid field within Fluid field:**

Outputting an image using the "wrap" parameter outputs the string "image" instead of the file name as indicated in docs ( https://docs.expressionengine.com/latest/fieldtypes/file.html#wrap-parameter ).

Example:

```
{my_fluid_field}
	{my_fluid_field:file_grid_field}
		{content}
			A: {content:file}<img src="{url}" alt="{filename}">{/content:file}
			B: {content:file wrap="image"}
		{/content}
	{/my_fluid_field:file_grid_field}
{/my_fluid_field}

output:
A: <img src="some-url.jpg" alt="my-filename.jpg">
B: <img src="some-url.jpg" alt="image">
```

 - Version: 5.1.2
 - PHP Version 7.1.12
 - MySQL Version 5.6.38
 - OS: mac
 - Web Server: mamp apache

**Comment by kevincupp** [comment]
Sorry for your trouble. I'm unable to reproduce this one. Here is my entire template:

```
{exp:channel:entries channel="test_bug" entry_id="328"}
	<h1>{title}</h1>
	{some_fluid_test}
		{some_fluid_test:test_file_grid}
			{content}
				A: {content:file}<img src="{url}" alt="{filename}">{/content:file}
				B: {content:file wrap="image"}
			{/content}
		{/some_fluid_test:test_file_grid}
	{/some_fluid_test}
{/exp:channel:entries}
```

It outputs this as expected:

``` html
A: <img src="http://eecms.localhost/images/uploads/VIDEO_STAFF_14VT_3949E.jpg" alt="VIDEO_STAFF_14VT_3949E">
B: <img src="http://eecms.localhost/images/uploads/VIDEO_STAFF_14VT_3949E.jpg" alt="VIDEO_STAFF_14VT_3949E" />
```

I find it really strange your B example doesn't have the old XHTML closing slash on the end of the `img` tag like mine does. It's like something else is generating the markup. Could you try reproducing this on a clean install, or see if there are any other variables as play?

**Comment by bwydev** [comment]
Well I can't duplicate my own issue now either! Sorry for the wasted time.
