### ISSUE TITLE
Control panel upload directory edit fails

### ISSUE THREAD

**Issue by tday55** [ExpressionEngine/ExpressionEngine#1236]
**Description of the problem**
Trying to edit the upload directories from control panel.
EE 5.3.2

**How To Reproduce**
Go to control panel click on files
Then click on edit one of the upload directories.

**Error Messages**

<pre><code>

Exception Caught
SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'where clause':
SELECT `group_id`, `group_name`, `sort_order` FROM (`exp_category_groups`) WHERE `site_id` = 1 AND (exclude_group = "0" OR exclude_group = "1") ORDER BY `group_name`
ee/legacy/database/drivers/mysqli/mysqli_connection.php:117

Stack Trace: Please include when reporting this error
#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('SELECT `group_i...')
#1 ee/legacy/database/DB_driver.php(270): CI_DB_mysqli_driver->_execute('SELECT `group_i...')
#2 ee/legacy/database/DB_driver.php(180): CI_DB_driver->simple_query('SELECT `group_i...')
#3 ee/legacy/database/DB_active_rec.php(1138): CI_DB_driver->query('SELECT `group_i...')
#4 ee/legacy/models/category_model.php(100): CI_DB_active_record->get()
#5 ee/EllisLab/ExpressionEngine/Controller/Files/Uploads.php(312): Category_model->get_category_groups('', false, 1)
#6 ee/EllisLab/ExpressionEngine/Controller/Files/Uploads.php(49): EllisLab\ExpressionEngine\Controller\Files\Uploads->form()
#7 [internal function]: EllisLab\ExpressionEngine\Controller\Files\Uploads->create()
#8 ee/EllisLab/ExpressionEngine/Core/Core.php(241): call_user_func_array(Array, Array)
#9 ee/EllisLab/ExpressionEngine/Core/Core.php(110): EllisLab\ExpressionEngine\Core\Core->runController(Array)
#10 ee/EllisLab/ExpressionEngine/Boot/boot.php(151): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request))
#11 index.php(148): require_once('...')
#11 index.php(148): require_once('...')
</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 5.3.2
 - PHP Version  7.2.24
 - MySQL Version mysql  Ver 15.1 Distrib 10.3.28-MariaDB, for Linux (x86_64) using readline 5.1
 - OS: Centos 8
 - Web Server: Apache

**Possible Solution**

**Additional context**

**Comment by intoeetive** [comment]
Since EE5 has reached end of life, I am closing this out.
Please open new issue if you face same problem in EE6
