### ISSUE TITLE
`channel_url` not being saved on channel creation

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1240]
The value submitted at the field `channel_url` isn't saved on channel creation, just on channel edition.

Running: 

- eecms 6.0.6
- mariadb:10.5.10-focal
- Apache 2.0
- PHP Version 7.4.20

**Comment by intoeetive** [comment]
I wasn't able to replicate this in EE 6.0.6 by creating new channel and entering only channel name and channel URL. Closing for now, please reopen with more details ff you still experience this issue

**Comment by robsonsobral** [comment]
I should have told that the site url is saved instead of the filled value.

I'm sorry.

**Comment by intoeetive** [comment]
You are right. Not that I look at it more closely I see that wrong value is saved initially
