### ISSUE TITLE
[EEv6.0.6] All entries table "Author" column not displaying the ˆ accent correctly.

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#1248]
EE v6.0.6 / PHP 7.4.19 / MySQL 5.7.35

Our client's organization's name is correctly spelled/written Kôr. The "Title" column gets the display correct, but the "Author" column doesn't.

Looks like EE is trying to use "Safe HTML" with the Author column.

<img width="1103" alt="Screen Shot 2021-08-03 at 1 16 47 PM" src="https://user-images.githubusercontent.com/6145078/128080767-00b7bf9e-d25b-4e6a-8c60-8bee662baf09.png">

**Comment by robsonsobral** [comment]
Please, check if [this helps](https://github.com/ExpressionEngine/ExpressionEngine/pull/1196).

**Comment by PDXMan1** [comment]
Works like a charm. That didn't come up in any of my searches. I appreciate your help @robsonsobral! Thank you.
