### ISSUE TITLE
Adding image in textarea type field

### ISSUE THREAD

**Issue by abhijeetbhushan** [ExpressionEngine/ExpressionEngine#1249]
Either in upgraded EE version or if you do the new setup, this issue is in both situation.
 
1. The problem is with textarea field. So, if you create a textarea field and allow formatting button and file upload and then assign this field to any channel.
2. Now, add a new entry in that channel. Add some text there in 6-7 paragraphs.
3. Now, if you want to add file then first time the after adding the file the image tag always comes below the all paragraph texts, which means this tag is not added where you cursor had. But when you try the second time then it works fine.
 
Please check attached.
![2021-07-31_155806](https://user-images.githubusercontent.com/6028847/128307813-d8469046-6e2d-410a-9b7e-a0da9df6af0a.png)
![2021-07-31_155923](https://user-images.githubusercontent.com/6028847/128307820-8d04470e-2a97-4baf-a7f3-063d691ee700.png)
![2021-07-31_160020](https://user-images.githubusercontent.com/6028847/128307823-3604f430-b96c-484a-b589-2a45866507f4.png)

**Comment by abhijeetbhushan** [comment]
Do we have anything here?

**Comment by intoeetive** [comment]
@abhijeetbhushan all of PacketTide team is busy getting EE 6.1 out of the door. Please understand we can't provide immediate reaction to GitHub issues that are not showstoppers.

It has been noted however and will be addressed in one of upcoming releases.

You may as well check out latest `6.dev` branch from this repo and see if it's already fixed there. If it's not, and you know how to fix it, feel free to submit pull request, as ExpressionEngine is open source project and the community input is highly valuable.

**Comment by abhijeetbhushan** [comment]
Okay Yuri, I understand.
Very excited about pro.
