### ISSUE TITLE
Issue in multiselect fieldtype

### ISSUE THREAD

**Issue by abhijeetbhushan** [ExpressionEngine/ExpressionEngine#1250]
1. I have a website dirtyboots.co.za which was in EE2. The client has requested us to upgrade this to the latest.
2. When we upgrade any website, first we move the website at the development server, so I copied the complete database and files to our development server. demo2.host4india.in/dirtyboots, I have already shared the backend and credentials to you, so you can check if that helps.
3. When we upgrade the EE version then at that time, we never touch the database at all or also don't do any testing. Which means that in EE2 the multiselect was working fine and already had saved values. There are many entries, so it is not possible if we or the client can change in each entry.
4. In the multiselect field option from the fields, we had radio selected for getting the values from another channel and everything was working in EE2.
5. Now, after the upgrade the values of multiselect was not showing selected and when I print the array then I was seeing that the value is saved but that is not showing selected in channel entry. Of course, no change in the database(as we never touch in upgrading process and also not change the value of any entry which channel was associated with that field)
6. So, I took a closely look and found that there is a extra space at the saved value and that is why it is not showing selected in the field.
7. I went to the default multiselect addon file in EE, a core file and added my patch of trim that I explained and then it started working. Which means the trim removed the extra space and then it was matching to the field values which was associated to the another channel.
 
But the important things is that, I have four mutiselect fields in the same channel, and the issues was only with two multiselect fields, other two was showing the correct data. So, that is the confusion actually, because it that is something wrong then that shou;d be all four fields but it is also possible that we had a extra space in the entry title and the same was saved to data but in new EE6 the extra space has been automatically removed from the entry title and that is why the saved value which was actually has a space at the end was mismatching.
 
But here, I am 100% sure, that there is no data change in database of the entry title.
 
The same thing was on live as well, but just for your note: - When we move the dev site to live after upgrade then we don't move all the files or db from dev to live as we can loss the recent data. We just upgrade all the addons and then we do the same process to live again and just moved the third party addons only. And the same error was on live site as well.
 
Which means, I upgraded the both dev and live site separately.
 
Let me know if you have any question, maybe I explained it in a better way.
 
So far, the trim option is the only solution that I have but that is in core file and I don't prefer to make change in core file. But at the moment I had to do for the fixing the issue. 
 
I have added a patch here in core addon of multiselect in line number: - 61 to 66.
And added below code: - 
 Old code: - $values = decode_multi_field($data);
Changed code: - 
$values1 = decode_multi_field($data);
        $values = array();
                                foreach($values1 as $key => $value)
                                {
                                                $values[$key] = trim($value);
                                }

**Comment by intoeetive** [comment]
I'll have to close it, as there were no specific steps that we could follow to replicate the issue on our end (and as mentioned, this is specific to certain site and certain fields, so could be import issue etc.)

If you have specific steps that we could follow and replicate the issue, please comment back
