### ISSUE TITLE
After Enabling Signatures, No Settings for Signatures in Admin Present

### ISSUE THREAD

**Issue by jaredchesebro** [ExpressionEngine/ExpressionEngine#1266]
### ISSUE
I have enabled member signatures as specified in documentation: https://docs.expressionengine.com/latest/general/system-configuration-overrides.html#allow_signatures

After enabling I do not see a way of editing the signature in the members profile settings or anywhere else in the admin settings panel.

### EXPECTED BEHAVIOR
I would expect that after enabling this feature there would be settings in the member profile area:
![Screen Shot 2021-08-09 at 10 57 49 AM](https://user-images.githubusercontent.com/21958491/128752120-90fcf6c4-12e9-476f-aaa8-49855f2e6d81.png)

### ENV
- PHP 7.4
- mysql 5.7
- ExpressionEngine 6.0.6

**Comment by jaredchesebro** [comment]
If this option is only for use with the Forum Add-On vs sending emails, I would recommend specifying that in the documentation.

**Comment by inconsiderate** [comment]
The documentation for Signatures lives under the Forum add-on section, so I expected the settings to live there in the control panel. 
https://docs.expressionengine.com/latest/add-ons/forum/signatures.html

However, from my testing, the options do not appear after enabling the Forum add-on either.

**Comment by bakin1999** [comment]
Editing Signatures can be found in the Forum add-on by visiting the forum, then logging in and clicking 
Your Control Panel->Menu->Personal Settings->Edit Signature.
After saving, all posts after that will include signature.
![image](https://user-images.githubusercontent.com/17011377/130109736-3cc4d003-5749-458f-aeab-472ceb135c18.png)

Hope that helps, please comment again if that is not working out.

**Comment by yiodranis** [comment]
From EE documentation you can read: Signatures and Avatars. To edit any of these settings you should visit the Membership Preferences General Configuration page. This can be found under Members > Preferences.

1. No such an option.
2. In signatures option in the forums, you don't have the image upload option, and there is no way you can enable it.

You have: My Control Panel Edit Signature states: Upload an Image .Image uploads are not enabled

~And this is not the only problem with the Forums. [Also Empty Edit profile fileds]

FYI. fresh install to a new web, just using forums....[To check it for 5-6 times, in different websites]

<img width="1306" alt="blue" src="https://user-images.githubusercontent.com/85391756/131454569-c3d28e5b-bbbe-48ad-88ec-a783cafa1f53.png">
<img width="1349" alt="blue2" src="https://user-images.githubusercontent.com/85391756/131454578-fde34a91-d07e-4c1b-a4b9-0bb91a7b7715.png">

**Comment by yiodranis** [comment]
Everything Solved......

**Comment by inconsiderate** [comment]
> Everything Solved......

@yiodranis Can you explain how you solved this, instead of just posting that it is solved? 😃 

From what I see in the replies here from @bakin1999 and @yiodranis, they are attempting to change their own signatures (or that of the currently logged in user) using the front-end Forum user settings. That's useful information, but not what this issue is referring to. 

The issue here is that there is currently no way to edit/set the Signature and/or Image on any user (meaning users other than yourself), through the Control Panel as an admin.

**Comment by yiodranis** [comment]
Hi inconsiderate, 

To fix the error of not being able to upload images as signature, getting the "Image uploads are not available". You must turn that on as a system configuration override.

https://docs.expressionengine.com/latest/general/system-configuration-overrides.html#sig_allow_img_upload
talks about it in more detail here.

So adding, $config['sig_allow_img_upload'] = 'y'; to you config will fix everything

should allow images to be set. There are also all sorts of settings that can be set regarding how large these images can be.

**Comment by inconsiderate** [comment]
I'm guessing the admin editing functionality was dropped in EE3 and never came back. If that's the case, the documentation just needs to be updated to reflect reality.

https://docs.expressionengine.com/latest/add-ons/forum/signatures.html#signatures-and-avatars

> Avatars and Signatures are used throughout ExpressionEngine and are not specific to the forum.
To edit any of these settings you should visit the Membership Preferences General Configuration page. This can be found under Members > Preferences.

**Comment by yiodranis** [comment]
Yes, you are right!!! Better and correct explanation moves to a better service
