### ISSUE TITLE
Display error in Live Preview in older versions of Safari

### ISSUE THREAD

**Issue by ricklecoat** [ExpressionEngine/ExpressionEngine#127]
**Description of the problem**
Top bar (the mid/pale blue one) of Live preview does not display properly in older versions of Safari. I think the height of the bar is being set to zero or something.

**How To Reproduce**
Open any entry's Live Preview mode in the CP using Safari (Mac) v10 (I've tested in 10 and 12 but don't have access to v11). Displays correctly in Safari 12 and Google Chrome.

**Error Messages**
None

**Screenshots / Videos / Template Code**

Viewed in Safari 10:
<img width="672" alt="safari10_1_2-pga" src="https://user-images.githubusercontent.com/13526883/52722067-d36f3980-2fa2-11e9-9a1e-a2c2b55bcd40.png">

Viewed in Safari 12
<img width="594" alt="safari12_0_3-pga" src="https://user-images.githubusercontent.com/13526883/52722085-d9fdb100-2fa2-11e9-984c-50de13a51b88.png">

Viewed in Google Chrome:
<img width="936" alt="googchrm71-pga" src="https://user-images.githubusercontent.com/13526883/52722095-dcf8a180-2fa2-11e9-983c-38c00ccacd24.png">

**Environment Details:**
 - Version: 5.1.3
 - PHP Version 7.2.1
 - MySQL Version 5.6.38
 - OS: Mac OS 10.12.6]
 - Web Server: MAMP

**Additional context**
I suspect that this is due to buggy Flex support in old versions of Safari (this bug: https://bugs.webkit.org/show_bug.cgi?id=136041 ) since it seems not to be a problem with new versions. However, with many people still using older versions of Safari (I work at a university, for example, and corporate policies mean that our install Mac OS base is always a fair way behind the curve) so maybe this is something that could have some fallback CSS put in place?

**Comment by jmathias** [comment]
Thanks for the report Rick!

I'm closing this, as the CP only supports the latest versions of browsers as seen here: https://docs.expressionengine.com/latest/installation/requirements.html#control-panel-browser-requirements
