### ISSUE TITLE
channel:entries has a disable parameter for "relationships" that does nothing

### ISSUE THREAD

**Issue by nep** [ExpressionEngine/ExpressionEngine#1272]
https://github.com/ExpressionEngine/ExpressionEngine/blob/1b28b8572ea479b7a5d0a282da4e664be3eb3849/system/ee/ExpressionEngine/Addons/channel/mod.channel.php#L4756

It doesn't appear in the [documentation](https://docs.expressionengine.com/latest/channels/entries.html#disable), and I think it might be vestigial at this point.

**Comment by intoeetive** [comment]
While this parameter is not being treated in `mod.channel.php`, it is being respected in channel entries parser: 
https://github.com/ExpressionEngine/ExpressionEngine/blob/1b28b8572ea479b7a5d0a282da4e664be3eb3849/system/ee/legacy/libraries/channel_entries_parser/components/Relationship.php#L24
It is true that it needs to be documented however.
