### ISSUE TITLE
Update JSON version feed for v6.x

### ISSUE THREAD

**Issue by tommymcgahee** [ExpressionEngine/ExpressionEngine#1276]
**Is your feature request related to a problem? Please describe.**
The JSON version feed, as documented here - https://docs.expressionengine.com/latest/development/json-version-feed.html, was last updated for v5.3.0. 

**Describe the solution you'd like**
It would be nice to have this updated for v6.x.

**Describe alternatives you've considered**
None.

**Teachability, Documentation, Adoption, Migration Strategy**

- [ ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
It looks like the feed is not updated automatically (currently shows 7.2.7 as latest) - @matthewjohns0n can you get that fixed?
Alternatively, we could just remove reference to feed from the docs and ask people to use GitHub API instead https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release

**Comment by matthewjohns0n** [comment]
This feed has been updated to be accurate and will dynamically stay correct in the future.

PR:
https://github.com/packettide/expressionengine.com/pull/407
