### ISSUE TITLE
On the fly image tag pair not outputting file meta description

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#1279]
EE6.0.6

Using the :resize image modifier in a tag pair I'd expect file meta values to be included in the output.

A tag pair like this using the files "Description" field as the ALT parameter value:

```
{block_image:resize width="680" height="680" quality="80" maintain_ratio="y" master_dim="width"}
  <img src="{url}" width="{width}" height="{height}" alt="{description}">
{/block_image:resize}
```
...doesn't process the {description} variable. Instead you get:

`<img src="/path/to/my_image.jpg" width="680" height="327" alt="{description}">`

If you don't use the modifier part it works fine. Seeks like a faux pas with the modifier?

Update: for reference is you use the file's Title variable that works fine, just not the Description variable.

**Comment by bakin1999** [comment]
Thank you for reporting this, I was able to resize an image and get the alt as the description by doing it a slightly different way:

`{blog_image:image}
    	<img src="{blog_image:image:resize width="100" height="100"}" alt="{description}" />
{/blog_image:image}`

Until a fix comes out for described problem, this should work for now.

**Comment by ic360-com** [comment]
I'm running into a very similar issue, when trying to use a Variable Pair to output an image File field.
`{primary_camera_image}<img src="{url}" jqimg="{primary_camera_image}" {if width < height}style="height:400px"{/if} alt="{title}" />{/primary_camera_image}`

...is rendering as...
`https://www.domainname.com/upload_file/product_images/_DSC0910.jpg
<img src="{url}" jqimg="" style="height:400px" alt="_DSC0910.jpg" />`

Very weird.

**Comment by ic360-com** [comment]
PS. My rather nasty workaround is this:
`<img src="{primary_camera_image}" jqimg="{primary_camera_image}" {primary_camera_image}{if width < height}style="height:400px"{/if}{/primary_camera_image} alt="{title}" />`

...which has output this...
`<img src="https://www.domainname.com/upload_file/product_images/_DSC0910.jpg" jqimg="https://www.domainname.com/upload_file/product_images/_DSC0910.jpg" style="height:400px" alt="The Entry Title" />`

**Comment by blue-dreamer** [comment]
@bakin1999 thanks for the fix idea :)

@ic360-com in your first example calling `{primary_camera_image}` inside the `{primary_camera_image}` tag pair will throw that error, likely because `{primary_camera_image}` is already being processed as the tag pair so the only variables available are `{url} {width} {height} ` + file meta data variables. If you use `jqimg="{url}"` it should output the correct image URL.

PS love the `{if width < height}` conditional could have some uses!

**Comment by ic360-com** [comment]
OK thanks, have just tested and that works.  :-)
Think I was confusing myself a bit there.
