### ISSUE TITLE
File upload directory chooser should sort directories alphabetically

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#128]
**Is your feature request related to a problem? Please describe.**
The file upload directory chooser, both in the File Manager, and when uploading a file from the Entry Manager, lists upload directories in the order they were created (I assume, technically, by their (hidden) IDs). When more than a handful of upload directories exist, it becomes progressively harder to locate the intended directory from the list.

**Describe the solution you'd like**
Upload directories should be listed alphabetically in the chooser. This would also create consistency with the alphabetical listing of upload directories in the File Manager side-menu.

(An argument could be made for treating the Main Upload Directory as a special case, as the built-in, default upload directory, and always listing this first, followed by the user-created directories listed alphabetically. This would apply to the File Manager side-menu as well.)

**Comment by kevincupp** [comment]
Good point, will fix, @PaulBaileyAtChan!

**Comment by PaulBaileyAtChan** [comment]
Looks like this was fixed in the File Manager, but not in the file upload modal when editing an entry. My original description alluded to that, but the wording could have been clearer perhaps.
