### ISSUE TITLE
In exp:channel:entries tag, disable="custom_fields" does not exclude joins from query

### ISSUE THREAD

**Issue by rowansentesy** [ExpressionEngine/ExpressionEngine#1280]
**Description of the problem**
We were debugging an issue with a somewhat complex multi-channel `exp:channel:entries` tag, and were running into an issue with MYSQL. 
```
General error: 1116 Too many tables; MySQL can only use 61
tables in a join
```

This error has been introduced after we split out all custom fields into their own tables i.e. exp_channel_data_field_XX. We used the 'Channel Data Migration' addon v1.0.1. This issue is not directly related to this add-on or the migration, it is something to do with how I tried to reduce the number of queries in the entries loop. 

I noticed that all of the custom fields (and their tables) were being linked in the SQL query. I was mucking around with the parameters and tried to exclude the 'custom_fields' via the disable parameter. What I found was quite alarming! 

The `disable="custom_fields"` parameter does NOT actually remove these custom field joins from the query, it seems to only prevent the variables from being accessible in the template.

**How To Reproduce**
1. Create a template with an exp:channel:entries loop. The selected channel needs to have some custom fields assigned to it. The template code could be something like this:
```
{exp:channel:entries channel="blog" limit="1"}
{title}
{/exp:channel:entries}
```
2. Turn on template debugging, and log in as a super-admin. View the template above in a browser.
3. In the debugging section, click on the 'Queries' tab. Find the string (CMD + F) and look for `exp_channel_data_field_`. You should see the 'query file' section showing something like `#system/ee/legacy/libraries/Template.php L:1702 Channel::entries()
`
Notice that this is including the custom field tables, and these joins look like:
`LEFT JOIN exp_channel_data_field_3 ON t.entry_id = exp_channel_data_field_3.entry_id`
4. Go back to the template, and add in `disable="custom_fields"` as per the [documentation](https://docs.expressionengine.com/latest/channels/entries.html#disable)
5. Reload the template in the browser, and look for the same string as above `exp_channel_data_field_`
6. You should find the exact same joins and fields being queried, even though the custom_fields are supposed to be disabled.

**Environment Details:**
 - Version: 5.4.2 & 6.0.6
 - PHP Version:  7.3
 - MySQL Version: mysqlnd 5.0.12-dev
 - Web Server: various

**Possible Solution**
Because of the new and preferred way that EE is storing custom fields in their own tables, AND given the MYSQL limitation we encountered with a maximum of 61 tables in a join, the 'disable="custom_fields"' functionality should absolutely be removing all of the custom field tables from any queries generated from the exp:channel:entries tag. This is a seemingly minor bug, but it has relatively huge implications and overhead required to query all of these tables for no reason whatsoever. The incremental cost of the db server to be running these queries constantly is something that should be avoided.

It might also be worth building in an error message of some sort to give a friendlier EE error when there are too many tables in a query. If this limitation is encountered in an entries tag, the system could provide an error such as:

> Your entries tag is returning too many results and/or too many tables. Consider reducing the number of channels being included or use the 'disable' parameter to improve the performance of this request. 

**Additional context**
We were amazed that this issue hasn't been encountered or reported (as far as we could tell). The MYSQL limit (61 joins) is new to me, and something that I imagine others will encounter with large enterprise-level sites.

**Comment by rowansentesy** [comment]
See the Exception with the query limit info:
[20211111 Query limit - Exception - ExpressionEngine.pdf](https://github.com/ExpressionEngine/ExpressionEngine/files/6995033/20211111.Query.limit.-.Exception.-.ExpressionEngine.pdf)

**Comment by intoeetive** [comment]
@rowansentesy I can confirm the issue really exists.
We need to figure out why the things are built this way, but this definitely needs to be improved.
Thanks for reporting!
