### ISSUE TITLE
[Solved] Legacy Columns in exp_sites Table?

### ISSUE THREAD

**Issue by bsrweb** [ExpressionEngine/ExpressionEngine#1282]
Hello good EE people! Ran into an SQL error when trying to add a new site in an EE 6.0.6 site:

* `'site_system_preferences' doesn't have a default value` [in the `exp_sites` table]

Either I did something wrong or perhaps this is a bug because this site is an upgrade from EE 5 and I noticed that a clean EE 6 install doesn't have this column in the `exp_sites` table (among others in pre-EE 6 sites).

Please let me know if you need further info or testing. Thank you!

**Comment by intoeetive** [comment]
@bsrweb do you have stack trace where we could see what function was trying to access that column?

**Comment by bsrweb** [comment]
Hi @intoeetive thanks for your response. Sorry, not stack trace but I'll need to do this on our production website soon and would be happy to send you one if you can suggest how I could set this up.

**Comment by intoeetive** [comment]
In system settings -> Debugging & Output, set "Error Visibility" to "superadmins only" and turn on "Enable debugging?" switch. That should make full trace appear when error is happening, not just short error text

**Comment by bsrweb** [comment]
Just following up that I was able to add a new MSM site on our production system with no errors and it looks like the database table there does not contain those pre-EE6 columns. So, something weird must have happened on my dev site during the upgrade. Thanks for your attention to this and I'll close this Issue.
