### ISSUE TITLE
Textarea formatting button is blocking common keyboard shortcut Ctrl+A

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#1284]
Ctrl+K is an appropriate shortcut for links, not Ctrl+A — Ctrl+A is a basic system-wide shortcut for "select all". 

![image_2021-08-19_14-09-33](https://user-images.githubusercontent.com/12234507/130059540-fe6efee1-7eca-4709-8eec-d47ba34f32a1.png)

**Comment by bakin1999** [comment]
Thank you for this, the pr will make the default upon install switch to ctrl k instead of ctrl a.  

To change a current shortcut setting on an already existing.  Visit CP->Settings->Content&Design-> HTML Buttons.  From there you can edit the shortcuts for all buttons using the manage table.

**Comment by shbchk** [comment]
Thank you!
