### ISSUE TITLE
Entries search bar issue.

### ISSUE THREAD

**Issue by giganticdesign** [ExpressionEngine/ExpressionEngine#1286]
Had a client ask me about the All Entries search bar acting weird when they try using it. I was able to recreate that … seems like if you don’t type fast enough it starts to replace characters and acts funky. Screenshot attached of the search bar I’m talking about.

More info on the issue:
When the user tries to type in a search query the autocomplete starts to soon. If they are typing slow, the autocomplete starts to bring back results based on their search and as they continue to type it replaces letters and removes letters, etc.

![Screen Shot 2021-08-18 at 8 41 51 AM](https://user-images.githubusercontent.com/21126768/130099765-db5dbb80-2059-4355-b809-0cdf2faf244a.png)

Version: EE 6.0.6
Browser/OS: Mac and PC issue see in Chrome.

**Comment by creativearc-paul** [comment]
+1

**Comment by bakin1999** [comment]
Thank you for reporting this! 

(For future reference for people working on this, same problem is also reported in #1219 so close that as well upon fix.)

**Comment by shbchk** [comment]
For me search doesn't work at all, if there is no channel selected.

**Comment by intoeetive** [comment]
The search-as-you-type feature in Entry Manager has been improved since this has been reported. In some edge cases (like if you type exactly 1 character in a second) there might be some issues, but generally we consider this fixed
