### ISSUE TITLE
Channel form stumbles on multiple question marks in action URL (on submit)

### ISSUE THREAD

**Issue by nathanvanbakel** [ExpressionEngine/ExpressionEngine#129]
**Description of the problem**
If "Force URL query strings" is on then it is not possible to submit the channel form.

**How To Reproduce**
1. Turn "Force URL query strings" on
2. Create a template with a channel form
3. Surf to the template you've just created
3. Type something into a field and hit submit.

**Error Messages**
<pre>Disallowed Key Characters</pre>

This suggests that there is something wrong with the input.    
There is absolutely nothing wrong with the user input. We can disable it. But that is not something we want.

We can do better, right? Let's inspect the form tag. The action is    
<code>https://website-adress.com/?/channel-form-template/35?RET=all-sorts-of-usefull-return-information</code>
_For clarification: 35 is a valid entry._

See the double question mark? That's a problem. I can manually remove it and the entry saves just fine.    

**Environment Details:**
 - Version: 5.1.3
 - PHP Version 7.0.32
 - MySQL Version 5
 - OS: Linux
 - Web Server: Apache, nginx

**Possible Solution**
Not a good solution, but if you're in a rush this works:
The [input](ExpressionEngine/system/ee/legacy/core/Input.php) handling can be turned off or changed. It is on line 994. Just comment out line 994 - 1011. This however is not a real solution, as input handling is something that is quite useful. 

Another solution, of course, is to turn "Force URL query strings" off. But you probably turned it on for a reason...

**Comment by derekjones** [comment]
Can you clarify how you're getting that form action URL? There shouldn't be any additional query string there. Channel Form submits via POST, so it's action URL in your case should just be `https://example.com/?/channel-form-template`

**Comment by nathanvanbakel** [comment]
It's in the (HTML) form tag: action. When I don't force query strings everything works. If I do force query strings I get a very long URL with two question marks and a blank page with <code>Disallowed Key Characters</code>.

**Comment by derekjones** [comment]
I don't replicate with that tag, what is the full URL you are on when you land on the page. And do you have any add-ons installed?

side note: the return= parameter should just be a template path / route and not a full URL, but that doesn't trigger the reported behavior on a fresh install either.

**Comment by nathanvanbakel** [comment]
<code>https://example.com/?/channel-form-template/2?RET=https%3A%2F%2Fexample.com%2F%3F%2Fchannel-form-template%2F2&URI=channel-form-template%2F2&return_url=&author_id=1&channel_id=1&entry_id=2&ACT=1&meta=8%2BLwLBCjWOgG9tEUp1F%2FmgGfpf60kRiam%2F1gxpx3NK4NJghtOzWrUtsqVrp1174jIeErg3cSWyL3YH%2FJ%2BNmhupNfi4lwVZb%2F0rXYvna4dQn%2B5xCvX6UZgiUPcqR47KR07l6ncJ681NEq9e%2B47X7ZBAO0M49nw6R779BLkLpohbSmgzkBAyrcUrMTUesPd4C5v7Ypr%2FdzfYCRd0rBIaimTNUPHloo7cGTEg89RlOHNz6%2BLbvFLXehfLvFM816mX9wD93eik7HJ5r%2FDeJV%2FAIU0Qn2Obf5uAOHGef8gL5F8XTo5ZKkqqnj3EWoXTtB2VsHct4Y8Ni9uH9W7iF%2BEN1hfYOc%2FWpLPmgOgmCzaSKAOoc%3D&checkbox_fields=collection</code>

**Comment by derekjones** [comment]
That's the URL in the address bar? If so, what are you using to create that link?

**Comment by nathanvanbakel** [comment]
It's in address bar after I hit submit on the form.

**Comment by derekjones** [comment]
I'm asking about the URL in the address bar on the page that _renders_ the form. It sounds like your form is not submitting via POST. You'll need to provide steps to show how to make that happen on a fresh installation with no add-ons, as none of this is standard behavior, and I can't replicate your issue with any manner of fiddling. I'd try a different browser or disable browser plugins as well, just in case. Eliminate the variables.

**Comment by nathanvanbakel** [comment]
Thanks.

- I've tried multiple browsers.
- The page that renders the form is <code>https://example.com/my-template-group/5</code>
- There are no extra add-ons installed (not in EE, not in my Browsers)
- Did a quick check: updated my PHP to 7.2
- Checked the browser console: noticed that the <code>https://example.com/my-template-group/5<code> form gets indeed sent via POST.

For me: I can live without "Force URL query strings". But I'd like to understand this behaviour and fix it (if we can).

**Comment by derekjones** [comment]
Yeah I'd like to get to the bottom of it as well, but if there's something in the app that needs modifying, a contributor would need to be able to replicate your issue. 

> Can you think of any other variables?

Well that's why I recommended doing this on a new install, should only take a few minutes at most to spin up, and doing that will remove anything that might be specific to your installation, making it easier to work towards the problem.

The other question mark is the server environment? You mention Apache and nginx, so you've already tried swapping those out to eliminate web server config?

Lastly there are some other [local machine issues](https://stackoverflow.com/questions/6192837/form-being-randomly-submitted-as-get-instead-of-post) that can cause forms to submit via GET instead of POST.

**Comment by nathanvanbakel** [comment]
Okay, I'll try a fresh domain & installation.
I'll edit this when ready.
