### ISSUE TITLE
Add sticky column to entries list

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1293]
Hi!

Please, add the sticky column to the entries list.

![image](https://user-images.githubusercontent.com/931642/130685182-206193c4-e96f-41ce-a1b9-bf6abc5ac98d.png)

The absence of it can cause terrible problems. (I guess I've lost my job...)

- [ ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by robsonsobral** [comment]
I tried to implement this by myself, but couldn't find where. Too much back and forth.

**Comment by intoeetive** [comment]
You probably need `ExpressionEngine\Service\Filter\Columns.php`
Line 35 for default values.

But you also might need to add column definition for it.

**Comment by robsonsobral** [comment]
I thought it would be easier.
