### ISSUE TITLE
Entries search kills MySQL

### ISSUE THREAD

**Issue by itelligence** [ExpressionEngine/ExpressionEngine#1311]
When attempting to perform a entry search in entries section MySQL server load goes high and stays high.
No mater what keyword you enter 

Debugging the query log shows something really strange, the LIMIT parameter doesn't makes sense.

`SELECT COUNT(*) AS `numrows`
FROM (`exp_channel_titles` as ChannelEntry_channel_titles, `exp_channel_data` as ChannelEntry_channel_data)
LEFT JOIN `exp_channel_data_field_12` AS ChannelEntry_field_id_12 ON `ChannelEntry_field_id_12`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_20` AS ChannelEntry_field_id_20 ON `ChannelEntry_field_id_20`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_26` AS ChannelEntry_field_id_26 ON `ChannelEntry_field_id_26`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_32` AS ChannelEntry_field_id_32 ON `ChannelEntry_field_id_32`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_34` AS ChannelEntry_field_id_34 ON `ChannelEntry_field_id_34`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_49` AS ChannelEntry_field_id_49 ON `ChannelEntry_field_id_49`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_50` AS ChannelEntry_field_id_50 ON `ChannelEntry_field_id_50`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_51` AS ChannelEntry_field_id_51 ON `ChannelEntry_field_id_51`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_52` AS ChannelEntry_field_id_52 ON `ChannelEntry_field_id_52`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_53` AS ChannelEntry_field_id_53 ON `ChannelEntry_field_id_53`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_54` AS ChannelEntry_field_id_54 ON `ChannelEntry_field_id_54`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_55` AS ChannelEntry_field_id_55 ON `ChannelEntry_field_id_55`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_56` AS ChannelEntry_field_id_56 ON `ChannelEntry_field_id_56`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_57` AS ChannelEntry_field_id_57 ON `ChannelEntry_field_id_57`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_61` AS ChannelEntry_field_id_61 ON `ChannelEntry_field_id_61`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_65` AS ChannelEntry_field_id_65 ON `ChannelEntry_field_id_65`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_144` AS ChannelEntry_field_id_144 ON `ChannelEntry_field_id_144`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_146` AS ChannelEntry_field_id_146 ON `ChannelEntry_field_id_146`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_150` AS ChannelEntry_field_id_150 ON `ChannelEntry_field_id_150`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_154` AS ChannelEntry_field_id_154 ON `ChannelEntry_field_id_154`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_156` AS ChannelEntry_field_id_156 ON `ChannelEntry_field_id_156`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_157` AS ChannelEntry_field_id_157 ON `ChannelEntry_field_id_157`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_158` AS ChannelEntry_field_id_158 ON `ChannelEntry_field_id_158`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_159` AS ChannelEntry_field_id_159 ON `ChannelEntry_field_id_159`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_160` AS ChannelEntry_field_id_160 ON `ChannelEntry_field_id_160`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_data_field_161` AS ChannelEntry_field_id_161 ON `ChannelEntry_field_id_161`.`entry_id` = `ChannelEntry_channel_data`.`entry_id`
LEFT JOIN `exp_channel_entries_autosave` AS Autosaves_channel_entries_autosave ON `Autosaves_channel_entries_autosave`.`original_entry_id` = `ChannelEntry_channel_titles`.`entry_id`
LEFT JOIN `exp_channels` AS Channel_channels ON `Channel_channels`.`channel_id` = `ChannelEntry_channel_titles`.`channel_id`
LEFT JOIN `exp_members` AS Author_members ON `Author_members`.`member_id` = `ChannelEntry_channel_titles`.`author_id`
LEFT JOIN `exp_member_data` as Author_member_data ON `Author_member_data`.`member_id` = `Author_members`.`member_id`
LEFT JOIN `exp_category_posts` as ChannelEntry_Categories_category_posts ON `ChannelEntry_Categories_category_posts`.`entry_id` = `ChannelEntry_channel_titles`.`entry_id`
LEFT JOIN `exp_categories` as Categories_categories ON `Categories_categories`.`cat_id` = `ChannelEntry_Categories_category_posts`.`cat_id`
LEFT JOIN `exp_category_field_data` as Categories_category_field_data ON `Categories_category_field_data`.`cat_id` = `Categories_categories`.`cat_id`
WHERE ChannelEntry_channel_data.entry_id = ChannelEntry_channel_titles.entry_id
AND (
`ChannelEntry_channel_data`.`site_id`  =  1
)
AND  (
  (
     `ChannelEntry_channel_titles`.`title`  LIKE '%keyword%'
  )
  OR (
     `ChannelEntry_field_id_20`.`field_id_20`  LIKE '%keyword%'
  )
  OR (
     `ChannelEntry_field_id_144`.`field_id_144`  LIKE '%keyword%'
  )
  OR (
     `ChannelEntry_field_id_146`.`field_id_146`  LIKE '%keyword%'
  )
  OR (
     `ChannelEntry_field_id_26`.`field_id_26`  LIKE '%keyword%'
  )
  OR (
     `ChannelEntry_field_id_32`.`field_id_32`  LIKE '%keyword%'
  )
  OR (
     `ChannelEntry_field_id_34`.`field_id_34`  LIKE '%keyword%'
  )
  OR (
    `ChannelEntry_field_id_65`.`field_id_65`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_154`.`field_id_154`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_159`.`field_id_159`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_160`.`field_id_160`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_161`.`field_id_161`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_12`.`field_id_12`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_61`.`field_id_61`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_49`.`field_id_49`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_50`.`field_id_50`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_51`.`field_id_51`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_52`.`field_id_52`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_53`.`field_id_53`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_54`.`field_id_54`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_55`.`field_id_55`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_56`.`field_id_56`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_57`.`field_id_57`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_150`.`field_id_150`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_156`.`field_id_156`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_157`.`field_id_157`  LIKE '%keyword%'
  )
  OR (
      `ChannelEntry_field_id_158`.`field_id_158`  LIKE '%keyword%'
  )
)
LIMIT 18446744073709551615`

**Comment by intoeetive** [comment]
@itelligence what is the error shown by EE? Screenshot with stack trace would be appreciated

**Comment by itelligence** [comment]
I am not sure how to get to stack trace. All that happens is that MySQL server essentially hangs with that query and nothing else works until MySQL service is restarted. 

That query effectively kills the MySQL server.

**Comment by itelligence** [comment]
I am not sure what else I need to add but this issue is really frustrating.
The Ajax call:
`https://www.somedomain.com/admin.php?/cp/publish/edit&search_in=titles_and_content&perpage=25&sort_col=column_entry_date&sort_dir=desc&S=2290e7585e6a5779b9360823eaf78610`

![Untitled](https://user-images.githubusercontent.com/885464/131808970-5a7b4a48-3c5c-471d-a782-2aca01cf3872.jpg)

What else can I provide to help with this bug?

**Comment by robsonsobral** [comment]
Some suggestions. 

1. Does the same happens if you search only titles?
2. Does it happens if you limit the search by channel? 
3. Something similar happened to me years ago. It was some weird character on some field. I don't remember which one. Run the query by yourself and go limiting it until find the database column with problems.

**Comment by intoeetive** [comment]
Internal Slack discussion: https://packettide.slack.com/archives/C030Y8HG9L3/p1681311790526679

**Comment by intoeetive** [comment]
The fix for this has been release in EE 7.3.11: https://github.com/ExpressionEngine/ExpressionEngine/pull/3501
