### ISSUE TITLE
Bug in Forum Installation???

### ISSUE THREAD

**Issue by yiodranis** [ExpressionEngine/ExpressionEngine#1315]
. Fresh install to a fresh website, running only forums. But there is no Signature Preferences section. My Control Panel Edit Signature states: Upload an Image .Image uploads are not enabled. Also on Edit profile I get empty fields…..

<img width="349" alt="screen" src="https://user-images.githubusercontent.com/85391756/131452959-429cf9f9-4676-4a58-9506-7673cf19d854.png">
<img width="1306" alt="blue" src="https://user-images.githubusercontent.com/85391756/131452964-91bb6053-4aa6-425d-86a0-5ae6623029c4.png">
<img width="1349" alt="blue2" src="https://user-images.githubusercontent.com/85391756/131453037-765ae640-a5ca-4033-ad3b-a1d794b3f060.png">

**Comment by bakin1999** [comment]
To fix the error of not being able to upload images as signature, getting the "Image uploads are not available".  You must turn that on as a system configuration override.

https://docs.expressionengine.com/latest/general/system-configuration-overrides.html#sig_allow_img_upload
talks about it in more detail here.

So adding,  $config['sig_allow_img_upload'] = 'y';
should allow images to be set.  There are also all sorts of settings that can be set regarding how large these images can be.

**Comment by yiodranis** [comment]
bakin1999 thank you. That fixed the signatures. What about the  Empty Edit profile fileds?
<img width="1349" alt="131454578-fde34a91-d07e-4c1b-a4b9-0bb91a7b7715" src="https://user-images.githubusercontent.com/85391756/131557773-6a49e17c-8e9c-4b11-b4cb-293cfbf5b37a.png">

**Comment by yiodranis** [comment]
bakin1999, hi again. Everything solved…….to have Profile Fields you must Create some [not there by default] in Custom Member Fields….
