### ISSUE TITLE
Entry preview doesn't work with status "closed"

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#1316]
Hello!

I believe entry preview should work regardless of status. Or not?

**Comment by intoeetive** [comment]
The logic of preview is that you see what the (logged in) visitors of your site will see.

If you need to be able to preview entries that are closed (but not show those to general public), you can use `{is_live_preview_request}` conditional in your template: https://docs.expressionengine.com/latest/templates/globals/single-variables.html#is_live_preview_request

**Comment by shbchk** [comment]
Thanks!
