### ISSUE TITLE
IP to Nation - Update IP Database error 

### ISSUE THREAD

**Issue by tewells** [ExpressionEngine/ExpressionEngine#1320]
EE v6.0.3

Logged in as Super Admin

I'm trying to update the IP to Nation data but I'm getting the following error when selecting the 'Update IP database' button in admin: 'Error: You are not authorized to access this page'

This is being thrown at line 235 in mcp.ip_to_nation.php:

```
        if (! AJAX_REQUEST) {
            show_error(lang('unauthorized_access'), 403);
        }
```

The file URIs are also invalid:

```

        // download
        $files = array(
            'http://geolite.maxmind.com/download/geoip/database/GeoIPCountryCSV.zip',
            'http://geolite.maxmind.com/download/geoip/database/GeoIPv6.csv.gz'
        );
```

**Comment by VarenSwaab** [comment]
I'm receiving a similar error. Install the add-on for a new installation of EE6 and get: IP databse update failed Unable to connect to data provider. So, there is no way to currently use this feature.

**Comment by intoeetive** [comment]
@icasmIT @VarenSwaab we have this reported in https://github.com/ExpressionEngine/IP-To-Nation/issues/1 so I'll have to close this as duplicate
