### ISSUE TITLE
Relationship search doesn't search diacritics

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#1321]
Hi there!

Is it possible to search related entries that have diacritical marks without actually typing them?

For example — I have entry title «Héloïse Théo Ferré». How can I find this entry with a relationships search using simple english keyboard? :)

**Comment by shbchk** [comment]
Regular entries search in CP works with diacritics perfectly well, btw.

**Comment by shbchk** [comment]
I was hoping it will be addressed in 6.1 :)

**Comment by intoeetive** [comment]
This is likely the hidden implication of https://github.com/ExpressionEngine/ExpressionEngine/issues/1058 which is getting fixed in 6.1.2
