### ISSUE TITLE
HTML Buttons

### ISSUE THREAD

**Issue by yiodranis** [ExpressionEngine/ExpressionEngine#1325]
I don't have HTML Buttons in post 

Here are all the details https://expressionengine.com/forums/topic/253195/html-buttons

<img width="1557" alt="fields-1" src="https://user-images.githubusercontent.com/85391756/132054081-20b9a2df-6d3e-4daf-b7da-813547c6d9fd.png">
<img width="1265" alt="buttons" src="https://user-images.githubusercontent.com/85391756/132054087-149ed221-8cd9-40bb-b3fe-5907fff45103.png">
<img width="861" alt="keimeno" src="https://user-images.githubusercontent.com/85391756/132054089-e5ee3066-1d4d-474b-855f-b9390190fbf7.png">

**Comment by intoeetive** [comment]
As per forum thread, the issue only exists in Safari

**Comment by Yulyaswan** [comment]
EE 6.3.5, Safari
<img width="1167" alt="Screenshot 2022-10-11 at 10 29 05" src="https://user-images.githubusercontent.com/23382425/195039514-09e0a7b9-e24d-4d7e-9b60-6c554745a420.png">

**Comment by Yulyaswan** [comment]
I'm closing this issue because we can't reproduce it
