### ISSUE TITLE
Trying to get property 'site_name' of non-object  warning when editing templates

### ISSUE THREAD

**Issue by tyssen** [ExpressionEngine/ExpressionEngine#1333]
When editing templates in the control panel on an EE 6.0.6 site, I get a series of warnings at the top of the page:

> Trying to get property 'site_name' of non-object
> ee/ExpressionEngine/Model/Template/TemplateGroup.php, line 174

and I also get all the folders from `default_site` except for `_partials` copied one folder up, i.e. directly into `templates`.

If I remove all the added folders and go to edit another template in the CP, they get recreated again.

This is happening both locally running PHP 7.4.12 under MAMP and on a Nexcess staging server running PHP 7.4.

The site has only recently been upgraded from EE 2.11.1.

**Comment by intoeetive** [comment]
@tyssen  Would you be able to check something?
If you place `var_dump($this->site_id);` before the line that says `// Cache the sites as we query` in `system\ee\ExpressionEngine\Model\Template\TemplateGroup.php` - what does that output?

**Comment by tyssen** [comment]
`int(1) int(1) int(1) int(1) int(0) ` at the very top of the page and then either `int(1)` or `int(0)` below each of the warnings.

**Comment by intoeetive** [comment]
And if you go to `exp_sites` in your database, what are the `site_id` column values?

**Comment by tyssen** [comment]
Only a single row with 1. `site_name` is `default_site`.

**Comment by tyssen** [comment]
Any further steps to help troubleshoot?

**Comment by intoeetive** [comment]
@robinsowell maybe you have some ideas here?

**Comment by robinsowell** [comment]
It's weird!  I might just make sure exp_templates and exp_template_groups don't have any bad site ids.

select * from exp_templates where site_id != 1
select * from exp_template_groups where site_id != 1

And maybe ....  Nope, that's all I got.  

Anything come from that?  If not, why don't you drop us an email at support@expressionengine.com and if you can give us superadmin and ftp we can take a look.

**Comment by tyssen** [comment]
@robinsowell Yes, I have a bunch of templates with `site_id` = 0 which is related to this:

> I also get all the folders from `default_site` except for `_partials` copied one folder up, i.e. directly into templates.

That happens whenever I access the templates section in the control panel.

If I remove them, they just get recreated again the next time.

**Comment by tyssen** [comment]
I'm doing an upgrade to 6.2.4 and have come across this again and can't remember whether I emailed support@ after your last reply or not.

**Comment by intoeetive** [comment]
I was able to replicate issue with template files saved one directory up only when site's short name is empty.

@tyssen if you still have this issue, can you tell us if there's anything in your config.php or admin.php files that could be setting this? Or an extension?

**Comment by tyssen** [comment]
@intoeetive The site this was happening on seems to have a lot of bugs like this in it as it's been running on EE since 1.x so I decided to completely rebuild the database from scratch by reimporting all the entries. Although that's also presenting its own challenges. :/
