### ISSUE TITLE
When LastPass extension is enabled, tables with checkboxes select all items above

### ISSUE THREAD

**Issue by swierczek** [ExpressionEngine/ExpressionEngine#1342]
**Description of the problem**
On tables with a checkbox column in the Control Panel, with the LastPass extension enabled and being logged in, when clicking on any item (or its checkbox), all of the items previous to this item get "checked" too. I've experienced this on template/partial/variable listings (/admin.php?/cp/design/variables), entry listings (/admin.php?/cp/publish/edit), and files (/admin.php?/cp/files), though I'm sure it happens in other similar places too.

It happens probably 80% of the time (notably not 100%, so replicating this is slightly inconsistent) that I click an item on the page with the LP extension enabled, though disabling the extension seems to prevent this behavior 100% of the time. I've experienced this over the past 3-4 years on different OS's and different browsers, with the only consistent symptom being when I disabled LastPass or logged out of the extension, the problem goes away.

**How To Reproduce**
1. Install the LastPass extension in Firefox or Chrome (and maybe others?)
2. Log in to the LastPass extension
3. Go to any of the above listed places in the CP (files, templates, entries)
4. Click on any item (except the first one) or its checkbox
5. Now that item should be "checked", along with all of the items above that item.

**Error Messages**
No console messages

**Screenshots / Videos / Template Code**
With LastPass enabled and clicking on `partial_blog_first_or_featured`:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/2423727/133126292-4b768a05-24c2-4e31-80d9-46dfdf641ba3.png">

With LastPass disabled and clicking on `partial_blog_first_or_featured`:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/2423727/133126403-6ba73c6e-90d4-4ffa-9b69-e5d8663bb3f3.png">

**Environment Details:**
 - Version: 6.0.6, but I've seen it in past versions (v5.x) too
 - PHP Version: n/a
 - MySQL Version: n/a
 - OS: Mac/Firefox, Mac/Chrome, Windows/Chrome
 - Web Server: n/a

**Possible Solution**
More investigation is required, but I wanted to at least document the behavior. I'm not sure if the solution is adding something to the generated HTML in the control panel (i.e. https://stackoverflow.com/questions/20954944/stop-lastpass-filling-out-a-form), or if there's a setting I can define in LastPass itself to prevent this from happening.

**Additional context**

**Comment by Yulyaswan** [comment]
I tried to reproduce this issue and I can't do it.
@swierczek could you please check if the problem is still on your side?
