### ISSUE TITLE
Add entry ID placeholder to URL title field

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1348]
**Is your feature request related to a problem? Please describe.**
Sometimes the Title and the URL title fields don't matter to the content. It's a rare case, but it happens. In these cases, the URL title field could autofills itself.

**Describe the solution you'd like**
We could have a placeholder `{entry_id}` to the URL Title prefix field.

![image](https://user-images.githubusercontent.com/931642/134218727-0badeca3-51a6-4e36-975d-fe5ad4df6222.png)

**Describe alternatives you've considered**
Probably, I gonna use a JS to random populate this field

**Comment by intoeetive** [comment]
We went for a somewhat different solution for this problem, that will be released in 7.3.0: https://github.com/ExpressionEngine/ExpressionEngine/pull/2677
