### ISSUE TITLE
Sorting entries by number of comments

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#1359]
EE 6.0.6 (updated from EE 5)

When I enable the Comments-column in the Entry-listing and click on the header to sort by comments nothing happens on the front-end.

The AJAX-query in the background (/admin.php?/cp/publish/edit&filter_by_channel=1&search_in=titles_and_content&perpage=25&sort_col=comments&sort_dir=asc&filter_by_keyword=) throws an exception:

`

Exception Caught
Unknown field ChannelEntry.comments

ee/ExpressionEngine/Service/Model/Query/Select.php:706
Stack Trace: Please include when reporting this error

    #0 ee/ExpressionEngine/Service/Model/Query/Select.php(520): ExpressionEngine\Service\Model\Query\Select->translateProperty('comments')
    #1 ee/ExpressionEngine/Service/Model/Query/Select.php(124): ExpressionEngine\Service\Model\Query\Select->applyOrders(Object(ExpressionEngine\Service\Database\Query), Array)
    #2 ee/ExpressionEngine/Service/Model/Query/Select.php(49): ExpressionEngine\Service\Model\Query\Select->buildQuery()
    #3 ee/ExpressionEngine/Service/Model/DataStore.php(275): ExpressionEngine\Service\Model\Query\Select->run()
    #4 ee/ExpressionEngine/Service/Model/DataStore.php(220): ExpressionEngine\Service\Model\DataStore->runQuery('Select', Object(ExpressionEngine\Service\Model\Query\Builder))
    #5 ee/ExpressionEngine/Service/Model/Query/Builder.php(138): ExpressionEngine\Service\Model\DataStore->selectQuery(Object(ExpressionEngine\Service\Model\Query\Builder))
    #6 ee/ExpressionEngine/Service/Model/Query/Builder.php(63): ExpressionEngine\Service\Model\Query\Builder->fetch()
    #7 ee/ExpressionEngine/Controller/Publish/Edit.php(183): ExpressionEngine\Service\Model\Query\Builder->all()
    #8 [internal function]: ExpressionEngine\Controller\Publish\Edit->index()
    #9 ee/ExpressionEngine/Core/Core.php(251): call_user_func_array(Array, Array)
    #10 ee/ExpressionEngine/Core/Core.php(111): ExpressionEngine\Core\Core->runController(Array)
    #11 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
    #12 example.com/admin.php(144): require_once('...')
    #12 example.com/admin.php(144): require_once('...') 

`

**Comment by intoeetive** [comment]
@silenz88 thank you for report!

I have a feeling we have this fixed somewhere in not-yet-released PR, but cannot find it ATM. I am able to replicate the bug though
