### ISSUE TITLE
Icon files fail the image check

### ISSUE THREAD

**Issue by acalvino4** [ExpressionEngine/ExpressionEngine#1361]
When trying to upload an icon file into an image upload directory, one receives the error
```
Cannot Upload File
File not allowed.
```

### Steps to reproduce
* Create an upload directory that can only take images
* Attempt to upload an icon file
* See the error

### I know exactly what needs to be done and can submit a PR.
* In `mimes.php` add the following two lines
```
    'image/vnd.microsoft.icon', //.ico
    'image/x-icon', // .ico
```
* In `MimeType.php`, in the `fileIsImage` function, bypass the `imagecreatefromstring` check for icon files, as they are [not supported](https://www.php.net/manual/en/function.imagecreatefromstring.php) by that function.

Again, I am ready to submit a PR if a project lead can confirm that this would be desired. If there is a contributing guide, just send me a link.

The big argument for needing this is really straightforward: being able to manage favicons via the control panel.

**Comment by acalvino4** [comment]
I noticed that additional mime types can be added via the `mime_whitelist_additions` parameter in my config file. However, because favicons are needed on every website, I think that's a pretty strong argument for making them included by default.

Also, even by adding those mime types to my config, it doesn't solve the problem of them not being recognized as images, hence the need for a PR. If there is a strong reason not to implement my suggested changes, just let me know!

**Comment by acalvino4** [comment]
Loosely Related Issue: https://github.com/ExpressionEngine/ExpressionEngine/issues/304

**Comment by acalvino4** [comment]
Is there any reason not to accept this? If not, I'd love to submit a PR.

**Comment by intoeetive** [comment]
@acalvino4 sorry for delay on this!

I agree, `.ico` files should be considered as images with the same or similar limitations that exist for `.svg`

Please go ahead and submit a PR, we will be greateful for the contribution!
