### ISSUE TITLE
[EE6] Channel form doesn't allow file uploads by guest users

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#1362]
In EE6, channel form file uploads only appear to work if the current user is logged in and has upload access to the relevant file upload directory. This means that channel form submissions by guest users which include file uploads fail — with the error: "You do not have permission to save a file". This happens even if the channel form explicitly allows guest submissions, and the default author for guest entries has access to the upload directory. This issue is new to EE6 — guest submissions with file uploads worked as expected in EE5 — and contradicts the EE6 documentation.

@JCOGS Design presented a deeper analysis of this issue on Slack:

> Working with @Juan Sbaraglia Pinkus have identified that although channel form allows for 'guest posting' both explicitly (via the logged_out_member_id= parameter) and implicitly via the "Allow Guest Submissions" channel setting, it appears that this is not true for file fields - when you try to upload a file using channel form via a logged-out session, the file upload fails reporting a permission error (You do not have permission to save a file).  On digging deeper this error is being generated by the function _check_permissions in the Filemanager class which checks to see if the currently logged in member has upload permissions for the upload directory targeted; it does not appear to have a work-around to proxy the logged_out_member_id= parameter (or that specified in Allow Guest Submissions) in this check as it only tests for the member_id obtained using $member = ee()->session->getMember(); - debugger output indicates that for logged out sessions no session member_id value is set...

This analysis matches the behaviour I've seen. Channel form submissions in EE6 succeed for guest users so long as no file uploads are included; and also succeed **with** file uploads where the current logged-in user has appropriate file upload access. But form submissions with file uploads always fail for guest users.

[EE6.0.6]

**Comment by mkinberg** [comment]
+1 Having the same issues here.  Please prioritize high :-)

**Comment by intoeetive** [comment]
I am unable to replicate this with "minimal" channel form (containing just the title and file field) in EE 6.1.2
Assuming it was fixed as part of something else - @PaulBaileyAtChan  @mkinberg would you be able to confirm it's resolved?

**Comment by PaulBaileyAtChan** [comment]
It does look like it's working for me now, in EE6.1.3, and there's new code in the identified class that looks like it might be doing the right thing. I think this might be the change that fixed it: https://github.com/ExpressionEngine/ExpressionEngine/pull/1201

But rather than just "assuming it was fixed as part of something else", it would be good to look at this change in detail to make sure that it catches all conditions, so that it's not being considered resolved prematurely.

**Comment by intoeetive** [comment]
Unfortunately the changelog for 6.1 - 6.1.2 is too big to easily identify the exact change.

I'll close the issue for now, if someone faces same problem again - please reopen
