### ISSUE TITLE
Category and Entry url title clash

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#1364]
I have a category and an entry that share the same URL title slug.

Using an {exp:channel:categories} tag to generate category links, where the category shares the same URL title slug as an entry the category page shows no results even though entries are assigned to that category.

Renaming the category URL title to something unique outputs the category entries as expected.

I'd expect category URL titles to work independently from regular entries.

**Comment by intoeetive** [comment]
@blue-dreamer is this something that you still see?

I am unable to replicate on EE 7.2.17 when using this code when I have entry and category with same URL title (category group assigned to same channel)

```
{exp:channel:entries channel="news"}
Entry: {title}
{/exp:channel:entries}
<hr>
{exp:channel:categories channel="news"}
Category: {category_name}
{/exp:channel:categories}
```

**Comment by blue-dreamer** [comment]
I can't replicate with latest EE7 so perhaps it has been fixed somewhere along the line.

Probably close this one off!
