### ISSUE TITLE
Query module failure when using url_title

### ISSUE THREAD

**Issue by VarenSwaab** [ExpressionEngine/ExpressionEngine#1365]
Using EE 6.06 and php 7.3

I'm trying to get an entry title using the query module. I'm passing a url_title as segment_2 to the tag and I get the following error. It seems like the parser is mistaking the "-" in the url_title for a "/". Here's the tag:

```
{exp:query sql="SELECT * FROM exp_channel_titles WHERE url_title = {segment_2} "}
{title}
{/exp:query}

```

Here is what the url looks like: **https://mysite.dev/location/1840037856-Marrowstone**
I have an override set in the config file to use "-" in url titles.

Here is the error:

Exception Caught

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Marrowstone' in 'where clause':
SELECT * FROM exp_channel_titles WHERE url_title = 1840037856-Marrowstone

ee/legacy/database/drivers/mysqli/mysqli_connection.php:114

Stack Trace: Please include when reporting this error

#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('SELECT * FROM e...')
#1 ee/legacy/database/DB_driver.php(260): CI_DB_mysqli_driver->_execute('SELECT * FROM e...')
#2 ee/legacy/database/DB_driver.php(175): CI_DB_driver->simple_query('SELECT * FROM e...')
#3 ee/ExpressionEngine/Addons/query/mod.query.php(31): CI_DB_driver->query('SELECT * FROM e...')
#4 ee/legacy/libraries/Template.php(1644): Query->__construct()
#5 ee/legacy/libraries/Template.php(1386): EE_Template->process_tags()
#6 ee/legacy/libraries/Template.php(560): EE_Template->tags()
#7 ee/legacy/libraries/Template.php(228): EE_Template->parse('{!-- ra:0000000...', false, 1, false)
#8 ee/legacy/libraries/Template.php(163): EE_Template->fetch_and_parse('', Array, false)
#9 ee/legacy/libraries/Core.php(647): EE_Template->run_template_engine('', '')
#10 ee/legacy/controllers/ee.php(53): EE_Core->generate_page()
#11 [internal function]: EE->index()
#12 ee/ExpressionEngine/Core/Core.php(251): call_user_func_array(Array, Array)
#13 ee/ExpressionEngine/Core/Core.php(111): ExpressionEngine\Core\Core->runController(Array)
#14 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#15 html/index.php(164): require_once('...')
#15 html/index.php(164): require_once('...')

**Comment by robsonsobral** [comment]
Hi, @VarenSwaab .

Do you mind to try this way?

```
{exp:query sql="SELECT * FROM exp_channel_titles WHERE url_title = '{segment_2}' "}
{title}
{/exp:query}
```

**Comment by intoeetive** [comment]
@VarenSwaab you have an error in your SQL query. You always need to add quotes around the string values (Query module will not do that automatically)

`SELECT * FROM exp_channel_titles WHERE url_title = 1840037856-Marrowstone` is not valid SQL query, however `SELECT * FROM exp_channel_titles WHERE url_title = '1840037856-Marrowstone'` is

As @robsonsobral pointed out, just add quotes
