### ISSUE TITLE
Sort selected fields to top of "Fields" dialog in Channel->Fields form

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#1369]
**Is your feature request related to a problem? Please describe.**
When editing an existing channel definition, on the 'Fields' tab the dialog box relating to fields needs to be scrolled to be able to see which (if any) fields are already selected for this channel. This can make it hard to find out which fields are selected on a site with many fields defined (e.g. MSM ones).

**Describe the solution you'd like**
Change the sort criteria for this dialog box to put any selected fields first, so they will be easily visible without scrolling.

**Describe alternatives you've considered**
n/a

**Teachability, Documentation, Adoption, Migration Strategy**
This feature would not need documentation, would be backward compatible.

- [x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
@ajohnson bringing this into your consideration

**Comment by ajohnson** [comment]
@jcogs-design Thanks for the suggestion! We've put this into the team's dev schedule to get it implemented in a future update. Can't promise a timeframe, but we'll hit you back as/if we have questions.

@intoeetive Created an internal issue to implement this here: https://packettide.atlassian.net/browse/EECORE-1539

**Comment by intoeetive** [comment]
This has been implemented for EE 7 and will also be backported into 6.4.0
