### ISSUE TITLE
Entry Manager "Select All" checkbox does nothing after installing Transcribe addon

### ISSUE THREAD

**Issue by maxbato** [ExpressionEngine/ExpressionEngine#137]
**Description of the problem**
Since I have installed Transcribe. Latest version 3.1.2 on Latest version of EE5 5.1.3, It has rendered the select all check box at the top of a CP entry list useless. It simply wont select the ones below it.

**How To Reproduce**
See attached screenshot

**Error Messages**
There are not error messages. None in js console either

**Screenshots / Videos / Template Code**
![screen shot 2019-02-20 at 8 01 43 pm](https://user-images.githubusercontent.com/7504208/53420421-a05c7b00-3990-11e9-9cb6-4590c08fd9c0.png)

**Environment Details:**
N/A

**Possible Solution**
EEHarbor sent me back the following:
"Technically, this is an EE bug with the way their bulk selector works; it's looking to check the boxes in column 6 but because Transcribe injects a column, the checkboxes become column 7.

We'd recommend opening a bug report with them.

In the meantime, if you do not need the language to be displayed on the Entry Manager page, you can disable the Transcribe extension `cp_js_end` in the `exp_extensions` table. That will stop Transcribe from trying to inject that column. It will also remove the language label from any relationship fields you have (but that's all just aesthetic)."

**Additional context**
None

**Comment by obfuscode** [comment]
EEHarbor: We have looked into this issue on our end and it appears to be a problem with how EE is targeting the checkboxes. It is only looking for checkboxes in the 6th column so when we inject a column, making the checkboxes the 7th column, it is no longer able to find them. Injecting the column after the checkbox column does not seem rational and as there is, at the time of this writing, no official way to add columns to this display, we believe the checkbox selector should be more accurate.

**Comment by maxbato** [comment]
Honesty, I suggest those check-boxes always be in the 1st column. Much easier to get to anyway as long titles cause the additional columns to be hidden. Without horizontal scrolling, you cannot even access them.

i.e:

![screen shot 2019-02-20 at 8 01 43 pm](https://user-images.githubusercontent.com/7504208/53421223-2af1aa00-3992-11e9-8f31-e4e99e759c78.png)

**Comment by kevincupp** [comment]
@obfuscode There is no selector that targets the 6th column for this functionality, there is no selector to change. Are you injecting this column via JavaScript or something? If so, you're probably throwing off the `ee_toggle_all` plugin which relies on keeping track of which column indices contain checkboxes. A contributor would likely need to update that if they want this method of table alteration to work.

**Comment by obfuscode** [comment]
Yes, we're injecting the column via javascript. Is there a way to re-bind the `ee_toggle_all` after we modify the page?

**Comment by kevincupp** [comment]
Not sure. If calling `$('table').toggle_all();` again doesn't work, something probably needs to change in there.

**Comment by ops-andy** [comment]
this no longer seems to be an issue when using Transcribe 3.6.0 and EE 6.0.3.
