### ISSUE TITLE
Debugger only appears on MSM site when logged in via site url

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#1370]
Logged in as a super-admin to an MSM site you can set / deset debugging output for each MSM site separately by switching sites from the menu and navigating to the CP debugging option area.

Regardless of settings however, it appears that debugging **output** for an MSM site will only appear if you log into the EE system using the url for the MSM site you want to see the debugging output for.

Given that the user / super-admin has access to all of the MSM sites within CP and can control the option to display / not display debugging output for any without having to log out / in using the site url concerned, to then not display the debugging output for sites unless such a login change is made seems slightly odd.

A better solution would be ensure that display of debugging output is not constrained in this way.

Using EE 6.0.6 / MSM.

**Comment by silenz88** [comment]
If this is possible the same would apply to live-previews.

**Comment by jcogs-design** [comment]
> If this is possible the same would apply to live-previews.

Have you tried this?

**Comment by robsonsobral** [comment]
Thank you so much, @jcogs-design ! Maybe you've found the reason I can't see the debug profiler!

**Comment by robsonsobral** [comment]
Are you capable of tell me where I can fix this. @jcogs-design ?

**Comment by jcogs-design** [comment]
Probably... busy today but will see if I can diagnose tomorrow: will post update if so.

**Comment by silenz88** [comment]
> 
> 
> > If this is possible the same would apply to live-previews.
> 
> Have you tried this?

![Zwischenablage01](https://user-images.githubusercontent.com/6132998/138296701-cdf6d960-dd03-41f2-8804-a3e4808d5844.jpg)

**Comment by robsonsobral** [comment]
In [case of the debugger](https://github.com/ExpressionEngine/ExpressionEngine/blob/382082af7397d52cc6fd53f294139f832ed6ff0d/system/ee/legacy/libraries/Core.php#L311), `ee('Permission')->isSuperAdmin()` and `ee()->session->userdata('can_debug')` are always returning `FALSE`:

```php
        if ((ee('Permission')->isSuperAdmin() || ee()->session->userdata('can_debug') == 'y')
            && ee()->config->item('show_profiler') == 'y') {
            ee()->output->enable_profiler(true);
        }
```

**Comment by intoeetive** [comment]
Are you people talking about debugger in CP, or on the frontend?

I am unable to spot this issue in the CP
On the frontend, there's a chance you're not really logged in to frontend if you've logged in to CP using different URL (unless you configured [multi-site login](https://docs.expressionengine.com/latest/msm/overview.html#multi-site-login)  )

**Comment by jcogs-design** [comment]
Not sure about the others - I'm talking about the template debugger that appears below a frontend page when debugging is turned on and a superuser logged in...  HTH

**Comment by robsonsobral** [comment]
> Are you people talking about debugger in CP, or on the frontend?

Front end.

**Comment by robinsowell** [comment]
You're probably not really logged in to the frontend.  Try putting a {member_id} tag on it to see.

If you login to the cp, you are only setting the cookie for the url you're on.  So if you visit a url on a different domain, the logged in cookies aren't going to be set.  I think that's what's going on.

When you switch sites in the cp, it doesn't actually change the domain, just the msm site displayed.  So cp works different.  (Though if you have a cp on multiple domains, you'd run into the same issue moving from a cp on one domain to another.

Now live preview?  I think that's a different issue but I'm also not exactly sure what's happening there.
