### ISSUE TITLE
Model Service - Relationships Carrying Count From Parent

### ISSUE THREAD

**Issue by stephengalbraith** [ExpressionEngine/ExpressionEngine#1373]
I am not sure if this is a bug or expected behaviour. It certainly does not seem to be what I would expect to happen.

The behaviour is this. I have two Models: Team and Project. A Team can 'HasMany' Projects and a Project 'BelongsTo' a Team.

I inserted one row in the teams table just to test that the model was working. The output was as expected:

```json
{
    "data": [
        {
            "team_id": 1
        }
    ],
    "total_results": 1
}
```

When I eager load the relationship for Projects and then run the loop to get the number of projects for the team (which should be 0 since there is absolutely nothing in the projects table yet), I get 1.

```json
{
    "data": [
        {
            "team_id": 1,
            "count_projects": 1, // should be 0 
        }
    ],
    "total_results": 1 // number of teams
}
```

Here is the stripped down code I ran to get this result:

```php
$teams = ee('Model')->get('collaborate:Team')
    ->with('Projects')
    ->all();
		
$return_data['total_results'] = $teams->count();
		
foreach($teams as $team)
{	
    $return_data['data'][] = [
        'team_id' => $team->team_id,
        'count_projects' => $team->Projects->count()
    ];
}
		
return json_encode($return_data);
```

So there seems to be something happening where the Relationship Count is perhaps inheriting the count of the parent. I say that because for my next test, if I add a second team and then add 2 projects for team 1, this is the result.

```json
{
    "data": [
        {
            "team_id": 1,
            "count_projects": 2, // expected result
        },
        {
            "team_id": 2,
            "count_projects": 1, // should be 0
        },
    ],
    "total_results": 2 // number of teams
}
```

I am not sure where to look at in the Query Builder to see where I might be able to see where the issue lies, but any help would be appreciated if I am using the Model Service incorrectly. Otherwise, I think this is a small bug that should be resolved. I know there have been previous issues about how the Models interact with Relationships.

**Comment by intoeetive** [comment]
@stephengalbraith I have tested your code (using Channel and Entries models instead of your custom ones; they have the same kind of relationships you are describing).
The data I got in response were correct.
Could there be a duplicate record somewhere?
If you're absolutely positive this is code error and not corrupted database, I'd love to see the full code and maybe sample database dump.

**Comment by stephengalbraith** [comment]
@intoeetive I had moved on from this code shortly after the bug report, so I just spun up a new fresh install of EE and a new test addon with the models. It does appear to work now, so I am not sure what had changed, but I cannot produce it again now. I'll close this. If for some reason I can re-create it, I'll re-open with more info.
