### ISSUE TITLE
exp_channel_data_field_xyz no longer exists

### ISSUE THREAD

**Issue by Fred2341** [ExpressionEngine/ExpressionEngine#1398]
Hi

I am using an external add-on to delete channel data. I now get an error that a certain exp_channel_data_field_xyz  does not exists. The field with that number xyz however does exist. When i explore the SQL manager, it seems most exp_channel_data_field_ have disappeared. Moreover, the exp_channel_data table is overloaded and produces and memory size error when I try to view the contents.

With an almost identical website I have no such errors.

I am running EE 6.0.6.

I hope you have a solution.

Regards

Fred Geiger

**Comment by intoeetive** [comment]
@Fred2341 it looks like you're running into specific issue with third-party add-on.

We strive to keep GitHub for bug reports and feature requests for ExpressionEngine

Please post your question in [Slack](https://expressionengine.com/blog/join-us-in-slack#join-us-on-slack) or on [Forums](https://expressionengine.com/forums)

You may also consider getting help as part of one of our [support plans](https://expressionengine.com/support)

**Comment by Fred2341** [comment]
Sorry, Yuri

I have to disagree. The issue is in the EE database, which I approach with a mysql query. This is not a third party add-on.

Regards

Fred Geiger
M: 06 1092 8658

**Comment by robinsowell** [comment]
Can you help me replicate?  What should we do on a clean install to see the problem in action?

**Comment by Fred2341** [comment]
That will be difficult, Robin, as a clean install shows all data fields. Attached is a screen shot of the current situations:


Note that there are only three exp_channel_data_field_ items left. It seems all data are stored in exp_channel_data. I think that was the case in older versions of EE.  I cannot inspect exp_channel_data, it is too big?

Regards

Fred Geiger
M: 06 1092 8658

**Comment by robinsowell** [comment]
Right- but what did you do that deleted them?  What steps can I take to make it happen?  

Does that make sense?

**Comment by obfuscode** [comment]
Hi Fred, you mentioned you're using an external add-on to delete channel data. What add-on are you using and who makes it? We just want to cross it off as a potential cause of this issue.

We take data loss very seriously and need to narrow down where that is happening.

**Comment by Fred2341** [comment]
Again a tough question.

The website has not been used for more that a year due to Corona.
Data are entered by reading a CSV file. From the website the data (file and associated data) can be deleted using a pi.function.php add-on that I made myself. So it is hard to say when the problem originated, or even what the problem is. The strange thing is that almost all exp_channel_data_fields have gone.

Starting with a clean install is an option, but that is a lot of work. Any thoughts?

Fred Geiger
M: 06 1092 8658

**Comment by Fred2341** [comment]
This is the function that I use:

public function wissen_zitting()
{
    $entry_id   =   ee()->TMPL->fetch_param('zitting_id');
    
    $query      = ee()->db->query("
    SELECT field_id
    FROM exp_channel_fields AS c
    WHERE field_name = 'zittingbestand'
    ");

    $field_id   =   $query->row('field_id');

    $query_tekst    =   "SELECT field_id_$field_id AS bestand
    FROM exp_channel_data_field_$field_id 
    WHERE entry_id = '$entry_id'
    LIMIT 1”;
$query         = ee()->db->query($query_tekst);

The error occurs with the last query.
This is the error:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bcboschenduin_nl_ee2018.exp_channel_data_field_65' doesn't exist:
SELECT field_id_65 AS bestand FROM exp_channel_data_field_65 WHERE entry_id = '35643' LIMIT 1

Indeed, exp_channel_data_field_65 does not exists, whereas a field with ID 65 does.


Fred Geiger
M: 06 1092 8658

**Comment by robinsowell** [comment]
Hrm- well it's really 2 issues.

1. Getting the site back up and running.  By far the easiest option would be rolling back, if you've got a relatively current backup.  If not... I'd be torn between a clean install and adding back just the missing tables.  And which I'd choose would be based on a lot of factors- mostly what's still left in the db.

2.  Fixing whatever caused the tables to be deleted.  That's the bug, and if it's in core it really is mission critical.  I'm just not thinking how it could be.  Like- was it working fine and then you deleted a field or changed it to a different type or... something?  Any chance you have a 'drop' anywhere in the third party add-ons?  Heck, maybe it's environmental and the database got munged, which I have seen happen once or twice.

**Comment by robinsowell** [comment]
You know- if this was an upgrade, and if exp_channel_data is throwing memory errors, it was almost certainly an upgrade, the old fields wouldn't have their own tables.  They'd be in exp_channel_data.

Maybe they didn't get dropped- maybe they never existed.  And the problem is now there are memory issues with exp_channel_data where the field ids did exist as columns.

I'm actually leaning hard toward that.  Hrmmmm- I think you can tell if channel fields are 'legacy' and thus in exp_channel_data by looking at the field table.  Anything interesting there?

**Comment by Fred2341** [comment]
Thanks, Robin.
What I have tried is create a tables and see if they appear in the database table exp_channel_data_field_newnumber.
It does, so the systems works for new data.
I’ll see if I can copy table contents to new tables and then delete the old ones.

Regards

Fred Geiger
M: 06 1092 8658

**Comment by robinsowell** [comment]
well- first check and see if the missing ones are legacy.  if so, they are in exp_channel_data as columns, not in their own tables.

**Comment by robinsowell** [comment]
Yea- in exp_channel_fields see the legacy column?  Are the missing 'tables' legacy?  If so, they never existed as tables.

**Comment by Fred2341** [comment]
How can I check if tables are legacy?

Fred Geiger
M: 06 1092 8658

**Comment by robinsowell** [comment]
check the databse- the exp_channel_fields table- there's a legacy column.

**Comment by Fred2341** [comment]
Yes, all channel_fields are legacy.

Fred Geiger
M: 06 1092 8658

**Comment by robinsowell** [comment]
OK- on a normal install that was upgraded from like v3 or what have you, the old fields have columns in exp_channel_data.  When we upgraded and moved to having a table per field, we left that old data where it was and marked the field as 'legacy' so that we knew whether to look in exp_channel_data or in the field's own table.

If a field is marked legacy?  It shouldn't have a table.

I think maybe the tables never existed.  But the add-on is newer and just assuming the data from a field is going to be in a table, and it's not- it's over there in exp_channel_data.  

Does that make sense?  And does it fit with everything you know?

**Comment by Fred2341** [comment]
It makes sense, Robin.
So if I look for the data in exp_channel_data rather than in
exp_channel_data_field I should be able to retrieve the data. Right?

Regards
Fred

Op vr 8 okt. 2021 17:57 schreef robinsowell ***@***.***>:

**Comment by robinsowell** [comment]
Correct.  And if it's a custom add-on, you could even do a check on the field id and determine whether to look in exp_channel_data or for a table.  Find the very first field id that is NOT legacy- that and anything higher than that is going to be in a table.  Fingers crossed, should be an easy fix.

**Comment by Fred2341** [comment]
Final question, Robin.
It appears that from the 115 channel fields, only 4 are not legacy.
With future upgrades of EE, do the channel fields remain legacy?

Regards

Fred Geiger
M: 06 1092 8658

**Comment by robinsowell** [comment]
Yes- the old ones remain legacy, any new ones will not be legacy and will have their own table.  If there's a big problem with the exp_channel_data table being too large, we have some options.  But if it's working, I expect it to keep working all else equal.

**Comment by Fred2341** [comment]
The website is working ok, except that I cannot inspect the
exp_channel_data table.
Would removing superfluous data solve that?

Regards
Fred

Op vr 8 okt. 2021 18:14 schreef robinsowell ***@***.***>:

**Comment by robinsowell** [comment]
Well it would, but I wouldn't manually remove anything.  It's more likely to break things than fix them.

You should be able to access the table via something outside of ee- like phpmyadmin through your host's control panel?  I would expect that to work.  That would probably be the easiest option.

But I personally wouldn't mess with the table if it's working.  If you wanted to delete fields you know you don't need via the control panel, that should be fine.  But at this point, I'd definitely make a good backup of the database before doing anything.  Best to be cautious.

**Comment by Fred2341** [comment]
Thanks, Robin

Op vr 8 okt. 2021 18:20 schreef robinsowell ***@***.***>:

**Comment by robinsowell** [comment]
NP- it was an interesting mystery!  I'm like 'what the heck is deleting tables!!!!!'  That just doesn't happen by accident!

Have a good one!

**Comment by Fred2341** [comment]
Hi Robin

Checking for the legacy value and then deleting from the correct table worked well.
Thanks again for your help.

Regards

Fred Geiger
M: 06 1092 8658
