### ISSUE TITLE
Translation tool issue - modify / damage the HTML tags (EE 6.1.x)

### ISSUE THREAD

**Issue by Caleydon** [ExpressionEngine/ExpressionEngine#1399]
Hello,

the translation tool is broken and also modify / damage an existing translations. 

A few examples - try to edit and save existing translations:

`<abbr .... tag is converted into <a ...`

`you\'re is converted into you\\'re and after repetative saving another backslash is added. In the end you can get \\\\\\\\'`

`<a href=\'%s\' rel=\'external\'> is converted into <a >`

`"%s" is converted into \\\\"%s\\\\"  `

`%1\$s is converted into %1$s`

--------

After saving the translations that contain DOC_URL PHP variable (e.g. require_cookie_consent_desc, enable_php_desc etc.) are converted into following URL: https://docs.expressionengine.com/v6/
Shouldn't there be a PHP variable left?

Typo 'anonimized' in 'anonymize_consent_logs_desc' translation string.

Thank you.

**Comment by robsonsobral** [comment]
https://github.com/ExpressionEngine/ExpressionEngine/issues/1125
