### ISSUE TITLE
Parse file directories on `exp:query` module

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1400]
**Is your feature request related to a problem? Please describe.**
Why not? Isn't one of the great features of eecms to be flexible?

**Describe the solution you'd like**
Clear and concise? Ok!

```
        if (strpos($str, '{filedir_') !== false) {
            ee()->load->library('file_field');
            $str = ee()->file_field->parse_string($str);
        }
```

**Describe alternatives you've considered**
Alternatives? Get only the IDs and nest a `exp:channel:entries`! (Die, performance! Die!)

**Teachability, Documentation, Adoption, Migration Strategy**
I guess, it would work automagically, right?

- [x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by TomJaeger** [comment]
I think this is a solid idea.  Would really have to have a parameter to enable, or a different template tag to ensure we maintain existing sites built without it.
