### ISSUE TITLE
E_DEPRECATED with dynamic channel parameters

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#1402]
Deprecated
implode(): Passing glue string after array is deprecated. Swap the parameters
ee/ExpressionEngine/Addons/channel/mod.channel.php, line 559

Severity: E_DEPRECATED

Code:
```
<form method="post" action="{path='group/index'}">

<input type="hidden" name="csrf_token" value="{csrf_token}" />
<label class="filter-label">Select one</label>
<select id="select_one" name="category[]" onchange="this.form.submit()">
<option value="">Select country...</option>
{exp:channel:categories channel="channel" style="linear" category_group="2" show_empty="no" disable="category_fields"} 
<option value="{category_id}">{category_name}</option>
{/exp:channel:categories}
</select>

<label class="filter-label">Select two</label>
<select id="select_two" name="category[]" onchange="this.form.submit()">
<option value="">Select one...</option>
{exp:channel:categories channel="channel" style="linear" category_group="4" show_empty="no" disable="category_fields"} 
<option value="{category_id}">{category_name}</option>
{/exp:channel:categories}
</select>

</form>

{exp:channel:entries channel="channel" limit="12" dynamic="yes" dynamic_parameters="category[&]" disable="member_data|category_fields"}
{title}
{/exp:channel:entries}
```

6.1.1, PHP 7.4.21

**Comment by shbchk** [comment]
That was on dev server. This is on production:

Warning: include(/var/www/vhosts/production.com/ee6system/ee/legacy/errors/error_php.php): failed to open stream: No such file or directory in /var/www/vhosts/production.com/ee6system/ee/legacy/core/Exceptions.php on line 113

Warning: include(): Failed opening '/var/www/vhosts/production.com/ee6system/ee/legacy/errors/error_php.php' for inclusion (include_path='.:/opt/plesk/php/7.4/share/pear') in /var/www/vhosts/production.com/ee6system/ee/legacy/core/Exceptions.php on line 113

Warning: include(/var/www/vhosts/production.com/ee6system/ee/legacy/errors/error_php.php): failed to open stream: No such file or directory in /var/www/vhosts/production.com/ee6system/ee/legacy/core/Exceptions.php on line 113

Warning: include(): Failed opening '/var/www/vhosts/production.com/ee6system/ee/legacy/errors/error_php.php' for inclusion (include_path='.:/opt/plesk/php/7.4/share/pear') in /var/www/vhosts/production.com/ee6system/ee/legacy/core/Exceptions.php on line 113

Warning: include(/var/www/vhosts/production.com/ee6system/ee/legacy/errors/error_php.php): failed to open stream: No such file or directory in /var/www/vhosts/production.com/ee6system/ee/legacy/core/Exceptions.php on line 113

Warning: include(): Failed opening '/var/www/vhosts/production.com/ee6system/ee/legacy/errors/error_php.php' for inclusion (include_path='.:/opt/plesk/php/7.4/share/pear') in /var/www/vhosts/production.com/ee6system/ee/legacy/core/Exceptions.php on line 113

Warning: include(/var/www/vhosts/production.com/ee6system/ee/legacy/errors/error_php.php): failed to open stream: No such file or directory in /var/www/vhosts/production.com/ee6system/ee/legacy/core/Exceptions.php on line 113

Warning: include(): Failed opening '/var/www/vhosts/production.com/ee6system/ee/legacy/errors/error_php.php' for inclusion (include_path='.:/opt/plesk/php/7.4/share/pear') in /var/www/vhosts/production.com/ee6system/ee/legacy/core/Exceptions.php on line 113

**Comment by intoeetive** [comment]
@shbchk these are the separate issues. For the second one, if you still have it - please check if the files are really present on server, and if yes - please create separate issue.

We will address the first one

**Comment by shbchk** [comment]
Yes, files was missing due to .gitignore misconfiguration. Thanks!
