### ISSUE TITLE
Unnecessary JOINs on search module

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1403]
**Is your feature request related to a problem? Please describe.**
The performance of Search module isn't that by itself. However, there are some unnecessary `OR` and `JOIN`s. For example, the comments table is [left joined even with `search_in` not set to `everywhere`](https://github.com/ExpressionEngine/ExpressionEngine/blob/1b4080febb757f07edb7221edd15dde5ee42ae80/system/ee/ExpressionEngine/Addons/search/mod.search.php#L501) and the categories are also [always left joined](https://github.com/ExpressionEngine/ExpressionEngine/blob/1b4080febb757f07edb7221edd15dde5ee42ae80/system/ee/ExpressionEngine/Addons/search/mod.search.php#L504).

**Describe the solution you'd like**
I did little tweaks which fix that, but I think the best is to rewrite everything using [ActiveRecord](https://docs.expressionengine.com/latest/development/legacy/database/active-record.html#selecting-data).

The [sql_andor_string()](https://docs.expressionengine.com/latest/development/legacy/libraries/functions.html#sql_andor_stringstr-field-prefix---null--false) function also needs a variant which uses `IN` instead of `OR`.

I already started to refactor, but I'm going to need some help on tests.

- [ ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by robsonsobral** [comment]
@intoeetive , hi!

Please, what's the currently preferable method for queries? [Model Services](https://docs.expressionengine.com/latest/development/services/model.html) or [ActiveRecord](https://docs.expressionengine.com/latest/development/legacy/database/active-record.html#active-record)?

I'm under the impression that everything with **exception to the search itself** should be got from Model Services.

**Comment by intoeetive** [comment]
Well you cannot fetch _everything_ using the Model Service. You can only manipulate the models. I believe the Models Service was not intended as replacement for Active Record, so it's fine to use AR if you need to manipulate something that's not a model (or your query is too complex or too simple to be handled via models)

**Comment by robsonsobral** [comment]
@intoeetive , good morning!

Have you write tests for search module? I'm asking because I can't make sense of the [following code](https://github.com/ExpressionEngine/ExpressionEngine/blob/1b4080febb757f07edb7221edd15dde5ee42ae80/system/ee/ExpressionEngine/Addons/search/mod.search.php#L943):

```php
protected function getAllQueryParts()
{
    $query_parts = $this->build_standard_query();

    // starting next line, this looks like a dead legacy code
    if (! empty($this->custom_fields)) {
        // This loop is running again and again for every custom field
        // without change a thing and merging arrays exactly equals
        foreach (array_keys($this->custom_fields) as $i) {
            $qp = $this->build_standard_query();

            if ($query_parts === false) {
                $query_parts = $qp;
            } else {
                if ($qp) {
                    $query_parts['entries'] = array_merge($query_parts['entries'], $qp['entries']);
                    $query_parts['channel_ids'] = array_merge($query_parts['channel_ids'], $qp['channel_ids']);
                }
            }
        }
    }

    // Set absolute count
    $this->num_rows = $query_parts ? count(array_unique($query_parts['entries'])) : 0;

    return $query_parts;
}
```

The custom fields are [already being searched](https://github.com/ExpressionEngine/ExpressionEngine/blob/1b4080febb757f07edb7221edd15dde5ee42ae80/system/ee/ExpressionEngine/Addons/search/mod.search.php#L635). I guess, whether you remove or keep this code, the search results will be the same.

Have I found the major cause of bad search performance?!

**Comment by intoeetive** [comment]
It could possible be the case. We don't have any tests around search

**Comment by robsonsobral** [comment]
I've been able to reduce queries without editing a single one. Just moving things around. I guess I'm going to do a PR before rewrite to ActiveRecord. It could be a good improvement already.
