### ISSUE TITLE
Typo in naming of a class file - Writable instead of Writeable

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#1405]
The Validation Service's built-in rule `writeable` relies upon the existance of a class `Service/Validation/Rule/Writeable` but this file in the distribution is called [Writable](https://github.com/ExpressionEngine/ExpressionEngine/blob/6.dev/system/ee/ExpressionEngine/Service/Validation/Rule/Writable.php), and so attempts to use this validation rule trigger an exception error.

Tested on EE 6.0.6 but as link above indicates the github code base has this wrong file name, so presumably also affects other versions linked to this code base.

**Comment by intoeetive** [comment]
@jcogs-design can you point me to the file where `writeable` validation rule is being called or defined? I can't find any reference to it in the current codebase

**Comment by jcogs-design** [comment]
[Here...](https://docs.expressionengine.com/latest/index.html) 
Or you could have searched the docs... 
![Screenshot 2021-10-11 at 18 28 50](https://user-images.githubusercontent.com/13821249/136831155-66ebe5a7-f294-4544-a53a-84d0de4bf237.png)

**Comment by intoeetive** [comment]
Ah, so it's typo in the docs. I was confused because this issue is in main EE repo.

**Comment by jcogs-design** [comment]
It is not, I think, a typo in the docs - it is a typo in the code base. Writable is not a word in common use (possibly it might mean something that can be pursued via legal challenges), Writeable is (and this is the state that library checks for, and the documentation describes).

I think the reason why it has not come up before is (as far as I can tell) no part of EE core ever uses the writeable test of validation library (I suspect that the tests for writeability performed when processing the path settings use some other test - which is odd in itself), so it never actually gets fired by EE core. The absence of any reports of bugs in Github suggest that perhaps I am the first to even try and use it for a while...

**Comment by intoeetive** [comment]
It might be typo in the sense of English grammar, but the code is using `Writable` - whether this is grammatically correct or not - so we'll need to update the docs to use that

**Comment by jcogs-design** [comment]
Really? That's ludicrous. Looks like there are 203 instances of **writable** in the code base across 67 files, with what looks like a reasonable number of those being use in lang() references.

**Comment by jcogs-design** [comment]
Just for the record, changing the documentation won't eliminate the bug... this rule also causes the `unknown validation rule` error on EE6.0.6... 
```
            $validator->setRules(array(
                'img_cp_default_cache_duration' => 'isNatural|required',
                'img_cp_default_cache_directory' => 'writable|required',
                'enable_img' => 'enum[y,n]',
                'img_cp_enable_debugging' => 'enum[y,n]'
            ));
```
![Screenshot 2021-10-12 at 09 21 51](https://user-images.githubusercontent.com/13821249/136919407-0bca7e18-458a-4a16-8f18-d079901e04b3.png)

**Comment by intoeetive** [comment]
What you hit here might be a different bug, because `Writable` validation rule definitely exists, but is not found for some reason. I'll get this investigated

**Comment by intoeetive** [comment]
@jcogs-design I'm unable to replicate this. Does the file `system\ee\ExpressionEngine\Service\Validation\Rule\Writable.php` exist on your installation or you have renamed it?
