### ISSUE TITLE
{total_pages} only reports count of search hits for last set of custom fields 

### ISSUE THREAD

**Issue by natzmaton** [ExpressionEngine/ExpressionEngine#141]
After moving from EE2 to EE5, our search-result page now reads "_n_ results for _keyword_" despite many more than _n_ results appearing below.

I see that `Search->getAllQueryParts()` calls `Search->build_standard_query()` once, and then once again for each item in array `Search->custom_fields` (i.e., if there're 4 items in `Search->custom_fields`, `Search->build_standard_query()` gets called 5 times).

However, because `Search->build_standard_query()` overwrites `Search->num_rows` every time it gets called (line 1069 of `mod.search.php` in EE 5.1.3) …

`$this->num_rows = $query->num_rows();`

… `$this->num_rows` only reflects the count from the final call of `Search->build_standard_query()`, and therefore `Search->do_search()` only writes this lesser number to `exp_search`.`total_results`.

In turn, EE reads this this wrong count from `exp_search`.`total_results` and displays it atop the search-result page.

I have tested and confirmed that using a combined (`+=`) operator instead fixes this bug; I therefore propose changing line 1069 of `mod.search.php` to:

`$this->num_rows += $query->num_rows();`

**Comment by natzmaton** [comment]
Upon review, my solution wasn't quite right, but this was:

```
diff --git a/system/ee/EllisLab/Addons/search/mod.search.php b/system/ee/EllisLab/Addons/search/mod.search.php
index 214be1df..68b2d978 100644
--- a/system/ee/EllisLab/Addons/search/mod.search.php
+++ b/system/ee/EllisLab/Addons/search/mod.search.php
@@ -29,6 +29,7 @@ class Search {
 
 	protected $_meta 	= array();
 	protected $custom_fields = [];
+	protected $hits = array();
 
 	/**
 	 * Do Search
@@ -1077,11 +1079,14 @@ class Search {
 		foreach ($query->result_array() as $row)
 		{
 			$return['entries'][] = $row['entry_id'];
+			$this->hits[] = $row['entry_id'];
 			$return['channel_ids'][] = $row['channel_id'];
 		}
 
 		$return['channel_ids'] = array_unique($return['channel_ids']);
 
+		$this->hits = array_unique($this->hits);
+
 		/** ----------------------------------------------
 		/**  Set sort order
 		/** ----------------------------------------------*/
@@ -1146,6 +1151,8 @@ class Search {
 			}
 		}
 
+		$this->num_rows = count($this->hits);
+
 		return $query_parts;
 	}
 

```

**Comment by robinsowell** [comment]
Thanks! I had confirmed the bug, but new the first fix wasn't quite getting them all.  I'll test this one out tomorrow!

**Comment by robinsowell** [comment]
OK, give this commit a try: https://github.com/ExpressionEngine/ExpressionEngine/commit/80fc70e04724eeabaa32c2f05e657a19f6309e25

That get everything squared away for you?

**Comment by natzmaton** [comment]
Yes, it does! Thank you very much!!

**Comment by robinsowell** [comment]
Excellent, I'll put in a pull request.  Thanks for the confirmation and the excellent debug.
