### ISSUE TITLE
Request module doens't know how to deal with an array

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1426]
In case of a query string like `/test/?category[]=4&category[]=5&category[]=6`, we get:

```
Array to string conversion

ee/legacy/libraries/Template.php, line 1728

    Severity: E_NOTICE
```

And just `Array` is printed.

Shouldn't it return `4|5|6`, the infamous eecms array notation?

**Comment by intoeetive** [comment]
Just to make sure, what is the template tag that you use here?

**Comment by robsonsobral** [comment]
🙄 `{exp:request:get name="category"}`?
