### ISSUE TITLE
exp:consent:cookies showing cookie info not in use

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#1427]
The new `exp:consent:cookies` tag that lists out cookie info is a nice addition but it also outputs info for cookies that aren't used (such as forum cookies even if forum isn't installed). What's more alarming is that it outputs control panel cookie info as well (possible security issue there?).

Ideally there would be a way to control what cookie info gets displayed in the tag, either:

1. In the CP a setting per cookie whether to include in the tag output or not
2. Additional parameters for the `exp:consent:cookies` to control output, e.g. show_cp_cookies="y|n"

**Comment by intoeetive** [comment]
You are right in the sense that the cookies get registered if an add-on is present, but not installed. I'll probably qualify this as bug and work on a fix.

Unfortunately there is no way for us to tell whether certain cookie is used in CP, on frontend, or both. I'll see if we can use `exclude` parameter though to remove certain cookies from output.
