### ISSUE TITLE
Grid Field within Fluid Field gets cut off.

### ISSUE THREAD

**Issue by acalvino4** [ExpressionEngine/ExpressionEngine#1429]
When having a grid field within a Fluid Field, the editing pane get's cut off on smaller screens, as below.
![image](https://user-images.githubusercontent.com/43254861/137373339-db1e61b8-f828-470e-a13c-9745a10587d1.png)

This occurs at `/admin.php?/cp/publish/edit/entry/#`

The interface is somewhat responsive in that when it gets small enough, it does snap to a vertical arrangement that works well.

However, the in-between screen width is at times unusable since I can't edit the content on the far right. The easiest (and probably best) solution would be to give that portion of the editor a horizontal scroll bar, rather than it overflowing the parent container.

- [x] I am available, able, and willing to work on this fix if it is approved.

**Comment by robsonsobral** [comment]
Isn't better to wrap them as flex items? I'm really guessing here.

 (The SASS build process of EECMS scare me!)

**Comment by acalvino4** [comment]
Yes, that's definitely the best solution, but it might involve some more UI considerations that I'm not totally aware of. creating a horizontal scroll for that box is not the best solution; just probably the easiest, and better than the current behavior.

**Comment by robsonsobral** [comment]
I took a look at the code. I could fix that "properly", but it would not be simple. Better to go with the simpler approach.

I'm sorry.

**Comment by acalvino4** [comment]
Haha I thought that might be the case, hence why I figured on a scroll. I'll try to submit a PR with an overflow-scroll of some sort when I get the chance.

**Comment by Yulyaswan** [comment]
@acalvino4  Thank you for your submission!
Your idea about adding scrolling is really great, but IMO it’s better to add scroll inside the `Fluid field`. Because adding it to the `.tab` is too global and can create problems in the future.

Please check this PR - https://github.com/ExpressionEngine/ExpressionEngine/pull/1507

**Comment by dankingsley** [comment]
Do we have an ETA on this being fixed? It's currently a really big frustration for one of my clients where we have a fair few grids within fluid.

**Comment by TomJaeger** [comment]
I think we looped back into it a bit earlier this week.  Ideally it would be shipped next week (we're planning 6.2.4 for next week).  We ran into some issues in testing with the fix the last go around; so as long as their all resolved we should be in good shape!

I'm sorry I don't have something more definitive then this currently.

**Comment by intoeetive** [comment]
This has been resolved in referenced PRs, and the fix released
