### ISSUE TITLE
dbforge->add_key(array()) does not create a multi key

### ISSUE THREAD

**Issue by obfuscode** [ExpressionEngine/ExpressionEngine#143]
**Description of the problem**
When creating a new database table, the `dbforge->add_key(array())` function is adding individual, non-sequenced keys.

I tried this with and without the primary key column.

**How To Reproduce**
```php
ee()->load->dbforge();
ee()->dbforge->add_field(array(
    'id'         => array('type' => 'int', 'constraint' => '10', 'unsigned' => true, 'auto_increment' => true),
    'site_id'    => array('type' => 'int', 'constraint' => '10', 'unsigned' => true, 'null' => false),
    'channel_id' => array('type' => 'int', 'constraint' => '10', 'unsigned' => true, 'null' => false)
));

ee()->dbforge->add_key('id', true); // Primary
ee()->dbforge->add_key(array('site_id', 'channel_id')); // Multi

ee()->dbforge->create_table('test_table');
```

**Screenshots / Videos / Template Code**
<img width="570" alt="indexes" src="https://user-images.githubusercontent.com/2160089/53684933-e479b380-3ce1-11e9-9348-e5ae6cd3b0fc.png">

**Environment Details:**
 - Version: 5.1.3
 - PHP Version: 7.1
 - MySQL Version: 5.7
 - OS: macOS
 - Web Server: nginx

**Comment by derekjones** [comment]
`add_key()` isn't designed to make multi-column keys. An array input just allows you to make many keys in a single line for convenience. Is it documented somewhere that that should make a multi-column key?

**Comment by obfuscode** [comment]
Yes, in both the [CodeIgniter](https://www.codeigniter.com/user_guide/database/forge.html#adding-keys
) and [ExpressionEngine](https://docs.expressionengine.com/latest/development/legacy/database/forge.html#add_keykey-primary--false) docs:
```
ee()->dbforge->add_key(array('blog_name', 'blog_label'));
// gives KEY `blog_name_blog_label` (`blog_name`, `blog_label`)
```

**Comment by derekjones** [comment]
Ok! Looks like that's definitely the intent in [`mysqli_forge`](https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/system/ee/legacy/database/drivers/mysqli/mysqli_forge.php#L168) as well, but DB_Forge doesn't let arrays get through. Looks like it is a bug that was [fixed in CodeIgniter](https://github.com/nonchip/CodeIgniter/commit/1b2d8aef9e09ca0f5b02d0dad85150f0d7f3b1e6) that should also work here.
