### ISSUE TITLE
Live Preview giving notices when using exact keyword search on `exp:channel:entries`

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#1434]
Notice
Undefined offset: 1
ee/ExpressionEngine/Addons/channel/mod.channel.php, line 2293

Severity: E_NOTICE
Notice
Undefined index:
ee/ExpressionEngine/Addons/channel/mod.channel.php, line 2295

Severity: E_NOTICE

EE 6.1.1

**Comment by intoeetive** [comment]
This might be as well and error in the template. How does your `exp:channel:entries` tag look like?

**Comment by shbchk** [comment]
`{exp:channel:entries channel='films' limit='1' require_entry='yes' disable='member_data|pagination|category_fields'}`

And a lot of stuff inside. If you wish, I can DM you the whole template in Slack :)

**Comment by intoeetive** [comment]
Please do. The tag seems pretty straigtforward, there might be something inside it though causing the preview to fail.

Few extra questions:
- what is your PHP version?
- does the front-end output for this entry/template work fine?

**Comment by shbchk** [comment]
> what is your PHP version?

Right. Completeley forgot, sorry. PHP 7.4.24

> does the front-end output for this entry/template work fine?

Yep. Front-end works okay, without any warnings. And yes, preview shows warnings only for this channel\template.

**Comment by intoeetive** [comment]
Testing showed that this code was causing the error (presumably the `not` part)
> {exp:channel:entries channel="films" entry_id="not {segment_2}" limit="12" search:film_vurchel_pick_toggle="=1" search:film_full="not IS_EMPTY" dynamic="no" disable="categories|member_data|pagination|category_fields"}
