### ISSUE TITLE
Apostrophe causes error

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#1443]
field_name (text input) content: 

> Gobelins - L'École de l'Image

Template code:
`{if "{grid_field:relationship_field:field_name}" != ""}<div>{grid_field:relationship_field:field_name}</div>{/if}`

Error: 

```
You have an invalid conditional in your template. Please review your conditionals for an unclosed string, invalid operators, a missing }, or a missing {/if}.
Parser State: Unexpected ‘École’ (VARIABLE); expected RD in Template “group/template” on line 133.
```

EE 6.1.3

**Comment by shbchk** [comment]
And there is no error when I change code to this: 

`{if grid_field:relationship_field:field_name != ""}<div>{grid_field:relationship_field:field_name}</div>{/if}`

or this:

`{if grid_field:relationship_field:field_name}<div>{grid_field:relationship_field:field_name}</div>{/if}`

**Comment by robsonsobral** [comment]
A long time ago, in a distant galaxy, when a developer called Pascal rewrote the template conditionals, to use `{if grid_field:relationship_field:field_name}` become the preferred method.

When you write `{if "{grid_field:relationship_field:field_name}"}`, you're replacing the variable with its value and delaying the conditional evaluation to the following parsing step. Do you really need to do that, @shbchk ?

**Comment by shbchk** [comment]
I guess I do not. Thanks for clarification!

**Comment by robsonsobral** [comment]
You're welcome! Please, close the issue if there isn't something else.
