### ISSUE TITLE
Grid field throws JS error with jQuery 3 in channel forms

### ISSUE THREAD

**Issue by 620studio** [ExpressionEngine/ExpressionEngine#1462]
Web application for client, using channel forms for customer information update. Here's my CF tag:

`{exp:channel:form channel="company" entry_id="{segment_4}" include_jquery="no" json="yes" class="cf-ajax-form gsm-form" id="edit-company"}`

Was working fine in 6.0.6, but now I'm at 6.1.4 it's not working any longer. I've attached a screenshot of the response on submission.

<img width="889" alt="Screen Shot 2021-10-19 at 5 33 04 PM" src="https://user-images.githubusercontent.com/563396/138001569-5f1ac54c-97cb-42aa-ba17-bd58630c7c3e.png">

Here's my js ajaxForm code:

`// edit company
	$('.cf-ajax-form#edit-company').ajaxForm({
		dataType: 'json',
		success: function(data) {
				if (data.success) {
					$('#response').html('<h3>Successfully updated!</h3><p><a href="/projects/company/all"><i class="fas fa-chevron-circle-left"></i> Back to Company List</a> ').addClass('success');
					$('#submit-response').slideDown();
				} else {
					$('#response').html('<h3>Something went wrong!</h3><p>Error: '+JSON.stringify(data.field_errors)+'</p>').addClass('error');
					$('#submit-response').slideDown();
				}
		}
});
`

**Comment by intoeetive** [comment]
@620studio I have not been able to replicate this in Chrome when using EE 6.1.4 with the latest jQuery Form Plugin and your javascript code.

The JSON on screenshot looks correct to be, so this might some some javascript error. Do you see anything if you open developer console in browser?

**Comment by 620studio** [comment]
Using Chrome, I get this error in the console:

`DevTools failed to load source map: Could not parse content for https://portal.goldstandardir.com/redactor.min.js.map: Unexpected token < in JSON at position 1`

I did update the RTE fields from CKEditor to Redactor (which was the main reason for upgrading to 6.1.3 to begin with). Switching it back to CKEditor still brings up the console error and still redirecting.

I'll try reducing the form to the bare minimum to see if it still redirects.

**Comment by 620studio** [comment]
I tried narrowing it down to a single field and verified the console didn't have any more errors. Checked in Firefox and Chrome and both having the same redirect behavior. 

I've attached the code below but for the sake of time spent and the client needing to move forward; I removed the json functionality and did a simple page redirect.


```
{exp:channel:form channel="company" entry_id="{segment_4}" include_jquery="no" json="yes" class="cf-ajax-form gsm-form" id="edit-company"}
	<label for="company_symbol">Symbol</label>
	{field:company_symbol}
	<input name="submit" type="submit" value="Update Company" />
<div id="submit-response" style="display: none;">
	<div id="response">
	</div>
{/exp:channel:form}
```

`$('.cf-ajax-form#edit-company').ajaxForm({
		dataType: 'json',
		success: function(data) {
				if (data.success) {
					$('#response').html('<h3>Successfully updated!</h3><p><a href="/projects/company/all"><i class="fas fa-chevron-circle-left"></i> Back to Company List</a> ').addClass('success');
					$('#submit-response').slideDown();
				} else {
					$('#response').html('<h3>Something went wrong!</h3><p>Error: '+JSON.stringify(data.field_errors)+'</p>').addClass('error');
					$('#submit-response').slideDown();
				}
		}
});`

I'm not including jquery as I'm loading that up independently. EE6 still uses v2 and the reporting section of our site needs libraries that rely on v3. I'm loading jQuery 2.2.4 for all channel form pages. Is this still the correct version to load?

`<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>`

**Comment by intoeetive** [comment]
You can use whatever jQuery version you need. 
I wonder if the jQuery plugin that you use for `ajaxForm` does not like jQuery v3 (i've been tested with 1.7, which is the example they give on their site)

**Comment by 620studio** [comment]
Actually we can't. I've tried loading up jQuery 3.6 and I get deprecation errors when using channel forms. I just loaded up 3.6 and here's the error I get

`Uncaught TypeError: $(...).closest(...).size is not a function`

.size is no longer available in 3 (https://api.jquery.com/size/) and .length is used instead.

I've been using it on jQuery 2.2.4 up until last week which it had been working.

**Comment by intoeetive** [comment]
That probably explains it.
What fieldtypes do you have in your form (wonder if that issue is coming from EE itself or third-party fieldtype)?

**Comment by 620studio** [comment]
I believe it's coming from the Grid field, here's the debugger info:

source js: https://_domain_/?ACT=3&ui=core,widget,mouse,position,draggable,resizable,sortable,button,dialog&plugin=ui.touch.punch,ee_table_reorder,markitup&file=fields/rte/redactor/redactor.min,fields/rte/rte,cp/files/picker,cp/files/picker,cp/sort_helper,cp/grid,vendor/underscore,cp/date_picker,cp/date&v=1634677450&use_live_url=y

Uncaught TypeError: $(...).closest(...).size is not a function

Referencing row: 8259, 90

8259: if (field === null || field === undefined || $(field).closest('.fluid-field-templates').size() > 0) {
