### ISSUE TITLE
EE6: enable extended configuration of Redactor settings

### ISSUE THREAD

**Issue by BridgingUnit** [ExpressionEngine/ExpressionEngine#1465]
Current configuration of RTE field for Redactor at least is very limited compared with what is available and possible (and, dare I say it, desirable) within Redactor directly.

For instance, within EE, there is a single Heading/Format button that you can enable or disable per config, and that's it. 

That generates a simple array which you store in the exp_rte_toolsets DB table, with a portion that relates to the custom configuration. The relevant bit is this (taken from RedactorService.php within the native rte addon):

```
    'buttons' => [
        'html',
        'format',
        'bold',
        'italic',
        'deleted',
        'underline',
        'redo',
        'undo',
        'ol',
        'ul',
        'indent',
        'outdent',
        'sup',
        'sub',
        'link',
        'line'
    ],
    'plugins' => [
        'alignment',
        'rte_definedlinks',
        'filebrowser',
        'pages',
        'inlinestyle',
        'fontcolor',
        'limiter',
        'counter',
        'properties',
        'specialchars',
        'table',
        'video',
        'widget',
        'readmore',
        'fullscreen',
    ]
```

And that I'm guessing is converted into the actual JSON used by Redactor on the frontend.

But within Redactor you can also specify _which_ headings/formats are available within the Format menu:

https://imperavi.com/redactor/docs/settings/formatting/

So you ought to be able to configure an array like this:

```
    'buttons' => [
        'html',
        'format',
        'bold',
        'italic',
        'redo',
        'undo',
        'ol',
        'ul',
        'link',
    ],
    'formatting' => [
        'p',
        'h2',
        'h3',
        'h4'
    ],
    'plugins' => [
        'alignment',
        'rte_definedlinks',
        'filebrowser',
        'pages',
        'inlinestyle',
        'fontcolor',
        'limiter',
        'counter',
        'properties',
        'specialchars',
        'table',
        'video',
        'widget',
        'readmore',
        'fullscreen',
    ]
```

Note that the purpose in my second example is to _remove_ h1 (and others) from the format list, because that is catered for by a separate field within the channel. We _don't_ want the editor to use h1 just because they want to make a title bigger.

This is just one example, but Redactor offers a lot more relating to custom configuration that is being exposed right now. 

Perhaps it would be possible to provide a textarea where you can drop your own formatted JSON array for Redactor configs?

**Comment by paulcripps** [comment]
This would be really handy, +1 for me :)

**Comment by paulcripps** [comment]
It would be great if config file, perhaps JSON, can be managed externally, in the system/user folders or config files. 
Alternately per field would be neate too.

**Comment by BridgingUnit** [comment]
Yep, if the JSON for defaults _or custom configs added by a dev_ could just sit in the /user/config folder and be read from there in the CP, that'd be really useful. Then you could add, edit them right there.

Also be useful if within a RTE field instance (when setting up the field within the CP) in addition to dropdown to pick from global configurations, there was also an option to override with your own JSON direct via a textarea there.

**Comment by robinsowell** [comment]
I had a request from someone to be able to add to the RTE buttons in the same way you do the HTML buttons currently.  For simple ones, this might tie in here- you just specify the beginning and ending tag, save, and EE does the work of writing it to the config.

**Comment by PDXMan1** [comment]
I like what I see in Redactor, but it doesn't work for us until I can both remove some of the default options (like the h1 heading mentioned above) AND add some project-specific buttons with custom classes (like we can with the old-school HTML buttons that have been in EE for ages).

**Comment by BridgingUnit** [comment]
Redactor itself allows you to add custom classes (and tags):

https://imperavi.com/redactor/docs/settings/formatting/#s-formattingadd

Also, I note that it has a dedicated method of hiding specific tags from formatting (in addition to just changing the default tags provided within the formatting sectioned  already mentioned):

https://imperavi.com/redactor/docs/settings/formatting/#s-formattinghide

If we could provide EE with these custom JSON configs ourselves, then all of this _should_ be possible.

**Comment by paulcripps** [comment]
I'd really like to push for this, desperate to ensure my clients can not add h1 and other formatting... so it would a great help to allow us to configure and hide formatting styles such as heading 1, quote and code.

**Comment by pixiwooh** [comment]
Yeah, it is kind of related to #1425 (where we want to add custom styles to the formatting dropdown). I think it is one of the last reasons stopping me using RTE Redactor instead of Wygwam.

**Comment by PDXMan1** [comment]
I am the person that Robin mentions in this thread, and we would still LOVE to be able to add custom html buttons to Redactor. All our sites are custom designed and they all have some odd text formatting class or two that our publishers need easy access to. Would love to see this enhancement gain some traction.

**Comment by dankingsley** [comment]
@TomJaeger Any update on this or #1425? Would really enable me to move a few of my sites over from Wygwam... thanks.
