### ISSUE TITLE
Glitchy password masking when using "Login as..."

### ISSUE THREAD

**Issue by mcfarlandonline** [ExpressionEngine/ExpressionEngine#1466]
EE Version 6.1.4
PHP Version 7.3.30

Steps to recreate: 
1. Login as a Super Admin
2. Edit a member's roles and provide password to Authenticate & Save
3. Visit Administration > "Login as..." page of any member profile
4. Type in password to Login as... and see that the password masking is broken

_Note: 
I'm guessing there's a cookie that is caching the Super Admin's password, since after editing once member's roles, authenticating & saving, I'm not required to type my password in again to perform the action again or on another member. I find this inconsistent presence of the password field a little more alarming than helpful, and wonder if it's causing the glitchy password masking issue._

![Screen Shot 2021-10-20 at 10 33 27 AM](https://user-images.githubusercontent.com/20441129/138144253-d94d1627-9e9b-4479-a128-f569031cbe24.jpg)

**Comment by intoeetive** [comment]
@mcfarlandonline this is actually input for "other" URL, not for the password. But I agree, there is some UX confusion here - maybe we can improve it.

Generally speaking, the password is being asked for sensitive actions once per "auth timeout" period, which is 15 minutes currently. This is similar to the concept of "escalated sessions" in other systems.

**Comment by PaulBaileyAtChan** [comment]
Labelling the submission control "Authenticate & Save" implies that the user is being asked for their password again, and there's only one text field where the password could go, which helps to mislead. Changing the label on the submission control would help here.

**Comment by mcfarlandonline** [comment]
Oh! I see what you're saying... 

Yes, some UX modifications would be helpful here. Alternative idea would be to only show that text field if the "Other" radio button gets selected. 

Thanks for clarifying!
