### ISSUE TITLE
Overlay over file modal (z-index)

### ISSUE THREAD

**Issue by 2op** [ExpressionEngine/ExpressionEngine#1468]
Problem happens when publishing an entry.

The publish page contains an RTE field and an file field.

To reproduce the problem:

1 - Insert an image in the RTE field;
2 - Next, in the file field click on "Upload New".

The overlay z-index is greater than the modal.

Printscreen:
<img width="2169" alt="overlay" src="https://user-images.githubusercontent.com/29434623/138153617-f6f69eda-6b26-4573-bdd4-f40ab865b333.png">

**Comment by robsonsobral** [comment]
(quer compartilhar minha nova tradução, @2op ? Se quiser, entre em contato.)

**Comment by intoeetive** [comment]
@2op I wasn't able to replicate this. Would you mind record screencast of the actions that you take?

Is there any error in browser console? Also, what engine does RTE use here - CKEditor or Redactor? Lastly, what's your EE version?

**Comment by 2op** [comment]
**Screencast:** 
https://user-images.githubusercontent.com/29434623/139307969-831fb718-5bdc-478e-9ab1-a85b7a1b0d2a.mov

Console: The console has no errors.
RTE: CKEditor
EE version: 6.1.4
