### ISSUE TITLE
Saving text to a rich text field in a fluid field triggers an exception

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#1473]
Created a new Fluid Field and added to it an existing Rich Text field.
Added Fluid Field to a channel which already had a copy of the Rich Text field attached.
Existing Rich Text Field works fine.
Copied over text from existing field to new field and hit save and got an exception error.
Exception Report attache
![Screenshot 2021-10-21 at 12-37-12 Exception - ExpressionEngine](https://user-images.githubusercontent.com/13821249/138269703-e89160a1-02d6-4a7f-a608-be2aaddc78eb.png)
d.
EE6.1.3, php 7.4.12, MySQL 5.7.32

**Comment by intoeetive** [comment]
Couple of questions:
- what field type is the field ID 40? RTE?
- what is the "Column type " for the field set to in field properties in CP?
- what is the column properties in DB for `field_id_40` in `exp_channel_data_field_id_40`?

**Comment by jcogs-design** [comment]
Field 40 is the fluid field itself.
![Screenshot 2021-10-21 at 14 55 12](https://user-images.githubusercontent.com/13821249/138292382-e872a949-69f8-4341-89ac-594adeb4a43c.png)
There are no 'Column type' settings for fluid fields that I can see in CP.
Grab of table structure for exp_channel_data_field_40 attached.
![Screenshot 2021-10-21 at 14 56 23](https://user-images.githubusercontent.com/13821249/138292769-7745917e-5a71-4f3c-a9c8-a28dbe27d620.png)

**Comment by intoeetive** [comment]
So just to make sure I'm following:
- and entry has RTE field and Fluid field
- You copy over text from RTE field to RTE sub-field inside Fluid
- Trying to save the entry give this error

**Comment by jcogs-design** [comment]
Exactly so. FWIW the RTE Field is field 39.

**Comment by intoeetive** [comment]
@jcogs-design I wasn't able to replicate this so far.
What are the other tabs/fields that you have on this page?
Also, what toolset does RTE field use - Redactor or CKEditor?
