### ISSUE TITLE
Cant input content to link fields in RTE

### ISSUE THREAD

**Issue by kippenblinky** [ExpressionEngine/ExpressionEngine#148]
Im using the RTE and if I choose to add a link to a text the boxs appears but it is not possible to fill the fields.
![screen shot 2019-03-06 at 13 46 39](https://user-images.githubusercontent.com/45204314/53882795-90d7d480-4017-11e9-8a81-967b6e786ed5.png)

**Comment by kevincupp** [comment]
I am unable to reproduce. Can you please use the template provided when you create a new issue? That will prompt you to fill in information like steps to reproduce on a fresh install which would be very helpful here.

<img width="973" alt="screen shot 2019-03-06 at 10 58 46 am" src="https://user-images.githubusercontent.com/93695/53894858-d9cf5f00-3ffe-11e9-9f3a-e6b4c81e906f.png">
