### ISSUE TITLE
Can't setup fresh clone, MAMP Pro mac OS

### ISSUE THREAD

**Issue by KeygenOld** [ExpressionEngine/ExpressionEngine#1492]
Just cloned EE to test it out, setup a new MAMP Pro host, navigated to `https://local.example.com:8890/admin.php` and get a blank page with error text: `The configuration file does not exist.`

I didn't see anything in the install instructions for creating a config file. Is this a bug or am I missing something?

Also ran the server test and all checked out fine.

### System info
mac OS 11.6
MAMP Pro 5.7
all Apache modules enabled
PHP 7.4
MySQL 5.7.26

**Comment by TomJaeger** [comment]
Thanks for getting in touch about this!

Installing directly from the repo does require a few additional steps (it's not fully packaged up).  However you can go to the Tags 6.1.5 is the most recent, and download the zip file there, and you should be good to go!

https://github.com/ExpressionEngine/ExpressionEngine/releases/tag/6.1.5


For more information on installing from the repo, see the readme file here: https://github.com/ExpressionEngine/ExpressionEngine/tree/6.dev#how-to-install
