### ISSUE TITLE
reCAPTCHA v3 does not work

### ISSUE THREAD

**Issue by benya** [ExpressionEngine/ExpressionEngine#1493]
Hi!

EE 6.1.5

Included reCAPTCHA instead of standard captcha.

But now, when you try to register on the site or add material, nothing happens.

There are no errors in the console either.

```
{exp:channel:form channel="jobs" return="jobs/ENTRY_ID" include_assets="no" logged_out_member_id="2"}

<input type="text" class="form-control" id="title" name="title" placeholder="Title" maxlength="128" required>

<input type="hidden" name="url_title" value="{current_time}">


....


{if captcha}
{captcha}
{/if}

<button type="submit" name="submit" class="btn btn-primary">ok</button>

{/exp:channel:form}
```

**Comment by TomJaeger** [comment]
HI @benya just about to test and confirm we can reproduce.

Just to confirm, you changed the captch settings to be reCAPTCHA?  Or is this with the native one still in use?

**Comment by benya** [comment]
> HI @benya just about to test and confirm we can reproduce.
> 
> Just to confirm, you changed the captch settings to be reCAPTCHA? Or is this with the native one still in use?

https://prnt.sc/1xe68q3

**Comment by benya** [comment]
The form for sending messages does not work either :(

```
{exp:email:contact_form recipients="XXX@gmail.com"}

<input name="from" type="hidden" value="{webmaster_email}">

<input name="subject" type="hidden" value="{site_name}">

<textarea class="form-control" placeholder="message" name="message" rows="5" required autofocus></textarea>

{if captcha}

{captcha}

{/if}

<button type="submit" class="btn btn-primary">ok</button>

{/exp:email:contact_form}
```

**Comment by robinsowell** [comment]
If you switch back to the old captcha type, is it working?

**Comment by benya** [comment]
@robinsowell Yes, the old captcha works.

**Comment by robinsowell** [comment]
So on one where the old captcha works, if you switch it to reCaptcha and add the correct keys for the site, you don't get the little recaptcha image showing up and if you view source- do you have the google recaptcha link added in there a la

```<script>var eeRecaptchaEndpoint ='https://6-1-4.local:8890/index.php?ACT=26'; etc....>```

I'm seeing it in my tests, so I think something must be off.  If the script is there but the image isn't, it may be a setting in google is off?

**Comment by robinsowell** [comment]
OH and I think I may know the problem in the channel form.  It works a little differently for the 'make members fill it out'- if you're a real, logged in member with permission to publish, you don't get the captcha.  If you're a non-logged in person but allowed to publish, you get the captcha.  

So maybe if you're testing as a superadmin with 'require for members on' and not getting the captcha, that could be confusing things.  Because admittedly, that's not how the others work.

**Comment by benya** [comment]
@robinsowell The form can be viewed at https://exprod.net/support

When the button was clicked, the form was submitting the script plugin jquery + jquery.form.min.js.

I thought this might be the case. But I disabled jquery and form.min.js for verification by making the standard submission of EE and nothing changed.

When I click on the button, I get a 403 error.

Maybe this will help, the server works without apache, and on nginx + the ngx_pagespeed module from Google.

**Comment by robinsowell** [comment]
Oh- interesting.  Your action id isn't parsing- view source and see:

https://xxx.net/?ACT={AID:Member:recaptcha_check}'

That's the problem.  I suspect once we put that into the exp_actions table and you'll be good.   But before we do, can you double check- do you have the rest of these records for the Member class in your database table called 'exp_actions'?  

<img width="563" alt="Screen Shot 2021-10-27 at 3 09 47 PM" src="https://user-images.githubusercontent.com/1181219/139131330-bb50c629-6cc4-4e0c-b813-c8043ac13646.png">

I just want to nail down how it went missing.  And that will give me a good hint.

**Comment by benya** [comment]
https://prnt.sc/1xj09d7

**Comment by intoeetive** [comment]
It looks like one of the EE updates was not properly executed.

I suggest that you replace the files with one ones from 6.1.5 zip again (including installer folder, but don't forget to keep your existing config.php). Then in config.php change the version to 6.0.0
Visit CP, and the installer will run and perform all updates needed again.
