### ISSUE TITLE
{author} variable in {exp:comment:entries} isn't parsed.

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#1496]
EE 6.1.5 and earlier

According to the docs there is an {author}-variable.
https://docs.expressionengine.com/latest/comment/entries.html#author
But it doesn't get parsed . Output on the frontend is {author}.

{name} does the desired thing  however.

**Comment by robsonsobral** [comment]
Please, give us more details.

**Comment by silenz88** [comment]
`{exp:comment:entries}
{author}
{/exp:comment:entries}`

is supposed to output 

> The comment author’s screen name, if a member; otherwise, this variable will display the name submitted with the comment.

according to the docs.

Instead the output is:  {author}

**Comment by intoeetive** [comment]
This does seem to work on my test template.
Is this an issue with just certain comment or all of those? If it's just one, can you check the values of `author_id` and `name` columns for this comment in `exp_comments` DB table. If there a chance `author_id` is poiting to non-existing member and/or `name` is empty?

If you see it with all comment, I would like to see the minimal code required to replicate this (using the sample you gave does not show any issues for me, so there must be something else)

**Comment by silenz88** [comment]
Okay. It seems only to affect members, not guests.

The author_id in exp_comments is 2.
The name in exp_comments is filled.
The user 2 exists and is logged in when posting the comment.

`{exp:comment:entries sort="desc" limit="100"}
{author}<br>
{/exp:comment:entries}`

output

> Andi<br>
> Schmidt<br>
> mara<br>
> Petra<br>
> Sonja<br>
> {author}<br>

**Comment by intoeetive** [comment]
Is this code inside `{exp:channel:entries}` or is this the only code that's on page? Also, does the page URL include entry's url_title or entry_id?

**Comment by silenz88** [comment]
It's not nested inside {exp:channel:entries} and the url_title is in the last segment.

**Comment by intoeetive** [comment]
@robinsowell inviting you here in case you have any ideas what might be cauing this. I am still unable to replicate

**Comment by robinsowell** [comment]
Hrm, I can't replicate either.  Tried it logged out, logged in as superadmin and author of entry, logged in as regular member.  Both name and author always parsed.

OK, forgive me for the redundancy, but a completely blank template, just this on it:

```
{exp:comment:entries dynamic="no"}
{author_id} - {comment_id} - {name} - {author}<br> 
{/exp:comment:entries}
```
All of the ones by logged in users have the author variable unparsed?  And it's the only thing ever unparsed?

AND if you go look in exp_comments db table, the ones with author unparsed do have a name value there.

If all of that's true, I'd do a really quick test where you disable extensions and see if it matters.

It really is puzzling- I can't replicate it.

**Comment by silenz88** [comment]
My bad. I found the culprit. It's the threadedcomments addon.

**Comment by robinsowell** [comment]
AHA!!  Good catch.  And I do kinda wish we had threaded comments.

**Comment by silenz88** [comment]
And it only happens from second level down.
