### ISSUE TITLE
Unecessary DB query when fetching templates from files

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1509]
The function [`fetch_template()`](https://github.com/ExpressionEngine/ExpressionEngine/blob/991de92312bcf791688b358798d2427820f111cb/system/ee/legacy/libraries/Template.php#L2329) check the database:

```sql
SELECT `exp_templates`.*, `exp_template_groups`.`group_name`
FROM (`exp_templates`)
JOIN `exp_template_groups` ON `exp_template_groups`.`group_id` = `exp_templates`.`group_id`
WHERE `exp_template_groups`.`site_id` = 26
AND `exp_templates`.`template_name` = 'index'
AND `exp_template_groups`.`group_name` = 'site'
```

In case, the query returns empty, it calls the function [`_create_from_file()`](https://github.com/ExpressionEngine/ExpressionEngine/blob/991de92312bcf791688b358798d2427820f111cb/system/ee/legacy/libraries/Template.php#L2723) passing the parameter `$db_check` as `TRUE`, which triggers a new query:

```sql
SELECT COUNT(*) AS `numrows`
FROM (`exp_templates`)
LEFT JOIN `exp_template_groups` ON `exp_templates`.`group_id` = `exp_template_groups`.`group_id`
WHERE `group_name` = 'site' AND `template_name` = 'index'
```

What is the point of this second query?! And, worst, it doesn't check for the site the templates should belong to.

**Comment by intoeetive** [comment]
@robsonsobral thank you for finding this!

We are planning to have some code optimization to reduce the number of queries and improve EE speed overall, and this is one of the things we'd definitely want to change!

**Comment by robsonsobral** [comment]
Actually, @intoeetive, I only find it because it's **a bug**.

The second query, without `site_id`, prevents the templates of other sites to be fetched when using MSM.

The quick and dirty fix is to change the `$db_check` value to `FALSE` at the line [2434](https://github.com/ExpressionEngine/ExpressionEngine/blob/991de92312bcf791688b358798d2427820f111cb/system/ee/legacy/libraries/Template.php#L2434). Can we fix that before to do any enhancement?

**Comment by intoeetive** [comment]
Do you have some sample template code that can be used to replicate the bug?

**Comment by robsonsobral** [comment]
It isn't a matter of code, but of configuration.

Let's say, we have 2 sites and we create their templates using files, not the CP. At the first access to any site, the template of the corresponding site are fetched and included at database. Now, when we try to access the other site, the second query returns the already created templates of any site, which stops the process of fetching the new ones. We have to open the design section of the CP for the templates be created.

This bug was driving me nuts! My CI process deployed the files, but the client complained the staging URL returned blank pages. Then, I had to open the CP of that environment and force the creation of the new templates.

**Comment by intoeetive** [comment]
So just to make sure, the user-facing implication of this issue is that when using MSM, only templates of first site are being synchronized when visiting site page? And you need to visit CP for the secondary site to have them actually synchronized?

**Comment by robsonsobral** [comment]
In case the names of the template group and of the template file are equal between sites, **YES**!

**Comment by intoeetive** [comment]
@robsonsobral if you still have the setup to replicate the issue, can you check if adding this code fixes it?
```
ee()->db->where('site_id', ee()->config->item('site_id'));
```
around line `2740` in `system\ee\legacy\libraries\Template.php`

**Comment by robsonsobral** [comment]
I'm sorry, but I don't. I can try to replicate later, however.

By what I can see, yeah, it works. It isn't what I would do, but should work.

**Comment by robsonsobral** [comment]
No, @intoeetive ! It doesn't work, but it's simple:

> SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'site_id' in where clause is ambiguous:
> SELECT COUNT(*) AS `numrows` FROM (`exp_templates`) LEFT JOIN `exp_template_groups` ON `exp_templates`.`group_id` = `exp_template_groups`.`group_id` WHERE `group_name` = 'test' AND `template_name` = 'index' AND `site_id` = 1

So:

```php
ee()->db->where('templates.site_id', ee()->config->item('site_id'));
```

**Comment by intoeetive** [comment]
Thanks @robsonsobral !
