### ISSUE TITLE
When you change a select field value, you need a warning

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#1514]
This verges on a bug.  Basically, any select/checkbox/radio, if you edit it and change or delete an existing value, then any old entries that have that value selected can't be edited.  You're going to get a 'Invalid Selection' warning in validation, because validation checks what's set against what's possible and it's going to fail.

Would be nice to get a warning if you make a change and better yet if there was some way to update the old values to the new.  But it definitely jams folks up, and they don't know why they're getting the validation warning.

**Comment by intoeetive** [comment]
Thinking through it, we'd need to perform the check during the validation request. Then have the javascript perform checks whether we should display alert when save is triggered. And then if necessary display alert similar to this https://github.com/ExpressionEngine/ExpressionEngine/pull/2378
