### ISSUE TITLE
Low Search error on PHP 8

### ISSUE THREAD

**Issue by Caleydon** [ExpressionEngine/ExpressionEngine#1517]
Clean EE 6.1.5 installation.
Low Search 7.0.3 (Trial) installaton return error on PHP 8.0.7.
Module setting page return the same error.

![low-search](https://user-images.githubusercontent.com/2806752/139556376-820bcd3c-962c-4d77-ab06-7ac66ad1b82e.png)

**Comment by obfuscode** [comment]
This has been fixed in Low Search 7.1.0.
