### ISSUE TITLE
Action Buttons and more removed in Add-ons

### ISSUE THREAD

**Issue by blairliikala** [ExpressionEngine/ExpressionEngine#1518]
While I'm posting this as a possible bug, there is no documentation on this so I am not sure what this should look like, I'm only going from examples in the EE source. 

I would like to add a button in the top right navigation in an add-on.  An example would be in Channels (/cp/channels).  However the action button array is stripped out when it gets to` _templates/default-nav`.  Only the settings button passes.

mcp:
```
$header = [

// Removed:
    'title' => 'My Title',
    'test  => 'test',

// The only things that passes
    'toolbar_items' => [
        'settings' => [
            'href' => '#',
            'title' => lang('settings')
        ],
    ],

// Removed:
    'action_buttons' => [
        [
            'href' => '#',
            'text' => 'text',
        ] 
    ]

];

ee()->view->header = $header;
```

I added a var_dump in the default-nav view, and only the toolbar_items is passed.  I was able to call the view directly and get the button added, though it duplicates the entire CP and explodes.  First-party add-ons seem to work, Pro for example, and internal pages, Channels for example (where this snippet came from).

v6.1.5

**Comment by intoeetive** [comment]
@blairliikala my guess is part of your header is getting overwritten somewhere. Can you post (or send me in Slack) more of code that you have? EE does not make any difference here between first-party and third-party, so there should be some other small thing missing.

Additionally, if you're using shared form view, you can add buttons like this:
```
        $vars['buttons'] = [
            [
                'name' => 'submit',
                'type' => 'submit',
                'value' => 'save',
                'text' => 'save',
                'working' => 'btn_saving'
            ],
            [
                'name' => 'submit',
                'type' => 'submit',
                'value' => 'save_and_new',
                'text' => 'save_and_new',
                'working' => 'btn_saving'
            ],
            [
                'name' => 'submit',
                'type' => 'submit',
                'value' => 'save_and_close',
                'text' => 'save_and_close',
                'working' => 'btn_saving'
            ]
        ];

        ee()->cp->render('settings/form', $vars);
```

**Comment by blairliikala** [comment]
[teest.zip](https://github.com/ExpressionEngine/ExpressionEngine/files/7461188/teest.zip)
Here's a test add-on.

**Comment by blairliikala** [comment]
> @blairliikala my guess is part of your header is getting overwritten somewhere. Can you post (or send me in Slack) more of code that you have? EE does not make any difference here between first-party and third-party, so there should be some other small thing missing.
> 
> Additionally, if you're using shared form view, you can add buttons like this:
> 
> ```
>         $vars['buttons'] = [
>             [
>                 'name' => 'submit',
>                 'type' => 'submit',
>                 'value' => 'save',
>                 'text' => 'save',
>                 'working' => 'btn_saving'
>             ],
>             [
>                 'name' => 'submit',
>                 'type' => 'submit',
>                 'value' => 'save_and_new',
>                 'text' => 'save_and_new',
>                 'working' => 'btn_saving'
>             ],
>             [
>                 'name' => 'submit',
>                 'type' => 'submit',
>                 'value' => 'save_and_close',
>                 'text' => 'save_and_close',
>                 'working' => 'btn_saving'
>             ]
>         ];
> 
>         ee()->cp->render('settings/form', $vars);
> ```

I got this error when trying this.

Undefined variable: cp_screen_name
ee/ExpressionEngine/View/_shared/header.php, line 93
Severity: E_NOTICE

**Comment by intoeetive** [comment]
@blairliikala so I went through the code and appears not all variables were passed to header view for add-ons. There might have been specific reason why this was built this way in its own time, however I don't see reason for it now - so hopefully my PR will make it into the next release

**Comment by blairliikala** [comment]
Thank you Yuri!
