### ISSUE TITLE
Duplicate names in relationship field cause processing error in EE5.2 but not EE5.1.3

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#152]
**Description of the problem**
A block of code that has worked without issue in EE5.1.3 fails after upgrade to EE5.2.

The code unpacks information from a relationship field.

Under EE5.1.3 and before the sample code attached worked fine: generating a series of lists of anchor items with a heading before each, based on the content of a series of entries included in a relationship list.

Under EE5.2 the code fails to render output - instead simply returning the correct number of list items but with unformed content (`{item_selection:item_selection:title}`) in place of text required.

Conjecture that the issue is due to the name of the relationship field being duplicated in the template - a result of both parent and child entries in the main relationship field containing instances of the same field definition (so the same field name appears twice in series when accessing some elements).

Issue identified after routine upgrade of EE from 5.1.3 to EE 5.2.0.

**How To Reproduce**
Have not yet developed a generic process to reproduce, but would appear to be simply enough to setup a situation where a relationship field recurses.  See sample code appended.  The error relates to the failure to process the code within the tag pair ```{item_selection:item_selection} ... {/item_selection:item_selection}```

**Error Messages**
No error message, just unformed tags appearing in template output.

**Screenshots / Videos / Template Code**
```
{item_selection}
    {if item_selection:channel_short_name != 'collections'}<a href="/info/{item_selection:url_title}" class="junk">{item_selection:title}</a>{/if}
        {item_selection:item_selection}
            {if item_selection:item_selection:count == 1}<div class="subhead d-flex">{item_selection:title}</div>{/if}
            {if item_selection:item_selection:url_title == "member-login-registration" || item_selection:item_selection:url_title == "logout"}
                {if  item_selection:item_selection:url_title == "member-login-registration" && logged_out}<a href="/info/{item_selection:item_selection:url_title}">{item_selection:item_selection:title}</a>
                {if:elseif item_selection:item_selection:url_title == "logout" && logged_in}
                        <a href="{path='club'}">Member Area</a>
                        <a href="{path='logout'}">Logout</a>
                {/if}
            {if:else}
                <a href="/info/{item_selection:item_selection:url_title}"> {item_selection:item_selection:title}</a>
            {/if}
    {/item_selection:item_selection}
{/item_selection}
```

**Environment Details:**
 - Version: 5.2.0
 - PHP Version 7.1
 - MySQL Version 5.7.16
 - OS: Linux
 - Web Server: Apache

**Possible Solution**
Have reverted the site to EE 5.1.3 until workaround or fix identified.  One solution I think would be to create a duplicate relationship field with a different name and use alternative named field in one of the two instances - but would appear some change between EE 5.1.3 and EE 5.2.0 has triggered this anomalous behaviour, and a better fix would be to understand why and revert the change.

**Additional context**
Will post additional information on solutions when I get a chance to set up site on a test server.

**Comment by kevincupp** [comment]
Sorry for the trouble, it was probably caused by this: https://github.com/expressionengine/expressionengine/commit/a2913901bac24a8b2efc444b634b061453e8cbdb

I'm going to revert that change and fix the original issue it was trying to fix another way.
