### ISSUE TITLE
Hyperlink issue

### ISSUE THREAD

**Issue by docshort** [ExpressionEngine/ExpressionEngine#1528]
I'm having a problem creating internal hyperlinks that highlight the words showing they are a link. In the last blog post article it seems to be working but with the one I just posted today it is not.
--

</body>
</html>
Please describe your issue in as much details as you can. What you were trying to do, what steps did you take, what did you expect, what did you see instead.

Make sure to mention what page you are on, if this is issue in Control Panel - provide the URL (domain name can be removed)

Add a screenshot. If error backtrace is available, provide it. 

If this is front-end issue, provide template code you have been using.

Tell us about your environment (EE version including beta number, PHP/MySQL version, web server, OS etc)

Lastly, anything else you may find useful for us to know! (But please don't put multiple bugs into same issue - create as many new ones as needed)
-->

**Comment by robsonsobral** [comment]
WHAT?!
