### ISSUE TITLE
CLI unable to create ChannelEntry

### ISSUE THREAD

**Issue by dougblackjr** [ExpressionEngine/ExpressionEngine#1530]
**Description of the problem**

When seeking to create a ChannelEntry via the Model service in the CLI, I am getting a number of different errors and am unable to create.

**How To Reproduce**

### CLI for adding ChannelEntry breaks when adding entry date

1. Run command as below, with a value set as the `entry_date`.
2. Error received:

> Uncaught InvalidArgumentException: No such property: 'session'

### CLI for adding ChannelEntry breaks because of missing Request

1. Run command as below (getting around entry_date for testing by setting a default in the DB).
2. Error received:

> Call to a member function get() on null

Looks to be related to this conditional in ee/ExpressionEngine/Addons/pro/Model/Channel/ChannelEntry.php

```
if (IS_PRO && ee('Request')->get('field_id'))
```

**Environment Details:**
 - Version: 6.1.5
 - PHP Version 8.0 and 7.3
 - MySQL Version: MariaDB 10.5.12
 - OS: Linux
 - Web Server: nginx

**Additional context**

Here is my code for creating a ChannelEntry in the command:

```
$member = ee('Model')->get('Member')->first();
$channel = ee('Model')->get('Channel')->filter('channel_name', 'blog')->first();

$data = [
    'author_id' => $member->member_id,
    'channel_id' => $channel->channel_id,
    'ip_address' => '127.0.0.1',
    'title' => 'Test Entry',
    'url_title' => 'test_entry',
    'status' => 'open',
    'entry_date' => time(),
    'versioning_enabled' => 'n',
    'allow_comments' => 'n',
    'sticky' => 'n',
];

$fields = [
    'blog_content' => 'test',
    'rando_date' => '2021-01-01 00:00:00',
    'some_wygwam_field' => 'test',
];

$this->info('Creating channel entry');
$entry = ee('Model')->make('ChannelEntry');

foreach ($data as $d => $val) {
    $this->info('Adding ' . $d . ' to entry as ' . $val);
    $entry->{$d} = $val;
}

$customFields = $entry->getCustomFields();

foreach ($customFields as $field) {
    $fName = $field->getName();
    if (array_key_exists($fName, $fields) && !isset($entry->{$fName})) {
        $fieldToSave = 'field_id_' . $field->getId();
        $this->info('Adding ' . $fieldToSave . ' to entry as ' . $fields[$fname]);
        $entry->{$fieldToSave} = $fields[$fname];
    }
}

$this->info('Saving...');
$entry->save();
$this->info('All done!');
```

**Comment by TomJaeger** [comment]
I believe you'll need to load the session library, and create an empty request as part of your command then you should be in good shape!

`ee('App')->setRequest(new \ExpressionEngine\Core\Request([], [], [], [], []));`

`ee()->load->library('session');`

The following command is working as intended in my tests.  Please note, I'm using field_id_3.  I've used this to seed a few thousand entries for testing...

` ee('App')->setRequest(new \ExpressionEngine\Core\Request([], [], [], [], []));

        ee()->load->library('session');

        $member = ee('Model')->get('Member')->first();
        $channel = ee('Model')->get('Channel')->filter('channel_name', 'blog')->first();

        $data = [
            'author_id' => $member->member_id,
            'channel_id' => $channel->channel_id,
            'ip_address' => '127.0.0.1',
            'title' => 'Test Entry'.$i,
            'url_title' => 'test_entry',
            'status' => 'open',
            'entry_date' => time(),
            'versioning_enabled' => 'n',
            'allow_comments' => 'n',
            'sticky' => 'n',
        ];

        $fields = [
            'field_id_3' => 'test the body field here.', // this is an RTE field with redactor
            // 'rando_date' => '2021-01-01 00:00:00',
            // 'some_wygwam_field' => 'test',
        ];

        $this->info('Creating channel entry');
        $entry = ee('Model')->make('ChannelEntry');

        foreach ($data as $d => $val) {
            $this->info('Adding ' . $d . ' to entry as ' . $val);
            $entry->{$d} = $val;
        }

        $customFields = $entry->getCustomFields();

        foreach ($customFields as $field) {
            $fName = $field->getName();

            if (array_key_exists($fName, $fields) && !isset($entry->{$fName})) {

                $fieldToSave = 'field_id_' . $field->getId();
                $this->info('Adding ' . $fieldToSave . ' to entry as ' . $fields[$fName]);
                $entry->{$fieldToSave} = $fields[$fName];
            }
        }

        $this->info('Saving...');
        $entry->save();
        $this->info('All done!'.$i);`

**Comment by dougblackjr** [comment]
@TomJaeger Yes, this seems to address the issue. Is this the kind of thing that would best be addressed within a command? Or in the CLI as a whole?

**Comment by TomJaeger** [comment]
Great question... Originally added it on a global level.  This is an area we're still adding unit tests for, so we didn't feel great about making it as a foundational change until after we have a higher level of certainty that it doesn't negatively impact things.

**Comment by dougblackjr** [comment]
@TomJaeger That's fair. For now, we can close this, as your solution solved the issue. Will look into adding testing and this solution into the core of the CLI at a later point. Thank you!
