### ISSUE TITLE
CLI list cuts off longer names of commands

### ISSUE THREAD

**Issue by dougblackjr** [ExpressionEngine/ExpressionEngine#1531]
**Description of the problem**

When creating a command with a longer name, it gets cut off in `eecli:list`

**How To Reproduce**

1. Create an addon with "Hey This Is a Great Module".
2. Create a command for that addon titled "Oh Wow What a Command" with a signature `do:amazing-things-all-the-time`
3. Run `php eecli.php list`

**Environment Details:**
 - Version: 6.1.5
 - PHP Version 8.0 and 7.3
 - MySQL Version: MariaDB 10.5.12
 - OS: Linux
 - Web Server: nginx

**Additional context**

![Screenshot from 2021-11-03 10-48-09](https://user-images.githubusercontent.com/6020323/140083595-873eae70-e70a-41eb-959f-1ee23349d090.png)

![Screenshot from 2021-11-03 10-48-14](https://user-images.githubusercontent.com/6020323/140083602-61dc573d-89bf-4326-854d-a0f9b9e63b14.png)

**Comment by eric-lamb62** [comment]
@dougblackjr you mind giving this PR a kick in the tires? Works pretty on Windows but am pretty sure I'm the only EE dev that uses it ;)
