### ISSUE TITLE
When displaying custom fields in the entry manager list view, sorting is lost during pagination

### ISSUE THREAD

**Issue by aasun** [ExpressionEngine/ExpressionEngine#1532]
When displaying custom fields in the the entry manager list view, after sorting by one of those custom fields, doing anything to change pagination (increasing the number of records to display, or going to another page) results in the sort being lost.

So, you have to first, increase the number of records being displayed, then sort by the custom field, and hope that you chose to display enough records to catch what you are looking for.

sort setting for default fields works across pagination changes.. Ideally, custom field sort settings would function the same way.

**Comment by aasun** [comment]
ping

**Comment by intoeetive** [comment]
@aasun I wasn't able to replicate this on fresh install with sample theme.,

Could it be specific to the field's name or fieldtype?

**Comment by intoeetive** [comment]
This does not seem to be an issue when tested using latest EE. Closing
