### ISSUE TITLE
Can't access Communicate and Roles on sites with ~ 50k members

### ISSUE THREAD

**Issue by cbmmd42** [ExpressionEngine/ExpressionEngine#1533]
Summary: 
When an ee site gets too many members, an inefficient query in system/ee/ExpressionEngine/Controller/Utilities/Communicate.php prevents admins from accessing the ee utilities in the control panel. Clicking on tools > utilities in the control panel loads system/ee/ExpressionEngine/Controller/Utilities/Utilities.php which in turn automatically loads Communicate.php. 

admin.php?/cp/utilities/communicate 
This page isn’t working domain is currently unable to handle this request.
HTTP ERROR 500
Can't reproduce on staging ( Our staging database doesn't have member data )

The snippet of code which is causing the issue is in the file 
```
system/ee/ExpressionEngine/Controller/Utilities/Communicate.php
```
on line 87

```
if ($role->getAllMembers()->count() == 0) {
     $disabled_roles[] = $role->role_id;
}
```
This is a foreach loop which iterates through each member role and checks to see if there are any members in that group. 

When $role->getAllMembers() gets called groups with large numbers of member 10k - 50k (the exact number changes with your infrastructure), you are not able to load the page. 

I have this conditional commented out for now on my site. Let me know if I diagnosed this issue incorrectly. 

Possible Solution: 

I could see this being replaced with a more verbose method such as
```
$role->hasMemebers()
```
which would hopefully be more efficient than returning a collection of all members.

**Comment by intoeetive** [comment]
@cbmmd42 we have addressed this issue in EE 6.1.0
Please update your system and reopen this issue if the problem still persists

**Comment by cbmmd42** [comment]
Hi, I just updated to 6.1.5 and the issue still persists

I also just notice two related issues. I can't access /admin.php?/cp/members/roles and /admin.php?/cp/members&role_filter=5
/admin.php?/cp/members&role_filter=7 (the role groups with the bulk of the site's user base)

I was able to access /admin.php?/cp/members/roles after commenting out $role->PrimaryMembers->count() on line 124 of /system/ee/ExpressionEngine/Controller/Members/Roles/Role.php

When I looked at the members controller it does call the $role->getAllMembers() on 1019

I don't think I have the correct permissions to reopen this issue

**Comment by intoeetive** [comment]
Thank you for getting back to us.

It looks like getting the number of members assigned to role is what's causing the issue. We'll probably check if we can optimize that function - or add a config variable which large sites like yours would set and it would not perform those queries in real-time (making the numbers slightly less accurate, but the pages more speedy)

**Comment by cbmmd42** [comment]
Awesome thanks! If you have any further questions or if I can help in any way, let me know
