### ISSUE TITLE
File upload fields should allow you to preview the file, and edit related file data

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1539]
File fields feel under-developed. They hold complex pieces of content, but you'd never know that to look at the UI in the publishing field:

<img width="744" alt="Screen Shot 2021-11-05 at 3 40 19 PM" src="https://user-images.githubusercontent.com/308752/140569095-d6f3a545-bd5c-4946-b51f-cc0f7e96b5a0.png">

- You can't preview the full sized image
- The square thumbnail hides the original aspect ratio
- The title/filename is the only piece of meta data shown
- You can't *edit* the file in question — you can't even click through to the file manager to edit it; you can only remove it or replace it

Additionally, if you use drag and drop to upload a file in entry, you are never given the opportunity to edit its related data fields. This discourages the addition of descriptions needed for accessibility, artist/photographer credits needed for accountability, and titles needed for helpful organization and reference.

**Describe the solution you'd like**

<img width="771" alt="Screen Shot 2021-11-05 at 4 31 16 PM" src="https://user-images.githubusercontent.com/308752/140574753-236cca61-8410-4cec-8580-59473519fa2e.png">

- For new images, dragging and dropping an image should open up the same modal as clicking "Upload New".
- The same buttons that show up in the File Manager should show up here.
- The thumbnail should keep the aspect ratio of the original.
- Clicking the thumbnail should let you preview the file, with an option to edit.
- The file's meta data should available right in the field, or in the preview (better for multiple images)

**Comment by robsonsobral** [comment]
Github doesn't have enough emoji feedback buttons for how much we need this!

**Comment by intoeetive** [comment]
@ajohnson would you be willing to provide some feedback here?

**Comment by ajohnson** [comment]
@murtaugh @intoeetive Nailed it! Yes, the current File field is definitely still an MVP for v6. Most of the points you bring up Tim have been mentioned in internal team meetings. So it's definitely something we plan to address, just a matter of fitting it into the list of priorities.

I'm linking to this conversation from our internal notes so we can reference your comments as we plan the work.

Thanks much!

**Comment by murtaugh** [comment]
That's great. 

Even incremental updates would be much appreciated, like linking the thumbnail to the file manager, or displaying the image's full aspect ratio.

**Comment by intoeetive** [comment]
Closing as new file manager has been introduced in EE7 and things reported here are not relevant anymore
