### ISSUE TITLE
Access to Relationship Field values via single related entries tag form not working after EE 5.1.3 -> EE 5.2.0 upgrade

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#154]
**Description of the problem**
After a routine / one-click update from EE 5.1.3 to EE 5.2.0 a template that used the short form tag for "Single Related Entries" stopped working - returning the tag in place of the required value.

Updating template to use the standard relationship tag pair solved issue, but indicative of an issue (and if a permanent change a need to change [relevant EE documentation](https://docs.expressionengine.com/latest/fieldtypes/relationships.html#accessing-children)

**How To Reproduce**
Error occured on retrieval of a conventional single-use relationship tag.

**Error Messages**
No Error message - just template tag appearing in output.

**Screenshots / Videos / Template Code**
This code failed: 
```{product_series:entry_id}``` 
where `product_series` is a single-value relationship field in a channel, and the tag is returning the `entry_id` value for the related entry.

This code modification restored normal working in the template: 
```{product_series}{product_series:entry_id}{/product_series}```

**Environment Details:**
 - Version: 5.2.0
 - PHP Version 7.2
 - MySQL Version 5.7.16
 - OS: Linux
 - Web Server: Apache

**Possible Solution**

**Additional context**

**Comment by kevincupp** [comment]
Sorry for the trouble, it looks to have been caused by this: https://github.com/expressionengine/expressionengine/commit/a2913901bac24a8b2efc444b634b061453e8cbdb

I'm going to revert that change and fix the original issue it was trying to fix another way.
