### ISSUE TITLE
The add-on lasting impressions is using ee6 non-compatible code

### ISSUE THREAD

**Issue by thomasdefilippis** [ExpressionEngine/ExpressionEngine#1540]
When attempting to update lasting impressions, I noticed that nothing happened. And when I tried to uninstall the add-on I received this error:

<img width="1068" alt="Screen Shot 2021-11-05 at 3 03 01 PM" src="https://user-images.githubusercontent.com/61485862/140578796-eb31eda4-d35c-4148-af2c-782d3eaf28d7.png">

So, it appears that this add-on is using a table in the database called exp_module_member_groups which is now renamed to exp_module_member_roles. I am not sure if Expressionengine manages this add-on, but I thought I would throw it over anyways. Here is an example of the code in upd.lasting_impressions.php on line 137:

<img width="915" alt="Screen Shot 2021-11-05 at 3 11 47 PM" src="https://user-images.githubusercontent.com/61485862/140579146-4dec6eaf-8864-465b-9117-35f2a55eeb24.png">

**Comment by intoeetive** [comment]
Please address the issue to the corresponding add-on developer. The issues in https://github.com/ExpressionEngine/ExpressionEngine/ are for ExpressionEngine only.
