### ISSUE TITLE
Low Search warning on PHP 8 #2

### ISSUE THREAD

**Issue by Caleydon** [ExpressionEngine/ExpressionEngine#1544]
Clean EE 6.1.5 installation.
Low Search 7.1.0 (Trial) - License page return following warning on PHP 8.0.7.

![warning-low-search](https://user-images.githubusercontent.com/2806752/140743789-baff0f1a-b6a2-413c-9d43-07e4982c49e8.png)

**Comment by robinsowell** [comment]
Just to close the loop, this should be fixed in the latest release of Low Search.  If you still have any issues, let us know at help@eeharbor.com
