### ISSUE TITLE
Undefined index: search_flood_control

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#1549]
EE 6.1.5

When debug is on and a non-superuser uses a search-form on the frontend PHP throws a notice:

`Notice
Undefined index: search_flood_control
ee/ExpressionEngine/Addons/search/mod.search.php, line 97

Severity: E_NOTICE
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/legacy/libraries/Functions.php, line 458

Severity: E_WARNING`

**Comment by robsonsobral** [comment]
There's already a PR for it. Let me find it...

**Comment by robsonsobral** [comment]
This is fixed at the PR #1410
