### ISSUE TITLE
MSM: Color coding to differentiate MSM sites so you know which site you're editing

### ISSUE THREAD

**Issue by creativearc-paul** [ExpressionEngine/ExpressionEngine#1554]
Probably no need to elaborate on this one.

Something like the attached image could work. Just need a HEX selector in the Site preferences, perhaps.

![msm-color](https://user-images.githubusercontent.com/224037/141197812-16a2cda1-a6ad-4cea-8b9f-756db400e192.jpg)

**Comment by intoeetive** [comment]
@ajohnson what are your thoughts on this? (I think we can achieve this by adding color picker field to MSM site edit page)

**Comment by robsonsobral** [comment]
Jesus, please! I'm working on 59 sites!

---

I think you should start to move some settings out of the `exp_config` table to the `exp_sites`. This settings could be a start.

**Comment by ajohnson** [comment]
@creativearc-paul Thanks for the idea! We've put this into the team's dev schedule to get it implemented in a future update. Can't promise a timeframe, but we'll hit you back as/if we have questions.

@intoeetive Created an internal issue to implement this here: https://packettide.atlassian.net/browse/EECORE-1540

**Comment by robsonsobral** [comment]
(Jesus... They use Jira!)

**Comment by PDXMan1** [comment]
Brilliant! That might have helped me when I built out this project: https://netraising.com/portfolio/san-jose-unified-school-district

**Comment by intoeetive** [comment]
This feature will be included in `6.3.0` release
