### ISSUE TITLE
Deprecated function set_cookie() called in mod.comment.php

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#1558]
Deprecated function set_cookie() called in
/www/htdocs/w01c3b4e/0_EE.melody.de/vib/ee/ExpressionEngine/Addons/comment/mod.comment.php
on line 1747.

Deprecated since 2.8. Use EE_Input::delete_cookie() instead.

**Comment by intoeetive** [comment]
Like 1747 in file `mod.comment.php` as of EE 6.1.6 does not contain `set_cookie()`

Please update your ExpressionEngine installation
