### ISSUE TITLE
`no_results` on Request module

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1559]
Couldn't `{if no_results}` work on `exp:request`?

**Comment by robsonsobral** [comment]
One more thing! There's a bug on the module. Not even the sample on docs work:

```
{exp:request:get name="my-var"}
<li>{item}</li>
{/exp:request:get}
```

The `<li>` is returned only if `my-car` is an array. I've already fixed it, but the PRs are blocked.

**Comment by robsonsobral** [comment]
@intoeetive , please, take a look at my code. It works on my tests, but not on my website. Probably, is an error on the website I'm working on. Please, check!

**Comment by intoeetive** [comment]
@robsonsobral what's the error that you get? And what's the template code and how the URL looks like?

**Comment by robsonsobral** [comment]
I'm not getting the content within `{if no_results}{/if}`.

```html
<li class="search-form__options-item">
    <input type="radio" name="required" id="news" value=""
        {exp:request:get name="required"}
            {if no_results}
                checked
            {/if}
            {if item != "fotos" && item != "videos"}
                checked
            {/if}
        {/exp:request:get}
    />
    <label for="news">Notícias</label>
</li>
```

It works on `http://localhost/test/`, but not on `http://localhost/agencia-de-noticias/`. It's probably my fault, but it's better to make sure.

**Comment by intoeetive** [comment]
It does work for me on the PRed branch.

The common pitfall with `{if no_results}` is that if you're nesting tags (e.g. your `{exp:request:get}` is inside `{exp:channel:entries}` or other tag) then you need to specify `{if no_results}` pair for each tag in order for this to work correctly

**Comment by robsonsobral** [comment]
Thank you! Yeah, we need `{if MODULE:no_results}`.

Thank you!
