### ISSUE TITLE
 Updated to 5.2.0 with errors with "{if}"s

### ISSUE THREAD

**Issue by jamesraffield** [ExpressionEngine/ExpressionEngine#156]
I just updated to 5.2.0 and I have a page that runs a lot of "{if}"s. Once I updated I am getting a "You have an invalid conditional in your template. Please review your conditionals for an unclosed string, invalid operators, a missing }, or a missing {/if}." Before I updated I had no errors and now after the update I am running into all kinds of errors. I don't really want to restore since the rest of the site seems to be working fine. FYI...I do have "{if}"s inside of relationship tags and believe that is where the errors are coming from.

**Comment by kevincupp** [comment]
Could you update to 5.2.1 and see if that fixes the problem?

**Comment by jamesraffield** [comment]
That fixed it. Thank you very much.
