### ISSUE TITLE
password_confirm fields should not have autocomplete="new-password"

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1572]
This attribute value triggers the "generate new password" feature in browsers, which is a problem when what you need to do is enter your *existing* password.

**Comment by intoeetive** [comment]
I believe this is duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/209 and has been resolved in EE 6.1.6 https://github.com/ExpressionEngine/ExpressionEngine/pull/1194

**Comment by murtaugh** [comment]
The password field in the Member Role Assignment form still has this attribute.

**Comment by intoeetive** [comment]
This is getting fixed in `6.2.0` release
