### ISSUE TITLE
Language files in the wrong place after updating?

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1578]
After updating to the most recent release, I notice that I can not access my language files.

When I click into the default English language, I get the message `Language files cannot be accessed. Please consult documentation on placing the files into right folder.` As far as I can tell, the files are exactly where they were. (`~/system/ee/language/english`).

When I click into my custom language, I get a 404, even though the files are exactly where they were before (`~/system/user/language/custom`).

**How To Reproduce**
1. Go to Tools > CP Translation
2. Click on the default language, then any custom language.

**Additional context**
I do not know for sure that this started happening with the latest update, it's been a little while since I've tried to work with the language files.

**Comment by intoeetive** [comment]
@murtaugh please make sure the folder name is all lower case, i.e. `english` not `English`

**Comment by murtaugh** [comment]
I made a typo in the above — the folder name is lowercase on the server.

**Comment by murtaugh** [comment]
I also did not mention: 

The message the 404 error give me is that it can't find my custom language file at this location: `cp/utilities/translate/custom`

This is unclear, since it's not where the language files used to be, and I don't actually know which `cp` folder it's referring to.

**Comment by murtaugh** [comment]
I have removed the custom language files I had in place, just to clear the slate. I also migrated the default language files from a fresh download of EE. They are in the right place, with the right permissions and I'm still getting this error:

`Language files cannot be accessed. Please consult documentation on placing the files into right folder.`

The error references the documentation which doesn't offer any guidance about the default language files not being able to be accessed.

**Comment by murtaugh** [comment]
I can still click to manage each of the language files, but attempting to save data to them fails without a specific error.

**Comment by robinsowell** [comment]
I'm able to replicate on 6.1.5.  It looks like the APPPATH is wrong in some versions- 6.1.5/system/ee/legacy/ - that's where it's looking for language folders, but that is not right.  We shall poke!

**Comment by robinsowell** [comment]
Quick question- can you double check you're on 6.1.6?  Because I suspect it may be fixed there.

**Comment by murtaugh** [comment]
My install is reporting 6.1.6

**Comment by murtaugh** [comment]
Actually, wait a moment, I might have a source control issue, let me verify.

**Comment by murtaugh** [comment]
Ok, belay my last message. I compared my install to a fresh download of 6.1.6 and found nothing out of place.

**Comment by intoeetive** [comment]
Since we were not able to replicate the issue, and also did not get more reports of this behavior, I will close the issue
