### ISSUE TITLE
Author listing for default Channel Form author does not account for > 100 authors

### ISSUE THREAD

**Issue by amphibian** [ExpressionEngine/ExpressionEngine#1582]
When an author is selected in a channel's "default author" field of it's Channel Form settings, and that author is past the 100 default limit of the Member service's `getAuthors() `function (e.g., found by searching for the author), subsequent loads of that channel's settings screen will not reflect the actually chosen author. Instead it will default to selecting the first author in the list.

**Comment by intoeetive** [comment]
@amphibian which EE version are you running?

**Comment by amphibian** [comment]
Sorry - this is with 6.1.4.
