### ISSUE TITLE
Filesystem->normalize() method redundant...

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#1583]
**Is your feature request related to a problem? Please describe.**
The `normalize()` method in the [EE Filesystem Class](https://github.com/ExpressionEngine/ExpressionEngine/blob/6.dev/system/ee/ExpressionEngine/Library/Filesystem/Filesystem.php) is redundant.  Here it is the entire code... 

```
    /**
     * Normalize the path for a native function call
     *
     * This is used by classes that extend this one to, for example, root
     * the filesystem in a specific location. It can also be used for sanity
     * checks, but beware that it is slow.
     */
    protected function normalize($path)
    {
        return $path;
    }
```
From the docblock text it seems that once this method did more, and at some later point this functionality was removed.

A search of the EE codebase indicates that this function is **only** called from elsewhere within the Filesystem class - but therein it is called in 30 different places.

**Describe the solution you'd like**
Since this function does nothing and appears to only be used within the Class itself, removing it completely would lead to more efficient code.

**Describe alternatives you've considered**
Leaving it in is an option, but is relatively inefficient compared to removing it.

**Teachability, Documentation, Adoption, Migration Strategy**
This whole class is currently undocmented... so not a big hit here !

- [x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
I agree with the sentiment here, but calling out for @bryannielsen expertise whether we can feel safe about removing it

**Comment by bryannielsen** [comment]
I also agree this function doesn't seem to do much but it is doing a little more in the [Directory](https://github.com/ExpressionEngine/ExpressionEngine/blob/6.dev/system/ee/ExpressionEngine/Service/File/Directory.php#L32-L41) class that extends the Filesystem class so I think we need to keep it around for now until a larger refactor and cleanup of the filesystem can happen.
