### ISSUE TITLE
Creating an entry via the API fails when field data stored in its own table.

### ISSUE THREAD

**Issue by boilerroomdigital** [ExpressionEngine/ExpressionEngine#159]
I use the legacy API to inset entries in my extension. In particular, if the site settings entry doesn't exist, I create it using the following code:

```
// Create a new settings entry
ee()->load->library('api');
ee()->legacy_api->instantiate('channel_entries');
ee()->legacy_api->instantiate('channel_fields');
					
$channel_id = $settings_channel_id;
																								
$data = array(
    'title'         => "Site Settings" ,
);
										
ee()->api_channel_fields->fetch_custom_channel_fields(); 
ee()->api_channel_fields->setup_entry_settings($channel_id, $data);
					
if (ee()->api_channel_entries->save_entry($data, $channel_id, '') === FALSE)
{
    show_error('An Error Occurred Site settings');
}					

```

When this code runs, I see an error 

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_ft_326' in 'field list':`

And a long field list. 

field id 326 has only just been created on my site, and the API is trying but failing to find it in exp_channel_data because it lives in exp_channel_data_field_326. (It's the only field that has its own table as this site has just been upgraded from Version 3.

To replicate, create some new fields and then try inserting an entry using the Channel Entries API.

**Comment by kevincupp** [comment]
This legacy API probably isn't going to get updated. Can you use the `ChannelEntry` model instead? In general, we'd recommend not using anything labeled "legacy" if there's a replacement for it.

**Comment by boilerroomdigital** [comment]
OK - that's fine. Is there anywhere where there's an example of how to use the `ChannelEntry` model? Would be great if someone could point me in the right direction. I'm updating a site to from EE2 via EE3.

**Comment by kevincupp** [comment]
The [Model Service](https://docs.expressionengine.com/latest/development/services/model.html) documentation is meant to be generically applied to all models, but here's what it might look like for that particular model:

```php
$entry = ee('Model')->make('ChannelEntry');
$entry->title = 'Entry title';
$entry->entry_date = ee()->localize->now;
$entry->status = 'open';
$entry->channel_id = 1;
$entry->author_id = 1;
$entry->field_id_1 = 'Some custom field value';
$entry->save();
```

**Comment by boilerroomdigital** [comment]
Thanks, that’s really helpful. :)

**Comment by boilerroomdigital** [comment]
Hi again - one more quick question about using the EE models to RETRIEVE data to get an array of all custom fields. I have this so far:

$settings = ee('Model')->get('ChannelEntry')->filter('channel_id', '13')->first();

Settings returns an object, but I can’t quite work out how to get an array of the custom fields from it. I assume that this would be possible, and easier than querying/joining multiple data fields.

Would really appreciate any help you can give.

**Comment by scbarber** [comment]
The custom fields should already be populated on the model. So if you had field ID 12 assigned to the Channel for that Entry, you could do `$settings->field_id_12` to gain access. You can also do `$settings->getCustomFields()` if you would like an array of all the custom fields for the Entry; however that will return an array of [FieldFacade](https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/system/ee/EllisLab/ExpressionEngine/Model/Content/FieldFacade.php) objects.
