### ISSUE TITLE
Conditionals exiting on first OR

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1592]
Given:

```html
{if bidding__files:total_rows || bidding__notice:total_rows || bidding__edict:total_rows}
some code
{/if}
```

In case, `{bidding__files:total_rows}` returns `0`, the conditional evaluates as false completely.

```html
<pre>
bidding__files:total_rows: {bidding__files:total_rows}
bidding__notice:total_rows: {bidding__notice:total_rows}
bidding__edict:total_rows: {bidding__edict:total_rows}
</pre>
```

Evaluates as:

```html
<pre>
bidding__files:total_rows: 0
bidding__notice:total_rows: 1
bidding__edict:total_rows: 1
</pre>
```

**Comment by intoeetive** [comment]
Confirming the issue.

If you have a separate conditional where `:total_rows` is checked for Grid that's not empty, then the "bigger" conditional works correctly. Otherwise it return `false` (while should be true)

**Comment by intoeetive** [comment]
Turns out that if `:total_rows` is not first/only thing in conditional, then the conditional is parsed before this variable is populated. So it returns as `BOOL (false)`.

I also notices that if I do
```
{if grid:total_rows OR 0}TRUE{/if}
```
it takes 2 passes to calculate (and the `grid:total_rows` is present on 2nd pass)

but if I do 
```
{if 0 OR grid:total_rows}TRUE{/if}
```
it takes 3 passes and the variable is never there

**Comment by intoeetive** [comment]
This appears to be limitation of ExpressionEngine template parser. It is possible to use variable modifier (such as `:total_rows`) if that is the only variable in conditional expressions

If there is need to use more modifiers, braces need to be used.

The following works:
```
{if {bidding__files:total_rows} || {bidding__notice:total_rows} || {bidding__edict:total_rows}}
some code
{/if}
```
