### ISSUE TITLE
Member Profile URL segment field only present if $config['legacy_member_templates'] = 'y';

### ISSUE THREAD

**Issue by mcfarlandonline** [ExpressionEngine/ExpressionEngine#1595]
EE 6.1.6
PHP 7.3

The "Member profile URL segment" field under System Settings > URL and Path Settings is only showing up for me if I add this to my config file: 

> $config['legacy_member_templates'] = 'y';

Is this method deprecated, or is there a different way to get the field to show up? 
It's still showing in the docs, (albeit listed as just "Profile URL segment"): 

> https://docs.expressionengine.com/latest/control-panel/settings/urls.html#profile-url-segment

**Comment by ops-andy** [comment]
@mcfarlandonline this is expected. looks like we need to add more notes to the docs in other places though. On the Profile Templates page we note that you must add the config override for Legacy Templates to work. https://docs.expressionengine.com/latest/member/profile-templates.html

**Comment by ops-andy** [comment]
this will be resolved when we next deploy `6.dev` branch of the docs with the release of EE v6.2
