### ISSUE TITLE
Channel mandatory fields are not working properly

### ISSUE THREAD

**Issue by bobural** [ExpressionEngine/ExpressionEngine#16]
Steps to reproduce:
- Have one channel created (apples), assign 2 fields (textarea and text input) assigned to it. The fields have **Require field** checked (activated)
- Have in front end a channel form to this channel (appels).
- Input text
- Get error: "The form you submitted contained the following errors" even if I have text imputed to them.
- Unchecked the **Require field** from Admin Panel.
- Now it works... I can submit messaged from front end to my channel (apples) channel.

**Comment by derekjones** [comment]
Please provide the full Channel Form tag and complete errors, thanks!

**Comment by bobural** [comment]
channel form:
```
{exp:channel:form channel="test_channel"}
	<input name="title" type="text">
	<textarea name="{test_text_area}" id="{test_text_area}">{test_text_area}</textarea>

	<input type="submit" value="Submit">
{/exp:channel:form}

```
and the error I get:

`The form you submitted contained the following errors
test-text-area: This field is required.
test_text_area: This field is required.
Return to Previous Page`

**Comment by bobural** [comment]
My **test_text_area** field is in **test Field Group** and the group is assigned to my **test_channel**
**test_text_area** also if I disable in **Require field** I can post an entry but the content is not displayed in that entry..

**Comment by kevincupp** [comment]
Why are you putting the field contents as the `name=` and `id=`? I wouldn't think that would work well.

**Comment by bobural** [comment]
I found the example here: https://docs.expressionengine.com/latest/channel/channel_form/index.html

**Comment by kevincupp** [comment]
There is no example where a variable is used as the `name=` or `id=`, except when using a `{custom_fields}` loop.

**Comment by bobural** [comment]
You are right. My bad. 

Thank you.
