### ISSUE TITLE
Memory warning when uploading an avatar

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#1611]
EE 6.1.6
PHP Version 7.4.25

I'm trying to upload an avatar in the backend. I'm logged in as a SuperUser.
It is a jpg (tried several), 151x176 pixel, 5,34 KB.

The upload fails with the following warning:

![memory](https://user-images.githubusercontent.com/6132998/144720089-6249d37b-252c-4019-a8c6-fe45ed74c377.jpg)

Probably related (but not checked yet):  According to phpinfo() memory_limit in PHP is -1.

Uploading images via the filemanager or channel fields works as supposed.

**Comment by silenz88** [comment]
I inserted 
`var_dump($memory_limit);`
in ee/ExpressionEngine/Service/Memory/Memory.php, line 34
and tried again.
Result:
int(-1)
int(-1)
int(-1043106)

When I insert a `return` at the beginning of the function the image uploads without problems.

**Comment by silenz88** [comment]
Another note: The images are actually uploaded. 
So the error occurs after the upload but before renaming the file.

**Comment by intoeetive** [comment]
Looking at the screens, this seems to be EE5 installation? Are you able to replicate this on EE6 install as well?

**Comment by silenz88** [comment]
It is 6.1.6
There's no EllisLab folder in the path.
