### ISSUE TITLE
6.1.6 ft.forms.php Error

### ISSUE THREAD

**Issue by nickpuglisi** [ExpressionEngine/ExpressionEngine#1612]
Upgraded to PRO 6.1.6 today, everything was running fine, however now when contributing anything to our site receive this error on the frontend: 

```
Unable to load requested field type file: ft.forms.php.
Confirm the fieldtype file is located in the /system/user/addons/ directory
```

No clue what add-on that could be triggering this? 

EE (PRO) 6.1.6
PHP Version 7.4.3
Ubuntu 18
Running Nginx

**Comment by intoeetive** [comment]
This indicates that Forms add-on is installed, but the files are not present (likely have been removed without completing correct uninstall). 

I would suggest to bring the files back in place, and perform correct module uninstall from the control panel, if you don't need it anymore.

**Comment by nickpuglisi** [comment]
I don’t have the Forms add-on… so I’m not sure where this file came or comes from?

**Comment by intoeetive** [comment]
If you go to `exp_fieldtypes` in your database, do you see `forms` there? If you are not using it, it's save to delete - however I'm clueless how it got in there.

Also, at what point do you get errors - is that when clicking "save" in front-end edit popups?

**Comment by nickpuglisi** [comment]
Will take a look at the file types. I’ll be honest the “forms” add on doesn’t sound familiar at all. And nothing close enabled in Admin console…

Error popped up upon any front end form loading. Not submittal. 


• Sent from iPhone

**Comment by TomJaeger** [comment]
My gut reaction was the same as Yuri's... to check the exp_fieldtypes table.
