### ISSUE TITLE
fluid field dropdown issue

### ISSUE THREAD

**Issue by thomasdefilippis** [ExpressionEngine/ExpressionEngine#1619]
``When I added more than 19 fields in a fluid field, the field selector switches over to a dropdown menu. However, if you select the dropdown menu, you cannot view all of the options and select them. 

<img width="1059" alt="Screen Shot 2021-12-07 at 2 55 24 PM" src="https://user-images.githubusercontent.com/61485862/145112131-2f95219c-db18-4b59-86ea-8b935d14debe.png">

This is probably not an issue on screens with a higher widths as you would never add enough fields to fill up the height of a large screen. Nonetheless, it is not possible to add as many fields as you like because they cannot be selected on the dropdown.

The file that controls this functionality is at system/ee/ExpressionEngine/Addons/fluid_field/views/filters.php and the code is as follows:
```
<?php if (count($fields) < 20) : ?>
	<?php foreach ($fields as $field): ?>
		<a href="#" class="button button--auto button--default button--small" data-field-name="<?=$field->getShortName()?>">
			<img src="<?=$field->getIcon()?>" width="16" height="16" alt="<?=lang('add')?> <?=$field->getItem('field_label')?>" /><br />
			<?=lang('add')?> <?=$field->getItem('field_label')?>
		</a>
	<?php endforeach; ?>
<?php else: ?>
	<a href="javascript:void(0)" class="js-dropdown-toggle button button--auto button--default button--small"><i class="fa-2x icon--add"></i><br /> <?=lang('add_field')?></a>
	<div class="dropdown">
		<?php foreach ($fields as $field): ?>
			<a href="#" class="dropdown__link" data-field-name="<?=$field->getShortName()?>"><img src="<?=$field->getIcon()?>" width="12" height="12" /> <?=$field->getItem('field_label')?></a>
		<?php endforeach; ?>
	</div>
<?php endif; ?>
```

A solution would be to set a max-height and an overflow:auto on the div.dropdown so that you can access all the fields. I would have made a pull request, but I didn't want to just add an inline style and all the css is minified in common.min.css, so I thought it would be best to let the development team take care of it.

Thanks,
Thomas Defilippis

**Comment by intoeetive** [comment]
@thomasdefilippis just to make sure, what EE version are you on?

**Comment by Yulyaswan** [comment]
The dropdown works correctly in EE 6.1.6
https://share.getcloudapp.com/bLudEDQW
![Edit Entry Structure 2-1 ExpressionEngine 2021-12-09 at 2 43 29 PM](https://user-images.githubusercontent.com/23382425/145398709-d4b40a6d-b77c-43e9-b284-a2d331e71320.jpg)

**Comment by thomasdefilippis** [comment]
Perfect! I am on 6.0.3. Will be updating this week to the newest version, so that will fix my issue.

Thanks,
Thomas Defilippis
