### ISSUE TITLE
Channel Import fails with empty message

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#1623]
EE 6.1.6

I tried to import a Channel Set with the following not particularly helpful result:

![cahnnelimport](https://user-images.githubusercontent.com/6132998/145200488-46eb01c6-77a7-4aec-9180-5e1974f2ebc7.jpg)

Language is set to English.

**Comment by robsonsobral** [comment]
Do these channels use already created fields?

**Comment by silenz88** [comment]
None of the fieldnames in the set are currently present on the site,

**Comment by robsonsobral** [comment]
Just to make sure it isn't my fault.

Maybe @intoeetive can help you.

**Comment by silenz88** [comment]
I did resolve it in the meantime by removing a relationship field and the corresponding channel from the JSON which was not needed on the new site.

Just a wild guess though what might be problematic. So the main issue is that the error message leaves you clueless.

**Comment by robsonsobral** [comment]
Hmmmnnnn... This can help.

Glad you found a way.

**Comment by silenz88** [comment]
I still have problems with this.
I created a new site. Exported a channel from a different site. Tried to import it on the new site and:
![Zwischenablage01](https://user-images.githubusercontent.com/6132998/158027614-f96f6aaa-f8ef-4261-aeb0-9ba4a8e3f0b8.jpg)

EE 6.2.7

**Comment by intoeetive** [comment]
Confirming the errors reporting here is not very useful.
This is what I got on my test:
![image](https://user-images.githubusercontent.com/752126/186170449-cf74c7de-655f-42d7-acb2-50d6f562655e.png)
We'll see what we can do to improve it
