### ISSUE TITLE
Request for Core Hook Page Output.

### ISSUE THREAD

**Issue by hmimthiaz** [ExpressionEngine/ExpressionEngine#163]
**Is your feature request related to a problem? Please describe.**
It is not a problem, it would be a nice to have hook where we can control the output of a page.

**Describe the solution you'd like**
I looking for a solution to capture the full output of page
`//system/ee/legacy/core/Output.php

//function _display

if (ee()->extensions->active_hook('page_output') === TRUE)
{
	$output = ee()->extensions->call('page_output', $output);
}
echo $output;
`

**Describe alternatives you've considered**
Currently I don't see any way to do this

- [ Yes ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by kevincupp** [comment]
Thanks for the request. What are you looking to do with this hook that you can't do with the `template_post_parse` hook?

**Comment by hmimthiaz** [comment]
I am trying to implement full page caching of the website. template_post_parse is called many time before the final template is formed. 

Also move the header output just before the echo $output. This was with single hook we can process both. 

`        
// -------------------------------------------
// 'display_output' hook.
//  - Modify the HTML output of the message
//
if (ee()->extensions->active_hook('display_output') === TRUE)
{
	$output = ee()->extensions->call('display_output', $output, $this);
}
//
// -------------------------------------------

// Are there any server headers to send?
if (count($this->headers) > 0)
{
	foreach ($this->headers as $header)
	{
	    @header($header[0], $header[1]);
	}
}

// --------------------------------------------------------------------
echo $output;  // Send it to the browser!

`

**Comment by derekjones** [comment]
I think it would be better if full page caching were built-in to the CMS rather than opening a very broad hook that would encourage regex parsing of HTML output. Perhaps instead of developing an extension for this, you can just propose it as a new feature for the CMS or even submit a Pull Request. Then all users benefit and you aren't maintaining an extension, and the app doesn't open itself up with such a potentially abusive hook.
