### ISSUE TITLE
Minified debug css has a square in content field for Font Awesome's before pseudo elements

### ISSUE THREAD

**Issue by erinathop** [ExpressionEngine/ExpressionEngine#1638]
I'm trying to amend an issue with Font Awesome icons not appearing on the front-end while logged into the CP. I implemented a temporary hot-fix on our site previously, but i'm seeing that there were changes made to `themes/ee/debug/css/eecms-debug.min.css` that have removed the correct FA content in the `::before{}` pseudo element. 

Example: 

```
.fa-arrow-alt-circle-left:before{
    content:"[]";
}
```

Should be:

```
.fa-arrow-alt-circle-left:before{
    content:"\f359";
}
```

**Comment by intoeetive** [comment]
@erinathop can you tell us where exactly the issue is? Maybe send us a screenshot

**Comment by erinathop** [comment]
@intoeetive The issue is appearing in `themes/ee/debug/css/eecms-debug.min.css`

![image](https://user-images.githubusercontent.com/87494039/148125043-d70e9376-c4c4-4ebc-b91f-f5977d5cdebf.png)

**Comment by intoeetive** [comment]
I am not seeing this in latest released version of EE. My suspect is that you've had this file open with some editor that screwed up here. Try reverting to the original version.
