### ISSUE TITLE
File upload directories should be sorted alphabetically in chooser when uploading from New/Edit Entry form

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#164]
**Description of the problem**
The fix for #128 is only partial. It sorts file upload directories in the File Manager's chooser, but not in the file upload modal when uploading a file from the New/Edit Entry form.

**Comment by kevincupp** [comment]
Ah sorry Paul. Do you mean in the filter? If so, I've just fixed that.
