### ISSUE TITLE
Issues with the new Fluid field hooks

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#1643]
Sorry it's taken so long to get around to actually using the new hooks as they were implemented, and thanks for adding them, but their current implementation falls a little short. My original submission included passing the FluidField instance, if available at the time of the hook call, as the first parameter of the hook call. Having the full instance available provides a lot of information, such as the fluid_field_id, and entry_id being enacted upon. It looks like the `fluid_field_add_field` and `fluid_field_get_all_data` hook signatures were changed.

Originally submitted as

`fluid_field_get_all_data($entryId, $fluidFieldId)`
`fluid_field_add_field(FluidField $fluidField, $fieldTableName, $fieldData)`

but they're currently

`fluid_field_get_all_data(FieldData $fieldData)`
`fluid_field_add_field($fieldTableName, $fieldData)`

When I call the `fluid_field_add_field` from what I can tell when setting a break point, is that with the new method signature I have no way of knowing what the entry_id or the fluid_field_id is.

Originally submitted the signatures as:

```
public function fluid_field_get_all_data($entryId, $fluidFieldId): Collection|array
public function fluid_field_get_field_data($fieldId, $fieldDataId): array
public function fluid_field_add_field(FluidField $fluidField, $fieldTableName, $values): array
public function fluid_field_update_field(FluidField $fluidField, $fieldTableName, $values): array
public function fluid_field_remove_field(FluidField $fluidField): void
```

Ideally they'd all have `FluidField $fluidField` as the first parameter. It's important to know the `entry_id`, `field_id`, `fluid_field_id`, and the state of any array data of the field when the hook is called.

For example with the current implementation of `fluid_field_add_field` I have no idea what the `entry_id` or the `fluid_field_id` is :(

<img width="977" alt="Screen Shot 2021-12-10 at 2 34 54 PM" src="https://user-images.githubusercontent.com/53965/145640647-2518e014-0df9-4014-9603-7236899241f0.png">

**Comment by intoeetive** [comment]
@dougblackjr it looks like you worked on this originally, do you have any insight?
