### ISSUE TITLE
File Grid fields broken after import of Channel Set

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#1645]
EE 6.1.6

After importing a channel set with several fields I was not able to create a new entry because for all included file-grid-fields the extra-grid-table was missing.

Normal grid-fields in that Channel Set did not pose any problem.

Error when trying to save the entry:
![importc](https://user-images.githubusercontent.com/6132998/145725078-e612758d-30c1-4830-bf27-a7a4e434d908.jpg)

**Comment by intoeetive** [comment]
@silenz88 I did not dig too deep, but can you try this change?

In `system\ee\ExpressionEngine\Service\ChannelSet\Set.php` change line 781 to `$this->importGrid($field, $value, $type);`

Then in same file on line 870 change to `private function importGrid($field, $columns, $type = 'grid')`
and below it, change 2 occurrences of `$_POST['grid']` to `$_POST[$type]`

**Comment by silenz88** [comment]
I'm afraid I have no capacities right now to test it. I deleted and recreated the fields and moved on.

**Comment by intoeetive** [comment]
No worries. We'll have this checked later

**Comment by silenz88** [comment]
> @silenz88 I did not dig too deep, but can you try this change?
> 
> In `system\ee\ExpressionEngine\Service\ChannelSet\Set.php` change line 781 to `$this->importGrid($field, $value, $type);`
> 
> Then in same file on line 870 change to `private function importGrid($field, $columns, $type = 'grid')` and below it, change 2 occurrences of `$_POST['grid']` to `$_POST[$type]`

Applying that change only led to a bunch of other errors and no action being taken at all.
