### ISSUE TITLE
Redactor and material link from Channels

### ISSUE THREAD

**Issue by benya** [ExpressionEngine/ExpressionEngine#1653]
https://prnt.sc/22ym7gs

For the Pages module in the Redactor editor, it is possible to specify a link to a page via {id}.

Can you do this for materials from Channels?

**Comment by intoeetive** [comment]
In ExpressionEngine there is not always direct relation between entry and URL, unless you use Pages module (or Structure etc.). You can display entry on many different URLs.

Therefore auto-linking for regular entries that are not Pages is not possible.
