### ISSUE TITLE
Allow files to be moved to a new destination folder

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1657]
As you're setting up a site, or sometimes after you launch, you might want to change how files are organized. Or, perhaps a user has been uploading their files to the wrong destination, which isn't the end of the world, but you like things to be nice and orderly.

At the moment, there's no way to move files from one upload destination to another, so you either need to live with your mistakes, or physically move your files and do some search and replace work in the database.

**Describe the solution you'd like**
1. Most of the time I'm interested in moving multiple files at once, so ideally it would be nice if "Move file(s) to..." was an option in the bulk action bar. A modal would open up, letting you select a folder to move them to.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/308752/146051004-c15db278-c706-46e8-8cc8-39ecae3f6814.png">

2. Secondarily, a dropdown letting you choose a new folder could be added to the Edit File Meta Data modal. This would be nice to have, but not a replacement for solution 1, since moving a lot of files one at a time would be a nightmare.

**Comment by intoeetive** [comment]
Moving the files is now possible in ExpressionEngine 7
