### ISSUE TITLE
Error when creating a template group with suggested valid characters

### ISSUE THREAD

**Issue by mindpixel-labs** [ExpressionEngine/ExpressionEngine#166]
**Description of the problem**
An observation I made in the Template Manager when creating groups. It says you can have a period within a template group but I get an error when it goes to create it. For example: **.my-template-group**

While it doesn't make sense to create a template group that would be hidden, it may be best to still validate the user input and let them know not to do that.

**How To Reproduce**
1. Create a template group called **.my-template-group**
2. Hit save and you will be redirected to an error message that says **Error: The Template Group _my-template-group does not exist.**
3. If you go back to the Template Manager, it does show the template as created with the correct name, but if go to click it you will get the same error.

**Error Messages**

<pre>Error: The Template Group _my-template-group does not exist.<code>

</code></pre>

**Screenshots / Videos / Template Code**
**Example 1:**
Just an example here where I triggered an error explicitly to see the available valid characters within a template group.
![image](https://user-images.githubusercontent.com/32364162/55029913-a2dae080-4fe1-11e9-83cd-7331e2a2e410.png)

**Environment Details:**
 - Version: 5.2.1
 - PHP Version 7.2
 - MySQL Version 5.6
 - OS: macOS High Sierra 10.13.6
 - Web Server: Apache

**Possible Solution**
The error message/suggested valid characters should exclude the dot for template groups. 

Let me know if you need any more details!

**Comment by kevincupp** [comment]
This is actually a quirk in how PHP handles variable names in `$_GET`:

http://ca.php.net/variables.external#language.variables.external.dot-in-names

We'll have to work around it. Thanks for the report!
