### ISSUE TITLE
Choose method of transliteration on slugs creation

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1664]
**Is your feature request related to a problem? Please describe.**
Diacritics are converted on URL titles using, for example, "ão" to "aeo", which isn't expected to Brazilian users.

**Describe the solution you'd like**
I would like to set plain transliteration of characters. For example, "ão" to "ao".

**Teachability, Documentation, Adoption, Migration Strategy**
We could have a config override to set that.

- [x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
This isn't well documented, but you can create `system/user/config/foreign_chars.php` file and define your own characters map there. (You can see the default one in `system\ee\ExpressionEngine\Config\foreign_chars.php`)

Alternatively, there is an extension hook: `foreign_character_conversion_array`
