### ISSUE TITLE
stray HTML-Tag on all CP pages

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#1673]
EE 6.1.6

On all CP pages a stray `</i>`-Tag is rendered before the main title.

```
<div class="main-nav__title">
		<h1></i> Entries</h1>
</div>
```

**Comment by robsonsobral** [comment]
At [`ExpressionEngine/system/ee/ExpressionEngine/View/_templates/default-nav.php`](https://github.com/ExpressionEngine/ExpressionEngine/blob/292951c13a4e6a1605d08b7aac1e86641e39e9b9/system/ee/ExpressionEngine/View/_templates/default-nav.php#L17)

```
	<div class="main-nav__title">
		<h1></i> <?=$header['title']?></h1>
	</div>
```
