### ISSUE TITLE
UX file upload

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#1679]
EE 6.1.6
RTE field with Redactor

When I click the File Upload-Button the modal that opens and shows 25 files in list view spans about 3 screens vertically.

Then I have to select an upload directory (although there is one configured in the Redactor config) and have to scroll 3 screens down to find the upload button. (If I forgot to select a directory I find nothing and have to scroll up again and down again.) 

Upon clicking the upload button, I'm left with only the white backdrop. So I have to scroll up 3 screens to discover the new upload modal.

That can't be right...

**Comment by mcfarlandonline** [comment]
I second this! And it's still an issue in EE 6.2.7

It's super annoying to not have another "Upload New File" button right here...
> <img width="985" alt="Screen Shot 2022-03-25 at 1 09 17 PM" src="https://user-images.githubusercontent.com/20441129/160198589-1828ae2f-69f3-425c-902f-77d68164a941.png">

Someone less tech savvy could get really lost in this process. It's still catching me off guard!

There's already a precedent for a button (at both top & bottom), with the screen/window that comes _**after**_ you select the bottom "Upload New File" button...
> <img width="944" alt="Screen Shot 2022-03-25 at 1 09 53 PM" src="https://user-images.githubusercontent.com/20441129/160198729-32800b82-d2cc-414a-868d-8609a526fa84.png">

**Comment by intoeetive** [comment]
With the release of ExpressionEngine 7 and the new File Manager there is no intermediate screen for upload, so this is not relevant anymore.
