### ISSUE TITLE
SEEO

### ISSUE THREAD

**Issue by clifavenu** [ExpressionEngine/ExpressionEngine#1681]
Hi,

We've run into a possible bug with SEEO and Assets. We're running current versions of EE, EEpro, Assets and SEEO. 

SEEEO Settings: OG and Twitter image upload: works perfectly with EE file manager. When using Assets, the images upload but not are not saved. Tried on two sites and the results were the same.

Thanks,
clif

**Comment by TomJaeger** [comment]
Clif thank you for reporting.  We'll have someone jump in and take a peek at this shortly!  (Might be early in the new year when we get an update out)
