### ISSUE TITLE
Make the hover state for the navigation submenu items more distinctive

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1684]
In the navigation dropdown for Channels there are two links for each channel. Clicking the text label takes you to the list of entries, and the `+` takes you to the new entry form. Visually, there's no indication that this dichotomy exists until you hover, and even then it's *extremely* subtle.

Creating a new entry is arguably the most important task the CP offers, and this UI choice has been a source of confusion for clients for a while.

_Hovering over "Landing Pages":_
<img width="281" alt="image" src="https://user-images.githubusercontent.com/308752/147595764-a3ce46b9-6b18-4d9e-93a8-d43a8e11904e.png">

Even when hovering over the label, there's still no indication that there are two actions being presented here.

_Hovering over the `+` in Landing Pages:_
<img width="298" alt="image" src="https://user-images.githubusercontent.com/308752/147595522-c60c1605-012b-4e42-934a-cd4fb98bbd85.png">

The hover state for the `+` is so subtle as to almost not exist.

**Describe the solution you'd like**
Hovering over the label and the `+` should offer distinct hover states.

_Hovering over the `.dropdown__item a:first-child` element:_
<img width="280" alt="image" src="https://user-images.githubusercontent.com/308752/147597072-fc516f09-e4ee-4f78-a3df-b78a065059f0.png">

(An accessibility review would probably tell us that an underline would also be desirable.)

_Hovering over the `.dropdown__item .dropdown__item-button` element:_
<img width="353" alt="Screen Shot 2021-12-28 at 1 16 23 PM" src="https://user-images.githubusercontent.com/308752/147596642-cbb49833-ee1b-4e21-ab7e-141f470e1b2d.png">

I like these suggestions for two reasons:

1. Even though the dichotomy still isn't clear at first glance (which could probably use some thought), the two elements react separately when hovered.
2. The differences between the hover states (one being purely text styles, and one offering a shape that invokes the idea of clicking a button) implies their purpose — clicking the text link brings you to a page full of content, your list of entries; clicking on the button-like thing opens an action for the user to take, an empty form.

**Comment by intoeetive** [comment]
@ajohnson please have a look

**Comment by ajohnson** [comment]
@murtaugh I agree! We've brought this up at internal meetings, but just haven't gotten to it yet. Our solution is slightly different from the examples you've posted, but similar. I'll see what we can do about bumping it up in priority. Thanks!

**Comment by TomJaeger** [comment]
Closing this as it shipped with 6.3.0
