### ISSUE TITLE
Accessibility Issues: Control panel publishing > select dropdown menus, radio, and checkbox fields

### ISSUE THREAD

**Issue by mcfarlandonline** [ExpressionEngine/ExpressionEngine#1686]
EE 6.1.6
PHP 7.3.32

I don't normally use a screenreader, and primarily use a mouse for navigation. However, I find it extremely frustrating while publishing content that I can't keyboard-tab into a select dropdown menu. Having to manually click on the dropdown fields is tedious and inaccessible. See screenshot below for the interface that finally "broke the camel's back" and made me submit this ticket.

While getting ready to submit this issue, I tested a couple other fields and found that checkbox fields and toggles are able to be tabbed to via keyboard. However, they don't have focus states, so unless you're using a screenreader, (like the one Mac OS Monterey provides), or an overlay that adds in this UX, you have no idea and are virtually lost until you start tapping enter and see what happens. 

The "Add Category" button **_barely_** has a focus state. 

Also, radio buttons don't appear to be tab-able, (e.g. to change the entry's author). And they don't have a focus state. 

I second the issues submitted (_over a year ago_) by @blue-dreamer here: https://github.com/ExpressionEngine/ExpressionEngine/issues/556
and by chunkitdesign here: https://github.com/ExpressionEngine/ExpressionEngine/issues/1590

<img width="365" alt="Screen Shot 2021-12-31 at 2 08 29 PM" src="https://user-images.githubusercontent.com/20441129/147839974-83fbca8e-af67-4dce-8fbf-f324c173f312.png">

**Comment by intoeetive** [comment]
@Yulyaswan FYI
