### ISSUE TITLE
SEEO

### ISSUE THREAD

**Issue by clifavenu** [ExpressionEngine/ExpressionEngine#1687]
Hi,
An additional issue has come up with using SEEO: the entry screen preview bombs. Error message coped below. We're using current versions of ee, eepro and seeo.

Thanks,
clif

InvalidArgumentException Caught
No such property: 'cp' on ExpressionEngine\Legacy\Facade

ee/ExpressionEngine/Legacy/Facade.php:128
Stack Trace: Please include when reporting this error

    #0 ee/ExpressionEngine/Legacy/Facade.php(35): ExpressionEngine\Legacy\Facade->get('cp')
    #1 user/addons/seeo/tab.seeo.php(93): ExpressionEngine\Legacy\Facade->__get('cp')
    #2 ee/ExpressionEngine/Model/Channel/ChannelEntry.php(724): Seeo_tab->display(1, 32)
    #3 ee/ExpressionEngine/Model/Channel/ChannelEntry.php(999): ExpressionEngine\Model\Channel\ChannelEntry->getTabFields()
    #4 ee/ExpressionEngine/Model/Content/ContentModel.php(352): ExpressionEngine\Model\Channel\ChannelEntry->getDefaultFields()
    #5 ee/ExpressionEngine/Model/Content/ContentModel.php(300): ExpressionEngine\Model\Content\ContentModel->initializeCustomFields()
    #6 ee/ExpressionEngine/Model/Content/ContentModel.php(186): ExpressionEngine\Model\Content\ContentModel->usesCustomFields()
    #7 ee/ExpressionEngine/Addons/pro/Model/Channel/ChannelEntry.php(34): ExpressionEngine\Model\Content\ContentModel->set(Array)
    #8 ee/ExpressionEngine/Service/LivePreview/LivePreview.php(102): ExpressionEngine\Addons\Pro\Model\Channel\ChannelEntry->set(Array)
    #9 ee/ExpressionEngine/Addons/channel/mod.channel.php(5101): ExpressionEngine\Service\LivePreview\LivePreview->preview('1', '32', NULL)
    #10 ee/legacy/libraries/Actions.php(175): Channel->live_preview()
    #11 ee/legacy/libraries/Core.php(529): EE_Actions->__construct(true, Object(Closure))
    #12 ee/legacy/controllers/ee.php(51): EE_Core->generate_action(true)
    #13 [internal function]: EE->index()
    #14 ee/ExpressionEngine/Core/Core.php(255): call_user_func_array(Array, Array)
    #15 ee/ExpressionEngine/Core/Core.php(111): ExpressionEngine\Core\Core->runController(Array)
    #16 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
    #17 public/index.php(164): require_once('...')
    #17 public/index.php(164): require_once('...')

**Comment by robinsowell** [comment]
I can replicate.  You can get by for now adding this code to system/user/addons/seeo/tab.seeo.php arroun line 92.  But I tend to think that you shouldn't need to and core would load it.  I'm at least kicking it to one of the developers internally for confirmation.

```        // -------------------------------------------------------------------
        // Include system css and theme js files
        // to create character counter
        // -------------------------------------------------------------------
        ee()->router->set_class('cp');
        ee()->load->library('cp');›

        ee()->cp->add_to_foot('<script type="text/javascript" src="' . URL_THIRD_THEMES . 'seeo/javascript/seeo.js"></script>');
        ee()->cp->add_to_head('<link rel="stylesheet" href="' . ee()->config->item('site_url') . 'system/user/addons/seeo/css/seeo.css" type="text/css" media="screen" />');
```

So you're adding this bit:

        ee()->router->set_class('cp');
        ee()->load->library('cp');›
