### ISSUE TITLE
Template settings modal window close button can not be pressed

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#1689]
I can not click on the close button:

![271ede4d-6855-427e-9d3d-b86f2c3871c0](https://user-images.githubusercontent.com/12234507/148376184-f17e3122-139c-4ee7-a16f-ed7f6ea7327c.png)

**Comment by TomJaeger** [comment]
What version of EE is this on?  I believe we have a fix for this (might not be released yet.... digging on that front currently.)

**Comment by shbchk** [comment]
Sorry, 6.1.6
