### ISSUE TITLE
Comment sorting always ascending by date

### ISSUE THREAD

**Issue by mkinberg** [ExpressionEngine/ExpressionEngine#169]
**Description of the problem**
Comments are always displaying as sorted ascending by date.  None of the comment parameters effect the front-end view of the exp:comment:entries tag.  Specifically the date and name parameters.

**How To Reproduce**
A comment tag with any sort and orderby parameters.  Specifically the orderby date and name.

**Environment Details:**
 - Version: 5.2.2
 - PHP Version 7.2
 - MySQL Version 5.7
 - OS: Linux
 - Web Server: Apache 2.4

**Comment by derekjones** [comment]
Can you share your template tags for what's not working? `sort='asc'` and `sort='desc'` are behaving as expected for me, reversing the order of the comments displayed by date.

**Comment by mkinberg** [comment]
Hey Derek,

I’m using the following:  {exp:comment:entries channel="portal_blogDet_phys" sort="desc" orderby="date”}

It’s located within an embed from my main blog detail template.  It might be helpful to note this is an EE2 —> EE5 upgraded site.  


-mk




Matt Kinberg
Digital Mullet / CEO & Founder
Direct: 425-214-6949
Seattle, WA



 <http://www.digitalmullet.com/>

Matt Kinberg <https://www.linkedin.com/in/mattkinberg/>
Digital Mullet / CEO & Founder
Direct: 425-214-6949
Seattle, WA
 <https://www.linkedin.com/in/mattkinberg/>

**Comment by derekjones** [comment]
That it's embedded or from an upgrade shouldn't be affecting it. Just for testing and isolating the issue, if you put your comment entries tag by itself on a new template, are you able to control the order of the comments? Also I'm not sure if it's a cut/paste or formatting issue at GitHub, but you've got a curly quote in one of your parameters, so you might double check those and manually retype `'` or `"` to be sure.

**Comment by mkinberg** [comment]
Confirmed - The curly quote is from Github (email reply).
Confirmed - An new, isolated comment entries template still only displays ascending by date.

**Comment by derekjones** [comment]
Any extensions installed? Not really sure what could be going on, I can't replicate on a clean install. Do all the comments in question have a different date? i.e. they weren't imported and all have identical timestamps or something?

**Comment by mkinberg** [comment]
BINGO.  Threaded Comments is installed and is causing this issue.  Thanks for the quick support Derek!

**Comment by derekjones** [comment]
🕵🏻‍♂️😉

**Comment by ops-andy** [comment]
this seems to have already been resolved.
