### ISSUE TITLE
Add-ons store bug: category URL doesn't work

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#1690]
For example: [https://expressionengine.com/add-ons/category/security](https://expressionengine.com/add-ons/category/security)

**Comment by intoeetive** [comment]
@ops-andy this seems to be still an issue with the add-ons Store

**Comment by intoeetive** [comment]
@matthewjohns0n something you could check?

**Comment by matthewjohns0n** [comment]
This is fixed in this PR:
https://github.com/packettide/expressionengine.com/pull/404
