### ISSUE TITLE
Parsing of variables broken if variable only appears within a CSS rule within a template

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#1698]
Bug has been reported affecting the JCOGS Image addon, but it appears to be actually a quirk of EE's evaluation of a variable that happens (due to template design) to be enclosed within a pair of curly brackets.

If the only place a variable is called is within a pair of curly brackets (e.g. because it is contributing to a computed CSS rule) the variable is not evaluated - if the value is a parameter for an Add-on function then the variable itself is passed to the add-on not its value.

Removing the enclosing brackets fixes the issue (but breaks the CSS rule), but so also does calling the variable at least once more in a location that is **outside** the curly brackets - suggesting that the issue is with the evaluation process rather than the parsing process - since if the variable is evaluated due some other call on the variable, when the variable is parsed from within the CSS rule the correct value is provided.

Example follows.

For a channel with file parameter `{background_image}` and this construct:
```
{exp:channel:entries entry_id='X'}
{layout:set name="css"}
<style>
.bgimage {
    background-image: url('{exp:jcogs_img:image src="{background_image}" width="480" allow_scale_larger="yes" crop="yes" output="{made}"}'); 
}
</style>
{/layout:set}
{/exp:channel:entries}
```
The jcogs image tag receives the value for `src` the text '{background_image}' via `ee()->TMPL->fetch_param('src')`.

If you modify the code to call `{background_image}` outside of the CSS construction the **value** of `{background_image}` is sent to jcogs image instead of the variable name as text.  So this code 'works':
```
{exp:channel:entries entry_id='X'}
{layout:set name="css"}
<style>
.bgimage {
    junk: {background_image};
    background-image: url('{exp:jcogs_img:image src="{background_image}" width="480" allow_scale_larger="yes" crop="yes" output="{made}"}'); 
}
</style>
{/layout:set}
{/exp:channel:entries}
```
This suggests that something specific in the background-image CSS construction is preventing EE from evaluating the variable.
It does not seem to matter where the second instance of the variable appears in the template, as long as it does. If the only instance(s) are within background-image constructions the variable is not rendered.

There is a work around (simply include the variable in some other construct within same template) but it would be good to understand (and fix) this issue.

Any thoughts on how to resolve the underlying issue would be valued.

**Comment by jcogs-design** [comment]
Upon further investigation it appears to be the inclusion of curly brackets in the CSS definition that is causing the problem.

In this example `{image}` is an EE file field that only appears once in the template - in this CSS structure - and contains reference to a local image stored within the EE File area.

This code
```
<style> .stuff   {         
        something:    {exp:jcogs_img:single
            width='300'
            src="{image}"
            url_only='yes'};
}
</style>
``` 
generates this output in the template
```
<style> .stuff   {         
        something:    ;
}
</style>
```
Looking at the debug output from JCOGS Image gives this info about what was received from EE by the add-on
```
Calling Tag: {exp:jcogs_img:single width='300' src="{image}" url_only='yes'}
```
i.e. the text of the variable has been passed to the function, not the value.

If we remove the outer curly brackets and then this code
```
<style> .stuff          
        something:    {exp:jcogs_img:single
            width='300'
            src="{image}"
            url_only='yes'};

</style>
```
generates this output in the template
```
<style> .stuff            
        something:    https://ee6-test:8890/images/jcogs_img/cache/strange_times_-_0_-_a6fb8a899668ca73185e1198ec2636a4321999d5_-_28de80_-_a545af7d9769a9ade9f36e77dc71647ae6f4cf65.webp;

</style>
```
and the corresponding JCOGS Image debug info is 
```
Calling Tag: {exp:jcogs_img:single width='300' src="https://ee6-test:8890/media/images/strange_times_-_0_-_a6fb8a899668ca73185e1198ec2636a4321999d5.webp" url_only='yes'} 
```
i.e. simply removing the outer curly brackets has resulted in the variable being evaluated correctly.

**Comment by robinsowell** [comment]
Got another one that is similar.  Interesting note- this worked in 6.0.6:
```
{exp:channel:entries ...}
    <pre>
        .thing {
            {exp:custom_plugin:img src="{events_hero_graphic_image}"}
                {url}
            {/exp:custom_plugin:img}
        }
    </pre>
{/exp:channel:entries}
```
So basically, passing the custom plugin an assets field with a url in it.  But in 6.2, the assets variable is unparsed when the plugin gets the parameter, so it fails.

If you remove the brackets from the enclosing css, it works again.

So something changed since 6.0.6

**Comment by intoeetive** [comment]
The regression was introduced with this commit: https://github.com/ExpressionEngine/ExpressionEngine/pull/1190/commits/75487b31859c07cb946b1902d315872e6374a115 and it looks strange for me as of why it would break things, and yet it does!
