### ISSUE TITLE
Saving emoji in entry fields returns unpredictable results.

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1707]
Emoji are fairly important these days, and are legal to use in URLs. It's a frustration to users that they can't be used in content, and a frustration to me, the admin, that I can't import content with emoji in it.

1. Saving an emoji in a title field results in "????" instead of the emoji. Strangely, the "Entry Updated" notification maintains the emoji.
2. Saving an emoji in the URL Title field results in an Exception Caught error:

`SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8_unicode_ci,COERCIBLE) for operation '=':`

3. I have custom fields into which I'm attempting to save emoji, and they just get stripped out. Example:

`https://www.test.com/vegan/sweet-potato-with-miso-glazed-tofu-🌱`

When you save this, the field comes back simply without the emoji. not even the questions marks.

`https://www.test.com/vegan/sweet-potato-with-miso-glazed-tofu-`

<img width="645" alt="image" src="https://user-images.githubusercontent.com/308752/149032238-9b639295-5ebc-4027-9de6-dddb2696f1a3.png">

**Comment by bsrweb** [comment]
The latest version supports Emojis in the title field. I think you just need to set the correct character set for your database. https://docs.expressionengine.com/latest/troubleshooting/installation.html#emoji-support

**Comment by intoeetive** [comment]
Because the emojis are multibyte characters, you need to make sure your database supports those.

Please see the troubleshooting docs: https://docs.expressionengine.com/latest/troubleshooting/installation.html#emoji-support

**Comment by murtaugh** [comment]
Got it, thanks. I searched the docs but didn't see that.
