### ISSUE TITLE
Unable to upload some SVG files to "Images only" directory

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#1709]
If in an Upload Directory settings I set `Allowed file types` to `Images only`, I won't be able to upload SVG file to this directory. 

Since SVG is an image file, I believe it should be allowed.

**Comment by robsonsobral** [comment]
@shbchk , which version of eecms are you using?

**Comment by shbchk** [comment]
6.1.6

**Comment by robsonsobral** [comment]
This [merge](https://github.com/ExpressionEngine/ExpressionEngine/pull/979) should have fixed it.

**Comment by shbchk** [comment]
Well...
![error](https://user-images.githubusercontent.com/12234507/149198769-ef071a36-f08d-4b16-96fd-d48854794d61.png)

**Comment by intoeetive** [comment]
@shbchk can you send us the file you're trying to upload? Maybe it contains something that we did not consider and thus is not validating properly

**Comment by shbchk** [comment]
Sure, for example: [Annecy Festival logo](https://www.annecy.org/resources/interface/header/logo__dark.svg)

**Comment by chenchen2003** [comment]
I have the same issue with version 6.2.6.

**Comment by shbchk** [comment]
@chenchen2003 I believe you'll be asked for a file you are trying to upload

**Comment by paulcripps** [comment]
We are on EE 6.4.7 and .svg assets are not showing, the directory is synced and it see the 14 files, but then says directory empty.
