### ISSUE TITLE
Still getting upgrade notice after upgrading

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1716]
Immediately after the upgrade process finished, I was presented with the about panel, which still has the big red notification to upgrade.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/308752/149386325-1e186a74-ff64-4a0b-af90-e81ca2fc1a11.png">

**Comment by murtaugh** [comment]
Good job on the update though, everything looks great so far!

**Comment by TomJaeger** [comment]
Hrmm... We can't replicate this one... Any chance you can check the version number in your config file?

And Thanks!

**Comment by robinsowell** [comment]
Weird!  What version does it have in config.php?  And in system/legacy/libraries/core.php around line 72, what's the app_ver:

define('APP_VER', '6.2.0');

**Comment by murtaugh** [comment]
config.php: `$config['app_version'] = '6.2.0';`

system/legacy/libraries/Core.php: `define('APP_VER', '6.2.0');`

**Comment by TomJaeger** [comment]
If you delete your current_versions file in /system/user/cache does it then report as intended?

**Comment by murtaugh** [comment]
Current contents of that file:

`a:3:{s:4:"time";i:1642097817;s:3:"ttl";i:86400;s:4:"data";a:4:{s:14:"latest_version";s:5:"6.2.0";s:12:"license_type";s:3:"pro";s:10:"build_date";s:8:"20220113";s:8:"severity";s:4:"high";}}`

I deleted it, and nothing changed.

**Comment by murtaugh** [comment]
This is probably expected, but the `current_version` file didn't reappear until after I clicked "Upgrade Now" again, which just refreshes the page.

**Comment by robinsowell** [comment]
cache? does it show the same in a different browser?  Except we just released 6.2.1, sooooo you may really need to upgrade now.

**Comment by murtaugh** [comment]
Yep, something was cached. I had done some hard refreshes, but once I manually emptied my caches it went away. That sort of thing doesn't often happen, where a hard refresh doesn't do the trick, I wonder what it was.

**Comment by robinsowell** [comment]
Hrm- agreed, I'd expected the hard refresh to do it.  But I don't think we ever replicated, so for now I'm chalking it up to 'weird'.  If it happens again, we can reassess.

**Comment by murtaugh** [comment]
FWIW, it also just happened on another site I just upgraded. Hard refresh didn't work, clearing caches did. (Latest desktop Safari.)
