### ISSUE TITLE
Relationships display, min, max issues in CP

### ISSUE THREAD

**Issue by aasun** [ExpressionEngine/ExpressionEngine#1717]
Quoted From Slack: Found a bug on min/max and display relationships.  (love these additions, btw).   when the maximum entries to show is set to 10, minimum is set to 0 and maximum selection is left blank.. when 11 relationships are set in an entry, the “Relate Entry” button is gone.. Based on how I think this should work.. the maximum entries to show should be how many are shown in the relationship dropdown.   and maximum entries should be what limits how many can be related.

**Comment by ops-andy** [comment]
https://user-images.githubusercontent.com/55093827/149392046-0eb7fde2-03f1-4c1a-95ec-18970d6d7488.mp4

**Comment by aasun** [comment]
Re:  the video..  The button being gone is accurate. The auto-decrement inside the dropdown as new relationships are repeatedly selected is not necessarily problematic. I understand the challenges of constantly building/refreshing after each selection.  It's fine to have the dropdown be refreshed to the display limit on each open.  If you save that entry you made in the video and reload, there still is no “relate entry” button.  So, that's not just a drawing error.  

Also a Text update suggestion.. The Maximum entries (to show) label should probably be something “Maximum entries displayed in dropdown”.  Then, “Minimum selection” should be “Minimum relationships” and “Maximum section” should be “Maximum relationships”.  (or something like that to clarify a bit more)

**Comment by ops-andy** [comment]
@aasun The video was just there to help verify what you reported. We agree it's an issue to fix.
