### ISSUE TITLE
"Add new column" in grid field is not working

### ISSUE THREAD

**Issue by euchenhofer** [ExpressionEngine/ExpressionEngine#172]
**Description of the problem**
If you create a new Grid field you are not able to create new columns.

**How To Reproduce**
Create a new Grid field and then try to add a new column.

**Error Messages**
JS Console: "Uncaught TypeError: Cannot read property 'replace' of undefined"

</code></pre>

**Screenshots / Videos / Template Code**
Error Message if you click on the "Add new column icon" (+):
![image](https://user-images.githubusercontent.com/696665/55732884-0d960e00-5a1d-11e9-99cc-0e80ae5ecc1c.png)

**Environment Details:**
 - Version: 5.2.2
 - PHP Version 7.1
 - MySQL Version 5.5.58
 - OS: Linux
 - Web Server: Apache
 - Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by derekjones** [comment]
I am unable to reproduce on a clean installation. Both the Add New and the `+` button add new columns to a new Grid field without error. I tried in both Safari and Chrome. Do you have any add-ons or extensions installed? Any other JS or request-related errors or browser plugins that are blocking your JavaScript?

**Comment by euchenhofer** [comment]
Re-Installed EE and it's working fine. Sorry for the false alarm.
