### ISSUE TITLE
Security settings demand dictionary file after upgrade to v6.2.1

### ISSUE THREAD

**Issue by Zignature** [ExpressionEngine/ExpressionEngine#1728]
I just upgraded to v6.2.1 (from v6.1.5) and I wanted to change security settings (`/admin.php?/cp/settings/security-privacy`), but the page will not safe unless I provide the name of a dictionary file.

I have never used a dictionary file and the `Allow dictionary words in passwords?` has never been toggled `on`.

![image](https://user-images.githubusercontent.com/4068757/149638322-c4a1a28a-e835-4112-a953-379fa13db84e.png)

This install of EE was earlier upgraded all the way from a fresh install of v2.11.9.

**Comment by intoeetive** [comment]
@Zignature if `Allow dictionary words in passwords?` is toggled OFF, that means that dictionary words are NOT allowed. Which means there needs to be a dictionary file.

This is somewhat confusing wording, but we're keeping it for historical reasons.

So, if you don't want to use any dictionary restrictions (and so ALLOW all words), the toggle should be turned ON

**Comment by Zignature** [comment]
I didn't make myself clear I think. I didn't change the dictionary settings. They were off and remained off. I tried to change the `CP session type` and `Website Session type` settings...

**Comment by Zignature** [comment]
When I toggled `Allow dictionary words in passwords?` to ON, it works fine. 
Very confusing...

**Comment by intoeetive** [comment]
That just means that in older EE version, this setting was wrong ("allow dictionary words" was set to "n" while the dictionary file was not provided).
In EE6.2, we have added validation around these settings, so you need to have those fixed in order to save (which is what you did)
