### ISSUE TITLE
Simple search channel parameter is not working 

### ISSUE THREAD

**Issue by DesignWorkshop** [ExpressionEngine/ExpressionEngine#1737]
EE 6.2.2
PHP: 7.4.16

I'm trying to exclude entries from a certain channel appearing in the search results.

I’ve added the channel not parameter to the simple search but results from the channel are been returned on the results page.

```
{exp:search:simple_form channel="not asset" status="Protected|open" search_in="entries" result_page="bca/search-results"}
         <div class="mb-3">
         <label for="keywords" class="form-label">Search</label>
         <input type="text" class="form-control mb-2" name="keywords" id="keywords" placeholder="Search term">
         <input type="submit" value="Search" class="btn btn-bca-blue">
        </div>
  {/exp:search:simple_form}
```

I've also tried getting results from a certain channel `channel="news_blog"` and this also returns results from outside of the set channel.

**Comment by robsonsobral** [comment]
Hi, @DesignWorkshop . It's my fault. I'm sorry.

Does it only happens on Simple Search Form?

**Comment by DesignWorkshop** [comment]
> 

It also happens on the advanced search form

**Comment by robsonsobral** [comment]
I'm working on a fix right now! I'm really sorry!

**Comment by robsonsobral** [comment]
@DesignWorkshop , can you, please, try [this](https://github.com/ExpressionEngine/ExpressionEngine/pull/1742/files)?

**Comment by DesignWorkshop** [comment]
> @DesignWorkshop , can you, please, try [this](https://github.com/ExpressionEngine/ExpressionEngine/pull/1742/files)?

Thanks @robsonsobral I'll have a look as soon as I can. Will this be included in the next update of EE?

**Comment by robsonsobral** [comment]
It's already in the process of review and possible approval, @DesignWorkshop .

Thank you for your patience.
