### ISSUE TITLE
developer log complains set_cookie-function

### ISSUE THREAD

**Issue by bnetz** [ExpressionEngine/ExpressionEngine#1738]
Developer log complains:
```
Deprecated function set_cookie() called in /var/www/vhosts/domain.tld/systemfolder/ee/ExpressionEngine/Addons/comment/mod.comment.php on line 1738.

Deprecated since 2.8. Use EE_Input::delete_cookie() instead.
```

and

```
Deprecated function set_cookie() called in /var/www/vhosts/domain.tld/systemfolder/ee/ExpressionEngine/Addons/comment/mod.comment.php on line 1728.

Deprecated since 2.8. Use EE_Input::delete_cookie() instead.
```
Running PHP 7.4.27 / MariaDB 5.5.68 / FPM as nginx
ExpressionEngine 6.2.1

**Comment by intoeetive** [comment]
@bnetz I have feeling that these records are from older EE version, because as of EE 6.2.1 the lines referenced do not contain `set_cookie` code (it's on different lines)

Can you clear your developer log and see if you get the message again? (maybe with updated line numbers)

**Comment by bnetz** [comment]
I compared the two files ([mod.comment.php](https://raw.githubusercontent.com/ExpressionEngine/ExpressionEngine/5b36e9d84ba183ef863747dbb7df16b56644a83e/system/ee/ExpressionEngine/Addons/comment/mod.comment.php) - the 6.2.1-version on Github) and the one from my server. They are identical. I attach the file from my server. [mod.comment.php.txt](https://github.com/ExpressionEngine/ExpressionEngine/files/7905989/mod.comment.php.txt)

I emptied the developer log, but I don't know how I could force the system to check for errors/update the log.

**Comment by intoeetive** [comment]
It will be updated once the issues appears again when someone uses comment form. So just keep an eye on it and update the issue if you get this reported again

**Comment by bnetz** [comment]
It came in again:

```
Date logged: 22/1/2022 17:02
Deprecated function set_cookie() called in
/var/www/vhosts/…/ee/ExpressionEngine/Addons/comment/mod.comment.php
on line 1739.

Deprecated since 2.8. Use EE_Input::delete_cookie() instead.

Date logged: 22/1/2022 17:02
Deprecated function set_cookie() called in
/var/www/vhosts/…/ee/ExpressionEngine/Addons/comment/mod.comment.php
on line 1729.

Deprecated since 2.8. Use EE_Input::delete_cookie() instead.
```
