### ISSUE TITLE
Moving system directory to a subfolder with a dot in the name breaks admin.php

### ISSUE THREAD

**Issue by jakecovert** [ExpressionEngine/ExpressionEngine#1741]
Trying to move the system folder to a subdirectory per this [best practice](https://docs.expressionengine.com/latest/installation/best-practices.html#moving-the-system-directory-above-webroot).

Version 6.2.2

Example that doesn't work: 

`$system_path = '../example.com_system';`

Great product! 

Thanks.

**Comment by intoeetive** [comment]
@jakecovert what error did you get?

**Comment by jakecovert** [comment]
Apologies; should have added that from the get-go:
```
Your system folder path does not appear to be set correctly. Please open the following file and correct this: admin.php
```

Details: Ubuntu 20.04 LTS / Apache2

**Comment by intoeetive** [comment]
Could you double check that it's set correctly indeed? I've just tested with the same name and location that you posted, and works fine for me

**Comment by intoeetive** [comment]
Closing as we did not receive any follow-up on this issue
