### ISSUE TITLE
Can't move entries between channels with identical settings

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1749]
The docs[^1]. say that you can move entries between channels with the same Fields, Field Groups, Category Groups, and Statuses. 

I want to move the entries from one channel to another, so have made all these things identical, but the Channel field still only has one radio button.

EE 6.2.3

[^1]: https://docs.expressionengine.com/latest/control-panel/create.html#options-tab

**Comment by intoeetive** [comment]
Just checked, and it works as expected for me. There is probably still a difference somewhere (Fields are probably the longest list, so easiest to miss something)

**Comment by murtaugh** [comment]
I've checked three or four times. Tom Jaeger is kindly helping me out via Slack.

**Comment by murtaugh** [comment]
We've tried making sure all channel settings are the same, not just those mentioned in the docs.

**Comment by TomJaeger** [comment]
For people following along.  We worked on this in slack, with same DB, and we are unable to replicate.  As such closing this issue.  If anyone else runs into this please let us know.
