### ISSUE TITLE
PHP in static templates does not work

### ISSUE THREAD

**Issue by Yvan256** [ExpressionEngine/ExpressionEngine#175]
**Description of the problem**
1. The documentation only says that a "Static" template is not parsed by the ExpressionEngine parsing engine but makes no mention of PHP parsing.

2. Static templates still have the "Enable PHP" toggle.

3. The problem: PHP in a "Static" template is not parsed, wether or not the "Parse PHP" option is checked, both on "input" and "output". 

**How To Reproduce**
1. Create a template and set its "Type" to "Static".
2. Put PHP in the template such as <code>&lt;?php echo 'Lorem ipsum'; ?&gt;</code>
3. The template is sent as-is, the PHP code is not run.

**Environment Details:**
 - Version: [e.g. 5.2.2]
 - PHP Version [e.g. 7.0.33]

 
**Additional context**
It would be useful in some cases to be able to use PHP in templates while bypassing ExpressionEngine's own parsing engine/templating language. Using a static template in such a manner would be similar to having a "Disable the ExpressionEngine parsing engine" toggle.

It would, however, be useful to have access to the ee objects, to be able to use the database functions, access the logged-in user information such as <code>ee()-&gt;session-&gt;userdata('screen_name')</code>, etc.

Maybe a new type of template, named "PHP with ee()" or similar, would be more appropriate? In which case, selecting the "Static" type should show disabled PHP options.

**Comment by robinsowell** [comment]
It is intentional that php isn't parsed, and I'll update the docs to clarify that.  Adding it would be a feature request, but we really discourage using PHP in templates.  It's cleaner, more portable and runs faster to put it into an add-on, which shouldn't add much overhead. 

I don't think we want to make a change that encourages the use of PHP in the templates.

**Comment by ops-andy** [comment]
closing this as it's an enhancement we will not be implementing due to reasons mentioned by Robin above.
