### ISSUE TITLE
~~`{auto_path}`~~ `{channel_url}` on Channel module

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1751]
**Is your feature request related to a problem? Please describe.**
Many times, I have to loop through multiple channels. To create links to different templates, I need to add conditionals:

```html
{exp:channel:entries related_categories_mode="yes" channel="event|news|service"}
    {if channel_short_name == "event"}
        <a href="{url_title_path='event/index'}" class="related-content__link">
    {if:elseif channel_short_name == "news"}
        <a href="{url_title_path='news/index'}" class="related-content__link">
    {if:elseif channel_short_name == "service"}
        <a href="{url_title_path='service/index'}" class="related-content__link">
    {/if}
          {title}
        </a>
{/exp:channel:entries}
```

**Describe the solution you'd like**
~~As we already need to set the path of a channel for the Search module to work, why not to use the same configuration on the Channel module?~~

We can add `channel_url` to Channel Module. It can't be easier than that!

```html
{exp:channel:entries related_categories_mode="yes" channel="event|news|service"}
-  <a href="{auto_path}" class="related-content__link">
+  <a href="{channel_url}/{url_title}" class="related-content__link">
    {title}
  </a>
{/exp:channel:entries}
```

**Describe alternatives you've considered**
I've using `https:/{relative_url}/{url_title}` to avoid the conditionals.

**Teachability, Documentation, Adoption, Migration Strategy**
~~We rename the **Search results** field on the [Channel settings form](https://docs.expressionengine.com/latest/control-panel/channels.html#settings-tab).~~

We should also make sure it works with variables modifiers, to avoid the [issue of the Search Module](https://github.com/ExpressionEngine/ExpressionEngine/issues/458).

- [x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
Can you add some more details? I am unsure what exactly you suggest to change and where

**Comment by robsonsobral** [comment]
I'm sorry. From time to time, I forgot that what is obvious to me isn't to somebody else. Dumb, dumb...

Description updated, @intoeetive !

**Comment by blue-dreamer** [comment]
Just for reference you can already use `{comment_url_title_auto_path}` where you set the path in channel settings. That gives you a way of generating URL's for any channel.

**Comment by robsonsobral** [comment]
`{channel_url}` is already available, however undocumented.
