### ISSUE TITLE
Conditional Validation Based on Parent Value

### ISSUE THREAD

**Issue by eric-lamb62** [ExpressionEngine/ExpressionEngine#1753]
**Is your feature request related to a problem? Please describe.**
So. I have a task. Build a form with the following fields:

1. Radio group 
2. Input field

With the Validation requirement that the Input field is required only IF a specific option in the radio group is selected AND THEN the value has to be inspected. 

**Describe the solution you'd like**
I've dug into the `Validation\Validator` object and it appears to be related to a very specific conditional at line:
https://github.com/ExpressionEngine/ExpressionEngine/blob/7372d4696ff14e31d3ba0a3542b96f2b60a6af5f/system/ee/ExpressionEngine/Service/Validation/Validator.php#L208

Now, to be fair, I'm not at all sure what the change is that's needed there; I only know everything worked right insofar as teh execution of my validation Rule and it's return, but it didn't get passed that point. I saw that and realized this was over my pay grade (and let's be real, I could be way overthinking this) so figured throwing it here and hopefully getting some guidance. 

I'm down to fix it or change it or whatever; just not entirely sure there's anything "there" there. 

**Describe alternatives you've considered**
Drinking

**Teachability, Documentation, Adoption, Migration Strategy**
I mean, sure, if needed I can add a couple paragraphs to the docs here:
https://docs.expressionengine.com/latest/development/services/validation.html#conditional-rules

I can't promise there won't be profanity though. 

- [x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
It looks like you are looking to build your own custom conditional rule, which is described in the docs here: https://docs.expressionengine.com/latest/development/services/validation.html#custom-conditional-rules

So you'll basically need custom validation rule that will skip the validation if radio does not have some value and then chain it with the rest of your validation logic using `|` separator.

You may as well just write your own custom validator for everything. 

I am not sure what's missing there for you and what change you'd like to make and why (but maybe that just means I need more coffee this morning)

**Comment by eric-lamb62** [comment]
Oh hell yes. Thanks @intoeetive I had a feeling I was missing something.
