### ISSUE TITLE
Grid Mouseover issue

### ISSUE THREAD

**Issue by hcanning** [ExpressionEngine/ExpressionEngine#176]
Video of issue
[mouseover-issue-grid.zip](https://github.com/ExpressionEngine/ExpressionEngine/files/3077640/mouseover-issue-grid.zip)

**Description of the problem**
When u mouse over an image title in a Grid fieldtype in a Channel the row flickers due to the mouseover

**How To Reproduce**
Create Grid with image and mouse over the title as per video

**Error Messages**
see vid. Mouseover

**Screenshots / Videos / Template Code**
see vid

**Environment Details:**
 - Version: [e.g. 5.2.2.]
 - PHP Version 7.0.33-0+deb9u3
 - mysqlnd 5.0.12-dev 
 - Deb 9
 - Web Server:Apache2

**Possible Solution**

**Additional context**

**Comment by jmathias** [comment]
Hi, sorry for the trouble.

This is a known issue that requires a change to the way the Grid input is built. I've got it on my list to repair.
