### ISSUE TITLE
New hook: cache_clearing_end

### ISSUE THREAD

**Issue by gilbert-hop** [ExpressionEngine/ExpressionEngine#1762]
**Is your feature request related to a problem? Please describe.**
We'd like to create some extensions that can fire after the user click clear cache in the CP.

**Describe the solution you'd like**
When the user chooses to flush cache in the Cache Manager, an extension hook is triggered.

**Describe alternatives you've considered**
-

**Teachability, Documentation, Adoption, Migration Strategy**
cache_clearing_end ($witch = 'all')
Fires when the cache clearing sequence has ended.

- [x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
Wouldn't it be better to implement the hook in `functions` library, or the `cache` library itself? Otherwise, I think the more hooks, the better

**Comment by gilbert-hop** [comment]
In my test, I added to the `legacy/libraries/Functions.php`
```
    /**
     * Delete cache files
     *
     * @access	public
     * @param	string
     * @return	string
     */
    public function clear_caching($which, $sub_dir = '')
    {
        $options = array('page', 'db', 'tag', 'sql');

        if (in_array($which, $options)) {
            ee()->cache->delete('/' . $which . '_cache/');
        } elseif ($which == 'all') {
            foreach ($options as $option) {
                ee()->cache->delete('/' . $option . '_cache/');
            }
        }
        if ($which == 'jumpmenu') {
            ee('CP/JumpMenu')->clearAllCaches();
        }
        if (ee()->extensions->active_hook('cache_clearing_end') === TRUE) {
            $result = ee()->extensions->call('cache_clearing_end', $which);
        }
    }
```
I think this is the desired location?

**Comment by intoeetive** [comment]
It probably is. Just be aware that in some places `ee()->cache->delete` is called directly as well to clear some very specific caches

**Comment by gilbert-hop** [comment]
But the `cache_clearning()` method is not called every time `ee()->cache->delete()` is called right? Basically, I want to fire a hook when the user click **Clear Caches** on `?/cp/utilities/cache`. Or are you saying that we should add the extension to the cache library directly so that all `ee()->cache->delete()` calls will trigger the extension hook?

**Comment by intoeetive** [comment]
`legacy/libraries/Functions.php` might be the good place then
