### ISSUE TITLE
PHP Warning shown when cache is invalidated

### ISSUE THREAD

**Issue by blairliikala** [ExpressionEngine/ExpressionEngine#1764]
When using the cache class in an add-on I am getting the error below intermittently.  I've been finding it might be happening when the cache invalidates after the TTL expires.  The unserialize process is returning `false` and then breaks the next conditional.  I have not been able to narrow down why the unserialize function is intermittently returning false.

One solution might be to simply check if $data is not `false`.  The same check might be needed with the other caching drivers.  I have had this added in my development environment for some time and has helped suppress the issue.

EE v6.1 through 6.2.4, nginx/apache, two different web hosts.

```
Warning
Trying to access array offset on value of type bool
ee/legacy/libraries/Cache/drivers/Cache_file.php, line 53
Severity: E_WARNING
```

Line 53:

```
 // unserialize is failing here:
        $data = unserialize(file_get_contents($this->_cache_path . $key));

// Suggesting to Add
        if (!$data)
        {
            return false;
        }
//*****//

        if ($data['ttl'] > 0 && ee()->localize->now > $data['time'] + $data['ttl']) {
            unlink($this->_cache_path . $key);

            return false;
        }
```

**Comment by intoeetive** [comment]
I've seen that issue myself and I think the proposed solution might just solve it. Thank you!
