### ISSUE TITLE
Fluid field str_replace deprecation issue

### ISSUE THREAD

**Issue by rileymacisaac** [ExpressionEngine/ExpressionEngine#1776]
This is a pretty tiny bug, but I am getting a deprecation issue when using the fluid field type. 

The same error is logged for each meta tag:
```
Deprecated
str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated

ee/ExpressionEngine/Addons/fluid_field/Service/Tag.php, line 237

    Severity: E_DEPRECATED
```

Line 237 in `tag.php` seems to be using str_replace and receiving a null value for the second parameter in some cases. For example, if I `print_r($meta)` on line 101 you can see that some values are null, such as ` [layouts:prev_field_name] => `

I can fix the issue temporarily by checking if the `$value` is empty, and if it is just set it to an empty string. Probably not the correct way to fix it, but it saves me from seeing all the issues for now.

Example:
```
foreach ($meta as $name => $value) {
            $value = !empty($value) ? $value : '';
            $tag = LD . $name . RD;
            $tagdata = str_replace($tag, $value, $tagdata);
        }
```

**Comment by intoeetive** [comment]
@rileymacisaac thank you for the report!

Checked and found this issue to be present in few other places as well because of `null` being used as default value for tagdata (which should be string). The fix is on the way!
