### ISSUE TITLE
Member Pending Activation manage options not available for other member groups

### ISSUE THREAD

**Issue by joshconner** [ExpressionEngine/ExpressionEngine#178]
**Description of the problem**
When new member is created from the front-end and set to and Account Activation Type is set to "Manually moderated by administrator" a user that has CP access and appropriate permissions can not manage pending member from Members => Pending Activation in the CP.

**How To Reproduce**
1. Create new member group with enough permissions to manage members within CP. Let's call that group "CP Admin"
2. Have at least 1 member in said member group
3. Logout of CP
4. Create new member from front-end
5. Login to CP with member that's in the "CP Admin" group
6. Navigate to Members => Pending Activation

**Error Messages**
No error message but the member manage options are available if you go to Members => All Members.

**Screenshots / Videos / Template Code**
![image](https://user-images.githubusercontent.com/479358/56168096-261ba080-5fa8-11e9-808c-6ab164205022.png)
![image](https://user-images.githubusercontent.com/479358/56167878-6b8b9e00-5fa7-11e9-9124-c52ad4ba7b93.png)

**Environment Details:**
 - Version: 5.2.2
 - PHP Version: 7.2.14
 - MySQL Version: 5.7.25
 - OS: macOS
 - Web Server: Apache, MAMP

**Comment by jasonboothman** [comment]
I am running into the same issue on EE 4.3.8.

**Comment by brettburwell** [comment]
+1 Seeing the same thing on EE 5.2.2

**Comment by jasonboothman** [comment]
Any traction on this bug report?
