### ISSUE TITLE
Curly brace-reliant HTML buttons breaking channel form jQuery assets

### ISSUE THREAD

**Issue by mcfarlandonline** [ExpressionEngine/ExpressionEngine#1788]
PHP 7.3
EE 6.2.4

I have a channel form that uses a couple RTE fields (CKeditor), so I'm including jQuery assets, (but not CSS). 

None of my other form fields are textarea fields, but I'm seeing a call for the HTML buttons we set up in the EE control panel. One of our standard buttons (to help clients remember how to make sure their email addresses get encrypted), is "email" and we set up something like this...
> <img width="651" alt="Screen Shot 2022-02-04 at 2 11 31 PM" src="https://user-images.githubusercontent.com/20441129/152610674-a92ebe57-6061-4568-82a2-3263de1aff71.png">
However, that type of HTML button will break the channel form's jQuery, as it gets read as an interrupting <script>. I finally tracked it down at the end of this line...
> <img width="1108" alt="Screen Shot 2022-02-04 at 2 13 32 PM" src="https://user-images.githubusercontent.com/20441129/152610814-59231ea1-1156-450d-ba24-99298eeca6f6.png">
I'm not sure why the HTML buttons are getting called in the first place, but is there a workaround for this? It's not always possible for us to just have "Render URLs and Email addresses as links?" turned on for each channel, so I'd still like to offer my clients a way to encrypt their emails, or create "Contact Foo" links that are encrypted mailto's.

**Comment by intoeetive** [comment]
Due to how the template parser works, we can't avoid parsing `{encode}` tag on frontend (inc. channel forms) - but we certainly should not include the buttons by default. That is already done by textarea field itself, when it's in use
