### ISSUE TITLE
Channel limit reached - CSS flow bug

### ISSUE THREAD

**Issue by liamcrean** [ExpressionEngine/ExpressionEngine#1798]
Channel limit reached warning message - placement layout bug - negatively interrupts layout by pushing "Entries" section title right.

<img width="1549" alt="Screenshot 2022-02-08 at 13 05 31" src="https://user-images.githubusercontent.com/2526645/152993094-56db0138-8a6c-4d0a-82d0-69631406f944.png">

**Comment by TomJaeger** [comment]
Hi!

Thanks for posting this!  I believe this will be fixed in the following PR (slated for 6.2.5).

https://github.com/ExpressionEngine/ExpressionEngine/pull/1796
