### ISSUE TITLE
Password Validation Algorithm "Very Strong" ranking setting the bar too low

### ISSUE THREAD

**Issue by mcfarlandonline** [ExpressionEngine/ExpressionEngine#1806]
PHP 7.3
EE 6.2.4

I recently tested out using [the password validation script from the docs](https://docs.expressionengine.com/latest/member/password-validation.html) alongside a front-end member registration form. It seems pretty easy to get going, but upon testing, it's clearly not very strict. 

For this site, I have the Password Security Policy set to "Strong"...
> <img width="500" alt="Screen Shot 2022-02-09 at 2 38 54 PM" src="https://user-images.githubusercontent.com/20441129/153302500-4176d8dc-7896-44d0-bb12-a113686d968d.png">

My passwords **are** getting validated as it relates to the minimum number of characters, but sequences and consecutive numbers aren't negatively impacting things as much as I expected. It appears that only one capitalized letter or special character is required to earn a "Very Strong" ranking. To further test things, I tried changing my Super Admin password in my profile. This seems a little overly forgiving...

> <img width="1205" alt="Screen Shot 2022-02-09 at 2 25 15 PM" src="https://user-images.githubusercontent.com/20441129/153303929-314239fb-5e5a-470b-b377-929ec1dc79fe.png">
> <img width="1181" alt="Screen Shot 2022-02-09 at 2 25 44 PM" src="https://user-images.githubusercontent.com/20441129/153303932-7b68304c-6424-4d7f-b6ef-e35b58c2d04d.png">
> <img width="1195" alt="Screen Shot 2022-02-09 at 2 25 58 PM" src="https://user-images.githubusercontent.com/20441129/153303934-11a5ce1f-19f4-42ac-96cd-79cd5176adab.png">
Here's where we draw the line...
> <img width="1196" alt="Screen Shot 2022-02-09 at 2 26 24 PM" src="https://user-images.githubusercontent.com/20441129/153303937-c22f8e5a-7d9b-4659-ba07-95d0d8b98b36.png">

I wonder if we should just do away with a "Very Strong" ranking at this point, if the algorithm could be tightened up, or if there's a way to exclude certain words and strings (similar to the Word Censoring feature), while still allowing most dictionary words.

**Comment by intoeetive** [comment]
@mcfarlandonline you're aware about [Allow dictionary words in passwords?](https://docs.expressionengine.com/latest/control-panel/settings/security-privacy.html#allow-dictionary-words-in-passwords) setting, right?

**Comment by mcfarlandonline** [comment]
Hi @intoeetive,
We tried installing that, too, but don't see that it's making any difference. I've tried a bunch of combinations with:
- Allowing and disallowing dictionary words
- removing "password" from the dictionary.txt file
- Using capitals and lowercase versions

It doesn't appear that this setting is having any effect on our end. We also checked the wizard just in case a module on our server might be missing, but that looks good, too...
![unnamed](https://user-images.githubusercontent.com/20441129/162287462-6b24a1dd-b2c6-4d06-a1ab-65e249bb5da5.jpg)

**Comment by intoeetive** [comment]
I think I know why you are experiencing this. Using the dictionary file is only performing "full match" check.
It does probably make sense to check for partial match.
We'll discuss this internally and maybe we might have some better solution indeed,
Thank you for reporting!
