### ISSUE TITLE
Date name typo in core_lang.pgp

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#181]
File /system/ee/legacy/language/english/core_lang.php line 327

‘May_l’ => ‘May’,

should be

‘May’ => ‘May’,

Seen in EE5.2.1

**Comment by scbarber** [comment]
It turns out this is not a typo. We use the key "May_l" to mean "the long, not abbreviated name for the 5th month of the year." The key "May" is the "short" 3 letter abbreviation, and already present on line 303.
