### ISSUE TITLE
Error when updating 6.2.5

### ISSUE THREAD

**Issue by benya** [ExpressionEngine/ExpressionEngine#1810]
When upgrading to 6.2.5, I get an error at the end.

https://prnt.sc/26t9uxb

**Comment by TomJaeger** [comment]
Hi Benya,

Thanks for posting this.  What version of PHP is this in?

**Comment by benya** [comment]
@TomJaeger Hi

php 7.4.3

**Comment by benya** [comment]
To clarify, I did an update on two sites.

On one everything went well, and on the second I got an error.

**Comment by intoeetive** [comment]
which version did you update from?

**Comment by benya** [comment]
from 6.2.4

**Comment by benya** [comment]
Also after the update I can't get into the "Templates" section.
Error.
https://prnt.sc/26wqsl8

**Comment by intoeetive** [comment]
Looks like your `exp_templates` DB table (or the fields in it) are not using multibyte encoding (utf8mb64) but your template file contains emojis which are multibyte entities.

You can update directly in database, or use this add-on for the fix: https://github.com/ExpressionEngine/Emoji-Support

**Comment by benya** [comment]
wow. Thank you.
That helped.
Updated to 6.2.5 without errors.
Thank you
