### ISSUE TITLE
Discussion Forum 5.0.2 - topics and boards order output order error

### ISSUE THREAD

**Issue by 0xVitalyFedorov** [ExpressionEngine/ExpressionEngine#1813]
1) Topics and categories order in output do not match the order in CP.

2) Error when editing category name:

Warning
in_array() expects parameter 2 to be array, string given
ee/ExpressionEngine/Addons/forum/mcp.forum.php, line 572

Severity: E_WARNING
Warning
in_array() expects parameter 2 to be array, string given
ee/ExpressionEngine/Addons/forum/mcp.forum.php, line 573

Severity: E_WARNING
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/legacy/core/Input.php, line 266

Severity: E_WARNING
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/legacy/libraries/Functions.php, line 458

Severity: E_WARNING

**Comment by TomJaeger** [comment]
Thanks for posting this.  

Any chance you can pass along the version of EE and PHP your running as well?

Thanks!

**Comment by 0xVitalyFedorov** [comment]
Currently PHP 7.4

Switched to 8.0 - got the following error when editing

TypeError Caught

in_array(): Argument #2 ($haystack) must be of type array, string given

ee/ExpressionEngine/Addons/forum/mcp.forum.php:572

Stack Trace: Please include when reporting this error

#0 ee/ExpressionEngine/Addons/forum/mcp.forum.php(572): in_array('forum_notify_mo...', '')
#1 ee/ExpressionEngine/Addons/forum/mcp.forum.php(2030): Forum_mcp->validateBoard(Object(ExpressionEngine\Addons\Forum\Model\Forum))
#2 ee/ExpressionEngine/Addons/forum/mcp.forum.php(334): Forum_mcp->editForum('14')
#3 [internal function]: Forum_mcp->edit('forum', '14')
#4 ee/ExpressionEngine/Controller/Addons/Addons.php(1489): call_user_func_array(Array, Array)
#5 ee/ExpressionEngine/Controller/Addons/Addons.php(797): ExpressionEngine\Controller\Addons\Addons->getModuleSettings('forum', 'edit', Array)
#6 [internal function]: ExpressionEngine\Controller\Addons\Addons->settings('forum', 'edit', 'forum', '14')
#7 ee/ExpressionEngine/Core/Core.php(257): call_user_func_array(Array, Array)
#8 ee/ExpressionEngine/Core/Core.php(113): ExpressionEngine\Core\Core->runController(Array)
#9 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#10 index.php(143): require_once('...')
#10 index.php(143): require_once('...')

**Comment by 0xVitalyFedorov** [comment]
EE 6.2.5

<img width="1863" alt="Screenshot 2022-02-12 at 10 45 04" src="https://user-images.githubusercontent.com/99512477/153702319-3735620b-8567-470f-a039-00f5469e3ad6.png">
<img width="712" alt="Screenshot 2022-02-12 at 10 47 07" src="https://user-images.githubusercontent.com/99512477/153702357-f17bfe83-77a7-4f38-90fc-321eb1cff2be.png">

**Comment by intoeetive** [comment]
The error will be resolved with https://github.com/ExpressionEngine/ExpressionEngine/pull/1812/commits/4a094dd074d704a137250f8cfd2f9ee61d366a72
