### ISSUE TITLE
Include short name of field on keywords search

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1815]
**Is your feature request related to a problem? Please describe.**
I don't even think of the name of the field. I only care about the short name. So, the more the number of fields, the harder it gets to find them.

**Describe the solution you'd like**
It would be good if the keyword search considered the short name.

**Describe alternatives you've considered**
To name the fields using the same language, but it makes the code messy.

- [ ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by murtaugh** [comment]
+1 to this. I always namespace my fields, so to be able to search for "people_" would help a lot.

**Comment by intoeetive** [comment]
Assuming this refers to search on "Field" page in CP, searching by field short name works as of EE 7.2
