### ISSUE TITLE
EE 6.2.5 Icons in control panel for all menu items, html buttons, etc. are just squares

### ISSUE THREAD

**Issue by dipsacus** [ExpressionEngine/ExpressionEngine#1832]
1.  All the icons in my control panel are just displaying as squares
2. When I am logged in as super admin in the control panel, the front end website is not recognising that I am logged in, and so I cannot do comments etc. Also i would like to have the website displayed as offline to anyone who is not logged in, but this is not possible at present.

**Comment by intoeetive** [comment]
@dipsacus we try to only use GitHub issues for bug reports and feature request.

For support issues, please use [Forums](https://expressionengine.com/forums) or [StackExchange](https://expressionengine.stackexchange.com/)

In general, it looks like your theme folder path is wrong, and the CP session type does not match website session type.
