### ISSUE TITLE
Control panel navigation issue on iPhone 

### ISSUE THREAD

**Issue by VarenSwaab** [ExpressionEngine/ExpressionEngine#1840]
On an iPhone, there is an issue where the left navigation pane of the CP retracts when a user is trying to scroll to the bottom of a page. This makes it impossible to select any links in the navigation panel that aren't visible in the viewport.

In other words, on an iPhone, if you try to scroll to the bottom of the navigation panel to select a link such as Settings, the act of scrolling makes the navigation panel go away thereby making it impossible to navigate to any of the lower links in the panel that aren't visible in the viewport on page load.

**Comment by TomJaeger** [comment]
Related / maybe the same issue https://github.com/ExpressionEngine/ExpressionEngine/issues/846
