### ISSUE TITLE
Role counts are incorrect and don't update

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#1844]
On the Member Roles page, all roles are listed with their count in ()- but the counts are incorrect and when I go to the Profile page and update their roles, I can't get them to change.  It looks like total_members is 'off' in exp_roles.  

I'm not sure if those should be primary role counts or just counts (I'd assume counts) but they're off either way.  A few have some assigned, but I can't get the number to change and I'm not sure why some do and some don't- probably a matter of whether they were assigned a role when I registered them.

6.2.6

**Comment by intoeetive** [comment]
@robinsowell this might happen if `ignore_member_stats` config override is set to `y`.

Did you check if that's not the case?

**Comment by robinsowell** [comment]
You're right that adding $config['ignore_member_stats'] = 'n'; fixed it- yay!  But I think that should be the default, correct?  I can't find anywhere I was setting.  I think it's defaulting to 'y' aka ignore.

Without digging, I don't see where a default is set- so would it come back as false?  And everywhere it's checking, it's using ee()->config->item('ignore_member_stats') != 'y', so it's not going to be 'y'.

I THINK- I didn't dig.
