### ISSUE TITLE
Relationship Field, Edit Entry Interface: show more than title

### ISSUE THREAD

**Issue by creativearc-paul** [ExpressionEngine/ExpressionEngine#1845]
I have a site that features archival audio/music files by title. Many of those titles are the same. When I use a relationship field, in the Edit Entry interface, the relationship search window allows you to keyword search the title or filter by channel.

In my case, I might have 3 dozen "Battle Hymn of the Republic" as titles, and I have no way of knowing which particular entry I am selecting. An entry id, date added, or any similar differentiator would be a big help!

<img width="1006" alt="relate-meta" src="https://user-images.githubusercontent.com/224037/155407206-9488395a-fea2-4e14-a1f8-16db703d8fea.png">

**Comment by shbchk** [comment]
There is a new toggle switch in relationship field settings:

![78a266d8-5757-42ed-90ad-510e6c8a448c](https://user-images.githubusercontent.com/12234507/155551315-caa1e96d-7c07-47b2-a1c4-51934a5e7d70.png)

**Comment by creativearc-paul** [comment]
That's great! I would never have found that. Thanks!
