### ISSUE TITLE
EE 6.2.6 has an error when using the search on the website

### ISSUE THREAD

**Issue by wernergusset** [ExpressionEngine/ExpressionEngine#1846]
Have a website that uses the simple search. It worked on 6.2.2 (or 6.2.4 where I am not 100% sure). Now on 6.2.6 the website shows this error when searching a term:

`Exception Caught
There was a database connection error or a problem with a query. Log in as a super admin or enable debugging for more information.
mysqli_connection.php:114`.

What can I do?

**Comment by intoeetive** [comment]
I suggest that you start with following the instructions given: `Log in as a super admin or enable debugging for more information.`

This will show you detailed error log which you can investigate or send to use if that will look like EE core bug to you.

**Comment by wernergusset** [comment]
Here is the full debugging code
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'no_result_page' in 'field list':
INSERT INTO `exp_search` (`search_id`, `search_date`, `member_id`, `keywords`, `ip_address`, `total_results`, `per_page`, `query`, `custom_fields`, `result_page`, `no_result_page`, `site_id`) VALUES ('6752c9e71c6207accdecfd908f402533', 1645795994, 1, 'Test', '185.168.9.97', 23, 50, 'a:3:{s:7:\"entries\";a:23:{i:0;s:3:\"218\";i:1;s:3:\"485\";i:2;s:4:\"1916\";i:3;s:4:\"2685\";i:4;s:1:\"8\";i:5;s:1:\"9\";i:6;s:2:\"10\";i:7;s:4:\"2688\";i:8;s:4:\"2689\";i:9;s:4:\"2701\";i:10;s:3:\"147\";i:11;s:3:\"215\";i:12;s:3:\"220\";i:13;s:3:\"256\";i:14;s:3:\"361\";i:15;s:4:\"1493\";i:16;s:4:\"1112\";i:17;s:4:\"2504\";i:18;s:4:\"2503\";i:19;s:4:\"2500\";i:20;s:4:\"2501\";i:21;s:4:\"2508\";i:22;s:4:\"2512\";}s:11:\"channel_ids\";a:5:{i:0;s:1:\"2\";i:4;s:1:\"6\";i:10;s:2:\"11\";i:16;s:2:\"12\";i:17;s:2:\"24\";}s:3:\"end\";s:26:\" ORDER BY entry_date desc\";}', 'a:29:{s:8:\\\"kurztext\\\";a:2:{i:0;s:1:\\\"1\\\";i:1;b:0;}s:9:\\\"haupttext\\\";a:2:{i:0;s:1:\\\"2\\\";i:1;b:1;}s:10:\\\"untertitel\\\";a:2:{i:0;s:2:\\\"26\\\";i:1;b:0;}s:13:\\\"zweiter_titel\\\";a:2:{i:0;s:2:\\\"27\\\";i:1;b:0;}s:9:\\\"home_text\\\";a:2:{i:0;s:2:\\\"28\\\";i:1;b:0;}s:4:\\\"text\\\";a:2:{i:0;s:1:\\\"4\\\";i:1;b:1;}s:12:\\\"beschreibung\\\";a:2:{i:0;s:1:\\\"6\\\";i:1;b:1;}s:3:\\\"ort\\\";a:2:{i:0;s:1:\\\"8\\\";i:1;b:1;}s:7:\\\"mbsince\\\";a:2:{i:0;s:1:\\\"9\\\";i:1;b:0;}s:12:\\\"member_email\\\";a:2:{i:0;s:2:\\\"12\\\";i:1;b:0;}s:7:\\\"vorname\\\";a:2:{i:0;s:2:\\\"13\\\";i:1;b:1;}s:8:\\\"nachname\\\";a:2:{i:0;s:2:\\\"14\\\";i:1;b:1;}s:12:\\\"adresszusatz\\\";a:2:{i:0;s:2:\\\"18\\\";i:1;b:1;}s:9:\\\"trainings\\\";a:2:{i:0;s:2:\\\"29\\\";i:1;b:0;}s:9:\\\"website_2\\\";a:2:{i:0;s:2:\\\"31\\\";i:1;b:0;}s:12:\\\"member_photo\\\";a:2:{i:0;s:2:\\\"32\\\";i:1;b:0;}s:16:\\\"website_linkname\\\";a:2:{i:0;s:2:\\\"33\\\";i:1;b:0;}s:18:\\\"cf_member_latitude\\\";a:2:{i:0;s:2:\\\"34\\\";i:1;b:0;}s:19:\\\"cf_member_longitude\\\";a:2:{i:0;s:2:\\\"35\\\";i:1;b:0;}s:19:\\\"trainings_worldwide\\\";a:2:{i:0;s:2:\\\"50\\\";i:1;b:0;}s:23:\\\"members_additional_text\\\";a:2:{i:0;s:2:\\\"51\\\";i:1;b:0;}s:14:\\\"cf_website_url\\\";a:2:{i:0;s:2:\\\"77\\\";i:1;b:0;}s:19:\\\"cf_linkedin_adresse\\\";a:2:{i:0;s:2:\\\"78\\\";i:1;b:0;}s:19:\\\"cf_facebook_adresse\\\";a:2:{i:0;s:2:\\\"79\\\";i:1;b:0;}s:20:\\\"cf_instagram_adresse\\\";a:2:{i:0;s:2:\\\"80\\\";i:1;b:0;}s:18:\\\"cf_twitter_adresse\\\";a:2:{i:0;s:2:\\\"81\\\";i:1;b:0;}s:19:\\\"cf_country_latitude\\\";a:2:{i:0;s:2:\\\"36\\\";i:1;b:0;}s:20:\\\"cf_country_longitude\\\";a:2:{i:0;s:2:\\\"37\\\";i:1;b:0;}s:15:\\\"cf_country_zoom\\\";a:2:{i:0;s:2:\\\"38\\\";i:1;b:0;}}', 'search/results', 'search/noresults', '1')
ee/legacy/database/drivers/mysqli/mysqli_connection.php:114

Stack Trace: Please include when reporting this error
#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('INSERT INTO `ex...')
#1 ee/legacy/database/DB_driver.php(260): CI_DB_mysqli_driver->_execute('INSERT INTO `ex...')
#2 ee/legacy/database/DB_driver.php(175): CI_DB_driver->simple_query('INSERT INTO `ex...')
#3 ee/ExpressionEngine/Addons/search/mod.search.php(265): CI_DB_driver->query('INSERT INTO `ex...')
#4 ee/legacy/libraries/Actions.php(175): Search->do_search()
#5 ee/legacy/libraries/Core.php(604): EE_Actions->__construct(true, Object(Closure))
#6 ee/legacy/controllers/ee.php(51): EE_Core->generate_action(true)
#7 [internal function]: EE->index()
#8 ee/ExpressionEngine/Core/Core.php(257): call_user_func_array(Array, Array)
#9 ee/ExpressionEngine/Core/Core.php(113): ExpressionEngine\Core\Core->runController(Array)
#10 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#11 index.php(173): require_once('...')
#11 index.php(173): require_once('...')`

**Comment by intoeetive** [comment]
It looks like you did not run ExpressionEngine update wizard, but only replaced the files. Please run the updater https://docs.expressionengine.com/latest/installation/updating.html

**Comment by wernergusset** [comment]
I don't understand what exactly I would need to do? This project was upgraded from EE 2 to EE 5 and from then on updatet within EE itself the last couple of months.

**Comment by intoeetive** [comment]
Copy over `system/ee/installer/` folder again and visit the Control Panel to re-run the update. It looks like some queries were not executed

**Comment by wernergusset** [comment]
Okay, but from where do I get that file?

**Comment by robinsowell** [comment]
Hi Werner, Yuri asked me to hop in and double check this for you.  It actually looks like that particular module update didn't run.  While the devs figure out why and get a fix in, you can fix it short term by just manually running the query:

```ALTER TABLE exp_search ADD result_page varchar(70) NOT NULL```

You can do it in phpmyadmin or even just the query form in EE (under tools).  That should get you squared away and you won't need to worry about it going forward.  Though we'll make sure it gets run in the next update!

**Comment by wernergusset** [comment]
Thanks Robin

I run the query within EE and get this in return:

`Attention: Query not run

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'result_page':<br> ALTER TABLE exp_search ADD result_page varchar(70) NOT NULL`

**Comment by robinsowell** [comment]
MAN- yes, it did that to me when I ran it and then I edited it and it worked and then I sent you the old broken one.

```ALTER TABLE exp_search ADD no_result_page varchar(70) NOT NULL```

LOL- I blame it on Friday!

**Comment by wernergusset** [comment]
Never mind, Robin

It works now without any error. Thank you very much.
Have a wonderful weekend.
