### ISSUE TITLE
Cloning entries for Transcribe module

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#1848]
**Is your feature request related to a problem? Please describe.**
When using the Transcribe module you are forced to create a _new_ entry for entry translation, that means you can't clone and assign the cloned entry as a translation entry in one go.

**Describe the solution you'd like**
Extend Transcribe > Entry translations to allow cloning as well as adding a _new_ entry.

**Describe alternatives you've considered**
No alternative available

**Teachability, Documentation, Adoption, Migration Strategy**
It's an enhancement so backwards compatible.

**Comment by robinsowell** [comment]
Just wanted to note, I've added this as a feature request to our internal tracker for Transcribe.  I definitely think there could be some really smooth way to give an option to clone the current entry to a different language.  Closing it here, but we've got it noted in Transcribe project.
