### ISSUE TITLE
EE6 Pro Front End Editing PHP 8 compatibility error

### ISSUE THREAD

**Issue by lookwhatimade** [ExpressionEngine/ExpressionEngine#1849]
**Observation**: When front end editing is disabled, everything loads fine.  When I enable front end editing, a “strpos(): Argument #1 ($haystack) must be of type string, array given” error is thrown.  This is a result of the PHP8 change to strict types

**Debugging**:
I added in this try catch around line 155 in Custom_field.php and the error is thrown on a “File” field.  You can also see that in the stack trace screenshot attached.

```
try {

} catch ( \TypeError $e )  {
    die(var_dump($ft_api->field_type));
}
```

Also, if I var dump the value of entry at this point, it is an array and not a string.

I will note that I also found the issue happening on another field and when var_dump’ing the $entry value, it was an int(0), so I can’t say with certainty that there aren’t also other fields that this fails on. 

**Current Solution**:
Currently, my workaround is to currently wrap the entry and tagdata str_replace assignment with a type check to verify that the $entry is in fact a string.  See code below.  I can create a pull request, but wanted to add this information in case this has been reported before and there is something else going on.

```
    if (is_string($entry)) {
        if (strpos($entry, '{') !== false) {
            $entry = str_replace(
                array('{', '}'),
                array(unique_marker('channel_bracket_open'), unique_marker('channel_bracket_close')),
                $entry
            );
        }

        $tagdata = str_replace(LD . $tag . RD, $entry, $tagdata);
    }
```

Extra Notes
I will note that the File field that is erroring is in an embed template.  I'm not sure if this matters or not, but the calling template uses EE Bloqs.  The custom Bloq contains "number of entries" to show, and a "category id" field.  Those values are passed to the embed, and used as part of a normal channel entries loop.   Not sure if any of this extra info matters, but want to be thorough.

<img width="1224" alt="Screen Shot 2022-02-25 at 11 09 19 AM" src="https://user-images.githubusercontent.com/2078172/155762990-658f1b7f-8202-45f5-87b9-820ba84d4c92.png">

**Comment by intoeetive** [comment]
Thank you for reporting this! Are you running latest version of Bloqs?

Also, can you post the result of `var_dump($entry);` at this point?

**Comment by lookwhatimade** [comment]
Thanks @intoeetive 

I am on the latest version of Bloqs.  To make sure that wasn't an issue, I removed Bloqs from the equation.  

I created a new channel called Test.  Then I created a new channel field called Test File.  That's all the entry contained.  So, the new entry looks like this:
<img width="1229" alt="Screen Shot 2022-02-28 at 9 02 05 AM" src="https://user-images.githubusercontent.com/2078172/156005903-f2415805-ca5a-43aa-bfd5-69952dbedabe.png">


Then, in my template, this is the only code I used.

```
{exp:channel:entries
    channel="test"
    disable="category_fields|member_data|pagination"
    limit="1"
    dynamic="no"
    entry_id="82324"
}

Entry ID is {entry_id}

File is {test_file}

<img src="{test_file:1020x240}" alt="">

{/exp:channel:entries}
```


Here's a var dump of $entry.  I only copied the first part of the array, to make sure client info and EE keys weren't exposed.  Let me know if you need to see anything else.
<img width="1479" alt="Screen Shot 2022-02-28 at 8 56 28 AM" src="https://user-images.githubusercontent.com/2078172/155995751-d9f495d3-25a1-4d59-b210-f2f2175f8d31.png">


Lastly, to reiterate, I'm testing with PHP 8.1.1.  I can drop that PHP version to be lower, but it still may be an issue in the future.   

And again, here is what I added in Custom_field.php.  The error was caught on the file field and I was able to var dump $entry.  Otherwise, if uncommented and added back in the is_string() check, then the "strpos(): Argument #1 ($haystack) must be of type string, array given" error isn't thrown.


```           
     try {
                // if (is_string($entry)) {
                    if (strpos($entry, '{') !== false) {
                        $entry = str_replace(
                            array('{', '}'),
                            array(unique_marker('channel_bracket_open'), unique_marker('channel_bracket_close')),
                            $entry
                        );
                    }

                    $tagdata = str_replace(LD . $tag . RD, $entry, $tagdata);
                // }
            } catch ( \TypeError $e )  {
                die(var_dump($entry));
            }
```
