### ISSUE TITLE
Grid mangles anchor "name" attribute value in third-party textareas

### ISSUE THREAD

**Issue by obfuscode** [ExpressionEngine/ExpressionEngine#185]
**Description of the problem**
HTML anchors in the content of third-party add-ons gets mangled by the Grid's `namespaceForGrid` method. I've confirmed the data is correct leaving the add-on's `grid_display_field()` method. This happens in both Wygwam and Editor and is related to the same bug that was fixed in EE previously in non-grid fields (sorry, I don't have a reference to that issue/fix at the moment).

**How To Reproduce**
1. Create a third-party Wygwam or Editor add-on field **inside a Grid field** with:
```html
<p>Test <a name="my_anchor">anchor</a> area</p>
```
2. Save the entry

**Screenshots / Videos / Template Code**
![anchor-issue](https://user-images.githubusercontent.com/2160089/56315097-de6e5380-6124-11e9-8273-d8b6e8a3d88f.png)

**Environment Details:**
 - Version: 5.2.2
 - PHP Version:  7.1
 - MySQL Version: 8.0.12
 - OS: macOS
 - Web Server: nginx

**Comment by aaroncrawford** [comment]
Do we have an expected ETA on this one?  Got a few sites with this bug.

**Comment by ron-soak** [comment]
+1
Does anyone have a workaround?

**Comment by aaroncrawford** [comment]
In my case, I'm using Fluid fields and this bug has me adding just another text field to the fluid group that's just dedicated to anchors.  Not the best approach, but it works for now until this is resolved.

**Comment by intoeetive** [comment]
As of to-be-released EE 6.1 (`6.dev`) I wasn't able to replicate this with RTE (using CKEditor or Redactor engines). However I confirm the issue exists in Wygwam (not checked Editor)

Which makes me think it's related to referenced add-ons - @obfuscode
