### ISSUE TITLE
Form validation string triggers deprecation warning from EE Channel Entries Parser

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#1852]
I have a site with a form that uses HTML5 validation.
One of these rows tests for a UK Post Code value (e.g. of the form AB1 2CD) - the regex to test for this is 
```
^([a-zA-Z]){1}([0-9][0-9]|[0-9]|[a-zA-Z][0-9][a-zA-Z]|[a-zA-Z][0-9][0-9]|[a-zA-Z][0-9]|[0-9][a-zA-Z]){1}([ ])?([0-9][a-zA-z][a-zA-z]){1}$
```
So the form input looks like this... 
```
<input 
    class='form-control w-100' 
    type='text' 
    id='Post_Code' 
    name='Post Code' 
    maxlength='15' 
    required pattern="^([a-zA-Z]){1}([0-9][0-9]|[0-9]|[a-zA-Z][0-9][a-zA-Z]|[a-zA-Z][0-9][0-9]|[a-zA-Z][0-9]|[0-9][a-zA-Z]){1}([ ])?([0-9][a-zA-z][a-zA-z]){1}$"
>
```
When this element is included in the form, I get a deprecation warning from the EE Channel Entries parser thus:
```
Deprecated
strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

ee/legacy/libraries/channel_entries_parser/Parser.php, line 297

    Severity: E_DEPRECATED
```
As you will note, the form input value concerned does not contain any EE template variables (but does sit within a Channel Entries loop).

Removing the three `{1}` elements from the validation regex fixes the issue (but breaks the regex).

This is a bit of overreach by the Channel Entries parser I think...

EE 6.2.6 running on php 7.4.

**Comment by mcfarlandonline** [comment]
I'm seeing this again in EE 6.2.7, too. (PHP 7.4)
(I think it was fixed for a time... https://github.com/ExpressionEngine/ExpressionEngine/issues/1495)

> Deprecated
> strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior
> ee/legacy/libraries/channel_entries_parser/Parser.php, line 297
> 
> Severity: E_DEPRECATED
> Warning
> Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
> ee/ExpressionEngine/Boot/boot.common.php, line 477
> 
> Severity: E_WARNING
