### ISSUE TITLE
`URL` query string allows for unwanted bot traffic redirects from front end

### ISSUE THREAD

**Issue by dougblackjr** [ExpressionEngine/ExpressionEngine#1856]
## Description of the problem

ExpressionEngine currently has a query string (`?URL=`) that is checked with all network calls. This currently exists with both Control Panel calls and front end calls, and is used by various parts of the backend.

When in use by the backend of an EE site, it is assumed this would be fine behavior. However, the front end query string use can currently be used by any user, and can be utilized by bot traffic.

Example: [https://nerdcore.codes/?URL=example.com](https://nerdcore.codes/?URL=example.com)

EE 6.2.x and 5.4.x introduced a robots NOFOLLOW NO INDEX for these redirects. However, it does continue to provide behavior that is not ideal and can be manipulated by bots and bad behavior users. It also allows for a simple screen to redirect unsuspecting users.

## How To Reproduce

Go to [https://nerdcore.codes/?URL=example.com](https://nerdcore.codes/?URL=example.com)

## Recommended Solution

- Disallow by default these types of redirect from the frontend
- Add config override to enable these types of redirects

**Comment by dougblackjr** [comment]
Draft PR here: [https://github.com/ExpressionEngine/ExpressionEngine/pull/1857](https://github.com/ExpressionEngine/ExpressionEngine/pull/1857)

**Comment by blue-dreamer** [comment]
Sounds good to me, once spammers know that redirects are stopped they might go elsewhere!

Would the config setting for URL redirects be allowed or disallowed by default?

**Comment by dougblackjr** [comment]
@blue-dreamer In this PR this would disallow by default. You would need to add the config override to allow the behavior.

**Comment by blue-dreamer** [comment]
^ Perfect :)

**Comment by silenz88** [comment]
> * Disallow by default these types of redirect from the frontend

Right now there is intended usage for these type of redirects from the front-end, so just turning them off might lead to confusion elsewhere,

**Comment by dougblackjr** [comment]
@silenz88 Can you give an example? I was struggling to find one.

**Comment by silenz88** [comment]
Somewhere in Security Settings you should find something like 'Apply Rank Denial for user-submitted links'.
From the top of my head ...

**Comment by silenz88** [comment]
How about blocking external referrers? Of course referrers can be spoofed but up to now none of these redirect spammers seemed to bother.
