### ISSUE TITLE
Channel Default author not being updated when deleting members

### ISSUE THREAD

**Issue by ops-andy** [ExpressionEngine/ExpressionEngine#1867]
Set the default author of a channel to a member.
Delete that same member from the site.
Try to access channel settings for which that member was the default author.
The following error is displayed:
```
Call to a member function getMemberName() on null
ee/ExpressionEngine/Controller/Channels/Channels.php:816

Stack Trace: Please include when reporting this error
#0 ee/ExpressionEngine/Controller/Channels/Channels.php(266): ExpressionEngine\Controller\Channels\Channels->renderSettingsTab(Object(ExpressionEngine\Model\Channel\Channel), NULL)
#1 ee/ExpressionEngine/Controller/Channels/Channels.php(169): ExpressionEngine\Controller\Channels\Channels->form('1')
#2 [internal function]: ExpressionEngine\Controller\Channels\Channels->edit('1')
#3 ee/ExpressionEngine/Core/Core.php(257): call_user_func_array(Array, Array)
#4 ee/ExpressionEngine/Core/Core.php(113): ExpressionEngine\Core\Core->runController(Array)
#5 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#6 admin.php(144): require_once('...')
#6 admin.php(144): require_once('...')
```
![image](https://user-images.githubusercontent.com/55093827/156419583-61c64ee7-f413-4f32-a086-a0e75d235ad5.png)

My thought is that EE should ask who to reassign as the default author for respective channels where the deleted member was the default author, similar to reassigning authors for published entries by the deleted member.

related forum post: https://expressionengine.com/forums/topic/253338/solved-getting-an-error-clicking-on-a-channel-name-in-the-cp-any-ideas

**Comment by intoeetive** [comment]
@ops-andy while the reassignment dialog would be good to have (please create Jira ticket), for now the referenced PR is fixing the error
