### ISSUE TITLE
[EE6] Simplistic sanitization of search terms produces unexpected/inappropriate/no results

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#1869]
The EE6 search module "sanitizes" search terms using a very simple strategy of replacing certain non-alphanumeric characters with spaces. This appears in `/system/ee/legacy/helpers/search_helper.php` (screenshot below).

The effect of this sanitization is (obviously) to create a modified search term, which potentially gives unexpected results. This is especially the case when a search term is quoted — the typical meaning of which is that the search term is intended to be used exactly.

A real example. The name of a real project on a site that I manage uses an exclamation mark in place of the letter i, in the form **abc!def** (not the real title, but the same form). As a search term, this is modified to **abc def**. When used unquoted, this will search separately for the terms **abc** and **def**, returning inappropriate results, which don't match the original search term. More seriously, when quoted, the search term is modified to **"abc def"**. This modified search term is then searched exactly, and (incorrectly) returns no search results at all. The effect is that this perfectly innocuous project title cannot be searched for.

This behaviour is sufficiently inappropriate/unexpected that it should be considered a bug. It's not reasonable to expect that a typical user will understand that the search term has been modified, resulting in an entirely different search being performed. Using quoted search terms has a specific common expectation in search, and this behaviour of EE violates that expectation.

It's not unreasonable for EE to sanitize search terms if they represent a genuine security threat. But a much less simplistic algorithm is needed, which doesn't modify search terms — especially when quoted — unless absolutely necessary. This should be managed within EE, and not be made the user's problem.

<img width="564" alt="Screen Shot 2022-03-04 at 12 01 32 PM" src="https://user-images.githubusercontent.com/46760375/156835225-57f413a8-62a4-45ec-ab6c-76c41409b17d.png">

**Comment by PaulBaileyAtChan** [comment]
Afterthought. Disallowing the @ symbol in search terms has the obvious effect of making it significantly harder to search for email addresses, and impossible to search for them exactly. This is clearly not great.

**Comment by PaulBaileyAtChan** [comment]
A late addition here to note that I clearly missed the fact that the "sanitzation" looks like it's mainly to remove characters with special meaning in regular expressions (presumably to avoid borking the search). The issue still remains that such characters should be suitably *escaped*, rather than removed, so that the original search term is respected.

**Comment by intoeetive** [comment]
@matthewjohns0n do we need this function here at all? The search is performed using SQL `LIKE`, not regular expressions - so probably regular XSS cleanup should be sufficient?

**Comment by matthewjohns0n** [comment]
From what I can tell, this code dates back to [this commit](https://github.com/ExpressionEngine/ExpressionEngine/commit/6029ffdef522146923ed63f92b4ff8b6a1ec00f7) from 13 years ago, and it is probably actually older than that. We are already [XSS sanitizing before returning it](https://github.com/ExpressionEngine/ExpressionEngine/blob/7.dev/system/ee/legacy/helpers/search_helper.php#L79), so we're good there. 

My one concern in this code is that we definitely need to be sanitizing against SQL injection before using this as a search term in the DB. This character stripping that is being performed is probably not the code responsible for SQL injection sanitization though, so I'm really not sure if there's a good reason to leave it at all.
