### ISSUE TITLE
EE_Fieldtype::pre_loop($data) method is never called.

### ISSUE THREAD

**Issue by jonathandixon** [ExpressionEngine/ExpressionEngine#187]
**Description of the problem**
For any custom field type that implements the [EE_Fieldtype::pre_loop($data)](https://docs.expressionengine.com/latest/development/fieldtypes.html#ee_fieldtypepre_loopdata) method, this method is not called when the field is rendered. 

This was noticed when upgrading from EE 2.9.2 to 5.2.1. We have a custom field type that implements this method. The field type is primarily used in a grid and the `pre_loop` method is used so only one DB query is made.

This may have been introduced in [this commit](https://github.com/ExpressionEngine/ExpressionEngine/commit/a2bc3bdaa2e4a3dea63a2104c7332400ea078de6). An additional key was added to the `$_grid_data` array in `system/ee/legacy/models/grid_model.php`, but `system/ee/legacy/libraries/Grid_parser.php` was never updated to handle this new key.

**How To Reproduce**

1. Create a field type that implements the `pre_loop` method.
2. Create a grid field that contains a field of the type from step 1.
3. Add the grid field to a channel and update the template to render the grid field.
4. Create an entry with data for the grid field.
5. Render the entry and observe that the `pre_loop` method is not called.

**Environment Details:**
 - Version: 5.2.1
 - PHP Version 7.2.12
 - MySQL Version 5.7
 - OS: Linux
 - Web Server: Apache with php-fpm

**Comment by eric-lamb62** [comment]
Neat. This is still a thing 🤔 

Doing a quick search of the code, the only first party field that uses this method is the File FiledType. But, as is said in OP, the core never calls that method (in 6.1.X at least). 
https://github.com/ExpressionEngine/ExpressionEngine/blob/eb622f075047348d787235e9b33c15406e292fb2/system/ee/ExpressionEngine/Addons/file/ft.file.php#L301

Going aaaaalllllll the way back to EE 2, it does appear there was support for that method. And it was used pretty heavily. 
https://github.com/ExpressionEngine/ExpressionEngine/blob/0017bb5add82250eb8f3fa8252c38590e0989d38/system/expressionengine/fieldtypes/EE_Fieldtype.php#L281

And it appears to be executed in the legacy Preparser stage:
https://github.com/ExpressionEngine/ExpressionEngine/blob/0017bb5add82250eb8f3fa8252c38590e0989d38/system/expressionengine/libraries/channel_entries_parser/Preparser.php#L114

So, I guess it begs the question: this thing needed? Should be fun tracking down the intent and implementing them, but also a bit of effort lol

**Comment by intoeetive** [comment]
I wasn't able to figure out at what point / commit this got fixed, but as of EE 7.2.17 `pre_loop` is being called whether this is from stand-alone field or Grid column
