### ISSUE TITLE
Channel settings throw an error when the default author gets deleted.

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1878]
I tried to go into a channel's settings and got the following error:

![image](https://user-images.githubusercontent.com/308752/157335430-35d230a8-59a7-4c26-be43-298eaf1c3074.png)

I think I nailed the problem down to the fact that the "Default author for guest entries" member for the channels in question had recently been deleted.

A event is triggered when you try to delete a member that has authorship of an entry, it seems like a similar error should be thrown when a member is referenced in settings.

**Comment by intoeetive** [comment]
@murtaugh thank you for reporting! We are already aware of the issue: #1867 and have the fix ready, pending release #1872
