### ISSUE TITLE
reCaptcha v3 not working in Channel Form with inline error handing

### ISSUE THREAD

**Issue by jamesseavers** [ExpressionEngine/ExpressionEngine#1880]
reCaptcha v3 (v3) not working correctly in Channel Form with inline error handing due to the input name="captcha" having no value when the channel form is submitted.

v3 requires no user input, which is probably why the captcha field is hidden. However, when using v3 with inline errors, the Channel_form_lib.php executes the following code on line 1256:

1256:

if (! ee()->input->post('captcha')) {
    $this->field_errors['captcha_word'] = ee()->config->item('use_recaptcha') == 'y' ? ee()->lang->line('recaptcha_required') : ee()->lang->line('captcha_required');
}

This is then referenced on line 1586:

if ($captcha_required && $this->error_handling == 'inline') {
    $this->field_errors = array_merge($this->field_errors, array('captcha_word' => (ee()->config->item('use_recaptcha') == 'y' ? ee()->lang->line('recaptcha_required') : ee()->lang->line('captcha_required'))));
 }

As the captcha input is empty, an error will always occur.

I'm using EE 6.2.7 and have replaced this error in the front-end in a variety of browsers.

**Comment by intoeetive** [comment]
@jamesseavers when using reCapthca v3, you are still required to have `{captcha}` or `{if captcha}... some code.. {/if}` inside your channel form. Can you confirm that you have it and also you see reCaptcha "badge" on the page?

If you do have it (and see the badge) - can you check if there are any javascript errors in developer console when submitting the form?

**Comment by jamesseavers** [comment]
@intoeetive I can confirm that I am using in the form <code>{if captcha}
        {captcha}
      {/if}</code> within the channel form tags.

I am not seeing the reCaptcha badge (which is odd), but I am seeing the reCaptcha code sent back as successful by adding a console.log line to the recaptcha.js javascript file. I did this as my initial thoughts were that reCaptcha mustn't be working, this proves otherwise.

Here's the form page:

/* removed URL as this is now closed */

There are no Javascript errors in console.

**Comment by intoeetive** [comment]
@jamesseavers I just tested your form and it worked just fine

**Comment by jamesseavers** [comment]
Apologies, I should have pointed out that I have negated the problem with the following code:

<code>{if field_errors:count == 1}
    {field_errors}
    {if '{error}' == 'reCAPTCHA check did not pass'}{redirect="/contact/thanks"}{/if}
    {/field_errors}
    {/if}</code>

I received your submission.

I figured that the recaptcha.js just prevents form submission if failed, so checking for the 1 error and making sure it's the recaptcha one is an ok temporary fix.

**Comment by intoeetive** [comment]
So that submission actually works, right? It's just that the error is shown while it should not be?

**Comment by jamesseavers** [comment]
That is correct, the submission works, reCaptcha does it's thing but ExpressionEngine thinks there is an error when there isn't one.
