### ISSUE TITLE
Channel Form Tag doesn't work with entry_id set as template partial

### ISSUE THREAD

**Issue by creativearc-paul** [ExpressionEngine/ExpressionEngine#1883]
{exp:channel:form channel="member_profiles" status="open|Private" entry_id="**{tp_logged_in_profile_entry_id}**" include_assets="no" require_entry="yes" author_id="CURRENT_USER" return="/thanks/" error_handling="inline"}
...stuff...
{/exp:channel:form}

The {tp_logged_in_profile_entry_id} contains exp:query output:

`{exp:query sql="SELECT entry_id as profile_entry_id  FROM exp_channel_titles WHERE channel_id = 17 AND author_id = {logged_in_member_id} LIMIT 1"}`

However, the exact same channel form tag works when the template partial has the literal value of '45', which is the same result from the query.

**Comment by creativearc-paul** [comment]
The EE Template error is "You must specify a valid entry to edit." suggesting that no value is being returned to the entry_id parameter via the partial.

**Comment by jamesseavers** [comment]
Have you tried to just output the value of {tp_logged_in_profile_entry_id} to make sure the variable is accessible? I normally remove all the template code, and then add in:

`<h1>{tp_logged_in_profile_entry_id}</h1>`

to see if it exists and has a value I expect.

**Comment by creativearc-paul** [comment]
Yes, if I just place the template variable on its own in the template it produces '45,' based on the exp:query within.

**Comment by jamesseavers** [comment]
Thanks. It would be interesting to know which thrown error you are getting from the Channel_form_lib.php file. The error is invoked 2 times at line 189:

`// require entry?
        if (! $this->entry('entry_id') && $this->bool_string(ee()->TMPL->fetch_param('require_entry'))) {
            if (ee()->TMPL->no_results()) {
                $this->switch_site($current_site_id);

                return ee()->TMPL->no_results();
            }

            throw new Channel_form_exception(lang('channel_form_require_entry'));
        }`

And also at line 2228:

`protected function entry_match_check($params)
    {
        // Whoa there big conditional, what's going on here?
        // We want to make sure no one's being tricky here and supplying
        // an invalid entry_id or url_title via a segment, so we need to
        // check to see if either exists and if it does make sure that the
        // passed in version is the same as what we find in the database.
        // If they are different (most likely it wasn't found in the
        // database) then don't show them the form.  We also double check it's
        // in the correct channel

        if (($params['entry_id'] != '' && $this->channel('channel_id') != $this->entry('channel_id')) or
            ($params['url_title'] != '' && $this->channel('channel_id') != $this->entry('channel_id')) or
            ($params['entry_id'] != '' && $this->entry('entry_id') != $params['entry_id']) or
            ($params['url_title'] != '' && $this->entry('url_title') != $params['url_title'])
        ) {
            if (ee()->TMPL->no_results()) {
                return ee()->TMPL->no_results();
            }

            throw new Channel_form_exception(lang('channel_form_require_entry'));
        }
    }`

Do you know which one you are falling foul of?

**Comment by intoeetive** [comment]
I believe this is expected behavior here

The content of the partial is populated, but not executed, at the point where the parameter is read. 

If you need to ensure parsing order, consider placing `exp:channel:entries` inside `exp:query` call
