### ISSUE TITLE
Slideshow not working on EE 6 demo theme/ clean install (pr coming)

### ISSUE THREAD

**Issue by jaysavage83** [ExpressionEngine/ExpressionEngine#1885]
When installing EE 6 using the demo theme, The slideshow does not load on the home/index page template. 
After some digging it appears to be a simple issue with the image directory id.  Changing the directory_id on line 37
in the home/index template from 8 to 7 appears to be the fix for my home lab install.

**Comment by matthewjohns0n** [comment]
Hi @JayGreentree! Thanks for jumping in and fixing this, and sorry for the delayed reply. We're reviewing this and planning on getting it into the 6.3.x release schedule.
