### ISSUE TITLE
Channel Form errors are created twice for custom fields 

### ISSUE THREAD

**Issue by jamesseavers** [ExpressionEngine/ExpressionEngine#1887]
It's my first bug squash attempt, so I thought I would post here and then branch as per Contributions.md.

Channel Form errors are being created twice, once for the field_id, and once for the field_name. For example, one validation error for a field labelled 'Content' and had a field_id of 9 would look like this when returned:

field_id_9 is required
Content is required

This happens whether errors are handled inline or not.

The code that is causing this issue starts at line 1589:

`
foreach ($this->field_errors as $field => $error) {
            if (isset($id_to_name_map[$field])) {
                $this->field_errors[$id_to_name_map[$field]] = $error;
            }
        }
`

As you can see, the error is only appended to the list of field errors, it does not replace the original error.

**Comment by jamesseavers** [comment]
When debugging this I found that the code above just needs to be removed as field matching happens later in the method.

**Comment by ops-andy** [comment]
related Slack discussion: https://eecms.slack.com/archives/C04L896K4/p1646736479603529

**Comment by ops-andy** [comment]
@intoeetive can you review this and let me know your thoughts or open an internal ticket to resolve.

**Comment by jamesseavers** [comment]
@ops-andy @intoeetive I have forked EE and coded a fix to the non-inline duplicate error issue here [jamesseavers](https://github.com/jamesseavers)
/
[ExpressionEngine](https://github.com/jamesseavers/ExpressionEngine)

How do I merge it into the dev?

**Comment by jamesseavers** [comment]
Pull request done.

**Comment by intoeetive** [comment]
The pull request has been merged and released: https://github.com/ExpressionEngine/ExpressionEngine/pull/1895
