### ISSUE TITLE
`exp:channel:entries` breaks when without categories

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#1891]
In case `exp:channel:entries` has a `{categories}` tag, but no entries, the SQL gives an error:

```
Exception Caught
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') ORDER BY c.group_id, c.parent_id, c.cat_order' at line 7:
SELECT c.cat_name, c.cat_url_title, c.cat_id, c.cat_image, c.cat_description, c.parent_id, p.cat_id, p.entry_id, c.group_id , cg.field_html_formatting, fd.* , exp_category_field_data_field_1.field_id_1, exp_category_field_data_field_1.field_ft_1, exp_category_field_data_field_2.field_id_2, exp_category_field_data_field_2.field_ft_2 FROM (exp_categories AS c, exp_category_posts AS p) LEFT JOIN exp_category_field_data AS fd ON fd.cat_id = c.cat_id LEFT JOIN exp_category_groups AS cg ON cg.group_id = c.group_id LEFT JOIN exp_category_field_data_field_1 ON exp_category_field_data_field_1.cat_id = c.cat_id LEFT JOIN exp_category_field_data_field_2 ON exp_category_field_data_field_2.cat_id = c.cat_id WHERE c.cat_id = p.cat_id AND p.entry_id IN () ORDER BY c.group_id, c.parent_id, c.cat_order

ee/legacy/database/drivers/mysqli/mysqli_connection.php:114
```

A quick and dirty fix is to replace [this](https://github.com/ExpressionEngine/ExpressionEngine/blob/8d254789042f9ea1423c1984e018e3468b0765ad/system/ee/ExpressionEngine/Addons/channel/mod.channel.php#L419):

```php
$sql .= implode(',', array_unique(array_filter($categories))) . ')';
```

By:

```php
$sql .= empty($categories)
    ? implode(',', array_unique(array_filter($categories))) . ')'
    : '0)';
```

I think it's enough until we reafactor this part.

**Comment by intoeetive** [comment]
@robsonsobral can you tell more about how to replicate this? I tried and I could not - I think these lines prevents the error already (but looks like not in your case) https://github.com/ExpressionEngine/ExpressionEngine/blob/8d254789042f9ea1423c1984e018e3468b0765ad/system/ee/ExpressionEngine/Addons/channel/mod.channel.php#L415-L417

**Comment by robsonsobral** [comment]
@intoeetive , using the database for tests, try to access `http://localhost:8888/index.php/cats/entry` without any categories associated yet.

**Comment by intoeetive** [comment]
@robinsowell can you help replicating this? I am not able to

**Comment by intoeetive** [comment]
Closing out as we were never able to replicate this. Please comment back if you still see the issue, if possible with more details how to replicate
