### ISSUE TITLE
Indicate when you're looking at an entry version

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1897]
At the moment, click on "view" to see an entry version takes you to a page that is totally indistinguishable from the normal edit view. There's no indication that you're looking at a version that doesn't represent the latest version of an entry.

Adding text to the main nav title area would be sufficient, I think:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/308752/158472644-9b8c7556-a848-4029-b9ef-0991f37f274a.png">

**Comment by intoeetive** [comment]
@ajohnson what are your thoughts? (we also could style it similar to "auto saved" message )
![image](https://user-images.githubusercontent.com/752126/158777361-e0fc6e4a-fd7f-4241-b2ad-56ad4bd23ba4.png)

**Comment by ajohnson** [comment]
@intoeetive Using the same "auto saved" component should work nicely, especially the new header design on the publish form.

The copy in the component could be formatted as follows:

> **Revision #3** (3/23/2022 6:19 PM)

(Where the "**Revision #3**" is bold, and without making the number a link. That's just GitHub.)
