### ISSUE TITLE
Does the "link" HTML button work as intended?

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1899]
The value of the "opening tag" for the link button reads as follows:

`<a href="[![Link:!:http://]!]"(!( title="[![Title]!]")!)>`

To me this reads as prompting the user to add a value for the `href` attribute, and then prompting the user to add a value for the `title` attribute. When using the button, the second prompt doesn't happen.

If I'm wrong and the second prompt isn't expected, why is the `title` attribute referenced at all?

**Comment by robsonsobral** [comment]
(a plus: I'm not sure, but `title` isn't recommend to links.)

**Comment by intoeetive** [comment]
@Yulyaswan can you look and see whether this is something we need to fix - or something we need to remove?

**Comment by Yulyaswan** [comment]
`The `title` attribute specifies extra information about an element. The information is most often shown as a tooltip text when the mouse moves over the element.`
The `title` is ok to use for the link

HTML Button will check
