### ISSUE TITLE
RFC: ExpressionEngine X should be a rebuild from the ground up

### ISSUE THREAD

**Issue by AndrewLowther** [ExpressionEngine/ExpressionEngine#19]
Adding this here for comment.

ExpressionEngine currently has a lot of legacy baked into the code to handle when a user upgrades from EE 2 -> 3 -> 4. This is absolutely fine, however as this goes on, the more and more legacy needs to be supported.

What I would like to propose for comment is that future versions of EE, potentially 6 or higher should be a full rebuild of the CMS, and be fully incompatible with previous versions.

Defined below are what I believe some of the talking points should be:
- More utilisation of modern development practices. i.e. Adoption of PSR standards, etc
- Modular design. i.e. Drop in/replacement of modules via a package manager (ties into adoption of PSR)
- Security with utilisation of open source modules for data management

Feel free to add further points, or close if this is not relevant.

**Comment by kevincupp** [comment]
Further talking points should be:

* What do we tell our users who were excited about EE going open source when they have to wait for years for a rewrite just to reach feature parity with the current version?
* What do we tell our users who are on EE 5 and depend on certain add-ons that, like EE3, they will have to wait for add-on developers to update to the new EE 6 architecture, but that most add-on developers never will, leaving them stuck?

I personally think we should continue iteratively making improvements in this area as we have been, and if eventually it ends up being a full rebuild while also releasing builds that make forward progress in all areas of user and developer experience along the way, then that's great. Stopping everything to do a full rebuild seems very idealistic, but not very pragmatic.

We already have a system for making these kinds of improvements, we deprecate code in each major version, we're not actively trying to support all code that once relied on EE 2 as you're suggesting. We can do the things you're suggesting without a full rebuild.
