### ISSUE TITLE
EE Pro Styling Issues

### ISSUE THREAD

**Issue by dougblackjr** [ExpressionEngine/ExpressionEngine#1903]
**Description of the problem**

Minor EE Pro styling issues.

EE Pro icons do not have max width set, so they grow infinitely in some circumstances:

![Screenshot from 2022-03-22 05-31-35](https://user-images.githubusercontent.com/6020323/159451845-d4ad8757-9500-4fb2-bf1c-9c42bc91173f.png)

In addition, the headers of the modals can have an `:after` attached, which may display ugly stuff:

![Screenshot from 2022-03-22 05-31-43](https://user-images.githubusercontent.com/6020323/159451997-d1ede14d-7244-481e-8fb1-1f1a4f0a77eb.png)

![Screenshot from 2022-03-22 05-33-28](https://user-images.githubusercontent.com/6020323/159452026-b90efd64-a031-464b-b977-cb9d5ee9915e.png)

**Environment Details:**
 - Version: 6.2.4
 - EE Pro: 1.1

**Possible Solution**

For the icons, adding a max-width of 24px addressed the issue.

**Comment by Yulyaswan** [comment]
@dougblackjr could you please give me a little bit more info, what kind of fields did you use, how you got that `:after `element
Because fo now it's hard to reproduce your work and issue. Thanks!

**Comment by dougblackjr** [comment]
@Yulyaswan Sure, no problem!

It is unrelated to fields, more related to the CSS that's laid out on the page of a site.

## Image Size

If the selector applies a width to an image where the frontedit icons would be, the images inside of those get the width in the cascade.

![Screenshot from 2022-03-23 05-23-06](https://user-images.githubusercontent.com/6020323/159666563-346b65c0-3b31-4d5a-837f-3ebe6726a862.png)

The css that is applied there to `#inner-container .gallery-list .img-caption img` has a `width: 100%`. This allows the car images to span the entire div.

Adding `width: unset` to the frontedit icon image seems to fix the issue:

![Screenshot from 2022-03-23 05-27-03](https://user-images.githubusercontent.com/6020323/159667079-f64fafde-7de1-42d3-b9e0-3b1669717212.png)

## Modal Header

The modal header gets the cascaded header:after from the site CSS:

![Screenshot from 2022-03-23 05-29-03](https://user-images.githubusercontent.com/6020323/159667531-55d76acc-95b6-4f00-9563-9e8b107fd078.png)

In the image, the header of the site has that gradient background. That gets pulled into the modal header in the `header:after` selector. 

I'm not entirely sure how to get around that one. We can fix it in the CSS for the main site, but I'm sure others may be impacted by that.

Let me know how I can help!
