### ISSUE TITLE
Command line access to ExpressionEngine (cli)

### ISSUE THREAD

**Issue by dstrunk** [ExpressionEngine/ExpressionEngine#191]
**Is your feature request related to a problem? Please describe.**
I am working on a multi-lingual site that has thousands of products imported weekly via a cron. I am importing via DataGrab, which has to import in batches. As we launch new languages, we add new imports—each adding considerable time and front-end processing to the site's load.

**Describe the solution you'd like**
It would be great if PHP cli had access to ExpressionEngine API for longer-running cron processes that would otherwise time out in the browser, free of the `max_execution_time` and `memory_limit` imposed by web servers. I imagine drawbacks would be considerable refactoring effort, and perhaps an increased attack vector from a security standpoint.

Note that this proposal could open the door to other beneficial things missing from the EE ecosystem; namely, long running job queues, core-supported migrations, cache flushes, etc.

**Describe alternatives you've considered**
I've referenced [this post](https://www.thenerdary.net/post/20965500651/bootstrapping-ee-for-cli-access), but it's definitely hacky and requires manual patch updates to the CLI app directory.

**Teachability, Documentation, Adoption, Migration Strategy**
Users will be able to use this similar to the post referenced above. Once CLI has been implemented, a user could create a plugin or module. Inside of their module, they could create a controller that extends a special CLI controller, for instance. The below is semi-pseudo code to demonstrate `true` returning a success and anything else returning `false`, similar to what a shell program would expect:

```php
<?php

class Cli extends Cli_Controller // Cli_Controller doesn't currently exist
{
    public function __construct()
    {
        ee()->load->library('logger');
        ee()->load->library('api');
    }
    public function import()
    {
        ee()->api->instantiate('channel_entries');
        ee()->api->instantiate('channel_fields');
        $channel_id = 1;
        $data = ['title' => 'Title from some import process…'];

        ee()->api_channel_fields->setup_entry_settings($channel_id, $data);
        $success = ee()->api_channel_entries->save_entry($data, $channel_id);

        if ($success) {
            ee()->logger->log("Success! imported {$channel_id}.");
            return true;
        }

        return false;
    }
}
```

After this controller is written, you would call the following command from the root of your ExpressionEngine install (proposed CLI executable is the current `eecms` that handles command line upgrades, but it could be whatever):

```sh
php system/ee/eecms directory/controller/action --param=value
```

Proposing this syntax since it is similar to how EE currently handles routing, but open to other ideas on the CLI side.

**Comment by intoeetive** [comment]
@dstrunk thank you for the idea and providing so many details!

We have already [built CLI into EE6](https://docs.expressionengine.com/latest/cli/intro.html) and it will get more features in next releases.

Closing this issue, if you would be willing to provide some feedback on what should be in CLI and how it should function, please create new issue (or reopen this one).
