### ISSUE TITLE
On MacOS Safari, Entry Manager (5.2.2) won't accept keyword filter after any other filters have been changed

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#192]
**Description of the problem**
This is a minor but annoying UI glitch, which seems to be restricted to MacOS Safari. It doesn't occur in Firefox or Chrome.

After having changed any of the other filters, the Entry Manager won't accept any new (or different) keyword filters. No JS issues appear in the console. Clearing the other filters doesn't help; the page must be reloaded, and the keyword filter must be added as the first filter if it is to be accepted.

The effect is minor, but it is an annoyance when performing multiple or more complicated searches.

**How To Reproduce**
In MacOS Safari (tested with 12.1, running on MacOS 10.14.4), go to the Entry Manager. Add a keyword filter without first having changed any of the other filters. This will work as expected.

Reload the page. Change another filter — for example change "search in (Titles)" to "search in (Titles & Content)". It now won't be possible to add a keyword filter.

**Environment Details:**
 - Version: 5.2.2
 - MacOS 10.14.4
 - Safari 12.1

**Comment by quaimaker** [comment]
Isn't better with #EE6.

You can't really work with it in Safari.

https://user-images.githubusercontent.com/76868679/103456286-e7d29180-4cf4-11eb-89ca-ee5a62c0e316.mp4

**Environment Details:**

Version: 6.0.0
MacOS 11.1
Safari 14.0.2

**Comment by Colbitron** [comment]
Yeah, I've got several people in my company that use Safari as their primary browser. Can confirm this is happening exactly as quaimaker shows on our Macs running across different versions.

I assume this is a javascript problem given what's happening. When turning on the debugger in Safari and enabling it to stop on all exceptions, I do see that it errors in the `jquery.js` sent from the themes directory. Specifically, it errors on 3 different statements, all with the same exception, `SyntaxError: The string did not match the expected pattern.`.
* `a.querySelectorAll("*,:x")`, line 482 prettified in Safari or line 2, column 10515 in the uglified version <br> ![Screen Shot 2021-01-15 at 10 46 34 AM](https://user-images.githubusercontent.com/5994992/104761616-64fffc80-5720-11eb-80aa-d6a8aba42d93.png)
* `s.call(a, "[s!='']:x")`, line 486 pretty, line 2 col 10740 ugly <br> ![Screen Shot 2021-01-15 at 10 46 58 AM](https://user-images.githubusercontent.com/5994992/104761815-a8f30180-5720-11eb-9ca7-6b56f79a2602.png)
* `w.querySelectorAll(s)`, line 351 pretty, line 2 col 7060 ugly. This one repeats several times depending on the page (9 times on the generic entries page and 7 times on the members page for example). <br> ![Screen Shot 2021-01-15 at 10 47 16 AM](https://user-images.githubusercontent.com/5994992/104762281-50703400-5721-11eb-8b5b-ae3efa452f80.png)
