### ISSUE TITLE
grid_save hook is not called if all Grid rows are removed

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#193]
**Description of the problem**
I thought this was a problem with Publisher, but after debugging it, I'm pretty sure it's an EE issue. When deleting existing rows from a Grid field, thus leaving no rows, then saving, the grid_save() hook is not called. The issue seems to be in ContentModel.php line 218 `if ($this->isDirty($name))`, which is not evaluating to true. Looking at it more closely it appears that the Grid field name, in my case `field_id_24` is not in the `_clean_backups` array. Entity.php line 688 `return array_key_exists($name, $this->_clean_backups);`

**How To Reproduce**
Create a Grid field, add a row, then save the entry.
Delete the row, then save again. Notice that the grid_save hook is never called.

**Environment Details:**
 - Version: 5.2.2
 - PHP Version: 7.2

**Possible Solution**
No idea. The internals of the models are a confusing place. To EE everything seems fine b/c it does delete the Grid rows, but add-ons using the hook can't do their thing.

**Comment by robinsowell** [comment]
We're having trouble replicating this one.  We did a simple test- put a die in the extension call right here: https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/system/ee/legacy/models/grid_model.php#L827

Then faked an extension in the db:

<img width="730" alt="Screen Shot 2019-05-29 at 2 55 25 PM" src="https://user-images.githubusercontent.com/1181219/58583357-d32d3e00-8221-11e9-9d59-ba60a76a9bc6.png">

Then went and edited a test entry.  Entry only had a single grid field, grid had a single text column.

We deleted all rows, saved, and we got the die.

From here, it looks like it is firing.  Any chance it has to do with Publisher needing to juggle field id numbers? In the back of my head, I thought I recalled running into that.

**Comment by litzinger** [comment]
Did you put a die() statement in the isDirty() check? It doesn't juggle field ids, just row ids.

**Comment by robinsowell** [comment]
No, just in the extension call a la:


```
		// -------------------------------------------
		// 'grid_save' hook.
		//  - Allow developers to modify or add to the Grid data array before saving
		//
			if (ee()->extensions->active_hook('grid_save') === TRUE)
			{

				die('hooked');

				$data = ee()->extensions->call(
					'grid_save',
					$entry_id,
					$field_id,
					$content_type,
					$table_name,
					$data
				);
			}
```
I was thinking that wasn't firing at all.

**Comment by robinsowell** [comment]
Double checked with Seth, the hook only fires if the grid is dirty, so something odd is going on.

**Comment by robinsowell** [comment]
Brian, just to be clear, if you die in the hook, is it firing for you? It does for me and that means it is seen as dirty, so if it's not for you, then whatever the difference is in our tests should give us a hint.

**Comment by litzinger** [comment]
I just tested in a different environment and the hook was triggered correctly and the Grid rows were properly deleted. I don't know what was happening in the original environment I was testing this on.

**Comment by robinsowell** [comment]
Hrm- interesting!  OK, I've got a user who is reporting the issue, so I'll see if I can get access and see what's going on.  I'll be cursious to see if the hook is triggered or not.

Thanks Brian. I'll update once I find something.

**Comment by robinsowell** [comment]
Well, it's not firing for this one and I suspect it's because it's not dirty.  

Here's a question- they've got drafts turned off and are just using it as multi-lingual.  Looking in the database, they still have a draft row.  So here's an example where I can't delete the row:

<img width="763" alt="Screen Shot 2019-06-19 at 12 04 44 PM" src="https://user-images.githubusercontent.com/1181219/59781765-7ce47580-928a-11e9-8366-02319ba63c3c.png">

It's a live site so I don't want to hack away too much- but do you think that could be a factor? And if I flip it to enable drafts just to test, is that going to be problematic?

**Comment by litzinger** [comment]
Publisher still creates the draft rows even if drafts are disabled b/c if they want to start using drafts at a future date, the data already exists. You could try deleting the draft row (shouldn't hurt anything) and see what happens (maybe save that row as an SQL insert to add it back when you're done testing).

**Comment by robinsowell** [comment]
Well- this is weird, but I think I nailed down the proximate cause.  In exp_channel_data_field_x, field_id_x is going in as an empty string instead of NULL.  Without publisher, those go in null.  

When I:
`
update exp_channel_data_field_1 set field_id_1 = NULL where field_id_1 = ''`

I can delete the only row. I even vaguely recall an environmental issue in how the null/empty string is handled that might explain why it's so quirky to replicate.

Now- as soon as I save, I get the empty string back in there, and I'm not sure where in publisher that happens.  Can you point me to the right spot? I need NULL instead of an empty string.  Once I tweak that, I'll clean up the existing data one more time and then see if that's got it fixed.

**Comment by litzinger** [comment]
That is odd. Publisher doesn't actually save blank strings or null values. All Publisher does is append a lang_id and status key to the save array in publisher/legacy/libraries/hooks/Publisher_grid_hooks.php->grid_save(). It never actually tries to set a blank or null value, or directly set the value of any column in a Grid field.

**Comment by robinsowell** [comment]
Somewhere it must be going astray. I noticed it when I uninstalled publisher.  I ended up with 2 entries in my grid (which makes sense) and I still couldn't delete the last one.  But I could delete any I made after publisher was deleted.  So I compared, and that was the difference.

With publisher installed, if I swap all the empty strings to null, I can delete the last one, but upon save, any other grid fields saved go back to empty string.

I can't spot where it's happening, though.  But I'll dig some more.

**Comment by bsabalaskey** [comment]
I too have this problem. I use a grid field for an optional featured video which takes a URL and optional graphic image (to replace YouTube default). When I try to delete that field in an article (which has quite a few fields), it never gets deleted, which reminds me of Hotel California. This is true for both saving a draft ('draft') or a published ('open') state. I am using EE 5.2.3 and Publisher 2.11.1. I do use Publisher for the draft feature but not for language translations. I tried running MySQL 5.7.27 on Ubuntu 18.04 LTS in both modes of STRICT_TRANS_TABLES or not. The only way to get around this is to close the original article and make a new copy without that grid field present. The authors and editors despise that of course.

**Comment by ballmannweber** [comment]
this problem is also still present with ee 5.2.6 and publisher 2.11.2 as reported in april.

**Comment by rhgarage** [comment]
@litzinger It looks like the likely culprit is in publisher/Service/Entry/Entry.php at line 497 (the cleanup routine).  It doesn't "respect" the NULL values and sets them to empty strings and saves that empty string to the channel_data instead of preserving the NULL, thereby scrambling the isDirty check later.

**Comment by litzinger** [comment]
> @litzinger It looks like the likely culprit is in publisher/Service/Entry/Entry.php at line 497 (the cleanup routine). It doesn't "respect" the NULL values and sets them to empty strings and saves that empty string to the channel_data instead of preserving the NULL, thereby scrambling the isDirty check later.

Interesting. Are you saying it is this conditional?

`if (isset($defaultData[$fieldName]) && $defaultData[$fieldName] != '') {
                $value = $defaultData[$fieldName];`

**Comment by rhgarage** [comment]
Yep.  NULL doesn't pass the isset() test so the else portion sets it to empty string.  I switched to

`if (is_null($defaultData[$fieldName]) || (isset($defaultData[$fieldName]) && $defaultData[$fieldName] != '')) {
                $value = $defaultData[$fieldName];`

**Comment by litzinger** [comment]
Neat, I'll test that out soon myself. Thanks for finding that.

**Comment by litzinger** [comment]
I can confirm that @rhgarage correctly identified the issue and his code change fixes it. Thanks, @rhgarage :)

Sorry, Robin!
