### ISSUE TITLE
Error with fluid field. The data is no longer displayed.

### ISSUE THREAD

**Issue by benya** [ExpressionEngine/ExpressionEngine#1930]
There is a fluid field to which 2 fields are attached: file grid and Rich Text Editor.

When I went into the settings of the fluid field and unchecked one of the fields https://prnt.sc/1Sbx78B2uWdN (without even saving these changes), the data was no longer displayed on the site and in the admin panel. When trying to edit a material, this data is no longer displayed. The previously filled fields are now empty.

How can we get this data back?

I downloaded the SQL file of the database, there is this data. How can you get them back?

**Comment by intoeetive** [comment]
Unfortunately we are only able to accept bug reports in English language. Please edit your post.

Please also note that we can't provide support on GitHub - we only use it for bug reports and feature requests. You can subscribe to one of our [support plans](https://expressionengine.com/support) or seek community support in Slack or in Forums.

**Comment by benya** [comment]
Hi @intoeetive 

Isn't this a mistake?

**Comment by intoeetive** [comment]
I think this might be expected behaviour - once the field is removed from Fluid, it should not be displayed anywhere (even if it contains data)

What is probably no correct is that the data stopped being displayed before field saving - we'll need to check that

What happens if you just select the field again in Fluid field settings? (make sure you have a backup)

**Comment by benya** [comment]
>What happens if you just select the field again in Fluid field settings? (make sure you have a backup)

Nothing has happened. The data is not displayed :(

**Comment by intoeetive** [comment]
I was able to replicate the issue and am working on a fix.

Thank you for the report!

**Comment by benya** [comment]
@intoeetive Tell me, the data that is lost can I return or not already?

**Comment by intoeetive** [comment]
If you don't have a backup, there is a "combined" represenation of data in `exp_channel_data_field_X` table, where X stands for Fluid field ID, which can be used to restore the data manually. It does not seem to be possible to restore with SQL or PHP script

**Comment by intoeetive** [comment]
Another thing you may try is loading revision (if revisions are enabled) or auto-saved version (if it exists)

**Comment by benya** [comment]
> Another thing you may try is loading revision (if revisions are enabled) or auto-saved version (if it exists)

when I try to do this I get an error:
https://prnt.sc/jgs0ELcUUtgS
