### ISSUE TITLE
Matrix 3.4.0 not placing files in the correct place.

### ISSUE THREAD

**Issue by jeremydye** [ExpressionEngine/ExpressionEngine#1939]
Having an issue where the content manager tried to upload a file into one column of a matrix field but doesn't get placed in the intended column.  It places the file in a completely different column.
![intended_place](https://user-images.githubusercontent.com/94487095/160611679-b3b9cae8-8fc9-4ffc-836d-9ce1f71118ac.jpg)
![where_it_ends_up](https://user-images.githubusercontent.com/94487095/160611704-e1314fba-bd39-4176-8823-6417d14da045.jpg)

EE v6.2.7
Matrix v3.4.0

**Comment by bakin1999** [comment]
Thank you for reporting this!

**Comment by jeremydye** [comment]
Is this still open?  I noticed you sent a solution but I get a 404.

**Comment by bakin1999** [comment]
Hey! I believe Robin has reached out and got you my fix for this. Let us know if not. This will also be addressed for next release of matrix, but you can use the fixes Robin sent out and let us know if that works out.

**Comment by jeremydye** [comment]
Yup, we got the fixes.  working on applying them now.  Thanks!

**Comment by jeremydye** [comment]
Is this a replacement file or a new file.  Where’s the best place to put it?

**Comment by jeremydye** [comment]
nevermind, Robin helped us.

**Comment by jeremydye** [comment]
We've applied the new file but it still doesn't seem to be working.

**Comment by jeremydye** [comment]
OK, I just created a new entry and it seems to work, but when updating an existing entry, I still get the problem.

**Comment by jeremydye** [comment]
OK, I deleted an existing entry to recreate it.  It was going fine until the 4th column.  Placed the file in there and it placed it at the end.
![Screen Shot 2022-03-30 at 12 10 15 PM](https://user-images.githubusercontent.com/94487095/160881560-5db9778e-1fed-417b-b53d-529bea6f472b.png)

**Comment by jeremydye** [comment]
Looks like we're good with the latest .js file.  Thanks!

**Comment by bakin1999** [comment]
Great to hear! Glad it is up and working now.
