### ISSUE TITLE
Entry Manager (5.2.2) should wrap (or truncate display of) long entry titles to preserve visibility of subsequent columns

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#194]
**Description of the problem**
This is a long-standing UI issue, I think. The Entry Manager (5.2.2) fails to handle long entry titles in a sensible way, causing subsequent columns to push beyond the visible section of the display. Scrolling to the right is available, but this is not intuitive for non-technical users, and in any event compromises the UI.

**Environment Details:**
 - Version: 5.2.2

**Possible Solution**
Applying a maximum width to the entry title column, and then allowing the entry title to wrap within that width, might be the best solution. A less-appealing alternative would be truncating the entry title, as displayed.

**Comment by jmathias** [comment]
Hi Paul, thanks for the feedback! This is a know issue, and we have some updates to the Entry Manager in the pipeline, and this issue is addressed in those updates!

**Comment by PaulBaileyAtChan** [comment]
Great stuff, thank you.

**Comment by ic360-com** [comment]
I hoping  this fix will apply to the Template edit boxes too.   :-)

**Comment by jmathias** [comment]
> I hoping this fix will apply to the Template edit boxes too. :-)

I'm not aware of an issue with template editing. Could you please open an issue with reproducible steps so I can look into it?

**Comment by ic360-com** [comment]
Apologies - it seems okay in EE5. I must be still coming across this one when editing older sites.
:-)

**Comment by Jordan-Ellis** [comment]
Fixed in EE6!
