### ISSUE TITLE
Add count indication of installed addons

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1944]
This is a fairly minor problem, but I think it has a very simple solution: Sometimes when I'm working with multiple installations of a site (local/remote), I lose track of whether the installed addons are in sync. (I know this is dumb.)

I feel like it would be useful, even when I'm not being dumb, to add a count of installed addons, like so:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/308752/160653885-45db0df7-d1b6-4ccb-9234-29ec32294f39.png">

It might be nice to be able to have a count right at your fingertips for a couple reasons, like when you prepare to upgrade a site, or when you're comparing two installations :)

**Comment by intoeetive** [comment]
@ajohnson FYI

**Comment by ajohnson** [comment]
@murtaugh @intoeetive That would come in handy.

Yuri, I can't remember if we already indicate when/if add-on updates are available via the Updates tab? If so, we should style this new "installed" count in the same way we're already styling the "updates" count.

If not, I have an idea for how we can style this.

**Comment by intoeetive** [comment]
yes we have counter on "updates" tab (is basically same that's on screenshot proposed)

**Comment by ajohnson** [comment]
@intoeetive OK, cool. In that case let's just use that same counter design on the Installed tab. 

I can add this to the Core team's issue queue, unless @murtaugh you've already coded this up and have a PR.

**Comment by murtaugh** [comment]
I don't have a PR, but I took a look at the current design just to see: 

<img width="270" alt="image" src="https://user-images.githubusercontent.com/308752/161090178-4024f849-e37c-4d17-ad5b-e2cedd5f7197.png">

Reusing an element is always ideal, but I've thought about this for a moment and there are a couple issues I see, first that this particular element is red, implying urgency, which is not what I would suggest for something that's communicating a very non-urgent piece of information. I'd update the default class (`tab-bar__tab-notification`) with neutral colors, for example `background: var(--ee-accent-light)` and `color: var(--ee-text-secondary)`:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/308752/161092943-f224766f-70c7-4d47-bac0-431aeea21a44.png">

Then I'd add a secondary class, such as `tab-notification-urgent` to apply the the "urgent" colors to the "Updates" tab. (I don't know enough about the class naming conventions to know what this secondary class *should* be called, so I don't think I should work on the PR.)

Second, sadly, it — understandably — wasn't designed to properly hold double-digit numbers.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/308752/161092807-03c56307-4770-4908-9048-4cbf881dafc5.png">

A minor CSS update to `tab-bar__tab-notification` could handle this, by updating it with `border-radius: 50px`, `width: auto`, and `padding: 0px 5px`:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/308752/161097085-7c0a0fe4-dd01-4e55-939c-b59269931891.png">

**Comment by robsonsobral** [comment]
(The pill shape can be achieved using a `border-radius` greater than possible. For example, `border-radius: 999em;`.)

**Comment by ajohnson** [comment]
@murtaugh Yes indeed, didn't realize a red beacon was being used for Updates. Definitely would not be appropriate for the Installed count.

I'll add this to our issue queue and we'll get it implemented for a future release. Thanks!
