### ISSUE TITLE
Shared Form View: Bug in EE5 results in inconsistent behaviour from same code between EE5 and EE6

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#1960]
**Description of the problem**
Code in the file `ExpressionEngine/View/_shared/form/fieldset.php` was changed between EE5 and EE6.  
In EE5 there is this code beginning line 28 of that file:
```
// Any fields required?
foreach ($setting['fields'] as $field_name => $field)
{
	if (isset($field['required']) && $field['required'] == TRUE)
	{
		$fieldset_classes .= ' fieldset-required';
		break;
	}
}
```

In EE6 the equivalent block of code traps for non-set array variables:
```
// Any fields required?
if (isset($setting['fields']) && !empty($setting['fields'])) {
    foreach ($setting['fields'] as $field_name => $field) {
        if (isset($field['required']) && $field['required'] == true) {
            $fieldset_classes .= ' fieldset-required';

            break;
        }
    }
}
```

As a result it is possible to have mcp definitions that 'work' in EE6 fail noisily in EE5; any element definition that does not include a `fields` section will fail in EE5 with a raft of inline Errors and Warnings about `$setting['fields']` not being set and the `foreach` being given duff data.

**Possible Solution**
It is possible to work-around this issue by adding a 'hidden' type field definition to each element affected, but this is undocumented (and is probably quite difficult to document clearly).

A better solution would be to update the shared form view in EE5 to include the same trap for unset or empty `$setting['fields']` values.

**Comment by intoeetive** [comment]
Since EE5 has reached it's end of life, I am closing this issue
