### ISSUE TITLE
PHP warning when using native Markdown typography plug-in

### ISSUE THREAD

**Issue by nathanpitman** [ExpressionEngine/ExpressionEngine#197]
**Description of the problem**
I'm using the native EE3.x Markdown plug-in (2.0.0) as a field format for a text formatting choice for a textarea field. This works however it generates a warning in the typography library as follows:

```
Warning
time() expects exactly 0 parameters, 1 given
ee/legacy/libraries/Typography.php, line 940 hide details

Severity: E_WARNING
```

**How To Reproduce**

1. Create a channel called "Releases"
1. Create field within the channel called "release_body" which is a text area that uses the Markdown plug-in for text formatting
2. Create a channel entry which includes some markdown (bullets for example)
3. Load the template
4. See PHP warning at head of page

**Error Messages**

<pre><code>
Warning
time() expects exactly 0 parameters, 1 given
ee/legacy/libraries/Typography.php, line 940 hide details

Severity: E_WARNING
</code></pre>

**Screenshots / Videos / Template Code**

```
{exp:channel:entries
                        channel="releases"
                        dynamic="no"
                        disable="categories|member_data|relationships"
                        limit="10"
                        paginate="bottom"
                        }

                                    {release_body}

                    {/exp:channel:entries}
```

**Environment Details:**
 - Version: 3.5.17
 - PHP Version: 7.3.1
 - MySQL Version: 5.7.25
 - OS: macOS
 - Web Server: MAMP

**Possible Solution**
Removing the zero from the `time` function at line 940 in the Typography library as follows resolve the warning:

```
$this->quote_marker = md5(time() . 'quote_marker');
```

**Comment by scbarber** [comment]
This was already done in eb0b70ac3c8650dda3181fcb15ea648e694d8f54.

**Comment by nathanpitman** [comment]
Thanks, I'm on EE3.x at the mo so I'll patch manually. :)
