### ISSUE TITLE
RTE Text Direction Removed IN EE6 

### ISSUE THREAD

**Issue by AhmadXotox** [ExpressionEngine/ExpressionEngine#1981]
hi all,

I'm not able to change the text direction in RTE fields in EE6 , however in EE5 i can do that.

Can you add text direction to RTE fields in EE6. 

Best Regards

**Comment by intoeetive** [comment]
If you set the EE language to RTE language (such as Arabic) the CKEditor text is changing the direction automatically.

However this does not happen with Redactor

(There is no official or complete language pack for Arabic, but the direction change can be achieved by just placing empty `arabic` folder under `system/user/languages`)
