### ISSUE TITLE
Templates with certain types of relationships  error array_slice(): Argument #2 ($offset) must be of type int, string given

### ISSUE THREAD

**Issue by aasun** [ExpressionEngine/ExpressionEngine#1994]
We have lots of different relationship fields.  All of them are limited to 1 child channel. However, we have 1 that has 2 child channels.  And when this field was called on a template, we got the PHP error:

array_slice(): Argument #2 ($offset) must be of type int, string given

We traced through code and found that this commit on line 80 is what changed from EE 6.2.7 to EE 6.3.0
https://github.com/ExpressionEngine/ExpressionEngine/commit/b106365d10b612d4ec6317ee44b5089ea01bc259

We changed that back to NULL and it corrected the issue.

We're not immeidately clear why this relationship field (from multiple child channels) caused the error and others did not.  (Too much of a deep dive for us! )

<img width="1294" alt="PNG image" src="https://user-images.githubusercontent.com/5115281/162851007-5f26b5b6-d0ea-4768-95a0-864e0ac777cb.png">
.

**Comment by intoeetive** [comment]
@aasun what's the template tag that you use for that relationship field?

**Comment by aasun** [comment]
It's a standard relationship tag.

The one thing that is different on this, is that since the children related entries that can be selected in the CP belong to one of 2 different channels, I have a conditional in here to manage some output based on that channel.

I do 4 different relationships in this site that are the same as this (different channels, though, and some slightly different HTML for displaying on templates).  The only difference is those other relationships are limited 1 channel.  This particular one is children from 2 channels.

`{vendors}
<a class="{if bloqs:parent:shortname == 'feat_vendors_slider_no_borders'}slide{if:else}article{/if}" href="{site_url}{if vendors:channel_id == '15'}venue{if:else}vendor{/if}/{vendors:url_title}" title="{vendors:title:attr_safe}">
	<div class="img">
		{vendors:vendor_thumbnail}
			<img src="{cdn_url}_images/utility/placeholder_2.3.png" alt="{vendors:title:attr_safe}" class="lazyLoad" data-lazyimg="{img:url:resize width='480' height='720' crop='true' scale_up='true'}" width="240" height="360">
		{/vendors:vendor_thumbnail}
	</div>
	<div class="text {if bloqs:parent:shortname == 'feat_vendors_slider_no_borders'}onImage{/if}">
		<div class="preHeader">{vendors:vendor_category limit="1"}{vendors:vendor_category:title}{/vendors:vendor_category}</div>
		<div class="subHeader">{vendors:title}</div>
		<div class="minorText ital">
		{if vendors:channel_id == "15"}
			{vendors:vendor_city}, {vendors:vendor_state}
		{if:else}
			{vendors:locations limit="1"}{vendors:locations:city}, {vendors:locations:state}{/vendors:locations}
		{/if}
		</div>
	</div>
</a>
{/vendors}
`

**Comment by aasun** [comment]
Hmm. that code snippet didn't format how I wanted.. it removed line breaks and tab indents..
