### ISSUE TITLE
Installer complains that user theme directory is not writable

### ISSUE THREAD

**Issue by bjornbjorn** [ExpressionEngine/ExpressionEngine#20]
When leaving the "Install default theme" checkbox unchecked the installer still complains about the user theme directory not being writable:

![Image](https://i.imgur.com/ZdoByW9.png)

The installer is not going to write anything to this directory in this case, so I think one should be able to install EE w/o having it fail.

If this directory being writable is indeed a requirement for the installation of EE it would be better if this was verified at an earlier stage (where the config.php / database.php checks are).

**Comment by kevincupp** [comment]
Thanks, @bjornbjorn, we've got a fix for this we'll get merged in soon.
