### ISSUE TITLE
Cookie consent form does not delete cookies

### ISSUE THREAD

**Issue by Havsvik** [ExpressionEngine/ExpressionEngine#201]
Hi

I've created a cookie form that declines all cookie consents

``` 
{!-- Disable cookies form --}
  {exp:consent:form form_id="cookieConsentFormNo" return="{current_path}"}
      {consents}
          <input type="hidden" name="{consent_short_name}" value="n">
      {/consents}
  {/exp:consent:form}
```

The problem is that "Functionality" cookies like "exp_tracker" aren't deleted when submitting the form, even though the form is submitted successfully.

Since I can't delete these HttpOnly cookies with javascript, is there any other way to delete them?

/Oskar

**Comment by derekjones** [comment]
If the user consent began with functionality cookies enabled, the cookie will be set, but will not be unset by changing the consent. The cookie won't further be set and used, however, which you should be able to confirm by manually deleting the cookie in your browser and seeing that it does not come back.

**Comment by Havsvik** [comment]
Alright, I wasn't sure if the cookies were still being used behind the scenes even though the user declined them (after accepting them). The EU cookie laws are quite strict, so I just wanted them to be removed just in case :)

Thanks for the quick answer!
