### ISSUE TITLE
Empty Grid Fields and Conditionals

### ISSUE THREAD

**Issue by cjgyt** [ExpressionEngine/ExpressionEngine#2011]
I've been trying to build two conditionals with a File Grid field (which itself just has a field fieldtype in it, nothing else). One of the conditionals is set up to show a slider if one or more images are present, and the other is supposed to show a fallback image if none are present in the File Grid field. I've run into a glitch: if a file was present and removed, ExpressionEngine still sees the field as having content.

As an example, here:
`{if guided_experience_slider !=""}<div class="gallery"><div class="carousel" data-flickity='{ "lazyLoad": true, "percentPosition": false }'>{guided_experience_slider}<img src="{site_url}assets/images/placeholder/placeholder_slider.png" data-flickity-lazyload="{guided_experience_slider:file:experience_slider_scale}"  alt="{title} experience image" />{/guided_experience_slider}</div></div>{/if}`

With an entry where there is nothing linked in the File Grid field but there once was, the gallery displays but is empty.

**Comment by intoeetive** [comment]
In this code, you're checking whether `guided_experience_slider` (Grid field) evaluates to empty string - which is not the case if Grid was manipulated indeed.

Instead, you should check whether it's not empty, e.g. `guided_experience_slider:total_rows`

**Comment by cjgyt** [comment]
Thank you! I've resolved the issue another way. Very much appreciate your help!
