### ISSUE TITLE
Comments not added to Spam Trap when changing their status to SPAM

### ISSUE THREAD

**Issue by hopDrew** [ExpressionEngine/ExpressionEngine#2017]
**Description of the problem**
EE Spam is detecting that there are comments in moderation that do not exist.
This is a bit of a shot in the dark considering that there is no supporting information that I was able to find.

- Developer console provided no feedback
- I was unable to find a log that provided any information.

**How To Reproduce**
N/A

**Error Messages**
See Below

**Screenshots / Videos / Template Code**
![image](https://user-images.githubusercontent.com/102068794/163450958-588b52e5-0acb-4a0f-9070-bfc179a199c8.png)

![image](https://user-images.githubusercontent.com/102068794/163472906-753d6b40-d758-404a-b669-1ecd59c3a96a.png)

**Environment Details:**
 - Version: 6.2.2
 - PHP Version 7.2.34
 - MySQL Version 5.0.12
 - OS: Linux
 - Web Server: Apache

**Possible Solution**
N/A

**Additional context**
N/A

**Comment by intoeetive** [comment]
@hopDrew is that what you seen when you click "need moderation" link or when vising the Spam addon directly from Add-ons page?

Also, any chance someone else cleared up spam que while you were browsing? :)

**Comment by hopDrew** [comment]
@intoeetive, this happens when clicking on need moderation.

This message has been displaying for a while now and there were no other users signed in at the time I recorded the screenshot.
