### ISSUE TITLE
text describing channels in CP is grammatically awkward possibly incorrect.  

### ISSUE THREAD

**Issue by bmackenty** [ExpressionEngine/ExpressionEngine#203]
**Description of the problem**
The text describing channels in CP is grammatically awkward possibly incorrect.

"Channels are used to store content for your website. For example, if you want a Blog. You would first need to create a Channel to store the entries. Think of them as folders, or directories."

The sentence "For example, if you want a Blog." isn't a sentence. 

**How To Reproduce**
1. Login to control panel version 5.2.2
2. look at the default text describing channels. 

**Environment Details:**
 - Version: 5.2.2

**Possible Solution**
I looked here: https://github.com/EllisLab/EE-Language-English/tree/master/user/language/english but I couldn't find the text. 

I think text might be better:
"Channels are used to store content for your website. For example, if you want a blog you would first need to create a Channel to store the entries. Think of channels as folders or directories."

**Comment by bmackenty** [comment]
Created pull request with suggested changes. https://github.com/EllisLab/EE-Language-English/pull/9/commits/ade89004dbd855ea3d00bb1c7a7a24717061609b

**Comment by derekjones** [comment]
Hey thanks for the suggestion and pull request Bill! That repo is actually just a reflection of *this* one to make editing language packs easier for non-English users. The file you're looking for, and the target of the pull request should be [this file](https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/system/ee/legacy/language/english/homepage_lang.php). Mind making your Pull Request there? Thanks!

**Comment by bmackenty** [comment]
thank you!
