### ISSUE TITLE
 It still says there's a "new version".

### ISSUE THREAD

**Issue by bytebaby** [ExpressionEngine/ExpressionEngine#2037]
After updating to version 6.3.2, the following error message appears when I click on the button for "Automatically check for new version" under "Settings"

{"isVitalUpdate":false,"isMajorUpdate":false,"newVersionMarkup":"<b><b>6<\/b>.3.2<\/b><em>Build: 15-4-2022<\/em>\n"}

Problem: Even though I've updated to version 6.3.2, it still says there's a "new version".

<img width="343" alt="image" src="https://user-images.githubusercontent.com/21154749/164452569-14a662ef-5a2c-4369-b5e6-e6e4d1eb82a6.png">

EE 6.3.2
PHP 7.4
defakto.org

Thanks

**Comment by robinsowell** [comment]
I'm thinking this was probably a cache issue.  But if it is STILL showing an update available while you know you're on the latest, let me know.  First thing I'd do is go in via ftp and manually delete system/user/cache/current_version and see if that matters.
