### ISSUE TITLE
Very irritating usability issue when uploading images

### ISSUE THREAD

**Issue by bytebaby** [ExpressionEngine/ExpressionEngine#2038]
If a customer wants to upload an image, then he has to scroll down (if many images have already been uploaded) to reach the "Upload new file" button. See screen:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/21154749/164454302-62a77d2f-da2d-42ec-a2f2-1668d6d9fe7b.png">

If he then clicks on the button, the modal for uploading has disappeared, see screen:

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/21154749/164454104-090745b0-ce6a-429e-976d-a5ef40fedde9.png">

An inexperienced editor doesn't know how to proceed. This always irritates my customers! The solution is simple, the editor just has to scroll back up. But how should he know that? I would be very happy if the problem would be solved soon.

EE 6xx
PHP 7xx
Browser: Chrome, Firefox, Safari

Thanks

**Comment by mcfarlandonline** [comment]
Agreed! This issue is also mentioned here: https://github.com/ExpressionEngine/ExpressionEngine/issues/1679

**Comment by intoeetive** [comment]
With the release of ExpressionEngine 7 and the new File Manager there is no intermediate screen for upload, so this is not relevant anymore.
