### ISSUE TITLE
Improve differentiation between selected and unselected "selectable buttons" 

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2041]
**Is your feature request related to a problem? Please describe.**
Currently it is difficult to see whether a selectable button has been selected or not... 
Here is an example:
![image](https://user-images.githubusercontent.com/13821249/164951820-c33fe3a1-0603-46cc-9ae0-cc392300a91d.png)

**Describe the solution you'd like**
Revision to the button CSS to make the selected status more strongly differentiated from the unselected state.

**Describe alternatives you've considered**
Using some other control... but would prefer not to.

**Teachability, Documentation, Adoption, Migration Strategy**
No wider implications

- [ ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
@ajohnson FYI

**Comment by ajohnson** [comment]
This is currently using EE's default active button state for selected buttons. But we can probably add extra emphasis to that state targeted at just this fieldtype. I'll put this in the Core team's queue. Thanks!
