### ISSUE TITLE
EE Pro Front End Edit CSS conflict

### ISSUE THREAD

**Issue by meatpaste** [ExpressionEngine/ExpressionEngine#2045]
My website has some CSS, which causes the front-end editor buttons to fall of the bottom of the screen and become unuseable. I think the CSS in Pro should be specific enough for this not to happen or make use of [shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) (recommended by 'mithra62' on the slack channel!)

The CSS: 

`footer>div {
    background: #96d5ea;
    padding-top: 40px;
    padding-bottom: 20px;
}`

**Comment by intoeetive** [comment]
@Yulyaswan can you check if this is still relevant?

**Comment by Yulyaswan** [comment]
I can't reproduce anything like this.
most of the pro elements have inline styles or use specific classes

**Comment by Yulyaswan** [comment]
@meatpaste if you still have this problem could you please provide more specific info, maybe a screenshot?
