### ISSUE TITLE
name attribute replaced with filed name in grid field name with fluid

### ISSUE THREAD

**Issue by chenchen2003** [ExpressionEngine/ExpressionEngine#2047]
**Description of the problem**

When rendering grid field in the publish form, the namespaceInputs function replace name attribute of the content as well.
example:
 <a name="link-name">example</a>
replaced with <a name name="field1[field2][link-name]">example</a>
If saving multiple times without removing, it becomes <a name name="field1[field2][field1][field2][field1][field2][link-name]">example</a>

**How To Reproduce**

**Error Messages**

<pre><code>

</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 5.4.2
 - PHP Version 7.4
 - MySQL Version [e.g. 5.7]
 - OS: [e.g. Linux, macOS, Windows]
 - Web Server: nginx

**Comment by intoeetive** [comment]
@chenchen2003 looks like some error message / images did not come though.

Also can you specify in more details, what is the template code that you are using and what is the output that you get. It's not really clear from your post as it is now

**Comment by chenchen2003** [comment]
![Screen Shot 2022-04-22 at 5 43 19 PM 64](https://user-images.githubusercontent.com/2659954/165360958-9aa0bf8b-720f-4445-9cc4-a1784168c462.jpg)
The content was an anchor link and when editing the page, it replace the name attribute in <a name="coastal-region" with field_id_7[fields][field_id-5......[row_id_17].

**Comment by intoeetive** [comment]
This seems to be same as https://github.com/ExpressionEngine/ExpressionEngine/issues/185
Closing as duplicate
