### ISSUE TITLE
Error on front-end when image is added to an additional file field column in File Grid field

### ISSUE THREAD

**Issue by 5BYFIVE** [ExpressionEngine/ExpressionEngine#2048]
Site Running on development server
EE version 6.3.2
PHP 7.4.16

I'm getting this error on the front-end on a page that is displaying content from a File Grid field. The file grid field has the "File" column, a "Title" column, and a File "Thumbnail" column. If the image is removed from the Thumbnail file column, the error disappears on the front-end. Maybe an issue having 2 file fields in a file grid field?

`Notice
Array to string conversion
ee/legacy/libraries/Grid_parser.php, line 497

Severity: E_NOTICE`

This page shows no errors on the live site running EE 5.4.3 with PHP 7.1.33. The site was copied to a development server where is was updated and the same page is getting the error.

![Screen Shot 2022-04-26 at 10 53 46 AM](https://user-images.githubusercontent.com/31897342/165380670-55bb4adf-a299-40a9-9bca-9cc5b8caaf08.png)

**Comment by intoeetive** [comment]
@5BYFIVE I wasn't able to replicate it so far.
Any chance you can `var_dump` what you have in `Grid_parser.php, line 497`?

**Comment by 5BYFIVE** [comment]
@intoeetive I apologize, I'm no PHP developer, can you show me what and where to add to that section to get an output?

 // Finally, do the replacement
            $grid_row = str_replace(
                $match[0],
                (string) $replace_data,    /// Line 497
                $grid_row
            );

**Comment by 5BYFIVE** [comment]
I added `var_dump($replace_data);` a little lower down the file and got a big output, not sure if this is what you are looking for...

Severity: E_NOTICE
array(34) { ["file_id"]=> int(124) ["site_id"]=> int(1) ["title"]=> string(25) "disinfectant-types@1x.jpg" ["upload_location_id"]=> int(1) ["mime_type"]=> string(10) "image/jpeg" ["file_name"]=> string(27) "disinfectant-types%401x.jpg" ["file_size"]=> int(23337) ["description"]=> string(0) "" ["credit"]=> string(0) "" ["location"]=> string(0) "" ["uploaded_by_member_id"]=> int(14) ["upload_date"]=> int(1607652728) ["modified_by_member_id"]=> int(14) ["modified_date"]=> int(1607652728) ["file_hw_original"]=> string(7) "451 348" ["model_object"]=> object(ExpressionEngine\Model\File\File)#4825 (27) { ["file_id"]=> int(124) ["site_id"]=> int(1) ["title"]=> string(25) "disinfectant-types@1x.jpg" ["upload_location_id"]=> int(1) ["mime_type"]=> string(10) "image/jpeg" ["file_name"]=> string(25) "disinfectant-types@1x.jpg" ["file_size"]=> int(23337) ["description"]=> string(0) "" ["credit"]=> string(0) "" ["location"]=> string(0) "" ["uploaded_by_member_id"]=> int(14) ["upload_date"]=> int(1607652728) ["modified_by_member_id"]=> int(14) ["modified_date"]=> int(1607652728) ["file_hw_original"]=> string(7) "451 348" ["_name"]=> string(7) "ee:File" ["_new"]=> bool(false) ["_validator"]=> object(ExpressionEngine\Service\Validation\Validator)#4841 (3) { ["rules":protected]=> array(0) { } ["custom":protected]=> array(0) { } ["failed":protected]=> array(0) { } } ["_in_hook"]=> array(0) { } ["_associations"]=> array(5) { ["Site"]=> object(ExpressionEngine\Service\Model\Association\ToOne)#4836 (6) { ["booted"]=> bool(false) ["loaded"]=> bool(false) ["saving"]=> bool(false) ["inverse_name"]=> NULL ["related"]=> NULL ["foreign_key"]=> string(7) "site_id" } ["UploadDestination"]=> object(ExpressionEngine\Service\Model\Association\ToOne)#4837 (9) { ["booted"]=> bool(true) ["loaded"]=> bool(true) ["saving"]=> bool(false) ["inverse_name"]=> NULL ["diff"]=> object(ExpressionEngine\Service\Model\Association\Diff)#4851 (5) { ["parent":"ExpressionEngine\Service\Model\Association\Diff":private]=> *RECURSION* ["relation":"ExpressionEngine\Service\Model\Association\Diff":private]=> object(ExpressionEngine\Service\Model\Relation\BelongsTo)#1817 (13) { ["from"]=> object(ExpressionEngine\Service\Model\MetaDataReader)#1815 (3) { ["name":protected]=> string(7) "ee:File" ["class":protected]=> string(32) "ExpressionEngine\Model\File\File" ["tables":protected]=> NULL } ["to"]=> object(ExpressionEngine\Service\Model\MetaDataReader)#1024 (3) { ["name":protected]=> string(20) "ee:UploadDestination" ["class":protected]=> string(45) "ExpressionEngine\Model\File\UploadDestination" ["tables":protected]=> array(1) { ["upload_prefs"]=> array(19) { [0]=> string(2) "id" [1]=> string(7) "site_id" [2]=> string(4) "name" [3]=> string(11) "server_path" [4]=> string(3) "url" [5]=> string(13) "allowed_types" [6]=> string(18) "default_modal_view" [7]=> string(8) "max_size" [8]=> string(10) "max_height" [9]=> string(9) "max_width" [10]=> string(10) "properties" [11]=> string(10) "pre_format" [12]=> string(11) "post_format" [13]=> string(15) "file_properties" [14]=> string(15) "file_pre_format" [15]=> string(16) "file_post_format" [16]=> string(9) "cat_group" [17]=> string(14) "batch_location" [18]=> string(9) "module_id" } } } ["name"]=> string(17) "UploadDestination" ["is_weak"]=> bool(false) ["inverse"]=> NULL ["inverse_info"]=> NULL ["to_table"]=> string(12) "upload_prefs" ["from_table"]=> string(5) "files" ["from_key"]=> string(18) "upload_location_id" ["to_key"]=> string(2) "id" ["key_tuple"]=> array(2) { [0]=> string(18) "upload_location_id" [1]=> string(2) "id" } ["from_primary_key"]=> string(7) "file_id" ["to_primary_key"]=> string(2) "id" } ["added":protected]=> array(0) { } ["removed":protected]=> array(0) { } ["was_set":protected]=> bool(false) } ["model"]=> *RECURSION* ["related"]=> object(ExpressionEngine\Model\File\UploadDestination)#4842 (32) { ["_property_overrides"]=> array(0) { } ["id"]=> int(1) ["site_id"]=> int(1) ["name"]=> string(11) "Main Upload" ["server_path"]=> object(ExpressionEngine\Model\File\Column\LocalPath)#4850 (3) { ["files":protected]=> NULL ["path":protected]=> string(27) "{base_path}/images/uploads/" ["data":protected]=> *RECURSION* } ["url"]=> string(26) "{base_url}/images/uploads/" ["allowed_types"]=> string(3) "all" ["default_modal_view"]=> string(4) "list" ["max_size"]=> string(0) "" ["max_height"]=> string(0) "" ["max_width"]=> string(0) "" ["properties"]=> string(0) "" ["pre_format"]=> string(0) "" ["post_format"]=> string(0) "" ["file_properties"]=> string(0) "" ["file_pre_format"]=> string(0) "" ["file_post_format"]=> string(0) "" ["cat_group"]=> string(0) "" ["batch_location"]=> NULL ["module_id"]=> int(0) ["_name"]=> string(20) "ee:UploadDestination" ["_new"]=> bool(false) ["_validator"]=> object(ExpressionEngine\Service\Validation\Validator)#4849 (3) { ["rules":protected]=> array(0) { } ["custom":protected]=> array(0) { } ["failed":protected]=> array(0) { } } ["_in_hook"]=> array(0) { } ["_associations"]=> array(5) { ["Site"]=> object(ExpressionEngine\Service\Model\Association\ToOne)#4844 (6) { ["booted"]=> bool(false) ["loaded"]=> bool(false) ["saving"]=> bool(false) ["inverse_name"]=> NULL ["related"]=> NULL ["foreign_key"]=> string(7) "site_id" } ["Roles"]=> object(ExpressionEngine\Service\Model\Association\ToMany)#4845 (6) { ["booted"]=> bool(false) ["loaded"]=> bool(false) ["saving"]=> bool(false) ["inverse_name"]=> NULL ["related"]=> NULL ["foreign_key"]=> string(2) "id" } ["Module"]=> object(ExpressionEngine\Service\Model\Association\ToOne)#4846 (6) { ["booted"]=> bool(false) ["loaded"]=> bool(false) ["saving"]=> bool(false) ["inverse_name"]=> NULL ["related"]=> NULL ["foreign_key"]=> string(9) "module_id" } ["Files"]=> object(ExpressionEngine\Service\Model\Association\ToMany)#4847 (6) { ["booted"]=> bool(false) ["loaded"]=> bool(false) ["saving"]=> bool(false) ["inverse_name"]=> NULL ["related"]=> NULL ["foreign_key"]=> string(2) "id" } ["FileDimensions"]=> object(ExpressionEngine\Service\Model\Association\ToMany)#4848 (6) { ["booted"]=> bool(false) ["loaded"]=> bool(false) ["saving"]=> bool(false) ["inverse_name"]=> NULL ["related"]=> NULL ["foreign_key"]=> string(2) "id" } } ["_property_types"]=> array(19) { ["id"]=> NULL ["site_id"]=> NULL ["name"]=> NULL ["server_path"]=> object(ExpressionEngine\Model\File\Column\LocalPath)#4850 (3) { ["files":protected]=> NULL ["path":protected]=> string(27) "{base_path}/images/uploads/" ["data":protected]=> *RECURSION* } ["url"]=> NULL ["allowed_types"]=> NULL ["default_modal_view"]=> NULL ["max_size"]=> NULL ["max_height"]=> NULL ["max_width"]=> NULL ["properties"]=> NULL ["pre_format"]=> NULL ["post_format"]=> NULL ["file_properties"]=> NULL ["file_pre_format"]=> NULL ["file_post_format"]=> NULL ["cat_group"]=> NULL ["batch_location"]=> NULL ["module_id"]=> NULL } ["_foreign_keys"]=> array(2) { ["site_id"]=> string(4) "Site" ["module_id"]=> string(6) "Module" } ["_has_saved"]=> bool(false) ["_event"]=> object(ExpressionEngine\Service\Event\Emitter)#4843 (2) { ["events":protected]=> array(0) { } ["subscribers":protected]=> array(0) { } } ["_filters"]=> array(4) { ["get"]=> array(1) { [0]=> array(2) { [0]=> string(4) "this" [1]=> string(8) "typedGet" } } ["set"]=> array(1) { [0]=> array(2) { [0]=> string(4) "this" [1]=> string(22) "typedSetAndForeignKeys" } } ["fill"]=> array(1) { [0]=> array(2) { [0]=> string(4) "this" [1]=> string(9) "typedLoad" } } ["store"]=> array(1) { [0]=> array(2) { [0]=> string(4) "this" [1]=> string(10) "typedStore" } } } ["_clean_backups"]=> array(0) { } ["_mixin_manager"]=> NULL } ["relation"]=> object(ExpressionEngine\Service\Model\Relation\BelongsTo)#1817 (13) { ["from"]=> object(ExpressionEngine\Service\Model\MetaDataReader)#1815 (3) { ["name":protected]=> string(7) "ee:File" ["class":protected]=> string(32) "ExpressionEngine\Model\File\File" ["tables":protected]=> NULL } ["to"]=> object(ExpressionEngine\Service\Model\MetaDataReader)#1024 (3) { ["name":protected]=> string(20) "ee:UploadDestination" ["class":protected]=> string(45) "ExpressionEngine\Model\File\UploadDestination" ["tables":protected]=> array(1) { ["upload_prefs"]=> array(19) { [0]=> string(2) "id" [1]=> string(7) "site_id" [2]=> string(4) "name" [3]=> string(11) "server_path" [4]=> string(3) "url" [5]=> string(13) "allowed_types" [6]=> string(18) "default_modal_view" [7]=> string(8) "max_size" [8]=> string(10) "max_height" [9]=> string(9) "max_width" [10]=> string(10) "properties" [11]=> string(10) "pre_format" [12]=> string(11) "post_format" [13]=> string(15) "file_properties" [14]=> string(15) "file_pre_format" [15]=> string(16) "file_post_format" [16]=> string(9) "cat_group" [17]=> string(14) "batch_location" [18]=> string(9) "module_id" } } } ["name"]=> string(17) "UploadDestination" ["is_weak"]=> bool(false) ["inverse"]=> NULL ["inverse_info"]=> NULL ["to_table"]=> string(12) "upload_prefs" ["from_table"]=> string(5) "files" ["from_key"]=> string(18) "upload_location_id" ["to_key"]=> string(2) "id" ["key_tuple"]=> array(2) { [0]=> string(18) "upload_location_id" [1]=> string(2) "id" } ["from_primary_key"]=> string(7) "file_id" ["to_primary_key"]=> string(2) "id" } ["foreign_key"]=> string(18) "upload_location_id" } ["UploadAuthor"]=> object(ExpressionEngine\Service\Model\Association\ToOne)#4838 (6) { ["booted"]=> bool(false) ["loaded"]=> bool(false) ["saving"]=> bool(false) ["inverse_name"]=> NULL ["related"]=> NULL ["foreign_key"]=> string(21) "uploaded_by_member_id" } ["ModifyAuthor"]=> object(ExpressionEngine\Service\Model\Association\ToOne)#4839 (6) { ["booted"]=> bool(false) ["loaded"]=> bool(false) ["saving"]=> bool(false) ["inverse_name"]=> NULL ["related"]=> NULL ["foreign_key"]=> string(21) "modified_by_member_id" } ["Categories"]=> object(ExpressionEngine\Service\Model\Association\ToMany)#4840 (6) { ["booted"]=> bool(false) ["loaded"]=> bool(false) ["saving"]=> bool(false) ["inverse_name"]=> NULL ["related"]=> NULL ["foreign_key"]=> string(7) "file_id" } } ["_property_types"]=> array(15) { ["file_id"]=> NULL ["site_id"]=> NULL ["title"]=> NULL ["upload_location_id"]=> NULL ["mime_type"]=> NULL ["file_name"]=> NULL ["file_size"]=> NULL ["description"]=> NULL ["credit"]=> NULL ["location"]=> NULL ["uploaded_by_member_id"]=> NULL ["upload_date"]=> NULL ["modified_by_member_id"]=> NULL ["modified_date"]=> NULL ["file_hw_original"]=> NULL } ["_foreign_keys"]=> array(4) { ["site_id"]=> string(4) "Site" ["upload_location_id"]=> string(17) "UploadDestination" ["uploaded_by_member_id"]=> string(12) "UploadAuthor" ["modified_by_member_id"]=> string(12) "ModifyAuthor" } ["_has_saved"]=> bool(false) ["_event"]=> object(ExpressionEngine\Service\Event\Emitter)#4832 (2) { ["events":protected]=> array(2) { ["beforeDelete"]=> array(1) { ["00000000632eed7f0000000036bc46b4"]=> object(Closure)#4834 (2) { ["static"]=> array(3) { ["trigger"]=> object(Closure)#4830 (3) { ["static"]=> array(1) { ["in_hook"]=> array(0) { } } ["this"]=> *RECURSION* ["parameter"]=> array(1) { ["$name"]=> string(10) "" } } ["hook"]=> string(18) "before_file_delete" ["that"]=> *RECURSION* } ["this"]=> *RECURSION* } } ["afterDelete"]=> array(1) { ["00000000632eed7e0000000036bc46b4"]=> object(Closure)#4835 (2) { ["static"]=> array(3) { ["trigger"]=> object(Closure)#4830 (3) { ["static"]=> array(1) { ["in_hook"]=> array(0) { } } ["this"]=> *RECURSION* ["parameter"]=> array(1) { ["$name"]=> string(10) "" } } ["hook"]=> string(17) "after_file_delete" ["that"]=> *RECURSION* } ["this"]=> *RECURSION* } } } ["subscribers":protected]=> array(0) { } } ["_filters"]=> array(4) { ["get"]=> array(1) { [0]=> array(2) { [0]=> string(4) "this" [1]=> string(8) "typedGet" } } ["set"]=> array(1) { [0]=> array(2) { [0]=> string(4) "this" [1]=> string(22) "typedSetAndForeignKeys" } } ["fill"]=> array(1) { [0]=> array(2) { [0]=> string(4) "this" [1]=> string(9) "typedLoad" } } ["store"]=> array(1) { [0]=> array(2) { [0]=> string(4) "this" [1]=> string(10) "typedStore" } } } ["_clean_backups"]=> array(0) { } ["_mixin_manager"]=> NULL } ["raw_output"]=> string(36) "{filedir_1}disinfectant-types@1x.jpg" ["raw_content"]=> string(36) "{filedir_1}disinfectant-types@1x.jpg" ["path"]=> string(45) "http://4m.5byfivecreative.com/images/uploads/" ["extension"]=> string(3) "jpg" ["filename"]=> string(23) "disinfectant-types%401x" ["url"]=> string(72) "http://4m.5byfivecreative.com/images/uploads/disinfectant-types%401x.jpg" ["width"]=> string(3) "348" ["height"]=> string(3) "451" ["image_pre_format"]=> string(0) "" ["image_post_format"]=> string(0) "" ["file_pre_format"]=> string(0) "" ["file_post_format"]=> string(0) "" ["image_properties"]=> string(0) "" ["file_properties"]=> string(0) "" ["file_size:human"]=> string(35) "23KB" ["file_size:human_long"]=> string(12) "23 kilobytes" ["directory_id"]=> int(1) ["directory_title"]=> string(11) "Main Upload" }

**Comment by intoeetive** [comment]
Thank you. I will try to replicate this once again. Can you also post the template code that you use to display this field on front-end?

**Comment by 5BYFIVE** [comment]
yes, thanks!

        <div class="sidebar">
            {if document_thumbnail}
            <div class="sidebar_chunk">
                {document_thumbnail}
                    <h2>{document_thumbnail:title}</h2>
                    <a target="_blank" href="{document_thumbnail:file}">
                        <img src="{document_thumbnail:thumbnail}" alt="{document_thumbnail:thumbnail:title}" />
                        <span class="view-here">View Here</span>
                    </a>
                {/document_thumbnail}
            </div>
            {/if}
        </div>

**Comment by intoeetive** [comment]
@5BYFIVE `:title` is not available as modifier on file fields; instead it is available as variable when field is being used as tag pair.
So your code should look like
```
{document_thumbnail:thumbnail}<img src="{url}" alt="{title}" />{/document_thumbnail:thumbnail}
```
