### ISSUE TITLE
Toggle control in fluid field can trigger deprecation warning due to php changes in php 7.3 and later

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2049]
Since php 7.3 passing a integer as a needle to the [strpos()](http://www.php.net/manual/en/function.strpos.php) method has been deprecated.

If you add a 'toggle' field to a channel and include this within a fluid field, the value given to the field to indicate selected status is the integer value 1.

During the parsing of a template that looks for this value the integer value is passed to the `strpos()` method and the deprecation warning is triggered.

## Example

Suppose a field `include_a_contact_form` is included in a fluid field `fcf`.  You might expect to see something like this in the template processing the fluid field:
```
{fcf} // evaluate the fluid field
    {fcf:include_a_contact_form} // look for instances where the "include_a_contact_form" variable has been chosen 
        ... do something ... 
    {/fcf:include_a_contact_form}
{/fcf}
```
During the parsing of this template, when evaluating the fluid field a value for `fcf:include_a_contact_form` (which evaluates to integer 1 when the slider is in the selected state) is passed to the `EE_Channel_entries_parser` class; during that class's evaluation, at line 305 it hits this test:
```
            //  Parse individual variable tags
            foreach ($singles as $key => $val) {
                if (strpos($tagdata, $key) === false) {
                    continue;
                }
```
The value of `fcf:include_a_contact_form` has been assigned to `$key` at this point, and so results in the integer value being passed to strpos and so the deprecation warning is triggered.

Note: In theory this deprecation error should trigger a full php error in php 8 and above, but currently it appears that it continues to simply trigger the deprecation error. However to ensure php8 compatibility it is probably something to address sooner rather than later.

// Using php 7.4.28 and / or php 8.0.17 with EE 6.3.2

**Comment by intoeetive** [comment]
@jcogs-design I'm unable to replicate this on my tests. Is there anything else that needs to be in the template? Or an extension installed etc.

**Comment by jcogs-design** [comment]
@intoeetive Thanks for looking. Not sure about add-ons etc - it is a fairly simple site it is happening on.  The site has been updated a few times so maybe some legacy stuff lurking that is influencing. I will dig into again and see if I can work out whether it is an anomalous set up.

**Comment by robinsowell** [comment]
@jcogs-design, if you get a chance, can you include the stack trace when you post back?  Wonder if that might reveal something.  Seems like it should have been easy to replicate.  Oh- and if you can, test on 6.3.4 as well.  That could be in play.

**Comment by jcogs-design** [comment]
Haven't been back to that site in a while and changed design to remove issue - will see if I can scroll back to the version running at time and reproduce / get stack trace. May take a few days...

**Comment by intoeetive** [comment]
I am closing this since we haven't been able to replicate (almost a year since the report), and OP has changed design since, I am closing this issue.

Please comment back / reopen if the issue persists, and add more details.
