### ISSUE TITLE
Image Upload Error

### ISSUE THREAD

**Issue by SilverHawK-105** [ExpressionEngine/ExpressionEngine#205]
**Description of the problem**
I tried to Upload an Image to my new Installation of EE. Out of some reason I Always got an PHP Error. But when I did Upload an .mp4 instead of .png or. jpg it worked.
**How To Reproduce**

**Error Messages**

<pre><code>

( ! ) Fatal error: Uncaught Error: Call to undefined function EllisLab\ExpressionEngine\Library\Mime\imagecreatefromstring() in /var/www/system/ee/EllisLab/ExpressionEngine/Library/Mime/MimeType.php on line 192
--

1 | 0.0000 | 366968 | {main}(  ) | .../admin.php:0
2 | 0.0001 | 368384 | require_once( '/var/www/system/ee/EllisLab/ExpressionEngine/Boot/boot.php' ) | .../admin.php:153
3 | 0.0011 | 478376 | EllisLab\ExpressionEngine\Core\Core->run(  ) | .../boot.php:151
4 | 0.0017 | 584784 | EllisLab\ExpressionEngine\Core\Core->runController(  ) | .../Core.php:110
5 | 0.0283 | 2422752 | call_user_func_array:{/var/www/system/ee/EllisLab/ExpressionEngine/Core/Core.php:241} (  ) | .../Core.php:241
6 | 0.0283 | 2423144 | EllisLab\ExpressionEngine\Controller\Files\Files->upload(  ) | .../Core.php:241
7 | 0.0284 | 2424120 | EllisLab\ExpressionEngine\Service\File\Upload->uploadTo(  ) | .../Files.php:138
8 | 0.0320 | 2564520 | Filemanager->upload_file(  ) | .../Upload.php:299
9 | 0.0327 | 2604432 | Filemanager->_upload_file(  ) | .../Filemanager.php:1024
10 | 0.0367 | 2654544 | EE_Upload->do_upload(  ) | .../Filemanager.php:1908
11 | 0.0411 | 2655216 | EE_Upload->is_allowed_dimensions(  ) | .../Upload.php:243
12 | 0.0411 | 2655216 | EE_Upload->is_image(  ) | .../Upload.php:583
13 | 0.0411 | 2655216 | Mime_type->fileIsImage(  ) | .../Upload.php:524
14 | 0.0411 | 2655216 | EllisLab\ExpressionEngine\Library\Mime\MimeType->fileIsImage(  ) | .../Mime_type.php:121

</code></pre>

**Environment Details:**
 - Version: [5.2.2]
 - PHP Version [7.0 as well as 7.2]
 - MySQL Version [ 10.1.37-MariaDB-0+deb9u1]
 - OS: [Debian or Ubuntu]
 - Web Server: [Apache 2.4.25]

**Comment by litzinger** [comment]
It may help to include what file, or at least file type, you were trying to upload as this may be specific to the type of file.

**Comment by SilverHawK-105** [comment]
Soory, out of some reason my Contents where deleted before I posted it. I added all the relevant Information. I also could show you the Problem.

**Comment by derekjones** [comment]
`imagecreatefromstring()` is a standard [PHP function](https://www.php.net/manual/en/function.imagecreatefromstring.php). Please make sure that your server meets the system requirements for running ExpressionEngine. You can test it with the [Server Compatibility Wizard](https://docs.expressionengine.com/latest/installation/requirements.html#server-compatibility-wizard), thanks!
