### ISSUE TITLE
Problem with the update function

### ISSUE THREAD

**Issue by bytebaby** [ExpressionEngine/ExpressionEngine#2055]
If I click on settings <index.php?/cp/settings/general> then a white page appears with the following line:
{"error":""}
If I reload this page in the browser, the line disappears again. At the same time, a new update is displayed, but I cannot import it because version 6.3.2 is not displayed. See the screenshots:

<img width="196" alt="image" src="https://user-images.githubusercontent.com/21154749/166218289-8e523b62-80ea-4520-82c5-c887897c9d65.png">
then:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/21154749/166218337-5edc3710-6645-478d-8abc-e07116a2eb0f.png">

I don't have this problem with other EE websites

Configuration:
PHP 7.4.28
MariaDB 10.5.15

**Comment by bytebaby** [comment]
Addendum: The developer logs reports: 
"To fetch templates from database is usually faster than from file cache driver."

**Comment by robinsowell** [comment]
Can you open up your browser debugger, go to the 'Network' tab- then navigate to settings where you get the error.  If you look in the XHR responses, is there anything there?  That looks like a json response to something, but I'm not getting anything loaded when I do the same.

Also- if you click the version number on any other page, does it say you're on the latest or does it come up with the new version number to upgrade to?

**Comment by bytebaby** [comment]
Nothing appears for me with the browser developer tool either.

But I just disabled the cache once with the browser developer tool. And suddenly I get the current version displayed

<img width="338" alt="image" src="https://user-images.githubusercontent.com/21154749/166289110-980ac183-2f66-4777-b159-9d25bd4e19ca.png">

After that I was able to import the update to 6.3.3 without any problems. After the update, the latest version also appeared below:

<img width="194" alt="image" src="https://user-images.githubusercontent.com/21154749/166289760-b341a260-e3dc-4897-a72d-789ead6d9f23.png">

But when I click on it, the update box reappears:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/21154749/166289110-980ac183-2f66-4777-b159-9d25bd4e19ca.png">

If I then click on the small "Check now" button under basic settings, the problem disappears.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/21154749/166290381-a35a3b16-e94e-4704-9236-6738b6d385d4.png">

This procedure has haunted me since EE version 6.1.

**Comment by bytebaby** [comment]
Interesting: If I reactivate the cache with the browser developer tool and then click on "Basic settings" in the backend and then on the "Check again" button, the line ["up-to-date"] appears again.

**Comment by bytebaby** [comment]
It appears to be a Chrome cache issue as it doesn't show up in Firefox. I cleared the Chrome cache and there were no error messages after that. I'm curious if it stays that way with the next update. :-) Thank you

**Comment by robinsowell** [comment]
HRM!  Weird one.  Well, especially that error message.  I don't recall seeing prior reports of that happening.  We'll keep an eye out and if it happens again, we'll at least have a good starting point!
