### ISSUE TITLE
File/Image Upload Button fails after new textarea field is created w/in a fluid field

### ISSUE THREAD

**Issue by mcfarlandonline** [ExpressionEngine/ExpressionEngine#207]
When a new Textarea field is added within a Fluid Field and someone tries to immediately use the HTML/Formatting Image Upload button, the button does not work. I don't see any errors in the console either. 

It doesn't seem to matter if the entry is brand new or a preexisting entry that's been saved and reopened. 

In either case, the entry must first be saved with its new Fluid > Textarea field in place. Once the entry is saved, the Image Upload button works as expected.

**How to Reproduce:**
1. Create a Textarea field and enable Formatting Buttons
2. Create a Fluid Field and select the new, aforementioned Textarea field from the Field Options.
3. Add the new Fluid Field to some channel's field settings.
4. Create a new entry in that channel, or open an existing one. 
5. Add a Textarea field within the Fluid Field and immediately try to upload an image or file into it using the Image Upload button (cloud w/ arrow icon). 
6. You shouldn't be able to. 
7. Try saving the entry with your new Fluid<Textarea field still in place.
8. The Image Upload button should now work for that field.

**Environment Details:**
 - Version: 5.2.2
 - PHP Version: 7.1
 - MySQL Version: 5.6.43
 - OS: macOS
 - Web Server: Apache

**Comment by ops-andy** [comment]
making a note that this issue exists in v6

**Comment by intoeetive** [comment]
@ops-andy I have not been able to replicate this in EE 6.0.3. The file browser shows up and I am able to use Upload button once I select upload destination

**Comment by ops-andy** [comment]
![eecore-1076](https://user-images.githubusercontent.com/55093827/113313265-156dad80-92d9-11eb-9d20-b0913edc3e9e.gif)

**Comment by mcfarlandonline** [comment]
https://user-images.githubusercontent.com/20441129/113331180-78107a80-92d4-11eb-8d51-bf20edd78201.mov
