### ISSUE TITLE
Sticky Entry Search

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#2078]
When editing lots of Entries, and needing to Search for specific Entries every time using the Filter, it can get very time consuming (and painful!).

It would be great if the Search terms used in the Entry Search fields are Sticky.
This would include the keywords and all the dropdown menus (eg. Status, Category).

So when Saving the changes in an Entry and returning to the Entry Listing, the previous Search terms should still remain and the listed Entries should remain as before. If this could include landing back on the same Paginated page... even better.
Also, I think the Search filters should remain Sticky when navigating back to the Entries listing using the breadcrumbs, displayed on the Edit Entry screen.
Should they be cleared with listing Entries again from the Sidebar?  I think so. But not 100% sure.

A "Clear Search" button might be handy too - maybe placed next to the "Search Titles Only" option.

**Comment by PaulBaileyAtChan** [comment]
I think this is essentially the same as https://github.com/ExpressionEngine/ExpressionEngine/issues/111. It's been an issue for a *very* long time, and IMO is absolutely a basic feature which should be a priority to fix. How old that other issue is gives a sense of how long it's been needed.

**Comment by ic360-com** [comment]
You're right Paul, it is the same Request, well spotted - and I've even commented on that old request myself!
I tried searching for an existing request, but didn't find one.
Thanks for highlighting.  :-)

**Comment by robinsowell** [comment]
I did 'bump' this internally, but closing this one as a duplicate.
