### ISSUE TITLE
Current date/time button for Date Picker

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#208]
When editing old Entries, it takes an age to click through all the months to find the current date, to replace the old one. Plus, most customers/users aren't confident enough to over-type the date and time with the current date/time.

Solution: Have a "Current" or "Now" button (or similar) on the Date Picker, to set the date/time to current.

**Comment by Jordan-Ellis** [comment]
Added to EE6!
