### ISSUE TITLE
Comments Setting Off, still shows Comments column in Entries Listing

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#2080]
When switching off Comments in the overall CP Settings... I would expect the Comments column in the Entries Listings to disappear.
But maybe keep it as a toggled option to enable historical Comments to be displayed if required.

**Comment by robinsowell** [comment]
I'm thinking I wouldn't want to automatically have it toggle of myself.  But if there are no comments, none in spam, and it's disabled?  I think it shouldn't be available to toggle at all and if it had been showing, remove it.

Which is pretty close, behavior wise.  And I agree, it's a nice UI enhancement.

**Comment by ic360-com** [comment]
Yes, it needs some kind of 'overall' control I think. I'm sure this used to be included in the CP somewhere / somehow pre-V6.

eg. If you have 100 channels, then setting the Entries List view manually, to remove the Comments column, will be a pain, if you decide not to be using Comments on the site anymore... whether there are Entries with pre-existing Comments or not.
