### ISSUE TITLE
Field Names Showing DB Columns?

### ISSUE THREAD

**Issue by nickpuglisi** [ExpressionEngine/ExpressionEngine#2081]
6.3.4 (PRO) - noticing that in the latest update the field names in many Channel Fields are not calling the default field names and instead are calling the database column names (ig field_id_6) instead of what was called upon for Member & other fields?

**Comment by robinsowell** [comment]
Hi Nick,

I'm a little fuzzy on this one.  Do  you mean if you use {field:my_custom_field} the parsed output  uses the db name rather than the field shortname in the rendered html form?  Walk me through it a bit.

And is it messing up posting/editing/existing forms, or is it just weird?

**Comment by nickpuglisi** [comment]
Hey Robin, 

On my EE version if I create a custom Member Field in the Admin Console, then go to the front-end and use the Edit Member Profile tags it displays the database name of each field rather than the key fieldname given in the database. This _does_ work the correct way in templates (ig if I do a textarea called "about" and add {about} in a profile that will work, however when they go to edit that field having the input be name="about" doesn't work; it requires name="field_id_9").

**Comment by intoeetive** [comment]
This is correct pre-existing behavior. The fields in Profile Edit form are addressed by their "technical" name (e.g. m_field_id_9), not their short name. The documentation is not 100% clear on this, we'll have it updated
