### ISSUE TITLE
Date formatting bug from Relationship field in Grid field

### ISSUE THREAD

**Issue by avnerw** [ExpressionEngine/ExpressionEngine#2082]
On the front-end, this following template code skips the `relationship_field` altogether when the `entry_date` includes the `format='....'` part, but works if `entry_date:relative`, or just `entry_date` is used. 

Here is the complete code block.

```
{if grid_field}
    {grid_field}
          {if grid_field:relationship_field} 
             {grid_field:relationship_field:title}
             {grid_field:relationship_field:entry_excerpt}
             {grid_field:relationship_field:article_lead}

                {grid_field:relationship_field:entry_date format='%F, %j, %Y'}
              
           {if:else}

             ...
           
          {/if}
    {/grid_field}
{if:else}

...

{/if}
```

Version: EE Pro 6.3.4
Hope this is enough information to reproduce, if this is a bug.
https://eecms.slack.com/archives/C04L896K4/p1652611901575109

**Comment by intoeetive** [comment]
@avnerw I guess I'm late here, but looks like your code us missing the wrapping `{grid_field:relationship_field}` field tag pair. When using it, everything was parsed fine on my test
