### ISSUE TITLE
Selectable Button Field outputs Label instead of Value

### ISSUE THREAD

**Issue by avnerw** [ExpressionEngine/ExpressionEngine#2085]
For the new Selectable Button field, when I use this code  {button_field} , it  outputs the Label instead of the Value.

![Screen Shot 2022-05-18 at 4 54 47 PM](https://user-images.githubusercontent.com/17215743/169059916-d23d16aa-4a51-4603-9ad5-26284cdc86f9.png)

```
Value: {button_field} <br>
Value: {button_field:value}<br>
Label: {button_field:label}<br>
```

_Output from above:_

One
1
One

_Instead of_ 

1
1
One

So, also `{if button_field == 1} ... {/if}` won't work because the Label is returned and not the Value.

EE: 6.3.4 Pro
MySQL: 8.0.29

Thanks

**Comment by robinsowell** [comment]
Unfortunately, this is actually a documentation bug.  It's not a behavior we can alter now, as too many sites are relying on current behavior.

I have put in a PR to make sure the docs are correct on value/label display: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/465

The lack of consistency isn't what we'd prefer, but altering the behavior isn't a good option.
