### ISSUE TITLE
In Edit Profile Data Tag -> Custom Profile Field Variable Pair How can i add class to {form:custom_profile_field}

### ISSUE THREAD

**Issue by ErhanGuneyKaradag** [ExpressionEngine/ExpressionEngine#2087]
{custom_profile_fields}
        <div class="form-group">
            <label>{lang:profile_field}</label>
            {form:custom_profile_field}   **--> I need to add class to this field like form-control**
        </div>
    {/custom_profile_fields}

Thank You..

**Comment by intoeetive** [comment]
Late to the party, but please head over to [Forums](https://expressionengine.com/forums) or [EE Slack](https://expressionengine.com/blog/join-us-in-slack#join-us-on-slack) if you're looking for community help.

We tend to keep GitHub issues for bug reports and feature requests
