### ISSUE TITLE
Annoying and inaccurate warning when uploading images/files while publishing

### ISSUE THREAD

**Issue by mcfarlandonline** [ExpressionEngine/ExpressionEngine#2090]
When uploading a new file from within an entry, you must first select which directory to store the file in. The modal then takes you to that directory, but half the time, before I can continue, I get overzealous browser warnings like these...

<img width="856" alt="Screen Shot 2022-05-19 at 2 44 26 PM" src="https://user-images.githubusercontent.com/20441129/169410215-9c8a5dd5-d8c8-463a-984f-dc8e95893970.png">

I believe this also sometimes happens on the window where you actually choose which file to upload from your computer. 

I can't yet figure out the pattern of when this does/doesn't happen, but I hate to think of how it might be confusing some of my less tech-savvy clients. 

EE v 6.3.4 (but this has been a persistent throughout the last few versions)
PHP v 7.4.29

**Comment by PaulBaileyAtChan** [comment]
+1 Was just about to suggest (wrongly!) that this is coming from the browser itself, rather than EE. Just tested in EE6.3.4 using (Mac) Safari, Firefox and Chrome, and I see the message on all of them when I choose an upload directory in the modal. It's clearly firing at an inappropriate time, and is definitely confusing.

**Comment by intoeetive** [comment]
That is an interesting case, thanks for reporting!

Is the site using MSM, or set up using multiple subdomains?

**Comment by mcfarlandonline** [comment]
No MSM or multiple subdomains over here in this instance.

**Comment by PDXMan1** [comment]
My clients are seeing this too. Sometimes, after dismissing the EE alert, then a seperate browser alert pops up. In this case, I have an entry open, then navigate to a channel within the entries menu. We have to dismiss both alerts just to get to the table of the entries page.
<img width="300" alt="zalert1" src="https://user-images.githubusercontent.com/6145078/170538596-cee57853-12d0-4f04-8d54-e2e3442dad05.png">
<img width="303" alt="Screen Shot 2022-05-26 at 10 02 47 AM" src="https://user-images.githubusercontent.com/6145078/170538634-aeca52b4-9e82-414c-8a40-dd0831c2b9cb.png">

**Comment by intoeetive** [comment]
This has been fixed in EE7 and the fix is getting backported into 6.4.0
