### ISSUE TITLE
Parsing issue, select statements, active record

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2093]
Adding this construction to an active record triggers a SQL error
```
ee()->db->select('IF(code = \'NO\', 1, 0) as out');
```
The error comes because the select string is wrongly parsed by Active Record - the SQL generated contains this construction
```
IF(code = 'NO', `1`, `0)` as out,
```
Notice that the final quote mark is placed the wrong side of the closing parenthesis which borks MySQL.

EE 6.3.4, php 7.24.8, MySQL 5,7.23

**Comment by jcogs-design** [comment]
Did some digging and this error is being introduced by the method `escape_identifiers()` in `source/system/ee/legacy/database/DB_driver.php` (the file for the `CI_DB_driver` class).

AR breaks up the select into fragments based on the location of `,` (so `IF(code = 'NO'`, `1`, `0) as out`).

When the actual SQL query is constructed these fragments are passed through the `_protect_identifiers()` method, which breaks the string passed based on the first space (so `0) as out` becomes `0)` and ` as out`, and then in turn passes each of these elements through the `escape_identifiers()` method.

`escape_identifiers()` takes the element and basically wraps it in back-ticks.  So `0)` becomes `\`0)\``.

All these elements are then bolted together - so hence how we gain the unnecessary tick outside the bracket.

`_protect_identifiers()` already has a bit of code to stop it breaking opening brackets (line 953 ... 
```
        // This is basically a bug fix for queries that use MAX, MIN, etc.
        // If a parenthesis is found we know that we do not need to
        // escape the data or add a prefix.  There's probably a more graceful
        // way to deal with this, but I'm not thinking of it -- Rick
        if (strpos($item, '(') !== false) {
            return $item . $alias;
        }
```
I've tried adding a fix for this issue by duplicating this escaping clause for closing brackets, (and then adding another to escape numeric values, as `1` is borked) and this seems to work, but not really had chance to do any testing. Added to `_protect_identifiers()` after line 960... 
```

        // Another quick hack to trap closing brackets
        if (strpos($item, ')') !== false) {
            return $item . $alias;
        }

        // Another quick hack to trap numeric values
        if (is_numeric($item) !== false) {
            return $item . $alias;
        }
```

**Comment by robinsowell** [comment]
Ack- really appreciate the nice debugging.  I can follow along and everything including the fix makes sense, but I'd definitely like one of the developers to eyeball it as well.  I've got an internal report in on it to make that happen.

**Comment by intoeetive** [comment]
Just noting that possible workaround for this is adding `false` as second parameter for `select()`
```
ee()->db->select('IF(code = \'NO\', 1, 0) as out', false);
```

**Comment by intoeetive** [comment]
Closing out as we have a solution mentioned in comment above.

Advanced SQL statements would often need to skip built-in identifiers escaping, that's why the second param exists
