### ISSUE TITLE
Add the ability to define join aliases in Active Record

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2096]
**Describe the solution you'd like**
Sometimes it is necessary to use an alias in a JOIN - when you want to make two separate table joins to the same column for example. Active Record does not support this, nor does it support the addition of aribtrary SQL to a query it is building, so currently you cannot (for example) use a lookup table multiple times in the same request. For example (from the [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/sql-statements.html#join) you might want to do this
```
SELECT t1.name, t2.salary
  FROM employee AS t1 INNER JOIN info AS t2 ON t1.name = t2.name;
```
Currently this is not possible to specify using Active Record' [join()](https://docs.expressionengine.com/latest/development/legacy/database/active-record.html#jointable-cond-type--) method.

It would be good to add the ability to specify an alias in the join() method. 
It would be easy enough to add to the function by defining a further optional parameter to those already in place, but it would be the necessary to disable the application of the `_protect_identifiers()` method to the join condition, since otherwise AR would attempt to (at the very least) prefix the alias prefix (similar to the effect of setting `$escape = false` in a select() statement).

**Describe alternatives you've considered**
Usually the need for aliased joins can be avoided by data table design (e.g. [avoiding the need for look-ups by duplicating data](https://dev.mysql.com/doc/refman/8.0/en/optimization.html#data-size-joins)), but if you are working with legacy data this might not be possible.

**Teachability, Documentation, Adoption, Migration Strategy**
A small addition would be needed to the AR documentation to note the additional parameter, and that table-name protection is removed when an alias specified.

- [X] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
This has been merged and released.
