### ISSUE TITLE
Server error — spam referral urls with parsed spaces  (xss filtering issue?)

### ISSUE THREAD

**Issue by liamcrean** [ExpressionEngine/ExpressionEngine#2098]
This URL structure (note spaces) triggers server errors (on some builds runnig EE latest but not all..? - see attached error message) which show up in Google Search Console as indexing issues — Google tries to crawl and fails.

**my-ee-site.com/?url=somespamsite.com/results/spam spam**
**my-ee-site.com/?url=somespamsite.com/results/spam%20spam**

These do not trigger server error messaging(404 as expected) 

**my-ee-site.com/?url=somespamsite.com/results/spam-spam**
**my-ee-site.com/?url=somespamsite.com/results/spam_spam**
**my-ee-site.com/?url=somespamsite.com/results/spam/spam**

This is a problem for any client running Google's Search Console. Ideally EE would serve 404s for all of these — so as not to render the search console 'coverage' tool redundant (can be many many thousands of errors).

<img width="1246" alt="Screenshot 2022-05-23 at 19 54 36" src="https://user-images.githubusercontent.com/2526645/170080340-f751e5be-81c9-4c25-a61d-9d82f7251af6.png">

**Comment by liamcrean** [comment]
Any news on this one please? Would be great if I had some kind of timeline so we can contact our EE clients and let them know.

**Comment by intoeetive** [comment]
@liamcrean 

The message on screenshots will only appear in two cases: if you are logged in to Control Panel or you have `$config['allow_url_redirects_from_site'] = 'y';` set in your config file. For the general public and the default setup, 404 is thrown before XSS check

But also if you're logged in or have that config override set, 404 is not shown at all - you get Redirect warning interstitial page (which is served with HTTP 200 code) or that XSS error.

So, can you double check your setup?

**Comment by intoeetive** [comment]
@liamcrean do you still have the issue? If yes, are you using the above-mentioned config override?

**Comment by liamcrean** [comment]
I can't quite remember how we solved it Yuri (mix of above + htaccess config I think) — but this one can be closed. Thanks.
