### ISSUE TITLE
Adding a Relationship Field shows alert without any message

### ISSUE THREAD

**Issue by lilywhiteweb** [ExpressionEngine/ExpressionEngine#2099]
This problem was happening on 6.3.3 so I updated to 6.3.4 to see if it would fix it and it didn't. When I try to add a relationship field, the form fields show the warning and highlight the form entry, but there is no alert message. Also the 'Save' button becomes an 'Errors Found' button and again no message associated with it (checked for tooltips as well). What is strange is that is saves the relationship field without me clicking Save...it's as if the Error triggers a save?? 
![image](https://user-images.githubusercontent.com/38029048/170213840-d90c71e8-8712-4d55-9c05-ad43efd2f137.png)

**Comment by robinsowell** [comment]
So- that is super weird!  If you open up browser tools, are you getting a javascript error at any point?  And if you can, does disabling all extensions resolve the issue?  Note- this may well break things, so be careful if it's a live site.

**Comment by lilywhiteweb** [comment]
Hey. Yeah I get this error when I select the Relationship Field. 

![image](https://user-images.githubusercontent.com/38029048/171114802-36f12675-0d7e-4341-8d1c-129c26f4e2d2.png)

Looking at the network requests, it seems like the response from selecting the Relationship field yields a html error page instead of JSON formatted result

Selecting Rich Text Editor Field
![image](https://user-images.githubusercontent.com/38029048/171115154-9bc0d6fa-ee04-4a06-a15a-ba1c42f6489e.png)
![image](https://user-images.githubusercontent.com/38029048/171115212-f8258488-897a-48d2-8869-385b1553f7c2.png)

Selecting Relationship Field
![image](https://user-images.githubusercontent.com/38029048/171115383-089b2f2a-6e18-4ae8-8884-121b1d74292d.png)
![image](https://user-images.githubusercontent.com/38029048/171115472-f253ecdf-e15e-475b-a99b-e39a2d7ffc43.png)
![image](https://user-images.githubusercontent.com/38029048/171115564-52e2d37e-09cd-4223-a8b0-88a0b08e8a60.png)

**Comment by robinsowell** [comment]
Hrm, ok, I think this is probably installation specific rather than a generic bug.  It might even be an issue coming from a different field.  Do you see any PHP errors in those xhr responses?

Can you flip on logging PHP errors- you need to ftp in and put this in system/user/config/config.php:

```$config['log_date_format'] = 'Y-m-d H:i:s';
$config['log_threshold'] = '1';
```
And create a folder system/user/logs/ that's writable.  Go to add a new relationship field and then go check in logs.  Let's see if it's created a file with anything interesting in it.

**Comment by lilywhiteweb** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/38029048/171957220-2ab05341-1269-4b94-8cd5-9713ae494e91.png">

**Comment by robinsowell** [comment]
Hrm, nothing useful there.  If you're able to get us superadmin access, drop a line to support@expressionengine.com and we can take a closer look.  I don't THINK this is a bug, since I can't duplicate it and I'm not getting other reports of it.  But we can take a closer look and see what jumps out.

**Comment by intoeetive** [comment]
@robinsowell has there been any update or we can close this issue?
