### ISSUE TITLE
Saving field changes throws wobbly

### ISSUE THREAD

**Issue by bron-yr-aur** [ExpressionEngine/ExpressionEngine#21]
Saving changes to existing fields results in following "E_Warnings". I happened to be adding a field within a grid. The changes do appear to get saved but I get the following warnings:

"Notice

Undefined offset: 1

ee/legacy/fieldtypes/OptionFieldtype.php, line 114

Severity: E_NOTICE
Warning

Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)

ee/legacy/core/Input.php, line 238

Severity: E_WARNING
Warning

Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)

ee/legacy/libraries/Functions.php, line 393

Severity: E_WARNING"

**Comment by bron-yr-aur** [comment]
I meant to write that this is EE 5.0.1 automatically updated from 4.3.6.

**Comment by derekjones** [comment]
Can you please provide steps to reproduce? Also please use our [issue templates](https://github.com/ExpressionEngine/ExpressionEngine/issues/new) from now on, which will guide you through the information that is needed for issue reports to be workable. Thanks!

**Comment by bron-yr-aur** [comment]
Not sure there is much to say, Derek. I recently updated to 5.0.1 from paid 4.3.x (can't remember exact iteration). All seemed well with the update. Today, I went to amend a grid field and when I saved the change I got the message quoted above. This occurred both when I simply changed the order of existing grid fields and also when I added another field to that grid. Both changes seemed to have been saved despite the error message/warning. Incidentally, I am able to use this EE install to make normal changes to entries without any errors reported or warnings (which is good because I have a client who actively updates entires frequently and I'd hate the upgrade to 5.0.1 to have broken anything). Thanks. 
_ps. Your point about using issue templates in the future is noted._

**Comment by derekjones** [comment]
If an issue can't be reproduced as a bug, there's nothing actionable for anyone to do. Do you still get this error when editing a Grid field? Do you have add-ons installed? What steps can someone take on their own install to reproduce your errors?

**Comment by bron-yr-aur** [comment]
No, I don't have any add-ons – I never use add-ons. I get the message every time I "open" this grid field and save it (using any of the three save options) – I don't have to actually edit the field in any way. I can edit and save other fields without a problem. Are you not able to tell anything at all from the message? If it's not a reproducible bug does it seem like something may have become corrupted (possibly as a consequence of the update process)? I am a designer (and long time user of EE) and working out what the error message means is way beyond my understanding. I was rather hoping that somebody might have a few pointers. Thanks.

**Comment by derekjones** [comment]
The error indicates an issue with populating an option-type field (checkbox, etc.), but not why you're experiencing that. Can you export this Channel Set and attach it here, please? Maybe that will tease out the details.

**Comment by bron-yr-aur** [comment]
Thanks Derek. Forgive my ignorance but I'm not sure how to export the Channel set. I'll see what I can do. What I have done is create a new grid field altogether as a test and added to this a checkbox option field. This worked absolutely fine without error messages of any kind. However, the existing grid field is still causing the same error messages whenever I try and save it (though, as stated earlier, it does save any changes made). Barring any other advice, I will recreate the grid field that I need and delete the old one. Hopefully that will work ok but I'm a little worried that the error message will rear up in some other context.

**Comment by derekjones** [comment]
To export a Channel Set, go to Developer > Channels, and click the "cloud" icon next to the channel that uses the field(s) in question.

**Comment by bron-yr-aur** [comment]
Thanks, Derek. Yes, just read this in the user guide. :-) The field in question is called 'variations'.
[ChannelSet.zip](https://github.com/ExpressionEngine/ExpressionEngine/files/2617192/ChannelSet.zip)

**Comment by derekjones** [comment]
Thanks @bron-yr-aur, found and fixed.
