### ISSUE TITLE
Invalid GET Data after filtering entries in CP using diacritics

### ISSUE THREAD

**Issue by low** [ExpressionEngine/ExpressionEngine#210]
When filtering the list of entries in the CP by keywords, you can encounter the "Invalid GET Data" error message, when you're using keywords that contain diacritics. Related, selecting a different channel (which triggers an Ajax request) also does not work.

1. Navigate to the Entry Manager in the CP
2. Filter entries by keyword, using something like "tëst"
3. This works; now try and search again, using any search term
4. Now you're getting the Invalid GET Data error.

If you repeat step 1 to 3, and then try to switch channel in the filter list, you'll get a JS error and the Ajax request will fail.

The error is caused because of an HTML-entity (eg, `&euml;`) being URL-encoded in the GET request.

Reproduced in EE 5.1.2 and 5.2.2, on PHP 7.1.

**Comment by derekjones** [comment]
Since `register_globals` is no longer a thing, and web browsers are getting better with their own security precautions around URLs, perhaps it's time to eliminate this filter error. Can you think of any reason that we should keep and modify it to fix this bug instead?

**Comment by low** [comment]
Nope, I'd remove it. The real issue is when you want to output that GET data to the browser, or use it in a query. In both of those cases, the responsibility lies with sanitizing the input before doing so, rather than doing that from the GET go. Heh.

**Comment by derekjones** [comment]
Oh, oops, I just confused this with Disallowed Key Characters.

**Comment by derekjones** [comment]
There we go. Want to double check that your issue is gone?
