### ISSUE TITLE
Conditional field UI returning values for the wrong field

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#2103]
I'm trying to update a field that has existing conditions. I want to switch it from "all" to "any", using additional values from the same Selectable Buttons field.

The values in the second instance of the button field are pulling from the wrong field.

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/308752/171245757-269e768d-2e94-4228-aa43-da7ccb51a007.png">

The "theme" value is from a completely different Selectable Buttons field.

To test, I went into a "new field" form, and tried creating a new conditional using the same field, and I'm getting the same wrong results:

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/308752/171248865-883500f1-9473-4275-bba5-b286c5730e8d.png">

I can update the *existing* condition successfully, but can't use the existing field in a *new* condition.

(EE 6.3.4)

**Comment by murtaugh** [comment]
Brief update on this: I tried using "contains" in the second column, manually entering the item I was looking for in the "Type {widget_type}" field, which doesn't work:

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/308752/171477120-f1d88bb4-2cfc-4056-af0b-6d46dfabcd4e.png">

That said, I tried again, using the *value* I'm looking for, which *does* work.

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/308752/171476916-aae4e5c4-696e-45a9-9ac4-64fdada5cfe6.png">

**Comment by jcogs-design** [comment]
Just a bump on this - I've got the same issue (6.3.5) and have found that if you add the conditional you initially get the wrong drop-down values as noted in the original post - however if you then save the field and do the update conditional logic thing,  the field reloads and when the field reloads you get the correct fields in the dropdown.
HTH
