### ISSUE TITLE
"Data will be lost warning" triggered on command-click

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#2104]
The "data will be lost" warning alert triggers when you command click on a link, meaning the page you're on isn't going to be navigated away from, and no data is going to be lost.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/308752/171496082-86d8c163-1d81-4ef6-9183-401d4e84034d.png">

Mac OS, Safari 15.5

**Comment by murtaugh** [comment]
FWIW, I also just got this warning in the file chooser modal, after I clicked the button switch views.

**Comment by robinsowell** [comment]
Hrm, I'm not able to replicate.  Tried on Mac FF, Chrome and Safari.  I tried swapping between list view and thumbs in the file model on an entry edit page and tried cmd+click on the link in
<img width="991" alt="Screen Shot 2022-06-03 at 10 40 51 AM" src="https://user-images.githubusercontent.com/1181219/171877323-380c3934-1869-4ec8-a146-3b23bc48db41.png">

Are you on 6.3.4?

If so, wonder if there's some setting in play or something.

**Comment by murtaugh** [comment]
(This obviously isn't critical, just an annoyance.)

Did you make any change to the publish form? I wasn't thorough with my report. The alert only triggers if the form isn't in the same state it was when the page first loaded.

I just confirmed this in my install by doing the following:

1. Create a new entry, don't do anything yet
2. Command-click in the left column to open the File Manager, the new tab opens without issue
3. Type "test" to the title field
4. Command-click to open the file manager again, I get the alert

It doesn't happen with every field type (fluid fields for example, which I don't think trigger the EE alert, but do *sometimes* trigger Safari's alert — which is another minor frustration, duplicate warnings, but _c'est la vie_). 

The instance of it happening in the file modal also depends on you having changed a field value.

(EE 6.3.4)
