### ISSUE TITLE
Return parameter does not work in exp:email:contact_form

### ISSUE THREAD

**Issue by bobhuf** [ExpressionEngine/ExpressionEngine#211]
**Description of the problem**
After updating to 5.2.2 (from 3.x) the [return parameter](https://docs.expressionengine.com/latest/add-ons/email.html#return) is no longer working in exp:email:contact_form. The form always returns to the homepage.

**Environment Details:**
 - Version: 5.2.2
 - PHP Version 7.2.10
 - MySQL Version 5.7.23
 - Web Server: MAMP & Apache

**Comment by derekjones** [comment]
I do not replicate with the contact form in the demo site on a fresh install. Can you share your full opening `exp:email:contact_form` tag? If possible I would also double check that your .htaccess or similar isn't redirecting your desired URL back to your home page.

**Comment by bobhuf** [comment]
You're right, it's a htaccess issue. This rewrite rule that redirects the root url to a subpage breaks the form redirect:
`RewriteRule ^$ /subpage [R=301,L]`

Any suggestions on how to get both to work?

**Comment by derekjones** [comment]
That's a somewhat unusual redirect; you cannot visit the root domain of your site at all?

If that's a purposeful decision, then you could add some `RewriteCond` statements prior to that that exclude certain URLs, such as your form submission/redirects, e.g. https://stackoverflow.com/questions/13282262/trying-to-exclude-a-url-from-htaccess-rule

**Comment by bobhuf** [comment]
Yes, very unusual... unfortunately. Thanks for responding so quickly.
