### ISSUE TITLE
EE5.2.2 hits an SQL exception when simple search keyword/s longer than 60 character

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#212]
**Description of the problem**
Simple search in EE5.2.2 is throwing an SQL exception when the keyword/s is/are longer than 60 characters. This seems to fit with the 60-character length of the <code>keywords</code> column of <code>exp_search</code>.

Restricting the keywords length is fine, obv., and 60 characters is as good a length as any, but longer keywords should be trapped earlier — and probably truncated.

Note that the EE5 user guide gives <code>maxlength="100"</code> as an attribute of the sample search tag, suggesting that at least at some point the maximum keyword length might have been 100 characters, and has since been reduced. This page in the guide might also be amended to be clearer about the practical maximum keyword length.

**Error Messages**
<img width="1031" alt="Screen Shot 2019-05-16 at 3 42 22 PM" src="https://user-images.githubusercontent.com/46760375/58043690-adea5280-7af2-11e9-8fbe-5a2f3bdfa33c.png">

**Environment Details:**
 - Version: 5.2.2
 - PHP Version: 7.0.33
 - MySQL Version: 5.7.26
 - OS: Ubuntu 16.04.1
 - Web Server: Apache 2

**Comment by robinsowell** [comment]
Good catch, this should be fixed in https://github.com/ExpressionEngine/ExpressionEngine/commit/c8243c9cac15ab0b15c3fef297de314fa60b8d7b
