### ISSUE TITLE
Hitting escape in the New Entry modal causes you to lose your inputs

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#2121]
In what is the opposite of my last issue (#2104), you don't get any warning at all when you escape out of the New Entry modal, meaning you can easily lose work.

1. Find a relationship field
2. Click "new entry"
3. Enter some data in the fields
4. Hit escape
5. Mourn for your lost work

EE 6.3.4

**Comment by TomJaeger** [comment]
Thanks for submitting this @murtaugh 

From a UX standpoint, any thoughts around an optimal experience?

**Comment by murtaugh** [comment]
At the least it should offer the same "data will be lost" warning as clicking away from the main edit form.
