### ISSUE TITLE
Previewing an entry with grid shows incorrect data when applying `search` parameter to checkboxes column

### ISSUE THREAD

**Issue by hopDrew** [ExpressionEngine/ExpressionEngine#2122]
![image](https://user-images.githubusercontent.com/102068794/175399614-3960f9ea-246e-4d7e-9037-90b155ad2a2e.png)

In the image attached, we have an entry with multiple images with additional corresponding content and attributes in a grid. When previewing the entry (and regardless of what other images are present) the first image is being used for all of the images in the preview pane.

This only happens in the entry preview, as the entries themselves are fine when displaying on the front-end.

Images are parsed with jcogs_img prior to being output on our production site, but I've also tested this locally with and without the jcogs_img tags and I have noticed no changes in behaviour.

EE Version 6.3.4
PHP 7.2
MySQL 5.0

**Comment by TomJaeger** [comment]
@hopDrew Thanks for submitting this.  Just to confirm, the file here is a standard EE File field?

**Comment by hopDrew** [comment]
Hi Tom,

Yes, that is correct.

Thanks,
Drew.

**Comment by TomJaeger** [comment]
Awesome,

With a quick test we were not able to replicate it... Any chance you can post a simple example for replication?   (Also any other add-ons at play here?..)

Thanks,
-Tom

**Comment by hopDrew** [comment]
Here is the field list for our project images file grid
![image](https://user-images.githubusercontent.com/102068794/175658527-ccd130e3-6429-4875-a9c7-da0133f77f77.png)

Here are our project entries fields
![image](https://user-images.githubusercontent.com/102068794/175658621-baa16eaf-8971-424c-aff1-f16f66a8ed85.png)

From what I can tell, none of our addons would be interfering with this:
![image](https://user-images.githubusercontent.com/102068794/175657947-b75ba2fd-991e-440e-b8a3-e0913149aa13.png)

Here is what our project images fields look like:
![image](https://user-images.githubusercontent.com/102068794/175658702-caec87bc-2934-4139-9c52-aa202e880111.png)

Note that one image is marked as featured, and one is marked as a halfway image.

Here you can see that all of the images on the page are strictly the "feature" image:
![image](https://user-images.githubusercontent.com/102068794/175659007-de9a80f7-dc41-4bfb-92d4-5d2845883114.png)


Code snippet for our featured image:
![image](https://user-images.githubusercontent.com/102068794/175662590-88c417ef-1cd6-4a66-add6-198f6f46aa3f.png)


Code snippet for our midway image:
![image](https://user-images.githubusercontent.com/102068794/175662654-5bf44834-3c01-40ce-97ac-2a5680df4372.png)

**Comment by hopDrew** [comment]
Hi @TomJaeger,

If you haven't been able to replicate this issue yet, can you please let me know if there's any further information I can provide?

Thanks,
Drew.

**Comment by TomJaeger** [comment]
Hi @hopDrew,

I've been out of the office a good bit here recently, so haven't had a chance to dig in beyond the initial testing mentioned above.

Few thoughts on this one as a whole.

1. Any chance you can put together the most simplistic example to replicate the issue?  (anything to simplify the replication of the bug will greatly expedite us in replicating it and working towards a fix).... Might be easiest to start a new channel, and start adding the fields to it with a simplistic template 1 at a time or something along those lines... to find out where things start getting messed up.. from there it might be easy to streamline the example down to the 1 field or something along those lines. 
2. If you backup your DB, and then start uninstalling add-ons 1 at a time and testing, does it start working after a specific add-on (this might be easier to test then #1 above)

Thanks,
-Tom

**Comment by hopDrew** [comment]
Hi @TomJaeger,

Sorry for the delay on this. I'm still figuring my way around EE a bit.

I've been able to reproduce this issue on one of our experimental sites. Here's what I did.

**1. Create a new template group and template (our_work/item) (Apologies about the image, github was not playing nice with the pasted content)**

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/102068794/177897683-dd042030-28a6-463b-8c7f-67712e709b89.png">

**2. Create a new field group called Project Fields**

**3. Add a new field to the group called "Project Images".**
![image](https://user-images.githubusercontent.com/102068794/177895165-1e6be756-3aa1-4715-bd57-a36c150aca8d.png)
3 a. The grid fields are as follows:

**Field 1**
- Type: File
- Name: Project Feature Image
- Short: project_feature_image
- Column minimum width: 300
- Allow file types: All
- Allowed directory: Uploads
- Show Existing FIles: On

**Field 2**
- Type: File
- Name: Project Thumb Image
- Short: project_thumb_image
- Allow file types: All
- Allowed directory: Uploads
- Show Existing FIles: On

**Field 3**
- Type: Checkboxes
- Name: Is this a special image?
- Short: is_special
- Include In Search: On
- Text Formatting: None
- Populate Manually: featured, midway

**Field 4**
- Type: Text Input
- Name: Project Feature Alt Text
- Short: project_feature_alt_text
- Maximum Characters: 100
- Text Formatting: None
- Direction: L -> R
- Allowed Content: All

**4. Create a new Channel**

**Channel**
- Name: Projects
- Short Name: projects

**Fields**
- Title field label: Title
- Field Groups: Project Fields

**Settings**
- Channel: HTTP(s)://whatever.your.domain.is.com/our_work
- Comment form: same as above
- Search Results: same as above
- Allow Preview: Enabled
- Preview URL: our_work/item/{url_title}
- Status: Open
- HTML Formatting: Allow all HTML
- Allow image URLS?: Enabled
- Enable sticky entries: Enabled
- Enable entry versioning?: Enabled
- Comments: Disabled

**5. Create a new entry under projects**

- Title: OpenMedia
- URL title: openmedia
- Project Images: **PLEASE SEE ATTACHED IMAGES**

<img width="2095" alt="image" src="https://user-images.githubusercontent.com/102068794/177896972-543a6280-f188-4f3e-b98c-0ebafb5334c4.png">

**Options**
- Channel: Projects
- Entry Status: Open

**Pages**
- Pages URI: /our_work/openmedia
- Template: our_work / item

**Images Used For Testing**

_Openmedia_feature1_
![openmedia_feature1](https://user-images.githubusercontent.com/102068794/177897706-d9d715bd-90fd-4130-9617-7c9d4b4df047.png)

_Openmedia_feature2_
![openmedia_feature2](https://user-images.githubusercontent.com/102068794/177897708-10f16fcf-df62-4aef-8ff1-f01375ca5c75.png)

_Openmedia_feature3_
![openmedia_feature3](https://user-images.githubusercontent.com/102068794/177897709-d9c79201-93d6-4797-87be-05b21460e9bc.png)

_Openmedia_feature4_
![openmedia_feature4](https://user-images.githubusercontent.com/102068794/177897711-97408018-ebe6-4221-a6b5-f0deca59cf8d.png)

_Openmedia_thumbnail1_
![openmedia_thumbnail1](https://user-images.githubusercontent.com/102068794/177897712-c725d9ea-7ebf-4254-83cf-daf11f5fb540.png)

_Openmedia_thumbnail2_
![openmedia_thumbnail2](https://user-images.githubusercontent.com/102068794/177897714-305ba859-97d6-4210-88ef-e56aa73b065d.png)

_Openmedia_thumbnail3_
![openmedia_thumbnail3](https://user-images.githubusercontent.com/102068794/177897715-0b29e664-bdeb-4fae-b0a1-89af49f6a541.png)

_Openmedia_thumbnail4_
![openmedia_thumbnail4](https://user-images.githubusercontent.com/102068794/177897716-69e879e7-aeab-4a3e-9943-311d07a2a51d.png)

When the entry is complete, you will see while previewing that two of the same images appear, as opposed to when you view {domain}/our_work/openmedia and both images are different.

For comparison, here is my preview screen in which you can see from the HTML headers that the featured and midway images are different:
![image](https://user-images.githubusercontent.com/102068794/177898255-6340604f-6825-43f7-9ded-2f1a2f97c7c5.png)


And here is the same page rendered on the front end:
![image](https://user-images.githubusercontent.com/102068794/177898307-381ab1d0-efa1-44c6-93a6-cf4af8973716.png)
