### ISSUE TITLE
Update Grid Fields data Programmatically

### ISSUE THREAD

**Issue by afifa-glowlogix** [ExpressionEngine/ExpressionEngine#2123]
I have a channel entry with the "images" field.

The field type is Grid.

What I'm trying to do is add a few pictures in the field through PHP.

I'm using this query to fetch the entry:

```
$entry = ee( "Model" )->get( "ChannelEntry" )
->filter( "channel_id", $channel_id )
->filter( "entry_id", $entry_id )->first()
```

The issue is, that I can access simple fields but the grid is always empty.

I'm not sure how can I access the images in the field or add new images in the field.

Is there any better documentation on model relationships? or a way to achieve this functionality?

Any kind of help will be much appreciated.

**Comment by TomJaeger** [comment]
I think I replied on the stack-exchange question along these lines as well... copied for anyone following along.

Few notes / comments on this one.

Firstly, this is an area we need to get better docs around as a whole..

The following thread has a working example in it that may be of use for you.

https://expressionengine.com/forums/topic/253398

When saving images specifically, I would just confirm their saved correctly in the DB (ex. try saving the same image in the CP and then programmatically to make sure whats saved in the DB correctly.)

**Comment by TomJaeger** [comment]
Also might be worth jumping into slack to see if anyone else has input.

Closing thread here, as it's more of a how to.
