### ISSUE TITLE
Saving New Channel Layout rearranges fields on Publish tab and newly created tab

### ISSUE THREAD

**Issue by melbazany** [ExpressionEngine/ExpressionEngine#2131]
_EE 6.3.4, PHP Version 7.3.23, Google Chrome Version 103.0.5060.114_

When logged into EE and creating a new Channel Layout, I add a new tab to the layout setup. Drag and drop fields (textareas and text inputs) from the Publish tab over to the newly created tab. When I click Save for the New Publish Layout, I receive the confirmation/success that it's been created, but the ordering of the fields on the Publish tab and the newly created tab are completely different from where they were actually placed; some fields that were on the new tab end up on the Publish tab, and vice versa. Doesn't seem to be any correlation of which fields get moved to the new tab, either.

![Screen Shot 2022-07-07 at 11 12 26 AM](https://user-images.githubusercontent.com/75503142/177808804-ca059254-2cbf-4ecf-b5e5-e9cc050ea264.png)
![Screen Shot 2022-07-07 at 11 12 43 AM](https://user-images.githubusercontent.com/75503142/177808803-528c1109-6ce6-4dfb-ba36-9636f8412870.png)

**Comment by robinsowell** [comment]
It also looks like it goobers category groups if you pull them over and save (along with not saving all of them and goofing up the ordering:

<img width="939" alt="Screen Shot 2022-08-12 at 4 21 04 PM" src="https://user-images.githubusercontent.com/1181219/184436720-149c89e5-1d67-4371-9d19-19637b3c7438.png">
