### ISSUE TITLE
preg_match_all(): Passing null to parameter #2 ($subject) of type string is deprecated error with RTE fields in in PHP 8.1

### ISSUE THREAD

**Issue by tyssen** [ExpressionEngine/ExpressionEngine#2132]
> preg_match_all(): Passing null to parameter #2 ($subject) of type string is deprecated
> user/addons/assets/rtefb.assets.php, line 43
> Severity: E_DEPRECATED

This is appearing when publishing new entries on a site running PHP 8.1. It doesn’t appear when editing existing entries.

I've created a test channel with only a RTE field on it, and the error still occurs.

The field is using the basic CKeditor configuration but the error is still there when using any of the other options too, full, Redactor basic, and Redactor full.

**Comment by intoeetive** [comment]
Thank you for the report.
I have passed this on to Assets team so closing the issue
