### ISSUE TITLE
Edit Profile - Dropdown/Select Field Not Working

### ISSUE THREAD

**Issue by nickpuglisi** [ExpressionEngine/ExpressionEngine#2134]
Attempting to use the 'new' Edit:Profile field on our site. I want to manually construct the Select field from the Member Fields section, I understand that there's a bug where I can't call the field_name like normal and have to resort to `m_field_id_6` for each, but nothing I've tried has allows me to actually display the field properly. I've tried: 

## Opener

{exp:member:edit_profile
    return="payments/methods/saved"
    include_assets="no"
    }

## Using Channel Form as a stepping off point 
<select name="my_field_name" id="my_field_name">
  {options:my_field_name}
    <option value="{option_value}"{selected}>{option_name}</option>
  {/options:my_field_name}
</select>

No options returned when using the m_field_id or field_name. 

EE 6.3.4
PHP 8
Ubuntu

**Comment by intoeetive** [comment]
The options are automatically populated only if you use 
```
{custom_profile_fields}
      {form:custom_profile_field}
{/custom_profile_fields}
```
tag. If you construct the form manually, you need to populate the options manually as well
