### ISSUE TITLE
Member fields and checkbox - Value cannot update properly

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#2143]
When you send value of checkbox for a member field, the value is always on and cannot be changed.
To reproduce:
Create a form for member field where a field is a checkbox.
Sending the value to on when the checkbox is checked always works
But if you uncheck the checkbox, the value of the field is never updated in the table. it stay with on value
The value return off when we test on the console before to update the form.
Maybe a member field with bolean is needed?

**Comment by intoeetive** [comment]
@digicali I presume you are talking about front-end forms and creating the input manually.

If you just add checkbox input to the form, deselecting it will make not change (it will act the same as if it wasn't present on the form)

You need to have hidden input of the same name placed before the checkbox to have it reset when unchecked.

I am closing the issue now, if you still believe this is a bug, please reopen with more details (e.g. the template code and how the field is set up in CP)
