### ISSUE TITLE
Possible regression: javascript in templates triggers php strpos error

### ISSUE THREAD

**Issue by areynold** [ExpressionEngine/ExpressionEngine#2144]
After upgrading from EE5 to EE6 (v6.3.4 running on an apache server with php 7.3.33), I started seeing the following error on some of our pages

```
Warning
strpos(): Empty needle
ee/legacy/libraries/channel_entries_parser/Parser.php, line 305
Severity: E_WARNING
```

The warnings were triggered by a bit of javascript in an old partial, and can be reproduced as follows:
```html
<script type="text/javascript">
    var foo = {};
    foo.bar = {};
</script>
```

I was able to work around the issue by restructuring the script:
```html
<script type="text/javascript">
    var foo = {
        bar: {}
    };
</script>
```

This looks very similar to #1083.

_edit: corrected EE version_

**Comment by intoeetive** [comment]
Noting that I wasn't able to replicate this in EE 6.3.5

**Comment by intoeetive** [comment]
Also not replicating in EE7.

Assuming it's not an issue anymore, but if it's still there - please post full template code
