### ISSUE TITLE
Unexplained errors with fluid grids & file fields, can't save entries

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#2145]
I've been getting an unspecified error when submitting entries, and I think I've nailed the problem down to an issue with fluid image grids.

1. Create a new entry.
2. In a fluid fieldtype, insert either a file grid field or a grid field with a file field in it. Make sure there's at least one row of content.
3. Add another grid field. As far as I can tell the content of this second grid field doesn't matter. Make sure there's at least one row of content.
4. The entry will save normally.
5. Return to the entry and add a row to the first grid. Trying to save the entry will now result in an error.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/308752/180301827-886f1e8d-498c-42b3-911b-d339f6ab2feb.png">

There are no indications of what the error is within the fluid field. At the bottom of the fluid field is this:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/308752/180301952-53ddc0af-d139-4a32-b2c1-812589d8fe5d.png">

I've noticed that if the second grid field has radio buttons, the radio buttons have a red border around them:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/308752/180302580-96563418-8381-467b-94a8-ac596ab023b7.png">

Interestingly, as I'm testing now, this field *appeared* with the red border around it. I never submitted the entry with this field in the fluid fieldtype, so I don't know why it has the error applied to it.

If you re-order the fields, so that the grid field with the file in it is no longer is position 1, the entry will save without an error, but the grid field that is *now* in position 1 *will* start throwing errors when you add a row, if it has a file field in it.

EE 6.2.4
PHP 8.0.8

**Comment by jejuna** [comment]
Yeah, me too. I reported this June 1, here:
[https://github.com/ExpressionEngine/ExpressionEngine/issues/2105](url)

It seems to be some odd validation bug. At least I'm not the only one who's got this issue, as it's driving my client insane.

**Comment by matthewjohns0n** [comment]
Just wanted to give a little update on this one. We're making progress on this. I've figured out part of this issue, but not exactly why it's happening yet. We'll get this fixed soon though!

**Comment by matthewjohns0n** [comment]
@murtaugh @jejuna I believe this PR fixes the grid validation issue you're running into. We should be getting this fix into an upcoming release. If you're able to, it would be great to verify this fixes the issues you're running into.

**Comment by jejuna** [comment]
Thanks, I will report back!

**Comment by robinsowell** [comment]
Worst bug EVER!  But Matt's fix killed it in my tests.

**Comment by murtaugh** [comment]
I won’t be able to test until next week, but I’ll let you know. Thanks!

**Comment by murtaugh** [comment]
It looks like it works! Phew!
