### ISSUE TITLE
404 after click on notification in CP

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2151]
I got this notification message after my Mastercard failed: 
![image](https://user-images.githubusercontent.com/12234507/181484246-7afcdd5f-7db9-4091-900d-0f17e1ac1a09.png)

But it leads to 404:
![image](https://user-images.githubusercontent.com/12234507/181484125-263ad0e0-619c-45c2-8f97-2cc23ac14382.png)

**Comment by intoeetive** [comment]
Closing this as we haven't been able to replicate the issue.

Please comment on it, if you still can see it, with more details so we could replicate
