### ISSUE TITLE
Add the ability to display the edit date in the CP entry list table.

### ISSUE THREAD

**Issue by aasun** [ExpressionEngine/ExpressionEngine#2153]
**Is your feature request related to a problem? Please describe.**
Similar to the display and sort-ability of the Date (entry_date) field in the CP entry list, I'd like to have a display and sort-ability of the Last Edit Date (edit_date) field in the CP entry list.

**Comment by intoeetive** [comment]
This has also been requested in #1850

Is implemented in EE7, implementation for EE6 is pending release

#2212 #1975
