### ISSUE TITLE
Relationship dialog loads partially off-screen within Grid 

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2173]
The Relationship field within a grid pops up a dialog box to allow choice of entry to relate to (EE6.3.4).
If this field is too close to the RH window edge when it first loads the dialog is partially off-screen, hiding the action buttons.
A bit of fiddling around sometimes can get the dialog to relocate to be fully within the window, but really it should load this way from the outset.
![image](https://user-images.githubusercontent.com/13821249/182487335-410d6a06-4955-4ead-8cc9-38657918b1cf.png)

**Comment by intoeetive** [comment]
With the latest changes in Grid (including ability to stack the cells vertically) this is no longer relevant. Closing out.
