### ISSUE TITLE
Pagination in CP works even when there is no entries to show

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2178]
Here is how newly registered author sees the CP:

![image](https://user-images.githubusercontent.com/12234507/182568169-55b27490-15ae-4366-b3a2-192c0eae1fc5.png)

There are no entries to edit, but pagination suggests that there are plenty of them.

**Comment by TomJaeger** [comment]
Thanks for submitting this... Few quick questions.

1. What version of EE 6 is this in?
2. Are there existing entries in the system that this user doesn't have access to?

**Comment by shbchk** [comment]
1. Latest, 6.3.4

2. Yes, there are several thousands entries, but this user group can view and edit only their own entries

**Comment by TomJaeger** [comment]
Thank you!

**Comment by intoeetive** [comment]
To replicate this on sites with less than 25 entries, one needs to pass perpage parameter: `admin.php?/cp/publish/edit&perpage=2`

**Comment by TomJaeger** [comment]
Would be awesome to resolve this one.
