### ISSUE TITLE
User gets logged out

### ISSUE THREAD

**Issue by rouviere** [ExpressionEngine/ExpressionEngine#218]
**Description of the problem**
Following upgrade to EE 5.2.3 I get logged out of the control panel after less than 30 minutes of activity - even while creating content.

**How To Reproduce**
1. Check Keep me logged in.
2. Log into Control Panel
3. Work on creating new entry
4. Less than 30 minutes of activity and the login screen appears

**Error Messages**
None

**Screenshots / Videos / Template Code**
None

**Environment Details:**
 - Version: 5.2.3
 - PHP Version 5.6.40
 - MySQL Version 5.5.62-cll
 - OS: macOS
 - Web Server: Apache

In my config file I have the following settings:
...
$config['cookie_prefix'] = '';
$config['cookie_path'] = '';
$config['cookie_domain'] = '';
$config['user_session_type'] = 'c';
$config['admin_session_type'] = 's';
...

**Possible Solution**

**Additional context**

**Comment by robinsowell** [comment]
I think there may be something environmental going on, as I'm not replicating or running into similar reports.

Can you double check and see if the server offset config override is being used?
`
$config['server_offset']`

That could throw things off.

**Comment by rouviere** [comment]
Hi Robin, sorry for the delay in responding. I did not receive a notice of the response. 

server offset is NOT being used. I do continue to get logged out of the control panel though.

**Comment by intoeetive** [comment]
@rouviere are you still expiriencing this issue? What is the current EE version that you're running?

I know that older versions of certain add-ons (including some that are related to tagging content) might cause premature logout when CP session type is "session only" - could that be your case?
