### ISSUE TITLE
When a new channel field is created via the CP, its "site_id" column is always set to 0.

### ISSUE THREAD

**Issue by vstaikov** [ExpressionEngine/ExpressionEngine#219]
**Description of the problem**
When a new channel field is created via the CP, its "site_id" column is always set to 0.

**How To Reproduce**
1. Install EE 5.2.3
2. Create new field
3. Check "site_id" column value

**Possible Solution**
Replace line 467 in: `system/ee/EllisLab/ExpressionEngine/Controller/Fields/Fields.php` 
with: `$field->site_id = ee()->config->item('site_id');`

**Comment by derekjones** [comment]
This is by design so Fields you create can be shared across Sites.
