### ISSUE TITLE
EE7 with .ENV: Exception Caught

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2199]
Hi there!

Just installed a fresh copy of EE7 on my local computer to test ENV file and other stuff. 

ENV is on.

Sometimes in CP I get this:

```
Exception Caught
You must define the following database parameters: username, hostname, database
DBConfig.php:138
```

![image](https://user-images.githubusercontent.com/12234507/182907042-af0ff3c3-55d1-407a-bff3-df6f509a5583.png)

Refreshing helps, but not for long. 

PHP Version 7.4.21
MariaDB 10.4

**Comment by shbchk** [comment]
Updated to EE7.0.1 - same story. Without ENV everything is okay

**Comment by bryannielsen** [comment]
Hi @shbchk, thanks for letting us know about this issue!

Could you share what your `.env.php` file looks like (please make sure to remove sensitive data) and also how you're using these values in your `system/user/config/config.php` file.

Also would you mind sharing the operating system and web server being used?

**Comment by bryannielsen** [comment]
It's possible that you are using names in your `.env.php` file that are conflicting with system environment variables and causing a problem. https://github.com/vlucas/phpdotenv/issues/523 

Please feel free to reopen the issue if you have more details that can help us reproduce.
