### ISSUE TITLE
Entry `url_title` does not match CP/URL `urlSlug` output

### ISSUE THREAD

**Issue by obfuscode** [ExpressionEngine/ExpressionEngine#22]
**Description of the problem**
The Channel Entry URL Title only needs to pass the [`validateUrlTitle`](https://github.com/ExpressionEngine/ExpressionEngine/blob/55ec2e91543b46e9a9fa11e67755e936bdea5a2e/system/ee/EllisLab/ExpressionEngine/Model/Channel/ChannelEntry.php#L357-L370) method and then accepts whatever the user enters so URLs like `ThIs_is.-Cool----....WHAT` save exactly like that whereas the `urlSlug()` method returns `this_is-cool-....what`.

The real-world use case for this is saving a person's name like `J. P. Morgan` which creates an EE URL Title of `j.-p.-morgan` but the [`urlSlug` regex specifically forbids the "dot-hypen" or "dot-underscore"](https://github.com/ExpressionEngine/ExpressionEngine/blob/bc54a3aeceea00f5de9e5468702cacbc5f4f7c83/system/ee/EllisLab/ExpressionEngine/Service/Formatter/Formats/Text.php#L596-L597) (depending on what separator setting you have) so calling `urlSlug` results in `j-p-morgan`.

**How To Reproduce**
1. Create an entry with a Title of "J. P. Morgan"
2. Save Entry
3. Notice the URL Title violates the dot-[separator] rule

**Environment Details:**
 - Version: 5.0.1
 - PHP Version: 7.1
 - MySQL Version: 5.7
 - OS: macOS (Mojave)
 - Web Server: nginx

**Possible Solution**
Pass the URL Title through the CP/URL service on save (and for the JS generation).

**Comment by t1mwillis** [comment]
@kevincupp does the closed tag mean that a fix for this will be released? Thanks.

**Comment by kevincupp** [comment]
Not necessarily. But in this case, there is a commit and a tag of Accepted, so yes.

**Comment by t1mwillis** [comment]
@kevincupp 👍
