### ISSUE TITLE
Publish Layout - randomly reorders fields EE 5.2.2

### ISSUE THREAD

**Issue by CreateSean** [ExpressionEngine/ExpressionEngine#220]
**Description of the problem**
Upgraded an EE2 to EE5 site a couple of weeks ago. Today I added new fields to one channel and went to reorder them using publish layouts and everything got wonky.

Initially on save one field moved correctly and the other did not. I kept trying, but the field did not change (maybe 5 or 6 saves), then 5 minutes later tried again and a random field changed order (not the one I moved). Tried again and a different field this time changed order. 

Kept trying - sometimes nothing moves other times a random field moves.

**How To Reproduce**

1. update EE2 to EE5.2.2
2. create 2 new text input fields
3. reorder them in publish layout
4. see description above

**Environment Details:**
 - Version: [e.g. 5.2.2]
 - PHP Version [e.g. 7.2.17]
 - MySQL Version [e.g. 5.7]
 - OS: Linux (Forge provisioning)
 - Web Server: Nginx

**Possible Solution**

**Additional context**

**Comment by stephengalbraith** [comment]
May not be of help but I remember seeing this on the EE website before in the bugs section and also had it happen to me. The solution that seemed to work was creating a new layout and reordering the fields rather than editing an already existing layout.

**Comment by CreateSean** [comment]
That worked - that's a hack or workaround not a fix though.

However still consider this a bug and it should be fixed.

**Comment by silenz88** [comment]
I can confirm this in 5.2.3.
Not an updated site. V5 from the beginning.

**Comment by ops-andy** [comment]
I'm closing this as it seems to have been resolved with the EE6 Control Panel overhaul. I've tried to replicate in v6 over and over and cannot. Please reopen this issue or ping me if you find the problem to persist in v6. thanks
