### ISSUE TITLE
After upgrade to 5.2.3 Using {parents:parents ... } produces error 

### ISSUE THREAD

**Issue by stasiup** [ExpressionEngine/ExpressionEngine#221]
After upgrade to 5.2.3  from 5.2.2 {paretns:parent} causes an error.
Checked on production and raw install.
eg:
`{exp:channel:entries channel='actions' limit='1' dynamic="yes" status="open"}
                    <h3>{title}</h3>
                    {parents field="rel_actions" limit="1" channel="activity" status="open"}
                        <p>{parents:title}</p>
                        {parents:parents field="rel_activity" limit="20" channel="blog" status="open"}
                        <a href="{path='main/activity'}/{parents:parents:url_title}"><h6>{parents:parents:title}</h6></a>
                        {/parents:parents}
                    {/parents}
{/exp:channel:entries}`

Displaying: 
Actions_Title

{parents field="rel_actions" limit="1" channel="activity" status="open"}
{parents:title}

{parents:parents field="rel_activity" limit="20" channel="blog" status="open"}
{parents:parents:title}

{/parents:parents} {/parents}

**Error Messages**
From Templates debugger:
 Found {parents:parents} relationship, but no parent {parents} tag pair was found.

**Steps to reproduce**
- Raw install EE 5.2.2
- Set some channels with relations one to second to third
- check above code is working
- upgrade to 5.2.3 - code is not working

**Environment Details:**
 - Version: [5.2.3]
 - PHP Version [7.1 and 7.2]
 - MySQL Version [5.7.23]
 - OS: [Linux, macOS]
 - Web Server: [Apache, MAMP]

**Possible Solution**
Downgrade to 5.2.2 ?

**Comment by stasiup** [comment]
Possibly fix:
replace file /system/ee/legacy/libraries/relationship_parser/Tree_builder.php from EE 5.2.2
- there is diff in line 352

**Comment by stasiup** [comment]
It may not have a connection to problem above - who knows, but after the upgrade to 5.2.3 "channel videos" plugin suddenly stopped working. I have a lot of {parents: parents} tags in my templates

**Comment by robinsowell** [comment]
See if the new Tree_builder.php in stability does the trick- see commit: https://github.com/ExpressionEngine/ExpressionEngine/commit/82aeb671619290ce7ab7ade43cf482aabd823aaa

**Comment by aasun** [comment]
I was having these issues with multiple parents tags on the same template after upgrade to EE 5.2.3.  I did the possible fix listed above and it's working again.

**Comment by stasiup** [comment]
commit: 82aeb67 also working for me
