### ISSUE TITLE
Edit > View All shows Fatal error: Uncaught Error: Call to a member function getAllCustomFields()

### ISSUE THREAD

**Issue by breezygrrl** [ExpressionEngine/ExpressionEngine#222]
**Description of the problem**
In the control panel (EE 5.2.3) when i try to go to the View All page under the Edit dropdown, i get this error:

**How To Reproduce**

1. Click Edit
2. Select View All

**Error Messages**

<pre><code>

Fatal error: Uncaught Error: Call to a member function getAllCustomFields() on null in /chroot/home/.../.../system/ee/EllisLab/ExpressionEngine/Model/Content/ContentModel.php:528 Stack trace: #0 /chroot/home/.../.../system/ee/EllisLab/ExpressionEngine/Model/Content/ContentModel.php(107): EllisLab\ExpressionEngine\Model\Content\ContentModel->deleteFieldData() #1 /chroot/home/.../.../system/ee/EllisLab/ExpressionEngine/Model/Channel/ChannelEntry.php(483): EllisLab\ExpressionEngine\Model\Content\ContentModel->onBeforeDelete() #2 [internal function]: EllisLab\ExpressionEngine\Model\Channel\ChannelEntry->onBeforeDelete() #3 /chroot/home/.../.../system/ee/EllisLab/ExpressionEngine/Service/Model/Model.php(825): call_user_func_array(Array, Array) #4 [internal function]: EllisLab\ExpressionEngine\Service\Model\Model->emit('beforeDelete') #5 /chroot/home/.../.../system/ee/EllisLab/Exp in /chroot/home/.../.../system/ee/EllisLab/ExpressionEngine/Model/Content/ContentModel.php on line 528 
</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 5.2.3
 - PHP Version 7.1.22
 - MySQL Version 5.0.12
 - OS: Linux
 - Web Server: Apache

**Possible Solution**

**Additional context**

Only happens when logged in as super admin.

**Comment by robinsowell** [comment]
I'm not able to replicate and I suspect it may be a case of something being 'off' in the database.  

Can you try this- go into system/ee/EllisLab/ExpressionEngine/Controller/Publish/Edit.phpand look around line 167:

```
			// wW had a delete cascade issue that could leave entries orphaned and
			// resulted in errors, so we'll sneakily use this controller to clean up
			// for now.
			if (is_null($entry->Channel))
			{
				$entry->delete();
				continue;
			}

Comment out the $entry->delete(); and let's see if the error is still happening.  So:

```
			if (is_null($entry->Channel))
			{
				//$entry->delete();
				continue;
			}
```
```

**Comment by ops-andy** [comment]
since the EE team was unable to replicate and this is over a year old, I'm going to go ahead and close this. Please let us know if this persists in EE 6. thanks
