### ISSUE TITLE
Not longer possible to access relationship fields from parent entries 

### ISSUE THREAD

**Issue by croxton** [ExpressionEngine/ExpressionEngine#223]
**Description of the problem**
It is no longer possible to access relationship custom fields from the `{parents}` tag pair in EE 5.2.3. This was working in EE 3.x. Subsequent template code is not parsed, but no errors are displayed.

**How To Reproduce**

    {exp:channel:entries entry_id="1"}
	
	    {!-- list parents --} 
	    {parents field="cf_a_related_field_in_parent_channel"}

		{parents:title}

		{!-- for each parent entry, list related entries (i.e. siblings of original entry) --} 
		{!-- this code stops subsequent template rendering --}
		{parents:cf_a_related_field_in_parent_channel}

			{parents:cf_a_related_field_in_parent_channel:title}

		{/parents:cf_a_related_field_in_parent_channel}

	    {/parents}

    {/exp:channel:entries}

**Error Messages**
None. Subsequent template code is not parsed.

**Environment Details:**
 - Version: 5.2.3
 - PHP Version 7.1
 - MySQL Version 5.7.20
 - OS: macOS
 - Web Server: Apache

**Comment by robinsowell** [comment]
I'm not sure it will address this issue, but can you try this recent commit that did fix some relationship parsing issues: https://github.com/ExpressionEngine/ExpressionEngine/commit/82aeb671619290ce7ab7ade43cf482aabd823aaa

**Comment by croxton** [comment]
Good news - I can confirm that works!

**Comment by robinsowell** [comment]
Whew!  Thanks for the test.  The issues manifested a bit weirdly, but it all related to variables not getting parsed..
