### ISSUE TITLE
PHP 8.1.8 Warning with EE7.03 on Timestamp column

### ISSUE THREAD

**Issue by clifavenu** [ExpressionEngine/ExpressionEngine#2233]
Using current version of EE7.0.3 and PHP 8.1.8 throwing warnings when cloning an entry. Full warnings below

Deprecated
strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated

ee/ExpressionEngine/Service/Model/Column/ColumnObject/Timestamp.php, line 52

    Severity: E_DEPRECATED

Deprecated
strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated

ee/ExpressionEngine/Service/Model/Column/ColumnObject/Timestamp.php, line 52

    Severity: E_DEPRECATED

Deprecated
strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated

ee/ExpressionEngine/Service/Model/Column/ColumnObject/Timestamp.php, line 52

    Severity: E_DEPRECATED

Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)

ee/legacy/core/Input.php, line 266

    Severity: E_WARNING

Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)

ee/legacy/core/Input.php, line 266

    Severity: E_WARNING

Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)

ee/legacy/core/Input.php, line 266

    Severity: E_WARNING

Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)

ee/legacy/libraries/Functions.php, line 458

    Severity: E_WARNING

**Comment by intoeetive** [comment]
Hi @clifavenu 

what fields (fieldtypes) do you have in the entry that's being cloned?

**Comment by clifavenu** [comment]
Hi Yuri,

  First noticed it with an entry with relationship, select, grid, fluid, 
wygwam, radio and files fields.

Just checked another channel with just a textarea field type with the 
same warning.

Thanks,
clif
***@***.***

**Comment by intoeetive** [comment]
Do you have any custom tabs or anything? Mostly interested in the fields that involve date inputs

**Comment by clifavenu** [comment]
The only add-ons at this time are wygwam and safeharbor. Otherwise all 
core, and all are current releases.

As mentioned in the last email, it's throwing the warning on a channel 
with only a textarea field type. That's the simplest input, but all our 
channel entries have the same results regardless of field types.

It does create the clone, but with warnings.

**Comment by clifavenu** [comment]
I can give you access if you want. If so, please contact me directly.

**Comment by robinsowell** [comment]
@intoeetive I spotted the problem.  When you clone, recent_comment_date goes into exp_channel_titles as NULL.  Should be 0.  Actually, looks like the default templates put it in as NULL as well.  

But in any case- the null throws the strtotime() error in php 8.1.  You may/may not see it depending on how the redirect reacts to the warning, but it's there.

Didn't fix it because I wasn't sure where that should happen.
