### ISSUE TITLE
Error when upgrading from 6.3.4 to 6.3.5

### ISSUE THREAD

**Issue by tyssen** [ExpressionEngine/ExpressionEngine#2241]
I wanted to test upgrading our site to EE7. I ran the process locally and upgraded from 6.3.4 to 6.3.5 first and then to 7.0.3 no problem.

But when I attempted the same thing on our staging server, the updater failed at the 6.3.4–6.3.5 stage with:

> Fatal error: Uncaught Error: Call to undefined function ExpressionEngine\Library\Filesystem\exec() in /ee/ExpressionEngine/Library/Filesystem/Filesystem.php:260
> Stack trace:
> #0 /ee/ExpressionEngine/Library/Filesystem/Filesystem.php(173): ExpressionEngine\Library\Filesystem\Filesystem->attemptFastDelete()
> #1 /ee/updater/ExpressionEngine/Updater/Service/Updater/Runner.php(165): ExpressionEngine\Library\Filesystem\Filesystem->deleteDir()
> #2 [internal function]: ExpressionEngine\Updater\Service\Updater\Runner->updateDatabase()
> #3 /ee/updater/ExpressionEngine/Updater/Service/Updater/SteppableTrait.php(94): call_user_func_array()
> #4 /ee/updater/ExpressionEngine/Updater/Service/Updater/Runner.php(316): ExpressionEngine\Updater\Service\Updater\Runner->runStepParent()
> #5 /ee/updater/ExpressionEngine/Updater/Controller/Updater/Updater.php(34): ExpressionEngine\Updater\Service\Updater\Runner->runStep()
> #6 /ee/updater/boot.php(96): ExpressionEngine\Updater\Controller\Updater\Updater->run()
> #7 /ee/updater/boot.php(70): routeRequest()
> #8 /home/softlink/staging.softlinkint.com/public_html/admin.php(144): require_once('/home/softlink/...')
> #9 {main}
> thrown in /ee/ExpressionEngine/Library/Filesystem/Filesystem.php on line 260

Locally I'm running PHP 8.0.0. Staging is on 8.0.21. MySQL is 8.0.16 locally and 8.0.21 staging.

**Comment by bryannielsen** [comment]
@tyssen thanks for letting us know about this issue!  It seems like your staging environment may have `exec()` listed as a `disable_functions` in your `php.ini` file.  Do you have control over the PHP configuration or is this a shared host?  Ideally you will want to allow the `exec()` function to run because it is also being used for image manipulations (crop, resize, etc...). 

Also if it's easier to view your `phpinfo()` output there should be a section under **Core** called `disable_functions` where you can confirm that exec is being disabled by your config.

**Comment by tyssen** [comment]
@bryannielsen I found in cPanel where to remove `exec` from `disable_functions` and have been able to complete the upgrade to 6.3.5 on staging. I'm not able to authenticate with the licence key on staging to be able to update to 7.x, but that's a separate issue.

**Comment by bryannielsen** [comment]
Thanks for the update @tyssen, I'm glad you were able to finish the update with that change!  

If you're having issues with a license key please send an email to support@expressionengine.com with the details and we should be able to get that sorted out for you.

**Comment by TomJaeger** [comment]
What version of PHP are you running on the server?

**Comment by tyssen** [comment]
@TomJaeger Sorry, I don't actually remember which site this was for anymore, lol.
