### ISSUE TITLE
SEEO - Existing File

### ISSUE THREAD

**Issue by clifavenu** [ExpressionEngine/ExpressionEngine#2260]
Hi,
We've run into a minor bug using SEEO 1.7.1, EE7.0.3 and php 8.1.8.

SEEO => Settings => OG or Twitter. Uploading an image from an existing opens the file mgr. Upon selecting a sub-folder, thrown to Files and no way back to the SEEO setup. Looks like sub-folders not working with the seeo.

Thanks,
clif

**Comment by robinsowell** [comment]
Thanks for the heads up- EE Harbor dev is taking a look at it, we do replicate.  I'm closing it out in the EE issues, but it's on the internal tracker for SEEO.  I think they have the image stuff fixed and under review- not so sure about the subfolder.
