### ISSUE TITLE
EE7.0.3 -> Color Picker Field not displaying correct in entry

### ISSUE THREAD

**Issue by karlosb** [ExpressionEngine/ExpressionEngine#2279]
Color Picker Field is not displaying correct in entry.

The field does not display a colour swatch icon or a drop down colour pallette, and appears to be a blank unformatted field.

**How To Reproduce**

**Environment Details:**
 - Version: ee 7.0.3
 - PHP Version 7.4 (or 8.1)
 - MySQL Version [e.g. 5.7]
 - OS: macOS
 - Web Server: Local DDEV nginx-fpm

**Comment by karlosb** [comment]
Hi Guys, the color picker still has the correct formatting now and displays a pop colour pallete. But the existing entry hexadecimal values in the color picker field do not show and still show a blank field.

**Comment by mattrandles** [comment]
Hi, i'm still seeing this on 7.1.2 when the color picker field is in a grid as a fluid field. Additionally, when added to the entry in a fluid field, the color picker in the grid fails to open until the entry has been saved.

**How To Reproduce**
Steps to reproduce the behavior:
Create a grid field, displayed vertically that has a color picker in it (not a required field).
Allow a fluid field to use the newly created grid field. 
Go to an entry and add new grid to the fluid field content.
The color picker won't open until the entry has been saved, and saved values won't display on load, causing an empty response.

**Environment Details:**

Version: ee 7.1.2
PHP Version 8.0.19
MySQL Version 10.6.7-MariaDB
OS: macOS
Web Server: Apache2.4 Devilbox docker
