### ISSUE TITLE
Categories do not save with new entries

### ISSUE THREAD

**Issue by rouviere** [ExpressionEngine/ExpressionEngine#228]
**Description of the problem**
When I create new entries on the site and select a category for the entry, Expression Engine does not save the category selection. After saving the entry and returning to the Categories tab, nothing is selected.

**How To Reproduce**

1. Create new entry
2. Click Calories tab
3. Select a category
4. Save the entry
5. Click on the categories tab again - no category is selected.

**Error Messages**
None

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 5.2.3
 - PHP Version 5.6.40
 - MySQL Version [e.g. 5.7]
 - OS: Linux
 - Web Server: Apache

**Possible Solution**

**Additional context**
The only thing I can think of that may be influencing this is that this site was separated out from a MSM configuring to a stand-alone site. That being said, everything else works correctly on the site. All category information be breakout is saved with the entries.

**Comment by derekjones** [comment]
What browser and version are you using, and are there any JS errors in the console?

**Comment by rouviere** [comment]
Safari 12.1.1 is the browser and the errors are attached.

![Screen Shot 2019-06-11 at 2 23 05 PM](https://user-images.githubusercontent.com/4437546/59304000-abdc6500-8c54-11e9-9082-563bfb54d569.png)

**Comment by derekjones** [comment]
That looks like it's from a browser extension, that's not an ExpressionEngine JS file. Can you try disabling all browser extensions and trying to save an entry again? I use Safari myself and have never had any problems. I have seen some extensions—like LastPass for instance—completely wreck checkboxes in forms.

**Comment by rouviere** [comment]
I disabled all Safari extensions and the problem persists. I also tried it in Chrome and it doesn’t save category selections either, so I am thinking is must be something other than the browser.

**Comment by rouviere** [comment]
Interesting note. I tried using the bulk add categories option and that worked.

**Comment by derekjones** [comment]
Interesting, and good debugging. What add-ons do you have installed? Perhaps it is an add-on that interacts only with the Publish page that is causing an issue.

**Comment by rouviere** [comment]
These are the current Add-Ons:

**Comment by derekjones** [comment]
Don't think that cut and paste worked... ;)

**Comment by rouviere** [comment]
Hope this works better.

BBD Chopper
BBD Hon:EE
Freeform
GWCode Categories
Low Seg2Cat
SEO Lite
Sitemap
Wygwam

**Comment by derekjones** [comment]
Some of those add-ons are not compatible with v5, is this an upgrade? Did you update those add-ons for compatibility?

**Comment by rouviere** [comment]
Looks like the ball is in my court. I’ll tidy up there and report back.

**Comment by rouviere** [comment]
I have it down to: Freeform, SEO Lite, Sitemap and Wygwam. The problem persists so I disabled all extensions in the config file and alas it still persists

**Comment by derekjones** [comment]
And you've updated SEO Lite and Wygwam to the latest versions? If you need help troubleshooting, you can always engage EllisLab or others in the community for direct assistance.

**Comment by rouviere** [comment]
Yes. They are the latest versions.

**Comment by derekjones** [comment]
Sorry I'm stumped helping troubleshoot from afar. If you have steps that would allow someone else to reproduce on a fresh install, please let us know and post them here.

**Comment by rouviere** [comment]
Thank you for your time and for your efforts. Fortunately I have an alternative until I can get it worked out.

**Comment by robinsowell** [comment]
I just wanted to note, I ran into this with someone in support and it ended up being database corruption. It may not be relevant, but it's worth a check.

The group id associated with some of the categories in exp_category_field_data were incorrect- they should match up to the group_id in exp_categories.

Take a look at those two tables and see if you spot a category id with one group id in exp_categories and a different one in exp_category_field_data. Find anything?

**Comment by rouviere** [comment]
That was it. The site ID was mismatched. It was set to 3 in one and 1 in the other. When I set them all to Site ID 1, the problem was fixed.

Thank you so much for the diligence. The follow up is greatly appreciated.

**Comment by robinsowell** [comment]
Good catch checking site_ids as well.

Weird one- I've never seen it before.  If it crops up again, I'd really like to pinpoint how it's getting out of sync.  But for now- glad that's got it working.
