### ISSUE TITLE
Exception shown after creating select field populating from other field, but no source field selected

### ISSUE THREAD

**Issue by freaksarise2** [ExpressionEngine/ExpressionEngine#2285]
Hi. I was in the process of making a new field (single selection pulldown type). I was about to prepopulate the field's options with another channel and remembered that I had yet to make the channel. I went over to a new tab to make the channel and then came back. In order to see the new channel as an option, I refreshed the browser and since that step, I can no longer access any fields in the CP. Upon attempting to create or edit a field, I receive the error "Unknown field ChannelEntry.field_id_0" followed by "ee/ExpressionEngine/Service/Model/Query/Select.php:709". I will attempt to post a screen shot of the trace also.  

Thank you for any help. 

![eeFieldErrorTrace](https://user-images.githubusercontent.com/45470099/185174189-28c7099b-d756-4e13-93ca-dd6d91f453e3.jpg)

**Comment by TomJaeger** [comment]
Thanks for passing this along.

Any chance you know what version of ExpressionEngine and PHP your running?

**Comment by freaksarise2** [comment]
Oh Jesus, I was just sitting here and realized I forgot to include that. Sorry. Its EE Pro v6.3.4. In case it matters I have query installed, and low search installed. And PHP Version 7.4.30. Thanks!
