### ISSUE TITLE
Upgrading from 6.3 to V7 - error

### ISSUE THREAD

**Issue by 10on12** [ExpressionEngine/ExpressionEngine#2292]
V6.3 PHP 7.4 – atempting to upgrade to V7

• Safari only displaying this error.

• Firefox displaying this error at the top of the control panel - control panel displayed below with version 7.0 listed as installed.

Notice
unserialize(): Error at offset 0 of 42 bytes

ee/ExpressionEngine/Service/Model/Column/Serialized/Native.php, line 27

    Severity: E_NOTICE

Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)

ee/legacy/core/Input.php, line 266

    Severity: E_WARNING

Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)

ee/ExpressionEngine/Boot/boot.common.php, line 476

    Severity: E_WARNING

**Comment by intoeetive** [comment]
This should be fixed with the referenced PR once EE 7.1 is out (really soon!)
