### ISSUE TITLE
EE7.1 Deferred Relationships not working as expected

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#2297]
I'm not entirely sure this is working as expected. Below is a video of my CP page loading, and it's hard to tell exactly when the page render is done, but you can see "Edit Relationships" pop up for a quick second, then it turns into the "Relate Entry" button, but I had not clicked on "Edit Relationships" yet and the React field is immediately initialized.

https://user-images.githubusercontent.com/53965/185468827-98e70774-9bf3-4dcc-9691-4051cf4fd9e1.mp4

**Comment by litzinger** [comment]
I still don't see this working as expected. I updated to 7.1.1, cleared cache, and I tested in Safari and Chrome. Re-saved the field's settings so the deferred toggle is on, and the field always loads the React component immediately. The Edit Relationships button is never present.

**Comment by intoeetive** [comment]
@litzinger This is how it worked in the original PR. However I think I know what has caused that, and I believe that's kind of "big typo" - block of the code that should not be there. Referenced commit should be fixing it.

@Yulyaswan please review, if all is good - then we need same change in the PR for 6.x #1882

**Comment by litzinger** [comment]
I need to go back and update my original PR? At this point though it's extremely outdated.

**Comment by intoeetive** [comment]
@litzinger do not worry, we'll do that (and hopefully merge into 6.x soon)

**Comment by litzinger** [comment]
Deleted last comment, I misread it and realized it wasn't addressed to me and got really confused. Sorry about that.

**Comment by litzinger** [comment]
I just updated to 7.1.2, and I'm still seeing the same behavior. An existing entry with a field with an already assigned relationship immediately loads React instead of displaying the related entries and the Edit Relationships button. A field with no assigned entries, e.g. when creating a new entry, does show the Edit Relationships button.

**Comment by litzinger** [comment]
If I remove the `&& empty($selected)` in the conditional that was added recently I can see the field displaying on page load as expected. It shows a related entry, and the Edit Relationships button, but the React is still immediately taking over and making the field active without getting a chance to click on Edit Relationships.

**Comment by intoeetive** [comment]
No idea how that happened ;(

The change was in https://github.com/ExpressionEngine/ExpressionEngine/commit/f66c8b2cb092fc7b9269590eeb2f1a71b05cb583 but did not make it through in the merge commit.

Thank you for bringing attention, we'll have this included (once again!) in 7.1.3
