### ISSUE TITLE
Channels' Publish Layouts don't respect non-Primary member roles

### ISSUE THREAD

**Issue by mcfarlandonline** [ExpressionEngine/ExpressionEngine#2298]
EE 6.3.5
PHP 7.3.33

I have a website where all the members need to have the same Primary role so they can access a front-facing intranet. However, some of those members also need Site Admin clearance, so they're assigned those roles, too. (But only the minimum access role as their "Primary" role). 

I just noticed today, that the channel Publish Layouts don't honor the secondary member roles when they're selected. So my Site Admins aren't actually benefiting from a custom/clean interface.

**Comment by TomJaeger** [comment]
Just to make sure we follow, users with the Super Admin role are getting the Super Admin publish layout, even if that's NOT their primary role?

**Comment by mcfarlandonline** [comment]
No, it seems even for the Super Admins, that if they're Primary Role is something else, they don't get the Super Admin publish layout. 

So, for example, this is my Super Admin's role setting...
> (Not pictured: in addition to Super Admins, the Member Portal role is reiterated/checked in the "secondary" Roles checkbox menu). 
<img width="952" alt="Screen Shot 2022-08-18 at 1 39 58 PM" width="500" src="https://user-images.githubusercontent.com/20441129/185490592-866e175a-b282-4337-9e06-3de27824735d.png">

And this is the channel's Publish Layout setting...

<img width="404" alt="Screen Shot 2022-08-18 at 1 40 17 PM" src="https://user-images.githubusercontent.com/20441129/185490920-d666b533-22f7-446a-afbc-85ac02d6090a.png">

But my Super Admin doesn't reap the benefits of this layout.

**Comment by intoeetive** [comment]
I can confirm that the layouts are assigned based on primary role (as the member can have multiple roles and we don't have system which would allow selection of layouts for member)

However it makes sense to pick the layout from secondary role, if the primary one does not have layout assigned
