### ISSUE TITLE
Control Panel "My Profile" page doesn't allow "https" URL scheme

### ISSUE THREAD

**Issue by h3xl3r** [ExpressionEngine/ExpressionEngine#23]
**Description of the problem**
In the Control Panel navigating to "My Profile" from the top-left current user drop-down, trying to update the "Custom Field > URL" with anything starting with "https://" results in a validation error 
`Your URL must begin with a valid scheme:`

**How To Reproduce**
- Click on top left username drop down
- Select "My Profile"
- Scroll down to "URL" and enter an URL with https:// scheme
- Try to submit/savesave

**Error Messages**
<pre><code>
Your URL must begin with a valid scheme: 
</code></pre>

**Screenshots / Videos / Template Code**
![screen shot 2018-11-27 at 10 28 47](https://user-images.githubusercontent.com/2123/49052664-2b15c880-f230-11e8-8e81-c1ab4b5a3aa5.png)

**Environment Details:**
 - Version: 5.0.1
 - PHP Version 5.6.38

**Comment by jmathias** [comment]
That is a custom member field, when setting it up you should see an option to allow `https://` schemes as well as several others.

I'm unable to replicate your bug, unless I turn off that scheme for my custom URL field.

You can edit your custom member fields under Members > Member Fields

**Comment by h3xl3r** [comment]
OK, I see. Thing is, I didn't set up this field. It was just magically there ever since I installed and since upgraded from Expression Engine 2.x and associated forum module.

**Comment by jmathias** [comment]
Are you able to get it working by editing the field under Members > Member Fields?

**Comment by h3xl3r** [comment]
Actually, no. "https://" was already checked there under "Allowed URL Schemes"

![screen shot 2018-11-27 at 10 52 49](https://user-images.githubusercontent.com/2123/49053240-b98b4980-f232-11e8-816b-840f68d86b18.png)

**Comment by h3xl3r** [comment]
Un-checking it here, saving, then re-checking it and saving again did the trick though.

**Comment by jmathias** [comment]
Great! I was just going to recommend doing that.

**Comment by h3xl3r** [comment]
Well, ok. It is fixed for **me** now.

Have to admit though, if my code didn't recognize an option that is clearly begin displayed as enabled in the UI, I'd still call it an "issue". And not an _invalid_ one at that.

**Comment by jmathias** [comment]
Unfortunately without steps to reproduce we don't have anything to take action on. 

I cannot reproduce this issue on a fresh install, nor an install that has been upgraded over time from version 2. 

It appears to me that this was likely a fluke with your install. The fact that the equivalent of turning it off and on again fixed the issue tells me that it the neither the UI or feature is actually broken, just that at some point the UI got the flag to check that input, but the DB never got the right value inserted. So when the field was edited and it validated it didn't see the right value and failed the check.

If you have explicit steps that I can take that will reproduce this issue on a fresh install, I will be happy to reopen this issue and investigate further.
