### ISSUE TITLE
404 error after accepting file change notice

### ISSUE THREAD

**Issue by tymrtn** [ExpressionEngine/ExpressionEngine#230]
**Description of the problem**
Upon completion of the updater on EE 5.x, if a change is detected in either admin.php or index.php it shows a warning at the top right of the Control Panel. If I click the Accept button, it directs me to a 404 error page. 

**How To Reproduce**
1. Run an update on EE 5.x from an earlier version to the latest.
2. If a change to admin.php or index.php is detected, review the warning notice at the top right.
3. Click Accept button

**Error Messages**
404 error. URL is:
<code>http://www.mydomain.com/admin.php&S=179cb9a9eb8b8e96d3749149a0175f6e9a31a65d
</code>
Note the '&' instead of '?'

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 5.2.3
 - PHP Version 7.1
 - MySQL Version 5.7

**Possible Solution**
Go back in browser or replace & with ? in the URL

**Additional context**
Note that I did not actually make any changes to the index.php or admin.php files in this case. Both were copied directly from the ExpressionEngine 5 install folder via FTP.

**Comment by intoeetive** [comment]
I wasn't able to replicate this in 5.3.1 to 5.3.2 upgrade
