### ISSUE TITLE
Selectable Buttons - default tag / single value returns label not value

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2302]
If you define a selectable button field, limit it to a single value, and then access this field value within a template, the default response appears to be the button label rather than the button value.

So - if a field `animal_characteristics` is defined with an option pair
`cats -> cats eat chicken`

When the value is accessed in a template, the tag `{animal_characteristics}` returns `cats eat chicken`.
The value returned when accessed using the tag `{animal_characteristics:value}` is `cats`.

This behaviour is different from the default behaviour suggested by [the documentation](https://docs.expressionengine.com/v6/fieldtypes/selectable-buttons.html#single-items).

EE6.3.5.

**Comment by intoeetive** [comment]
We have updated the documentation to properly describe the behavior
