### ISSUE TITLE
Channel Form not processing changes in Default Template Group index

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#2311]
I have a Channel Form in the 'index' template of the site's Default Template Group.
It submits and reloads the page okay, but the changes are not being made to the Entry.
However, if I try either of the following it works fine:
1) Adding "index.php" to the "URL and Path Settings > Website Index Page" field in the CP Settings.
....or...
2) Trying the same Channel Form code on another Template.

EE 6.3.4
PHP 7.4

**Comment by intoeetive** [comment]
@ic360-com I wasn't able to replicate this with a basic channel form.
Could be related to specific fields you are using or extensions that you have. Or specific configuration.
Is there a chance you could narrow down the problem?

**Comment by ic360-com** [comment]
I'll see if I can test this again... and will get back to you. Thanks.

**Comment by intoeetive** [comment]
@ic360-com do you have any update on this?

**Comment by ic360-com** [comment]
Hi Yuri,
Sorry, no, I've not been able to get back into this project. Please assume it's something wrong with my Templates... as it was worked fine for you.
I'm going to be updating this project to EE7 at some point anyway.
Thanks a lot.
