### ISSUE TITLE
Conditional Field starting status with radio buttons

### ISSUE THREAD

**Issue by PhilBrienesse** [ExpressionEngine/ExpressionEngine#2312]
Simple channel set up with a radio button field and 2 conditional fields which show or hide based on the value of the radio button.
radio button field with two values 'basic' or 'complex'
Their are 2 conditional fields on the entry one shows when the radio button is basic and the other shows when it is complex.
When the edit entry page first loads neither conditional field is displayed. You have to change the radio button to get a field to show and then change it back if you needed the default type.
It should load with the default radio button field showing. In this case 'basic'

EE 6.3.5

**Comment by intoeetive** [comment]
@PhilBrienesse can you post a screenshot of how the field conditionals look like?
