### ISSUE TITLE
Color picker does not reload saved value

### ISSUE THREAD

**Issue by andysh-uk** [ExpressionEngine/ExpressionEngine#2326]
I have added a color picker to a field group, which is assigned to a few channels.

Choosing a colour and saving it is fine - the colour shows up on the website correctly.

However when I edit the entry again, the existing saved colour does not load, so when the content item is re-saved, the colour is lost.

My colour picker is set to "Any" and this happens whether I choose a colour from the picker, enter a value like "000000" or "#000000".

ExpressionEngine version: 7.1.2
PHP: 8.1.7
Web server: Nginx
Web browser: Chrome

**Comment by intoeetive** [comment]
@andysh-uk would you be able to pick up the files from this PR, replace the files on your system and check whether that solves your issue?
