### ISSUE TITLE
Outgoing Email SSL failure warnings EE 6.3.5

### ISSUE THREAD

**Issue by captainFishcake** [ExpressionEngine/ExpressionEngine#2329]
Bug report with regard to outgoing email. PHP version 8.0.22. I recently changed the outgoing email settings from PHP mail to SMTP with connection type SSL. It was working fine with no errors with earlier EE version 6.3.x. But since upgrading to version 6.3.5 when I send a test message from the website contact form the message goes through, as before, but I get SSL failure warnings along with the standard send confirmation message – see screen-grab below

![Screenshot 2022-08-24 at 13 07 41](https://user-images.githubusercontent.com/15526069/186424820-8ac405d1-5560-4d8c-8f43-5c556ffb8efa.png)

My contact form template code is:
```
    {exp:email:contact_form user_recipients="no" recipients="" charset="utf-8" redirect="2" return="contact/thanks" form_id ="contactForm" form_class="contentLight cornerRad"}
       
            <p>
                <label for="from">Your Email:</label><br>
                <input type="email" id="from" name="from" maxlength="35" required placeholder="Your email address is required"/>
            </p>
            <p>
                <label for="subject">Subject:</label><br />
                <input type="hidden" name="subject" value="Contact from website: "/>
                <input type="text" id="subject" name="subject" placeholder="Enter a subject (optional)"/>
            </p>
            <p>
                <label for="message">Message:</label><br>
                <textarea id="message" name="message" rows="10" placeholder="Type your message here"></textarea>
            </p>
            <p>
                <button type="submit">Send your message</button>
            </p>
        </section>
    {/exp:email:contact_form}
```

Outgoing email settings are:
Protocol: SMTP
Email newline character: \n
Connection type: SSL (ssl://)
Mail format: plain text
Word-wrapping: enabled

**Comment by robinsowell** [comment]
Hrm- haven't seen that one before.  In a search, it typically looks like a bad setting.

Do this- I always test in the CP Communicate page, it's simplifies things.  Make sure you set the 'from' email with something from the domain you're sending for.  See if using tls works better in the settings.  Triple check your password, etc.  If that doesn't work- what host/mail server?

**Comment by captainFishcake** [comment]
Hi Robin,

Thanks for your message. Problem solved – I cleared all browser cached data
which seems to have fixed the problem. Must have been some cookie settings
were causing the problem.

Best regards,
Ben Plewes


Cogito Creative Ltd is a company registered in England and Wales
Registered number: 07757347 Registered office: 20 - 22 Wenlock Road,
London, England, N1 7GU
