### ISSUE TITLE
Add a link to open up a child related entry from the parent edit entry screen

### ISSUE THREAD

**Issue by dankingsley** [ExpressionEngine/ExpressionEngine#2330]
**Is your feature request related to a problem? Please describe.**
When editing an entry which has child related entries, it's a pain to be able to get into one of those entries to edit them.

**Describe the solution you'd like**
Being able to jump across either with a modal window, or just a link to open the entry itself from the parent entry to a child related entry would be great!

**Describe alternatives you've considered**
The only alternative is for the user to go to the channel list, select the channel and then find the related entry - this might not always be that simple if the entries are all fairly similar.

**Comment by intoeetive** [comment]
This has been implemented in https://github.com/ExpressionEngine/ExpressionEngine/pull/2380 and released
