### ISSUE TITLE
Cannot delete category when editing entry

### ISSUE THREAD

**Issue by gabrudan** [ExpressionEngine/ExpressionEngine#234]
**Description of the problem**
Logged out of the system when trying to delete a category while editing an entry 

**How To Reproduce**
1. Edit entry
2. Go to Categoiry tab
3. Turn on Manage Categories
4. Click on delete icon for category 
5. Confirm removal

**Error Messages**

Front end: "Your administration access session has timed out. Please use the form below to log back into your control panel."

Error log:  "POST /admin.php?/cp/categories/remove-single/ HTTP/2.0" 500

**Environment Details:**
 - Version: 5.2.3
 - PHP Version: 7.2.19
 - MySQL Version: MariaDB 10.1.40
 - OS: Windows
 - Web Server: Apache

**Comment by derekjones** [comment]
Hi @gabrudan, I do not replicate. Is this a fresh install without any add-ons? Also what browser and version are you using?

If you are getting that error on other form submissions, I would double check your server, PHP, and member Localization (date/time) settings, as well as your system clock; that can happen erroneously if any of those things are off as it can prematurely delete your session cookies.

**Comment by gabrudan** [comment]
This not a fresh install - it was upgraded from version 2 and many add-ons. This is the only form that logs us out.

Using Chrome Version 75.0.3770.80.

**Comment by derekjones** [comment]
The upgrade portion wouldn't affect anything, but it's possible that one of your add-ons is. I would try eliminating them one by one in a test environment until that behavior goes away, starting your focus on extensions.

If you're able to reproduce with steps on an installation without any add-ons, please let us know, but this appears to be external in nature.

**Comment by gabrudan** [comment]
I uninstalled all add-ons and I still have the issue. Any other suggestions?

**Comment by derekjones** [comment]
If you've eliminated all of the potential date/time exclusions I mentioned before, then perhaps browser extensions? Our team is not reproducing this behavior in Safari, Chrome, or Firefox.

**Comment by gabrudan** [comment]
At this point I think it is an upgrade issue - all upgraded sites have the same issue (different add-ons)

1. I tested in latest Firefox and latest Edge (no extensions) - same issue
2. I setup a test site on the same server with a fresh EE install, same add-ons - no issue
3. I checked date time setting - they are the same
   - member date/time use site default
   - site set to Canada/Toronto
   - system clock set to Eastern Time (US & Canada)
   - PHP timezone America/Toronto

**Comment by derekjones** [comment]
Good debugging. I can't imagine what upgrading would have to do with that, however; and it doesn't happen on the official expressionengine.com site (which is also upgraded) or two of my personal sites that were also upgrades. Do you have any console errors? Perhaps make sure $debug is set to 1 in your admin.php file (or system/index.php if you're using that) and check the XHR's response. I wonder if you have a PHP or MySQL error in an Ajax call that is causing the response to throw an errant error.

**Comment by gabrudan** [comment]
I have the debug on. The console and XHR show the same error I see on the server - 
internal server error on  admin.php?/cp/categories/remove-single/

**Comment by derekjones** [comment]
Check the web server error logs, a 500 error means a crash of some sort, and PHP can't generate any relevant errors at that point.

**Comment by gabrudan** [comment]
I had the web hosting admin look at this and couldn't find anything else in the error logs.  

I also tested on a different hosting envirenment :

- setup a Nexcess EE shared hosting account and moved one the sites.  
- tested with all add-ons -  **same issue**
- removed all add-ons and tested again -  **same issue**

What else can I do? Happy to give you access if you'd be kind to have a look.

**Comment by derekjones** [comment]
See if [this issue](https://github.com/ExpressionEngine/ExpressionEngine/issues/228#issuecomment-504546662) identifies the problem.

**Comment by gabrudan** [comment]
Nope, that's not it. 

The site I am testing is very simple - one category group and 4 categories. group_id is 1 and site_id is 1 in all tables: exp_category_groups, exp_categories, exp_category_field_data,

**Comment by derekjones** [comment]
There must be an error logged somewhere associated with that 500 error. On Nexcess definitely, you can look at the Apache Error Log and you'll find an entry associated with that request.

**Comment by gabrudan** [comment]
PHP Error log is empty
Web Server Error log is empty
Web Server Transfer log show the following:

[25/Jun/2019:14:10:19 -0400] "POST /admin.php?/cp/categories/remove-single/ HTTP/1.1" 302 - "http://domain.com/admin.php?/cp/publish/edit/entry/42&S=4ee417fab39c0dbf3e4ff6093081b03b" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"

[25/Jun/2019:14:10:19 -0400] "GET /admin.php?/cp/login&return=YTn24sNUukqkD4Q8NXHtO0ssfxTbv3Rm%2FB25gS8D%2B15zmfeDfo5nxEqe7egObAvidQ3mImo%2BTjTvL2AZ3Xc5zwBJJqF4Kf63tjbzCC8oIPo%3D HTTP/1.1" 200 10 "http://domain.com/admin.php?/cp/publish/edit/entry/42&S=4ee417fab39c0dbf3e4ff6093081b03b" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"

**Comment by derekjones** [comment]
I thought you said you were getting an "Internal Server Error"? Neither of those status codes would throw that, 302 is a redirect, expected after posting, and the following page is a 200 OK response.

**Comment by gabrudan** [comment]
Yeah I noticed that too but it still logs me out. It showed 500 on our hosting,

**Comment by derekjones** [comment]
That's as far as I can help here, then, it sounds like you have something else going on. If you'd like someone on the ExpressionEngine team to debug your environment, you can check out our [support options](https://expressionengine.com/support).

**Comment by gabrudan** [comment]
Will do. Thank you.

**Comment by derekjones** [comment]
Confirmed that it occurs when running with Session IDs in the URL instead of "Cookies Only". Fixed by 48970d1
