### ISSUE TITLE
Getting warnings when using Pro Variables

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2340]
```
Warning
strpos(): Empty needle
ee/ExpressionEngine/Addons/pro_variables/mod.pro_variables.php, line 118

Severity: E_WARNING

Warning
strpos(): Empty needle
ee/ExpressionEngine/Addons/pro_variables/mod.pro_variables.php, line 118

Severity: E_WARNING
```

There are two Pro Variables on the page and both of them are Grid type.

First one:

```
{exp:pro_variables:pair var="alert_variable"}
  {if alert_variable:on == "on"}
  <section class="alert">
    <div class="container">
      {alert_variable:text}
    </div>
  </section>
  {/if}
{/exp:pro_variables:pair}
```

Second variables pair tag:

```
{exp:pro_variables:pair var="footer_friends_variable"}
   <a href="{footer_friends_variable:friend_link}"><img src="{footer_friends_variable:friend_logo}" alt="{footer_friends_variable:friend_name}"></a>
{/exp:pro_variables:pair}
```

EE 7.1.2
Pro Variables 5.0.2

**Comment by intoeetive** [comment]
What is your PHP version?

**Comment by shbchk** [comment]
Hi Yuri! 
PHP Version 7.4.21

**Comment by intoeetive** [comment]
Grid variable type requires using `{exp:pro_variables:parse}` tag:
https://eeharbor.com/low-variables/documentation/tags#tag-{exp:low_variables:parse}

Can you make the change and see if it fixes the things for you?

**Comment by shbchk** [comment]
Nope :(

**Comment by shbchk** [comment]
Looks like it isn't required after all:

[{exp:low_variables:pair var="my_var"}{/exp:low_variables:pair}](https://eeharbor.com/low-variables/documentation/tags#tag-exp_)

In order to avoid conflicts with multiple instances of the Parse tag, both single and paired, you can use the alias {exp:low_variables:pair} for tag pair use. **It is identical to the Parse tag, but meant for tag pair use only.**

**Comment by intoeetive** [comment]
I wasn't able to replicate this so far.

Can you narrow it down to one of the variables that are being used (as the error seems to be caused by just one of those)? And what are the column types in that Grid?

**Comment by shbchk** [comment]
I just replicated it on a clean EE 7.1.2 install.

So, we need to create two Grid-type variables:

First grid, two columns: textarea, toggle
Second, three columns: text input, file (image), URL

index/index template contents:

```
{exp:pro_variables:pair var="grid_variable"}
<div style="padding: 10%; font-size: 2rem;">
{grid_variable:text}
</div>
{/exp:pro_variables:pair}
```

Variables:
![c366e891-0f37-4f5a-a920-07722f3abe3c](https://user-images.githubusercontent.com/12234507/187493896-cf3e1245-d9de-4335-81b9-e908849517f9.png)


Result:
![9972ef50-51ad-4f38-ada8-3101a927be72](https://user-images.githubusercontent.com/12234507/187493939-e54877e9-79f4-4cd3-8940-63760d4564f6.png)

**Comment by shbchk** [comment]
Updated to 7.1.3, but warnings is still there. Am I missing something?

**Comment by shbchk** [comment]
Well, git tells me that Pro Variables files haven't been changed by this update. Is it possible?

**Comment by intoeetive** [comment]
It looks like we had some glitch with the release. Can you please re-download the files and try again? (1-click update should also work if you set version back to 7.1.2 in your config.php)

**Comment by shbchk** [comment]
Done. Thank you, Yuri!
