### ISSUE TITLE
preg_split error message with php 8.1

### ISSUE THREAD

**Issue by dankingsley** [ExpressionEngine/ExpressionEngine#2348]
**Description of the problem**
On saving an entry with php 8.1 I get a preg_split depreciated error message

**Error Messages**
preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated
ee/ExpressionEngine/Service/Formatter/Formats/Text.php, line 51

Severity: E_DEPRECATED

**Environment Details:**
 - Version: 7.1.2
 - PHP Version 8.1

**Comment by intoeetive** [comment]
Hi @dankingsley , what fieldtypes (or tabs provided by addons) do you have in that entry?

**Comment by dankingsley** [comment]
I've got it happening on a couple of simple sites I've just upgraded to EE7 and it's happening across all channels and entries.

- I expect it might be Structure since that has tabs/fields etc and would explain the universal issue.
- Fields are just fairly standard - RTE, Files, Text

**Comment by intoeetive** [comment]
(marking as possibly related to https://github.com/ExpressionEngine/ExpressionEngine/issues/2349 )

What is the channel type for this entry as set in Structure settings? Also maybe you could make a screenshot of how Structure tab looks for this entry? I'm unable to replicate this so far

**Comment by dankingsley** [comment]
The channel is a Page type within Structure. Although I've also just tried saving a listing type entry too and it's happening there too - basically every entry where Structure is managing the channel. I've just tried creating a new channel not managed by Structure and oddly this error doesn't occur, but #2349 still does!

And I've attached a screenshot of what is in a Structure tab - the only thing I've potentially done differently is move the standard URL title field to the Structure tab as well - although I've just tried taking that back out and the error still occurs.

I can happily give you access to one of the sites where it's happening if needed, just PM me on Slack?

![Screenshot 2022-09-02 at 12 42 39](https://user-images.githubusercontent.com/705466/188132459-2f48ded2-3650-48e9-ad6b-b9fa1de0b792.png)

**Comment by dankingsley** [comment]
Yep that fixes it @bakin1999

**Comment by litzinger** [comment]
FWIW I had a customer using DataGrab report the same thing, and I could replicate it myself.

**Comment by Zignature** [comment]
Came across the same error concerning another line in `ee/ExpressionEngine/Service/Formatter/Formats/Text.php` after upgrading PHP to 8.1.0.

**Error message**     
```
preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated
ee/ExpressionEngine/Service/Formatter/Formats/Text.php, line 160

Severity: E_DEPRECATED
```
Line 160: `$censored = preg_split('/[\n|\|]/', $censored, null, PREG_SPLIT_NO_EMPTY);` should probably be changed to `$censored = preg_split('/[\n|\|]/', $censored, 0, PREG_SPLIT_NO_EMPTY);`

**Comment by TomJaeger** [comment]
@Zignature Thanks for posting this, what version of EE are you running?

**Comment by Zignature** [comment]
I've just updated to 7.2.5 from 6.2.5 and I updated PHP from 7.4.29 to 8.1.0
