### ISSUE TITLE
Structure php deprecated error with php 8.1

### ISSUE THREAD

**Issue by dankingsley** [ExpressionEngine/ExpressionEngine#2349]
**Description of the problem**
With the latest version of EE 7 with Structure I get a deprecated error message when saving an entry.

**Error Messages**
Automatic conversion of false to array is deprecated
ee/ExpressionEngine/Addons/structure/sql.structure.php, line 1188

Severity: E_DEPRECATED

**Environment Details:**
 - Version: 7.1.2
 - PHP Version 8.1

**Comment by bakin1999** [comment]
@dankingsley I am not able to replicate this one at all, so this happening when you save an entry managed by structure.  When you go to the channel settings of that channel in the structure addon settings is the channel set to listings? Page? I have tried both but so far have not had this one come up.

**Comment by dankingsley** [comment]
It's happening on all entries - both pages and listings.

The only thing to add which may help in replicating was that the couple of sites where this is happening were previously EE 6 sites with the Structure addon installed. Having migrated to EE 7 with the addon now part of core, I obviously upgraded from Structure 5 to the in-built Structure 6 and removed the third party addon files.

More than happy to give you access if helpful - just reach out on Slack or email.

**Comment by bakin1999** [comment]
Closes this:

https://github.com/ExpressionEngine/ExpressionEngine/commit/278941b5057a7f6f3bc24a6f7280df12ebfe05b3
