### ISSUE TITLE
Template Variables with more than 50 chars lead to possible crash of system

### ISSUE THREAD

**Issue by bnetz** [ExpressionEngine/ExpressionEngine#235]
**Please note**
We had a server crash (FPM-worker ran into a loop), the following description is something I summarize from information of the hoster and information of my administrator; so I have not seen the issue by myself but I am pretty sure that my description is correct.

**Description of the problem**
If you create a template variable with more than 50 chars the DB-system seems to trim to 50. Somehow this leads to serious problems as the longer name is existing somewhere else.

What happened was that new template variables were created automatically, A LOT. This lead to server crash / a 502 in the frontend.

**How To Reproduce**
Create a template variable with a name that contains more than 50 chars.

**Environment Details:**
 - Version: 5.2.3 Build: 27/5/2019
 - PHP Version 7.1.30
 - MySQL Version 5.5.60
 - OS: CentOS Linux 7.6.1810 (Core) / Plesk
 - Web Server: nginx

**Possible Solution**
Restricting lenght of variable-names via frontend before writing to DB.

**Additional context**
Probably this issue concerns not only template variables but also partials and templates.

**Comment by robinsowell** [comment]
Thanks for the report- and you were correct about the problem.  Templates already had a check for this, but template variables and partials didn't. A fix is up in stability: https://github.com/ExpressionEngine/ExpressionEngine/commit/1d8b12fd267dc83f74facadf88968fb2465b8576
