### ISSUE TITLE
Entry Preview still available when switched off

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#2356]
Even though I have the "Allow Preview" option switched off and the "Preview URL" blank in the Channel Settings, the Preview button is still available when editing an Entry.
EE 6.3.4
EE 6.3.5

**Comment by bakin1999** [comment]
tagged the wrong issue on my fix, this is for issue 2348

**Comment by intoeetive** [comment]
@ops-andy @TomJaeger we need to return to discussing this. We had reasons to always show preview button, but I think switching off "Allow Preview" in channel prefs should force it to be hidden

**Comment by TomJaeger** [comment]
I agree.  If Allow Preview is switched off we should be hidden.
