### ISSUE TITLE
Upgrading from EE 7.1.2 to 7.1.3 fails

### ISSUE THREAD

**Issue by dankingsley** [ExpressionEngine/ExpressionEngine#2360]
**Description of the problem**
Upgrading from 7.1.2 to 7.1.3 fails on multiple sites of mine via the 1 click upgrade, with no error message on php 8.1. Switching back to php 7.4 says there is an error with the root path not being readable. Since I had only just upgraded to 7.1.2 I didn't think this could possibly be the case since my server config hasn't changed. I tried upgrading manually and get the following message when trying to load the control panel / upgrade:

The root path / is not readable.
ee/ExpressionEngine/Library/Filesystem/Adapter/Local.php:47

It looks like it's an issue with a change that has been made with the filesystem.

**Comment by intoeetive** [comment]
@dankingsley we potentially have a fix for this, but having hard time to replicate the exact issue.

Can you help us test this? Replace the file with these changes and hopefully this will just work:
https://github.com/ExpressionEngine/ExpressionEngine/commit/f19d8e903ff44d7de41afdf2d4c9d2ce52318984

**Comment by dankingsley** [comment]
Yes @intoeetive - that fixes it!

**Comment by intoeetive** [comment]
Great, thank you!
