### ISSUE TITLE
Redactor toolbar hides behind entry tabs when sticked to the top of the screen

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2361]
When I have a lot of text in RTE field and scroll down to edit it, Redactor toolbar sticks to the top of the screen and that is great. 

But entry tabs are also sticked to the top with higher z-index - so I can't use RTE toolbar :)

![ec8d6aad-6c24-4704-956b-9f080f3093c6](https://user-images.githubusercontent.com/12234507/188153863-a6719aef-36a3-44a2-b0a6-246ceb2e73b1.png)

EE 7.1.3

**Comment by intoeetive** [comment]
While not real fix, for the time being you can limit the max-height for Redactor fields in toolbar settings
