### ISSUE TITLE
Fluid field last variable not working on relationship field

### ISSUE THREAD

**Issue by DesignWorkshop** [ExpressionEngine/ExpressionEngine#2362]
EE 6.3.5

Team member is a relationship field.
When used within a fluid field the last variable is not working.

`{page_content:team_member}
{if ! page_content:team_member:last}
Not last field
{if:else}
Last field
{/if}
{/page_content:team_member}`

When the team member field is the last field in an entry the code above outputs 'Not last field'.

**Comment by intoeetive** [comment]
@DesignWorkshop I don't think you're doing this right. `:last` is valid modifier for Fluid field (which is `page_content` I assume) but you are trying to apply it to `page_content:team_member` (which is Relationships field)

I am not sure what exact are your needs here, but feel free to post to [Forums](https://expressionengine.com/forums) or [EE Slack](https://expressionengine.com/blog/join-us-in-slack) if you're seeking for advice on how to best set up your template
