### ISSUE TITLE
Channel Layouts

### ISSUE THREAD

**Issue by builtbyryde2022** [ExpressionEngine/ExpressionEngine#2363]
Channel layouts not working. Have created a new tab for META and tried moving three custom fields to the tab but they are not saving on save.

**Comment by intoeetive** [comment]
@builtbyryde2022 which EE version were you on?

**Comment by shbchk** [comment]
Sometimes it is not working for me too. Last time I wasn't able to un-hide the Channel selector in Options tab. And to move category to another tab. 

Removing old layout and adding new one helps.

EE 7.1.3

**Comment by builtbyryde2022** [comment]
@intoeetive the latest version.

**Comment by builtbyryde2022** [comment]
EE 7.1.5 and the issue is still occurring - @shbchk tried your suggestion but still no luck. Annoying as the channel entry page is super long

**Comment by robinsowell** [comment]
Man, this one is weird to reproduce.  But I've been testing Yulya's latest changes in this commit and I haven't been able to break it.  https://github.com/ExpressionEngine/ExpressionEngine/commit/472e994cbf608f84913a0a2c3bc260ad8a27e493

On EE 7.1.5, I just replaced the layout.js and common.min.css files with those and so far, it's been dead solid.  But if anyone wants to test and confirm, that wouldn't be a bad thing.
