### ISSUE TITLE
Hardcoded English artifacts in the CP

### ISSUE THREAD

**Issue by igreil** [ExpressionEngine/ExpressionEngine#2375]
In Performance.php, line 56, the word "of" is hardcoded instead of using `lang('of')`. This only becomes apparent when using a separate language pack.

Also, the words "Total Execution Time" seem to be hardcoded. I have not been able to find a corresponding language string to translate. I am running EE 7.1.12 on a local staging server.

**Comment by igreil** [comment]
Easy to fix, though: https://github.com/ExpressionEngine/ExpressionEngine/commit/e858542729886a685fbddc2bf57fa5ed90fad033

**Comment by intoeetive** [comment]
@igreil thanks for reporting this! Do you want to open the pull request with a fix?

**Comment by igreil** [comment]
I did open a pull request (https://github.com/ExpressionEngine/ExpressionEngine/pull/2376), hope this went well. My Git skills still aren't anywhere near where I'd like them to be :-)

**Comment by intoeetive** [comment]
Yes, all good, thank you! 
(next time you might want to create new branch, just in case you'll want to make additional changes in your `7.dev`, but that's not critical)
