### ISSUE TITLE
ee 7.1.4

### ISSUE THREAD

**Issue by clifavenu** [ExpressionEngine/ExpressionEngine#2384]
Not sure if this belongs here or with TripleNerd. Just updated to 7.1.4 and  Bones broke:
Error Caught
Failed opening required '[path]system/user/addons/bones/FieldFormatters/BloqsFieldFormatter.php' (include_path='.:/opt/sp/php8.1/lib/php')

user/addons/bones/Services/DataService.php:479
Stack Trace: Please include when reporting this error

    #0 user/addons/bones/Services/DataService.php(98): Triplenerdscore\Bones\Services\DataService->loadCustomFieldParsing()
    #1 user/addons/bones/addon.setup.php(19): Triplenerdscore\Bones\Services\DataService->__construct()
    #2 [internal function]: ExpressionEngine\Core\Application->{closure}(Object(ExpressionEngine\Core\Provider))
    #3 ee/ExpressionEngine/Core/Provider.php(445): call_user_func_array(Object(Closure), Array)
    #4 [internal function]: ExpressionEngine\Core\Provider->ExpressionEngine\Core\{closure}(Object(ExpressionEngine\Service\Dependency\InjectionContainer))
    #5 ee/ExpressionEngine/Service/Dependency/InjectionContainer.php(173): call_user_func_array(Object(Closure), Array)
    #6 ee/ExpressionEngine/Boot/boot.php(159): ExpressionEngine\Service\Dependency\InjectionContainer->make('bones:DataServi...')
    #7 user/addons/bones/mod.bones.php(33): ee('bones:DataServi...')
    #8 ee/legacy/libraries/Actions.php(175): Bones->categories()
    #9 ee/legacy/libraries/Core.php(665): EE_Actions->__construct(true, Object(Closure))
    #10 ee/legacy/controllers/ee.php(51): EE_Core->generate_action(true)
    #11 [internal function]: EE->index()
    #12 ee/ExpressionEngine/Core/Core.php(268): call_user_func_array(Array, Array)
    #13 ee/ExpressionEngine/Core/Core.php(124): ExpressionEngine\Core\Core->runController(Array)
    #14 ee/ExpressionEngine/Boot/boot.php(184): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
    #15 index.php(164): require_once('...')
    #15 index.php(164): require_once('...')

**Comment by intoeetive** [comment]
This seems to be caused by the Bones add-on (looks like just missing file). Please contact the add-on developer
