### ISSUE TITLE
.phar files in Add-ons - antivirus alert: JS/Packed.Agent.Q suspicious application

### ISSUE THREAD

**Issue by Caleydon** [ExpressionEngine/ExpressionEngine#2388]
EE 7.1.5
PHP 8.1

When I upload any add-on with .phar file included and when I want to enter on Add-Ons page my PC antivirus (Eset) display following page. 

![antivir-treat](https://user-images.githubusercontent.com/2806752/190176457-054596ea-d07f-41e0-9ccc-0b052ae6c330.png)

**Comment by intoeetive** [comment]
@Caleydon is that one of EEHarbor add-ons? If yes, can you tell the add-on name and version?

**Comment by Caleydon** [comment]
It's User 5.2.4 Add-on - https://eeharbor.com/user
The problem is causing by Version.php file in the user.phar
I am analyzed different and newer add-ons with .phar but they already didn't have such file with suspicious JS code.

I am very disappointed to see such dirty tricks with commercials add-ons in the EE CMS. Honestly, please, stop it!

In addition the User addon is not yet EE 7 ready.

**Comment by bakin1999** [comment]
Have verified that this happens on User v5.2.4

Latest release of User v5.4.2 does not have this issue and is not flagged by eset.  Would you be able to upgrade to latest release

**Comment by ops-andy** [comment]
@Caleydon Just letting you know that there are no dirty tricks. Packet TIde owns both ExpressionEngine and EE Harbor. In no way did we insert malicious code or other such matter into the phar files. We've had issues with ESET and false positives before. We're working to ensure this add-on is on their whitelist to avoid these issues in the future. The best current option though is to update to User 5.4.2 which doesn't seem to have this issue.

**Comment by Caleydon** [comment]
@ops-andy I just want to continue using the (multiple-times) purchased module. So I will request to provide clean and safe version. 

You just said that Packet Tide knew an issue like this. But they didn't warn customers with User add-on license about conflict with ESET antivirus and not provide any explanation and solution / replacement in order to prevent this scenario.

**Comment by ops-andy** [comment]
@Caleydon apologies for any confusion. I believe you're misinterpreting what I'm saying. We have had issues with ESET before. However we have never had a report of an issue with the User add-on until a day or so ago when you and another person reported this. The previous issue was with Assets. We simply applied to ESET to whitelist the add-on and their software no longer recognizes it as a threat. The same with this issue. We will simply provide the file to ESET to show them it's not malicious and have the script allowed.
