### ISSUE TITLE
Darken the Background color for Fluid Fields in the Publish pages

### ISSUE THREAD

**Issue by stpruss** [ExpressionEngine/ExpressionEngine#239]
**Is your feature request related to a problem? Please describe.**
In the Fluid field in the publish form it is frequently difficult to see the seperation between fields because all the greys are so similar.

**Describe the solution you'd like**
It would be beneficial if you could consider darkening the background color if the Fluid Field so that it is easier for clients to see seperation between the fields. It wouldn't need to be much I don't believe & the adjustment could only make the experience better. See the attached example.
![suggested-color-change](https://user-images.githubusercontent.com/8058044/59682043-5c8dbb80-91a3-11e9-93fd-fa1cd33c7476.jpg)

**Describe alternatives you've considered**
Have not come up with any

**Teachability, Documentation, Adoption, Migration Strategy**
None necessary

- [ ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by Jordan-Ellis** [comment]
Fixed in EE6!
