### ISSUE TITLE
Incorrect site_id value for new Fields

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#2399]
I'm working on an EE 6.3.4 site at the moment and have just created some new Fields.

Having received a load of errors on one Template (running the Reefine add-on) I noticed all these new Fields had a site_id value of '0' instead of '1'. Manually changing these to '1' has fixed the Reefine errors, but why were they set to '0' in the first place?

The exp_sites table show only one row, with a site_id of 1.

**Comment by intoeetive** [comment]
@ic360-com in EE6 (and I believe it's same in EE5, but did not check) new fields by default are created with `site_id` equal `0` which means they can be shared through MSM sites.

If an add-on has issue with that, it's most likely that the add-on needs to be updated

**Comment by ic360-com** [comment]
All the site_id values in this installation were set to '1'... but the new fields I created were set to '0'. Shouldn't they be the same?
Does the "create new field" function in EE check to see what the current site's site_id value is when creating the new field?

**Comment by intoeetive** [comment]
If the fields were created on older versions of EE they might be restricted to a site.

But when creating field from control panel in EE6, the fields are created as shared, not restricted to current site (so site_id is 0)

**Comment by ic360-com** [comment]
OK, I see. So in this case... it would be best for me to:
a) change all the current site_ids in the database to 0, to make sure there are no further issues.
b) talk to the Reefine add-on developer, to see if there's a fix required.
Thanks Yuri.

**Comment by intoeetive** [comment]
If the add-on does not work correctly with fields that have site_id set to 0 then IDK if changing that would help the issue.

I believe fixing the add-on should be the way to go
