### ISSUE TITLE
Getting php warnings when using Low Variables on EE6 Pro

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2401]
Have an installation that uses EE Pro - works fine on staging server but when same configuration put on Laravel Valet local test server (i.e. domain.test) Low Variables throws out strpos() needle warnings for each Low Variable being evaluated in a template. Error of the form:

>>Severity: E_WARNING
> 
> Warning
> strpos(): Empty needle
> 
> user/addons/low_variables/mod.low_variables.php, line 122

The line referenced appears to be coming from the `parse` function in mod.low_variables.php.

The issue appears to be remarkably similar to the one closed recently for EE7 - vis https://github.com/ExpressionEngine/ExpressionEngine/commit/168623bf98309c5b448e67d898afeaea556857d2

If so, would it be possible to back-port the changes made to EE6?

EE6.3.5 // php 7.4.30

**Comment by jcogs-design** [comment]
Can confirm that applying the fix from the https://github.com/ExpressionEngine/ExpressionEngine/commit/168623bf98309c5b448e67d898afeaea556857d2 patch to the EE6.3.5 code fixes the issue.

i.e. replace line 122 in EE6 version with
```
elseif (!empty($t['variable_data']) && strpos($tagdata, "${t['variable_data']}") !== false && $t['is_hidden'] === 'n') {
```

**Comment by bakin1999** [comment]
Thank you for the report.  This will be in the next release of Low Variables very soon.
