### ISSUE TITLE
Checkboxes have too large of a click area

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#2403]
Tested in EE 6 and 7. This is an issue because we have users clicking areas far away from the actual checkboxes themselves, and inadvertently selecting a checkbox because they are display: block, so they stretch the entire width of their container. IMO this is a usability issue, and in our case it's actually causing excess support issues because of mis-clicks.

![checkbox-groups](https://user-images.githubusercontent.com/53965/191988226-e9942923-2533-448c-baaa-3d8d4fce5922.gif)

**Comment by intoeetive** [comment]
@ajohnson FYI
