### ISSUE TITLE
[EE6/7] Template group side-bar should be hidden when editing specific template partials, variables, and routes

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#2408]
When editing a specific template in the EE6/7 Control Panel, the side-bar which lists template groups is hidden, to allow more horizontal space for the editor. This occurs for all user templates, and for the system templates (messages, email, members).

But the side-bar *isn't* hidden when editing template partials, template variables, and template routes. There's no good reason for this, and they would make just as good use of the additional horizontal space.

The suggestion — for consistency, and to allow more horizontal space for editing — is to hide the template group side-bar when editing specific template routes and variables, and when using the template route editor.

**Comment by intoeetive** [comment]
@PaulBaileyAtChan I don't know if you're actually aware, but in EE7 we have "Toggle Sidebar" button that allows you to hide secondary sidebar same way that it is possible with primary sidebar. It becomes visible when you hover the area

![image](https://user-images.githubusercontent.com/752126/192441864-8c70d409-a0f8-4a9f-8140-d9c1ee5d415e.png)

**Comment by PaulBaileyAtChan** [comment]
Aha, I don't think I'd registered that yet. Sounds good. If you think it makes this issue irrelevant, feel free to close.
