### ISSUE TITLE
custom_profile_data tag not working within channel entries

### ISSUE THREAD

**Issue by jaapmurre** [ExpressionEngine/ExpressionEngine#241]
**Description of the problem**
The custom_profile_data tag works fine outside but not within channel entries, even though it should.

**How To Reproduce**
A file with only the following:
```
{exp:member:custom_profile_data member_id="2"}
    Birthdate1: {birthdate format="%d %m %Y"} <br />
{/exp:member:custom_profile_data}

{exp:channel:entries channel="studies"}
    {exp:member:custom_profile_data member_id="2"}
        Birthdate2: {birthdate format="%d %m %Y"} <br />
    {/exp:member:custom_profile_data}
{/exp:channel:entries}
```
Produces:
```
Birthdate1: 01 07 1963
Birthdate2:
Birthdate2: 
```
(There are only two entries in the study channel)

**Environment Details:**
 - Version: 5.2.3
 - PHP Version 7.0

**Comment by derekjones** [comment]
Does the author of the channel entry have a birthday value stored in their profile? If you're looking to display custom profile data for someone _other_ than the author of the entry, you will need to do that via your Layouts or with an embed. Those same variables are native to the Channel Entries tag, so, not knowing your intent, will parse them.

**Comment by jaapmurre** [comment]
No, I was trying to filter entries written by different authors on the basis of custom member fields of the logged in member. E.g., an entry may have an age requirement (>18) and the age of the logged in member maybe say 15 (cannot see it) or 41 (can see it). Also, on a large range of other attributes (e.g., handedness = left). I am quite experienced with expression engine but was unable to figure out how to do this one. I am now hardcoding it in the database.

**Comment by derekjones** [comment]
That's not going to 100% have the intended effect. Let's say the Channel Entries tag has a limit of 20. It will filter and return a set of 20 entries based on the Channel Entries' tag parameters. If you then use conditionals to determine visibility, that user won't necessarily get 20 entries, and you've potentially fetched a bunch of data that you don't need.

Thinking outside the box here, one of the multi-lingual add-ons might help you here, but you're specifying attributes other than language. The general idea is the same: you need to interrupt the Channel Entries tag and only fetch what you actually need based on your external criteria.
