### ISSUE TITLE
7.1.6 ee('CP/FilePicker') produced dialog produces a console error when clicking "upload" if no file field is present

### ISSUE THREAD

**Issue by tjdraper** [ExpressionEngine/ExpressionEngine#2412]
In my field type, Ansel, I use a native file picker dialog. And we recently [fixed a related bug](https://github.com/ExpressionEngine/ExpressionEngine/issues/2390), and I've [opened a new related bug](https://github.com/ExpressionEngine/ExpressionEngine/issues/2411).

In this bug, if a native file field is not present in the field set for the channel, clicking the upload button on the dialog will result in a console error, and nothing happens.

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/3803475/192652577-d0d0b917-cfbc-4046-9c27-ce739cf2fe06.png">

If a native file field is present in the channel's fields, the upload button works as expected.

**Comment by tjdraper** [comment]
Wait, the linked PR says it’s removing the ability to upload in the modal. But that ability has always been available until now and I’m specifically enabling it in my call to CP/FilePicker. So is removing the ability the correct thing to do?

**Comment by litzinger** [comment]
I'm with TJ on this one... why remove the option to upload though the modal? That functionality has been in place since... EE 3?

**Comment by Yulyaswan** [comment]
Looks like I mixed some parts
Working on it now.
We will leave  functionality how it should be, with the Upload button

**Comment by mvdesign** [comment]
I guess it's probably self-evident, but I'm getting this through the native RTE CKEditor image/upload tool, too.

**Comment by tjdraper** [comment]
@bryannielsen @Yulyaswan As of [ExpressionEngine 7.2.0 DP 14](https://github.com/ExpressionEngine/ExpressionEngine/releases/tag/7.2.0-dp.14), which, as far as I can tell, has the commits referenced in the MR that fix this, I'm still seeing this same behavior. I have to have a native file field on the entry page in order for the file picker to behave correctly.

If these commits aren't in DP 14 please let me know. I did a compare against the tag and it looked like they were in there.

**Comment by bryannielsen** [comment]
@tjdraper sorry for the misunderstanding, we were testing using a textarea with file picker and not the filepicker code snippet you had in #2390

I tested the latest fix from Yuri with your code and confirmed the bug as well as the fix.  This fix should be in the next DP
