### ISSUE TITLE
Comment expiration message (and other user-facing messages in comment_lang.php) should be modifiable via the EE CP

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#2415]
This is both a specific and general request.

### Specific.

When an older entry is closed for comments, using the **Comment expiration** channel setting, in place of the comment form EE displays the message "Commenting is not available in this channel entry". There are a number of issues here:

- It's not possible to tell EE *not* to display the message.
- It's not possible to change the message (except by hacking the language file `comment_lang.php`).
- There's no practical way to add styling to the message, so that it's presented in a way consistent with the rest of the surrounding content.
- The message is currently not suitable for a typical reader, since "channel entry" is an internal EE term, and not something intended to be meaningful to a general user.

The specific suggestion is that it should be possible, *via the EE control panel*, to:

- Enable/disable this message as required.
- Change the text of the message for local use.
- Add arbitrary HTML tags to the message for local styling.

### General

The above suggestion clearly applies to other language elements in `comment_lang.php`. Where a language element is intended to be used on the front-end of a website, it should be possible for this element to be modified — as described above — via the EE control panel.

**Comment by TomJaeger** [comment]
@PaulBaileyAtChan Thanks for passing this along, this is good feedback.  We're aiming to do a fairly large scope on the comments module soon.  If you have any additional feed back or thoughts we'd love to hear it!

**Comment by PaulBaileyAtChan** [comment]
Thanks, Tom. I was just looking through the docs, and since the conditional `{if comments_expired}` exists, I'm not sure that there's a good reason for EE to display *anything* by default when comments are expired for an entry. If anything is needed it can be triggered using this conditional, and that meets most of what I'm asking for above. So in this case I don't think there's really a need for anything other than disabling the default message.

**Comment by intoeetive** [comment]
I think we should not change the default behavior here, as it would break the existing installations.

Using `{if comments_expired}` however should completely cover what is being requested here.

I also must note that the default theme that ships with EE currently has this block inside comment form:
```
		{!-- required to prevent EE from outputting text --}
		{if comments_disabled}{/if}
		{if comments_expired}{/if}
```
Probably including it into the documentation as example might be good idea - @ops-andy

**Comment by PaulBaileyAtChan** [comment]
I can confirm that using this empty tag:

`{if comments_expired}{/if}`

disables the built-in message for expired comments. It's not intuitive, and it's a bit of a hack, but it's simple and works, so I'm happy to see it as a solution here. Second the suggestion to document this more fully, though.

And that's enough to close this issue from my side of things. Thanks!
