### ISSUE TITLE
Type Error - Editing Channel Layout

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2417]
EE6.3.5 php 8.0

Triggering a type error when saving a channel layout. Not sure what is trigger (happened after an edit to add a new tab, but otherwise no changes made).

Posted because sometimes the cause of the type error is apparent and can be fixed without detailed diagnosis of what happened in this instance etc... 

Stack trace attached 
![Screenshot 2022-10-05 at 14-49-16 TypeError - ExpressionEngine](https://user-images.githubusercontent.com/13821249/194077762-4ab91ae0-9a1d-4b5d-8298-5edd2df46b6c.png)

**Comment by intoeetive** [comment]
We've not been able to replicate this, but the referenced PRs will likely fix it.
