### ISSUE TITLE
Error on file upload

### ISSUE THREAD

**Issue by rihan2i** [ExpressionEngine/ExpressionEngine#242]
Hi we upgraded the expressionengine on 5.2.3.
we are getting error on file  upload.

Fatal error: Uncaught Error: Call to undefined function EllisLab\ExpressionEngine\Library\Mime\finfo_open() in /
/public_html/system/ee/EllisLab/ExpressionEngine/Library/Mime/MimeType.php:105 Stack trace: #0 

/public_html/system/ee/legacy/libraries/Mime_type.php(94): EllisLab\ExpressionEngine\Library\Mime\MimeType->ofFile('/tmp/phpKOlGrL') #1 

/public_html/system/ee/legacy/libraries/Upload.php(168): Mime_type->ofFile('/tmp/phpKOlGrL') #2 

/public_html/system/ee/legacy/libraries/Filemanager.php(1908): EE_Upload->do_upload('file') #3 

/public_html/system/ee/legacy/libraries/Filemanager.php(1024): Filemanager->_upload_file(Array, 'file') #4 

/public_html/system/ee/EllisLab/ExpressionEngine/Service/File/Upload.php(299): Filemanager->upload_file('6', 'file') #5 

/public_html/system/ee/EllisLab/ExpressionEngine/Controller/Files/Files.php(138): EllisLab\ExpressionEngine\Service\File\Upload->uploadTo('6') # in 

/public_html/system/ee/EllisLab/ExpressionEngine/Library/Mime/MimeType.php on line 105

**Comment by robinsowell** [comment]
It looks like the server doesn't have the required [fileinfo extension](https://docs.expressionengine.com/latest/installation/requirements.html#php-extensions-required) enabled.

Your host should be able to get you squared away.
