### ISSUE TITLE
Crash when using new filesystem api / deleteDir()

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2420]
**Description of the problem**
Hitting the "clear cache" button in JCOGS Image on an EE7.1.5 generates this error from the new Filesystem files

This function works without problem on EE6.3.5 and earlier (and I think on earlier versions of EE7).

**How To Reproduce**
Process some images in JCOGS Image that get written to its cache, then hit the button to delete the cache from Image CP.

**Error Messages**
<pre><code>
Error Caught
Call to undefined function ExpressionEngine\Library\Filesystem\Adapter\exec()

ee/ExpressionEngine/Library/Filesystem/Adapter/Local.php:161
Stack Trace: Please include when reporting this error

    #0 ee/ExpressionEngine/Library/Filesystem/Adapter/Local.php(136): ExpressionEngine\Library\Filesystem\Adapter\Local->attemptFastDelete()
    #1 ee/vendor-build/league/flysystem-cached-adapter/src/CachedAdapter.php(135): ExpressionEngine\Library\Filesystem\Adapter\Local->deleteDir()
    #2 ee/vendor-build/league/flysystem/src/Filesystem.php(208): ExpressionEngine\Dependency\League\Flysystem\Cached\CachedAdapter->deleteDir()
    #3 ee/ExpressionEngine/Library/Filesystem/Filesystem.php(260): ExpressionEngine\Dependency\League\Flysystem\Filesystem->deleteDir()
    #4 ee/ExpressionEngine/Library/Filesystem/Filesystem.php(324): ExpressionEngine\Library\Filesystem\Filesystem->deleteDir()
    #5 user/addons/jcogs_img/mcp.jcogs_img.php(1449): ExpressionEngine\Library\Filesystem\Filesystem->emptyDir()
    #6 [internal function]: Jcogs_img_mcp->clear_image_cache()
    #7 ee/ExpressionEngine/Controller/Addons/Addons.php(1513): call_user_func_array()
    #8 ee/ExpressionEngine/Controller/Addons/Addons.php(801): ExpressionEngine\Controller\Addons\Addons->getModuleSettings()
    #9 [internal function]: ExpressionEngine\Controller\Addons\Addons->settings()
    #10 ee/ExpressionEngine/Core/Core.php(268): call_user_func_array()
    #11 ee/ExpressionEngine/Core/Core.php(124): ExpressionEngine\Core\Core->runController()
    #12 ee/ExpressionEngine/Boot/boot.php(184): ExpressionEngine\Core\Core->run()
    #13 admin.php(144): require_once('...')
    #13 admin.php(144): require_once('...') 
</code></pre>

![Screenshot 2022-10-06 at 11-14-55 Error - ExpressionEngine](https://user-images.githubusercontent.com/13821249/194296690-d915b17d-0a98-44e2-8fbf-f497e51fc13d.png)

**Environment Details:**
 - Version: 7.1.5
 - PHP Version 8.0.22
 - MySQL Version  10.1.48-MariaDB-cll-lve

**Comment by intoeetive** [comment]
This has been resolved in EE 7.1.6 via https://github.com/ExpressionEngine/ExpressionEngine/pull/2406
