### ISSUE TITLE
Maximum length of member email field

### ISSUE THREAD

**Issue by meatpaste** [ExpressionEngine/ExpressionEngine#243]
**Description of the problem**
maximum email length is currently set to the maximum username length, suggest this is changed as there is a defined length that email addresses are aloud to be.

**How To Reproduce**
1. Install EE

**Error Messages**
NA

**Screenshots / Videos / Template Code**
https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/system/ee/installer/schema/mysql_schema.php#L297

**Environment Details:**
Any

**Possible Solution**
email varchar(254) NOT NULL,

**Additional context**
https://7php.com/the-maximum-length-limit-of-an-email-address-is-254-not-320/

**Comment by intoeetive** [comment]
@robinsowell do you chance know the reasons why email length is forced to be not greater than username length?

**Comment by intoeetive** [comment]
This is getting released in EE 7.4.0
