### ISSUE TITLE
Channel form asset tag 404s

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#2439]
[Per the docs](https://docs.expressionengine.com/latest/channels/channel-form/overview.html#including-assets), this should link to the channel form css:

`<link href="{path='css/_ee_channel_form_css'}" type="text/css" rel="stylesheet" media="screen">`

Link it creates looks ok, but it 404s.  That's on EE 7.1.6

**Comment by intoeetive** [comment]
@robinsowell can you check if this is not the case here? https://github.com/ExpressionEngine/ExpressionEngine/issues/588#issuecomment-718460813
