### ISSUE TITLE
<> markers get replaced by [] in text fields when accessed through relationship

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2446]
If you put text that includes an html tag into a text field and a template renders it the html tag is carried through unchanged.

e.g.

```
// Field content:
<span>Test Phrase</span>
// Field rendered output:
<span>Test Phrase</span>
```
If access the same field through a relationship field the angle brackets are replaced with square ones.
```
// Field content:
<span>Test Phrase</span>
// Field rendered output:
[span]Test Phrase[/span]
```
This (unsurprisingly) has an effect on how the HTML template output is rendered.

EE6.3.5 // php 8.0.24

**Comment by intoeetive** [comment]
@jcogs-design so far I wasn't able to replicate this using text field with default settings and a simple template:
```
{exp:channel:entries channel="news" url_title="getting_to_know_expressionengine"}
{cnt}
{/exp:channel:entries}
<hr>
{exp:channel:entries channel="news" url_title="welcome_to_the_example_site"}
{related_news}
{related_news:cnt}
{/related_news}
{/exp:channel:entries}
```
I guess something else is needed to replicate?

**Comment by jcogs-design** [comment]
I'll see if I can work out what else is going on and report back. Site is running a bunch of add-ons (esp. Publisher) and so it may be that there is some weird cross-talk effect going on.

**Comment by intoeetive** [comment]
@jcogs-design just wondering if you were able to replicate this issue or we can call it temporary glitch / external by nature?

**Comment by jcogs-design** [comment]
Hi. Sorry - I've completely forgotten about this one, and it was solved by some other means (as a fix was needed at the time). I'll see if I can track back and find the original code - if I don't post back in a couple of days I suggest you drop the matter.
