### ISSUE TITLE
URL Helper / base_url() method returns wrong values

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2452]
[URL Helper](https://docs.expressionengine.com/latest/development/legacy/helpers/url-helper.html) is documented as a utility library to assist in the manipulation of URLs.

The [base_url()](https://docs.expressionengine.com/latest/development/legacy/helpers/url-helper.html#base_urluri---protocol--null) method is documented as having a feature to prefix the base_url of the EE site to a supplied relative path thus:

> Also like site_url(), you can supply segments as a string or an array. Here is a string example:
> 
> `echo base_url("blog/post/123");`
> 
> The above example would return something like: `https://example.com/blog/post/123`

However the function has no such capability. The entire base_url() function in the `legacy/helpers/url_helper.php` comprises
```
/**
 * Base URL
 *
 * Returns the "base_url" item from your config file
 *
 * @access	public
 * @return	string
 */
if (! function_exists('base_url')) {
    function base_url()
    {
        return ee()->config->slash_item('base_url');
    }
}
```

Unless I am missing something ... this function accepts no parameters and simply returns the value of the base_url config variable, with a slash on the end... 

Not sure if this means the documentation should be updated (and similarly for the `site_url()` method) or the missing functionality should be added (?restored?) to the code base.

EE 7.1.6 // EE 6.3.5

**Comment by intoeetive** [comment]
It looks like it has been this way since at least EE3.

I believe we need to have the docs updated here.

Thanks for pointing this out!
