### ISSUE TITLE
Developer log recurs after deletion

### ISSUE THREAD

**Issue by captainFishcake** [ExpressionEngine/ExpressionEngine#2457]
Developer log message recurs after deletion: 

> Member profile templates are now legacy and not recommended to use. Please use regular templates and {exp:member:...} tags.

Every-time I delete it, it comes back after 20 minutes or so.

Running EE 6.3.5

**Comment by intoeetive** [comment]
Once you delete message from developer log, it will appear there again when the corresponding code it triggered (in your case, the legacy member template is accessed).

This is expected behavior

**Comment by captainFishcake** [comment]
Just following up on this issues as it’s still occurring. I'm having trouble locating the legacy member template code that is generating these recurring developer logs. I have checked through my template groups and templates but cannot find any reference to member profile templates being used.

config.php setting for legacy member templates is set to no, which I think is allowing the developer logs to be generated, but I’m having trouble locating the trigger source. Any ideas where the source might be?
