### ISSUE TITLE
Status is Case-Sensitive, UI is Uppercase

### ISSUE THREAD

**Issue by blairliikala** [ExpressionEngine/ExpressionEngine#246]
When the status is MyStatus:
<input name="status" value="MyStatus"> Works.
<input name="status" value="MYSTATUS">  Fails.

However in the CP all the statuses are uppercased "MYSTATUS".  Only way to know the status is to get source.

Solution is to remove uppercase styling in CP.

**Comment by skookie000** [comment]
When the status is MyStatus:
`< input name="status" value="MyStatus" >`Works.
`< input name="status" value="MYSTATUS" >` Fails.

However in the CP all the statuses are uppercased "MYSTATUS". Only way to know the status is to get source.

Solution is to remove uppercase styling in CP.

**Comment by robinsowell** [comment]
I see your point.  You can get the correct name by going to the 'Status' in the channel settings, but it's easy to get confused.

I personally would prefer the status just be case insensitive, but it's not impossible that would cause backward compatibility issues.  But Open and open both being used is not something I'd like to see.  

What are you thinking?

**Comment by skookie000** [comment]
Outside of just taking out that style definition in the stylesheet, whatever you do make it consistent.  I would like to think less about it, so my preference is case-insensitive.  Enforcing case sensitive template parameters would probably break a few templates out there.  I probably have some varying casing around mine too.
