### ISSUE TITLE
The after_channel_entry_save event hook is called twice for every add-on using it

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#248]
**Description of the problem**
It appears the `after_channel_entry_save` hook is getting called twice for every add-on using it, even if there is only 1 row per add-on in the `exp_extensions` table for the hook. 

**How To Reproduce**
Install an add-on using that hook, step debug, or log to file inside the add-on's method using the hook and you'll see it gets called twice every time an entry is saved. I tested this with 1 add-on installed, then a 2nd add-on, and they both have their `after_channel_entry_save` hook called twice. I also tested this in two different EE environments. One using 5.2.3, and another 5.2.4.

**Environment Details:**
 - Version: 5.2.3 & 5.2.4
 - PHP Version 7.2
 - MySQL Version 5.6
 - OS: macOS
 - Web Server: Apache (vagrant machine)

**Comment by derekjones** [comment]
Curious. Are either of those add-ons calling a new `save()` on the model?

**Comment by litzinger** [comment]
Nope, one of the is Reading Time Pro, and there are no instances of `->save` in its codebase. Publisher does call save on some models, but I commented those calls out while testing and it didn't make a difference... the hook was still called twice.

**Comment by litzinger** [comment]
Ok, I uninstalled Publisher and just tested RTP, and it wasn't called twice. So maybe it was a Publisher issue, but I can't pinpoint it yet.

**Comment by litzinger** [comment]
I take that back. When creating a new entry, the hook in RTP is called twice. When editing its saved once. Publisher is not installed.

**Comment by derekjones** [comment]
Is this occurring with the latest public release of Reading Time Pro so I can replicate or just in dev?

**Comment by litzinger** [comment]
Yes it is.

**Comment by derekjones** [comment]
Can you check to see if you have two rows for that hook and method in your `exp_extensions` table? At the top of your method, I added:

```
file_put_contents('/path/to/file/logit.txt', "\nHere at: ".ee()->localize->now, FILE_APPEND);
```

Watching the file live while saving, it only adds a single line for each save.

**Comment by derekjones** [comment]
Scratch that, reading comprehension. I'm also seeing it on new entries.

**Comment by dougblackjr** [comment]
Added PR #352 to address this one. I'm not sure it's the most elegant solution, so I invite feedback.
