### ISSUE TITLE
EE 6.3.5 is trying to get `members.dismissed_banner`, which doesn't exist. But there is `members.dismissed_pro_banner`

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2483]
This is weird one, I guess.

After importing mysql dump from production server to local dev server, EE suddenly throw this error at me: 

```
Exception Caught
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Member_members.dismissed_banner' in 'field list':
```

I rolled back previous dump, but nothing changed - the exception was still there, both on front and in CP.

For some unknown reasons EE 6.3.5 is trying to get `members.dismissed_banner`, which doesn't exist. But there is the `dismissed_pro_banner` column in the members table. Why EE is looking for a wrong column? Or, why the column was suddenly renamed to a pro?

Before importing mysql dump I also bought an EE7 license, attached it to domain (and removed previous EE6 licenses). But I haven't updated the system yet.

I fixed it by adding this column `members.dismissed_banner` manually, but, hey, I didn't like it :) And, after that, I updated EE to 7.1.6.

**Comment by intoeetive** [comment]
`dismissed_banner` and `dismissed_pro_banner` are different fields serving different purposes.

It looks like you did not run the updater script to 6.3.5 properly, which adds the `dismissed_banner` field.
