### ISSUE TITLE
Add wait cursor when File / Image Sync is running

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2490]
**Is your feature request related to a problem? Please describe.**
When you Directory Sync on a File location the process is handled via some kind of async process. The only way of telling that this is running is the moving line in the progress indicator - but this starts small and may take a few seconds to appear. When the sync process is triggered the mouse pointer remains in its default state, and the Sync Directory button remains active. On slow systems this may give the user the impression that the button click has not been registered and may result in multiple clicks on the button etc. 

**Describe the solution you'd like**
When a Directory Sync starts, the cursor shifts to a wait state, and the Directory Sync button is disabled (and possible has a wait animation replacing the Directory Sync term).

**Describe alternatives you've considered**
Getting a faster computer... 

**Teachability, Documentation, Adoption, Migration Strategy**
Should be self explanatory.

**Comment by Yulyaswan** [comment]
Hi @jcogs-design !
What version of ExpressionEngine is this on?

**Comment by jcogs-design** [comment]
EE 6.3.5
