### ISSUE TITLE
Pro variables file field portability

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#2498]
Per report: 
If you save a link to an image using a stand-alone Low Variable the value chosen is written to a file in the _variables template directory and the content comprises the full URL to the image.

If you put an image field into an LV grid and pick / save the same image, LV saves the filedir definition of the image path to the db.

What this means is when you move the site from a staging server to live server, any image links that are set using image fields in grid fields continue to work after the move, but any that were saved as single variables don’t (unless the staging server is visible to the live server).

**Comment by intoeetive** [comment]
On my testing with Pro Variables on EE7, I got different results.

When using Grid with File column, the data are only saved to database (not file) and the file format is correct in the form of `{file:1:url}`

Using the built-in File dropdown variable type is saving the full path indeed.

I think we need to consider replacing all built-in PV variable types with EE fieldtypes - this will make code more DRY, things more manageable and consistent and should solve problems like this.

@TomJaeger for your consideration

**Comment by intoeetive** [comment]
After discussion, we decided that we do this for File field, and is it's not much effort then for other fields as well.
