### ISSUE TITLE
Deleting individual items from developer log doesn't delete the item

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2499]
Have an EE2 site updated to EE6.
After update site reported 7 items in developer log.
3 items relate to things happening before the update so deleted those.
After deleting get a positive confirmation that items deleted and the clicking away from list and back again shows the reduced number correctly.
But after some (I am not sure how long) time the three deleted items return... :( 

EE6.3.5 / php 8.0.24

**Comment by TomJaeger** [comment]
Hi @jcogs-design

Thanks for posting this one.. Any chance you can keep an eye on the Date time on the log notifications to confirm they are duplicates?

**Comment by intoeetive** [comment]
@jcogs-design I believe what you are seeing here is expected (and it also means that the original issues were not resolved with update).

If the issue reported in developer log is not resolved, and you delete the record from the log - it will be logged again once it is encountered again.
