### ISSUE TITLE
URL_TITLE Not Generated when user try to re-submit the form, EE 5.0.0

### ISSUE THREAD

**Issue by ahmmadsaleh86** [ExpressionEngine/ExpressionEngine#25]
I have faced a problem in channel form.
I will tell you the scenario that led me to the problem and the problem message.

**Scenario**
I have placed a form for users, the url_title will be generated automatically by putting the parameter (<b>unique_url_title="yes"</b>).
If the user inputs all the data, the form will be submitted successfully.
But if the user forgets to input some required data, the user will re-input the missed data and resubmit the form, the form won't submit successfully and EE showed an error message (<b>url_title is required field</b>)

**Error Message**
url_title is required input.

I have used EE3 and EE4 and both of them worked correctly in a familiar scenario.

**Comment by kevincupp** [comment]
I'm unable to reproduce this. Here is my code:

```
{exp:channel:form channel="test" unique_url_title="yes" error_handling="inline"}
   <input name="title" type="text"> {error:title}
   <input name="entry_date" type="text">{error:entry_date}
   <input type="submit" value="Submit">
{/exp:channel:form}
```

I submitted an entry without an entry date, got an error, fixed the date, submitted the form, and the entry saved fine with a URL title. Let me know what else I can do, and please always include sample code use our issue template and provide steps to reproduce.

**Comment by kevincupp** [comment]
Closed due to abandonment.
