### ISSUE TITLE
RTE - Images not being deleted

### ISSUE THREAD

**Issue by ops-andy** [ExpressionEngine/ExpressionEngine#2518]
**Description of the problem**
Images in RTE are not deleted unless you interact with the RTE field before saving.

**How To Reproduce**
1. Create an RTE field using Redactor and a channel to use the field
2. Add an image to the field and save your entry.
3. Navigate back to the entry editor (If not still there), click on the image you just inserted and select "Delete" 
![image](https://user-images.githubusercontent.com/55093827/201948325-1efe2251-3280-4625-963e-7124bd6c5dc4.png)
4. Save your entry.
5. Navigate back to the entry editor (If not still there), and you will notice your image is still in the field
6. Click on your image and select "Delete" again. 
7. Type something new into the field
8. Save your entry, and you will see that now the image has disappeared. 

**Screenshots / Videos / Template Code**
![rte_image_bug](https://user-images.githubusercontent.com/55093827/201949738-20191219-6172-4d93-95b1-647802d9d5e2.gif)

**Environment Details:**
 - Version: 7.2.0, also reported in 6.2.7

**Additional context**
https://eecms.slack.com/archives/C04CUNNR9/p1668521860541449

**Comment by intoeetive** [comment]
Noting that this only happens if removing image is the last action you perform on field (i.e. if you don't add or remove other text)

Also this is an issue with the source engine (Redactor 2) which is not supported by developer anymore

So I suggest just closing this issue @TomJaeger
