### ISSUE TITLE
Expression Engine Times Out

### ISSUE THREAD

**Issue by rouviere** [ExpressionEngine/ExpressionEngine#252]
I have had repeated issues with Expression Engine timing out unexpectedly and not saving the work in progress.

I check the box "Keep me logged in" and sign in. Then after working on an entry in the control panel for 30 to 60 minutes when I try to save the entry I get an error message saying that I have been logged out. When I log back in, all the work I did was lost and there was no auto-save version. 

This one issue with Expression Engine has driven me crazy and is the single reason I would switch to another CMS. 

How can I solve this problem and how can I make sure that auto-save is always active. The last time I used the system auto-save was working fine. But this time there is no sign of it.

1. Check the box "Keep me logged in"
2. Sign in to the control panel.
3. Create a new entry or work on an existing entry
4. Work for 30-60 minutes
5. Expression Engine will randomly close out losing all changes.

**Environment Details:**
 - Version: 5.2.3
 - PHP Version 5.6.40
 - MySQL Version [e.g. 5.7]
 - OS: Linux
 - Web Server: Apache

I would love it if there was a solution.

It is difficult to replicate the problem because it happens erratically, but one time is enough to cause great mental stress!

**Comment by meatpaste** [comment]
In Settings > Security & Privacy, what do you have set for the session types? What you are describing sounds like session timeout.

**Comment by rouviere** [comment]
I have it set to Cookies only. What is the recommended setting to avoid the random timeout issue?

**Comment by adc91** [comment]
I'm having the same problem. I have an EE installation where journalists can spend hours editing an entry but EE loses the session after 60 minutes along with the data.

@rouviere what was the solution you came to?

**Comment by rouviere** [comment]
The way I have it set under System Settings > Security & Privacy is:

CP Session type: **Cookies only**
Website Session type: **Cookies and session ID**

Then on the login window I make sure that I check **Keep me logged in** before I sign in. 

So far this has worked fairly well, but I would also recommend **Save often**. It is tragic to have to rewrite something.

**Comment by adc91** [comment]
Yes, reviewing the configuration more thoroughly I also left it in that configuration. We will see how it goes.

**Comment by rouviere** [comment]
I hope it works for you. I feel a bit blown off on this topic. If EE is supposed to stay active as long as you are active in the Control Panel then there should be very clear instructions in the documentation on how to make it happen. I was told in no uncertain terms that if EE timed out the way I described in another case I opened on the topic that no one would be using EE. My point exactly. It should be resolved at the highest levels.

**Comment by TomJaeger** [comment]
Cookies only, and remember me on login should do the trick.

@rouviere Am I reading your comment correctly that this hasn't been an issue for you since setting it to cookies only with remember me?

https://github.com/ExpressionEngine/ExpressionEngine/issues/252#issuecomment-567133650

**Comment by adc91** [comment]
Investigating a little more about how EE sessions work, I arrived at the Session library and in the comment I found the key to the problem.

![image](https://user-images.githubusercontent.com/11680570/71114524-bac94480-21ae-11ea-8e5d-128749db23f4.png)

It has logic because of how cookies and sessions work.

**Comment by rouviere** [comment]
Thank you for sharing that.
