### ISSUE TITLE
When viewing entries in the admin the page limit and total results are incorrect when using categories as a display column

### ISSUE THREAD

**Issue by jamesseavers** [ExpressionEngine/ExpressionEngine#2526]
**Description of the problem**

When viewing entries in the admin the page limit and total results are incorrect when using categories as a display column.

1. View a set of entries for a channel with categories associated.
2. Select Categories to show as a column.

https://user-images.githubusercontent.com/14070252/202440432-7cc2ab5a-a386-4d8d-8e5f-069d1120c282.mov

**Environment Details:**
Version: 7.2.0

**Comment by intoeetive** [comment]
Thank you for reporting. We are aware of this problem, as it has been been reported in https://github.com/ExpressionEngine/ExpressionEngine/issues/987 - so closing this as duplicate, but will try to review the problem soon.
