### ISSUE TITLE
How to create home page getting blank screen after install

### ISSUE THREAD

**Issue by GaneshKandu** [ExpressionEngine/ExpressionEngine#254]
Hi

i have installed ExpressionEngine 5.2.4 after install getting blank screen in front page

seting ``$debug = 1;`` doesn't worked for me
```php
	$debug = 1;
```

Thank you! 🙏

**Comment by derekjones** [comment]
Please do not use the GitHub Issue tracker for support; use the [community forums](https://expressionengine.com/forums) or you can [get support](https://expressionengine.com/support) directly from ExpressionEngine.com.

Some things to look for:
- make sure you are logged in as a Super Admin to the front end of your website. Session type cookies only, with a properly set cookie domain to match the control panel and front end URLs.
- have you created any template groups and templates yet? If not, you'll get a white screen that is not an indication of any errors, it just means you need to start building your site.
