### ISSUE TITLE
New File Manager may not correctly render files correctly in MSM site when using `.env.php`

### ISSUE THREAD

**Issue by ops-andy** [ExpressionEngine/ExpressionEngine#2549]
**Description of the problem**
When using `.env.php` to configure paths, files may not render correctly on the front-end when using a file field.

**How To Reproduce**
Set up an MSM site
Refactor `config.php` to use `.env.php`
Add a file field with data
Try to render field on the front-end.

**Comment by intoeetive** [comment]
We figured out the user had incorrect setup in config file. Will need to have example for MSM sites using `.env.php` added to the docs
