### ISSUE TITLE
Too many columns issue

### ISSUE THREAD

**Issue by web-admin** [ExpressionEngine/ExpressionEngine#255]
Hi guys,

I get "Too many columns" error when I try to add another filed in channel. My site is quite large (over 2k columns at the moment - I have 9 languages and 3 MSM). Sys admins says that's the limit of MySQL database. Is that true? If not, how can I solve it?

I'm using EE 3.5.16.

Thanks.

**Comment by meatpaste** [comment]
upgrade, EE5 has a new solution for this, it creates new tables for the extra columns

**Comment by web-admin** [comment]
That's what I was thinking for as I saw new tables in EE5. Where can I find a proper info what has been changed in database structure since version 3 of EE?

**Comment by derekjones** [comment]
You can read the change logs for both v4 and v5 at https://docs.expressionengine.com
