### ISSUE TITLE
Layout lists are not working with `index='{index}'` parameter inside other lists

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2557]
EE 7.2.0

[Docs reference](https://docs.expressionengine.com/latest/templates/layouts.html#using-layout-lists-together)

How to reproduce:

Create templates `test/index` and `test/layout`.

`test/index` contents:

```
{layout="test/layout"}
<h1>Hello, lists!</h1>
{exp:channel:entries channel='somechannel' limit='5'}
{layout:set:append name="ids"}{entry_id}{/layout:set:append}
{layout:set:append name="titles"}{title}{/layout:set:append}
{/exp:channel:entries}
```

`test/layout` contents:

```
{layout:contents}
<ul>
  {layout:ids}
  <li>ID: {value}, TITLE: {layout:titles index='{index}'}</li>
  {/layout:ids}
</ul>
```

Output:

```
Hello, lists!
ID: 11473 / TITLE:
ID: 11471 / TITLE:
ID: 11463 / TITLE:
ID: 11456 / TITLE:
ID: 11452 / TITLE:

```

**Comment by intoeetive** [comment]
@shbchk just tested your templates, everything worked as expected (titles shown).
Would anything else be interfering here for you?

**Comment by shbchk** [comment]
Hmm 🤔 
But what can interfere here? There are no other tags in those templates. And this issue remains in other templates with different tags. Where should I look, what do I need to poke?

**Comment by intoeetive** [comment]
Try disabling extensions first.

I would also think some fieldtypes could interfere, but if this the only code you have (no custom fields called) then probably not

**Comment by shbchk** [comment]
Extensions disabled via config file with `$config['allow_extensions'] = 'n';` 

I even added `disable="categories|category_fields|custom_fields|member_data|pagination"` to the entries tag. Still nothing.

[video-convert-1669365274026.webm](https://user-images.githubusercontent.com/12234507/203936929-8fb6ccda-db23-4772-a232-120aaa8e9184.webm)

Sometimes I feel like I should start over by reinstalling EE, just like we did with the Windows 15 years ago :)

**Comment by intoeetive** [comment]
So the debugger is showing the variables correctly, but they don't get through in templates.
Which makes me wonder if `{index}` variable has a conflict. Maybe you have partial or global variable called `{index}`?

**Comment by shbchk** [comment]
It surprised me, but, actually, I have! I mean, there are blank `index.html` files in `_partials` and `_variables` folders. Was :)

I think I created them a long time ago, when my system folder was under webroot (for another project) and it migrated unnoticed into the new one. 

Thanks!

**Comment by intoeetive** [comment]
I wonder if those could have been created automatically at some point? In such case this might be a bug.

We'll need to test this more internally.

Thanks for reporting!

**Comment by shbchk** [comment]
No need, those files were definitely created manually — they were not truly blank, there was a redirect to 404 inside.
