### ISSUE TITLE
Rich Text Editor field does not load base styles for HTML tags on initial page load in EE v 7.2.1

### ISSUE THREAD

**Issue by roberthallatt** [ExpressionEngine/ExpressionEngine#2559]
When attempting to use the rich text editor field type (Redactor full), the HTML content remains un-styled after the page is loaded. The only way to get styles to show up correctly is by toggling between source code and design view.

The bug seems to affect new and existing fields and defining a custom stylesheet makes no difference.

https://user-images.githubusercontent.com/7095139/203831436-2854e391-90ef-4d3b-9873-d2c2ae431bc6.mov

**Comment by intoeetive** [comment]
This appears to only be issue if you have Wygwam and RTE (CKEditor 4 and CKEditor 5) on same page. Which is something that is outside of things we can fix
