### ISSUE TITLE
Multi-level relationship tags cause timeout when used in conditional without quotes

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2561]
EE 7.2.1

[Docs link](https://docs.expressionengine.com/latest/templates/conditionals.html#embedding-tags)
![6e7d9d9e-142a-4a22-9486-b790475629f0](https://user-images.githubusercontent.com/12234507/203981046-6c0dc944-0b5c-4c89-b270-5219d4a7ed13.png)

But, if I do not use quotes and braces in this example, EE breaks with fatal error.

**This line works:**
`{if "{parents:program_awarded_films_grid:awarded_film_relationship:title}" == "{title}"}` 

**This do not:**
`{if parents:program_awarded_films_grid:awarded_film_relationship:title == title}`

**Error message:**
`Fatal error: Maximum execution time of 90 seconds exceeded in C:\OpenServer\domains\vurchel.local\sstm\ee\ExpressionEngine\Library\Parser\AbstractLexer.php on line 44`
Or
`Fatal error: Maximum execution time of 90 seconds exceeded in C:\OpenServer\domains\vurchel.local\sstm\ee\ExpressionEngine\Library\Parser\AbstractLexer.php on line 46`
Or
`Fatal error: Maximum execution time of 90 seconds exceeded in C:\OpenServer\domains\vurchel.local\sstm\ee\ExpressionEngine\Library\Parser\AbstractLexer.php on line 103`

**Template:**
```
{exp:channel:entries 
  channel='channel' 
  limit='1' 
  require_entry='yes' 
  status='open{if is_live_preview_request}|closed|pending{/if}'
  disable='member_data|pagination|category_fields' 
  cache='yes' 
  refresh='36000' 
  }

{parents field="program_selected_films_grid:selected_film_relationship" orderby="program_year"}

  {parents:program_awarded_films_grid}
    {if "{parents:program_awarded_films_grid:awarded_film_relationship:title}" == "{title}"}
      some content
    {/if}
  {/parents:program_awarded_films_grid}

{/parents}

{/exp:channel:entries}
```

Is this okay?

**Comment by intoeetive** [comment]
I know this is somewhat late reply, but I believe the issue here is not with braces/quotes, but with the relationship parser

Also you may try using some of [these tips](https://docs.expressionengine.com/latest/fieldtypes/relationships.html#optimizing-relationships-performance) to optimize relationship performance

**Comment by intoeetive** [comment]
Also it might be that you are running into one of conditional tags limitations: https://docs.expressionengine.com/latest/templates/conditionals.html#embedding-tags
