### ISSUE TITLE
File manager performance

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2564]
EE 7.2.1
Over 10 000 images in the system, stored locally, most of them in one directory.
Compatibility Mode is off.

It takes almost half a minute to load the file manager (in modals too):

![649258b2-a070-41da-a1be-c67a50b6ac18](https://user-images.githubusercontent.com/12234507/204106352-cf9a0a7f-30a6-4013-b84c-d6f43b26b0d1.png)

**Comment by shbchk** [comment]
Well, I guess it is time to give a try to the new Cloud Files adapter and move those thousands of files to Digital Ocean Spaces :)

**Comment by shbchk** [comment]
Oh my god, how slow those are! I never tried S3 before and thought it might be faster, but it's really not.

When I tried to open the Sync Directory page for a directory of 10000 images that I've uploaded to Digital Ocean Spaces (_it was very long and painful_), I got this error:

`Fatal error: Maximum execution time of 300 seconds exceeded in C:\OpenServer\domains\vurchel.local\sstm\user\addons\cloud_files\vendor-build\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php on line 131`

**Comment by intoeetive** [comment]
@shbchk can you please try the change in linked PR and tell us if this works for you.

This change is for Local adapter only. Unfortunately we don't have good solution currently for cloud storage having thousands of files in single upload directory

**Comment by shbchk** [comment]
@intoeetive it worked great for me! Thank you!

**Comment by shbchk** [comment]
@intoeetive Hi, Yuri! Should I open a new ticket for this issue with cloud storage and a large number of files in a single directory? Is there a chance for this to be fixed?

**Comment by intoeetive** [comment]
I believe @bryannielsen is working on update for Cloud Files that should work better

**Comment by shbchk** [comment]
That's great! Thanks, I will wait. I hope waiting will not be long :)

**Comment by shbchk** [comment]
@bryannielsen hi! I can't yet transfer all my tens of thousands of image files to S3, right?

https://github.com/ExpressionEngine/ExpressionEngine/pull/3630 - we're waiting for this?
