### ISSUE TITLE
EE adds unwanted symbols to {if no_result} output

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2568]
EE 7.2.1 adds this line to `{if no_results}none{/if}` output: `{!-- ra:00000000687845e100000000664c16a2 --}` 

Resulting in `'none{!-- ra:00000000687845e100000000664c16a2 --} '`

I am saving this output as a layout variable and later I need to put it in a conditional `{if layout:variable != 'none'}`, but this conditional, obviously, doesn't work.

Can we get rid of this line?

**Template code:**
```
{layout:set name="credits__directors"}{film_filmmakers_grid search:film_filmmaker_production_role='director' backspace='2'}{if no_results}none{/if}{film__credits_filmmakers_part}{/film_filmmakers_grid}{/layout:set}

{layout:set name="credits__story"}{film_filmmakers_grid search:film_filmmaker_production_role='story' backspace='2'}{if no_results}none{/if}{film__credits_filmmakers_part}{/film_filmmakers_grid}{/layout:set}

{layout:set name="credits__cast"}{film_filmmakers_grid search:film_filmmaker_production_role='cast' limit="12"}{if no_results}none{/if}{film__credits_cast_part}{/film_filmmakers_grid}
```

**Output:**
```
  'credits__directors' => '<a href="/name/11472/aneil-karia-1984" class="filminfo__name-link">Aneil Karia</a>',
  'credits__story' => 'none',
  'credits__cast' => 'none{!-- ra:0000000061802a3e0000000060873a72 --} ',
```

**Comment by shbchk** [comment]
BTW, `{if no_results}` doesn't always work with grids.

**Comment by intoeetive** [comment]
@shbchk I wasn't able to replicate this issue by using JUST this code.

I would assume something in `{film__credits_cast_part}` partial or in wrapping `{exp:channel:entries}` call is influencing this.

Might be worth looking at difference between `film__credits_filmmakers_part` and `film__credits_cast_part` as the first one returns output parsed correctly, and the other one does not.

**Comment by shbchk** [comment]
@intoeetive, I just replicated it on a clean EE 7.2.3 install. Not exactly the same output, but still: we can see those unwanted symbols and `{if no_results}` tag doesn't work for a grid field.

Here are the steps:

1. Create a grid field with a Select dropdown in it and a text field.

**Dropdown example:**
![86a2fc21-4f69-46f6-9f25-16910f7f79ed](https://user-images.githubusercontent.com/12234507/207066237-e51f6cc5-3415-47ab-bcee-90fe06616dc2.png)

**Entry contents:**
![f8513221-ae0a-4ead-b520-da151c85e750](https://user-images.githubusercontent.com/12234507/207066330-73e831d7-d12b-4116-8756-1e1e5ebba86d.png)

2. Create a `test.group` with two templates: `index` and `_markup`

3. `test/index` template contents:

```
{layout="test/_markup"}
{exp:channel:entries channel="test"}
{layout:set name="ones"}{test_grid search:dropdown='one'}{if no_results}none{/if}{test_grid:text}{/test_grid}{/layout:set}
{layout:set name="twos"}{test_grid search:dropdown='two'}{if no_results}none{/if}{test_grid:text}{/test_grid}{/layout:set}
{layout:set name="threes"}{test_grid search:dropdown='three'}{if no_results}none{/if}{test_grid:text}{/test_grid}{/layout:set}
{title}
{/exp:channel:entries}
```

4. `test/_markup` template contents:

```
{layout:contents}
<div>Ones: {layout:ones}</div>
<div>Twos: {layout:twos}</div>
<div>Threes: {layout:threes}</div>
```

5. Enable debugger and check layout Variables section:
![106f125c-1d9d-4408-9676-4247da66dd49](https://user-images.githubusercontent.com/12234507/207067305-fc3d17a7-6dce-480e-a307-9aef32d0bf94.png)

**Comment by shbchk** [comment]
I should have done this earlier, sorry :( 

UPD: And, I just noticed, there was no mention of the debugger. Again, sorry :(

**Comment by intoeetive** [comment]
In order to get `{if no_results}` working correctly in tested tags, it needs to be added to each parent tag pair.

So if you're using  `{if no_results}` inside Grid, you should also make sure it's used in `{exp:channel:entries}`. Once I add it there, the variables are parsed correctly.

We'll make sure it's mentioned and is noticeable in the docs

**Comment by shbchk** [comment]
Thank you, Yuri!
