### ISSUE TITLE
No such property: 'db' on EllisLab\ExpressionEngine\Legacy\Facade

### ISSUE THREAD

**Issue by robchristian** [ExpressionEngine/ExpressionEngine#257]
**Description of the problem**
When following the installation instructions very closely, the install wizard always throws an error.

**How To Reproduce**
Install EE and mysql on macOS like this.

Apache:
1. Configure Apache to serve PHP files.
1. `sudo rm /Library/WebServer/Documents/*`
1. `sudo chown user:staff /Library/WebServer/Documents`

MySQL:
1. `brew install mysql`
1. `mysql -uroot`
1. `CREATE USER 'newuser'@'localhost' IDENTIFIED BY 'password';`
1. `CREATE DATABASE cms;`
1. `GRANT ALL PRIVILEGES ON * . * TO 'newuser'@'localhost';`
1. `exit`

Install Expression Engine:
1. `git clone git@github.com:ExpressionEngine/ExpressionEngine.git /Library/WebServer/Documents/`
1. `cd /Library/WebServer/Documents/`
1. `touch system/user/config/config.php`
1. Replace `EE_INSTALL_MODE=FALSE` with `EE_INSTALL_MODE=TRUE` in `/Library/WebServer/Documents/.env.php` (copy from repo example if not present)
1. `find ./ \( -type d -exec chmod 777 {} \; \) -o \( -type f -exec chmod 666 {} \; \)`
1. `open http://localhost/admin.php`
1. Fill in form with correct credentials for `newuser` and DB name `cms`.
1. Submit.

**Error Messages**
```
Exception Caught
No such property: 'db' on EllisLab\ExpressionEngine\Legacy\Facade
ee/EllisLab/ExpressionEngine/Legacy/Facade.php:120

Stack Trace: Please include when reporting this error
#0 ee/EllisLab/ExpressionEngine/Legacy/Facade.php(30): EllisLab\ExpressionEngine\Legacy\Facade->get('db')
#1 ee/installer/controllers/wizard.php(853): EllisLab\ExpressionEngine\Legacy\Facade->__get('db')
#2 ee/installer/controllers/wizard.php(272): Wizard->do_install()
#3 [internal function]: Wizard->_remap('do_install', Array)
#4 ee/EllisLab/ExpressionEngine/Core/Core.php(241): call_user_func_array(Array, Array)
#5 ee/EllisLab/ExpressionEngine/Core/Core.php(110): EllisLab\ExpressionEngine\Core\Core->runController(Array)
#6 ee/EllisLab/ExpressionEngine/Boot/boot.php(151): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request))
#7 admin.php(153): require_once('...')
#7 admin.php(153): require_once('...')
```

**Environment Details:**
 - Version: commit 4274c06045eccd12567667bd06a3c7bc4c27a826
 - PHP v7.1.23
 - MySQL Version v8.0.16
 - OS: macOS v10.14.5
 - Web Server: Apache v2.4.34

**Additional Info:**
I searched the internet and found mention of this error, but every page I see, has no solution or even a response.

**Comment by robchristian** [comment]
I suspect the issue is with mysql 8 on macOS. Seems the default password method has changed. Have not tested in Expression Engine yet, as I moved on to try out October CMS, and ran into similar error messages as I was seeing in EE.

For future readers:
- https://stackoverflow.com/questions/50169576/mysql-8-0-11-error-connect-to-caching-sha2-password-the-specified-module-could-n
- https://medium.com/@crmcmullen/how-to-run-mysql-8-0-with-native-password-authentication-502de5bac661

**Comment by derekjones** [comment]
Yep, we've got an [{ee:u} article](https://u.expressionengine.com/article/mysql-8-and-expressionengine-tips-for-the-trailblazers) covering it as well. Thanks @robchristian!
