### ISSUE TITLE
EE7.2.2 Throwing Warning on exp:channel:categories With Empty Categories

### ISSUE THREAD

**Issue by dougblackjr** [ExpressionEngine/ExpressionEngine#2571]
**Description of the problem**

Displayed warning after using `{exp:channel:categories}` tag with debug on:
![image](https://user-images.githubusercontent.com/6020323/204352257-c1241ec8-1de4-4a44-89b3-eff7a32cf148.png)

**How To Reproduce**
1. Create template with `{exp:channel:categories}` tag.
2. Run loop with an empty category.

For example, 
```
{exp:channel:categories category_group="1"}
        {embed="embeds/category-project-loop" title="{category_name}" cat_id="{category_id}"}
{/exp:channel:categories}
```
**Error Messages**

<pre><code>
Warning
Undefined variable $all
ee/ExpressionEngine/Addons/channel/mod.channel.php, line 3050

Severity: E_WARNING
</code></pre>

**Environment Details:**
 - Version: 7.2.2
 - PHP Version 8.0
 - MySQL Version : MySQL 8
 - OS: Ubuntu
 - Web Server: nginx

**Possible Solution**
On line 3050 of mod.channel.php, either null coalesce $all, or ensure it is set outside of the conditional.

**Comment by intoeetive** [comment]
@dougblackjr can you clarify what you call "Run loop with an empty category"?

**Comment by dougblackjr** [comment]
@intoeetive Sure! So, in the template I run this:

```
{exp:channel:categories category_group="1"}
    {embed="embeds/category-project-loop" title="{category_name}" cat_id="{category_id}"}
{/exp:channel:categories}
```

I have two categories in this category group that have no entries in them. This is when I get the notice thrown.

If I do this:

```
{exp:channel:categories category_group="1" show_empty="no"}
    {embed="embeds/category-project-loop" title="{category_name}" cat_id="{category_id}"}
{/exp:channel:categories}
```

Then the warning disappears.

**Comment by intoeetive** [comment]
I wasn't able to replicate :(

Is there anything in the embed that might be affecting the output?

**Comment by dougblackjr** [comment]
@intoeetive Nothing I can see. Here's a video walkthrough: https://www.loom.com/share/c6ae57b78d7149efbf9b1816309ea8d3

**Comment by intoeetive** [comment]
I think this might be related to the other `channel:entries` tag in this template. Can you send me the full template code, including the layout template and `project-block` partial?

**Comment by benya** [comment]
I am also getting this error on 2 sites.

```
Notice
Undefined variable: all
ee/ExpressionEngine/Addons/channel/mod.channel.php, line 3050
Severity: E_NOTICE
```

EE 7.2.2 & 7.2.3
PHP  7.4.3
nginx 1.18.0

**Comment by tyssen** [comment]
I'm getting the same thing except for me it happens with and without the `show_empty` parameter. Even in a completely stripped-down template with just this in it, I get the warning:

	  {exp:channel:categories
	    channel="articles"
	    style="nested"
	    show_empty="no"
	  }
	    <a href="{path=articles}/">{category_name}</a>
	  {/exp:channel:categories}

The site I'm working on is on EE 7.2.3.

**Comment by PDXMan1** [comment]
Getting this error also and tested and confirmed it in a stripped-down template.
