### ISSUE TITLE
Control Panel publish/edit entry pages have missing files

### ISSUE THREAD

**Issue by jamesseavers** [ExpressionEngine/ExpressionEngine#2577]
When working with an entry in the Control Panel that has a Redactor field, there is a missing file 404 generated in console (it's more likely a wrong file location):

Failed to load resource: the server responded with a status of 404 (Not Found)
WEBROOT/redactor.min.js.map

In this and all other CP pages there is another 404:

Failed to load resource: the server responded with a status of 404 (Not Found)
WEBROOT/themes/ee/cp/css/common.min.css.map

**How To Reproduce**
Inspect a Control Panel, it's missing in all.

**Environment Details:**
 - Version: 7.2.2 and 7.2

I'm sure I've reported this before but I cannot find it in issues.

**Comment by Yulyaswan** [comment]
hi, @jamesseavers .
Thanks for noting this.

Could you please clarify if you are seeing this issue as an error or as a warning?

**Comment by jamesseavers** [comment]
It's an error in the browser console, 404 errors, see image.
![Screenshot 2022-12-07 at 15 55 14](https://user-images.githubusercontent.com/14070252/206227206-239896d6-2950-4757-8aec-66a16d5ecaa7.png)
