### ISSUE TITLE
Request change "Date Added" shown in File Manager to "Last Modified" to be more useful

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#259]
In the file manager, showing when an image was initially uploaded is useless if that file has been overwritten.  Instead I'd like to suggest replacing it with (or adding?) Last Modified to the information displayed to be more useful.

**Comment by intoeetive** [comment]
The Last Modified date is shown in CP with the new File Manager that's included in ExpressionEngine 7 release.
