### ISSUE TITLE
Label issues - CP link redirect transit page

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2599]
If you click on an external link from the CP screen, the interstitial page has some labels missing.

![image](https://user-images.githubusercontent.com/13821249/205632417-b1f72ca0-a902-474a-b08e-09975f4e8dc4.png)

Similarly one of the pop up dialog boxes has labels missing 

![image](https://user-images.githubusercontent.com/13821249/205632800-593e19e5-7b25-409a-96b1-3fbd1bef2116.png)

And the side-bar has a few labels missing too
![image](https://user-images.githubusercontent.com/13821249/205633277-e419ce48-f383-48f2-9074-2d9b93fd363e.png)

This is on a site that had just been auto-updated to EE 6.4.1 from EE 5.4.3
php 7.4.33
Not sure if it is an update issue or more systemic.

**Comment by jcogs-design** [comment]
On digging further this looks like some kind of EE db issue.
For example, the pre-updated 5.4.2 site refuses to show the ee_news label even though it is present in the code and shows on other sites.
![image](https://user-images.githubusercontent.com/13821249/205641050-caf1516b-b8c5-4cd8-b416-055d7b290c39.png)
Will investigate further ... ;(

**Comment by intoeetive** [comment]
Are you by chance using custom language which is out of date? (even though it should pick up missing strings from English folder)

**Comment by jcogs-design** [comment]
Yes - it was indeed a custom language - was not aware there was one but removing fixed the issues - looks like it was introduced in EE4 and was a direct copy of English language folder at that time. With custom language in place update to EE6 triggered fatal error - caused by hardwired paths assuming EllisLab folder structure in that file - possibly worth adding some logic to protect against such dramatic failures - e.g. via a trap for unreachable file paths in code that loads language file as a FR

Anyhow - props to @robinsowell for help diagnosing / fixing the issue.
