### ISSUE TITLE
Config Environment Variables

### ISSUE THREAD

**Issue by levidurfee** [ExpressionEngine/ExpressionEngine#26]
**Is your feature request related to a problem? Please describe.**
Storing configuration settings in a file is a bit troublesome. Maintaing a file between different environments can be difficult.

**Describe the solution you'd like**
I would like for ExpressionEngine to store configuration settings in environment variables, or at least have that option. It could check if the environment variable is set, if it is set it would use it, but if it isn't set it would use a setting from the `.env.php` (or similar) file. At the time of writing this I don't see any potential drawbacks.

**Describe alternatives you've considered**
The `config.php` is in the `.gitignore` file, so I am free to edit it as I see fit and it won't be checked into any repo. I could set my environment variables, and have the `config.php` file use the `getenv()` function to retrieve the data.

**Teachability, Documentation, Adoption, Migration Strategy**
The user could then store their configuration settings in environment variables which would allow them to easily have different stages of development. It would require an update to the [System Configuration Overrides](https://docs.expressionengine.com/latest/general/system_configuration_overrides.html), and potentially other places.

**Documentation change**
```
$config['allow_avatar_uploads'] = 'y';
// would become
putenv('allow_avatar_uploads=y'); // The environment variable may be all uppercase
``` 

**Migration Strategy**
Allow both config methods. Maybe deprecate the current way in the next major release. Of course one way would need to override the other way, and that would need to be decided.

- [x] I am capable and would like to work on an implementation of this feature if it is considered.

**Comment by kevincupp** [comment]
It sounds like you're describing what folks commonly set up with environment-specific config files. So, if you're on your development machine, it reads from a file like `config.local.php` and then it falls back to values in `config.php`. Does that sound like what you're essentially trying to do? If so, I'm not sure why environment variables are required to solve this problem, could you elaborate on that?

**Comment by kevincupp** [comment]
You can set this up on your own. The problem is EE doesn't know which is your local environment, so you can decide and set up that logic yourself based on your preferences. Here's an example setup:

https://github.com/focuslabllc/ee-master-config/tree/EE3

We'd like to roll in some of this natively and it's been requested, but I'm not sure switching the storage mechanism to environment variables is necessary to achieve it.

**Comment by levidurfee** [comment]
Okay, thanks!
