### ISSUE TITLE
Member module not installed?

### ISSUE THREAD

**Issue by jHards** [ExpressionEngine/ExpressionEngine#260]
Coming from a legacy Core install, now running v5.2.4 and trying to load the standard Login Form code from [here](https://docs.expressionengine.com/latest/member/index.html#login-form-tag).

I'm getting the following error:

![error](https://i.imgur.com/qeHF7fc.png)

Member module is also not listed on the Module page in the CP.

The member files are on my server, surely in a past update the module should have been registered in the database?

**Comment by derekjones** [comment]
The member module was always installed, even with Core; it just lacked the code to execute tags and have front-end member pages. The only explanation I can think of is that someone accidentally and manually deleted the required row from exp_modules. I'd go back to a backup from before you upgraded and see if its in one of those backups, which might help determine where things went south. My concern at this point would be whether I could trust the integrity of the rest of the database if that required and default element was removed.

**Comment by jHards** [comment]
> The member module was always installed, even with Core; it just lacked the code to execute tags and have front-end member pages. The only explanation I can think of is that someone accidentally and manually deleted the required row from exp_modules. I'd go back to a backup from before you upgraded and see if its in one of those backups, which might help determine where things went south. My concern at this point would be whether I could trust the integrity of the rest of the database if that required and default element was removed.

FYI - ended up moving to a fresh install and now working as expected.
