### ISSUE TITLE
vCards cannot be uploaded

### ISSUE THREAD

**Issue by bytebaby** [ExpressionEngine/ExpressionEngine#2601]
After upgrading from EE 6.xx to version 7.2.2, I can no longer upload VCF files via a file field. The paths are correct and the directory has the appropriate write permissions. Nothing changed in the server settings after the upgrade.
I'm not sure if it's a bug.

<img width="278" alt="image" src="https://user-images.githubusercontent.com/21154749/205678982-704c21c0-5e28-4cc8-aa1a-79061b50af6c.png">

**Comment by intoeetive** [comment]
@bytebaby is the mime type whitelisted in `config.php`? If yes, how does the line look like?

If it's just not there, the best way to whitelist mime type would be to use custom `mimes.php` config file https://docs.expressionengine.com/latest/config/config-files.html#allowed-mime-types

**Comment by bytebaby** [comment]
I immediately thought of that and tried to enter the format vcf in mimes.php. Wrong syntax?
'application/vcf', // .vcf

**Comment by intoeetive** [comment]
```
return array(
    'doc' => array(
        'application/vcf', // .vcf
   )
);
```
is the best, but the below should also work
```
return array(
        'application/vcf', // .vcf
);
```

**Comment by bytebaby** [comment]
So I entered it into the mimes.php. Unfortunately, the error message remains

<img width="324" alt="image" src="https://user-images.githubusercontent.com/21154749/206186055-cc69eb3e-241c-4acc-8264-e1ff2a1adc24.png">

The upload has worked on this website for years without any problems. One question would be why suddenly not anymore.

**Comment by intoeetive** [comment]
I tested and found out that `.vcf` files on my system show mime type of `'text/vcard'`. Once I whitelisted that, the upload worked fine

**Comment by bytebaby** [comment]
Merci. Is working. I also tried "txt", but instead of "vcard" I wrote text/vcf. Ah!
