### ISSUE TITLE
In Rich Text Editor, Sharepoint links are likely to break

### ISSUE THREAD

**Issue by rmaclemale** [ExpressionEngine/ExpressionEngine#261]
**Description of the problem**
In the Rich Text Editor field, when you insert Sharepoint links which contain a colon followed by a letter followed by a colon, the links will break (depending on the letter.)  Sharepoint links are huge and often contain character strings like <code>:b:</code> which EE interprets as an emoji.  So you end up with the B emoji and a broken link.  

**How To Reproduce**

1.  In Developer/Add-Ons, enable Rich Text Editor.
2. On any entry, add a Rich Text Editor field.
3. Add the following HTML: <code>http://anysite.com/:b:/thispage</code>
4. Save the entry and view in a browser.  The <code>:b:</code> will be an emoji, which breaks the link.

**Error Messages**

<pre><code>
There are no Error Messages.

</code></pre>

**Screenshots / Videos / Template Code**
Unfortunately our Sharepoint is private, so our actual examples won't work, but if you follow the steps, the issue is easy to duplicate.

**Environment Details:**
 - Version: [e.g. 5.1.3]
 - PHP Version [e.g. 7.3.1]
 - MySQL Version [e.g. 5.7]
 - OS: [Windows]
 - Web Server: [IIS 10]

**Possible Solution**
In the ee/forums, it was suggested this is happening because the Typography parser sees <code>:b:</code> as an emoji short code.  The parser should ignore emoji short codes when they're inside an anchor link.

**Additional context**
One workaround on our end is to put a space after the first colon in <code>:</colon> or replace the first colon with <code>%3A</code>, but asking our office secretaries to dive into a long Sharepoint URL and change characters isn't going to work in our situation.  I can automate a MySQL replace and have it run every 5 minutes, but that's ugly.  I have no other workarounds.  Everyone who uses Sharepoint with EE in a Rich Text Editor will see this issue.  If there are any short term workarounds, I'd love to try them.

**Comment by derekjones** [comment]
This is a little heavy-handed if your users use and enjoy emoji shortcodes, but it does fully resolve the issue. You can apply this code as a patch and it will be included in the next one-click update, so you won't have to keep patching core code.

To disable Emoji short code parsing, add the following to your config file:

```
$config['disable_emoji_shorthand'] = 'y';
```

If this comes up again, or your users want Emoji short codes, we can reopen and look at a more targeted solution, however that type of text parsing can be expensive, so if this solution works for 80% of users, it's the best.

**Comment by rmaclemale** [comment]
We're fine with this as a fix.  Thanks!  We really appreciate it.
