### ISSUE TITLE
[Assets] Files > Upload Directories > Edit Upload Directory: File Limits asks for kilobytes, but actually measures bytes

### ISSUE THREAD

**Issue by creativearc-paul** [ExpressionEngine/ExpressionEngine#2614]
EE 6.3.5, but I've known this to be an issue for quite a while going back to EE5. 

- **When I set a 3000 kb limit in the admin:**

![3000](https://user-images.githubusercontent.com/224037/206229657-01658c77-d7ce-4854-b1c6-e10e7b8e26ca.jpg)

- **I get this warning on upload.**

![3kb](https://user-images.githubusercontent.com/224037/206229806-75163832-f8af-41f3-a0a6-eae1973307ed.jpg)

- **To actually get it to limit uploads to 3mb, I have to change the value to '3145728' bytes.**
- 

![314](https://user-images.githubusercontent.com/224037/206229996-b634be2b-18e9-420a-ba78-ef72d01b56fd.jpg)

- **Which then works as expected (using Assets module in this case):**

![3mb](https://user-images.githubusercontent.com/224037/206230218-bfddfffb-6e6d-4241-9acf-2e0858262b5a.jpg)

So the wording of this upload label needs to be adjusted, or the default actually needs to be changed to kilobytes.

**Comment by intoeetive** [comment]
I wasn't able to replicate the issue.

I can upload file of 5kb into upload directory that has `10` in the 'file limit' setting

@creativearc-paul can you confirm that you see this in EE File Manager and not just Assets?

**Comment by intoeetive** [comment]
Assets team has been informed; closing the issue as external by nature
