### ISSUE TITLE
Channel Import breaks if there is a file field in the import

### ISSUE THREAD

**Issue by jamesseavers** [ExpressionEngine/ExpressionEngine#2627]
**Description of the problem**

When importing a channel having a file field in the import breaks the import and just returns 'Cannot Import Channel' error.

**Environment Details:**
 - Version: 7.2.2 (but hasn't;t worked since EE6 for me).

Try the import zip attached.
[ChannelSet-116.zip](https://github.com/ExpressionEngine/ExpressionEngine/files/10196740/ChannelSet-116.zip)

**Comment by dougblackjr** [comment]
I think I'm having this same issue, noticed it a while back. +1 for this.

**Comment by TomJaeger** [comment]
Quick update on this one... I believe it's an issue due to the File Directory not existing on the site your importing to.

"Exhibitor logos"

Shouldn't error out either way.

**Comment by jamesseavers** [comment]
No, just tested with a site that has an upload destination of Exhibitor logos and it still reports 
"Cannot Import Channel".
