### ISSUE TITLE
Visual indicator of templates with HTTP authentication turned on

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#263]
**Is your feature request related to a problem? Please describe.**
A small thing, but it would be helpful for the Template Manager to show an indicator of any templates which have HTTP authentication turned on. This would allow much quicker identification of those templates, for general management of access.

EE2 had a small key icon which served this function, but it was lost (I think) in the big EE2 -> EE3 redesign. It would be great to have something similar back.

**Comment by intoeetive** [comment]
This has been added in EE6
