### ISSUE TITLE
Using EE Files system to upload animated gif removes animation from image

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2639]
As per title.
Using either the File / Upload or in-field upload options has same result - animated GIF images are collapsed to static images during the upload process.
This is a change in behaviour from EE5 - it cropped up on a site that makes extensive use of animated gifs, after updating to EE6 they no longer could add new content.

There is a work-around - upload the images directly to the Files folder on the server and then "sync" the images directory from within EE and then attach the found images to the entries concerned, but this is complicated to set up / execute for the design agency concerned... so better would be to fix the issue within EE.

EE 6.4.2 // php 8.0.25

**Comment by jcogs-design** [comment]
Bump!

**Comment by intoeetive** [comment]
I can confirm this issue exists in EE6 - but not in EE7 though.

Considering that file management got so much improvement in EE7, I would recommend updating to EE7.

I agree this would be nice to get fixed in EE6, but can't give any estimates ATM.

**Comment by jcogs-design** [comment]
Considering that this worked in EE5 it would seem that it now working in EE7 is not so much an improvement as a bug fix. 

Updating to EE7 is not a solution for many organisations so it would be good if a fix was queued up. 

I have not looked, but would strongly expect this to be caused by EE opening the image in GD before saving it to the Files area - GD does not preserve gif animation and so it gets lost. The fix is simply to copy gif images directly to the files area unless the need to be resized etc. 

I imagine this is what was happening in EE5

**Comment by jcogs-design** [comment]
I have had a closer look and the issue seems kind of straightforward to resolve.

EE6 checks to see if an uploaded image 'is editable' in the `is_editable_image` method of the legacy Filemanager class, and then later seems to always generate a thumbnail (via the `create_thumb` method in Filemanager class) and as part of this appears to always 'resize' the image as part of the saving process.  It would appear it is this obligatory 'resize' of the uploaded image that it the cause of the bug.

The check carried out is simply to interrogate the file's mime type and look this up within a preloaded list of EE approved mimetypes (in the config/mimes.php file), and GIF is one of these approved file types - i.e. no attempt is made to determine if the uploaded image is an animated GIF. This is an easy condition to test for - here is the code JCOGS Image uses to do this (in case it is useful).

```
    /**
     * Detects animated GIF from given image file loaded as string (via file_get_contents or similar).
     * Derived from code at https://stackoverflow.com/a/42191495/6475781
     * This version works on file in memory rather than on disk.
     *
     * @param string $image  - image loaded as a string
     * @return bool
     */
    function is_animated_gif($image)
    {
        if (!is_string($image)) {
            // Not an image string so bale out
            return false;
        }

        if (substr($image,0,3) !== "GIF") {
            // Not a GIF!
            return false;
        }

        // We use preg_match_all to count the markers for gif frames in the string
        // More than one and we've got an animated gif...
        // The test used is to look for the start of the 'application extension block' which
        // for animated gifs must always start with the bytes 21 F9 - if we get more than one 
        // we must have a layered GIF and so probably an animation.
        // Details here http://giflib.sourceforge.net/whatsinagif/animation_and_transparency.html

        $frames = preg_match_all('/\x21\xf9/', $image);

        return $frames > 1;
    }
```
The image could be tested for animated GIF status and if it is one, perhaps be marked as 'not editable' and so skip the processing steps (and get uploaded unchanged - much like a PDF would).

Another solution would simply be to remove the odd behaviour that resizes all images on upload.

**Comment by intoeetive** [comment]
Thanks @jcogs-design ! It might be related to MIME type checks indeed - those have been updated in EE7, which might have solved the issue there.

I'll have a closer look

**Comment by jcogs-design** [comment]
I have found where this bug is coming from (at least in EE 6.4.2).
In the library `ee/legacy/libraries/Filemanager.php` at line 1936 (in the `_upload_file` method) is this instruction:
```
       $file_data = $this->max_hw_check($file['full_path'], $file_data);
```
`$this->max_hw_check()` (line 501 of same file) in turn calls the method `resize()` in `ee/legacy/libraries/Image_lib.php`
This in turn calls the method `image_process_gd()` in the same `Image_lib` library.
This file in turn creates a new GD instance for the image (line 467) and saves it to the disk (line 480).
The issue here is that GD does not support animated gifs, and the save in this method destroys any animation.
Bizarrely the `resize()` method already contains the code needed to side-step this issue (starting line 418) it just never is called for animated gif files.

So a possible solution for this issue would be simply to add a test for animated gif files to the conditional at line 418 and use the conditional code instead of the resize. For example (from line 416 of `Image_lib.php`:
```
        // Are we looking at an animated gif? If so set flag to true to trigger the resize bypass
        $animated_gif = false;
        if($_FILES['file']['type'] == 'image/gif') {
            $temp_image = file_get_contents($_FILES['file']['tmp_name']);
            $frames = preg_match_all('/\x21\xf9/', $temp_image);
            $animated_gif = $frames > 1 ? true : false ;
        }

        // If the target width/height match the source, AND if the new file name is not equal to the old file name
        // we'll simply make a copy of the original with the new name... assuming dynamic rendering is off.
        if ($this->dynamic_output === false || $animated_gif) {
            if ($this->orig_width == $this->width and $this->orig_height == $this->height) {
                if ($this->source_image != $this->new_image) {
                    if (@copy($this->full_src_path, $this->full_dst_path)) {
                        @chmod($this->full_dst_path, FILE_WRITE_MODE);
                    }
                }

                return true;
            }
        }
```
This code appears to work - it is not very efficient (there is no need actually to copy the file - since the file has already been copied to the target location) but I am sure it can be used as the basis for something more elegant.

Of course, for this type of solution someone would have to generate equivalent code for the other graphics library variants of `image_process_xxx` too - so it might be more efficient from a coding perspective to move the animation check earlier in the workflow and simply avoid this step entirely (since by the time this step is reached, the file has actually already been uploaded to EE ... so this unneeded resizing based rewrite is doubly inefficient...).

**Comment by intoeetive** [comment]
@TomJaeger pinging about this issue

**Comment by jcogs-design** [comment]
I have had a brief look and it strongly looks like that the code fragment above can simply be dropped into the two other `image_process_xxx` library methods as-is.

The best place for the code in each would be at the very start of the methods concerned - i.e.:

- `image_process_gd` - line 416 of `Image_lib`
- `image_process_imagemagick` - line 510 of `Image_lib`
- `image_process_netpbm` - line 578 of `Image_lib`

This does not take away from the points made in earlier post about the whole activity being redundant for animated gifs which suggests that the test for same could be made earlier. It is clear that none of the library routines make any attempt to apply their transformations to animated gifs in a way that would preserve the animation, so either you accept you are going to destroy the animation when loading these images into EE (6 only) or simply side-step the unnecessary resize ...
