### ISSUE TITLE
Simple search not working with multiple channels for guest users

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#264]
**Description of the problem**
Set up a **simple search form** with parameter `channel="channel_1|channel_2|channel_3"` (as per [documentation](https://ellislab.com/expressionengine/user-guide/add-ons/search/simple.html#id24).  Searching when logged in either as a **Member** or **Super Admin** all results are shown across all three channels.  When searching as **guest** (i.e. when not logged in) results are only provided for one of the channels in the set in the channel parameter (not sure which - various attempts produce results from various single channels from the group).

**How To Reproduce**
1. Create field with EE setup with multiple channels, with search enabled for all member groups and search fields configured in each channel.
2. Construct template with simple search tag that targets multiple channels (e.g. something like ``` {exp:search:simple_form channel="channel_1|channel_2|channel_3" search_in="titles" result_page="site/search_results" no_result_page="site/no_search_results" name="search_form" where="any"}``` and create a search results template that will list the results of the search. 
3. Log in to EE and perform a search for a term that is common across multiple entries across the three channels - results from all three channels are found in output.
4. Log out of EE and repeat the search using same term.  Results obtained only from one of the multiple channels specified.  
5. Remove all but one of the multiple channels from the simple search parameter and repeat the logged-out search, and you get the results for that channel.  Repeat this for each of the multiple channels to confirm that logged out users can see all the results from all the channels.
6. Conclude that the bug relates to multiple channels and logged out users.

**Error Messages**
n/a

**Screenshots / Videos / Template Code**
n/a

**Environment Details:**
 - Version: 5.2.3
 - PHP Version 7.2.19
 - MySQL Version 5.7.27
 - OS: macos 10.14.6
 - Web Server: LiteSpeed V7.4.3 (Apache)

**Possible Solution**
This issue does not appear to affect advanced search (`exp:search:advanced_form`) so substituting the alternative tag is an effective solution.

**Additional context**

**Comment by ops-andy** [comment]
Since we were unable to replicate and this issue is over a yearand half old, I'm closing for now. If this still persists (please ensure you are using EE 6), feel free to re-open and let us know. thanks.
