### ISSUE TITLE
{form_declaration} in Member Templates

### ISSUE THREAD

**Issue by jHards** [ExpressionEngine/ExpressionEngine#265]
I might be just missing syntax but seems like `{form_declaration}` in the Member templates can only handle `hidden_fields`, and not the other variables listed [here](https://docs.expressionengine.com/latest/development/legacy/libraries/functions.html#form_declarationdata)?

Using a fresh v5.2.4 local install and hoping to add class/id tags to the form opening tags (along with some extra hidden fields).

**Comment by jHards** [comment]
e.g. change `{form_declaration}` to `{form_declaration form_class='test-class'}` in [system/ee/templates/_themes/member/default/username_password_form.html](https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/system/ee/templates/_themes/member/default/username_password_form.html) results in the original form opening tag `<form method="post" action="http://domain.com/index.php/member/update_userpass">` just print out `{form_declaration form_class='test-class'}`.

Am I missing something obvious here?

**Comment by jHards** [comment]
Referencing [recent forum post](https://expressionengine.com/forums/topic/252499/member-addon-set-class-to-form-with-form_declaration) on the same issue

**Comment by intoeetive** [comment]
Legacy member templates provide limited functionality, and `form_declaration` tag is not same as `form_declaration()` function referenced in the docs.

As of EE6, legacy member templates are not recommended for usage and `exp:member` tags should be used instead. https://docs.expressionengine.com/latest/member/edit-profile.html
