### ISSUE TITLE
[EE6/7] In Entry Manager columns, Select Dropdown fields are shown using the field value, rather than the label

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#2653]
When displaying a **Select Dropdown** field as a column in the Entry Manager, EE displays the field *value*, rather than the field *label*. This is inconsistent with other fields — for example, **Checkboxes** fields display the label. And it's also less user-friendly. The field *value* is for internal use, e.g. in code. Rather than the field value, EE should display the field *label* for **Select Dropdown** fields in Entry Manager columns.

**Comment by intoeetive** [comment]
I agree this is not consistent, however what we display here is what is getting displayed on front-end if you call field with a single tag. This is how the field has always been working in EE, and we can't change that without breaking existing installations.

[From the docs](https://docs.expressionengine.com/latest/fieldtypes/select.html): 
> Checkboxes, Multiselect and Selectable Buttons all default to showing the label. Radio Buttons and Selects default to showing the value.

**Comment by PaulBaileyAtChan** [comment]
@intoeetive With respect, I disagree with the above.

- An important consistency here is how the field is displayed **within the entry manager**. A Select Dropdown field **control** is displayed within the entry manager using the field **labels**, so it's reasonable to expect that when a Select Dropdown field is displayed as a column in the entry manager, the field labels would be used there as well. A user of the entry manager should expect that what they've chosen using the field control is what they see in the entry manager column. To have the **control** use the labels, but the column display the values, is unintuitive, and potentially confusing. A typical user of the entry manager might not know how the labels and values relate to each other.
- The entry manager and template code are two separate things, and they don't have to behave exactly the same way. A user of the entry manager is not necessarily the same person who created the template code. It's also possible to change, in template code, whether the value or the label is displayed. It's not possible to change which is displayed in the entry manager column, so it's more important to display the most user-friendly, and the most consistent **within the entry manager itself**.
- No existing installations would be broken by changing the behaviour of the **entry manager**. And saying that "This is how the field has always been working in EE" doesn't make much sense, given that it's only been possible to display a Select Dropdown field as a column in the entry manager since 6.4.0 / 7.2.0. That was a very recent bug-fix.

Could I ask that this be reopened and passed for a second opinion? Thanks.

**Comment by intoeetive** [comment]
@TomJaeger what's your opinion on this?

**Comment by TomJaeger** [comment]
A lot of good points on this thread as a whole.. As we've discussed in the past, there are some inconsistencies in how the label -> value is handled with these fields and it's something we need to be to pay attention to.

That being said, for the entry manager, we should display it as the Label to stay consistent in the Control Panel.  We can't change the default behavior for the templates though.
