### ISSUE TITLE
Fluid Fields issues since upgrading to 6.4.3

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#2660]
Since updating to 6.4.3 (I think I was on 6.4.0 before - waiting for backups from the host to confirm), I can no longer add sub-fields to a Fluid Field - clicking the "Add xxxx" button adds a # to the URL and it scrolls up to the top.  This happens in both Chrome and Firefox.

In the console, I see two instances of this error:
<img width="653" alt="image" src="https://user-images.githubusercontent.com/8193519/208813443-30885c5d-d99f-45ef-9942-7493484ab9dd.png">

This also appears to break simply trying to save an existing entry whether or not there are any existing sub-fields in the Fluid Field.  All my sub-fields available to the Fluid are Grid fields and if there are pre-existing Grid fields in the Fluid, attempting to save the entry adds a new/empty **row** at the top of **every** pre-existing Grid field which of course don’t validate so keep the entry from saving.  If the Fluid is empty, trying to save the entry adds the first sub-field (Accordion in my case) with an empty row and fails validation.  This is what I see just trying to save a page where the 'Page Builder' was previously empty:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/8193519/208814317-17fe081a-46c1-4df9-8130-4ae2b6bf6f45.png">

**Comment by intoeetive** [comment]
@pyrobob83 we haven't been able to replicate this so far.

Did anything else change except updating EE itself? Specifically, anything related to upload directories?

**Comment by pyrobob83** [comment]
@intoeetive Actually, I was just able to get the backup from the host, roll back and it's happening for me in 6.4.0 too, but this is definitely the first I've noticed this... I have no idea what's going on.  Nothing has changed around upload directories for months on this project - for sure since before I upgraded to 6.4.0.

**Comment by pyrobob83** [comment]
@intoeetive FWIW, 1-click updating all the way to EE7.2.5 resolves this, so I'm going to encourage the client to bite the bullet on the EE7 license for the sake of time.  But I genuinely have no idea when or how this started happening.  Maybe an environment thing!

**Comment by pyrobob83** [comment]
@intoeetive I have no idea what caused this, but the client approved the EE7 license so I'm just moving forward with that.  My guess is something got corrupted at some point and it just persisted through the 1-click update from 6.4.0 to 6.4.3.  Thanks for looking into this though - appreciate you all!
