### ISSUE TITLE
Low Variables deprecation warning on php 8.1

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2662]
**Description of the problem**
Running low variables 4.1.1 getting deprecation error when using php 8.1

**How To Reproduce**
Not sure ... run low variables with php 8.1?

**Error Messages**
<pre><code>

Deprecated
Automatic conversion of false to array is deprecated

user/addons/low_variables/mod.low_variables.php, line 419

    Severity: E_DEPRECATED

</code></pre>

**Environment Details:**
 - Version: 6.4.2
 - PHP Version 8.1
 - MySQL Version 8.x
 - OS: macos
 - Web Server: laravel valet

**Comment by intoeetive** [comment]
Passed on to EEHarbor team
