### ISSUE TITLE
Channel entry Channel switching not possible due to unsorted arrays of channel_ids

### ISSUE THREAD

**Issue by rowansentesy** [ExpressionEngine/ExpressionEngine#2669]
**Description of the problem**
We had a very odd issue appear for a client site where on the production site, the client was unable to switch an entry from one channel to another. 
Yes, the channels have identical fields and statuses. 
I could NOT replicate this issue locally when I pulled the production database down to test. 
I was able to debug the issue and discovered that this file:
system/ee/EllisLab/ExpressionEngine/Model/Channel/ChannelEntry.php >  populateChannels() function  was failing to match the $my_fields array with the returned $channel->getAllCustomFields()->pluck('field_id')

**How To Reproduce**
- I'm not sure what the differences were between local and production environments that would contribute to this. I checked the codebase on both, and the PHP versions match (PHP 7.4.33).

**Error Messages**

none.

**Screenshots / Videos / Template Code**
Local on left (working with no modification)
Production on right (not matching channels that should be matched)

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/39419325/209233557-5cdc5274-6efe-4c3d-a0a5-5935ef91b06e.png">

**Environment Details:**
 - Version: [5.4.2]
 - PHP Version [7.4.33]
 - MySQL Version [10.4.27-MariaDB - MariaDB Server]
 - OS: [OSX Locally via Docker]
 - Web Server: [Apache on server]

**Possible Solution**

system/ee/EllisLab/ExpressionEngine/Model/Channel/ChannelEntry.php
Lines 1105-1112

### Before:
```
		foreach ($channels as $channel)
		{
			if ($my_fields == $channel->getAllCustomFields()->pluck('field_id') &&
				$my_statuses == $channel->Statuses->getIds())
			{
				$channel_filter_options[$channel->channel_id] = $channel->channel_title;
			}
		}
````
### After
```
		foreach ($channels as $channel)
		{
			if (empty(array_diff($my_fields, $channel->getAllCustomFields()->pluck('field_id'))) &&
				$my_statuses == $channel->Statuses->getIds())
			{
				$channel_filter_options[$channel->channel_id] = $channel->channel_title;
			}
		}
```

**Additional context**

As I mentioned, this is a strange issue and I can't figure out why the returned getAllCustomFields() call would return an unsorted array, but it appears that the populateChannels function expects them to be pre-sorted. Might as well use the array_diff() function to improve usability.

**Comment by intoeetive** [comment]
Because this report is for EE5 (which has reached end of life) and in ExpressionEngine 6 and 7 corresponding code is different, I am assuming this issue is no longer relevant, so closing it out.
