### ISSUE TITLE
Still Issues with Relationships in 5.2.5

### ISSUE THREAD

**Issue by albuvee** [ExpressionEngine/ExpressionEngine#267]
**Description of the problem**
Following the Update to 5.2.5 some of my relationship tags are still broken.
This relates to https://github.com/ExpressionEngine/ExpressionEngine/issues/247

**How To Reproduce**
With the original files from Release 5.2.5 a simple channel:entries-loop with a relationship field (as parents) **do parse perfectly**: `{parents channel='channelxy'}<a href="{parents:comment_url_title_auto_path}">{parents:title}</a>{/parents}` **BUT** within a channel:entries-loop with an entry as child, the code **does not parse** and the tags get displayed raw in the frontend: `{fieldxy show_future_entries='yes' status='not Closed'}{fieldxy:entry_date format='%H:%i'} {fieldxy:channel}: {fieldxy:title}{/fieldxy}` that worked fine before upgrading to 5.2.4 and 5.2.5

Now if I undo [the change made to system/ee/legacy/libraries/relationship_parser/Tree_builder.php in 2.5.4 on line 359 ](https://github.com/ExpressionEngine/ExpressionEngine/commit/82aeb671619290ce7ab7ade43cf482aabd823aaa), the `parents`-Tag does not render anymore, but the `childs` do work perfectly again!

**Error Messages**
Unparsed ee-tags (see «How To Reproduce»)

**Environment Details:**
 - Version: 5.2.5
 - PHP Version 7.2.20 / 7.1.23
 - MySQL Version 5.7 / 5.7
 - OS: ubuntu / macOS
 - Web Server: Apache

**Comment by robinsowell** [comment]
Hrm- I'm not reproducing. Here's my test, top tag has a parent tag in it, second one is children:

<img width="1015" alt="Screen Shot 2019-07-26 at 11 15 14 AM" src="https://user-images.githubusercontent.com/1181219/61962095-cb2a1a00-af96-11e9-9ef0-5087d7ca1082.png">

What am I missing in the test?

**Comment by albuvee** [comment]
OMG, there was a minor typo in our (quite complex) template which apparently, I suspect, was ignored by EE for the last two years 😅 (also: no Syntax-Error) … well, now its corrected and of course now it works 🙄 🙈 sorry for this one!

**Comment by robinsowell** [comment]
Ha- well, turnabout is fair play. That's why it took me so long to figure out the other one.  Syntax error in my test making me think it was still broken.

Fingers crossed, we're all good!
