### ISSUE TITLE
Password Validation js link 500 error

### ISSUE THREAD

**Issue by jHards** [ExpressionEngine/ExpressionEngine#2679]
On version 6.4.3, using tag `{exp:member:validation_url fields="password"}` returns a 500 error. The [docs](https://docs.expressionengine.com/latest/member/password-validation.html#parameters) suggest that this should be allowed.

The issue seems to be in [mod.member.php line 2719](https://github.com/ExpressionEngine/ExpressionEngine/blob/87526473ae1f879c2f31709322b7b586addd7aba/system/ee/ExpressionEngine/Addons/member/mod.member.php#L2719) where function `passwordValidate` is called dynamically but doesn't exist.

I'm happy to propose a fix but I'm not sure what the original intention of that code block is - any direction appreciated.

**Comment by intoeetive** [comment]
@jHards looks like those functions have been refactored, but the Member module wasn't updated properly. Thanks!

**Comment by jHards** [comment]
> @jHards looks like those functions have been refactored, but the Member module wasn't updated properly. Thanks!

Happy to support if you point me in the right direction?

**Comment by intoeetive** [comment]
Do not worry, I'll get the fix ready soon!
