### ISSUE TITLE
Legacy member fields not showing on Personal Settings profile page

### ISSUE THREAD

**Issue by tobystokes** [ExpressionEngine/ExpressionEngine#268]
**Description of the problem**

since 5.2.5, specifically commit https://github.com/ExpressionEngine/ExpressionEngine/commit/764ecac4955c673c994ff9df4dcadde3ac1a251c

legacy member fields (store in exp_member_data) no longer show in  /cp/members/profile/settings. Newly created member fields, do show.

**How To Reproduce**

1. Create custom member field
2. [have existing custom member fields created in earlier versions in exp_member_data]
3. Visit  Personal Settings profile page in the CP

**Environment Details:**
 - Version: 5.2.5
 - PHP Version 7.1.26
 - MySQL Version 5.6
 - OS: Linux, macOS
 - Web Server: Apache

**Additional context**
I can see that change refers to a cache which I haven't inspected, but if so, the upgrade process and clearing the caches manually didn't seem to change the behaviour.

**Comment by pyrobob83** [comment]
Thanks for opening an issue for this Toby - +1
