### ISSUE TITLE
File Model to include path parameter

### ISSUE THREAD

**Issue by blairliikala** [ExpressionEngine/ExpressionEngine#2683]
Include a URL path to the file in the File model.  When needing to access files within an add-on, it seems common to access the file itself, or send the url of the file to another service. This requires the URL path to the file.  I was a little surprised this wasn't part of the file already.  Currently adding this to the model might look something like this:

```php
$files = ee('Model')->get('File')->all();

$result = [];
foreach($files as $file)
{
   $file->url = $file->UploadDestination->url.rawurlencode($file->file_name);
   $result[] = $file;
}
```

That's fine and all, and has been standard boilerplate in my add-ons.  Instead it would be easier for developers to simply access it by a method or parameter like:

```php
$files = ee('Model')->get('File')->all();
$file->url;
// or
$file->getUrl();
```

[x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by jcogs-design** [comment]
100% support for this.
However this appears to be another instance that is affected by the current oddity in EE system configuration that tolerates setups that do not have a value specified for `base_path` - without which any attempt to work out (or provide via this kind of canned solution) struggles ... so bump for that one too (making base_path and base_url required settings).

**Comment by intoeetive** [comment]
@blairliikala @jcogs-design it's already there, just the name is not what someone would expect :) (and the docs really need an update!)
`$file->getAbsoluteURL()`
and also
`$file->getAbsoluteManipulationURL('cropped')` if you need URL for manipulated version

Also doing it like in first example does not take subfolder into account, so is not really good for EE7

**Comment by blairliikala** [comment]
Well nuts, so it is!  And missing that in the docs was likely also me!  Double #fail on my part.

**Comment by intoeetive** [comment]
Well, we changed A LOT of things on Files since you've added docs to Models! So that's on us :(
