### ISSUE TITLE
Add additional HTML elements to stylesheet

### ISSUE THREAD

**Issue by blairliikala** [ExpressionEngine/ExpressionEngine#2685]
Add the additional types to the control panel stylesheet, such as `<input type="search">` `url` `date` (and date's variations).  Currently when adding these types they show unstyled.  Only a few, such as `text` and `textarea` are shown correctly in the control panel.  These additional types add better semantic value, and come with benefits for that type, but the lack of styling makes them less ideal to use.

Additionally style the `read-only` input property.

Add styling for the additional elements:
- `<dl>`
- `<details>` (and replace the show/hide field input, I have some styles for this one)
- `<progress>` (and replace the less semantic div progress bar)
- `<menu>`
- `<dialog>` (and change the modals and alerts to use it)

Increasing the use of the different HTML elements increases semantic markup, and improves accessibility.

[x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
@blairliikala are you referring to the fact that if add-on is providing inputs for CP pages (such as custom fieldtypes), those don't have styles at all by default? (maybe a screenshot here would be useful)

**Comment by blairliikala** [comment]
<img width="1173" alt="Screenshot 2023-01-03 at 10 06 08 AM" src="https://user-images.githubusercontent.com/4128963/210395143-654d6f39-e380-4fa4-b94c-e33d17a2796e.png">

The code for that is:
```php
      $html = "<input type='text'><br />";
      $html .= "<input type='search'><br />";
      $html .= "<input type='date'>";

      return $html;
```

And yes on if an add-on is providing inputs, but also in the form service.

**Comment by blairliikala** [comment]
<img width="1115" alt="Screenshot 2023-01-03 at 10 09 35 AM" src="https://user-images.githubusercontent.com/4128963/210395708-5c6e129f-5546-4e26-a014-25d6d22189a4.png">

So within a `ee:_shared/form` array, if the type was url or search..etc. then it would be blank.

```php
array(
   'title' => lang('test'),
   'desc' => lang('test_desc'),
   'fields' => array(
     'test_url' => array(
         'type' => 'url',
     )
   )
)
```
