### ISSUE TITLE
Expression engine Pro variable throws UNDEFINED VARIABLE: HEADER_SORTS after upgarde to EE7

### ISSUE THREAD

**Issue by ghost** [ExpressionEngine/ExpressionEngine#2700]
I have upgrade Expression Engine from 5.3 to 7 after upgrade i am facing Notice like `UNDEFINED VARIABLE: HEADER_SORTS ee/ExpressionEngine/View/_shared/table.php, line 320`

Above error is faced in Pro Variables. Pro variable is coming from the name Low variables in old version of Expression engine(EE). In new version of Expression Engine the Low variables is the part of Expression engine a core system which remove the dependancy of third party package Low variables as in old version of EE.

If we are going to change in core file by defining constant than it's working fine, but it's not a proper solution as core file will be change any time while we are upgrading the version.

**Comment by intoeetive** [comment]
@akshay-bhatt-softweb on what page(s) do you see the error?

Also screenshot would be helpful

**Comment by ghost** [comment]
![ErrorScreenshot](https://user-images.githubusercontent.com/122026617/210792466-d17f808a-789c-477c-8723-4a268053e4f6.png)

@intoeetive pls see the attached screenshot

**Comment by ghost** [comment]
@intoeetive I am getting error inside Pro variables Expression Engine plugin

**Comment by ghost** [comment]
Hii @intoeetive and @matthewjohns0n any update on above issue? As we need to go live as early as possible with this update

**Comment by matthewjohns0n** [comment]
Hi @akshay-bhatt-softweb, I was unable to replicate the issue using the default Pro Variables variable types. What variable types are you using in that variable group?

Your screenshot provided just enough information that I was able to look at the error thrown and provide what I think is a fix for the issue. Can you pull my branch and confirm that it fixes your issue?

**Comment by ghost** [comment]
@matthewjohns0n yes i got the solution by taking pull of your branch the issue is fixed in your branch. I'm closing issue here.

**Comment by matthewjohns0n** [comment]
@akshay-bhatt-softweb we ended up reverting that commit, as it was causing problems elsewhere. Can you provide more information so we can get a fix for this into the core? To continue, we would need to know the following:

 - Add-ons that are installed
 - EE version you were upgrading from
 - PHP version
 - Specific field that is failing, with field settings

**Comment by ghost** [comment]
Hii @matthewjohns0n,

Note: I have upgraded EE5.3.0 to 7.2.5 using manual upgrade as mentioned on official website: [Expression Engine](https://docs.expressionengine.com/v6/installation/updating.html#if-updating-from-expressionengine-3-or-higher)

- Earlier in Expression engine(5.3.0) i was using Low Variables and after upgrade Expression engine 7.2.5 it's automatically remove the Low variable and now it's using pro variables. As you know that Low variable are now supported as Pro variable in 7.2.5
- I am upgrading from EE 5.3.0 to EE 7.2.5 latest one
- PHP version 7.4
- It showing me the error in `UNDEFINED VARIABLE: HEADER_SORTS ee/ExpressionEngine/View/_shared/table.php, line 320` after upgrade to EE 7.2.5

**Comment by ghost** [comment]
Hii @matthewjohns0n,

Any update on above?

**Comment by matthewjohns0n** [comment]
Thanks for the response. Regarding point 4 - Can you send me information about the variable that is throwing the error? I see in your screenshot that it is called "Roth IRA Certificate 24-35 Months Rate". What type of Pro variable is this? What are its settings?

**Comment by ghost** [comment]
Ohh... Actually it's not an error in variables which i created("Roth IRA Certificate 24-35 Months Rate") earlier. The error is saying there is no any single row to show inside this variable. 

So, in a core file **table.php** by default you have not defined any value to this variable `$header_sorts = null` or something that's why it's throwing me this error. You can see the core file **table.php** of EE old version 5.3.0 in that version this variable is not used that's why it is working fine. In newer version you have added it but you have to handle the null value for that variable than definitely it will be work fine.

**Comment by matthewjohns0n** [comment]
That does look to be the problem you are running into, but I am unable to replicate it. Without being able to replicate it, there is not a lot I can do. 

It would be very helpful if you could provide the information requested about how you have pro variables set up. What type of variable is "Roth IRA Certificate 24-35 Months Rate", what are its settings, etc. Thank you!

**Comment by ghost** [comment]
Hii @matthewjohns0n,

Here is the video which i have made for your reference using that you can get more idea about it.
[Reference Video Link](https://watch.screencastify.com/v/2iYJqhMyupHooar0yIBC)

**Comment by ghost** [comment]
Hii @matthewjohns0n,
Any update on above issue?

**Comment by matthewjohns0n** [comment]
Hi @akshay-bhatt-softweb, thanks for recording that video. I haven't been able to spend a lot of time on this yet, but I'll keep you updated on the progress of this ticket when it changes.

**Comment by ghost** [comment]
Hii @matthewjohns0n can you pls put this issue on first priority? As we want to go live with EE latest version 7

**Comment by matthewjohns0n** [comment]
@akshay-bhatt-softweb from your video it looks like you are trying to use a grid inside a pro variable, without setting the grid field name, which is a required field. If you set the field name does it work for you?

**Comment by matthewjohns0n** [comment]
I fixed the issue you were experiencing with the settings not showing the correct error when saved without the required values. 

I can still not personally replicate the problem you're running into though. I tried deleting the `col_name` and `col_label` from the database, but I still can't get that error to throw. I think the best path forward will just be setting the name and label on that field.

**Comment by matthewjohns0n** [comment]
Also, are you currently running EE 7.2.7? It would definitely be worth trying to upgrade to the latest version.

**Comment by ghost** [comment]
> @akshay-bhatt-softweb from your video it looks like you are trying to use a grid inside a pro variable, without setting the grid field name, which is a required field. If you set the field name does it work for you?

Hii,

Yes that was i am trying to say that in older version may be that field was not required that's why this error thrown in this new version. In a new version this field is required so this error is not occurred in new version. I have taken a pull of your branch, it working fine now. Thank you

**Comment by ghost** [comment]
> Also, are you currently running EE 7.2.7? It would definitely be worth trying to upgrade to the latest version.

Yes i just upgraded it today.
