### ISSUE TITLE
`{exp:member:edit_profile}` template parsing errors

### ISSUE THREAD

**Issue by jHards** [ExpressionEngine/ExpressionEngine#2703]
**Description of the problem**
2 separate but similar issues with this tag.
1. The vanilla `{exp:member:edit_profile}` tag with no custom content between the tags isn't parsing `{lang:x}` variables.
2. When custom content between the tags is entered with `include_assets=yes` parameter, page load fails with errors shown below.

**How To Reproduce**
1. Put `{exp:member:edit_profile}{/exp:member:edit_profile}` into a template and access whilst logged in.
2. Put `{exp:member:edit_profile include_assets="yes"}<h4>Member</h4>{/exp:member:edit_profile}` into a template and access whilst logged in.

**Error Messages**
1. In my example I see `{lang:edit_your_profile}`, `{lang:update}` and `{lang:required}` remaining on the front end.
2. See screenshot below

**Screenshots / Videos / Template Code**
1. N/A
2. Screenshot:
![image](https://user-images.githubusercontent.com/17785714/210899099-e3f424c2-46ae-410d-ab9a-40040fa6b420.png)

**Environment Details:**
 - Version: 7.2.5
 - PHP Version 7.4.33

**Possible Solution**
Similar to other recent errors, I assume that core functions have been refactored but the Members addon hasn't been updated - hopefully a quick fix!

**Additional context**
N/A

**Comment by intoeetive** [comment]
@jHards I wasn't able to replicate the error on your screenshot using the code you provided. Did you by chance make any modifications to module code?

Also I believe `{lang:` variables are not supposed to be parsed when using template tags. They are available if you use legacy member templates, but not 'regular' templates

**Comment by jHards** [comment]
Following update to 7.2.6 error 1 is still there but 2 has seemingly been resolved, however this is not a fresh install and has been around with member legacy templates before. What's the expected behavior if you just drop in an empty pair of tags `{exp:member:edit_profile}{/exp:member:edit_profile}`?

I have `$config['legacy_member_templates'] = 'n';` in `config.php` but it seems that the empty tags for me are loading the template from `themes/ee/member/edit_profile_form.html`.

**Comment by intoeetive** [comment]
`{exp:member:edit_profile}` is generally not designed to work as empty tag par.
Can you describe the use case of having empty tag pair? (I think it _could_ be loading the legacy template indeed as a side effect of supporting both legacy template and template tags in same function)
(if you really need to have it empty, try adding a space or empty div inside)

**Comment by jHards** [comment]
I don't need it empty (my main issue was 2 which is resolved), but with `$config['legacy_member_templates'] = 'n';` I would have expected it to return an error message or just a blank?

**Comment by intoeetive** [comment]
Legacy member templates is a different feature : https://docs.expressionengine.com/latest/member/profile-templates.html
It does not stop you from using member tags (in fact, member tags were made available so that people would need to use legacy member templates)

**Comment by jHards** [comment]
As you say, legacy member templates are separate, so particularly when `$config['legacy_member_templates'] = 'n';` if you were to put an empty tag pair of `{exp:member:edit_profile}{/exp:member:edit_profile}`, I don't think it should load a legacy member template (which it currently seems to be doing)

**Comment by intoeetive** [comment]
Yes, that makes sense to check `legacy_member_templates` setting as extra precaution

**Comment by intoeetive** [comment]
This is getting released in EE 7.4.0
