### ISSUE TITLE
exp:consent:form does not log data from non-member users

### ISSUE THREAD

**Issue by 1llum1ina71** [ExpressionEngine/ExpressionEngine#271]
{exp:consent:form consent='ee:cookies_functionality' form_id="cForm"}
          {consents}
              <p>{consent_request}</p>
              <input type="hidden" name="{consent_short_name}" value="y" {if consent_granted}checked{/if}>
          {/consents}
          <input style="margin-bottom: 25px;" class="button" type="submit" name="submit" value="Accept">
      {/exp:consent:form}

This seems to work fine with logged in users, creating a log verifying their consent. This isn't the case for someone who isn't logged in. The cookie is saved to their browser but fails to produce a log.
Recently upgraded to v5.2.2

**Comment by derekjones** [comment]
Currently the consent audit log requires a member ID and does not log anonymous consents, which last only for the browser session. Can you describe how having logged anonymous session consents would be beneficial?

**Comment by 1llum1ina71** [comment]
It would be beneficial by allowing admins to have a record of users who are actually using the site.

**Comment by 1llum1ina71** [comment]
Is that not needed to be GDPR compliant?

**Comment by derekjones** [comment]
If anonymous consents were logged, you would have log entries like:

```
consent_audit_id consent_request_id member_id action                          log_date
108              3                  0         consent granted via online_form 1527125885
```

member_id of 0 doesn't seem helpful to me for an audit where you must prove consent: it's anonymous and untraceable back to the acting visitor. The purpose of that log is for auditing for the "data protection officer" to be able to demonstrate consents for someone who the site has collected Personally Identifiable Information. It's not a general activity log; can you help me understand what you would gain and do with such an activity log?
