### ISSUE TITLE
preg_split error message with php 8.1

### ISSUE THREAD

**Issue by Zignature** [ExpressionEngine/ExpressionEngine#2735]
**Description of the problem**
Came across the same error as in issue #2348 concerning another line in `ee/ExpressionEngine/Service/Formatter/Formats/Text.php` after upgrading PHP to 8.1.0.

**How To Reproduce**
Upgrade PHP from v7.4.29 to v8.1.0

**Error Messages**
```
preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated
ee/ExpressionEngine/Service/Formatter/Formats/Text.php, line 160

Severity: E_DEPRECATED
```

**Environment Details:**
- EE Version: 7.2.5     
- PHP Version 8.1
- MariaDB 10.4.24
- Apache 2.4.54
- Windows 11 Pro 22H2 build 22621.963

**Possible Solution**
Line 160:     
`$censored = preg_split('/[\n|\|]/', $censored, null, PREG_SPLIT_NO_EMPTY);`

should probably be changed to:     
`$censored = preg_split('/[\n|\|]/', $censored, 0, PREG_SPLIT_NO_EMPTY);`

**Comment by Zignature** [comment]
I posted an issue #2735

**Comment by Zignature** [comment]
I noticed another one on line 382:     
`foreach (preg_split('/[\s\|]/', $options['options'], null, PREG_SPLIT_NO_EMPTY) as $param) {`

**Comment by intoeetive** [comment]
@Zignature the referenced PR is fixing that one as well
