### ISSUE TITLE
Deprecation notice on opening of add-on manual (PHP 8.1.0)

### ISSUE THREAD

**Issue by Zignature** [ExpressionEngine/ExpressionEngine#2739]
**Description of the problem**
When running on PHP 8.1 opening a manual (local readme.md file) of any add-on sparks a deprecation notice.

**How To Reproduce**
1. Go to the `cp/addons` page
2. Open a manual of any add-on. The manual has to be the local `readme.md` file. External manuals are not affected of course.

**Error Message**
```
Deprecated
urlencode(): Passing null to parameter #1 ($string) of type string is deprecated
ee/legacy/libraries/Cp.php, line 552

Severity: E_DEPRECATED
```

**Environment Details:**
 - EE Version: 7.2.6
 - PHP Version: 8.1.0
 - MariaDB Version: 10.4.24
 - Apache Version: 2.4.54
 - Windows 11 Pro 22H2 build 22621.963

**Comment by Zignature** [comment]
I noticed the plugin documentation file (README.md) needs a capitalized name.
`readme.md` doesn't work and `README.md` _does_ work.

#### Environment Details:
- EE Version: 7.2.5+
- PHP Version: 8.1.0
- MariaDB Version: 10.4.24
- Apache Version: 2.4.54
- Windows 11 Pro 22H2 build 22621.963

**Comment by intoeetive** [comment]
@Zignature yes, that is correct as per the docs. The casing is important when working with files in EE.
https://docs.expressionengine.com/latest/development/guidelines/in-app-documentation.html

**Comment by Zignature** [comment]
Guess I missed that part in the docs. I apologize.
