### ISSUE TITLE
Auto updating EE fails with php 8

### ISSUE THREAD

**Issue by Fred2341** [ExpressionEngine/ExpressionEngine#2744]
All of my websites, including one with latest installation of EE fail to update automatically with php 8.
With php 7.4 there are no problems.

**Comment by intoeetive** [comment]
@Fred2341 I suspect there's a problematic add-on.

Is there any error log that you can provide?

**Comment by Fred2341** [comment]
Thanks for getting back, Yuri.
 I discussed with an EE expert. The cause appears to be CE image.
On one site he replaced it with an alternative he had made. My other sites
I leave at EE 6.4.4 and ignore updates until they're is a better solution.

Regards
Fred

vriendelijke groet
Fred

Op vr 13 jan. 2023 11:10 schreef Yuri Salimovskiy ***@***.***

**Comment by matthewjohns0n** [comment]
@Fred2341 Just wanted to let you know that @jcogs-design makes an add-on that replaces nearly all functionality of CE Image that is regularly updated and currently supports PHP 8. I haven't personally used it, but I've heard many good things, so I figured I'd throw it out there as a potential option:
https://expressionengine.com/add-ons/jcogs-image

**Comment by Fred2341** [comment]
That is the very add-on that Jelle Dijkstra used.
Regards

Fred

Op vr 13 jan. 2023 16:31 schreef Matt Johnson ***@***.***>:
