### ISSUE TITLE
Extend {exp:member:has_role} role_id parameter to accept multiple values

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2749]
**Describe the solution you'd like**
The current implementation of the `{exp:member:has_role}` tag (at least on EE6) takes the paramter `role_id=`, and this value is limited to a single value (i.e. one number).

There are times when you might want to check a member against multiple roles; the current implementation of this tag requires you to use multiple instances of this tag to achieve this end, which is inefficient.

**Describe alternatives you've considered**
Use multiple instances of this tag, one for each role.

**Comment by intoeetive** [comment]
This is getting released in EE 7.4.0
