### ISSUE TITLE
channel relationship having issues

### ISSUE THREAD

**Issue by daakbahok** [ExpressionEngine/ExpressionEngine#275]
I have a channel containing multiple related channels. In EE3, it worked fine when I try to access those entries and related entries. but having issue in EE4

I am using it like below-

{exp:channel:entries channel="channelname" orderby="date" entry_id="xxx" disable="categories|category_fields|trackbacks" sort="desc" dynamic="no" site="default_site" parse="inward"} 
       	{related_chapters}
      		<p>{related_chapters:entry_id}</p>
      	{/related_chapters}
        {related_exams}
        	<p>Exam title: {related_exams:title}</p>
        {/related_exams}
{/exp:channel:entries}

The output is like below-

{related_chapters}

{/related_chapters}
Exam title: abc

**Comment by robinsowell** [comment]
Can you upgrade to the latest version of 5? I know there have been a number of tweaks that could affect relationships.

**Comment by daakbahok** [comment]
After digging deeper, what I found was that relationships list had a collision (id=>name). the related_chapters with field_id=xx was  being overwritten by another (which is a grid)

**Comment by robinsowell** [comment]
That rings a vague bell, but I'm not sure if it's the same issue you're running into or not. Did you upgrade to the latest and you're still running into it?

And if so, sounds like to replicate I want a relationshp field with the same shortname as a grid column- correct?

**Comment by daakbahok** [comment]
What I did was checking if there is any collision in the ID fields relationships array. If there is a collision, I am not adding that. this is done in the __construct() of **system/ee/legacy/libraries/relationship_parser/Tree_builder.php** line 45. if $id key already exists in the array_flip(relationship_field_names) array, then I am not adding it

As for yor question, I don't think that's the way to replicate it

**Comment by robinsowell** [comment]
And just to be sure- what version are you on now?

**Comment by daakbahok** [comment]
4.3.8

**Comment by robinsowell** [comment]
Can you go ahead and upgrade to the latest v5? It shouldn't take a minute. Just make a quick backup and use the in-app updater.

I don't know that it will fix it, but it makes the most sense to debug it on the current code base.  I know for certain there have been changes to both grid and relationship parsing in v5.

**Comment by daakbahok** [comment]
Actually I figured it out. I am hesitating to upgrade to v5 yet because some of the 3rd party addons we use are not compatible with EE5 yet.

**Comment by robinsowell** [comment]
Glad you got it figured- hopefully it's moot in v5.

And you might double check on the v3 add-ons.  I'd say the majority of them will work on v5, so even if they don't explicitly state they're good, they may be.
