### ISSUE TITLE
Add Categories to Conditional field conditions options

### ISSUE THREAD

**Issue by melbazany** [ExpressionEngine/ExpressionEngine#2750]
Would love the ability to conditionally display a field based on categories selected:

Ex: If any category is selected, show X field.
Ex: If category named 'Foo Bar' is selected, show X field.
Ex: If at least 1 category from group X is selected, show X field.

At this point, I've just been adding a Notes field to the channel entries to make sure users are aware of the condition in order for a field to be utilized properly..

**Comment by intoeetive** [comment]
Moved to discussion here: https://github.com/ExpressionEngine/ExpressionEngine/discussions/2929#discussioncomment-5215422
