### ISSUE TITLE
Multi Login not working

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#2752]
Followed [Multi Site Login](https://docs.expressionengine.com/latest/msm/overview.html#multi-site-login)
But it's not working. 
Each website have correct cookie settings.
When you try to login to a website, the next website return

Error Caught

Call to a member function filter() on null

Auth.php:719

Or too many redirects popup sometimes too

**Comment by appricosa** [comment]
Seriousy? I am encountering this issue NOW, AFTER the update. Never had this before. Please undo whatever you have done here. When I log in via the regular login form on a multi-site installation, I receive the error "multi_auth_redirect_site_not_found". Only works with CP login but not with login_form tag. You can see this wonderful "feature" here: https://kunden.renvert.com/

**Comment by TomJaeger** [comment]
@appricosa Just to confirm.. what version of EE are you on?

**Comment by appricosa** [comment]
Hi @TomJaeger – I just updated from 7.2.12 to 7.2.13

**Comment by intoeetive** [comment]
@appricosa how does your `multi_login_sites` config value look like? Are all URL listed there valid sites sharing same EE installation?

**Comment by appricosa** [comment]
Hi @intoeetive – I gotta hand it to you – your support here is insanely fast. I think, that was the right hint to fix this issue. I have added this line to the user config, and now it seems to have been fixed:

`$config['multi_login_sites'] = "https://renvert.com/|https://kunden.renvert.com/";`

Just strange that this error did not appear in earlier versions without this explicit line..
Thanks a lot guys – I was about to roll back to 7.2.12

**Comment by intoeetive** [comment]
What was it set to before? Or you didn't have it set at all? (but you think multi -sites login still worked some time ago?)

**Comment by appricosa** [comment]
I had not set that line at all – I had followed the instructions here in the docs [Multi Site Login](https://docs.expressionengine.com/latest/msm/overview.html#multi-site-login) where it says, this line was necessary for different top level domains, but not, if the second site is a subdomain with a shared cookie domain.
So something must have changed here regarding behaviour of subdomain sites.

**Comment by intoeetive** [comment]
Thank you. I'll reopen the issue so we could test that. Maybe we broke something indeed (

**Comment by appricosa** [comment]
Okay, but thanks a lot for the quick response. That did fix it for my multi-site instance running one top level plus sub-domain. Happy to share any more details if necessary.
