### ISSUE TITLE
Table Class set_data method throwing error

### ISSUE THREAD

**Issue by dmc-webdev** [ExpressionEngine/ExpressionEngine#2765]
I'm writing an add-on that outputs a table of data to the user. It is not for the CP, but it throws the following error:

No such property: 'cp' on ExpressionEngine\Legacy\Facade

ee/ExpressionEngine/Legacy/Facade.php:128

The code is in my mod.addon.php file in a method called results. Nothing fancy.

I removed my code and inserted the demo code from the [Table Class](https://docs.expressionengine.com/latest/development/legacy/libraries/table.html#example-improving-usability-for-large-amounts-of-data) docs into my method and it throws the same error. If I remove just the set_data call, it will output the table with the headers as expected. I'm not sure if it is intentional that the class only be used in the CP, but it seems like this should work in a module method as well.

Using EE 7.2.6

**Comment by intoeetive** [comment]
@dmc-webdev it looks like the legacy table library contains some code that is designed to only work in CP.

We also have `CP/Table` table, which as well - as is stated in it's name - is designed to work in CP.

We will probably classify this as feature request, and not as a bug - but could you tell us more about your intended usage of Tables functionality on front-end, so we could think of best possible implementation?

**Comment by dmc-webdev** [comment]
I'm writing an add-on for a client that will pull race results from the [Run Signup API](https://runsignup.com/API/Methods). So taking the results array and just pushing it into the set_data method would be great. I have created the add-on to just have a tag pair with the race ID info passed into it. So get the race results from the API and output a table.

The set_columns and generate methods work without being in the CP. My work around right now is using add_row. That works, but it's cumbersome.

If you need anything more specific, just let me know.
