### ISSUE TITLE
Active/Inactive Template from Template settings not from Expression engine Template settings

### ISSUE THREAD

**Issue by ghost** [ExpressionEngine/ExpressionEngine#2776]
Hii there,

I want to add feature like active/inactive flag in template settings not in Expression engine template setting. I have seen the all addon feature but no one has feature like this to edit core files with new features and add new flag in database settings.
[Reference Image](https://ibb.co/6N42BNm)

**Comment by intoeetive** [comment]
@akshay-bhatt-softweb please see the documentation on [Shared Form View](https://docs.expressionengine.com/latest/development/shared-form-view.html#available-field-input-types)

It is not 100% clear what you are asking here, but I get impression that this is a question you need to ask on [Forums](https://expressionengine.com/forums) or in [Slack](https://expressionengine.com/blog/join-us-in-slack)

**Comment by ghost** [comment]
Hii @intoeetive,

I think you are not getting my question properly. I am talking about to edit the setting page of Template Tab of left menu not to edit the setting page of Expression engine.
[Reference Image](https://ibb.co/h1N308s)

**Comment by intoeetive** [comment]
Yes @akshay-bhatt-softweb it is completely not clear what you are asking here.

If this is a feature request, please describe in as many details as possible using this template: https://github.com/ExpressionEngine/ExpressionEngine/issues/new?assignees=&labels=&template=2-feature-request.md

If this is something that you need to customize in your own EE installation, please use the community Slack and Forum I mentioned above.

We do not provide support in GitHub, but we do offer paid [support plans](https://expressionengine.com/support).
