### ISSUE TITLE
RTE:CKEditor - stop stripping trailing slash from IMAGE links

### ISSUE THREAD

**Issue by ttmwebdesign** [ExpressionEngine/ExpressionEngine#2777]
**Is your feature request related to a problem? Please describe.**
Our client uses trailing slashes on their site for internal URLs. In order to maintain consistency with all internal links, all of them should have a trailing slash, particularly the urls in `<a href="">` tags. This works fine in TEXT links in RTE:CKEditor, but in IMAGE links, the trailing slash gets stripped out after the entry is saved. This is not a desired effect.

**Describe the solution you'd like**
The image widget should be agnostic of URL syntax. It should observe a trailing slash if one exists, or the lack of one. Whatever the user puts into that field should be left as-is, even including bad URLs. That is for a human editor to worry about and fix, not the software.

**Describe alternatives you've considered**
The client used to use Wygwam, which if I recall, left the URLs as-is, and did not overstep and strip slashes off of them. We would prefer not to need to go back to it if possible.

- [ ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
@ttmwebdesign I have tested this on EE 7.2.7 and wasn't able to replicate the issue - see the screenshot.
Is there a specific link format that I need to use?
![image](https://user-images.githubusercontent.com/752126/215529740-9915faf8-3acd-4e8f-9cca-33b050d18e42.png)

**Comment by ttmwebdesign** [comment]
Is that after saving the entry?

**Comment by intoeetive** [comment]
Correct, this is after entry has been saved

**Comment by ttmwebdesign** [comment]
Our version is EE7.2.5, but I can’t upgrade until 7.2.8 is released for the other issue I submitted. Once we can upgrade I will check it out and see if it is resolved. Thanks.

**Comment by intoeetive** [comment]
I believe there have been no changes in RTE between these versions. That's why I think there might be something specific about the links that are inserted

**Comment by ttmwebdesign** [comment]
Ok, I did some testing, and I think I have determined under what conditions it strips the trailing slash...

If the URL looks like your sample, AND is a literal URL that ExpressionEngine serves by a channel, it will strip the trailing slash. If it does not exist within EE, it does not strip the slash.

We have URLs like `/blog/this-article-long-title-type/`.  If that exists as something that EE will generate (via channel entries), it will strip the slash. _If_ the preceding slash is removed from that same URL, it _does not_ strip the trailing slash. It does not seem to apply to category URLs, only entry URLs.

So, in summary, if the entry exists within EE:
This trailing slash is removed: `/blog/this-article-long-title-type/`
This trailing slash is left alone: `blog/this-article-long-title-type/`

Another thing of note -- EE/Ckeditor do not seem to care whether the preceding slash exists in order to create a correct URL -- it does so in both cases. So I wonder then, if what is happening here, is when a preceding slash exists, the code removes that one, and also picks up on the trailing one and removes it as well? But only if the URL is an actual EE generated one for an entry, otherwise it does not seem to care either way.

**Comment by ttmwebdesign** [comment]
Another note -- the obvious fix would be for the client to change behavior and stop adding in the preceding slash, cool, easy enough.

However, the big sticking point here now is -- the client has been doing this with all of their linked images in their content for a while. Their SEO team has done new crawls since we upgraded EE and switched away from Wygwam to RTE, and is seeing a bunch of 301 redirects - lots and lots, where there were few before.

Wygwam did not care that the trailing slash _and_ the preceding slash both existed, but CKEditor apparently does care, and removes both the preceding and trailing slashes.  We do have a clause in our HTACCESS file that will automatically add the trailing slash to URLs _when clicked_ if they don't exist, but this is not going to stop EE from displaying URLs without the trailing slashes on Images, which the crawls are picking up on and causing a bunch of noise.

I don't suppose it's possible to update RTE:CKeditor to only remove the first slash and ignore all others rather than pick off both the first and last slashes for EE entry URLs? 

edited to add:  I could have sworn that text links behaved the way we expected, but it turns out that they too are stripping that trailing slash if the preceding slash exists. Which means we may have many more 301s cropping up in the crawl for those as well. :(

second edit to add:  Even worse -- I can't even fix this within the database, because those URLs are stored like `{page_11329}` when it strips both of the slashes from them. So it seems even if CKeditor were to be updated to not strip the trailing slash where a preceding one exists, it wouldn't fix the issue we've run into, we'll have to manually edit every instance.

**Comment by intoeetive** [comment]
I am still unable to replicate using existing links on the site :(

Do you have Structure / Pages running here? Does it still behave the same if you temporary disable extensions?

**Comment by ttmwebdesign** [comment]
Yes, this site uses Structure extensively. I’ll have to try disabling extensions and see what it does in that instance.

**Comment by ttmwebdesign** [comment]
Disabling extensions changed nothing. It still removes the trailing slash upon saving of the entry when the preceding slash exists. I don't want to go as far as uninstalling Structure just to prove that it would start to work if we weren't using it.

Instead, I did a test on two other unrelated sites -- one with Structure installed (ee7.1.6), and the other without (ee6.3.5), and it seems it is definitely Structure that is coming into play there, as it deletes the trailing slash when the preceding one exists on the other site with Structure, but does not on the site without.

Additional info re: disabling extensions -- That does not stop Structure from doing its thing. Earlier, I had tested on an existing test post in a Structure controlled channel (listing type). Then I thought, I should test a new entry in the same channel after disabling extensions -- it still ends up posting a new row in the DB table for exp_stucture_listings once that entry is created, and the trailing slash deleting still remains. Next, I tested a new entry in a channel that is _not_ managed by Structure, and it still deletes that trailing slash when the first one exists.

**Comment by ttmwebdesign** [comment]
I did some additional testing with the original EE5 version of the site that used Wygwam - it looks like it would only save the page as `{page_12345}` if the full URL was added to the link box, as in `https://www.domain.com/blog/article-title`. If the relative URL was used, it saved it literally instead of translating it to the page designation. So `/blog/article-title/` would be in the database literally as `<a href="/blog/article-title/">`. And for reference, that was also while Structure was installed and in use, albeit while it was still a standalone add-on and not part of EE core.

Edited to add: On the unrelated site I tested earlier that has Structure -- I also happen to have Wygwam installed on it, so I toggled the field I was testing over to it instead of RTE:CKeditor. Opening the image link in there, it had the full URL due to the db saving it as the page designation originally, and edited it to the relative URL instead, with both slashes, and saved, and checked the DB -- and as with the older EE/Wygwam version, it still saves the URL literally instead of translating it.

On that note -- even if the client with the site issue in question were to switch back to Wygwam, we would still need to go back and manually edit the URLs based on how they've been saved as page_12345 in the database since using RTE, so it seems to be a losing situation either way.

**Comment by ttmwebdesign** [comment]
And of course trying the 'remove first slash' on anything but the homepage results in a messy URL, which I should have known but hadn't been checking, since the first place I had seen this be a problem was ON the homepage.

That brings me back to asking if RTE (because I found it also happens in Redactor, so it seems to be an RTE thing, not specific to either editor type) can ignore that format of URL in the same way that Wygwam does? It should not matter whether Structure is there or not; "if relative URL, save as relative URL".

**Comment by intoeetive** [comment]
I am still not able to replicate this myself, will ask the team to investigate

As per my knowledge, RTE does not do any kind of "stripping slashes" stuff, but of course there might be a lot of areas that are hidden from us, because this is third-party code that generates the editor UI

Just to make sure we're on same page, can you post a screenshot of how you add link to the image?

**Comment by ttmwebdesign** [comment]
It's no different than your screenshot, just different words.
Before saving the entry:
![Screen Shot 2023-02-01 at 8 35 16 AM](https://user-images.githubusercontent.com/12754955/216088878-e67fc4f0-5e8f-4a60-8734-a47e55f04755.png)

After saving the entry:
![Screen Shot 2023-02-01 at 8 36 13 AM](https://user-images.githubusercontent.com/12754955/216088931-59829995-e9dc-4975-bb95-af39c69b638f.png)

(the image still exists, for some reason it whites out when clicking the options for the image)

**Comment by ttmwebdesign** [comment]
Out of curiosity, I decided to test out another of the sites on my local machine, that started out in its life on EE7... It has Structure and was not using RTE already but I added a field for testing purposes.

It works there. There is no slash being stripped. So I can see how you're not able to replicate it if you're using a freshly installed copy of EE7.

The common theme among the sites where that trailing slash is getting stripped off, is they are NOT originating as a site in EE7, but in earlier versions. The client site was originally on EE4, if not EE2 or even EE3, so it's been around long enough to have an extensive exp_channel_data table, but only started really using Structure sometime during its EE5 days. It might have been installed prior to that, but not really used.

The other site I used for testing, started out in EE6 and was upgraded (it too had Structure in an earlier version).

In both cases, both also used Wygwam for that field before. I don't know if that makes a difference, but that is another common thing between them.

For more thoroughness, on my EE7.1.6 site (formerly EE6) where I was able to duplicate the stripped trailing slash, I even added a new RTE field and tested it -- it still strips the trailing slash. That site has not been upgraded to EE7 on the production side (local only), so I created an RTE field on the EE6 version, and it too has the slash stripped. 

So it seems it might be an 'older EE' problem. Or maybe a ‘older Structure’ problem? Which then begs the question -- how in the world is this fixable? It seems there's some old baggage in there somewhere that's keeping it from working, but where is the question.

edited to add: I had a thought just now.. The other site I tested and duplicated the issue on, has far fewer things controlled by Structure than the client site does, so I was thinking, what if I take a snapshot of how it is configured as well as a backup of its tables, uninstall it and wipe the Structure tables if they aren’t emptied upon uninstall, then install it again fresh and reconfigure it, and retest. If it works after that then I could safely say it’s something amiss in the Structure tables, but if not then it might be the EE upgrades. I will give that a go this afternoon and report back my findings.

**Comment by ttmwebdesign** [comment]
Update: I uninstalled Structure on my small site, and I decided to try testing the relative URL with trailing slash. I am getting inconsistent behavior. With one relative URL, it seems to allow the slash. With the others, it persistently still removes it. All URLs are for other entries that exist. The difference between the entries, is those that won't allow the slash to exist is a few years old, while the one where it allows the slash to remain was created after the EE7 & Structure upgrades... The older ones still get saved as {page_12345} style, while the new one is saved as what is put into the text field. This is all with Structure gone. Old Structure seems to permanently change how EE sees those entries, even if it's not installed anymore. I even deleted the image and re-linked them to the older entries, and it still digs up the old URL structure.


The client has decided to switch back to Wygwam. I don't know if this weirdness between old Structure / new Structure & RTE will ever get sorted out unless there is some way to force the database to stop translating old Structure based URLs to {page_12345} type format unless it's the full URL.

**Comment by intoeetive** [comment]
Probably too late on this, but I think what might make the difference is the setting that exists in Structure "Add Trailing Slash to Page URLs". So if an entry was saved with that setting off, there will be no trailing slash. And so the link to it will not have a slash. Uninstalling Structure will not make any difference, you would likely need to re-save the entry that does not have slash in order to have that changed
