### ISSUE TITLE
Error when updating from 6.4.3 to 6.4.4 on a newly migrated installation

### ISSUE THREAD

**Issue by PontusMadsen** [ExpressionEngine/ExpressionEngine#2781]
Just migrated from one cloud host solution to another one within Nexcess.
All path and such has been updated in "settings" > "URL and Path Settings", so that the website is working.

But when clicking the "Upgrade now" I get an error thrown in my face:
_Update stoped.
We stopped on Preflight check.
Cannot get contents of path, the path is invalid: /chroot/home/a5ad91f1/little-gamers.com/html/themes/ee/_

In "settings" > "URL and Path Settings", the path is: /chroot/home/af4f72fd/little-gamers.com/html

From 6.4.3
Build: 13/12/2022
PHP: 7.2

To 6.4.4
Build: 10/1/2023
PHP: 7.3.33

Seems like the URL for the theme has been "stuck" to the old server? Somewhere.. in the.. files.. somewhere?
Feels like the PHP-version shouldn't matter.. but..

**Comment by TomJaeger** [comment]
@PontusMadsen thanks for posting all of this.

Just to confirm, is that the default base path?

If so, whats in the following 2 settings a bit lower down.

- Themes path
- Themes directory URL

**Comment by PontusMadsen** [comment]
Yes, it's Default base path.

Themes directory URL = {base_url}themes/
Themes path = {base_path}/themes

**Comment by intoeetive** [comment]
@PontusMadsen other than settings pages, the place where that could be stored is `config.php` file.
Also, worth checking `index.php` and `admin.php` files.

If it's not there, I wonder if it's been cached somewhere by Nexcess while moving between clouds - you should talk to them probably

**Comment by PontusMadsen** [comment]
@intoeetive 
Hi! I checked config.php, no URL that's wrong there. Same goes for index.php and admin.php.
I'll double check with Nexcess and report back when I hear from them.

**Comment by PontusMadsen** [comment]
According to Nexcess, it's not their problem. So I'm left with no idea on how to solve this. Any ideas? I can give you access if needed.

**Comment by intoeetive** [comment]
@robinsowell checking in if you have any ideas here

**Comment by PontusMadsen** [comment]
Solution:

This is the Base/Theme path in my settings in the database. Since I had a different hostname previously, with another username. I found it in the database searching for [xxxxxxxx].

These values have been changed to: [xxxxxxxx]

And the updater works.

**Comment by intoeetive** [comment]
Woof! Glad to hear you've got that fixed :)
