### ISSUE TITLE
New member groups should default to not having access to HTTP-protected templates

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#279]
**Is your feature request related to a problem? Please describe.**
This is some way between a bug report, a feature request, and a security issue.

When a new member group is created, it's given, by default, access to any templates which have HTTP authentication turned on. Good security practices would suggest that this is backwards, since access then has to actively be turned off for any HTTP-protected templates to which this new group shouldn't have access. The default should always provide the greatest security.

**Describe the solution you'd like**
The quickest, easiest solution would be for the default to switch. When a new member group is created, this group should by default be **denied** access to any templates protected by HTTP authentication. It should then be necessary to actively turn on access to any of these templates.

Part of the rationale behind this change is that it's not easy to find out exactly which templates are protected by HTTP authentication — short of going through them one by one. This makes it more likely that templates might be missed, leaving holes in the intended authentication. Because of this, a significant extension of this improvement would be a way to see, for each member group, an overview of which HTTP-protected templates that group has access to. The fundamental suggestion here, though, is that defaulting to **denying** access is the right thing for security.

**Comment by ops-andy** [comment]
resolved in beta-3: https://expressionengine.com/blog/expressionengine-6-public-beta-3
