### ISSUE TITLE
Wrong redirect link after password reset

### ISSUE THREAD

**Issue by jqdaily** [ExpressionEngine/ExpressionEngine#28]
**Description of Problem:**
After a member resets their password, the message page reads: 

> Password Successfully Changed.
> You have successfully changed your password. Please login using your new password.
> Click here if you are not redirected automatically

In Chrome, Firefox, and Opera for mac, and in Chrome for iOS:
The "Click here" link and the auto-redirect both successfully point to the page where the user originally clicked the "Forgot Password" link. In my case this is `{site_url}/index.php/site/login`

In Safari for mac, and Safari and iCab on iOS:
The "Click here" link and auto-redirect point to `{site_url}/index.php/member/reset_password`. This triggers the error page:

> The form you submitted contained the following errors
> The password reset token does not appear to be valid. Please check the link you followed.
> Return to Previous Page

Clicking "Return to Previous Page" goes back to the "Password Successfully Changed" page, where the "Click here" link still points to `{site_url}/index.php/member/reset_password`, which triggers the error page again, putting the user in a confusing feedback loop.

**Environment Details:**
EE Version: 5.0.1
PHP Version: 7.2
MySQL Version: 5.5
OS: macOS 10.13.6 and iOS 12.1
Web Server: Apache

**Comment by derekjones** [comment]
That link is based on your browsing history, so I'm guessing in the case of Safari you manually visited the reset password page, perhaps multiple times, between resetting?

In any case, clearing your browser cookies should fix that up for you, and should not be possible to trigger when following the reset workflow. If you find that's not the case, please re-open this issue and provide the steps necessary for someone to reproduce the behavior on their own install. Thank you!
