### ISSUE TITLE
Markdown email link in textarea renders as text

### ISSUE THREAD

**Issue by willowlight** [ExpressionEngine/ExpressionEngine#280]
**Description of the problem**

Markdown link with mailto: renders as markdown copy.

**How To Reproduce**

1. Create textarea field with markdown as the format
2. Enter standard markdown to create a email link in the field, example: ```[hello@willowlightstudio.com](mailto:hello@willowlightstudio.com)```
3. Add the field tag to a template

**Environment Details:**
 - Version: [e.g. 5.2.6]
 - PHP Version [e.g. 7.0.32]
 - MySQL Version [e.g. 5.0.12]
 - OS: Linux
 - Web Server: Apache

**Comment by intoeetive** [comment]
Unable to replicate this as of EE 5.4.1 and 6.0.3
