### ISSUE TITLE
Selected categories do not appear at the top of the list

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2807]
As you probably know, it was impossible to tell which categories of a long list are selected, until you scroll down the list all the way down. It was fixed in EE 7.2.0 and it worked. 

But not now: checked categories do not appear at the top of the list. 

I spotted the issue on my website and replicated it on a test EE 7.2.8 installation. Here is the video:

[video-convert-1675239567298.webm](https://user-images.githubusercontent.com/12234507/215992121-35708c03-7a18-45ba-8561-4cc04f0a970d.webm)

**Comment by Yulyaswan** [comment]
@TomJaeger I need your opinion about this one.
We have a possibility to reorder items on the Category page and moving all selected checkboxes to the top of the list for the `Entry page -> category tab` will break that ordering on the main page (What was marked by customers after changes made in 7.2.0)

**Comment by shbchk** [comment]
@Yulyaswan maybe we can do something like this?
![215799660-9c5f0bdd-345e-4845-a918-67663c5911f0](https://user-images.githubusercontent.com/12234507/221201351-a1fc98db-324b-4f7a-b331-b3ae130bd6ed.png)

It will not break the default order and will solve this UX issue.

**Comment by robinsowell** [comment]
@Yulyaswan Dang- this came out beautiful!!  Nice addition.
