### ISSUE TITLE
Certain SVG file is not allowed in image only upload directory

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2808]
EE 7.2.8

[This SVG image](https://drive.google.com/file/d/1uZ5wqCyMeQYARD3qudI6kEDxgVcmh0ke/view?usp=share_link) can not be uploaded as an image in EE:

![dfddbac7-8de9-4c91-93da-23abb05eb47c](https://user-images.githubusercontent.com/12234507/215994770-c97101a4-c1d0-48ea-af62-d592102e0692.png)

**Comment by intoeetive** [comment]
I wasn't able to replicate this.

If other SVG files work fine, I suggest that you open this file in code editor and check if it looks like valid XML

**Comment by shbchk** [comment]
It sure does look like valid XML:

![image](https://user-images.githubusercontent.com/12234507/216007854-670c4763-55b3-4b58-adf2-420cd61aee36.png)

And I just replicated it, using a clean copy of EE 7.2.8.

Here are the steps:

1. Create an upload directory:
![78a5588b-507b-4d66-9185-3e9929f6a598](https://user-images.githubusercontent.com/12234507/216008733-239d686d-bef0-4444-a126-d10672e90657.png)

2. Download this SVG file from Wikipedia: https://upload.wikimedia.org/wikipedia/commons/e/ef/Tribeca_Festival_logo.svg

3. Try to upload it.
![abc16179-4936-4d90-a27e-0aee08af8592](https://user-images.githubusercontent.com/12234507/216009127-eec12d7b-2725-401c-a6fe-40ee907612cb.png)

**Comment by shbchk** [comment]
PHP Version 7.4.21, btw

**Comment by shbchk** [comment]
Okay, you are right, it's not exactly valid - there is a declaration missing:
`<?xml version="1.0" encoding="utf-8"?>`

After I added it, EE accepted the file.

I guess, it is the correct behavior. Correct, but do you think it's good? It could be confusing for an editor, to be able to download an image from one website, where it is rendering totally fine, but not to be able to upload it to another.

**Comment by intoeetive** [comment]
The file still should be accepted, despite missing `<?xml` part

There must be something specific in how your server handles MIME types.

Can you do some checks for me? 
Try editing `system\ee\ExpressionEngine\Library\Mime\MimeType.php` file and on line `219` right after `$mime = $this->ofFile($path);` add this code
```
dd($mime);
```
Upload the file and inspect browser console for network requests (because the upload is AJAX). 
I'm interested to know what MIME type it returns for you

**Comment by shbchk** [comment]
I have three EE installs: localhost, Digital Ocean droplet, and a simple virtual hosting for a small website. And everywhere this file wasn't accepted, so this is not because of my setup, I guess :)

With `dd($mime);` it throws an error in a console.

I made a video!
[video-convert-1675248898946.webm](https://user-images.githubusercontent.com/12234507/216024192-98f9de0d-0e1a-48c0-912b-e15a23358f63.webm)

**Comment by intoeetive** [comment]
The error is expected in this case; I'd like to see what is returns in Response tab for this request

**Comment by shbchk** [comment]
Sorry, I'm not a true dev. Yet :)

Here it is:

```
<pre>string(9) "image/svg"
</pre>

```
BTW, sometimes, when I click on a file to upload it gets uploaded twice, like in the screenshot below. Not sure though why it is happening and how to replicate it.

![image](https://user-images.githubusercontent.com/12234507/216027604-6f26e945-2f85-4e23-bc85-d488170c5df1.png)

**Comment by intoeetive** [comment]
Interesting. This should just work.

Do you by chance have `mimes.php` file in `system/user/config` folder? If yes, what is the contents of it?

Also, you don't have any manipulations (resize / crop) assigned to this upload directory, right?

**Comment by shbchk** [comment]
No, no mimes.php on both local copies of EE - test install and the dev environment of my website.

I got manipulations on dev environment, but no manipulations on the test installation — it is fresh and clean, just installed for testing purposes.

**Comment by intoeetive** [comment]
Ok. If you change line 224 (`if ($mime == 'image/svg+xml') {`) to `if (strpos($mime, 'image/svg') === 0) {` - does that make things work?

**Comment by shbchk** [comment]
Yes, now EE is accepting this file!

**Comment by intoeetive** [comment]
Great! Thanks for helping me debug this

**Comment by shbchk** [comment]
Always a pleasure, Yuri! Glad to help you and EE :)
