### ISSUE TITLE
Date field can't be seen in preview when there is a condition

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#2822]
EE 7.2.8 

If you put this code in a template, it won't work in a preview mode:

```
{if date_field >= current_time}
<h3>Date:</h3>
<p>{date_field}</p>
{/if}
```

**Comment by intoeetive** [comment]
It looks like when using Live Preview date field is getting formatted early, instead of using raw value, thus causing incorrect parsing (`{date_field}` outputs  `2023-03-10 12:50:25` in Live Preview instead of `1678470625` as it shows up on frontend). This should not happen
