### ISSUE TITLE
EE timezone tag does not change unix timestamp but only formatted timestamp

### ISSUE THREAD

**Issue by thomasdefilippis** [ExpressionEngine/ExpressionEngine#2824]
**Description of the problem**
This is pretty simple. When using `{entry_date format='%U' timezone="America/Los_Angeles"}`, this is equal to  `{entry_date format='%U'}`. However, when using `{entry_date format="%D, %F %d, %Y - %g:%i:%s" timezone="America/Los_Angeles"}`, it changes the time appropriately. Is it possible to allow timestamps to also change when in unix format because it would be convenient to be able to dynamically change the timestamp by timezone and compare it in a conditional without having to use php? The docs seem to indicate that the timezone will alter even timestamps https://docs.expressionengine.com/v6/templates/date-variable-formatting.html#setting-the-timezone.

**How To Reproduce**
1.Use a channel entry tag (any channel entry_tag).
2. display entry_date as shown above.

**Environment Details:**
 - Version: 6.4.4
 - PHP Version 8.2
 - MySQL Version 8.0
 - OS: Linux
 - Web Server: nginx

**Comment by jcogs-design** [comment]
Sorry to be bearer of bad news, but [the underlying unixtime number is not affected by region](https://stackoverflow.com/questions/23062515/do-unix-timestamps-change-across-timezones#23062640) so your request does not have any meaning in real world.

If what you want to do is compare local times after adjusting for time zone you are going to have to do that by decomposing the formatted output - but you could make this easier by building a structured form that is easy to compare I guess.

**Comment by thomasdefilippis** [comment]
I see. Yeah, don't know why I didn't think of the fact that unix shouldn't change. That's a duh statement.

What do you mean by "but you could make this easier by building a structured form that is easy to compare I guess"
We are handling it by offsetting our timestamp in an addon method call and then comparing. This may be too specific of a case to require a change to the code. 

Thanks for your quick response.

**Comment by jcogs-design** [comment]
All depends what granularity of date you are comparing - but you could have (for example) two different tags and simplify the comparisons: apart from only (I think) two exception, timezones differ by whole hours - so you possibly could just compare the "date number" and "hours" values to work out the difference (you'd need the date number (e.g. 3 for 3rd day of month) to cover off changing from one day to the next (so 11pm in one zone, 8am the following day in another) - if your sample set includes half our timezones then you'd need three (day, hour, minute). HTH.
