### ISSUE TITLE
PHP error in dock / front end entries list

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#2841]
In a site that was just upgraded from EE2 to EE7, the front-end entries listing is throwing an ugly error:

```
Fatal error: Declaration of ExpressionEngine\Addons\Pro\Library\CP\EntryManager\Columns\Title::renderTableCell($data, $field_id, $entry) must be compatible with 
ExpressionEngine\Library\CP\EntryManager\Columns\Title::renderTableCell($data, $field_id, $entry, $viewtype = 'list', $pickerMode = false, $addQueryString = []) in 
[..]/system/ee/ExpressionEngine/Addons/Pro/Library/CP/EntryManager/Columns/Title.php on line 18
```

EE 7.2.9
PHP 8.0.8

<img width="969" alt="image" src="https://user-images.githubusercontent.com/308752/217950089-ce6a59e3-66e9-4caf-bce5-bf92a7a97cd9.png">

**Comment by murtaugh** [comment]
This was the first time I turned on the feature to explore it.

**Comment by studiopatagon** [comment]
Same happens to me, also on PHP 7.2 or 7.4
