### ISSUE TITLE
Channel Form errors in PHP 8.1

### ISSUE THREAD

**Issue by mcfarlandonline** [ExpressionEngine/ExpressionEngine#2842]
EE Version 6.4.5
PHP 8.1
* MSM * Site

I have a front-end channel form showing this list of errors now that I've bumped them into PHP 8.1: 

> Deprecated
> strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
> ee/ExpressionEngine/Addons/channel/libraries/channel_form/Channel_form_lib.php, line 767
> 
> Severity: E_DEPRECATED
> Deprecated
> strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
> ee/ExpressionEngine/Addons/channel/libraries/channel_form/Channel_form_lib.php, line 770
> 
> Severity: E_DEPRECATED
> Warning
> Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
> ee/ExpressionEngine/Boot/boot.common.php, line 477
> 
> Severity: E_WARNING

Any insight on what needs tweaking here?

**Comment by intoeetive** [comment]
@mcfarlandonline what are the field (fieldtypes) that you are including into this form?

**Comment by mcfarlandonline** [comment]
@intoeetive, 
- rich text editor
- text input
- select dropdown
- email address
- file
- radio buttons
- number input
- checkboxes

I'm also displaying logged-in members' avatars using the {exp:member:custom_profile_data}  tags.
