### ISSUE TITLE
User Gets Logged out. Edits lost!

### ISSUE THREAD

**Issue by rouviere** [ExpressionEngine/ExpressionEngine#286]
**Description of the problem**
Control panel session unexpectedly ends and content changes are not saved. The phenomenon is consistent. The timer interval is totally unpredictable.

**How To Reproduce**

1. Log into the control panel
2. Create new blog entry
3. Add text, photos, etc.
4. Save content
5. Continue editing content
6. Control panel suddenly closes and displays login screen

**Error Messages**
None.

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 5.2.6
 - PHP Version: 5.6.4
 - MySQL Version 5.5.3
 - OS: Linux
 - Web Server: Apache
 - Security and Privacy:  Cookies and session ID

**Possible Solution**
This is a show-stopper issue and costs hours of productive time every week. The system is always up-to-date. 

I expect that I can stay active in the Control Panel as long as I need to to create and edit content without getting booted out. Is there a preferred setting that I am overlooking that will keep the session active. Also, clicking the Save button regularly is problematic because it collapses the edit window and you have to expand it and find your spot.

I have also tried setting the frequency of auto-save using: 
$config['autosave_interval_seconds'] = '900';
to auto-save every 15 minutes, but this does not seem to work either. Today when it closed out the last version was more than 20 minutes old. 

I have been building EE sites since 2008. I hate WordPress and won't switch, but this one issue is enough to cause me to want an alternative to EE. 

Please help me find a solution to this problem.

**Additional context**

**Comment by derekjones** [comment]
This is not a reproducible bug; the control panel time-out is predictable at exactly one hour of inactivity. If this were a general bug with ExpressionEngine, it would be unusable for the many thousands of sites that it powers.

This sounds like an issue with the localization settings on either your server, PHP, ExpressionEngine, your ExpressionEngine member account, or with an incorrect date/time setting on your computer. For example, cookies will not work properly if your date/time of your local machine is incorrect. Or if you are in a load balanced environment and one server's date/time is wrong, that can also cause this to happen. Please check all of your date/time settings along the chain, or contact support if you need assistance identifying them.

**Comment by rouviere** [comment]
Derek, thank you for the quick response. I will dig deeper on the server setting side and see what may be happening there. It is nice to know that the panel time-out should be after exactly one hour of inactivity. This gives me a known standard to measure against.
