### ISSUE TITLE
Grid data not deleted with entry when under a fluid field

### ISSUE THREAD

**Issue by Chadnelson31** [ExpressionEngine/ExpressionEngine#287]
**Description of the problem**
If a grid field is part of a fluid field, it's data isn't removed from the database when the entry is deleted.

**How To Reproduce**
1. Create a fluid field that includes a grid field
2. Add fluid field to channel and create new entry
3. Select the grid field under the fluid field and add content
4. Delete the entry and check the channel_grid_field table
5. The grid data from the entry will still be there

**Environment Details:**
 - Version: 5.2.4, 5.2.2
 - PHP Version 7.3.4-2
 - MySQL Version 10.3.15
 - OS: Linux, Windows Server
 - Web Server: Apache, IIS

**Comment by pixiwooh** [comment]
Same problem here but except that the file grid doesn't need to be nested in a fluid fileds to be problematic, it can do that solo.

So when you delete a row of a file grid and save, your deleted row is back with it's content.

**Comment by ops-andy** [comment]
I've tested this sevearl different ways in version 6.0.3 and cannot replicate. I'm going to close this for now, assuming it was fixed somewhere between 5.3 and 6.0.3. Please review again on the latest version and feel free to reopen or ping us if the issue persists. thanks!
