### ISSUE TITLE
Page URI and page template are not deletable in EE 5.2.6

### ISSUE THREAD

**Issue by sonnenvogel** [ExpressionEngine/ExpressionEngine#292]
With a fresh install of ExpressionEngine 5.2.6 with the default theme installed i'm unable to delete the Page URI or the Page template selection once i have entered one and saved the entry. I can change the Page URI and also the Page template but you cannot delete it. If you try to delete it and save the entry the value is still in the Page URI input field after browser page refresh.

**Comment by robinsowell** [comment]
Agreed- I'm thinking a 'No selction' option in the dropdown and making certain you can clear the uri is the way to go.

**Comment by sonnenvogel** [comment]
This bug is not fixed in ExpressionEngine 5.3. When do you plan to fix it?

**Comment by sonnenvogel** [comment]
bump
