### ISSUE TITLE
RTE Front-End styles break when form ID specified

### ISSUE THREAD

**Issue by blairliikala** [ExpressionEngine/ExpressionEngine#295]
**Description of the problem**
When an ID is not specified in the channel:form parameters, then the form gets an ID of cform that has styling attributed to it for the RTE.  When an ID is specified, the form ID changes and breaks some styling for RTE.

**How To Reproduce**
{exp:channel:form
id="anything
channel="test"
....etc
}
Will break RTE styles.

**Environment Details:**
 - Version: 5.2.6
 - PHP Version 7.2

**Possible Solution**
Adjust styling to not be dependent on ID name, and use a selector that will always be included in the form.  Looks like it is mostly the toolbar styles.

**Comment by skookie000** [comment]
I also did this to resolve the issue.  Change the cform to a class might help, then a user could apply it to elements when needed.
```
  <article id="cform">
    <textarea name="custom_field"class="rte" cols="90" rows="6">{custom_field}{field_data}{/custom_field}</textarea>
  </article>
```
