### ISSUE TITLE
ExpressionEngine Server Compatibility Wizard apparently misreporting on Nexcess server

### ISSUE THREAD

**Issue by strudelmedia** [ExpressionEngine/ExpressionEngine#297]
I ran the latest server wizard on a Nexcess shared server where I have a few EE websites running and got the following error message:

> Oops, there was an error 
> To complete the wizard check, the following error(s) must be addressed:
> Your MySQL client version (5.1.73) does not meet the minimum requirements to support Emojis (5.5.3).

Nexcess support looked into it and said this:
<pre><code>The Database servers version is MariaDB 10.2 which does support the desired functionality.   

The issue is that Expression Engine is detecting the incorrect version.    I know of a Wordpress Plugin with similar functionality that has the exact same problem.   The developer does a good job explaining the issue in this thread.  https://wordpress.org/support/topic/error-in-warning-about-mysql/

I understand you are not using Wordpress,  but the explanation still applies.   

The PHP function mysqli_get_server_info() is responsible for retrieving the database server version.   

=================
[0511][root@eep1-15 /home/USER/DOMAIN.com/html]$ grep -r mysqli_get_server_info ./
./system/codeigniter/system/database/drivers/mysqli/mysqli_driver.php:			$this->use_set_names = (version_compare(mysqli_get_server_info($this->conn_id), '5.0.7', '>=')) ? FALSE : TRUE;
=================

The version details when MariaDB is in use look like:
=================
$ php dbserver_version.php
MySQL server version: 5.5.5-10.2.26-MariaDB
=================

The status check sees the '5.5.5'  and thinks it represents and outdated version of MySQL.   So you are seeing the 'no' instead of 'yes'.  

There really isn't anything we can do for that from our end.  The code in the status check would need to be updated by a developer to account for the way the version is reported when MariaDB is in use.</code></pre>

Here's a screenshot of the result the server wizard gave me:
![Screen Shot on 2019-08-29 at 08-06-09(1)](https://user-images.githubusercontent.com/9244121/63961868-ba6e3780-ca5f-11e9-9e4c-27893963a9cb.png)

**Comment by robinsowell** [comment]
Thanks for the detailed report!

**Comment by intoeetive** [comment]
Obviously late to the party here, but I noticed that the response from support is speaking about MySQL server version; while the error is related to MySQL client version. Those are separate things and are checked separately by server wizard.

Closing now; if anyone still thinks this is a bug, please reopen
