### ISSUE TITLE
Thumbnails should reflect their actual aspect ratio (i.e. portrait or landscape)

### ISSUE THREAD

**Issue by ballmannweber** [ExpressionEngine/ExpressionEngine#300]
At the moment (5.2.6), all images in the file dialog are provided with an icon that always has the same aspect ratio – regardless of the actual aspect ratio of the image, i.e. portrait or landscape format. 

<img width="946" alt="Bildschirmfoto 2019-09-03 um 21 19 06" src="https://user-images.githubusercontent.com/5177628/64202078-872d0d80-ce90-11e9-8dbc-9d474d706824.png">

If you manage many images and some of them are available in portrait as well as landscape format, this will cause many unnecessary steps when placing the images. 

It would be easier if the icons would show the actual aspect ratio.

**Comment by intoeetive** [comment]
The thumbnails are respecting the original ratio in ExpressionEngine 7.
