### ISSUE TITLE
MFA is turned off globally, but users are still able to enable it

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#3018]
EE 7.2.9

Steps to reproduce:

1) Disable MFA globally in /cp/settings/members

2) Go to your profile settings (/cp/members/profile/pro/mfa) and enable MFA for yourself, despite the global setting

**Comment by intoeetive** [comment]
@shbchk was the MFA previously enabled for member? I am getting "unauthorized" error when trying to access that page with MFA globally turned off

**Comment by shbchk** [comment]
No, definitely wasn't. But I'll check later, maybe there is something else. I just tried it with a fresh installation and couldn't reproduce it. Weird :) 

But I reproduced one more MFA bug, going to post it as a separate issue.

**Comment by shbchk** [comment]
Well, maybe it was enabled previously and I forgot about it. Closing this issue for now, I can't reproduce it with another member account
