### ISSUE TITLE
After user turn off MFA in profile, EE asks him for set it up again

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#3019]
EE 7.2.9

How to reproduce:

1) Enable MFA for your account
2) Disable it
3) Go to the index page

Video:

[mfa issue.webm](https://user-images.githubusercontent.com/12234507/219315530-723df9bd-ae09-4384-b705-f50f249f13f4.webm)

**Comment by intoeetive** [comment]
@shbchk at the end of your video, is the "set up MFA" screen is gone after you reload the page?

**Comment by shbchk** [comment]
@intoeetive that is correct

A little different behavior when the next screen is a CP page:

[mfa-bug-2.webm](https://user-images.githubusercontent.com/12234507/219322234-bf9f0963-8c20-41ab-8da3-09fe7f098b8f.webm)
