### ISSUE TITLE
What about a CP Home Manager?

### ISSUE THREAD

**Issue by ballmannweber** [ExpressionEngine/ExpressionEngine#302]
CP Home is a central but dead place. It's like walking past a vacant house every day, but neither is the house being renovated, nor is anything new being built there. For years.

CP Home would be the ideal place, similar to the Menu Manager, to give users a configurable or at least individually configured starting point for their work, for example to...

- to write a new news article directly.
- change the status of a museum ("open today").
- show all closed articles.
- to show all articles for which no translation is available (Hello Publisher).
- Load 20 new images into the File Manager at once.
- etc.

For many of our projects, clients wouldn't have to visit any other place of the backend in their everyday life if they could do many things directly in CP Home.

That would be a bit like the Wordpress dashboard.

Probably it would need an interface so that addons can address this manager directly.

**Comment by ic360-com** [comment]
This sounds like a good idea to me.   :-D

**Comment by WITwebmaster** [comment]
Agreed  would be great if you could customize the control panel widgets for users .Most ordinary users don’t care and dont need to know how many channels, field groups or members a site has but they are the first two widgets they see.

Useful widgets for ordinary users could include a widget for for favorite entries they edit regularly, recent comments , recently updated entries ( both of which were in the EE2 default widgets ) , custom text widget for instructions or links to help docs etc. There was a plugin (dash-ee ) that provided this functionality for EE2 and it would be great to see it as a core feature.

**Comment by intoeetive** [comment]
We will be implementing this as part of EE Pro.
