### ISSUE TITLE
Emoji running even when turned off on EE 6.4.4

### ISSUE THREAD

**Issue by muzesmtc** [ExpressionEngine/ExpressionEngine#3025]
**Description of the problem**

Add 4:2:2 on text input/textarea field and on front-end it will be converted to an emoji even when emoji is disabled.

**Environment Details:**
 - Version: 6.4.4
 - PHP Version : 8.1 and 7.2
 - MySQL Version 5.7
 - OS:  Linux, Windows
 - Web Server: Apache

![image](https://user-images.githubusercontent.com/48106972/219719913-d663b496-d530-4fe3-a120-3e5762553ff4.png)

**Comment by intoeetive** [comment]
@muzesmtc the setting you are referencing to here is about converting emoticons to emoji; not to emoji sequences themselves.

What you are looking for is `disable_emoji_shorthand` system config override. https://docs.expressionengine.com/latest/general/system-configuration-overrides.html#disable_emoji_shorthand
