### ISSUE TITLE
1-click fails with bad themes path on MSM secondary site

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3026]
1-click from 2.7.9 to 2.7.10 dp.

I have a site with MSM setup.  I'm only using 1 themes folder, all the MSM sites share it.

<img width="559" alt="Screenshot 2023-02-17 at 1 02 13 PM" src="https://user-images.githubusercontent.com/1181219/219743643-7cc474f4-a49f-4bdd-9508-b6ea74f365bd.png">

My relevant path settings on site 'Dos'.  

When I 1-click from that site, I get a pre-flight error:

<img width="941" alt="Screenshot 2023-02-17 at 1 01 48 PM" src="https://user-images.githubusercontent.com/1181219/219743944-f1d54141-260d-4a2a-ace3-1790d75eda0b.png">

But... my path to themes is correct.  

If I run the 1-click from my main site, it works.

Is weird- it's sticking that extra dos segment into my secondary site's theme path when it checks.

**Comment by intoeetive** [comment]
This is probably relevant to (if not the same as) https://github.com/ExpressionEngine/ExpressionEngine/issues/2753

**Comment by robinsowell** [comment]
Agreed- looks identical.  Swear I searched for it!

**Comment by robinsowell** [comment]
I'm closing, so we just have the one.
