### ISSUE TITLE
[EE v7.2.9] Publish Page File Manager Modal File Menu Using "safe" HTML

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#3027]
We use right angle brackets (greater-than signs) in our client's directory names. While they are displayed as expected in the File Manager, they are displayed at "safe" html in the Publish page's File Manager modal window's menus.

<img width="294" alt="Screenshot 2023-02-17 at 2 35 33 PM" src="https://user-images.githubusercontent.com/6145078/219810386-dbb0912c-d516-45c1-b554-6515b4daff82.png">

<img width="326" alt="Screenshot 2023-02-17 at 2 36 13 PM" src="https://user-images.githubusercontent.com/6145078/219810387-cabf72d3-117d-48ad-8a6c-57f05c78eca3.png">

**Environment Details:**
 - Version: [7.2.9]
 - PHP Version [8.1]
 - MySQL Version [5.7.x]
 - OS: [macOS: with Chrome]
 - Web Server: [Apache]

Let me know if you have any challenges recreating this.

**Comment by intoeetive** [comment]
@Yulyaswan this seems to be done by React component for dropdown. Do you think this is something we can avoid doing?

**Comment by Yulyaswan** [comment]
@intoeetive reassigned the issue to you because this  HTML character returns as result of ajax request from the server. We don't use React for this element
