### ISSUE TITLE
Markdown 2.0.0 wont works?

### ISSUE THREAD

**Issue by amolinaclp** [ExpressionEngine/ExpressionEngine#303]
hi, im use Markdown 2.0.0 Addon on my template like that, but only return same text with < p r e > tags
<pre>
{exp:markdown}
                                 				
 
- George Washington
- John Adams
- Thomas Jefferson
 

    Text to be **parsed**.

    - algo
    + otro
    * asterisco
    
    1. algo
    2. algo
    
    *   Red
    *   Green
    *   Blue
	
	
	1.  Bird
	2.  McHale
	3.  Parish
{/exp:markdown}
</pre>

**Comment by derekjones** [comment]
Is the add-on installed?

**Comment by amolinaclp** [comment]
hi @derekjones , yes Add-on its installed, im use in _html-wrapper.html file from blog demo(Expression Engine 5.2.6)
/web/system/user/templates/default_site/layouts.group/_html-wrapper.html

**Comment by amolinaclp** [comment]
return the same text with < p r e > tags

**Comment by derekjones** [comment]
Ah, that would be Markdown processing. In Markdown, one way of defining code blocks is by tabbing the content in.

    Much like here on GitHub

**Comment by amolinaclp** [comment]
OK, thans for your time and help.
