### ISSUE TITLE
Recent change to class properties causing issues

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#3030]
**Description of the problem**

In Publisher I have to reference the mod.channel.php->$query_string property. It was recently set to a protected property on the class, which I understand b/c you might not want someone modifying it, but not being able to reference it is a little painful.

Would it be possible to add at least a getter method to any of the newly added protected class properties so add-on devs could at least reference the value?

My use case:
```
// If a category is defined in the url or in the entries param then we have a bit more to do.
        // We can't use the specific entry ids available b/c the results could be wrong based on the category
        // assignments, e.g. drafts and different cats assigned to.
        // Handles site.com/category/foo or site.com/foo/C# urls
        if ($channel->cat_request && ee()->TMPL->fetch_param('dynamic') !== 'no') {
            if ($channel->query_string) {
                ee()->load->helper('segment');
                $this->entryResult->getEntryQuery()->setCategoryFilter(parse_category($channel->query_string));
            }
```

Thanks

**Comment by intoeetive** [comment]
@litzinger - sorry, that wasn't really intentional
Most of the properties on Channel module are public, so it wouldn't hurt if we make this one public as well

**Comment by litzinger** [comment]
No worries, thanks for making the change :)
