### ISSUE TITLE
Grid field publish view broken

### ISSUE THREAD

**Issue by UmbrellaProject** [ExpressionEngine/ExpressionEngine#3034]
after updating to 6.4.5, grid fields column are no longer displayed in a table form, but rather each column take 100 percent width.

**Comment by Yulyaswan** [comment]
Hi, @UmbrellaProject. Thanks for mentioning this.
Could you please check which layout your grid is using?
if the `auto` option is selected and there is not enough space for content on the page, then the grid is rebuilt in a vertical view.
the` Horizontal layout` will always display the grid as a table.
![Screenshot 2023-02-24 at 10 58 36](https://user-images.githubusercontent.com/23382425/221149757-378d05b0-935d-4fed-be20-52d28cc20581.png)

Thanks

**Comment by UmbrellaProject** [comment]
Hi @Yulyaswan , 

thank you, Was not aware of this feature.
