### ISSUE TITLE
Enabling Front End Editing (EE6) kills some relationship field rendering

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#3035]
**Description of the problem**
Enabling 'Front End Editing' as an option in the EEPro add-on (licensed) in EE6 causes some relationship fields to fail to render.

See the before / after images attached.
![Screenshot 2023-02-22 at 14 19 38](https://user-images.githubusercontent.com/13821249/220648938-bee391e3-fb5f-4feb-b8b6-44876d19c073.png)
![Screenshot 2023-02-22 at 14 20 11](https://user-images.githubusercontent.com/13821249/220648913-123cf9fa-9117-4e93-b088-cadaa8badfee.png)

**How To Reproduce**
Enable Front-End editing in EEPro add-on and reload page.

**Environment Details:**
 - Version: 6.4.5
 - PHP Version 8.0.27
 - MySQL Version MySQL 8.0.32 
 - OS: ?
 - Web Server: Litespeed (Apache)

**Comment by intoeetive** [comment]
@jcogs-design Can you send over the template code? And what fieldtypes are involved here (specifically interested in Grid, Fluid and Relationships)

**Comment by jcogs-design** [comment]
Might be easiest for you to poke around on the site directly - DM me if you want some access credentials. But roughly...

> The parent page contains a relationship field (content_block_linker) that links to (among other things) an entry in a channel that contains two grid fields (content_block_ctas and comparison_table_footer_text).

HTH.

**Comment by jcogs-design** [comment]
Just to add to this, have just noticed that in addition, a Wygwam and Text Input field (both with Front End Editing enabled) from an entry in channel do not show edit tags when Front End Editing is enabled. The text input field is the orange heading in the image, the Wygwam field the text block below. The entry containing the fields is in a channel entries of which are collated in a relationship field in an entry from another channel, and that entry is included in the same 'content_block_linker' relationship field mentioned above. The edit tag showing in the image is for the parent Relationship field (i.e. "content block linker").
![Screenshot 2023-02-22 at 18 50 58](https://user-images.githubusercontent.com/13821249/220729599-9f4b6871-b387-4e80-b4d5-c218e9a1df00.png)

**Comment by intoeetive** [comment]
@jcogs-design can you try applying the change in this PR and see if that helps? (this is for v7 but the corresponding code is the same)

https://github.com/ExpressionEngine/ExpressionEngine/pull/3037/files#diff-a7429b2609d058d5df52b25e0197e0406aebb5850bd102e2fd9712512259aaf8R222-R233

**Comment by jcogs-design** [comment]
Sure - will try and get to it later today and report back

**Comment by intoeetive** [comment]
sorry - please hold off testing, I found an issue with that supposed-to-be-fix. I'll keep you updated

**Comment by jcogs-design** [comment]
OK - np

**Comment by intoeetive** [comment]
@jcogs-design this should help - can you test and see? https://github.com/ExpressionEngine/ExpressionEngine/pull/3037/files#diff-a7429b2609d058d5df52b25e0197e0406aebb5850bd102e2fd9712512259aaf8R227-R235

**Comment by jcogs-design** [comment]
Sadly not... :( 
Replaced the code for FrontEdit.php with your modified version on the test server and got these results 
Without front edit enabled on two bottom grid fields
![image](https://user-images.githubusercontent.com/13821249/221571488-1d86f177-bc1d-440c-acc0-c32d76b11e33.png)
With front edit enabled on two bottom grid fields
![image](https://user-images.githubusercontent.com/13821249/221571542-00271ada-5659-412b-937f-879ecd90420a.png)
