### ISSUE TITLE
Select Dropdown field - can't reorder

### ISSUE THREAD

**Issue by kemmerly** [ExpressionEngine/ExpressionEngine#3042]
When setting up a Select Dropdown field I am unable to re-order rows by drag & drop. When I hover over the 3 horizontal bars on the left the cursor changes to the 4-way directional cursor but I can't drag and drop an item to a different position.

This is using 7.2.7 Pro. I tested it in an EE 6.0.6 site and it was working as expected.

**Comment by Yulyaswan** [comment]
Hi, @kemmerly. 
You are right, the problem did exist in version 7.2.7, but already in 7.2.8 it was fixed
Please update your version to the latest one (7.2.10)
Thanks
