### ISSUE TITLE
[EE v7.2.10] Entry Manager Table Column Select Menu missing "Comments" option

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#3047]
EE v6.x.x includes the Comments column menu option so that it may be deselected and removed as a column in the Entry Manager Table at /cp/publish/edit

That menu option is missing in EE v7.2.10 but the column for Comments still shows up. The menu opens over that column, so you can't see it in the screenshot, but it is under there.
 
<img width="279" alt="Screenshot 2023-02-27 at 4 37 38 PM" src="https://user-images.githubusercontent.com/6145078/221721927-1b245b0d-2c88-4acf-806e-04df432fc0bf.png">

If I add a new column to the table, the Comments column will go away, but it's not listed in the menu, so there's no way to add it back later if I change my mind.

It could be that EE is not listing Comments it in the menu because we have Comments off for all channels, but if that's the case, then the Comments column shouldn't have been displaying in the table either.

If this isn't a bug, it's very confusing behavior.

**Comment by intoeetive** [comment]
@PDXMan1 in EE 7.2.4 we added a check that if Comment module is globally turned off (in Content & Design system settings) then it does not display as a column

The list of columns is being cached, so there's a chance it showed up initially until you performed some actions with the Entry Manager setup - however I wasn't able to replicate that

**Comment by PDXMan1** [comment]
Hm... perhaps the table columns are being cached also, and both should get cleared when an update is run? We had to add a column we didn't need to get the Comments column removed, and then remove the one we just added, but didn't need.

**Comment by aasun** [comment]
I'm still seeing inconsistencies on this.  EE 7.2.11 (fresh install starting with EE 7.2.9).  Comment module is disabled.  Some entry listing are showing the comment column and some are not.  I've cleared all EE caches, and no change.  Can't seem to control it.

**Comment by PDXMan1** [comment]
Looks like this was later documented by Robin in #3135 and if resolved, then that would confirm and resolve this #3047  also.
