### ISSUE TITLE
Long titles causes visual bug in entry listings

### ISSUE THREAD

**Issue by willowlight** [ExpressionEngine/ExpressionEngine#305]
Create an article with the following title: Hope High School Field Dumped with Dozens of Barrels of Waste Marked “Cancer Causing” By City Vendor

This will cause the preview and edit icons to wrap vertically. 

I am able to fix the issue by explicitly declaring the max-width and white-space properties for the table cell:

`.tbl-wrap > table > tbody > tr > td:nth-child(2) {
max-width:550px;
white-space:normal;
}`

**Comment by Jordan-Ellis** [comment]
Fixed in EE6!
