### ISSUE TITLE
{encode} script doesn't need type="text/javascript" attribute

### ISSUE THREAD

**Issue by mcfarlandonline** [ExpressionEngine/ExpressionEngine#306]
This is a bit perfectionistic, but it bugs me that I can't get a perfect validation score at [The W3C Markup Validation Service](https://validator.w3.org/nu/) when using {encode} for emails. 

Does anyone know a way to hack out the type="text/javascript" attribute in EE's script? 

**Error:**
<img width="791" alt="Screen Shot 2019-09-05 at 11 47 11 AM" src="https://user-images.githubusercontent.com/20441129/64370761-f52e1d80-cfd3-11e9-90b3-0f14c934ee71.png">

**Source code:**
<img width="1198" alt="Screen Shot 2019-09-05 at 11 46 52 AM" src="https://user-images.githubusercontent.com/20441129/64370620-a97b7400-cfd3-11e9-86e6-da8b6f4fdeda.png">

**Comment by derekjones** [comment]
Nothing wrong with perfectionism! It's [right here](https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/system/ee/legacy/libraries/Typography.php#L2391). Would you like to [submit a patch](https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/CONTRIBUTING.md#contributing-code) with that removed?

**Comment by mcfarlandonline** [comment]
Oh perfect! Yes, thank you!

**Comment by robinsowell** [comment]
Closing as patch merged and released: https://github.com/ExpressionEngine/ExpressionEngine/pull/307
