### ISSUE TITLE
EE 6.4.5 Control Panel: Templates > (System Templates) Email > User – Forgotten password instructions. Inconsistent rendering of HTML emails

### ISSUE THREAD

**Issue by creativearc-paul** [ExpressionEngine/ExpressionEngine#3075]
**Description of the problem**

a) I noticed while logging into the EE backend, and then trying a "Password: Remind me" (/cp/login/forgotten_password_form), I get the email delivered as raw HTML.

b) But when I issue a forgot password request on the website _frontend_, I get a properly formatted email

**How To Reproduce**

1. Observe email template content in: Templates > (System Templates) Email > User – Forgotten password instructions. If there's no HTML there, add some (particularly adventurous HTML with css classes)
2. Trigger a forgot password request from the EE control panel login page
3. Note the display (or lack thereof) of HTML
4. Now, visit a frontend forgot password form that uses ex:member:forgot_password_form
5. Note the display of HTML
 
</code></pre>

**Screenshots / Videos / Template Code**

a) Email when triggered from EE login page:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/224037/222795006-e093c659-c270-45fa-94a7-cdba8c3c74bb.png">

b) Email when triggered from Frontend, using {exp:member:forgot_password_form...

<img width="883" alt="image" src="https://user-images.githubusercontent.com/224037/222795373-6c20909e-5c7e-48a6-9e90-3f8053548183.png">

**Environment Details:**
 - EE 6.4.5

**Comment by alexhobday** [comment]
I am experiencing the same issue. Specifically the user notification template for email address changed. Some templates parse HTML, this one doesn't.
