### ISSUE TITLE
Embeds and Template Partials not working on entry level.

### ISSUE THREAD

**Issue by PontusMadsen** [ExpressionEngine/ExpressionEngine#3078]
Hi!

I have a template that has a conditional in it.

`{layout="embeds/_layout"} {if segment_2 == ''}  Main info {header} {if:else} this is an entry {title} {/if} {embed="embeds/_kandidatnatverk"}`

In _layout there's an embed for {embed="embeds/_footer"}.
If I just call the template with no segment 2, its hows properly and shows {embed="embeds/_kandidatnatverk"} + the {embed="embeds/_footer"} too from _layout.

But if I add segment 2, it shows all the info from _layout + the info from the entry that is segment 2 .. but not the {embed="embeds/_kandidatnatverk"}-include nor the {embed="embeds/_footer"}-include from _layout.

So, it seems to be a include issue.

Template group Structure is:
[site]
[lediga-jobb]
[embeds]

The template I'm calling is from [lediga-jobb]

Expressionengine 7.2.10

--- Update:
If I create a subpage that holds the loop for the entry and no conditionals
alas: /lediga-jobb/jobb/
Then the embeds still doesn't work.. but the layout does >_<
So, same error.

Tried it on multiple pages now, and as soon as it's on a single entry level, includes does not work anymore.

--- Update
Also.. in _layout, there's an {embed="embeds/_navigation"}-include that works.. soooo.. not all embeds are broken?

--- Update
Same goes for Template Partials

**Comment by intoeetive** [comment]
@PontusMadsen I wasn't able to replicate this using _just_ the code that you provided.

I suspect that some other template tag is interfering here and causing the embed to be removed from parsing.

Would you be able to provide the minimal template code that we can use to replicate the problem?

**Comment by PontusMadsen** [comment]
Even the most trivial code doesn't work.. like, this should work, but is not if t's viewed as a entry (http://www.mydomain.com/case/test/case-1), where "case-1" is the entry, being show in the "test"-template, located in the "case" template group.

**Content of "test".**
Shows the "title", but not the embed.
```
{exp:channel:entries channel="cases" limit="1"} 
{title}
{/exp:channel:entries}
{embed="embeds/_kontakta-oss"}
```

**Content of "_kontakta-oss" located in the "embeds" template group.**
```
{exp:channel:entries channel="puffar" limit="1"} 
<section class="wide">
	<div class="kontakta-oss">
		<div class="content">
		<h2>{kontakta_oss_header}</h2>
		<p>{kontakta_oss_ingress}</p>
		{kontakta_oss_knapp}
		<a href="{kontakta_oss_knapp:knappurl}" class="button">{kontakta_oss_knapp:knapptext}</a>
		{/kontakta_oss_knapp}
		</div>
	</div>
</section>
{/exp:channel:entries}
```

Even if I have no loops in  the embeded template, the embeded fails to show if it's in an "entry"-loop template.

I can give you access to the server if you'd like.

**Comment by intoeetive** [comment]
@PontusMadsen so in this example you're not using any layouts, or conditionals like in your previous examples. And specifically for this one, the `exp:channel:entries` in `_kontakta-oss` would return no results, because there is no entry matching the segment 2 (as that belongs to different channel). You might need to specify `dynamic="no"` parameter.

So can you confirm that it's `embed` that's not being included/parsed, not that `channel:entries` gives no results (which is expected here in your template)?

**Comment by PontusMadsen** [comment]
That fixed it!
.. I feel like a tool now. It was indeed the dynamic="no".
Please remove this whole thread's existence, since it's so embarrassing . 10 years doing EE-sites, and this happens. Apologies for taking your time -_-;
