### ISSUE TITLE
Get deprecated notices when PHP Redis 5.X extension is used

### ISSUE THREAD

**Issue by bsabalaskey** [ExpressionEngine/ExpressionEngine#309]
If you have PHP Redis extension 5.X installed (I am on Ubuntu 18.04 LTS), then you get deprecation notices whenever Redis is used for the internal cache and you update things like global variables (Low Variables) in the backend. This does not occur with older 4.X versions.

See explanation here about Redis delete() method:
https://github.com/phpredis/phpredis#del-delete-unlink
*Note: delete is an alias for del and will be removed in future versions of phpredis.*

**How To Reproduce**
1. Setup Redis as your cache in the EE backened
2. Update anything that clears said cache, like templates or Low Variables

**Error Messages**
<pre><code>
Function Redis::delete() is deprecated
ee/legacy/libraries/Cache/drivers/Cache_redis.php, line 73
</code></pre>

**Screenshots / Videos / Template Code**
none.

**Environment Details:**
 - Version: 5.2.6
 - PHP Version 7.2.22
 - MySQL Version 5.7.27
 - OS: Linux Ubuntu 18.04 LTS
 - Web Server: Apache 2.4.41

**Possible Solution**
Easy fix, change 3 characters in system/ee/legacy/libraries/Cache/drivers/Cache_redis.php on lines 73 and 79 from "delete" to "del".
<code>
return ($this->_redis->del(
				$this->_redis->keys($this->unique_key($key, $scope).'*')
			) === 1);
</code>

return ($this->_redis->del($this->unique_key($key, $scope)) === 1);

**Additional context**
None.

**Comment by derekjones** [comment]
Would you like to make a pull request with that change? :)

**Comment by jackbrighton** [comment]
Did anything happen to resolve this? I'm running into similar "Deprecated" errors in EE 4.3.8 after upgrading to PHP 7.4.4 and MySQL 7.4.4.

**Comment by Sungodragon** [comment]
@jackbrighton I think here is the solution which i not merged yet 
https://github.com/ExpressionEngine/ExpressionEngine/pull/336
@dougblackjr

**Comment by jackbrighton** [comment]
@dougblackjr Thanks for the reply. Would rolling back to PHP 7.0 likely resolve this until this merge?

**Comment by Sungodragon** [comment]
> 
> 
> @dougblackjr Thanks for the reply. Would rolling back to PHP 7.0 likely resolve this until this merge?
@litzinger Can perhaps better answer this best.

**Comment by robinsowell** [comment]
Closing as fix has been merged: https://github.com/ExpressionEngine/ExpressionEngine/pull/336
