### ISSUE TITLE
File grid can be saved with empty rows

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#3098]
EE 7.2.11

How to replicate:

1. Create a simple file grid field. 
2. Choose an existing image or upload a new one. Remove it by pressing the `x` button. 
3. Add another empty row by repeating step 2.
4. Save an entry.

[empty-grids.webm](https://user-images.githubusercontent.com/12234507/224316778-2248dacc-236a-4fd6-90ce-93356407734e.webm)

**Comment by intoeetive** [comment]
I believe this is same as the issue you've reported already: https://github.com/ExpressionEngine/ExpressionEngine/issues/690

**Comment by shbchk** [comment]
Oh, I totally forgot already :)
