### ISSUE TITLE
Model service With() unexpected behaviour

### ISSUE THREAD

**Issue by reinos** [ExpressionEngine/ExpressionEngine#31]
Hi There,

Im trying to extend a `ChannelEntry` Model Query with a custom model. But im facing an error
```
Undefined index: webservice:TestWith
ee/EllisLab/ExpressionEngine/Service/Model/Query/Select.php, line 846
```

The following can be followed to reproduce this error.

1. Create a Model, with the following fields: `id` `entry_id` `title`
2. Add a relation in the model to the `ChannelEntry`
```
namespace Reinos\Webservice\Model;

use EllisLab\ExpressionEngine\Service\Model\Model;

class TestWith extends Model {

    protected static $_primary_key = 'id';
    protected static $_table_name = 'test_with';

    protected static $_relationships = array(
        'Entries' => array(
            'type'     => 'belongsTo',
            'model'    => 'ee:ChannelEntry',
            'from_key' => 'entry_id',
            'to_key'   => 'entry_id',
            'weak'     => TRUE,
            'inverse' => array(
                'name' => 'TestWith',
                'type' => 'hasMany'
            )
        ),
    );

    protected $id;
    protected $entry_id;
    protected $title;
}
```

4. Add the dependency in the addon.setup.php

```
'models.dependencies' => array(
        'TestWith'   => array(
            'ee:ChannelEntry'
        ),
    ),
```

4. Create a basic model call with the custom model included 
```
//search on a custom field within the Entries
$query = ee('Model')->model('ChannelEntry')->filter('field_id_10', 'search on a entry_field');

//include the model in the query
$query->with('moduleName:TestWith');

//search on the title in the custom model
$query->filter('moduleName:TestWith.title', 'test');

//print the result
print_r($query->first()->toArray());

```

It seems the `->with()` is not working with custom models. Using the `->with()` on the `Channel` model seems to working.

```
$query->with('Channel');
$query->filter('Channel.channel_id', 10);
```

Any idea what i  did wrong?

**Comment by kevincupp** [comment]
Sorry for the trouble, @reinos. Yes I can reproduce with just this:

```php
ee('Model')->get('ChannelEntry')->with('fluid_field:FluidField')->first();
```

It should probably work, so we can look into it, or let us know if you have a pull request in the works.

**Comment by reinos** [comment]
Hi Kevin,

Thanks for your reply. Sure i will try, but i need some direction where to look... What files are responsible for that link (`with()`)?

**Comment by kevincupp** [comment]
I'm not too sure where this bug may be, but this file captures the withs:

system/ee/EllisLab/ExpressionEngine/Service/Model/Query/Builder.php

And then this file processes them:

system/ee/EllisLab/ExpressionEngine/Service/Model/Query/Select.php

**Comment by reinos** [comment]
Hi Kevin,

I not have that much time to dive into, however i did try to debug it this day.

As it looks like, the name you set in the `->with()` in our example `->with('fluid_field:FluidField')` is literally added to the alias array. If i check the method `expandAlias($alias)` in file `system/ee/EllisLab/ExpressionEngine/Service/Model/Query/Select.php` i see that the array `$this->aliases` is hold the name `fluid_field:FluidField` instead of `fluid_field_m_FluidField`.

A quick dirty fix can be 
```
protected function expandAlias($alias)
{
    if(isset($this->aliases[$alias]))
    {
        return $this->aliases[$alias];
    }
    else
    {
        $alias = str_replace(':', '_m_', $alias);
        if(isset($this->aliases[$alias]))
        {
            return $this->aliases[$alias];
        }
    }
}
```

But this will trigger other errors.

I leave it for now because I do not exactly know the underlying code and how it works together. I hope you can fix it asap :-)

Let me know.

**Comment by kevincupp** [comment]
Ah, thanks, @reinos! I poked around there but totally didn't notice the formatting of the alias, so nice sleuthing.

I think this should fix it up:

``` diff
diff --git a/system/ee/EllisLab/ExpressionEngine/Service/Model/Query/Select.php b/system/ee/EllisLab/ExpressionEngine/Service/Model/Query/Select.php
index bb5cff9e1b..b789a89bbb 100644
--- a/system/ee/EllisLab/ExpressionEngine/Service/Model/Query/Select.php
+++ b/system/ee/EllisLab/ExpressionEngine/Service/Model/Query/Select.php
@@ -54,11 +54,7 @@ class Select extends Query {
                        $aliases = array_merge(array($this->root_alias), array_keys($withs));
                        foreach ($aliases as $alias)
                        {
-                               if (stripos($alias, ' as ') !== FALSE)
-                               {
-                                       $parts = explode(' ', $alias);
-                                       $alias = end($parts);
-                               }
+                               list($from, $alias) = $this->splitAlias($alias);

                                $class = $this->getClass($alias);
                                if ( ! is_null($class::getMetaData('field_data')))
```

Want to try that? I'm running our automated tests locally in the mean time.

**Comment by kevincupp** [comment]
This looks to be working and hasn't broken anything on my end, I'm going to go ahead and commit this so we can get it in our next release. Thanks again!

**Comment by reinos** [comment]
Hi Kevin,

A little feedback, it seems to work! Thank you!
