### ISSUE TITLE
Upgrading EEXam

### ISSUE THREAD

**Issue by ITatPRN** [ExpressionEngine/ExpressionEngine#3100]
We are a small non-profit on EE since 2010.  We are stuck on version, (wait for it,) 2.11.9.  We are stuck here because we use EEXam (1.0.14) to support our free education program and EEXam has not been updated beyond EE V2.

We are looking for a developer that can help us move beyond EE V2 by maybe updating EExam and helping us get to EE V7.

Any insight or help would be most appreciated. 

John - IT
PRN

**Comment by jcogs-design** [comment]
There were significant changes in EE's internal architecture between EE2 and EE3 that by necessity required EE2 era add-ons to be substantially rewritten to work with EE3. EExam is a fairly complicated add-on and to update it would be a significant task - the php and javascript code used would both need to be substantially updated before an updated add-on would work. 

Futher, it appears that while the original authors have abandoned their support for the software, it does not appear that they have given up their ownership of it, so any attempt to recode the add-on to work with newer versions of EE would likely be breach of their copyright for the code - this may have been waived or some such in the original license issued with the release of the software but while you can download a copy of the add-on from Devot:ee it does not come with any indication of what that original use license was. 

The original authors have a [one-page website](https://coffeebean.design/) still and that indicates that they are based in the UK, but offers nothing but an email address to inform on their active status. My suggestion is that if you want to pursue updating this add-on you first contact the authors are seek permission to create your own modified version of their software - without that anything else you do is likely to be exposing you to potentially adverse consequences later.

**Comment by ITatPRN** [comment]
Thank you for this thoughtful response.  After writing this post I did reach out
to the original developer.  However, I did not yet ask for permission to reuse
their code.   I'm waiting to see if I hear back from them at all.


Regards,


John
IT
PRN

[data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs=3D]

**Comment by intoeetive** [comment]
@ITatPRN the best place to look for advices like this would be `#programming` channel in [EECMS Slack](https://expressionengine.com/blog/join-us-in-slack)

**Comment by ITatPRN** [comment]
Thank you Yuri.
