### ISSUE TITLE
Members can view auto saves created by other members

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#3101]
EE 7.2.11

How to replicate:

1. Start creating an entry, and fill out some fields. Wait until the `Auto saved` indicator appears. Leave the page without saving it.
2. Log in as another user. Start creating an entry, and you will see `Auto saves` tab, where you can access other member's content

**Comment by intoeetive** [comment]
I initially accepted this as bug, but then realized that some people might actually be using this as a way for editors to continue work on someone's not-yet-saved entry.

But the list of autosaves should be restricted to just the current channel, which is a bug that we need to get fixed.
