### ISSUE TITLE
Misinterpretation of PHP string formatting directives when saving template

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#311]
**Description of the problem**
Some PHP string formatting directives are being misinterpreted, and as a consequence deleted, when saving a template.

**How To Reproduce**
Create a blank template, and add:

``<?php $test = sprintf("%02d", $num); ?>``

On saving, the template contents become:

``<?php $test = sprintf("d", $num); ?>``

**Environment Details:**
 - Version: 5.2.6

**Comment by intoeetive** [comment]
Unable to replicate this in EE 6.0.3
