### ISSUE TITLE
Pro Variable permission duplicates in cp

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3112]
Pro Variables settings page.  Add enough Roles with cp access that the display of the role permissions on the settings page switches to scrollable.  You will see that Super Admin is on there twice.  

So, you pick your roles you want to have access, you save.  Now you have 4 super admin listed.  OK, more than 4.  But regardless, more than 1 is too many.

<img width="1242" alt="Screenshot 2023-03-13 at 1 37 46 PM" src="https://user-images.githubusercontent.com/1181219/224782998-a6119f5f-5ab6-44f6-87a4-ee04a467b893.png">

**Comment by Yulyaswan** [comment]
@matthewjohns0n it would be great if you check this one. More details I sent you in DM

**Comment by robinsowell** [comment]
Quick note, same thing is happening with the Field choices.  Basically, we can have problems when we get selects with lots of options.  Ran into the same issue with the statuses #3120.
