### ISSUE TITLE
Login form error "The page you requested was not found."

### ISSUE THREAD

**Issue by CharlottesvilleMedia** [ExpressionEngine/ExpressionEngine#3119]
Just upgraded to 6.4.6 and when I use the basic login form:

`{exp:member:login_form}

        <label>Username</label><br />
        <input type="text" name="username" value="" maxlength="32" size="25" />
        <label>Password</label><br />
        <input type="password" name="password" value="" maxlength="32" size="25" />

        <input type="submit" name="submit" value="Submit" />

{/exp:member:login_form}`

I get the error "The page you requested was not found." with the url "[website]/assets/img/icons/icon-target.svg"

Using the "return=" parameter gives the same error and url

**Comment by intoeetive** [comment]
There is no reference to file named `icon-target.svg` in EE code.
You might have some extension involving that file, or server configuration setting.

I suggest that you search the site's codebase for `icon-target.svg` text.

And you're always welcome to ask for community help in [EE Slack](https://expressionengine.com/blog/join-us-in-slack) or [Forums](https://expressionengine.com/forums)
