### ISSUE TITLE
Getting notice after upgrade EE5.3 to EE7.2.11

### ISSUE THREAD

**Issue by sw-tt-akshaybhatt** [ExpressionEngine/ExpressionEngine#3123]
Hii there,

I am getting this Notice in expression engine control panel :

```
Notice
Trying to get property 'group_name' of non-object
ee/ExpressionEngine/Model/Template/Template.php, line 123
Severity: E_NOTICE
```
Error Image:
![Error Image](https://user-images.githubusercontent.com/127393683/225290517-5d009d9c-5d2e-4052-9c0c-01042f91da6d.png)

Local server Url, where i got the error:
http://mysite.local/admin.php?/cp/utilities/debug-tools/debug-tags&S=a084597f7946cc53dbf53f1568913cf6

Original Code:
![Orignal Code Image](https://user-images.githubusercontent.com/127393683/225287950-0e04bf79-0c29-454f-be3d-679df601c0fc.png)

If i modified line as per below screen shot than it's working fine:
![Modified core files](https://user-images.githubusercontent.com/127393683/225288520-9a8e7e38-2bdf-436f-9bd8-28bc9cb92a63.png)

To modify it what will be the solution because i can't change directly in core file, because if i upgrade it in future the changes will be removed. Pls provide the solution for it.

**Comment by intoeetive** [comment]
@sw-tt-akshaybhatt can you show the structure of `system/user/templates` and `system/user/templates/<site_name>` folders? Particularly interested to know if there are any files in there that are not in subfolders

**Comment by sw-tt-akshaybhatt** [comment]
Hii @intoeetive ,

Pls check the attached screenshot:

**Comment by intoeetive** [comment]
Thank you. Can you also show the contents of `templates/default_site`?

**Comment by sw-tt-akshaybhatt** [comment]
Hii @intoeetive ,

It's my project template files

**Comment by intoeetive** [comment]
what's in bottom part of the list? (any files that are not in folders)

**Comment by sw-tt-akshaybhatt** [comment]
Hi @intoeetive ,

Here is the remaining list of bottom part of template list.

**Comment by sw-tt-akshaybhatt** [comment]
Hi @intoeetive,

Any update on above point?

**Comment by intoeetive** [comment]
We have not been able to replicate the issue so far, but we'll be investigating it further (please understand we can't provide any ETA here)

**Comment by sw-tt-akshaybhatt** [comment]
Hii @intoeetive,

Is there any update on above stuff? As we want to go live as soon as possible.

**Comment by intoeetive** [comment]
@sw-tt-akshaybhatt I believe you're dealing with corrupt data

Can you try following, in `getPath()` function add this code:
```
if (!is_object($this->getTemplateGroup()) {
    dump($this->template_name, $this->group_id);
}
```
Make sure the `exp_template_groups` table has a record for that group_id
In case that is empty search your `exp_templates` table for the template with that name and give it correct group_id

Let me know if that helps to fix the issue.

Also - if that confirms to be the case - would be eager to know how you got there (any external scripts / addons executed, major version update, etc. etc)

**Comment by sw-tt-akshaybhatt** [comment]
Hi @intoeetive,

Yes you are right. I have found some data which has no matched group_id in the parent table `exp_tamplate_groups`. I have fixed it. There is one suggestion from my end that can you please add foreign key for key `group_id` in database table of `exp_templates`? So, we can avoid this type of issues in future. Thank you.

**Comment by intoeetive** [comment]
ExpressionEngine (as of versions 6 and 7) is not making use of MySQL foreign keys. If you think this is something we need to do, please open a feature request in Discussions.

Closing this out now.
