### ISSUE TITLE
Matrix + Pro Variables

### ISSUE THREAD

**Issue by liamcrean** [ExpressionEngine/ExpressionEngine#3128]
**Description of the problem**

Matrix Fields can not be added to Pro Variables. There's the following warning

`Matrix requires Low Variables 2.2 or later.`

The creation triggers this error

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.exp_low_variables' doesn't exist:`

This does create the field but the warning `Matrix requires Low Variables 2.2 or later.` remains

There are many references in Matrix files to Low, which will need updating.

**Environment Details:**
 - Version: [e.g. 7.2.10]
 - PHP Version [e.g. 8.0]

**Comment by bakin1999** [comment]
Thanks for letting us know about this
Matrix release 3.6.0 resolves this
