### ISSUE TITLE
Offline Message to display when Add-ons are being updated

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#3129]
I've noticed that while updating the EE add-ons, that an error is displayed on the site, even though I have set the site to Offline mode.

Would it be possible to make this Offline Message screen appear, whilst these kinds of updates are taking place?

**Comment by intoeetive** [comment]
@ic360-com is that when you place newer files in the /user/addons folder but did not run update in CP yet? Or during the (short) time when update is actually being run?

Also, I suspect this is limited to specific add-on and versions. Do you remember what you've been updating and between which versions?

**Comment by ic360-com** [comment]
This is when I replace the add-on files/folders on the server.
Yes, I was updating Cartthrob at the time from v6 to v7.

**Comment by intoeetive** [comment]
@ic360-com I wasn't able to replicate this going between CT 6.3 and CT 7.3 on ExpressionEngine 7

If you ever face this again, please make a screenshot of the error

**Comment by ic360-com** [comment]
I've just done another CT update (7.2 to 7.3) with the site Offline (EE 7.2.11) but can see the attached error when viewing the site, instead of the Offline Message. This occurs when the old CT files have been deleted, and before the new ones have been uploaded.
![Screenshot 2023-03-23 at 09 41 32](https://user-images.githubusercontent.com/36453035/227164411-d3010067-d937-48d6-b917-ee58a6d8788d.png)
