### ISSUE TITLE
Discussion Forum: After Upgrade, URL is 404ing

### ISSUE THREAD

**Issue by dougblackjr** [ExpressionEngine/ExpressionEngine#3139]
**Description of the problem**

Upgraded site from EE2.6 to most recent. Updated Forum add-on to most recent version. Now, the `/forum` route is 404ing.
![Screenshot from 2023-03-19 18-04-11](https://user-images.githubusercontent.com/6020323/226212543-2a89926a-1778-45ed-aa6e-f29e803a62e7.png)
![Screenshot from 2023-03-19 18-04-18](https://user-images.githubusercontent.com/6020323/226212553-051a0de5-3b56-4f5f-96c8-7804c7c74c4c.png)

**How To Reproduce**
1. Upgraded EE
2. Upgrade Forums
3. Ensure proper URL is set up
4. Visit page.

**Environment Details:**
 - Version: 7.2.11
 - PHP Version 8.0
 - MySQL Version - 8.x
 - OS: Linux
 - Web Server: nginx

**Comment by intoeetive** [comment]
@dougblackjr does it work if you make "forum directory" relative and not absolute URL?

Also, in EE7 the files for Forum should be in /system/user folder - can you confirm that is where your files are?

**Comment by dougblackjr** [comment]
@intoeetive No, unfortunately changing to a relative URL doesn't fix the issue. And the add-on is in `/system/user/addons`, is that correct?

**Comment by intoeetive** [comment]
That is correct. And the themes should be in `themes\user\forum`

**Comment by dougblackjr** [comment]
@intoeetive Ok that is all set up correctly. Where else should I look to debug this? I can check where the route is registered, but I'm not seeing that at all.

**Comment by intoeetive** [comment]
Does that work if you add `index.php` in the address bar? If not, we probably need to pull @robinsowell in

**Comment by dougblackjr** [comment]
@intoeetive Unfortunately neither https://aasbc.test/forum/index.php nor https://aasbc.test/index.php/forum/ work.

**Comment by robinsowell** [comment]
poking it....

**Comment by robinsowell** [comment]
It's working for me- is the 'Forum url segment' forum?  And are you using the forum tag in an actual template or letting the forum add-on handle it without that?

**Comment by robinsowell** [comment]
all good- there was some weirdness with settings and php in a template.  No bug.  All good here.  Move along....

**Comment by dougblackjr** [comment]
Thanks for all of your help @robinsowell!!!!
