### ISSUE TITLE
Template does not render if channel uses more than 50 data fields.

### ISSUE THREAD

**Issue by marketingalliance** [ExpressionEngine/ExpressionEngine#314]
**Description of the problem**

I built a channel with 75 fields of data. Not an issue under EE2, but under the latest release of EE5, once a channel has around 50 fields of data, the template will not render if there are more than 3 channel entries. I've tried this on two separate installs of EE5 on Siteground and Nexcess. In both cases, the template never rendered. It just timed out.

**How To Reproduce**

1. Create a channel called Test.
2. Assign 50 channel fields to that channel.
3. Post 4 entries to that channel.
4. Create a basic template (my example is below).
5. See if it will render.

**Error Messages**

<pre><code>

</code></pre>

**Screenshots / Videos / Template Code**

<pre><code>

{exp:channel:entries channel="test" disable="categories|category_fields|member_data|pagination" }
{title}<br />
{/exp:channel:entries}

</code></pre>

**Environment Details:**
 - Version: 5.2.6 [e.g. 5.0.1]
 - PHP Version: 7.2.2 [e.g. 7.1]
 - MySQL Version 5.6.4 [e.g. 5.7]
 - OS: Windows 7 [e.g. Linux, macOS, Windows]
 - Web Server: Apache [e.g. Apache, nginx, MAMP, etc.]

**Possible Solution**

Once I reduced the channel field count to 45, the template rendered instantly.

**Additional context**

**Comment by derekjones** [comment]
What do your MySQL, PHP, and Apache error logs have to say? This sounds like an environmental configuration issue.

**Comment by marketingalliance** [comment]
It's a different site and host than in #316. I'll need to go back and see if I can pull error logs from that day.

Just for comparison,
sql_big_selects is ON
max_join_size is 18446744073709551615

**Comment by derekjones** [comment]
What might be easier is to make a new test template reduction test with your Channel Entries tag, no markup, and just the 50+ fields. Then you can see your logs for that specific request more easily.

Might also try this in case there is some weird error suppression going on: https://gist.github.com/litzinger/5598641

**Comment by intoeetive** [comment]
I am closing this issue as out-of-date.

There have been a lot of changes in EE6 and 7 related to fetching and parsing fields (and few more coming in 7.3)

If you are still experiencing the problem, turn on debugging (as advised by Derek in post above) and [error logging](https://docs.expressionengine.com/latest/troubleshooting/error-logging.html) and see if you get any errors
