### ISSUE TITLE
Channel Form -> URL title: This field is required when capitalized french characters

### ISSUE THREAD

**Issue by benoitlemay** [ExpressionEngine/ExpressionEngine#315]
**Description of the problem**
Using dynamic_title in a channel form. If the input text containt capitalized french character ex.: ÉÀ. I got this error : 'URL title: This field is required'. If the character is not capitalized it's working and EE change the french character to is non-accent in the url_title .. ex.: é -> e

**How To Reproduce**
Creater a channel with input text field.
Create a template with channel form code and include a dynamic_title ex.: dynamic_title='{current_time format="%Y%m%d%H"}-[nom_test]_[prenom_test]'
Try to add Entry via the Channel form and use ÉÀ or any capitalized character.
You will get an error 

**Error Messages**
The form you submitted contained the following errors
URL title: This field is required.

**Environment Details:**
 - V 5.2.6 and 5.2.3
 - PHP Version 7.2.21
 - MySQL Version 5.1.73
 - OS: Linux
 - Web Server: Apache

**Comment by benoitlemay** [comment]
Hi,
Any idea when this bug will be solved? 
Thanks!

**Comment by benoitlemay** [comment]
I found a workaround (or maybe THE solution...)  i added the entities code in this file .. admin\ee\EllisLab\ExpressionEngine\Config\foreign_chars.php

**Comment by obfuscode** [comment]
I believe we can use the JS native `normalize()` to convert the diacritics to a unicode normalized format and remove the reliance on a foreign character dictionary as well as the PHP and JS to loop through and replace each character one-by-one.

We'll have to test it but we could remove these two bits of code:
https://github.com/ExpressionEngine/ExpressionEngine/blob/e601aab93d85e05975c7b7d8256a137d119c9e08/system/ee/EllisLab/Addons/channel/libraries/channel_form/Channel_form_lib.php#L3465-L3487

https://github.com/ExpressionEngine/ExpressionEngine/blob/e601aab93d85e05975c7b7d8256a137d119c9e08/system/ee/EllisLab/Addons/channel/libraries/channel_form/Channel_form_lib.php#L3522-L3538

And then add this code: 
```
NewText = NewText.normalize('NFD').replace(/[\u0300-\u036f]/g, "");
```

Above the `toLowerCase()` line:
https://github.com/ExpressionEngine/ExpressionEngine/blob/e601aab93d85e05975c7b7d8256a137d119c9e08/system/ee/EllisLab/Addons/channel/libraries/channel_form/Channel_form_lib.php#L3519

### There are limitations to this method as well though as some actual letters are not diacritics and are not replaced like ł ß æ ø

Thoughts? Should we replace the dictionary with this method or keep it?
