### ISSUE TITLE
EE7 Pro Variables RTE editor config doesn't stick

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3152]
EE 7.2.11

I allow RTE as a variable type in Pro Variables, make a pro variable, RTE type, but no matter what editor config I select, it doesn't stick and I end up  with ckeditor basic.

Also- RTE showed up twice in my variable choices when setting the allowed variable types..

<img width="704" alt="Screenshot 2023-03-21 at 5 31 41 PM" src="https://user-images.githubusercontent.com/1181219/226747589-f09856c5-6780-4ba0-bcb2-e6d71da6cfc9.png">

**Comment by jaredchesebro** [comment]
Having the same issue.
