### ISSUE TITLE
[7.3 DP4] I'm seeing an error from the rteOnGridDisplay function

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#3158]
**Description of the problem**

I'm seeing the following error in my console that I think originates from the rteOnGridDisplay() function.

`TypeError: undefined is not an object (evaluating 'config[0]')`

I'm actually seeing this in a Bloqs field that has an RTE field in it, and I haven't seen it before or made any changes to Bloqs recently to cause this. I'll do some more debugging locally and roll back to 7.2, just wondering if this is something you call can replicate in an actual Grid field? It's causing none of my RTE fields to show and since it's a JS error its terminating some additional JS on the page, thus breaking a lot of things.

**Comment by litzinger** [comment]
I rolled back to 7.2.12 and everything is working again.

**Comment by intoeetive** [comment]
@litzinger thank you for testing. I found the reason for this, but not sure about the solution.

In `system\user\addons\bloqs\Controller\FieldTypeWrapper.php` you have this check
> is_callable(array($ft, 'block_' . $methodName))

However in EE 7.3 we added `__call` magic method to `ModifiableTrait` whih all fieldtypes are using. That means that any method is always callable, and this means `grid_display_field` is never called.
Internally, we use `method_exists`, which works well for such cases - do you think it is possible for you to make this change in Bloqs code - or you have specific reasons to not use it?

**Comment by litzinger** [comment]
Interesting find. No reason I couldn't use method_exists. I'll make the change and test it locally. Thanks for pointing this out.
