### ISSUE TITLE
In RTE fields, inserted images that are in a subfolder do not use the correct URL

### ISSUE THREAD

**Issue by telophase** [ExpressionEngine/ExpressionEngine#3162]
**Description of the problem**
Inserting an image into an RTE field that is in a subfolder does not work correctly. Any subfolder path information is lost in the file's URL in the RTE field after it is inserted.

For example, if my image can be found in the file browser at `[url]blog/images/birds/cardinal.jpg`, inserting this image into an RTE field via the add image button will insert an image with the url `[url]blog/cardinal.jpg`, which yields a broken image.

If I insert an image that is not in a subfolder, such as `[url]blog/bluejay.jpg`, it is inserted correctly as an image with the URL  `[url]blog/bluejay.jpg`.

My installation uses MSM and this occurs across all sites.

This bug occurs regardless of:
- If the upload directory folders that use {base_url} in the upload directory URL or not
- If the RTE field has content in it or not
- If the RTE field was preexisting or was just created
- If the image was selected from the "recent files" or was browsed to explicitly (through subfolders) in the FilePicker
- If the image is one or many subfolders deep

**How To Reproduce**
1. Create a subfolder in any upload directory
2. Put an image in it
3. Go to an RTE field (CKEditor Full mode, not sure if it occurs with Redactor)
4. Attempt to add an image via the FilePicker
5. You can browse to image in subfolder and select it, but inserted URL will be wrong.

**Environment Details:**
 - EE Version: 7.2.12, MSM enabled
 - RTE Plugin Version: 2.1.0
 - PHP Version: 8.2
 - MariaDB Version:  10.11
 - OS: Alpine Linux, in a Docker container
 - Web Server: Caddy
 
**Additional context**
I want to say this bug is new, because I had previously and successfully inserted and image that was in a subfolder into an RTE field within the last week or so. I don;t insert images regularly, so I can't recall if I did that prior to 3/20/2023, when I updated to 7.2.12.

This is my first bug report, so please let me know if it's hard to understand or I need to change something! Thank you EE devs for continuing to develop and support ExpressionEngine.  :heart:

**Comment by telophase** [comment]
An update on this, the behavior is irregular. I've found that in grids with RTE fields, images in subfolders will work correctly in some grid rows, but incorrectly in others...

**Comment by intoeetive** [comment]
This seems to be an issue when there are files with duplicate name in and outside of subfolder. Also the previews shown in file managers are incorrect in this case

**Comment by telophase** [comment]
Wow, that was fast! I'll let you know if I still face this issue after updating to 7.2.14 after it goes live. Thanks
