### ISSUE TITLE
adding new conditional field and syncing conditional fields not completing

### ISSUE THREAD

**Issue by aasun** [ExpressionEngine/ExpressionEngine#3164]
**Description of the problem**
Trying to set up a conditional text field to only display when a toggle is turned on.. The specific toggle field is set to be off by default.  So, this conditional field should not display when the entry form is loaded if the toggle is off..  That works on a new entry. But, on existing entries, the conditional field is displaying, even when the toggle is off. If I toggle to on, then to off, the conditional field hides.  Something is quirky.

**How To Reproduce**
I create the conditional text field, then set up the single conditional rule, where the toggle field is on.

I then run the Sync Conditional Fields tool, but it always bails about 15%-20% through the progress bar.. The channel that I'm doing the sync on has 4,476 entries.. And the sync ends about 2 min each time (I think about there.. So, it may be an issue with the script execution time?

**Error Messages**

No error messages.  The syncing progress simply returns to the sync page showing all channels with the green notation box saying  at the top that "All related channel entries have been updated to use the most recent conditional logic."  But, the channel with the conditional field, still has a exclamation circle icon saying sync required..  I've re-ran this sync a few times, same behavior each time.

**Screenshots / Videos / Template Code**

**Environment Details:**
EE 7.2.12 Pro
PHP 8.1.17
Nginx

**Possible Solution**
Initially, I though maybe the toggle field keying the condition was the problem.. it was added after most of the entries were in the system, so there were only rows for about 200 of the entries... So, I manually updated that database table setting a 0 entry for the toggle for all the entries in the channel... But, there was no change in the sync behavior.

**Additional context**

**Comment by intoeetive** [comment]
@aasun can you try running the sync with the Network tab in browser developer tools open, and check the last AJAX request (the one where the sync stops; I think it will be marked red because of error). What is the response message that you can see in it?

**Comment by intoeetive** [comment]
We're adding new `php eecli.php sync:file-usage` command to CLI in EE 7.3.0 which will hopefully resolve your issue

This is also available in the [pre-release](https://github.com/ExpressionEngine/ExpressionEngine/releases) zip on Github, if you need it right now or want to test
