### ISSUE TITLE
cp/members/profile/settings - sprintf(): Too few arguments error…

### ISSUE THREAD

**Issue by karlosb** [ExpressionEngine/ExpressionEngine#317]
**Description of the problem**
When clicking on a member profile in the EE CP Login we are getting a PHP error.

**How To Reproduce**
ie. Logging into say member id#1
cp/members/profile/settings&id=1

**Error Messages**

<pre><code>
Warning
sprintf(): Too few arguments
ee/EllisLab/ExpressionEngine/Controller/Members/Profile/Profile.php, line 78
Severity: E_WARNING
</code></pre>

**Environment Details:**
 - Version: 5.2.6
 - PHP Version 7.0.33
 - MySQL Version: mySQLI 5.0.12 (staging) / MariaDB version 10.2 (local)
 - OS: MacOS
 - Web Server: Apache / Docker/DDEV

**Comment by derekjones** [comment]
Are you using a custom language pack? Sounds like your `profile_header` language item might be improperly defined.

**Comment by karlosb** [comment]
Hi Derek, 

Many thanks for getting back to me on this. 

We have EE Harbour Transcribe is installed on the site so we have:

system/user/language/

with the following folders:

- chinese
- deutsch
- english
- french
- portuguese
- spanish

Would something in one these folders be causing the issue perhaps?

I can see (at around) line 78 of profile.php we have:

`		ee()->view->header = array(
			'title' => sprintf(lang('profile_header'),
				htmlentities($this->member->username, ENT_QUOTES, 'UTF-8'),
				htmlentities($this->member->email, ENT_QUOTES, 'UTF-8'),
				$this->member->ip_address
			)
`

So could we be missing some data for this php script perhaps?

**Comment by derekjones** [comment]
No, the incorrect data is coming from the language pack itself. Specifically [myaccount_lang.php for the `profile_header` line](https://github.com/EllisLab/EE-Language-English/blob/8b379615ad8b0d3b232fea9722d1d63a81b2445c/user/language/english/myaccount_lang.php#L399-L401).

Notice that the English language pack has three `%s` (string) parameters that the code is expecting. You'll need to find which one of your language packs has the incorrect count within its defined values.

**Comment by karlosb** [comment]
Ok in system/user/language/english we have:

`'profile_header' => '%s Profile<br><i><b>Email</b>: <a href="mailto:%s">%s</a> / <b><abbr title="Internet Protocol">IP</abbr>:</b> <span class="ban-options"><b>%s</b></span></i>',
`
would this line be causing the issue?

**Comment by derekjones** [comment]
Yes, any and all language packs that you have customized or installed that are missing the required three `%s` placeholders will cause this problem.

**Comment by karlosb** [comment]
What I'm not understanding here is that the site has been recently upgraded to v5.2.6 from v3.5.8. Under v3.5.8 the profile error was not present and the language folders (and their contents) have not changed (since the upgrade to v5). Is there any reason why it would have worked without error in v3 but not in v5?

**Comment by derekjones** [comment]
Because the included default English pack has changed _a lot_ since v3. You can follow changes to the language packs, which should be updated and reflected in your custom ones, by visiting the links in the default English pack [README](https://github.com/EllisLab/EE-Language-English). You can also use GitHub's diff engine to see the difference between any two versions en masse by tweaking the tags in the URLs.

**Comment by karlosb** [comment]
Hi Derek, I've replaced the existing english pack with the latest on the supplied github link and the error is now gone.

So many thanks for the help with this, much appreciated :-)
