### ISSUE TITLE
[EEv6.4.7] Security Settings: Rank Denial of Submitted Links causing 404 when logged out.

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#3175]
1. Publish an off-site link to a live page.
2. Publish that entry to a channel that requires the person to be logged into EE to view.
3. Using another browser window in same browser, log out of EE (or wait for cookie to expire)
4. Without reloading the page with the content and link, click the link, and you'll end up on a default EE 404 page instead of either the login page or the templated 404 page.

We found this when social service caseworkers were keeping a page open in a tab in their browser with links to Google Docs where they would update info throughout the day. Sometimes the links worked (if/when they were logged in) and sometimes they got a 404 (if/when their cookie had expired).

We initially expected that EE would let them see and use the Redirect Warning regardless of login status, but it might be more secure if EE would either show the login page.

At a minimum take them to the templated 404 vs. the default 404.

<img width="720" alt="Screenshot 2023-03-30 at 3 50 58 PM" src="https://user-images.githubusercontent.com/6145078/228986146-b41216df-dfe9-4999-ae1e-b02965cdad6d.png">

Let me know if you have any questions.

- Kurt

**Comment by intoeetive** [comment]
Hi @PDXMan1 , few questions here

How is the access restriction done here? Is the template set to only allow certain member roles in template's settings? Or do you have parameter with `no_results` tag inside `exp:channel:entries` call?

How is the link set up? What is the template code for it and where is it placed in the template?

Also am I getting right that CP interaction is not involved here, this is the issue that happens on front-end?

**Comment by PDXMan1** [comment]
`{if segment_1 == 'advocates' AND (logged_in_group_id == '1' OR logged_in_group_id == '6') AND embed:require_login == 'yes'}
	[EMBEDED TEMPLATE]
	{exp:channel:entries site='{embed:site}' channel='{embed:host_language_channel_name}' dynamic='{embed:dynamic}' limit='8' {embed:channel_parameter}='{embed:channel_variable}' require_entry='yes' disable='pagination|categories|member_data'}{if no_results}{redirect='404'}{/if}
	{/exp:channel:entries}
	[/EMBEDED TEMPLATE]
{/if}`

The URL is directly in a textarea field, and EE is turning it into a link dynamically.

The reports of the issue came from people using a front-end login form, I could recreate it by logging in and out of the CP.

That help?

**Comment by intoeetive** [comment]
Hi @PDXMan1 - back on this one. 

I was able to replicate it and the behaviour you're seeing is actually intended. There's discussion around that here https://github.com/ExpressionEngine/ExpressionEngine/issues/1856

I believe what you need is `allow_url_redirects_from_site` configuration override
