### ISSUE TITLE
Creating new addon via CLI

### ISSUE THREAD

**Issue by williamsears** [ExpressionEngine/ExpressionEngine#3191]
**Description of the problem**
On EE 7.2.12 - If you use the CLI to make:addon and then subsequently make:fieldtype and then make:action you will get the following errors when installing / uninstalling your addon: 

```
Warning
Undefined array key "module"
ee/legacy/libraries/addons/Addons_installer.php, line 326

Severity: E_WARNING
Warning
Trying to access array offset on value of type null
ee/legacy/libraries/addons/Addons_installer.php, line 326

Severity: E_WARNING
Deprecated
rtrim(): Passing null to parameter #1 ($string) of type string is deprecated
ee/legacy/core/Loader.php, line 586

Severity: E_DEPRECATED
Warning
Undefined array key "module"
ee/legacy/libraries/addons/Addons_installer.php, line 330

Severity: E_WARNING
Warning
Trying to access array offset on value of type null
ee/legacy/libraries/addons/Addons_installer.php, line 330
```

**How To Reproduce**
1. make:addon
2. make:fieldtype
3. make:action
4. install the addon and see the errors

**Environment Details:**
 - Version: [7.2.12]
 - PHP Version [8.1.2]
 - OS: [Windows]
 - Web Server: [XAMPP]

**Comment by intoeetive** [comment]
@williamsears I wasn't able to replicate this following the steps you provided. Can you send me the copy of the add-on that was generated?

**Comment by williamsears** [comment]
[channel_explorer.zip](https://github.com/ExpressionEngine/ExpressionEngine/files/11136911/channel_explorer.zip)
