### ISSUE TITLE
Category entry all files search 

### ISSUE THREAD

**Issue by mackilroy007** [ExpressionEngine/ExpressionEngine#3194]
**Description of the problem**
Category entry image edit search does not function. 
The search field will not respond to any search request, ignoring any imputed terms. If one filters, the page is changed beyond the original instance to the general file management section, where the selection of an image/file does not result in selecting/changing the file within the previously opened category entry, rather opens an instance similar to the content file (url goes from /cp/categories/edit/4/34 to /cp/addons/settings/filepicker/modal&field_upload_locations=all&hasUpload=1&filter_by_category=12&viewtype=list&perpage=25&sort_dir=desc&sort_col=date_added and finally to /cp/files/file/view/1624 on item select ), where each individual image/file can be edited.
In the end once lands within the content file section, where one can't assign the given content to the entry any more. 

**gif**
![EE-bug](https://user-images.githubusercontent.com/61562994/229462189-63f1e914-620c-4e04-b4e9-9e2ce311c55c.gif)

**How To Reproduce**

1. Open Category
2. Edit an entry in a category group
3. Scroll down to file and click edit
4. search for file item to select/replace the current (image) field

**Error Messages**
no error message is displayed at any given stage 

**Environment Details:**
 - Version: 7.2.11
 - PHP Version 7.4.33
 - Server-Version: 10.3.38-MariaDB-0ubuntu0.20.04.1-log - Ubuntu 20.04

**Additional context**
The search functionality seems to be working fine within the general file search instance, however within this pop out modal version its not working at all. Filtering causes a redirect to the general search function within the content file instance. Once redirected the search function works again however now one cant assign the file any more to the entry as one now is within the file management system.

**Comment by intoeetive** [comment]
@mackilroy007 I believe this was fixed as part of https://github.com/ExpressionEngine/ExpressionEngine/pull/3117 and released in EE 7.2.12

Please let us know if you still experience the issue after updating to latest version

**Comment by mackilroy007** [comment]
Hey Ive tested it on the current build 7.2.12 and still encountered the same issue.

**Comment by mackilroy007** [comment]
Thanks for the quick reply. 
I tested it on 7.2.13 and it worked perfectly fine. Thanks again 🙌
