### ISSUE TITLE
RSS Bug in Forum

### ISSUE THREAD

**Issue by jbaeckmann** [ExpressionEngine/ExpressionEngine#320]
If I call .../forum/rss I got the following exception:

> Exception Caught
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm.url' in 'field list':
SELECT `t`.`topic_id`, `t`.`author_id`, `t`.`title`, `t`.`body`, `t`.`topic_date`, `t`.`thread_total`, `t`.`last_post_author_id`, `t`.`last_post_date`, `t`.`topic_edit_date`, `t`.`parse_smileys`, `f`.`forum_text_formatting`, `f`.`forum_html_formatting`, `f`.`forum_auto_link_urls`, `f`.`forum_allow_img_urls`, `lp`.`screen_name` AS last_post_author, `m`.`screen_name` AS author, `m`.`email`, `m`.`url` FROM (`exp_forum_topics` t) LEFT JOIN `exp_forums` f ON `f`.`forum_id` = `t`.`forum_id` LEFT JOIN `exp_members` m ON `m`.`member_id` = `t`.`author_id` LEFT JOIN `exp_members` lp ON `lp`.`member_id` = `t`.`last_post_author_id` WHERE `t`.`announcement` = 'n' AND `t`.`forum_id` IN (3, 4, 5, 6, 7, 13, 9, 11, 12, 14, 15) OR `t`.`moved_forum_id` IN (3, 4, 5, 6, 7, 13, 9, 11, 12, 14, 15) AND `t`.`board_id` = 1 ORDER BY `t`.`topic_date` DESC LIMIT 10
ee/legacy/database/drivers/mysqli/mysqli_connection.php:117

> Stack Trace: Please include when reporting this error
#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('SELECT `t`.`top...')
#1 ee/legacy/database/DB_driver.php(270): CI_DB_mysqli_driver->_execute('SELECT `t`.`top...')
#2 ee/legacy/database/DB_driver.php(180): CI_DB_driver->simple_query('SELECT `t`.`top...')
#3 ee/legacy/database/DB_active_rec.php(1138): CI_DB_driver->query('SELECT `t`.`top...')
#4 ee/EllisLab/Addons/forum/mod.forum_core.php(1239): CI_DB_active_record->get()
#5 ee/EllisLab/Addons/forum/mod.forum.php(510): Forum_Core->_feed_builder()
#6 ee/EllisLab/Addons/forum/mod.forum_core.php(114): Forum->_include_recursive('_feed_builder')
#7 ee/EllisLab/Addons/forum/mod.forum.php(153): Forum_Core->display_forum()
#8 ee/legacy/libraries/Template.php(1776): Forum->__construct()
#9 ee/legacy/libraries/Template.php(1482): EE_Template->process_tags()
#10 ee/legacy/libraries/Template.php(578): EE_Template->tags()
#11 ee/legacy/libraries/Template.php(234): EE_Template->parse('{!-- ra:0000000...', false, 1, false)
#12 ee/legacy/libraries/Template.php(165): EE_Template->fetch_and_parse('', Array, false)
#13 ee/legacy/libraries/Core.php(661): EE_Template->run_template_engine('', '')
#14 ee/legacy/controllers/ee.php(63): EE_Core->generate_page()
#15 [internal function]: EE->index()
#16 ee/EllisLab/ExpressionEngine/Core/Core.php(241): call_user_func_array(Array, Array)
#17 ee/EllisLab/ExpressionEngine/Core/Core.php(110): EllisLab\ExpressionEngine\Core\Core->runController(Array)
#18 ee/EllisLab/ExpressionEngine/Boot/boot.php(151): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request))
#19 www/index.php(172): require_once('...')
#19 www/index.php(172): require_once('...')

My RSS Template for the forum looks like

`<?xml` version="1.0" encoding="{encoding}" ?>
`<rss version="2.0"
`    xmlns:dc="http://purl.org/dc/elements/1.1/"
`    xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
`    xmlns:admin="http://webns.net/mvcb/"
`    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
`    xmlns:content="http://purl.org/rss/1.0/modules/content/"> 
`    <channel>   
`    <title>{exp:xml_encode}{forum_name}{/exp:xml_encode}</title>
`    <link>{forum_url}</link>
`    <description>{exp:xml_encode}{forum_name}{/exp:xml_encode}</description>
`    <dc:language>{forum_language}</dc:language>
`    <dc:rights>Copyright {gmt_date format="%Y"}</dc:rights>
`    <dc:date>{gmt_date format="%Y-%m-%dT%H:%i:%s%Q"}</dc:date>
`    <admin:generatorAgent rdf:resource="http://expressionengine.com/" />    
`{rows}
`    <item>
`      <title>{exp:xml_encode}{title}{/exp:xml_encode}</title>
`      <link>{exp:xml_encode}{path:view_thread}{/exp:xml_encode}</link>
`      <guid>{path:view_thread}#When:{gmt_post_date format="%H:%i:%sZ"}</guid>
`      <description>{exp:xml_encode}{body}{/exp:xml_encode}</description>
`      <dc:date>{gmt_post_date format="%Y-%m-%dT%H:%i:%s%Q"}</dc:date>
`    </item>
`{/rows}    
`    </channel>
`</rss>
`

Exception appears in Version 5.2.6

**Comment by derekjones** [comment]
Do you have this same problem on 5.3.0? Sounds suspiciously similar to a bug fixed in that release.

**Comment by jbaeckmann** [comment]
Oh sorry, it really works again with 5.3.0....
Thanks you for the hint.
