### ISSUE TITLE
Live Preview error on fluid field

### ISSUE THREAD

**Issue by jejuna** [ExpressionEngine/ExpressionEngine#3201]
Just upgraded to 7.2.12 from 7.2.11. Thought it would take a second. It didn't.

Getting this on all pages when I preview:

Call to a member function getField() on null
ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php:157

Stack Trace: Please include when reporting this error
#0 ee/ExpressionEngine/Service/LivePreview/LivePreview.php(116): Fluid_field_ft->save(Array)
#1 ee/ExpressionEngine/Addons/channel/mod.channel.php(5214): ExpressionEngine\Service\LivePreview\LivePreview->preview('1', '7', NULL, false)
#2 ee/legacy/libraries/Actions.php(181): Channel->live_preview()
#3 ee/legacy/libraries/Core.php(678): EE_Actions->__construct(true, Object(Closure))
#4 ee/legacy/controllers/ee.php(51): EE_Core->generate_action(true)
#5 [internal function]: EE->index()
#6 ee/ExpressionEngine/Core/Core.php(268): call_user_func_array(Array, Array)
#7 ee/ExpressionEngine/Core/Core.php(124): ExpressionEngine\Core\Core->runController(Array)
#8 ee/ExpressionEngine/Boot/boot.php(184): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#9 index.php(164): require_once('...')
#9 index.php(164): require_once('...')

PHP 8.19

Screenshot:
![screenshot](https://user-images.githubusercontent.com/36213652/229586203-ae682765-015a-45c0-ba7a-e28540457b40.jpg)

Please advise!

Thanks--
Debra Weiss

**Comment by intoeetive** [comment]
The fix for this is planned for release tomorrow in version 7.2.13
