### ISSUE TITLE
File Manager category search for filter doesn't work if uploaded by selected

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3202]
File manager- have a lot of files, a lot of categories.  When you have a lot of categories, you get the search field so you can quickly limit them.  This works fine when I load up the page:

<img width="1432" alt="Screenshot 2023-04-03 at 2 17 22 PM" src="https://user-images.githubusercontent.com/1181219/229593544-e4ff26d4-bc4d-447d-b702-e05d4f0d03b7.png">

But- load up the page, go pick an 'uploaded by' person and then go try and use the search to get to a category.  It does nothing.  I don't see errors, but it's like it doesn't fire at all.

<img width="1365" alt="Screenshot 2023-04-03 at 2 16 55 PM" src="https://user-images.githubusercontent.com/1181219/229593717-573d9554-b9ce-4135-9d33-8a322b222d93.png">

**Comment by chunkitdesign** [comment]
Not only Category but also Added by and Upload Location. The Upload button also has some UI issues.
![](https://user-images.githubusercontent.com/3195497/229595613-96e3f3a0-24a4-468f-b6e5-75fb481f2bdb.png)

**Comment by chunkitdesign** [comment]
<img width="1537" alt="CleanShot 2023-04-03 at 14 28 25@2x" src="https://user-images.githubusercontent.com/3195497/229595613-96e3f3a0-24a4-468f-b6e5-75fb481f2bdb.png">

**Comment by intoeetive** [comment]
@Yulyaswan assigning this to you as it looks like JS issue - the issue exists only when the file manager is reloaded via ajax, everything works fine if you reload the page

**Comment by Yulyaswan** [comment]
same issue for modal window will be resolved in PR #3180
