### ISSUE TITLE
Grid field error "Trying to get property 'max_entries' of non-object"

### ISSUE THREAD

**Issue by Laisvunas** [ExpressionEngine/ExpressionEngine#322]
Steps to replicate:

1. Create Grid field having 6 text fields inside a row.

2. Submit an entry with this Grid field having 150 rows.

3. Add a new text field to the Grid, so that now Grid field will have 7 text fields inside a row.

4. Open saved entry and submit it again. After that you will see outputted these errors:

Notice
Trying to get property 'max_entries' of non-object
ee/EllisLab/ExpressionEngine/Model/Channel/ChannelEntry.php, line 268

Severity: E_NOTICE
Notice
Trying to get property 'channel_title' of non-object
ee/EllisLab/ExpressionEngine/Controller/Publish/AbstractPublish.php, line 100

Severity: E_NOTICE
Notice
Trying to get property 'default_entry_title' of non-object
ee/EllisLab/ExpressionEngine/Controller/Publish/AbstractPublish.php, line 103

Severity: E_NOTICE
Notice
Trying to get property 'url_title_prefix' of non-object
ee/EllisLab/ExpressionEngine/Controller/Publish/AbstractPublish.php, line 113

Severity: E_NOTICE
Notice
Trying to get property 'channel_title' of non-object
ee/EllisLab/ExpressionEngine/Controller/Publish/Edit.php, line 545

Severity: E_NOTICE
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/EllisLab/ExpressionEngine/Boot/boot.common.php, line 488

Severity: E_WARNING

**Comment by litzinger** [comment]
That definitely sounds like you're running into the max_post_vars issue. https://stackoverflow.com/questions/9399315/how-to-increase-maximum-post-variable-in-php#9399708

If that is the case that isn't an EE issue, it's an issue with your environment.

**Comment by Laisvunas** [comment]
Hi Brian,

Thank you very much!

I increased the value of PHP max_input_vars variable and this solved the issue.
