### ISSUE TITLE
Redis::delete() is deprecated

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#323]
**Description of the problem**

```
Function Redis::delete() is deprecated
ee/legacy/libraries/Cache/drivers/Cache_redis.php, line 79
    Severity: E_DEPRECATED
```

**Environment Details:**
 - Version: 5.3
 - PHP Version PHP 7.2.23
 - OS: Ubuntu 16
 - Web Server: Apache

**Comment by intoeetive** [comment]
Will be resolved with https://github.com/ExpressionEngine/ExpressionEngine/pull/918
