### ISSUE TITLE
EE7: Field group select list renders incorrect group IDs

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#3244]
**Description of the problem**
The field group dropdown is rendering incorrect HTML. The ID value in the dropdown list is numerically ordered, it's not the ID of the actual field group that is selected, which causes some weird visual behavior when viewing a group, but the dropdown list is displaying the name of a different group. In this case the "horses" group is actually ID #6, and "sale barns" is actually ID #7 

Navigate to /admin.php?/cp/fields&group_id=N

<img width="774" alt="Screenshot 2023-04-06 at 10 11 55 AM" src="https://user-images.githubusercontent.com/53965/230424248-d0d9a84d-e60e-4ef4-910d-4bbaa52db3f8.png">
<img width="547" alt="Screenshot 2023-04-06 at 10 10 46 AM" src="https://user-images.githubusercontent.com/53965/230424249-df27f5bd-95a4-41f2-b70c-4c6618e45b33.png">

**Environment Details:**
 - Version: 7.2.6
 - PHP Version 7.4

**Comment by intoeetive** [comment]
@litzinger looks like it has been resolved in 7.2.9: https://github.com/ExpressionEngine/ExpressionEngine/pull/2796
