### ISSUE TITLE
Pro search {pro_search_distance} can't return 0

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3245]
EE 7.2.13

The {pro_search_distance} should show the distance from the 'to' lat/longitude parameter, and it works UNLESS the distance is 0.  Then it just is empty.  I couldn't get it to output 0 no matter how I futzed around with it, including just hard coding '0' in the code.

I'm not sure how to fix, but it's definitely a bit confusing.  And at some point in the past, it did work.

Example template:

```
{exp:pro_search:form query="{segment_3}" result_page="home/search"}

  {!-- The user’s lat/long values --}
  <input type="hidden" name="distance:from" value="52.163298|4.505547">
  
  <input type="text" name="distance:radius" value="100">


  <button type="submit">Go</button>
{/exp:pro_search:form}

{exp:pro_search:results
  query="{segment_3}"
  distance:to="local_lat|local_long"
  distance:unit="km"
}
  <p>{title} is {pro_search_distance}km away.</p>
  {if no_results}
    <p>Sorry, nothing found within a {pro_search_distance:radius}km radius.</p>
  {/if}
{/exp:pro_search:results}
```
I had 2 custom fields local_lat and local_long - local_lat 52.163298 local_long 4.505543 is so close, rounded it comes to 0 and just doesn't display anything for that variable.

**Comment by intoeetive** [comment]
This appears to be an issue with the parser in general, not Pro Variables in particular. Elvis can be dangerous!

(when you're using Elvis operand `?:` and not checking for variable type - PHP would evaluate `float(0)` or even `string("0")` as `false`. TL, DR: don't use Elvis if you're working with mixed data type)
