### ISSUE TITLE
Fluid field conditional to check existence of field fails

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3246]
EE 7.2.13 - note, user reports same conditional DID work in EE 6.

Say you have a fluid field named 'my_fluid'.  In v6

```
{if my_fluid == ''} Nothing to see here {/if}
```
Worked.  In the current version, it doesn't.  

```
{if ! my_fluid}
```
That does work, but I don't think we want breaking behavior between 6 and 7 on something like that, and I'd expect it to work like other fields in any case.

**Comment by intoeetive** [comment]
This is not related to ExpressionEngine version, but to PHP version.

With PHP 7.4, both conditionals work. With PHP 8.1, only the second condtional works.

**Comment by intoeetive** [comment]
We also has same issue with Grid (can't find issue for that, but it has been reported several times)
