### ISSUE TITLE
php 8.1 warning - Parser/Conditional/BooleanExpression.php, line 130

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#3259]
Front-end error, php 8.1.16 / EE 7.2.14

**Error Messages**

<pre><code>
Warning
foreach() argument must be of type array|object, null given

ee/ExpressionEngine/Library/Parser/Conditional/BooleanExpression.php, line 130

    Severity: E_WARNING
</code></pre>

**Comment by intoeetive** [comment]
@jcogs-design any ideas which specific conditional in template is causing that?

**Comment by jcogs-design** [comment]
It appears to be this one 
```
{if '{iso_code}' != 'en-gb'}<option value='{iso_code}' {if get_post:language == iso_code}selected{/if}>{name}</option>{/if}
```

**Comment by intoeetive** [comment]
Is `iso_code` coming from custom field? Or an add-on?
Also, `get_post:` - is that Mo'Variables or something similar?

**Comment by jcogs-design** [comment]
`iso_code` is coming from an addon (jcogs_mts)
`get_post:` is coming from Mo'Variables
The warning appears if the get_post variable is not set (i.e. if page url is `https://add-on-dev-7.ddev.site/home/mts_tester` you get the warning, if it is `https://add-on-dev-7.ddev.site/home/mts_tester?language=fr` you don't.
HTH

**Comment by intoeetive** [comment]
I wasn't able to replicate it, but my guess would be that you see it in case where both `get_post:language` and `iso_code` are not defined or empty.

Can you add this code around line 53, right in the beginning of `public function evaluate()`:
```
if (empty($this->tokens)) {
return true;
}
```

I am not sure whether that should evalulate to `true` or `false` though - on the one hand, it's empty-to-empty comparison (true), on the other hand - both values are not set (false?)

**Comment by jcogs-design** [comment]
I'll try that, but just for the lols this also works (tested) - insert before line 130 in BooleanExpression.php
```
if(is_null($tokens)) {
    return $output;
}
```

**Comment by intoeetive** [comment]
@jcogs-design when you get time, can you give a try to the solution provided in the PR referenced here? I think it's a bit better solution because it's happening earlier in the code, but I don't have a way to test it
