### ISSUE TITLE
Unable to open any existing entries in the EE CP

### ISSUE THREAD

**Issue by karlosb** [ExpressionEngine/ExpressionEngine#326]
**Description of the problem**

I have recently upgraded an EE2 to site up to EE5.3.0 and now I am getting PHP errors when trying to open ** any ** existing entry in the EE CP. The site has no third-party modules installed. Just the standard EE install with default modules etc.

**Error Messages**

<pre><code>Exception Caught
HEX color needs to be 6 or 3 digits long
ee/Mexitek/PHPColors/Color.php:41
Stack Trace: Please include when reporting this error
	•	#0 ee/EllisLab/ExpressionEngine/Model/Status/Status.php(116): Mexitek\PHPColors\Color->__construct('blue') 
	•	#1 ee/EllisLab/ExpressionEngine/Model/Channel/ChannelEntry.php(1176): EllisLab\ExpressionEngine\Model\Status\Status->getOptionComponent() 
	•	#2 [internal function]: EllisLab\ExpressionEngine\Model\Channel\ChannelEntry->populateStatus(Object(EllisLab\ExpressionEngine\Model\Content\FieldFacade)) 
	•	#3 ee/EllisLab/ExpressionEngine/Model/Content/FieldFacade.php(105): call_user_func(Array, Object(EllisLab\ExpressionEngine\Model\Content\FieldFacade)) 
	•	#4 ee/EllisLab/ExpressionEngine/Model/Content/FieldFacade.php(115): EllisLab\ExpressionEngine\Model\Content\FieldFacade->ensurePopulatedDefaults() 
	•	#5 ee/EllisLab/ExpressionEngine/Model/Content/ContentModel.php(363): EllisLab\ExpressionEngine\Model\Content\FieldFacade->setData('closed') 
	•	#6 ee/EllisLab/ExpressionEngine/Model/Content/ContentModel.php(404): EllisLab\ExpressionEngine\Model\Content\ContentModel->setDataOnCustomFields(Array) 
	•	#7 ee/EllisLab/ExpressionEngine/Model/Content/ContentModel.php(315): EllisLab\ExpressionEngine\Model\Content\ContentModel->initializeCustomFields() 
	•	#8 ee/EllisLab/ExpressionEngine/Model/Content/ContentModel.php(147): EllisLab\ExpressionEngine\Model\Content\ContentModel->usesCustomFields() 
	•	#9 ee/EllisLab/ExpressionEngine/Model/Channel/ChannelEntry.php(657): EllisLab\ExpressionEngine\Model\Content\ContentModel->getCustomField('title') 
	•	#10 ee/EllisLab/ExpressionEngine/Controller/Publish/Edit.php(517): EllisLab\ExpressionEngine\Model\Channel\ChannelEntry->getDisplay(Object(EllisLab\ExpressionEngine\Model\Channel\Display\DefaultChannelLayout)) 
	•	#11 [internal function]: EllisLab\ExpressionEngine\Controller\Publish\Edit->entry('505') 
	•	#12 ee/EllisLab/ExpressionEngine/Core/Core.php(241): call_user_func_array(Array, Array) 
	•	#13 ee/EllisLab/ExpressionEngine/Core/Core.php(110): EllisLab\ExpressionEngine\Core\Core->runController(Array) 
	•	#14 ee/EllisLab/ExpressionEngine/Boot/boot.php(151): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request)) 
	•	#15 index.php(152): require_once('...') 
	•	#15 index.php(152): require_once('...') 
</code></pre>

**Environment Details:**
 - Version: 5.3.0
 - PHP Version 7.2.23
 - MySQL Version 5.7.28
 - OS: macOS Catalina 10.15.1
 - Web Server: Apache

**Comment by paulcripps** [comment]
Sounds like a custom fieldtype, what do you have installed? 

>

**Comment by karlosb** [comment]
Hi Paul,

Many thanks for the feedback! :-)

It's just the standard field-types that come with EE5.3.0, no custom third-party fields in place.
(I am not sure 'where' EE5.x is listing those default fieldtypes these days as in EE2 you can simply go to Addons > Fieldtypes and see the list etc).

In terms of the issue error, it appears to be the system/ee/Mexitek/PHPColors/color.php file that is throwing the error on the following lines of the code:

`		// Make sure it's 6 digits
		if( strlen($color) === 3 ) {
			$color = $color[0].$color[0].$color[1].$color[1].$color[2].$color[2];
		} else if( strlen($color) != 6 ) {
			throw new Exception("HEX color needs to be 6 or 3 digits long");
		}
`

So I have temporaily removed the 'throw new exception' line by doing the following:

`		// Make sure it's 6 digits
		if( strlen($color) === 3 ) {
			$color = $color[0].$color[0].$color[1].$color[1].$color[2].$color[2];
		} else if( strlen($color) != 6 ) {
			$color = $color[0].$color[0].$color[1].$color[1].$color[2].$color[2];
// 			throw new Exception("HEX color needs to be 6 or 3 digits long"); // this line is throwing an error on when trying to open any entry on the EE CP
		}
`

…and this seems to let any CP entry open and you can edit as usual etc.

Not sure if this is causing issues further down the line, but it's a quick fix for now until I can get some resolution on what the actual issue is.

**Comment by karlosb** [comment]
*** update ***

I've sourced the issue to the SQL under **exp_statuses**.

One of **status_id**'s rows had the word 'blue' in the 'highlight' column instead of a required three or six digital hexadecimal number (as required in the **color.php** conditional above). Not sure 'why' it was a word and not a number, but this has appeared to fix the issue. Hence I've re-instated the original conditional in the **system/ee/Mexitek/PHPColors/color.php** file, and all is working as expected!
