### ISSUE TITLE
Grid rows duplicated in Fluid field

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3261]
Really weird one.  EE 7.2.14 (but also in some older versions of 7).

I have a channel, only has 1 field- a fluid field.

Fluid field only has 1 field- grid field.

Grid field has 3 columns, a select, a text, a file field.

I start a new entry, add my grid field via fluid, add 1 row- fill out each column.  Preview.  It all looks good.

I add another grid field (not another row in existing)- repeat above, preview.  I get a php error on the preview page.  Close preview.  Save.  Entry saves ok, but there is an extra empty row added to my second grid field.

Error I saw:

<img width="1131" alt="Screenshot 2023-04-11 at 1 46 50 PM" src="https://user-images.githubusercontent.com/1181219/231253312-561dccf3-7e22-4ee5-8988-49e55c4cab3a.png">

Saved entry- not the extra empty grid row:

<img width="1781" alt="Screenshot 2023-04-11 at 2 16 15 PM" src="https://user-images.githubusercontent.com/1181219/231253611-82cdd4be-9b2f-46ed-b3c1-6f63813c7a29.png">

It's definitely quirky.  When I first tried replicating locally, I just had a text and a file field in my grid and I couldn't replicate.  The user reporting also had a manually populated select field in their grid, so I added that and I replicated!  Though- user didn't report the php error I was seeing (but that could have been error settings).

Thinking it was something specific to selects, I tried replicating with a grid field that ONLY had 1 select field in it, but I didn't replicate with that.

Not sure what's up.  Was weird.  But I can reproduce it.

**Comment by intoeetive** [comment]
I was able to replicate it without LivePreview (looks like PHP errors there though are related to malformed data posted, as shown on video)

Only happens if you have both Select and File in the Grid - and this appears to be related to JS stuff, where `disabled` attribute is mistakenly removed. I'm attaching video https://www.dropbox.com/s/1ek308o6sairng4/Rec_15.29.52%2020230412.mp4?dl=0
