### ISSUE TITLE
TMPL changes changed add-on behaviour

### ISSUE THREAD

**Issue by gilbert-hop** [ExpressionEngine/ExpressionEngine#3272]
I was working on upgrading an add-on from EE6 to EE7, and I noticed that the simple template parsing method stopped working in the new environment. I tracked it down to the assembly of plugins that get used in `legacy/libraries/Template.php` around `// Nested Plugins...`. Basically, in the foreach of `fetch_addons`, the `$this->plugins` is under an elseif and add-ons don't get added to the `$this->plugins` if it `hasModule()`. Modifying the logic to just `if` by Itself resolved the issue. Any particular reasons it needs to be in if/elseif?

This works for me.
```php
    /**
     * Fetch Add-ons
     *
     * Gathers available modules and plugins
     *
     * @return  void
     */
    public function fetch_addons()
    {
        $addons = ee('Addon')->all();

        foreach ($addons as $name => $info) {
            if ($info->hasModule()) {
                $this->modules[] = $name;
                if ($info->isInstalled()) {
                    $this->module_data[ucfirst($name)] = $name;
                }
            }
            if ($info->hasPlugin() && $info->isInstalled()) {
                $this->plugins[] = $name;
            }
        }
    }
```

**Comment by intoeetive** [comment]
@gilbert-hop while plugins in EE are still a thing, we usually recommend to use module instead.

Once the plugins became installable thing, there is no advantage in using those - and with addition of CLI and installer classes modules are just as easy to developer as the plugins in their time.

If you have a plugin and a module in same add-on package, you might get into template parser issues sometimes because of duplicate names.

So my recommendation here, since you already have the module, would be to move plugin methods into the module file. Or if for some reason you need the plugin to stay as plugin, move it to separate package.

**Comment by gilbert-hop** [comment]
@intoeetive The logic is actually all in the module file. The thing is, I need my add-on to work the same around the code:
```php
// Nested Plugins...
                if (in_array($this->tag_data[$i]['class'], $this->plugins) && strpos($this->tag_data[$i]['block'], LD . 'exp:') !== false) {
                    if (!isset($this->tag_data[$i]['params']['parse']) or $this->tag_data[$i]['params']['parse'] != 'inward') {
                        $this->log_item("Nested Plugins in Tag, Parsing Outward First")
```
If my add-on is not added to the `$this->plugins`, this bit of code will not run, and the behaviour is different from EE6.

Would you agree to join `$this->plugins` and `$this->modules` in that if statement to check nested plugins?

**Comment by intoeetive** [comment]
We actually have same code in EE 6.4...

But I think I understand the issue. While we don't encourage having plugin and module in the same package, we also don't want to make things that worked before to stop working. 

I think it would be safe for us to remove `else`

**Comment by gilbert-hop** [comment]
Hey @intoeetive, thanks for making that change. However, I'd like to point out that even if I have this a module-only add-on, I'll still face the same issue because in the code I shared earlier
```php
// Nested Plugins...
                if (in_array($this->tag_data[$i]['class'], $this->plugins) && strpos($this->tag_data[$i]['block'], LD . 'exp:') !== false) {
                    if (!isset($this->tag_data[$i]['params']['parse']) or $this->tag_data[$i]['params']['parse'] != 'inward') {
                        $this->log_item("Nested Plugins in Tag, Parsing Outward First")
```
If `in_array($this->tag_data[$i]['class'], $this->plugins` is not satisfied, the parse order would be wrong for our add-on. Another way to resolve this is by adding to check if the tag class is in the `$this->modules` array. If modules should behave differently in the templating engine, please point me in the right direction to parse outward.

**Comment by intoeetive** [comment]
I've been thinking about that, but isn't that the code that exists in previous EE version, so your addon really works the same?

**Comment by gilbert-hop** [comment]
In the previous versions, our add-on was added to the `$this->plugins` so that logic would run. I'm saying that if we're going to do away with plugins and only have modules, the bit of code that I shared should be modified to include the `$this->modules` so that the same logic that applied for the plugins would also apply for the modules to parse tags outward if nested tags are found.

**Comment by intoeetive** [comment]
I think that we can't safely change that without possibly breaking other people's setups with module tags inside module tag - as the parsing order will change for everyone

**Comment by gilbert-hop** [comment]
I see. And I went back to the older version of Template.php, and I can see that the logic for those 2 is separated. In that case, I think if you want to remove `plugins` from the EE template system and move forward with modules only, developers should have a way to define whether their nested module tags should be parsed inward or outward in the `mod.` methods.
I did try to run another Template engine to parse the tag_data and wasn't successful. Maybe you have some tricks up your sleeves that you can share :D?

**Comment by intoeetive** [comment]
Sorry to say I have nothing in my sleeves :(

I'd say that if you need to rely on that specific parsing order - keep using plugins. They will not be removed in v6 or v7, and even if we decide to completely move away from those in later versions - there will be migration path etc.

We definitely need to address parsing order between add-ons in the future, like a way for developers to define parsing order, or a way to more precisely define parsing order in templates. But that's not happening soon.

Feel free to create a discussion  for this here on GitHub, so we could learn the specific needs from the community (and maybe get some ideas)

Thank you!
