### ISSUE TITLE
Retain title for collapsed Grid Rows

### ISSUE THREAD

**Issue by creativearc-paul** [ExpressionEngine/ExpressionEngine#3273]
In EE6 and 7, when a Grid field has collapsed rows, there's no title or identifier to distinguish what that row represents.

In the attached image, there are 3 grid rows, one is titled 'Jim'. When they are collapsed, the contents become difficult to manage, particularly when there are many rows.

Maybe it's a "row display name" or "row summary" name in cases where there isn't an obvious preview.

<img width="967" alt="grid-collapse" src="https://user-images.githubusercontent.com/224037/231873384-3009d48e-f999-4bc9-a651-eace875b8461.png">

**Comment by intoeetive** [comment]
@creativearc-paul we already have request for this, can you add a comment there instead? https://github.com/ExpressionEngine/ExpressionEngine/discussions/3262

Closing as duplicate
