### ISSUE TITLE
Fluid fields are not working on multi site (EE 5.3.0)

### ISSUE THREAD

**Issue by Havsvik** [ExpressionEngine/ExpressionEngine#328]
Hi,

When we reuse a Fluid field in another channel on a different site on our multisite installation, we get the following error in the console:
```TypeError: Cannot read property 'label' of undefined```

It appears in the following file on line 171:
<pre><code>
admin.php?S=0&D=cp&C=javascript&M=combo_load&ui=core,widget,mouse,position,sortable,dialog,button&plugin=ee_interact.event,ee_broadcast.event,ee_notice,ee_txtarea,tablesorter,ee_toggle_all,nestable&file=react/react.min,react/react-dom.min,json2,underscore,cp/global_start,cp/form_validation,cp/sort_helper,cp/form_group,cp/modal_form,cp/confirm_remove,cp/fuzzy_filters,components/no_results,components/loading,components/filters,components/filterable,components/toggle,components/select_list,fields/select/select,fields/select/mutable_select,fields/dropdown/dropdown&v=1571128170
</code></pre>

This results in fluid fields being unusable (nothing happens when we try to add new fluid content)

The steps we have done:
- Create fluid field
- Add an additional site to our multi site
- Create channel on the new site with the fluid field
- Get error in the console when creating an entry in the new channel

**Environment Details:**
 - Version: 5.3.0
 - PHP Version 7.0.33
 - MySQL Version 10.2.26-MariaDB
 - OS: Linux
 - Web Server: Apache

**Possible Solution**
We think it may be caused by duplicate jquery files.

**Comment by robinsowell** [comment]
Turns out it was related to this nefarious bug: https://github.com/ExpressionEngine/ExpressionEngine/issues/78

File upload directories are site specific, so if you have a file field and a specific directory assigned to it, it's not going to be usable cross-MSM.
