### ISSUE TITLE
Unable to Save in Expression Engine

### ISSUE THREAD

**Issue by npitkin** [ExpressionEngine/ExpressionEngine#329]
I am seeing this error at the top of my screen and we are unable to save changegs. 

Warning
An unexpected error occurred attempting to download the current ExpressionEngine version number. Please visit your Download Account to verify you are on the current version. If this error persists, please contact your system administrator
![update image](https://user-images.githubusercontent.com/57729494/68801186-27d24300-0621-11ea-8c30-13d9ec04ffa7.png)

**Comment by robinsowell** [comment]
That looks very odd- I wonder if there was a javascript error that somehow caused it.  Which would explain why it wouldn't close, either.

I don't think it's a general bug, as I haven't seen anything quite like it.
