### ISSUE TITLE
RTE extended variable conditional issue in fluid fields

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3292]
EE 7.2.14

The 'has_excerpt' conditional available to RTE fields works fine outside of a fluid field.  Inside fluid, it always returns false unless you add braces to the variable- see below:

```
{my_fluid}
  {my_fluid:rte_rad}
       excerpt: {content:excerpt}
   
      {if '{content:has_excerpt}' == 'y'}
      <h1>Read More</h1>
      {/if}    
    
  {/my_fluid:rte_rad}
{/my_fluid}
```
So when in a fluid field, the RTE has_excerpt conditional needs to have the variable braced in order to parse properly.  Otherwise it will never be true.  This may/may not be fixable.  If not fixable, we'll want to drop in a note in the docs.  There are other variables that requiring bracing in fluid- see https://docs.expressionengine.com/latest/fieldtypes/fluid.html#variables

I confirm the behavior locally, I'm just not sure whether it's a bug or a documentation issue.

**Comment by intoeetive** [comment]
@robinsowell the modifiers on the fieldtype are parsed later in the code and so the braces would be needed.

~Can you take care of adding the note to the docs?~

n/m, adding docs myself and assigning you to review
