### ISSUE TITLE
Content of channel not displayed 

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#3297]
**Description of the problem**
The content of a channel is not displayed when using search. Work for some but not for some

Content not displayed
https://apps.xproline.io/changelog/spamout
Content displayed
https://apps.xproline.io/changelog/infomenu

**How To Reproduce**
using this tag for search  

` search:fd_category_faqs="{last_segment}"`

**Error Messages**
None

**Environment Details:**
 - Version: 7.2.15
 - PHP Version 8.1.17
 - MySQL Version 5.7
 - OS:  Linux
 - Web Server: Apache

Was working in previous versions of eemcs. Found the problem on 7.2.14 and upgraded to 7.2.15

**Comment by intoeetive** [comment]
Can you provide some guidance on how we could replicate this?

**Comment by digicali** [comment]
Adding dynamic="no" to the channel search solved the problem. Weird that it worked for some content and not for others.

**Comment by digicali** [comment]
This is the code used: ` {exp:channel:entries status="open" channel="ch_changelog" orderby="date" sort="desc" search:fd_category_faqs="{last_segment}" dynamic="no"}`
fd_category_faqs is a select dropdown field used by two channels

**Comment by intoeetive** [comment]
If adding `dynamic="no"` solves the issue then you likely have entry with url_title that matches `last_segment`. This is expected behavior
