### ISSUE TITLE
1054 Unknown column error when upgrading from 3.5.15 to 4.3.6

### ISSUE THREAD

**Issue by nep** [ExpressionEngine/ExpressionEngine#33]
**Description of the problem**
Getting a MySQL error when upgrading from 3.5.15 to 4.3.6.  It appears to be dying at the 4.0.0 installer file step, relating somehow to the Member Group model.

**How To Reproduce**
1. Create a 3.5.15 site.
2. Try to upgrade it to EE 4.3.6
3. See error

**Error Messages**
<pre><code>
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ee_m_MemberGroup_member_groups.can_manage_consents' in 'field list':
</code></pre>

**Environment Details:**
 - Version: 4.3.6

**Possible Solution**
If I create the column in the exp_member_groups table myself before I run the upgrade, it solves the issue, but there's got to be a better way.

can_manage_consents char(1) NOT NULL DEFAULT 'n',

**Additional context**
I suggest this should be back-fixed to 4.x

**Comment by jmathias** [comment]
I followed your steps to reproduce, and did not replicate the error. Is there a step missing?

I installed a copy of 3.5.15, then upgraded it to 4.3.6, I did not get an error, and the upgrade completed successfully.

**Comment by kevincupp** [comment]
Heh, "Create a 3.5.15 site" is pretty nebulous. Luckily we got more specific steps earlier this week and already committed a fix: https://github.com/ExpressionEngine/ExpressionEngine/commit/a74a2d0e76c52b8b60de499fed3ace15faae8df6
