### ISSUE TITLE
Field names in Publish Layout

### ISSUE THREAD

**Issue by stoneandstorm** [ExpressionEngine/ExpressionEngine#331]
**Is your feature request related to a problem? Please describe.**
When creating or editing a Publish Layout and field names are equal it's now unclear what field is what. For example I like to create multiple Title fields for SEO, Navigation or overwriting the Tiltle on a page. With tabs I separate the fields for a clean and intuitive interface. But when creating the layout I see multiple title fields with the same name and type.

**Describe the solution you'd like**
I like to see the field short name to be added in the fields. For example:
![ee_shoprtname_layout](https://user-images.githubusercontent.com/5113702/69133707-a3674080-0ab6-11ea-8490-aa4b831e4430.JPG)
_Here you can see the short name on the right._

**Comment by Jordan-Ellis** [comment]
Implemented in EE6!
