### ISSUE TITLE
Selecting template in CP selects multiple templates

### ISSUE THREAD

**Issue by bankarbetsgivarna** [ExpressionEngine/ExpressionEngine#334]
### Description of the problem
Possibly catastrophic javascript bug in CP selects multiple templates when clicking on a template to select it. This can lead to unintended deletion of templates. (I have seen this behaviour in the CP for years.)

### How To Reproduce
Steps to reproduce the behaviour:

- Navigate to a template group with more than one template
- Select any template that is not at the top of the list

The bug only appears when the page has been loaded or refreshed. Refresh page to reproduce.

### Video
https://www.dropbox.com/s/6v53a74f3rl7jj3/Template%20Manager%20_%20ExpressionEngine%20-%20Google%20Chrome%202019-11-28%2009-26-02.mp4?dl=0 

### Environment Details:

- EE version 5.3.0
- PHP version 7.3.11
- MariaDB version 10.2.26
- Apache/2.4.41 on FreeBSD 12.0-RELEASE-p12
- Google Chrome version 78.0.3904.108 64-bit

**Comment by Jordan-Ellis** [comment]
Fixed in EE6!
