### ISSUE TITLE
[EE6] Template search can return spurious results when search term contains underscores

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#3348]
When the search term used for a template search in the CP contains an underscore, the underscore appears to match other characters (maybe any character?). For example, the search term `hello_goodbye` matches `hello_goodbye` (as expected), but also `hello goodbye` (wrongly), and `hello-goodbye` (also wrongly). The effect is that template search can give spurious results, in addition to the correct ones.

I don't know if this is caused by sanitization of the search term, but the fact that the standard form for EE variables uses underscores means the issue isn't an obscure one. A real example: I have a custom field called `lab_team`. If I search for this field in templates, I also see results for `lab team` and `lab-team` (in content text). What this means is that I have to check the search results by hand to make sure that the spurious results aren't actually real results, creating uncertainty and additional work.

[Tested using EE6.4.10]

**Comment by intoeetive** [comment]
Looks more like a feature, but is probably a bug :)

**Comment by intoeetive** [comment]
Appears this is also issue in few other places where search is used
