### ISSUE TITLE
Ampersand in Channel Entry Search filter causes Invalid GET Data error on second search

### ISSUE THREAD

**Issue by mindpixel-labs** [ExpressionEngine/ExpressionEngine#335]
**Description of the problem**
When entering an Ampersand character into a channel's filter search form and then doing a second search after produces an **Invalid GET Data** error to be returned on the second search.

**How To Reproduce**
1. Go into a channel's main listing. Edit > a channel name
2. In the channels search box, enter in a search term that contains an ampersand like **Title & Test**
3. After the first search has been completed, try searching for anything again. It will return an error of Invalid GET Data.

**Error Messages**
Invalid GET Data

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: [e.g. 5.2.0]
 - PHP Version [e.g. 7.2.25]
 - MySQL Version [e.g. 5.7]
 - OS: [macOS]
 - Web Server: [Apache]

**Possible Solution**

**Additional context**

**Comment by robinsowell** [comment]
This is fixed as of 5.4 (currently stability), though I'm not sure of the pull request, so could have been earlier. Closing.
