### ISSUE TITLE
str_replace deprecation issue on FieldModel

### ISSUE THREAD

**Issue by robsonsobral** [ExpressionEngine/ExpressionEngine#3350]
**Description of the problem**

In case of an empty variable, we get a warning.

**How To Reproduce**

1. Create a member field with type textarea
2. I'm not sure, but I guess I changed the **Text formatting** setting afterwards. I'm sorry! I'm not sure;
3. Leave the field empty for the member being tested;
4. output the field using `{exp:member:custom_profile_data}`

A code sample follows:

```html
{exp:member:custom_profile_data member_id="{embed:member_id}" cache="yes"
refresh="30" cache_prefix="h-card--{embed:member_id}"}
        {if mini_bio}
          <div class="p-note h-card__p-note">
              {mini_bio}
          </div>
        {/if}
{/exp:member:custom_profile_data}
```

**Error Messages**

```
Deprecated
str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated

ee/ExpressionEngine/Model/Content/FieldModel.php, line 516

    Severity: E_DEPRECATED
```

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 7.2.15
 - PHP Version 8.2.4
 - MySQL Version [e.g. 5.7]
 - OS: Linux
 - Web Server: nginx

**Possible Solution**

This can be fixed by replacing:

```
        if ($tag) {
            return str_replace(LD . $tag . RD, $data, $tagdata);
        }
        $tag = $this->field_name;
        if ($modifier) {
            $tag = $tag . ':' . $modifier;
        }

        return str_replace(LD . $tag . RD, $data, $tagdata);
```

With:

```
        if ($tag && $data !== null) {
            return str_replace(LD . $tag . RD, $data, $tagdata);
        }
        $tag = $this->field_name;
        if ($modifier) {
            $tag = $tag . ':' . $modifier;
        }

        return $data !== null
            ? str_replace(LD . $tag . RD, $data, $tagdata)
            : $tagdata;
```

**Additional context**

I'm sorry, but I can't dig more into it right now.

**Comment by intoeetive** [comment]
@robsonsobral what would be the steps to replicate this? Is this coming from an add-on or EE templates?

**Comment by robsonsobral** [comment]
It's on the member module, @intoeetive . I updated the previous message.
