### ISSUE TITLE
inconsistency with Relationship fields and “Display Entry IDs?” toggled on

### ISSUE THREAD

**Issue by aasun** [ExpressionEngine/ExpressionEngine#3351]
**Description of the problem**
With Relatioship fields and the setting “Display Entry IDs?” toggled on, I’m seeing inconsistency here.  I have a grid field with a relationship field and it’s showing the entry ID there.  But, I also have a relationship field outside of a grid field and it’s not showing the entry ID there.  It does show the entry ID in the dropdown, just not in the entry form once the relationship is made..

In the screenshots you can see the first one is in a grid field, and the relationships she the entry id.. But, in the second one, that's a root level relationship field, and the entry ids are not showing.
![grid-relatioship](https://user-images.githubusercontent.com/5115281/235513289-c649c4f9-1bf6-4702-9da5-d15f5c877173.png)
![root-relationship](https://user-images.githubusercontent.com/5115281/235513299-04580c79-b91d-4584-bee0-8d02d738d02a.png)

**Comment by Yulyaswan** [comment]
I could not reproduce this issue for either version 6 or version 7

**Comment by aasun** [comment]
This is in EE 7.   I'm definitely having this problem.  I have a single relationship field that allows multiple relationships.. set to show entry ID..  It does show the entry ID in the dropdown when choosing the relationship, but once the relationship is chosen, it only shows the title and channel of the child.. It does not show the related child's entry id.. (though, it does in when the relationship is in a grid field).

**Comment by aasun** [comment]
I've tried toggling off the "show entry id" option, saving the field, then toggling it back on and saving again.. No change..  This is a fresh install of EE 7...

**Comment by harthouse** [comment]
I could not reproduce this issue on either ee6 or ee7

**Comment by intoeetive** [comment]
@aasun which EE version is this? I think our current UI is slightly different - the channel names show below the title, not on the right side. So maybe some of the files were not updated properly, or you need to update

@Yulyaswan while I wasn't able to replicate the issue, I noticed that when using "defer field" option, the entry_id's are not shown (though the channel name is)

**Comment by aasun** [comment]
I see you closed this (I missed your previous question. Sorry about that).

I turned ON "Defer field initialization" and now I get an updated interface for the Multi-select relationship field that DOES show the entry ID AND the entry status..  If I turn OFF "Defer field initialization" then I still see the exact same interface as my second screenshot above..  

Below is what I see with "Defer field initialization" turned ON..  (this is EE 7.3.10)

**Comment by aasun** [comment]
<img width="677" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/5115281/535bd5cd-3444-43c6-9fcc-ee2d92466c37">

**Comment by intoeetive** [comment]
@aasun is there anything specific about this field or your setup in general? Is this stand-alone field, or inside Grid / Fluid? Using any publish-related add-ons that might interfere? Lastly, using MSM?
