### ISSUE TITLE
Entries with url_title of "n" not displaying

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#337]
**Description of the problem**
I've found that trying out a specific Entries' data, whose url_title is "n" isn't working.
I need to use this url_title as it relates to the North London postcode region.

**How To Reproduce**
{exp:channel:entries channel="postcode" url_title="n" dynamic="no"}
	{title}
{/exp:channel:entries}

**Error Messages**
Just a blank output.

**Environment Details:**
 - Version: 5.3.0
 - PHP Version 7.1

**Comment by Havsvik** [comment]
Seems like 'n' is changed to 'no' in the database query.

Small hack: Try adding a `|`, like `url_title="n|"`, it should now be treated as an array in the database query, and is not changed to 'no' :)

```
{exp:channel:entries channel="app_content" url_title="n|" dynamic="no"}
{title}
{/exp:channel:entries}
```

Hope this helps!

**Comment by ic360-com** [comment]
Hi Havsviik,
An interesting workaround. Yes, that has worked for me.  :-)
Hopefully this is something they can fix in the core EE software though.
Best wishes.

**Comment by litzinger** [comment]
This is actually an issue with ee()->TMPL->fetch_param(), not the database query.

```
public function fetch_param($which, $default = FALSE)
	{
		if ( ! isset($this->tagparams[$which]))
		{
			return $default;
		}
		else
		{
			// Making yes/no tag parameters consistent.  No "y/n" or "on/off".
			switch($this->tagparams[$which])
			{
				case 'y'	:
				case 'on'	:
					return 'yes';
				break;
				case 'n'	:
				case 'off'	:
					return 'no';
				break;
				default		:
					return $this->tagparams[$which];
				break;
			}
		}
	}
```

**Comment by ic360-com** [comment]
Thanks Brian - this is way out of my skillset, so hopefully a fix (or something) can be included in a future EE update. :-)
