### ISSUE TITLE
Error thrown on every page after updating to 7.2.17

### ISSUE THREAD

**Issue by aebgreene** [ExpressionEngine/ExpressionEngine#3371]
**Description of the problem**
I updated EE to 7.2.17 today and now am receiving this error at the top of every page, even with the settings set to hide all errors. 

**Error Messages**

Warning Undefined array key "grid_min_rows" ee/ExpressionEngine/Addons/grid/ft.grid.php, line 180
Severity: E_WARNING

Warning Undefined array key "grid_max_rows" ee/ExpressionEngine/Addons/grid/ft.grid.php, line 181
Severity: E_WARNING

 **PHP Version 8.1.18**

**Screenshots / Videos / Template Code**
<img width="1541" alt="to-upload" src="https://user-images.githubusercontent.com/81712652/236544329-4226833d-9c13-4eaa-b028-87fbab0b9e7d.png">

**Comment by intoeetive** [comment]
@aebgreene thank you for reporting!

For the time being, re-saving your Grid fields settings should make the error go away
