### ISSUE TITLE
When Deleting a Member, Member Select to Reassign Entries does not populate

### ISSUE THREAD

**Issue by dougblackjr** [ExpressionEngine/ExpressionEngine#3384]
**Description of the problem**

EE7 site that we're trying to delete a member. When trying to delete the member, it pulls up the modal to reassign entries. However, it does not populate the list of Members.

**How To Reproduce**
1. Create site with 1000+ members (it's a LOT).
2. Go to delete one of them.
3. View select for reassignment

**Error Messages**
No error messages. No error in the ajax call, nothing in the console.

**Screenshots / Videos / Template Code**
![Screenshot from 2023-05-11 13-18-43](https://github.com/ExpressionEngine/ExpressionEngine/assets/6020323/415abe66-9d27-4e0a-aba4-bc6d39f715b6)

I did see the `data-react-select` serialized data on the element in the code. That output a properly form object when using unserialize:
![Screenshot from 2023-05-11 13-23-19](https://github.com/ExpressionEngine/ExpressionEngine/assets/6020323/054252ae-bba8-4e30-8479-3b2cc975a864)

**Environment Details:**
 - Version: 7.2.19
 - PHP Version 8.0.x
 - MySQL Version 8.0
 - OS: Linux
 - Web Server: nginx, but prod has same on Apache

**Comment by intoeetive** [comment]
I can confirm this happening - @Yulyaswan I hope there is an easy fix ;)

You can use heavy_load/many_members Cypress test to quickly create a lot of members, and then turn on "include in authors list" for Members role. Assign an entry to one of members, and then try to delete that member

**Comment by wilsones-berkeley** [comment]
Hello,

I wanted to flag that I am still experiencing this issue on EE 7.4.10.

### Description of Problem
Same as initially reported.

### How to reproduce
Same as initially reported.

### Error messages
Same as initially reported.

### Environment Details
- Version 7.4.10
- PHP Version 8.2.x
- 10.5.17-MariaDB
- OS: Linux
- Web server: Nginx

### Possible Fix
I temporarily fixed this issue by pasting the same lines of code from commit [28c8566](https://github.com/ExpressionEngine/ExpressionEngine/commit/28c85669905ea1771676f1c0288f2cbb14eac41a) under the more specific jQuery selector for this modal (`a[rel="modal-confirm-delete"]`):

```diff
--- a/html/themes/ee/asset/javascript/compressed/cp/confirm_remove.js
+++ b/html/themes/ee/asset/javascript/compressed/cp/confirm_remove.js
@@ -153,6 +153,10 @@ $(document).ready(function () {
                        $.post(ajax_url, $(modalIs + " form").serialize(), function(data) {
                                $(modalIs + " .ajax").html(data);
                                Dropdown.renderFields();
+
+                               if ($('div[data-select-react]').length) {
+                                       SelectField.renderFields();
+                               }
                        });
                }
 
```
