### ISSUE TITLE
EE version check tooltip appears under some elements

### ISSUE THREAD

**Issue by obfuscode** [ExpressionEngine/ExpressionEngine#34]
**Description of the problem**
The EE version check tooltip box appears under the third party add-ons table heading row (z-index issue).

**How To Reproduce**
1. Go to Add-on Manager page
2. Click the EE version badge

**Screenshots / Videos / Template Code**
<img width="240" alt="overlap" src="https://user-images.githubusercontent.com/2160089/49330060-4bf35c00-f557-11e8-9565-2805f5b40c38.png">

**Comment by jmathias** [comment]
Thanks @obfuscode I'll get a fix in.
