### ISSUE TITLE
Automatic disable reorder when maximum rows is one

### ISSUE THREAD

**Issue by stoneandstorm** [ExpressionEngine/ExpressionEngine#340]
**Is your feature request related to a problem? Please describe.**
It's a bit meaningless to reorder a single row when the **maximum rows** is 1 of a grid field.
![ee_grid_reorder_one](https://user-images.githubusercontent.com/5113702/71065539-b03c8a00-2171-11ea-97d3-84c67c882b9c.JPG)

**Describe the solution you'd like**
So a little tweak for a little more attention to detail :) I like to see that when the **maximum rows** is 1 of a grid field that the _reordering of rows_ option is disabled.

**Comment by Jordan-Ellis** [comment]
Fixed in EE6!
