### ISSUE TITLE
Custom field create/edit shows stray instruction

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3438]
Testing EE 7.3.0 dp

Checkbox field create/edit form shows 

<img width="765" alt="Screenshot 2023-05-23 at 1 38 54 PM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/1181219/a9a85090-3b69-47a6-b798-754c588ee645">

That '* You may only select places where subfolders are not allowed' bit doesn't make sense, and probably isn't supposed to show there.

Note- seeing it with color picker too- probably universal.

**Comment by intoeetive** [comment]
@robinsowell this is not coming from EE. I think might be one of your add-ons - but also please "view source" and check if there are any PHP errors that are there but not visible
