### ISSUE TITLE
File field can break publish page in MSM

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3439]
Testing 7.3 and I LOVE you can have file directories shared across sites.

BUT in testing, I was reminded how it's not a great experience if you assign a file field to a channel and the file field does not have access to a directory on that site.  It just breaks itself and all of the js:

<img width="871" alt="Screenshot 2023-05-23 at 2 33 31 PM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/1181219/2af35cfb-598c-4957-9204-e603360df09d">

This isn't really a new bug, but with the ability to use directories across msm sites, maybe either do not even show fields as in the field options if they aren't valid on the site or show a warning or something.  But it was a bad user experience and for a moment I thought there was some new bug introduced.

**Comment by intoeetive** [comment]
@robinsowell I'm thinking maybe we should still allow assignment of field to channel (I often assign fields first and only then create upload directories) - but show some notice instead of field it can't be rendered because of missing permissions. Just extra checks in the `ft` itself

**Comment by robinsowell** [comment]
> but show some notice instead of field it can't be rendered because of missing permissions. Just extra checks in the ft itself

Sounds good.  Key point is to not have it breaking things and people have no idea why things don't work.
