### ISSUE TITLE
localhost error get_magic_quotes_gpc

### ISSUE THREAD

**Issue by Sceko** [ExpressionEngine/ExpressionEngine#344]
Deprecated
Function get_magic_quotes_gpc() is deprecated
ee/legacy/core/Input.php, line 970

Severity: E_DEPRECATED
Deprecated
Function get_magic_quotes_gpc() is deprecated
ee/legacy/core/Input.php, line 970

Severity: E_DEPRECATED
Deprecated
Function get_magic_quotes_gpc() is deprecated
ee/legacy/core/Input.php, line 970

Severity: E_DEPRECATED

**Comment by MrJustPeachy** [comment]
Hi,

I was installing ExpressionEngine and used PHP 7.4.1 and got these errors too. After switching to PHP 7.3.13 I was able to make the errors go away. It seems that some of the legacy code hasn't been updated to support PHP 7.4+ since they deprecated those functions since then.

**Comment by robinsowell** [comment]
Yep, MrJustPeachy nailed it.  We're working on a few php 7.4 issues now, and this is one!

**Comment by iammattmartin** [comment]
Is there a way to silence these errors for the interim as they only appear to impact us on the admin side.

**Comment by robinsowell** [comment]
Yes- it's the debug, you can hide PHP errors from everyone, including superadmin.  I'd definitely switch that back once we get an update out.

**Comment by robinsowell** [comment]
Closing as fix was merged and released: https://github.com/ExpressionEngine/ExpressionEngine/pull/348
