### ISSUE TITLE
Field group editing 'Remove' vs. 'Delete' and 'Remove from Group'

### ISSUE THREAD

**Issue by rowansentesy** [ExpressionEngine/ExpressionEngine#345]
**Is your feature request related to a problem? Please describe.**
We had an issue with a client site related to confusion in the EE CP when working with Fields and Field Groups. The ?/cp/fields&group_id=XX view has checkboxes for the fields. In the 'With Selected' dropdown that appears when a field is selected, there is ONLY an option for 'Remove'. This is quite confusing. I accidentally 'Removed' a field from the site when all I was trying to do was remove it from the field group. This created multiple hours of work recovering lost data associated with this confusion. 

**Describe the solution you'd like**
When 'destructive' edits are being done, the term should be 'Delete' not 'Remove'. When I 'remove' something, It makes sense that I am taking it out of a group, not obliterating the thing. 
On the ?/cp/fields&group_id=XX page, when an item is checked, there should be another option in the dropdown for 'Remove from Field Group'. 
I suggest that the options should be:
- 'Remove from Field Group' 
- 'Delete'
That would be much clearer. 

When 'Delete' is selected, the button could change from a green 'submit' to a RED 'DELETE PERMANENTLY'.

Clicking on the 'pencil' and having to 'uncheck' the field to remove from group is not intuitive or as easy to do as it could/should be. 

This functionality should be available on the main field group page. 

**Describe alternatives you've considered**
None, this should be clarified in the software. 

**Teachability, Documentation, Adoption, Migration Strategy**
This would be much simpler for Users, and would clarify ambiguity about 'Remove' ≠ 'Delete'. 
It would be worth revisiting the use of 'Remove' in EE, to maintain consistency. 

- [ Y ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by Jordan-Ellis** [comment]
Hi @rowansentesy,

Man, sorry to hear you lost that field's data!

This has been fixed in EE6. All the "remove" wording has now been replaced with the more appropriate "delete", including on the field groups page. The confirm button, and the dialog itself is now red, and way more dangerous looking!

Since the "Remove from Field Group" option is a separate feature from the wording change, would you mind opening a new issue for it?

Thanks!

**Comment by rowansentesy** [comment]
Hey Jordan,

Thanks for the email about this. Sounds like your changes in EE6 will help
clarify the severity of deleting fields for any other poor souls.

I will create a new issue for the other item for sure.

I appreciate your help.

Rowan

[image: photo]
*Rowan Sentesy*
Web Developer | DJ | Event Production
CTO at Bellyfit Enterprises Inc.
m:250-857-2348 | e: rowan.sentesy@gmail.com
<http://www.facebook.com/rowan.sentesy>
<http://ca.linkedin.com/pub/rowan-sentesy/20/227/9a5>
<http://twitter.com/rowansentesy>
