### ISSUE TITLE
Uploaded images showing incorrect rotation

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3456]
7.x issue

Basically, iphones use exif data to properly oriented images.  People upload an image that looks correctly oriented and it ends up sideways.

I know this has come up before and at one point 'fixed' but the fix no longer works and it's just not a good user experience, especially for non-technical users.  I believe any resizing/alteration loses exif and the image is just wrong.  

Here's the prior fix:
https://github.com/ExpressionEngine/ExpressionEngine/pull/277

Here's prior discussion:
https://github.com/ExpressionEngine/ExpressionEngine/issues/105

Here's 
an example- I'm also including a zip of the two files.  I was testing 7.3 and used the two test files in my tests- you can see the sideways orientation ends up sideways:

<img width="1218" alt="Screenshot 2023-05-25 at 11 39 45 AM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/1181219/d5d3888d-2645-4db6-87f1-b061a912e257">

MAYBE it works with the original image (if browser reading exif) but the thumbs and file manips don't read it and strip it and you end up sideways and people end up confused.

[dylan-Images.zip](https://github.com/ExpressionEngine/ExpressionEngine/files/11566800/dylan-Images.zip)

**Comment by VarenSwaab** [comment]
As the owner of a site where members upload a lot of pics, mostly from mobile devices, this fix would be most welcome.
