### ISSUE TITLE
PHP 7.3 issue -strpos(): Non-string needles will be interpreted as strings in the future.

### ISSUE THREAD

**Issue by dankingsley** [ExpressionEngine/ExpressionEngine#346]
**Description of the problem**
I’ve been getting this warning quite a bit on one of my sites: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior. ee/legacy/libraries/channel_entries_parser/Parser.php, line 314

**Environment Details:**
 - Version: 5.3.0
 - PHP Version: 7.3
 - MySQL Version: 5.7
 - OS: macOs
 - Web Server: Apache

**Comment by robinsowell** [comment]
Thanks for the heads up!  We're getting things tightened up for php 7.4 and I'll put this on the list to hit.
