### ISSUE TITLE
Gettign fieldtype warning after upgrade Expression engine

### ISSUE THREAD

**Issue by sw-tt-jaydeepcharadva** [ExpressionEngine/ExpressionEngine#3468]
Hi there,

I have upgrade Expression engine from **5.3** to **7.2.17**. After successful upgrade of expression engine it throws the warning as mentioned in below, on page **Tools > Debug FieldTypes**:

> The following fieldtypes are found in the database, but are not actually installed properly. This will cause issues with editing channels, fields, and entries. To resolve this, either install the missing addons or remove the fields from their tables.
> - nolan (exp_grid_columns)
> 

Here I am attaching the sceenshot for your reference
 
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/68269830/55a80691-a463-496a-8bc1-654557428489)

Can you please check and update?

**Comment by intoeetive** [comment]
@sw-tt-jaydeepcharadva it looks like "nolan" fieldtype (which is third-party add-on) is not installed properly. I think this was a read-only fieldtype of EE2 so not having it will not influence a lot, but you would do better if you resolve the issue by updating to version that's compatible with EE7 (if it exists) or removing it completely.

I am closing this issue as it is support request and not bug report.

If you're looking for community support, please post in [ExpressionEngine Slack](https://expressionengine.com/blog/join-us-in-slack) or [Forums](https://expressionengine.com/forums)

You may also consider getting one of our [paid support plans](https://expressionengine.com/support)
