### ISSUE TITLE
Not able to uninstall addon

### ISSUE THREAD

**Issue by sw-tt-jaydeepcharadva** [ExpressionEngine/ExpressionEngine#3493]
Hi,

I am trying to uninstall MX Tool Box addon from my EE7. But i am getting below error, while uninstall it.

![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/68269830/c5a317d8-2a5d-4674-92df-18c2973f082e)

As i am able to uninstall above addon on my old version of EE5.3, but not able to do it on newer version. I got one [reference link](https://expressionengine.com/forums/topic/253101/solved-exp_module_member_groups-doesnt-exist-on-deleting-module) to do above things manually, but i think it's a bad practice to do it manually. Can you please suggest is it a better way to do that or any other options for it?

**Comment by intoeetive** [comment]
@sw-tt-jaydeepcharadva it looks like the add-on is not compatible with EE7. If you're not feeling confident following the steps for manual uninstallation, contact the add-on developer.

Closing this issue as external by nature

**Comment by sw-tt-jaydeepcharadva** [comment]
Hi @intoeetive,

Just confirm that this table name: **exp_module_member_roles** is renamed from this name: **exp_module_member_groups** in latest version of Expression engine 6 right?

**Comment by intoeetive** [comment]
Yes, in ExpressionEngine 6.0.0 `module_member_groups` has been replaced with `module_member_roles`

**Comment by sw-tt-jaydeepcharadva** [comment]
okay thank you
