### ISSUE TITLE
template variables can not be used in redirect tag's path parameter

### ISSUE THREAD

**Issue by tokuroglu** [ExpressionEngine/ExpressionEngine#35]
When a template variable is used in the redirect tag, I get the braces encoded around the variable in the generated redirect URL like **%7Bthe_variable%7D**. And hence the error: **Error: The URI you submitted has disallowed characters.**

**Comment by kevincupp** [comment]
This is more a general behavior of the parser, template variables are parsed at the very end, after modules are parsed, would be difficult to change without fundamentally changing the parser which is risky and time consuming. Can you use a template partial instead? Or a `preload_replace` variable?
