### ISSUE TITLE
Template group redirect issue after syncing a file directory with the same name as template group.

### ISSUE THREAD

**Issue by ataucher** [ExpressionEngine/ExpressionEngine#3512]
Prefacing this issue with the fact that this bug only appeared after syncing a file directory.
This is a brand new build so nothing more than the following as part of the build:

**Before bug steps:**
- Added a template group named "products", within it added two templates.
- Templates within that products group: index, template1, template2 – all 3 just have a simple line of plain text.
- Added a file directory named "products", set proper directory URL and path. Did not add any images yet. File directory is in images/uploads/products.
- Tested templates at myurl.com/products/template1 and myurl.com/products/template2 and everything worked as it should.

**After bug steps:**
- Manually added images via Finder to the product directory (not through EE) then ran a sync on that file directory to perform some image manipulations on all images. Images showed up no problem in the file manager
– Tried to again access templates at myurl.com/products/template1 and myurl.com/products/template2 but now they did not work, they redirected back to the products/index template instead.
– Changed my template group name from "products" to "product" then it worked again as it should.

Something is conflicting with that naming convention of my template group and file directory being named the same thing.
Main thing is, the issue only started after running the file sync on the directory.

I did try testing with and without index.php, and using .htaccess from EE docs. My htaccess file has worked for me for many other prior projects no problem.

EE v 7.3.2
Local dev: MAMP Pro - PHP 8.1.13 - MySQL 5.7.39 
MacOS 13.2.1

**Comment by intoeetive** [comment]
@ataucher just to make sure, your `products` upload directory - does it only share its name with the template group name, or it's actually physical folder `products` directly in your web root?

**Comment by ataucher** [comment]
Shares the same name, template group name and physical folder name is "products."
The physical folder is in /images/uploads/ not web root.

**Comment by intoeetive** [comment]
Are you using Structure here? Or other add-ons that might influenece routing?

(not replicating on a fresh install)

**Comment by ataucher** [comment]
Yes, using Structure. I do have a channel called "products" as well. In addition to Structure, Rich Text Editor and Cloud Files.
<img width="1278" alt="Screenshot 2023-06-14 at 6 12 04 AM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/1093815/48a78092-2477-4c64-a827-ce98a6cca1fc">

**Comment by intoeetive** [comment]
Can you test if applying [this fix](https://github.com/ExpressionEngine/ExpressionEngine/pull/3516/files) would solve the issue?

If not, could you send screenshot of Structure settings page?

**Comment by ataucher** [comment]
That did fix it, thanks Yuri!
