### ISSUE TITLE
`:json` modifier doesn't escape line breaks

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#3540]
EE 7.3.0

If a textarea field contains line breaks, `{field:json}` returns content as follows:

```
"test\nline break"
```
`JSON.parse()` JS method doesn't accept those line breaks and throws this error: `Uncaught SyntaxError: Bad control character in string literal in JSON`.

It looks like in JSON, line breaks are not allowed within a string value unless they are properly escaped:
```
"test\\nline break"
```

**Comment by shbchk** [comment]
Thanks to modifiers chaining (really, thanks, guys, it's great!) we have a workaround:

`{field:json:replace replace:find="\n" replace:replace="\\n"}`

**Comment by intoeetive** [comment]
`"\n"` is the valid character in JSON.

You can check by running your output string with https://jsonlint.com/

The replacing is the way to go - either in EE, or in your JavaScript code

**Comment by shbchk** [comment]
Oh. So, there are different rules about JSON in different parsers. Didn't know that, thanks!
