### ISSUE TITLE
Structure {exp:structure:nav} adding li1 tag instead of li tag

### ISSUE THREAD

**Issue by sw-tt-jaydeepcharadva** [ExpressionEngine/ExpressionEngine#3545]
Hi,

I have upgraded version of Structure addon from version 4.6.1 to version 5.3.0 in Expression engine 5.3.0. After upgrade of addon i am facing the issue like Structure navigation tag ```{exp:structure:nav}``` adding **<li1>** tag instead of adding **<li>** tag. I am adding screenshot for your'e reference: 

1. Below is the structure code which i have mentioned in my site
![structureexpnav](https://github.com/ExpressionEngine/ExpressionEngine/assets/68269830/02aaedaf-35ad-43ff-8274-3db3de93ad4d)

2. Below is the Html elements render in my browser
![inspectcode](https://github.com/ExpressionEngine/ExpressionEngine/assets/68269830/175aeb13-f0d1-4b71-bc8b-876c8a14d123)

Can you please check and update?

**Comment by intoeetive** [comment]
@sw-tt-jaydeepcharadva Structure is only shipped with ExpressionEngine 7, so you need to email EEharbor support. Also I believe latest is currently  5.3.1, not 5.3.0

@bakin1999 FYI
