### ISSUE TITLE
Need to add Addon URL in Main Menu

### ISSUE THREAD

**Issue by sw-tt-jaydeepcharadva** [ExpressionEngine/ExpressionEngine#3559]
Hi,

I would like to add my Addon url in main menu of Expression engine 5.3.0 as per below screenshot

![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/68269830/6935164d-c89c-4e88-b68f-afc5d195d88e)

Right now i have added it using Menu manager of control panel as mentioned on documentation of [Expression Engine](https://docs.expressionengine.com/v5/control-panel/settings/menu-manager.html#menu-manager), but it's adding it below the main menu.

Thank you

**Comment by intoeetive** [comment]
@sw-tt-jaydeepcharadva feel free to ask this question in EE Slack, Forums, or subscribe to one of our support plans. We don't provide support on GitHub
