### ISSUE TITLE
Safari on Mac - cant search members

### ISSUE THREAD

**Issue by paulcripps** [ExpressionEngine/ExpressionEngine#3561]
**Description of the problem / How To Reproduce**

Mac OSX, Safari Version 16.3 (18614.4.6.1.6) and EE 6.0.6

Login > left menu > Members

/system/index.php?/cp/members

**How To Reproduce**

When typing into the keyword search nothing happens even when we hit return to search.

There are no errors in web inspector.

**Environment Details:**
 - Version: 6.0.6
 - PHP Version PHP Version 7.4.33
 - OS: Mac
 - Web Server: Apach and or MAMP

**Comment by PaulBaileyAtChan** [comment]
This should be fixed in EE6.1: https://docs.expressionengine.com/v6/installation/changelog.html#version-610-release-october-6-2021

**Comment by intoeetive** [comment]
@PaulBaileyAtChan thanks!

@paulcripps as Paul mentioned above, this has been fixed a while ago. Please consider updating to latest 6.x version and comment back if you still see the issue
