### ISSUE TITLE
7.3 Members can view entries they do not have permission to edit.

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3563]
I have a user role with permission to create, edit their own entries and delete their own entries.  That's it- they can't edit/delete other peoples'.  I have a user assigned to only that role.

In 7.2.17, on the edit entry page, that user would only see the entries they authored.  In 7.3, they see ALL of the entries.  They can't click a link and edit them, and they can't select the checkbox.  But they can see them all.

This is a change from 7.2.

**Comment by intoeetive** [comment]
The related discussion is happening in https://github.com/ExpressionEngine/ExpressionEngine/discussions/3091

**Comment by intoeetive** [comment]
We reverted behavior to be close to original in 7.3.5
