### ISSUE TITLE
7.3.5 Multisite manager disregards site_url overwrite in index.php

### ISSUE THREAD

**Issue by PontusMadsen** [ExpressionEngine/ExpressionEngine#3570]
After updating from 7.2.something to 7.3.5, Multisite manager disregards site_url overwrite in index.php.

**How To Reproduce**
EE7.3.5
Two sites
Different info in $assign_to_config['site_name'], $assign_to_config['cp_url'] and $assign_to_config['site_url'] on both sites

**Environment Details:**
 - Version: 7.3.5
 - PHP Version 7.3.33
 - MySQL Version 10.5.16-MariaDB
 - Web Server: Nexcess Cloud Hosting... uhm...

**Comment by intoeetive** [comment]
@PontusMadsen I wasn't able to replicate this on site front-end with EE 7.3.5

Where (what pages) is that you see the wrong behavior? Remember that CP will not respect those values if they are only set in `index.php` and not `admin.php`

**Comment by PontusMadsen** [comment]
We need to stop meeting like this @intoeetive ... It's in admin panel for "URL and Path Settings".
I have added in both admin and index on both sites.

It's the default base_url that is the same on all sites depending on which was saved last. Which means if I write site1.com in site1.com's base_path, it shows as site1.com on site2.com too.

**Comment by intoeetive** [comment]
I'm a little confused about your setup, because you say about `site_url` and then about `base_url` and then about `base_path` :)

How do the settings look like in CP?

What is the code for those that you have in `index.php` / `admin.php`? What's in `config.php`? Lastly, if you also use `.env.php` for those, how that looks like? (please replace actual site names/path with `***` and post here)

**Comment by PontusMadsen** [comment]
So.. yeah. This seems to be deeper than just the base_url, but this one problem I have.

Found "$config['base_url'] = 'https://www.Site2.jp/';" in config.. that was actually the problem.
Thanks!

Now to why images from bloqs doesn't show after update to 7.3.5 and latest Bloqs. But that's a question for someone else.

Thanks again dude, appologies.

**Comment by intoeetive** [comment]
Glad you have it solved! Closing the issue now :)
