### ISSUE TITLE
IPv6 causes an exception in the exp_pro_search_log table

### ISSUE THREAD

**Issue by dsite** [ExpressionEngine/ExpressionEngine#3589]
**Description of the problem**
I'm doing some testing with Pro Search on a staging site, and I hit an exception when I submitted a search. I believe the issue is that Pro Search tried to log my search, but it tried to record an IPv6 address in a column that was intended for IPv4 addresses.

**Error Messages**
<pre><code>
Exception Caught

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ip_address' at row 1:  
INSERT INTO exp_pro_search_log (site_id, member_id, search_date, ip_address, keywords, parameters) VALUES (1, 1, 1688757371, '2600:1700:57f0:a770:a885:f898:b68a:7072', '', '{\"result_page\":\"client\\/page\"}')

ee/legacy/database/drivers/mysqli/mysqli_connection.php:114

Stack Trace: _Please include when reporting this error_

#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query()
#1 ee/legacy/database/DB_driver.php(260): CI_DB_mysqli_driver->_execute()
#2 ee/legacy/database/DB_driver.php(175): CI_DB_driver->simple_query()
#3 ee/legacy/database/DB_active_rec.php(1297): CI_DB_driver->query()
#4 ee/ExpressionEngine/Addons/pro_search/model.pro_search.php(214): CI_DB_active_record->insert()
#5 ee/ExpressionEngine/Addons/pro_search/mod.pro_search.php(1800): Pro_search_model->insert()
#6 ee/ExpressionEngine/Addons/pro_search/mod.pro_search.php(1598): Pro_search->_log_search()
#7 ee/legacy/libraries/Actions.php(181): Pro_search->catch_search()
#8 ee/legacy/libraries/Core.php(684): EE_Actions->__construct()
#9 ee/legacy/controllers/ee.php(51): EE_Core->generate_action()
#10 [internal function]: EE->index()
#11 ee/ExpressionEngine/Core/Core.php(268): call_user_func_array()
#12 ee/ExpressionEngine/Core/Core.php(124): ExpressionEngine\Core\Core->runController()
#13 ee/ExpressionEngine/Boot/boot.php(184): ExpressionEngine\Core\Core->run()
#14 html/index.php(164): require_once('...')
#14 html/index.php(164): require_once('...')
</code></pre>

**Environment Details:**
 - Version: 7.3.5
 - PHP Version 7.4
 - MySQL Version MariaDB 10.6.12

**Possible Solution**
When I change the `ip_address` data_type from `varchar(16)` to `varchar(64)`, the error message no longer appears and the search is logged successfully.

**Comment by intoeetive** [comment]
This is interesting. Which Pro Search version are you running? I see that the current version has this field set to `varchar(46)`

**Comment by dsite** [comment]
It's 8.0.2. I don't actually know if that's the most recent, but it's not suggesting I upgrade, so I assume it is. 🤷🏻‍♂️

It might also be helpful to know that this is a site that has been upgraded from EE3/Low Search.

I'm doing another EE3 upgrade this week, so I'll see if it behaves differently.

**Comment by intoeetive** [comment]
Oh. I see what happened. If you went from Low Search directly to 8.0.2, the update might have not been run. We'll get this fixed
