### ISSUE TITLE
Closed Entry using Pages URI overrides url

### ISSUE THREAD

**Issue by ghost** [ExpressionEngine/ExpressionEngine#359]
**How To Reproduce**
- An entry is created using normal template group/entry url structure with `test` for its url title outputting for `/blog` template group e.g. outputting at url `/blog/test`
- An entry has Pages URI and template field filled out that overrides this page e.g. `/blog/test`
- Expect that the closed entry would not interfere with what renders at `/blog/test`
- Instead the page is outputting a 404

**Environment Details:**
 - Version: 5.3.0
 - PHP Version 7.1

**Comment by szgalbraith** [comment]
What template group / template file do you have?

If you don't have any routing on then EE, by default, will look to the "blog" template group then look for a "test" template.

That test template could then call the channel entries tag and look for a third segment in the url (either an Entry ID or an Url Title) to pull the specific entry.

Perhaps I am misunderstanding, but if you can include more information that would be helpful I think to others.

**Comment by mightyfernandez** [comment]
I don't think I'm explaining this clearly - let's give it another shot:

   - The default routing is working properly e.g. if I have blog/index
   template set up, then blog/test is working for my entry with url_title
   "test"
   - The only time the routing isn't working as expected is when I have a
   closed entry with Pages URI blog/test
      - So my expectation would be that Pages URI would trump default
      template routing if the entry was open, but not if the entry was closed
      (now that I think about it maybe this assumption isn't valid)


*Kristine Fernandez*

*SENIOR DEVELOPER*

*(512) 459-7000*


*MIGHTYCITIZEN.COM <https://www.mightycitizen.com/>*

**Comment by szgalbraith** [comment]
What does your {exp:channel:entries} tag in your blog/index file look like?

**Comment by mightyfernandez** [comment]
{exp:channel:entries channel="blog" disable="member_data|pagination"
url_title="{segment_2}" status="not Closed"}

*Kristine Fernandez*

*SENIOR DEVELOPER*

*(512) 459-7000*


*MIGHTYCITIZEN.COM <https://www.mightycitizen.com/>*

**Comment by szgalbraith** [comment]
I just replicated putting a basic entries tag in an index template in a group calling the second segment for the url_title parameter and status of not closed. It is doing what I would expect it to and simply displaying no results.

**Comment by mightyfernandez** [comment]
That's not quite the steps to replicate but I'm starting to think that maybe my expectation wasn't necessarily accurate.

For clarification, the steps would be:
- Basic entries tag in an index template in a group calling the second segment for the url_title parameter and status of not closed
- Initial state has an entry that is open, and is being displayed correctly at that URL, say /blog/test
- Create a different entry with Pages URI field filled out that overrides this url (blog/test) but this entry is closed
- Expected that this second entry with the Pages URI field would not override the url unless it was open
- Actual results is that now /blog/test is no_results despite the first entry still being open

**Comment by intoeetive** [comment]
I was not able to replicate the issue:
> Create a different entry with Pages URI field filled out that overrides this url (blog/test) but this entry is closed
on latest EE version. If you try to create duplicate Page URL, EE shows validation error

As of the issue in general, I would classify this as not a bug. You can specify to also show closed entries on the pages with `status` parameter, and the pages routing happens long before the template is parsed
