### ISSUE TITLE
Field settings for files in MSM

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3595]
MSM site- file field assigned to a directory only available on site A.  When in site B, if you go to edit the field, in the directory settings, nothing is selected (because the currently assigned directory is unavailable.  So you THINK no directory is assigned, but one is, and it's not available on the site you're trying to use it on.

<img width="915" alt="Screenshot 2023-07-10 at 11 44 04 AM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/1181219/f7e315bc-9d5d-4116-b47b-713d79db660e">

The big issues with using this field on multiple sites was addressed in https://github.com/ExpressionEngine/ExpressionEngine/pull/3452 but I'm thinking we also need either a validation error or some kind of warning on the file setting pages.

**Comment by intoeetive** [comment]
@robinsowell we already have validation error, but it's rather generic. The linked PR is adding warning banner, which I think should work good together with validation
