### ISSUE TITLE
WebP modifier doesn't maintain PNG transparency

### ISSUE THREAD

**Issue by ericharth-acer** [ExpressionEngine/ExpressionEngine#3609]
When using the {image_field:webp} image modifier on a PNG with an alpha transparency, the transparency is not retained and a matte colour (green?) appears where transparent areas were previously.

**Comment by intoeetive** [comment]
@ericharth-acer I wasn't able to replicate this. Are you using GD or ImageMagick? Is there a specific PNG file that you can provide that is problematic?

**Comment by intoeetive** [comment]
closing as we did not receive any follow-up information
