### ISSUE TITLE
BUG: CCHECKBOXES inside of GRID field

### ISSUE THREAD

**Issue by amadeus77** [ExpressionEngine/ExpressionEngine#361]
There is definetly something wrong with the checkboxes inside of grid field - see my posts above. It must be a bug - I tested it the whole day and the output of the template tags is inconsistent.

For example:

1. I save en entry with a grid row where 1 of three checkboxes in a column fields is selected.
2. Firstly the template tag {entries}{gridfield:checkboxcolumn}{/entries} is outputting correctly -> ONE result (the selected checkbox value). 
3. Then I deselect all checkboxes in the same grid row - again everything correct -> NO output. 
4. In the same row once again I select ONE of three checkboxes -> output is now THREE EQUAL comma separated values (the selected one - three times the same)

**Comment by dougblackjr** [comment]
@amadeus77 Can you show us your field set up and template? That may help in seeing what is happening here.

**Comment by amadeus77** [comment]
@dougblackjr No, I'm sorry - after hours of trying I deleted everything and managed it through toggles. But I believe you're also member of the slack channel. There I posted a few more details: https://eecms.slack.com/archives/C04CUNNR9/p1579273845025500
