### ISSUE TITLE
Front End Edit - empty fields not displaying

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#3616]
I've noticed that empty Entry fields, aren't displaying the Edit icon, in the Front End Edit mode.
This seems to apply to auto-displayed Edit icons, as well as manually added ones using the {if frontedit} markup.

EE 7.3.6
PHP 8.1

In this example, Stock does have a value, but the Storage field is empty.

```
{if frontedit}
	<div>
		Stock: {product-stock:frontedit}
		Storage: {product-stock-storage:frontedit}
	</div>
{/if}
```

![Screenshot 2023-07-19 at 17 17 33](https://github.com/ExpressionEngine/ExpressionEngine/assets/36453035/2640d6a0-09d4-4eb8-bbe8-ea7324ffb89b)

**Comment by intoeetive** [comment]
This is know limitation which we are not likely to change - however I'll move this to Feature Requests.

If you need to be sure the link is present, you can place it manually in the template: https://docs.expressionengine.com/latest/advanced-usage/front-end/frontend.html#customizing-the-link-location
