### ISSUE TITLE
ModSecurity software gives false positives in Expression Engine control panel

### ISSUE THREAD

**Issue by Fred2341** [ExpressionEngine/ExpressionEngine#362]
My webhost uses ModSecurity software that applies Webbased Applicatie Firewall from Comodo WAF.
In the Expression Engine control panel saving new channels or templates causes a 403 Access error.
Apparently, the the following rule causes the error:  ID '213060' and Description 'COMODO WAF: XSS Filter - Category 3: Attribute Vector||censere.nl|F|2'.   

It seems the text files that Expression Engine uses are saved with XML, which is considered unsafe by Comodo.

How to solve this?

**Comment by ic360-com** [comment]
My webhost is frequently having to whitelist mod_sec issues for me, when I get 403 errors within the CP. It was happening a lot with EE5 but seems (so far) to be happening less often with EE6.
