### ISSUE TITLE
Searching in File Field type with Subfolder - No results

### ISSUE THREAD

**Issue by kchatel** [ExpressionEngine/ExpressionEngine#3636]
**Description of the problem**
Using a File Fieldtype, there is no way to search for files within subfolders. I'm not sure if it's a bug or a feature that needs to be added. It becomes cumbersome to find files when they are located multiple levels deep in subdirectories.

**Environment Details:**
 - Version: [7.2.8]
 - PHP Version [8.0.27]

**Comment by intoeetive** [comment]
@kchatel are you speaking of using search in File Manager, Entry Manager or front-end entries search? can you provide an example?

**Comment by kchatel** [comment]
@intoeetive Using the Search in a File fieldtype in an entry in the CMS, I haven't tested it on the front-end.

**Comment by intoeetive** [comment]
@kchatel I'm still not sure which exactly search here you speak about :) Can you add a screenshot, the search keyword and the name of file that is not found

**Comment by kchatel** [comment]
![Screenshot 2023-07-26 at 11 01 00 AM](https://github.com/ExpressionEngine/ExpressionEngine/assets/11176076/ee19898f-92d1-4e33-bb32-4c24067598a8)
![Screenshot 2023-07-26 at 11 01 16 AM](https://github.com/ExpressionEngine/ExpressionEngine/assets/11176076/0334c51d-05e3-4a78-9b52-6c0b71bcb595)
