### ISSUE TITLE
Grid validation can throw a 'not authorized' message trying to save an old version

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3639]
Replicated on 7.3.8, only happens to logged in superadmin

Enable versioning for a channel.  Go make an entry with a grid field.  Save it.  Add a row, save.  It will go into exp_entry_versioning like this:

```s:10:"field_id_7";a:1:{s:4:"rows";a:1:{s:8:"row_id_2";a:2:{s:9:"col_id_11";s:0:"";s:9:"col_id_12";s:0:"";}}}s:10:"```

Edit the entry, delete the row, save it.

Load the version that has the saved grid field, try to save, now you get a validation error and basically no way to get rid of it rather than load a new version.

<img width="1424" alt="Screenshot 2023-07-27 at 2 24 33 PM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/1181219/3ab40fd0-0282-49a0-a6a5-6ac13aa001b4">

When you deleted the row, it removed it from exp_channel_grid_field_x and in grid/libraries/Grid_lib.php around line 250:

```
       if (isset($data['rows'])) {
            foreach ($data['rows'] as $key => $row) {
                if (substr($key, 0, 6) == 'row_id') {
                    $row_key = str_replace('row_id_', '', $key);

                    if (! in_array($row_key, $valid_rows)) {
                        if (ee('Permission')->isSuperAdmin()) {
                            return array('value' => '', 'error' => lang('not_authorized'));
                        } else {
                            unset($data['rows'][$key]);
```

If you're a superadmin and it's submitting a row that no longer exists, you get a not authorized error.  Otherwise, it just deletes it.  I'm not sure why it's different for superadmin, but it's definitely confusing.  

Note- IF before you save, you delete the orphaned row, you can save then.  Basically, you manually clear it out and your good.  But otherwise, once you save, you get the validation error, there's no trashcan to delete it and you basically have to refresh the page or load another version. 

ETA: SOOOO I thought the solution would be to just unset the data like we do for non-superadmins, but then I realized that for versions, that means you lose the data in the grid if the row was deleted in another version.  This is exactly what versions DO NOT WANT.

Solution- if the data in the version array looks like this:
```
s:11:"field_id_23";a:1:{s:4:"rows";a:1:{s:9:"new_row_1";a:2:{s:9:"col_id_39";s:0:"";s:9:"col_id_40";s:0:"";}}}s:11
```
It's ok.  EE is treating it like a new, unsaved row and not trying to match it to an existing column.  Maybe when we either save the version or more likely when we unserialize the array and set it up, we could treat either all or any missing grid rows as 'new_row_x' instead of 'row_id_1'?

**Comment by intoeetive** [comment]
@robinsowell - please review the linked PR
