### ISSUE TITLE
mb_convert_encoding used while Multibyte String library not required

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3643]
It's a [recommended but not required library](https://docs.expressionengine.com/latest/installation/requirements.html#php-extensions-recommended)

We're using it in a couple of spots, user ran into it in ee/ExpressionEngine/Service/Formatter/Formats/Text.php(605).

We do have a multibyte helper which does ee_mb options, but it's not in there.  https://stackoverflow.com/a/11978382 looks worth exploring, but it's definitely one I'm not strong enough to add, but I suspect adding an option to the helper is the way to go.

**Comment by intoeetive** [comment]
or make it required library maybe? In fact `mb_` functions are used in other places in EE. We ask for miltibyte support in DB. I think in year 2023 we should just use multibyte functions provided by PHP and not reinvent the wheel

@TomJaeger

**Comment by intoeetive** [comment]
I think for 7.5 we should start requiring Multibyte library. I don't see a single reason not to do that in 2024. @TomJaeger

**Comment by matthewjohns0n** [comment]
Had a conversation with @TomJaeger and @bryannielsen and we decided to add this as a requirement in the docs.
