### ISSUE TITLE
Autosave does not include data from Grids with Relationships

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#3645]
How to replicate: 

1. Create a Grid field with a relationship (multiple) and a text input.
2. In the existing entry add some content to that Grid field: rows, relationships. Do not touch other fields.
3. Lose that content due to something, get upset, and open an EE Bug Report :)

EE 7.3.8

**Comment by intoeetive** [comment]
@shbchk to be clear:
- does the "older" content of Grid not show when you load autosave, or
- does the autosave's data not get saved to entry after it has been loaded and you click Save
?

**Comment by shbchk** [comment]
Sorry, I wasn't clear.

If you modify content of a Grid field in an existing entry, it doesn't autosave at all.

**Comment by shbchk** [comment]
I made a video to illustrate the issue:

https://github.com/ExpressionEngine/ExpressionEngine/assets/12234507/36a8a0b2-3289-4f36-b04f-37be591d4a4e

**Comment by intoeetive** [comment]
@Yulyaswan please have a look.
This is not specific to Relationship, but also happens with simple text inputs in Grid (new rows only)
It looks like because the rows are created dynamically the autosave logic is not getting attached to those and so `entry:startAutosave` event is never fired
