### ISSUE TITLE
Add publicly accessible link to File Manager screen in CP

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#365]
Content editors cannot easily upload a file and quickly grab the publicly accessible link to it for use in email campaigns, social media posts, etc without publishing the link to a page first.

Suggested solution is to add a third icon/button in the 'Manage' column (next to 'Edit' and "Download" buttons) that allows CMS users to copy the full public URL to that file, eg: whatever `{filedir_x}file-name.pdf` resolves to.

**Comment by ops-andy** [comment]
@pyrobob83 Just doing some clean up, can you please confirm that this was resolved in 6.0.
![image](https://user-images.githubusercontent.com/55093827/120671208-295f9800-c45f-11eb-8aef-d421e7cabed3.png)

**Comment by pyrobob83** [comment]
Yes, that takes care of it - thanks!
