### ISSUE TITLE
502 Error When Adding Field to Fluid Field

### ISSUE THREAD

**Issue by drewmckenna** [ExpressionEngine/ExpressionEngine#3656]
While in the Fields page, I added a new field to an existing fluid field.  I received a 502 Bad Gateway message.  I hit the back button on my browser to see the change had been made.  I was also prompted:
Search Reindex
Please [run the search reindex tool] tool to keep your searchable data up-to-date.

The same behavior occurs when removing a field from my fluid field.  

**How To Reproduce**

1. Go to Fields
2. Select my Fluid field
3. Add a new Custom field to my Fluid field.  
4. Hit save

**Error Messages**
502 Bad Gateway
Reindex noted above 

**Environment Details:**
 - Version: [7.3.8]
 - PHP Version [8.1]
 - MySQL Version [8]
 - OS: [Ubuntu 20.04 LTS x65]
 - Web Server: [nginx]

**Additional context**
The reindex message appears until I depart the "Fields" pages.

**Comment by intoeetive** [comment]
@drewmckenna would you be able to inspect server error logs to get the actual error behind 502 message?
