### ISSUE TITLE
Comment module slowness and error (SQL Exception Caught) when more the 40 characters are imputed

### ISSUE THREAD

**Issue by bobural** [ExpressionEngine/ExpressionEngine#368]
**Description of the problem**
- Hi, The Comment Module is really slow and I've managed to get the following error when I enter more then 40 characters (numbers) in the input fields. The error I got:
```
Exception Caught
There was a database connection error or a problem with a query. Log in as a super admin or enable debugging for more information.
mysqli_connection.php:117
```

**How To Reproduce**
- one channel, with a few entries added to different categories.
- template group with only foo/index
- on index file add a channel entries tag and close the tag to display the entries in front-end.
- on same index file below closing tags of channel entries add the comment form tag according to documentation :  https://docs.expressionengine.com/latest/comment/form.html
- as GUEST, on fronted on **https://www.foobar.com/template-group/index**  when one entry is displayed, add more the 40 characters in the input fields of the Comment Submission Form.
- issue reproducible.

**Error Messages**

```
Exception Caught
There was a database connection error or a problem with a query. Log in as a super admin or enable debugging for more information.
mysqli_connection.php:117

```

**Environment Details:**
 - Version: 5.3.0
 - PHP Version: 7.2.27
 - MySQL Version: Ver 15.1 Distrib 10.4.12-MariaDB
 - OS: Ubuntu 16.04.6 with kernel 4.4.0-131-generic
 - Web Server: nginx/1.16.1 with php-fpm7.2

**Additional context**
- The above error I've manage to reproduce it multiple times.
- If I insert less the 40 characters as guest the module is very slow.

**Comment by dougblackjr** [comment]
@bobural Can you login as the super admin and give the error that is displayed there?

**Comment by bobural** [comment]
I tried to get the logs but I do not have them. No logs appear in admin panel. In nginx logs I only have the POST ant nothing more.

**Comment by dougblackjr** [comment]
@bobural If you are logged in as an admin, it should give you the error. Is the comment issue only happening with guests?

**Comment by bobural** [comment]
Hi,
The error I get is reproducible only as GUEST. If I am logged in as Admin the comment module work fine. As regarding the logs, I do not get any output in the Admin panel for this issue.
Thank you,

**Comment by bobural** [comment]
Has anyone tested this? Or is it only my setup...
Thank you.

**Comment by bobural** [comment]
I figure it out... All my traffic goes through Cloudflare and this is happening because of caching ...
If I remove this, everything works fine.
Thank you and sorry for the hassle.

**Comment by Sungodragon** [comment]
Could you post a solution for all of us.
Also could you tell us which plan you are one on Cloudlfare for this domain

**Comment by bobural** [comment]
I am still testing a solution through Cloudflare ... When I have done some extensive testing I will post my findings
