### ISSUE TITLE
Help! Massive problems with the file grid field since update to 7.3.9

### ISSUE THREAD

**Issue by bytebaby** [ExpressionEngine/ExpressionEngine#3689]
I can't maintain my client's website because of all the error messages after I upgraded EE from 7.3.6 to 7.3.9. (Note; I also have the addon "WYSIWYG" on version 5.4.4)

PHP: 7.4 (The errors also appear with PHP 8.1 and 8.2)
Apache

Please look the follow errors:

<img width="807" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/21154749/be56e92a-ef82-4ba1-9e00-b99800321159">

<img width="1274" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/21154749/747b2f41-bd6e-4b3f-b03b-e450cddf390d">

When I have saved a post:

<img width="622" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/21154749/b1feef0e-dba4-4ded-8f6c-13558e0c599c">

On the homepage of the website when I'm logged in:

<img width="1329" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/21154749/723d179c-0bba-4743-866c-45d8b7d16e11">

When I call the field in the field editor

<pre><code>
Warning
array_merge(): Expected parameter 2 to be an array, null given
ee/legacy/libraries/api/Api_channel_fields.php, line 136

Severity: E_WARNING
Warning
array_merge(): Expected parameter 2 to be an array, null given
ee/legacy/libraries/api/Api_channel_fields.php, line 136

Severity: E_WARNING
Warning
array_merge(): Expected parameter 2 to be an array, null given
ee/legacy/libraries/api/Api_channel_fields.php, line 136

Severity: E_WARNING
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Notice
Trying to access array offset on value of type null
ee/ExpressionEngine/Service/ConditionalFields/Factory.php, line 38

Severity: E_NOTICE
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/ExpressionEngine/Boot/boot.common.php, line 480

Severity: E_WARNING

</code></pre>

ADDENDUM: I can no longer edit fields

**Comment by intoeetive** [comment]
@bytebaby can you check if this fix would solve your issue? https://github.com/ExpressionEngine/ExpressionEngine/pull/3688

**Comment by bytebaby** [comment]
I have downgraded the system to 7.3.6 but the grid field error remains.

**Comment by intoeetive** [comment]
@bytebaby can you try applying the fix? (whether on downgraded or latest version)

**Comment by bytebaby** [comment]
Thanks for the quick reply. The micro update works. I am happy! :)
