### ISSUE TITLE
Various avatar issues

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#369]
**Description of the problem**

EE5.30

1. Template tags do not parse: `{avatar_image_width}` and `{avatar_image_height}`

2. Max image dimensions not appearing as information in CP member edit avatar upload section, they used to in EE2(?). Not helpful for clients and error feedback doesn't offer decent feedback.

**How To Reproduce**

1. Template tags, add author's avatar tag inside a channel entry including width and height attributes.

2. Set avatar max/width height and test uploading a larger image.

**Fixes**

1. Correct parsing of avatar width and height variables.

2a. Add avatar max/width height info to CP field (it only tells you max file size at the moment)
2b. Update error message to help fix the error, e.g. "File exceeds maximum allowed width X and height Y"  and/or "File exceeds maximum file size (50kb)"

**Comment by intoeetive** [comment]
This is going to be resolved with #1685

(the template tags though might be not accurate for pre-existing avatars)
