### ISSUE TITLE
guest entry creation is not working

### ISSUE THREAD

**Issue by erwingeiger** [ExpressionEngine/ExpressionEngine#370]
With EE2 I could easy create entries for guest users. Now with EE5.3 I cannot. I'm using the following rule to create entries: "ee('Model')->make('ChannelEntry')". When I'm logged in as a user It's working fine. But when not logged in I will get a white screen of death. When I try to debug it I notice It fails after or within $entry->save();'.

I can't figure out how to fix this. In the setting of the channels 'Allow guest submissions?' is enabled.

Who has a solution for this?

**Comment by dougblackjr** [comment]
@erwingeiger Is this in a custom addon?

**Comment by erwingeiger** [comment]
@dougblackjr yes it is

**Comment by dougblackjr** [comment]
@erwingeiger Since you are doing it in a custom addon, the `Allow guest submissions` setting wouldn't apply. Can you post the call being made? Does it work if you set the author ID to 0?

**Comment by erwingeiger** [comment]
@dougblackjr sure.

`$entry = ee('Model')->make('ChannelEntry');

		$url_title = $this->generateSeoURL($data['title']);

		$channel = ee('Model')->get('Channel', $channel_id)
		  ->filter('site_id', ee()->config->item('site_id'))
		  ->first();

		$entry->Channel = $channel;
		$entry->site_id =  ee()->config->item('site_id');
		$entry->author_id = ee()->session->userdata('member_id');
		$entry->ip_address = ee()->session->userdata['ip_address'];
		$entry->sticky = FALSE;
		$entry->status = 'open';
		$entry->url_title = $url_title;
		$entry->entry_date = ee()->localize->now;
		$entry->edit_date = ee()->localize->now;

		/* Array which contains your Field Data */
		$entry->set($data);
		$entry->save();`

**Comment by dougblackjr** [comment]
@erwingeiger Because this is custom work, it may be better to bring this in to the EE Slack. You can find the invite form here at the main EE site [https://expressionengine.com/](https://expressionengine.com/). I'd be glad to jump on there and debug with you!

**Comment by erwingeiger** [comment]
@dougblackjr thx I will first try to change the author_id to 0. If that's not working I will try in in Slack.

**Comment by dougblackjr** [comment]
@erwingeiger Can you give an update? Did that work?

**Comment by erwingeiger** [comment]
@dougblackjr unfortunately no it didn't work.
