### ISSUE TITLE
php 8 'dynamic property EE_Image_lib::$padding is deprecated'

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3701]
> Severity: E_DEPRECATED  --> Creation of dynamic property EE_Image_lib::$padding is deprecated /system/ee/legacy/libraries/Image_lib.php 121

**Comment by intoeetive** [comment]
@robinsowell what's the full trace for this error (or how to replicate it)?
$padding is non-existing property on that class and should not be set in the first place

**Comment by robinsowell** [comment]
I'm getting it running a sync in the EEH channel images add-on.  WHICH is where the bug is.  Was setting padding instead of wm_padding.  Bleh- sorry for the time waste!
