### ISSUE TITLE
View count not incrementing when using url_title

### ISSUE THREAD

**Issue by adster101** [ExpressionEngine/ExpressionEngine#3725]
The below snippet doesn't record page views as documented. 

`  {exp:channel:entries 
    channel="features" 
    require_entry="yes" 
    url_title="{last_segment}" 
    dynamic="no" 
    status="open|draft|submitted" 
    disable="category_fields|member_data|pagination"
    track_views="one"
  }`

When entry_id="12345" is used instead of url_title="{last_segment}" then the page view is made and {view_count_one} increments as expected. 

There are no error messages. No caching is enabled an no config overrides. 

**Environment Details:**
 - Version:6.4.3
 - PHP Version: 8.1.2
 - MySQL Version: 8
 - OS: Linux, Ubuntu]
 - Web Server: Apache

**Comment by intoeetive** [comment]
@adster101 I don't think that should make any difference. What would make difference though is the fact whether you are logged in or not - views from superadmin users do no count. Can you double check if that's not your case?

**Comment by adster101** [comment]
@intoeetive  Nope, I view an entry while in private browsing mode and {view_count_one} doesn't increment when I refresh the page. 

The below snippet works, that is when using entry_id instead of url_title:

` {exp:channel:entries  channel="features"  require_entry="yes"  entry_id="19358" dynamic="no" status="open|draft|submitted"  disable="category_fields|member_data|pagination" track_views="one" }`

...so I could use a plugin to lookup the entry_id as a workaround. When logged in to the CP the view count still increments when using the above code so being logged in doesn't seem to affect anything.

**Comment by intoeetive** [comment]
This appears to caused by the fact that you're using `dynamic="no"` parameter. If you need to make it work, you need to set a [configuration override](https://docs.expressionengine.com/latest/general/system-configuration-overrides.html#relaxed_track_views) (and we need to document this better)

**Comment by adster101** [comment]
Thanks, adding the override works.

Out of interest, how would I modify my tag so that it's 'dynamic'? If I remove dynamic="no" from my tag then no entry is returned? Do I need to use the entry id? What am I missing?

**Comment by intoeetive** [comment]
Usually, if your URL structure follows the pattern template_group/template_name/entry_url_title you'd get correct entry dynamically
