### ISSUE TITLE
New fields added to Field Groups not available to existing content within a Fluid Field

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#3741]
**Description of the problem**
If you have an existing Field Group, where that existing Field Group is already being used in a Fluid Field (such as a Page Builder) and there are existing entries that already have content utilizing the Field Group inside the Fluid Field (very typical site scenario)… and then you add a new field to the Field Group, all the existing instances of that Field Group inside the Fluid don’t see the new field - only new ones do. 

**How To Reproduce**
1. Create a Field Group with a set of fields
2. Create a Fluid Field (eg Page Builder) and assign the Field Group to it
3. Assign the Fluid Field to a channel
4. Edit an entry from that channel and add content to the Field Group within the Fluid Field
5. Go back to the Field Group and add a new field
6. Retry editing that entry and note you don't see the new fields for existing uses

I'm hoping this is an obvious bug and this wasn't intentional or some kind of technical limitation, but let me know either is true.

**Comment by intoeetive** [comment]
This is a known limitation

Adding new Group (even if it's same group) would add new fields (with changed order, if it was changed) - but the existing Fluid components are saved in the state when they were added, so the Group contents/order might be different from what you have

**Comment by pyrobob83** [comment]
@intoeetive @TomJaeger Wow, that's pretty huge.  If this is truly a restriction and we can't figure out a way to update existing entries that utilize Field Groups inside a Fluid to reveal new fields, I don't see how using Field Groups in Fluid Fields can be considered useful at all.  Who would want a site (or component) that once setup and content is added, can't evolve?

Brian mentioned in Slack that Bloqs does the same thing but saving the entry again would then introduce the new fields in existing bloqs... I don't even view that as an acceptable solution, since it adds responsibility to the user to know that's what they need to do, but maybe it'll give some ideas in terms of how to tackle this.

How feasible would some kind of sync utility be (CMS or CLI) that can be run manually by the DEV and essentially finds all the uses of a particular Field Group and injects fields that have been added since being saved?  Totally open to other solutions, but please, please let's find a way to fix this.

**Comment by JimStrive** [comment]
Did anyone come up with a solution to this as an interim measure? I've a big site with tonnes of these components which need new fields pushing to them!

**Comment by bryannielsen** [comment]
@JimStrive sorry you're hitting this issue as well.  We have a fix that we're in the process of testing and finalizing now but I don't have an estimate on when it will be released.  We are trying to support this with as little friction as possible so it will not require a special utility or any action on your end to get the new fields showing in your existing fluid field groups.

If you have a staging environment for your site setup and you're interested I would be happy to pass along the updates for you to test when they're ready.

**Comment by JimStrive** [comment]
I've got a local version of the site at the moment, I'm in the midst of making update to, I'd be happy to test the new functionality, if it works, It might save me a day of copy and pasting!

**Comment by bryannielsen** [comment]
Resolved in [7.5.0](https://github.com/ExpressionEngine/ExpressionEngine/releases/tag/7.5.0)
