### ISSUE TITLE
EE7 php warning in mail module on php 7.3

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3749]
Technically, [EE7 supports php 7.2.5](https://docs.expressionengine.com/latest/installation/requirements.html#the-bare-minimums).  And on php 7.3, you can get this error:

> Warning
> Use of undefined constant STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT - assumed STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT' (this will throw an Error in a future version of PHP)
ee/ExpressionEngine/Controller/Settings/Email.php, line 38

Looks like STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT isn't available until php 7.4 (I THINK)

**Comment by bryannielsen** [comment]
This should be resolved now in versions 6.4.16 and 7.3.15
