### ISSUE TITLE
E_DEPRECATED: Grid_parser.php, line 466

### ISSUE THREAD

**Issue by bytebaby** [ExpressionEngine/ExpressionEngine#3754]
Although everything was working fine last week, today my customer reports a PHP error message (see the following screen) on the page media2finish.com/making

<img width="1006" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/21154749/b7dd5202-69f7-4acc-99d9-11ebb83949f5">

Apparently it's a file grid field. What is strange, however, is that this message does not appear on the other sites (e.g. media2finish.com/we), even though the grid field is also used for these channels.

In addition, the error message does not disappear even if you select the "Hidden" option under "Debugging & Output" and are logged out. Which is unfortunate for my customer.

An update from 7.3.11 to 7.3.12 didn't help either.

PHP 8.1.22 (Aug 23 2023)
OS: macOS
Apache
MariaDB

**Comment by bytebaby** [comment]
Another note: Because the error message affects the layout, I set it to invisible via CSS. If anyone wants to see it, I can undo it.

**Comment by bytebaby** [comment]
I was able to fix the error. It was caused by an empty line with no image in the "grid field". See screen:

<img width="1187" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/21154749/d8c04a22-16da-4e36-a02b-25f1555e3bd2">

Since this kind of thing happens to authors, it would be nice if the case didn't give a PHP error. :)

**Comment by intoeetive** [comment]
@bytebaby what is the template code that you're using to display that field?

**Comment by bytebaby** [comment]
Gladly:
```
{sliderbilder}
        <li><img src="{sliderbilder:file}{path}_sliderdesktop/{filename}.{extension}{/sliderbilder:file}" alt="{if sliderbilder:slidertext}{sliderbilder:slidertext}{if:else}{title}{/if}"></li>
{/sliderbilder}
```
