### ISSUE TITLE
Rich Text Field: Content deleted when saving with CTRL+S

### ISSUE THREAD

**Issue by bytebaby** [ExpressionEngine/ExpressionEngine#3759]
I edited a long interview in a rich text field ("Redactor Full") in "Fullscreen" mode. Normally I can save without any problems using the Control + S key combination, but in fullscreen mode all content in the text field was then deleted, and even the automatically saved versions always only produced an empty field. Phew, valuable time worked for nothing. ;)

After further testing I found that all content in each field (Title etc) is deleted. With a cloned entry, however, the old content is retained and only the edited fields lose their content.

- EE-Version 7.3.12
 - PHP 7.4
 - OS: macOS
 - Web Server: Apache

**Comment by intoeetive** [comment]
@bytebaby phoof, that is frustrating!

Unfortunately Redactor's developers have abandoned it for sake of their new editor, so there's not much we can do - but we'll disable Ctrl + S functionality when Redactor is in full screen mode, so that at least the data wouldn't be lost

**Comment by bytebaby** [comment]
This is a good measure.
I also only use Redactor Full because CKEditor doesn't have an HTML view.
