### ISSUE TITLE
On-the-fly image manipulations in Relationship error

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#3766]
I have the following On-the-fly Image Manipulations required, for Related Entries...

`<a href="{pages:url_title_path="products"}" style="background-image:url({pages:product-thumb:file:resize:crop:webp quality="80" resize:width="480" crop:maintain_ratio="n" crop:width="480" crop:height="384"})">`

...the images are being created okay, but it's causing this Warning when rendering...
```
Undefined array key "path:file"  
ee/ExpressionEngine/Addons/file/ft.file.php, line 786
```

If I remove the ":resize:crop:webp" part it works fine.

EE 7.3.12
PHP 8.1

**Comment by intoeetive** [comment]
@ic360-com What is `file:` part supposed to represent? If the field type is File, you should not need it (it's not in the list of supported modifiers), and if you have File Grid, you would need to use tag pair. So you can get rid of error by removing the `file:` part.

However, thank you for reporting this - the warning should not be shown when using invalid modifier
