### ISSUE TITLE
EE uses SMTP to send mail even though php mail selected in Settings (EE6)

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#3767]
**Description of the problem**
Had an issue where mail was no longer being sent by site even though "Send a mail" utility in CP was sending OK.
Checked on outgoing mail settings and it was set to "php mail" - which I confirmed for server was working through another route.
Dug through debug and found that despite EE being set to use php mail, when `ee()->email->Send()` was being executed the `EE_Email` object was being set to use SMTP mail for sending.
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/a39d2353-053f-4d6d-9364-19d3db55aec3)
At some point in the past this configuration was used - but it had been replaced by simple php mail use a while back.
Unclear what caused this issue to arise now - possibly has been not sending mails for a while (from a contact form).

What is curious is that even though the SMTP credentials do not work (no email is sent) `ee()->email->Send()` returns "true" to the calling add-on.

**How To Reproduce**
As described above.

**Environment Details:**
 - Version: 6.4.14
 - PHP Version 7.4.33

**Possible Solution**
It would seem that EE is using the SMTP data even if the SMTP option is not chosen. Stopping it doing that would be a possible solution.

**Additional context**

**Comment by intoeetive** [comment]
@jcogs-design the sending method is identified using `$protocol` property. You can see that in your case it is set to `mail` which is correct value for using PHP mail. The SMTP settings are set - as saved in EE preferences - but will not be used

So the `true` that you get in add-on is coming from the PHP `mail()` result - which would be a place to debug
