### ISSUE TITLE
Fluid field short name with hyphen not displaying

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#3771]
Attempting to output data from a Fluid field, that has a short name containing a hyphen "-", does not work.
As soon as I change it to an underscore "_" it work fine.

EE 7.3.12

**Comment by intoeetive** [comment]
@ic360-com can you post sample template code?

Also, does it just not display - or is showing some error?

**Comment by ic360-com** [comment]
I've just been trying to replicate on EE 7.3.14, but it's working okay.
