### ISSUE TITLE
Date translation in EE news RSS feed (CP overview)

### ISSUE THREAD

**Issue by Biscuiterie975** [ExpressionEngine/ExpressionEngine#3772]
ExpressionEngine news might be displayed through RSS feed in CP overview (EE 7).
I use the French translation (v 7.3.12) and for each news, the date is partially translated:
- the month and year parameters are correctly set for my foreign language.
- the day parameter seems to be hard coded in English with  "th" and "rd" that should only be displayed for English ordinal numbers.
- the comma behind the month parameter is not required 

See attachment
<img width="1156" alt="essai" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/109601150/a4dd3daf-30e6-48a0-affd-0c81ed559085">

**Comment by intoeetive** [comment]
@Biscuiterie975 the `th` and `rd` are actually coming from your server localization settings, not from EE. But for some reason this part is not using the same date format as in other sections, which I believe is something we need to fix.

Thanks!
