### ISSUE TITLE
`{exp:member:edit_profile}` does not save custom field values

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#3797]
EE 7.3.12

So, this code works okay if the logged-in user is a Superadmin. And it doesn't work if the logged-in user is just a Member.

```
{exp:member:edit_profile return="/test/test/success"}
<div>
  <label for="testfield">Test Field</label>
  <input id="testfield" name="m_field_id_1" value="" dir="ltr" field_content_type="" maxlength="256" placeholder="test">
</div>

<button type="submit">Save</button>
{/exp:member:edit_profile}
```

**Comment by intoeetive** [comment]
@shbchk I think you ar running into this issue, can you confirm? https://github.com/ExpressionEngine/ExpressionEngine/discussions/2858

**Comment by shbchk** [comment]
Yep. That's it. It's not very intuitive :)

Thanks, Yuri!
