### ISSUE TITLE
Problems with SVG Thumbnails in File Manager

### ISSUE THREAD

**Issue by maposch** [ExpressionEngine/ExpressionEngine#3803]
Dear Team! 

Thumbnails for **SVG** files are not displayed in the file manager. Is this issue known?

Regards
Markus

**Comment by intoeetive** [comment]
@maposch can you please clarify that problem that you have

What do you see instead of SVG files? Which ExpressionEngine version are you running?

**Comment by maposch** [comment]
Hello Yuri!

Here you can see the Problem in the File-Manager – all other File-Forma Works:

Version = 7.3.5

***@***.***


Regards Markus!

Von: Yuri Salimovskiy ***@***.***>
Gesendet: Montag, 9. Oktober 2023 07:14
An: ExpressionEngine/ExpressionEngine ***@***.******@***.***>
Cc: Markus Posch ***@***.***>; Mention ***@***.***>
Betreff: Re: [ExpressionEngine/ExpressionEngine] Problems with SVG Thumbnails in File Manager (Issue #3803)


@maposch<https://github.com/maposch> can you please clarify that problem that you have

What do you see instead of SVG files? Which ExpressionEngine version are you running?

**Comment by intoeetive** [comment]
@maposch I assume you were going to post some screenshot or video, but nothing came through.

Also, might be worth updating to EE 7.3.12 - there have been no updates specifically to address SVG files, but there have been some updates to other components of file manager, which might affect things

**Comment by maposch** [comment]
Hello Yuri,

now you can see the attached file?

Regards
Markus

Von: Yuri Salimovskiy ***@***.***>
Gesendet: Montag, 9. Oktober 2023 08:28
An: ExpressionEngine/ExpressionEngine ***@***.***>
Cc: Markus Posch ***@***.***>; Mention ***@***.***>
Betreff: Re: [ExpressionEngine/ExpressionEngine] Problems with SVG Thumbnails in File Manager (Issue #3803)


@maposch<https://github.com/maposch> I assume you were going to post some screenshot or video, but nothing came through.

Also, might be worth updating to EE 7.3.12 - there have been no updates specifically to address SVG files, but there have been some updates to other components of file manager, which might affect things

**Comment by intoeetive** [comment]
I think you need to actually visit GitHub to add attachment

**Comment by maposch** [comment]
Hi Yuri, 

Thanks for your answer. I hobe you are able to see it now? (see attached file)

Best regards, Markus
![screen-svg](https://github.com/ExpressionEngine/ExpressionEngine/assets/47695860/50d9f505-c11d-407f-a22e-4e75fe4da6e2)

**Comment by intoeetive** [comment]
Is your upload directory set to allow "all files" or "images only"? Can you provide one of those SVG files that are problematic, for reference? (I suspect that system might be not identifying mime type correctly)

**Comment by maposch** [comment]
Hey! it was set to "images only". Now i switch to "all files" but there was no impact to the problem. When i open the svg file you are able to see the image. The Problem is the Thumbnail View...

**Comment by maposch** [comment]
oh, now it seems to work. i tried a new image to upload and now i can see the thumbnail :)
