### ISSUE TITLE
Error notice when changing entry to selectable channel with category group mismatch

### ISSUE THREAD

**Issue by wagonheart** [ExpressionEngine/ExpressionEngine#381]
Error:
```
Notice
Undefined index: categories[cat_group_id_1]

ee/EllisLab/ExpressionEngine/Model/Content/ContentModel.php, line 149

    Severity: E_NOTICE


Fatal error: Uncaught Error: Call to a member function setData() on null in /var/www/vhosts/example.com/system/ee/EllisLab/ExpressionEngine/Model/Channel/ChannelEntry.php:795 Stack trace: #0 /var/www/vhosts/example.com/system/ee/EllisLab/ExpressionEngine/Library/Data/Entity.php(443): EllisLab\ExpressionEngine\Model\Channel\ChannelEntry->set__categories(NULL) #1 /var/www/vhosts/example.com/system/ee/EllisLab/ExpressionEngine/Service/Model/Model.php(298): EllisLab\ExpressionEngine\Library\Data\Entity->setProperty('categories', NULL) #2 /var/www/vhosts/example.com/system/ee/EllisLab/ExpressionEngine/Model/Content/ContentModel.php(254): EllisLab\ExpressionEngine\Service\Model\Model->setProperty('categories', NULL) #3 /var/www/vhosts/example.com/system/ee/EllisLab/ExpressionEngine/Library/Data/Entity.php(255): EllisLab\ExpressionEngine\Model\Content\ContentModel->setProperty('categories', NULL) #4 /var/www/vhosts/example.com/system/ee/EllisLab/ExpressionEngine/Model/Content/ContentModel.php(191): EllisLab\ExpressionEngine\Library\Data\Ent in /var/www/vhosts/example.com/system/ee/EllisLab/ExpressionEngine/Model/Channel/ChannelEntry.php on line 795
```

When changing the Channel of an Entry [from Entry's Options tab] to a Channel with a different Category Group the error above is given.

The Channel is visible to select even though Category Groups don't match, but not visible for example if Field Groups don't match (as expected for Field Group mismatch).

**How To Reproduce**
Create 2 Category Groups (mine were empty).
Create 2 Channels with the same settings (except Category Group).
Assign each Channel a different Category Group.
Create an Entry in each Channel (mine just had Title/url_title as content).
Then change the Channel of one of the Entries (at this point I'd expect to not be able to - due to Category Group mismatch).
Save Entry.
Error.

**Environment Details:**
 - EE Version: [5.3.0]
 - PHP Version [7.1.33]
 - OS: [OSX 10.15.3]
 - Browser [Firefox 73.0.1]

**Comment by intoeetive** [comment]
This error appears to be non-existent when using latest EE6 code.

Since EE5 is only receiving security updates at this point, closing the issue
