### ISSUE TITLE
Limit variable modifier removes Wygwam RTE elements

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#3811]
**Description of the problem**
Apply the :limit variable modifier to a field containing RTE text (in this case from Wygwam) and in the process of applying the limit the variable modifier removes all styling tags (e.g. `<b></b>` etc.).

**Environment Details:**
 - Version: 7.3.12
 - PHP Version 8.1

**Comment by intoeetive** [comment]
This is actually intended behaviour. We strip the tags to make sure the desired number of character is actually displayed (and not is taken by non-visible HTML tags) and there is no broken markup included.

If you have  a need for modifier that would preserve HTML, please open a feature request.

**Comment by jcogs-design** [comment]
Well that's one solution for sure (it is not a bug it is a feature)
If you think that is the best solution, then might I suggest you think to document this - currently the docs for this variable modifier are mute on this 'feature' of the operation.

**Comment by intoeetive** [comment]
definitely need to document this, thank you!
