### ISSUE TITLE
Bug: Deprecation Warning - Passing Null to Parameter #1 in str_pos()

### ISSUE THREAD

**Issue by akolinski** [ExpressionEngine/ExpressionEngine#3813]
**Description of the problem**
I encountered a deprecation warning in ExpressionEngine when using the str_pos() function, where null is being passed to parameter 1. This issue may need attention as it can potentially disrupt the expected behavior of the function on the front end of the website.

**How To Reproduce**
Seeing it on the frontend of the website when logged in as an admin with output and debugging turned on.

<img width="1089" alt="Screenshot 2023-10-11 at 10 47 25 am" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/5883593/9f25ef74-9159-4132-b220-3c64d48f49ae">

**Error Messages**

```
Deprecated
strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
ee/legacy/libraries/Typography.php, line 565
Severity: E_DEPRECATED

Deprecated
strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
ee/legacy/libraries/Typography.php, line 565
Severity: E_DEPRECATED
```

**Environment Details:**
 - Version: 7.3.12
 - PHP Version 8.2
 - MySQL Version 8
 - OS: Linux
 - Web Server: Apache

**Comment by intoeetive** [comment]
Is there a chance you could narrow it down to using specific template tag / field?

**Comment by akolinski** [comment]
@intoeetive we are using this channel entries tag 

`{exp:channel:entries channel="scholarship-2018" url_title="parents" dynamic="off" limit="1" disable="member_data|pagination|trackbacks"}`

**Comment by intoeetive** [comment]
Sorry, I wasn't clear enough. I am interested to see the minimal template code that we can use to replicate the problem
