### ISSUE TITLE
TypeError: Cannot read property 'label' of undefined (Line 171)

### ISSUE THREAD

**Issue by amici-infotech** [ExpressionEngine/ExpressionEngine#382]
**Description of the problem**

I had the weired issue on my EE site today. in MSM sites, File field not working. it shows me error on 171 line.

**How To Reproduce**

I have had many file fields including normal and in Grid. In main site, it works good. However in MSM site I get this error.

**Environment Details:**
 - Version: [5.3.0]
 - PHP Version [7.1]
 - OS: Linux
 - Web Server: Apache

**Possible Solution**

I found suspected code in file: themes/ee/asset/javascript/compressed/fields/file/drag_and_drop_upload.js

where it says:
<pre><code>
{
    key: "getDirectoryName",
    value: function(e) {
        return "all" == e ? null : (e = EE.dragAndDrop.uploadDesinations.find(function(t) {
            return t.value == e
        }), e.label)
    }
}
</code></pre>

e.label is not exists. I return e and it work for me.

![image](https://user-images.githubusercontent.com/20450552/76384048-d2fec900-6383-11ea-9c66-f7d354dca98c.png)

**Comment by CapitalZ** [comment]
Having the same issue at the moment. Hope someone has a fix. 👍

**Comment by amici-infotech** [comment]
@CapitalZ solution is added in the thread already
