### ISSUE TITLE
Add relative "/" option to URL field under Field Options > Allowed URL Schemes

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#384]
Sometimes in a URL field, we need the ability to enter a URL relative to the site but we can't - the only options are the typical protocols and a // option, but none of these options allow the user to add a link to say:

`/my-page#my-anchor`

Please add an option for a URL scheme that starts with a single / to the 'Allowed URL Schemes' checkbox list in the Field Options when setting up a URL field.

**Comment by blue-dreamer** [comment]
I agree, relative URL should be an option for the URL field. 

There are times when you need to use relative URL's for adding internal links. Using a text field is fine but it allows for spaces etc which can make a link fail. The URL field would allow some sort of validation.
