### ISSUE TITLE
Issue with 7.3.11 Unable to drag/drop change order of fields in field groups

### ISSUE THREAD

**Issue by JimStrive** [ExpressionEngine/ExpressionEngine#3840]
Issue with 7.3.11 Unable to drag/drop change order of fields in field groups

**Comment by robinsowell** [comment]
If you open the browser tools, are you getting any javascript errors?  Also, just so I'm sure where you are, what's the url look like?  (no need to include domain/admin.php bit)

**Comment by JimStrive** [comment]
My issue was resolved in 7.3.13

**Comment by robinsowell** [comment]
Glad they got you squared away.
