### ISSUE TITLE
An entry titled "Selçuk Ören" cannot be created when `Enforce automatic URL title` is enabled

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#3841]
EE 7.3.12

How to reproduce:

1. Enable `Enforce automatic URL title` option in channel settings
2. Try to create a new entry, with title `Selçuk Ören`.

Video:
[video-convert-1697647638117.webm](https://github.com/ExpressionEngine/ExpressionEngine/assets/12234507/48a76c6f-3580-4f91-948c-09afe628c492)

**Comment by intoeetive** [comment]
@shbchk looks like capital "O umlaut" was missing from the built-in foreign characters config.

However be aware that you can always extend this by adding your own config files: https://docs.expressionengine.com/latest/config/config-files.html#foreign-characters

**Comment by shbchk** [comment]
Found another one: "Academy Award®"

`®` symbol also throws an error. 

I think it should not be this way. If the symbol is not in config, it should be ignored, not breaking things :)

**Comment by intoeetive** [comment]
The fix is getting released in EE 7.4.0
