### ISSUE TITLE
Can't access any field's editing screen in control panel

### ISSUE THREAD

**Issue by gabbathehutt** [ExpressionEngine/ExpressionEngine#3842]
**Description of the problem**

I cannot access the Field editing screen from the Fields page in the Control Panel (https://guicreative.com/admin.php?/cp/fields&perpage=214)

I get the error below.

I believe this may well be something to do with upgrading from EE2 about six months ago, as I have had similar problems upgrading another site. I did not notice this recently and the site has been significantly developed since then.

**How To Reproduce**
- try to open any field in Control Panel

**Error Messages**

<pre><code>
Exception Caught
Unknown field ChannelEntry.field_id_11
ee/ExpressionEngine/Service/Model/Query/Select.php:709

Stack Trace: Please include when reporting this error
#0 ee/ExpressionEngine/Service/Model/Query/Select.php(520): ExpressionEngine\Service\Model\Query\Select->translateProperty('field_id_11')
#1 ee/ExpressionEngine/Service/Model/Query/Select.php(124): ExpressionEngine\Service\Model\Query\Select->applyOrders(Object(ExpressionEngine\Service\Database\Query), Array)
#2 ee/ExpressionEngine/Service/Model/Query/Select.php(49): ExpressionEngine\Service\Model\Query\Select->buildQuery()
#3 ee/ExpressionEngine/Service/Model/DataStore.php(275): ExpressionEngine\Service\Model\Query\Select->run()
#4 ee/ExpressionEngine/Service/Model/DataStore.php(220): ExpressionEngine\Service\Model\DataStore->runQuery('Select', Object(ExpressionEngine\Service\Model\Query\Builder))
#5 ee/ExpressionEngine/Service/Model/Query/Builder.php(150): ExpressionEngine\Service\Model\DataStore->selectQuery(Object(ExpressionEngine\Service\Model\Query\Builder))
#6 ee/ExpressionEngine/Service/Model/Query/Builder.php(63): ExpressionEngine\Service\Model\Query\Builder->fetch(false)
#7 ee/legacy/fieldtypes/EE_Fieldtype.php(845): ExpressionEngine\Service\Model\Query\Builder->all()
#8 ee/legacy/fieldtypes/OptionFieldtype.php(548): EE_Fieldtype->_get_field_options(Array)
#9 ee/legacy/libraries/api/Api_channel_fields.php(381): OptionFieldtype->getPossibleValuesForEvaluation(Array)
#10 ee/ExpressionEngine/Model/Content/FieldFacade.php(307): Api_channel_fields->apply('getPossibleValu...', Array)
#11 ee/ExpressionEngine/Model/Content/FieldModel.php(73): ExpressionEngine\Model\Content\FieldFacade->getPossibleValuesForEvaluation()
#12 ee/ExpressionEngine/Controller/Fields/Fields.php(884): ExpressionEngine\Model\Content\FieldModel->getPossibleValuesForEvaluation()
#13 ee/ExpressionEngine/Controller/Fields/Fields.php(476): ExpressionEngine\Controller\Fields\Fields->form(Object(ExpressionEngine\Model\Channel\ChannelField))
#14 [internal function]: ExpressionEngine\Controller\Fields\Fields->edit('22')
#15 ee/ExpressionEngine/Core/Core.php(266): call_user_func_array(Array, Array)
#16 ee/ExpressionEngine/Core/Core.php(122): ExpressionEngine\Core\Core->runController(Array)
#17 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#18 admin.php(144): require_once('...')
#18 admin.php(144): require_once('...')

</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 6.4.14
 - PHP Version 7.4
 - MySQL Version 5.7.43-cll-lve
 - OS: Windows
 - Web Server: Apache

**Possible Solution**

**Additional context**

**Comment by intoeetive** [comment]
@gabbathehutt theres seems to be something broken in your specific installation

I would start with manually clearing your system/user/cache folder

Does this happen with any field, or a specific one?

**Comment by intoeetive** [comment]
Closing as we did not receive further details
