### ISSUE TITLE
Error The page you requested was not found

### ISSUE THREAD

**Issue by paultz** [ExpressionEngine/ExpressionEngine#3848]
Hi,
  I am still getting the Error - "Error The page you requested was not found" which i had addressed it in https://github.com/ExpressionEngine/ExpressionEngine/issues/3591 but got no solution or suggestions! 

I am Getting this error on either Saving a Template or a Saving a Post using RTE field (Most of the Time if i copy paste text from Word Doc or Justify Text etc.), it stated when the server was upgraded to Php 8.0. Also NOTE that this error sometimes does not happening and i can save posts

Could i get any feedback or steps i should follow to resolve this issue? 

**See screenshot and url:**
![error_page_not_found](https://github.com/ExpressionEngine/ExpressionEngine/assets/3635179/72d0806f-5adc-45b0-8b39-5cda7033fc0a)

**EE & Hosting Environment:**
EE 6.4.15
Php 8.0
Apache Version 2.4.57
MySQL Version 5.7.42
Architecture x86_64
Operating System linux

**Comment by intoeetive** [comment]
@paultz thank you for reaching to us again.

Looking at how the error is styled, this seems to be front-end error, so assuming it's hitting the wrong endpoint (index.php instead of admin.php)

Most likely you're getting this error because your configured Control Panel URL is not correct. Can you confirm that your `system` folder was renamed to `admin` and it contains `index.php` file, and that file is the one that's distributed with EE in `system` folder?

You can set the correct value in Settings -> URL and Path Settings.

Since this seems to be not a bug, but a configuration issue, you might get faster help from the community in [Slack chat](https://expressionengine.com/blog/join-us-in-slack) or [Forums](https://expressionengine.com/forums)

**Comment by paultz** [comment]
Hi, In Both admin.php and index.php system file has being renamed to admin,  $system_path = './admin'; 
and System Folder Renamed to 'admin', in CMS, 'Settings -> URL and Path Settings is set to /home/site/public_html/

Paul

**Comment by intoeetive** [comment]
So as you can see, the redirect is taking user to `/admin/index.php` while you likely want it to go to `/admin.php`

I would suggest to check this setting: 
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/752126/9c5ff426-4518-4984-bfa3-82b32793af06)

If it is correct, there might be an extension changing this - try temporary turning off extensions with [configuration override](https://docs.expressionengine.com/latest/general/system-configuration-overrides.html#allow_extensions) to see if that helps

Lastly, you may also just have a look at your `admin/index.php` file - most likely it's either wrong file or has wrong system directory set in it. For most of hosting providers, just replacing it with the one from EE distribution zip in `system` folder should work.

I'll have to close this ticket as we generally don't provide support over GitHub - please proceed to Slack or Forums if you need further help.

Thanks!

**Comment by paultz** [comment]
I have also posted this issue in Slack but still No Answer or Solution to Follow!, however I have done what you have recommended but still the Same Error!
**URL to your Control Panel index page**: {base_url}admin/index.php also changed to {base_url}admin.php 
also $config['allow_extensions'] = 'n'; 
also uploaded new index.php and admin.php files and change $system_path = './admin'; 
But Still Getting the Same Error!

**Comment by robinsowell** [comment]
So it sounds like it could actually be a mod_security issue.  They can be really weird.  A couple things you can do- check with the host, see if they have mod_security or a similar filter, check the logs, see if it's catching your post.  Another thing I do- copy the form that's triggering the error- everything from ```<form>``` to ```</form>``` including your content.  Do 'view source' to find it.  Put that in a seperate php file myform.php or whatever.  Change the action="" so it's just posting back to itself.  This now has nothing to do with EE at all.  Submit, see what happens.  If it goes weird, you've got a server issue.

I usually put

```<?php var_dump($_POST); ?>```

I put that at the top.  If everything is normal, you end up on the same page with everything you posted showing in a big mess.  If you ended up with nothing or on some weird page- the filter is messing with it.

**Comment by paultz** [comment]
I have gone through your steps on finding out the issue, see below

![Submitting_a_Form_3](https://github.com/ExpressionEngine/ExpressionEngine/assets/3635179/74096d12-c30b-48e0-8c05-f88d560cb40f)
(This the source form from my EE Posting page)

![Submitting_a_Form_3a](https://github.com/ExpressionEngine/ExpressionEngine/assets/3635179/23f62c09-7db9-49f0-a45e-d93beb286eff)
(This is the Error I a getting upon Submitting)

![Submitting_a-Normal_Form4](https://github.com/ExpressionEngine/ExpressionEngine/assets/3635179/eee4e36a-40ba-4dca-ab30-42eca93fb384)
(This is  a very simple independent form that i have tried to submit  without error)

![Untitled-1](https://github.com/ExpressionEngine/ExpressionEngine/assets/3635179/7f456c21-696f-4b42-b41f-51a9b9db39e2)
(This is the same EE form that i had submit outside ee inside ee files but still gave me error)

So as you have said maybe this is being coursed by "mod_security or a similar filter" can we do anything on ee? maybe on special character or we have to consult our host?

**Comment by robinsowell** [comment]
I do lean toward it being a server security filter.  There really isn't anything you can do in EE to alter it.  Not if it's jamming up creating entries and such.

You'll want to reach out to your host and let them know you're having an issue posting forms and ask if they can alter the security rules to allow it.  Use the standalone example to show them what's going on.  That will be simpler.
