### ISSUE TITLE
URL parameters from Entries list get appended to Entry links

### ISSUE THREAD

**Issue by swierczek** [ExpressionEngine/ExpressionEngine#3850]
**Description of the problem**
If you're on the Entries list (Entries > View All) and have any sorting/filtering URL parameters (e.g. `/admin.php?/cp/publish/edit&filter_by_keyword=&search_in=titles_and_content&perpage=25&sort_col=column_title&sort_dir=asc`), then the link to the Entries get the URL parameters appended to them too.

<img width="1410" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/2423727/dd4a0328-f540-4e8f-a15b-caad0e8d37cb">

And clicking on any entry then loads the URL with additional parameters. e.g. `/cp/publish/edit/entry/2&search_in=titles_and_content&perpage=25&sort_col=column_title&sort_dir=asc&filter_by_keyword=` when it should just be `/cp/publish/edit/entry/2`

**How To Reproduce**
1. Click Entries (or Entries > View All)
2. Sort the table or use any of the filters so the URL on this page gets updated with URL parameters
3. Hover/click on any entry title

**Environment Details:**
 - Version: 7.3.13

**Comment by intoeetive** [comment]
This is a feature, not a bug. We do this to identify correct return URL after saving entry.

Is there a reason why this is problematic for you?

**Comment by swierczek** [comment]
Oh interesting, is that for when a user clicks "Save & Close"? It is causing a slight issue with some custom functionality we built that utilizes a custom URL parameter that now persists across entry saves, but we can make a change to work around that knowing this is intended behavior.

**Comment by intoeetive** [comment]
Yes, that for redirect after "save & close"
