### ISSUE TITLE
File field permission issue

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3857]
I feel like I'm missing a setting, but I've triple checked.  I'm testing on 7.3.14 but issue came up for a user on earlier issue (his is slightly more complex, I've simplified).

I made a user role 'Admin' with access to 2 channels- About and Admin_ch.  I made a file field called dos_files.  Allowed directory is 'Blog', 'All Files' allowed.

That file is only assigned to the Admin_ch channel and is the only field assigned.  (Originally it was also assigned to a different channel the Admin was not allowed to post to, but I removed that one and it didn't alter the behavior.)

Blog directory has Admin role allowed.  That is the only directory they are allowed.  They do not have permission to access the file section.

If I try to make an entry in Admin_ch logged in as Admin user, the entry comes up fine but when I upload I get a permission error.  If I try to use an existing image, the directory comes up empty.

<img width="1083" alt="Screenshot 2023-10-23 at 5 49 51 PM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/1181219/19238bff-060c-41a0-841d-563c6d654554">

<img width="1655" alt="Screenshot 2023-10-23 at 5 49 59 PM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/1181219/e1667512-281e-4e33-a525-26ee35f71e73">

I have trouble believing this hasn't already come up, but I'm not spotting it and I'm not spotting a setting I missed.  So.  Here we are.

**Comment by intoeetive** [comment]
I think this is correct permission-wise, because the member does not have File Manager permissions

But we need to:
- not render the upload component, but show appropriate warning instead (similar to what we already did for MSM)
- document the fact that File Manager permissions are required to work with File fields

**Comment by robinsowell** [comment]
AH you're right.  I gave them permission to access file manager and then explicitly the blog directory and upload access and then it worked.  I think I'll close this and make a new bug report about it showing even when they have no access, as that's both a more minor bug and for clarity.
