### ISSUE TITLE
UI issue on moblie on Entry page

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3860]
So... this one is a bit of a bear to reproduce.  I've only seen it happen with Publisher add-on in use:

![EE_Admin](https://github.com/ExpressionEngine/ExpressionEngine/assets/1181219/bf86ad01-ee6c-4daa-ac23-48cdb0a3824c)

It's jamming the user, as "when trying to edit EE entries on a small screen, the “View (Published)” and “Save As (Draft)” buttons are really unusable. They are both inside a single container that does not expand. "

The reached out to Publisher/BM about it, but per them, it's actually an EE Core issue, as Publisher is using all the built in styles and markup for these elements.

But... you pretty much have to install Publisher to actually see the issue, at least from me experimenting around on my tiny phone.

**Comment by lnicely** [comment]
Just opened up a PR that should take care of this. It adds some padding below those buttons on mobile devices so that the dropdown options are visible

**Comment by robinsowell** [comment]
Awesome and thanks!  @lnicely

**Comment by bryannielsen** [comment]
This should be resolved now in version 7.3.15
