### ISSUE TITLE
Field groups in fluid fields explode when cloning an entry with the "clone to new entry"

### ISSUE THREAD

**Issue by JimStrive** [ExpressionEngine/ExpressionEngine#3865]
In 7.3.13 Field groups in fluid fields explode when cloning an entry with the "clone to new entry".

Starts like this
![image_720](https://github.com/ExpressionEngine/ExpressionEngine/assets/122804428/34762fc4-e493-4d0b-b2e0-bba9c145899e)

Ends like this
![image_720](https://github.com/ExpressionEngine/ExpressionEngine/assets/122804428/9cb3623f-5492-4c33-9865-40831dce0dd2)

**Comment by TomJaeger** [comment]
tested and confirmed

**Comment by JimStrive** [comment]
@intoeetive I applied these changes manually to v7.4.13 and it didn't fix the problem, the groups are still exploded after duplication.

**Comment by giganticdesignco** [comment]
I am also experiencing this issue in 7.3.14.

<img width="934" alt="Screenshot 2023-12-20 at 2 38 57 PM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/35230750/ff85d993-4625-4713-b4a4-6ee38b42e0ca">
<img width="931" alt="Screenshot 2023-12-20 at 2 39 24 PM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/35230750/7406f957-6868-41ef-966b-91c029ff58af">
