### ISSUE TITLE
@ suppression makes tracking down root problems difficult

### ISSUE THREAD

**Issue by tjdraper** [ExpressionEngine/ExpressionEngine#388]
I ran into an issue this week where I was getting a `File not allowed` error when uploading jpg files. Strangely this did not affect pngs.

![image](https://user-images.githubusercontent.com/3803475/77659130-a92dd080-6f45-11ea-98da-b7c84c36bc00.png)

I checked all the settings I could think of. PHP and NGINX file upload limits were high. So I started combing through the codepath with xdebug breakpoints. It took a while, but I finally arrived at the file `system/ee/EllisLab/ExpressionEngine/Library/Mime/MimeType.php` where there was an `@` error suppression hiding out.

![Annotation 2020-03-26 090725](https://user-images.githubusercontent.com/3803475/77659268-d8dcd880-6f45-11ea-90e8-aad1983a7a8f.png)

This means, of course, that the error happening here can NEVER be caught. Not in dev, not with error reporting cranked up. Never.

Removing the `@` suppression revealed the real problem was that somehow in my dockerfile I fudged it up and the PHP instance does not have JPEG manipulation built into it.

![jpeg](https://user-images.githubusercontent.com/3803475/77659431-0d509480-6f46-11ea-930b-7e8232e91f30.png)

But that was very difficult to determine because of the `@` suppression there was no way to see what the root cause was, which caused, ultimately, an incorrect error to be reported in the CP. It wasn't a file not allowed issue, it was a problem with PHP.

There are lots of `@`s in EE's code and those should be removed. Perhaps can be replaced with try/catch and in devmode or with a config setting of some kind the exception can be allowed to bubble up.

**Comment by intoeetive** [comment]
@tjdraper I totally get your point! I do have a suspect however that `@` was added to suppress notices, which are not uncommon with PHP image manipulation depending on how server is set up.

While we will probably not be touching the working code here, in the new code that we write we try - and will be - to avoid `@` suppression.
