### ISSUE TITLE
Bringing back all language files into the expressionengine repo (see comment)

### ISSUE THREAD

**Issue by ebeauchamps** [ExpressionEngine/ExpressionEngine#39]
Please bring back all language files repo from github/ellislab to github/expressionengine

BUT: make sure you fully own the procedure for maintaining the ENGLISH repo as the way it is currently managed is the sole and right way for translators to be aware of the changes being made between versions.

**Comment by derekjones** [comment]
That's the plan, @ebeauchamps! The repos have always been public and linked from the user guide, so it's a lower priority to change GitHub orgs. As far as procedure/control, we still maintain control over all processes; no code can be committed or merged without project owner approval.

**Comment by ebeauchamps** [comment]
👍🏻
