### ISSUE TITLE
Inbuilt check to prevent duplicate category_url_title 

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#390]
**Is your feature request related to a problem? Please describe.**
Where you have multiple category groups assigned to a channel it's possible to use the same category_url_title in each group. This can then cause problems displaying the correct content in a category view.

**Describe the solution you'd like**
Prevent a duplicate category_url_title from being used. If creating or renaming a category_url_title EE should flag this up, i.e. "The url title is already in use" and prevent saving until it has a unique value.

**Comment by TomJaeger** [comment]
After some internal discussion on this one as a whole. We believe this would be a breaking change, as it's been long standing that EE blocks duplicates on a per group level, but you can have duplicates in different groups.  

We discussed some other options around this as well (making it configurable, showing a warning etc.).

We ultimately decided this is something we will aim to address in a larger Category update scope.

Closing this for now.
