### ISSUE TITLE
Main entry manager counting and pagination not right.

### ISSUE THREAD

**Issue by DalizPR** [ExpressionEngine/ExpressionEngine#3921]
The default view (count and showing) of the Main entry manager is off. Normally we would see the first  25 entries of a channel and with the pagination we can see how many entries there are in the channel. But with my default view only the first 4 are shown. 
When i select 25 to be shown only 12 are shown, etc. 
Also the total number of entries doesn’t seem to be right. 
And the pagination isn’t consistent first page has 4 entries, second has 8, third has 6…

_I have imported entries using Data Grab. Had to delete a significant amount of them to._ 

![scherm__afbeelding_2023-11-30_om_11 13 43](https://github.com/ExpressionEngine/ExpressionEngine/assets/19518007/230cfa32-84e6-4ddb-8e13-4ba707d6067a)

<img width="931" alt="Scherm­afbeelding 2023-11-30 om 17 32 44" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/19518007/c65c7910-f061-48a0-99fe-b289612b8305">

In my screenshot it says there are 79 entries there are actually 25.

**Environment Details:**
 - Version: [7.14]
 - PHP Version [8.0.30]
 - MySQL Version [e.g. 5.7]
 - OS: [e.g. Linux, macOS]
 - Web Server: [e.g. Apache.]

**Possible Solution**
Inspecting the page shows a DOM-error/warning.

**Comment by intoeetive** [comment]
@DalizPR thank you for reporting.

This is a know issue and has been reported in https://github.com/ExpressionEngine/ExpressionEngine/issues/987

None of the entries is lost, it's just they are not paginated evenly when Categories column is present.

I'll close this issue as duplicate, if you want to comment please do so on #987
