### ISSUE TITLE
When Redactor / CKEditor RTE opened in modal, Link Edit button doesn't work

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#3928]
**Description of the problem**
If you open an RTE Field in Channel Forms, and that opening happens from within a modal (e.g. Bootstrap) the 'link' button in the toolbar is non-operational. Clicking on the button has no apparent effect - apart from the button itself greying out.

Upon digging deeper it turns out the pop-up menu that determines what action is performed on the link is being created, but is appearing "behind" the modal. Changing the menu's CSS z-index to a high value (2000 seems to work) results in the menu being displayed.

Sample rule to fix appearance of link pop-up menu when called for from instance in a modal: 
```
.reactor-dropdown.reactor-dropdown-link {
    z-index: 2000 !important;
}
```
However adding this extra bit of CSS to the page only results in the menu being shown. If you then choose to edit the link then a second modal is opened containing the text / link to edit - this again appears "behind" the modal the text / RTE Field is being displayed in. 

You can make the edit modal appear using the same `z-index` trick - however this is not so helpful, as once you can see the edit box, **you find that the fields it contains are not editable** - looking via an inspector it looks like the 'contents' of these fields are held somewhere in the page DOM rather than being attached to the HTML - so the content of the two fields (text, link) is not present in the fields when viewed via a browser "inspector".

**How To Reproduce**
Put a Channel Form set to edit an RTE field into a modal, open the modal.

**Screenshots / Videos / Template Code**
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/43bab12a-0fb2-40bc-a1f5-6bfdc9179eb1)
"Redactor Basic" RTE field open in a modal with "link" button selected after cursor put into the "link text" visible. Note no pop-up menu... 

![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/d98486e2-11d9-4605-86cd-dae7913a6fed)
Same view after CSS rule to promote z-index of menu item to 2000 added.

![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/0672be56-0909-43a3-bbef-97431f06563b)
Same view after the "Edit Link" option chosen - note the 'edit modal' is now hiding behind the main modal

![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/d30b0aec-4e08-4f92-9ef9-0088b777bd89)
Same view after CSS Rule to promte the z-index of the "Edit Modal" to 2051 added.

**Environment Details:**
 - Version: 7.3.13 // 7.4.0dp33
 - PHP Version 8.1

**Possible Solution**
Clearly adding some CSS to promote the z-index of the two elements is helpful, but some more deep-seated work will be required to find out why the two text fields that appear are not then editable.

**Context**
Tested in both Firefox Developer (v 121.0b7) and Safari (17.1.2) browsers on mac.

**Comment by Yulyaswan** [comment]
I pushed changes about z-index, and now link popup is visible 
changes in 7.4 release

https://github.com/ExpressionEngine/ExpressionEngine/assets/23382425/8ea22407-8d03-41a0-b93e-71b54aa86eca

`the fields it contains are not editable` - this is more of a problem between CKeditor and Bootstrap.
below I added an example of how to fix it
https://stackoverflow.com/questions/41121577/ckeditor-link-input-not-working-in-modal

close this issue and #3929
