### ISSUE TITLE
When RedactorX RTE opened in modal, link edit fields do not work

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#3929]
**Description of the problem**
If you open a RedactorX RTE Field in Channel Forms, and that opening happens from within a modal (e.g. Bootstrap) the edit fields of the dialog box that appears are non-operational. 

**How To Reproduce**
Put a Channel Form set to edit a RedactorX RTE field into a modal, open the modal.

**Screenshots / Videos / Template Code**
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/6fcdb372-1b86-4a7b-8bec-6a889ba76510)
RedactorX Basic RTE within a (Bootstrap5) modal - edit link menu appears when you click on link button in menu bar

![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/224e6093-bfbb-4f9a-ae02-ba8ae08e0818)
RedactorX Basic RTE Link Edit modal showing above a Bootstrap 5 modal with details of link and link text showing. 
Neither field is editable (as in you cannot click on either field and change content).

**Environment Details:**
 - Version: 7.4.0dp33
 - PHP Version 8.1

**Possible Solution**
Some work will be required to find out why the two text fields that appear are not editable.

**Context**
Tested in both Firefox Developer (v 121.0b7) and Safari (17.1.2) browsers on mac.

**Comment by Yulyaswan** [comment]
left comment in #3928

**Comment by jcogs-design** [comment]
Thanks - the `data-bs-focus="false"` fudge suggested in thread you linked to worked.
Now just need to fix the initialisation thing and RedactorX will be good to go I think 👍
