### ISSUE TITLE
Channel Form styling interferes with text rendering in RedactorX 

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#3932]
**Description of the problem**
Channel Form sets a number of text styles via a custom CSS entry.
These custom styles include `<em>` and `<a>`.
The definition of these styles is very broadly based, setting font, font size, display format and margins - vis: 
```
.ee-cform em, .ee-cform h3 {
	font-family: Helvetica,Arial,Sans-Serif;
	font-size: 16px;
	font-weight: 700;
	margin: 0;
}

.ee-cform em {
	font-weight: 400;
	display: block;
	margin-bottom: 20px;
}

.ee-cform a, .ee-cform b, .ee-cform code, .ee-cform dd, .ee-cform dl, .ee-cform dt, .ee-cform h1, .ee-cform h2, .ee-cform h3, .ee-cform h4, .ee-cform h5, .ee-cform h6, .ee-cform i, .ee-cform input[type="file"], .ee-cform li, .ee-cform mark, .ee-cform ol, .ee-cform p, .ee-cform pre, .ee-cform ul {
	background-color: transparent;
	border: 0;
	bottom: auto;
	color: #000;
	font: normal normal 14px Helvetica,Arial,Sans-Serif;
	left: auto;
	margin: 0;
	padding: 0;
	position: relative;
	right: auto;
	top: auto;
}
```
These styles are applied to any content in a RedactorX RTE field, leading to an anomalous appearance of the rich text.

![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/a01d38c6-99fa-479d-a839-7b005553fa6e)
Text in an RedactorX RTE field affected by the CF introduced styling elements.

![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/3f63b711-cd17-4001-a63f-1007022a54cf)
Text in a RedactorX RTE field after CF introduced styling elements have been removed.

**How To Reproduce**
Example above should be sufficient to allow issue to be reproduced.

**Environment Details:**
 - Version: 7.4.0dp33
 - PHP Version 8.1

**Possible Solution**
Improve the specificity of the definition of styles used by Channel Form to limit their action to only Channel Form elements.

**Comment by Yulyaswan** [comment]
made changes for `ee-cform`, removed specific styles for some common elements
changes for 7.4

**Comment by jcogs-design** [comment]
You didn't catch them all ... 
```
.field-control em {
	display: block;
	margin-top: 5px;
	font-size: 12px;
}
```
In EE7.4.0 dp 35
