### ISSUE TITLE
RedactorX - Issue with initialising javascript

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#3939]
**Description of the problem**
RedactorX is good, but seems to have a problem loading itself.
When a RedactorX field is loaded you get some of the toolbar elements showing OK, but others are missing.
Interactive functions for RedactorX are also missing after initial load.
If you toggle the "HTML View" mode on / off, upon resuming after the toggle the editor now has the full complement of toolbar buttons and contextual actions are now working correctly.

**How To Reproduce**
I setup a standard RTE field (accessed via a fluid field) and assigned the RedactorX RTE to it.
When you first load an entry that is in the channel with the field, the RTE editor "sort of" loads. This example image is taken from a Safari instance, but same happens in Firefox Developer. This field is using the default "RedactorX Full" toolbar set.
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/1e091055-a4ff-4dc8-9513-ea859fcab503)

In this mode, most of the toolbar icons do not work - in particulary the "styles" menu does not apply styles etc.

If I then toggle into HTML view I see this kind of display:
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/e56093ea-ecbb-4ea8-9ca4-e1ee6193be4e)

I can edit the HTML and the changes are 'remembered' when I leave this mode.
However when I leave this mode I also see that the main toolbar has gained many tools (the ones defined under "plugins" in RTE configuration). You can also see that the 'context marker' has appeared in the LH column of the editor window.
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/2e3299e3-908c-4bdf-84cf-bc4b505e9bb1)

Now, the styles menu works as it should, when I highlight text the 'context' menu appears, and if I click on the context-marker the "context menu" appears. 
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/433d1882-8c30-4480-a2bf-f9bf935422d3)
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/c120c94a-3228-45d1-9c1c-27ecddb0a9a8)

**Environment Details:**
 - Version: 7.4.0dp33
 - PHP Version 8.1

**Possible Solution**
It looks like that the RedactorX RTE is not fully initialising itself when it loads, but when you toggle in / out of HTML view mode, when returning RedactorX 'resets' its edit window Javascript and the tools initialise properly.

**Additional context**
Tested in Firefox Developer 121.0b7 and Safari 17.1.2 with identical results.
No apparent javascript errors showing in browser inspector view.

**Comment by intoeetive** [comment]
I wasn't able to replicate this in Firefox 120. What other fieldtypes do you have on the entry page?

**Comment by jcogs-design** [comment]
Here is the whole page view - the entry comprises:

- A fluid field "Site Page Content" that currently has a grid, an image and a toggle field selected in addition to the RTE field which is showing the anomalous behaviour
- A text field.
HTH
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/aaa14965-ecf8-409b-8f70-1d5a90bd0fed)

**Comment by intoeetive** [comment]
@jcogs-design just to confirm, if you create a channel that only has RTE field and create entry in it - do you still have this issue?

**Comment by jcogs-design** [comment]
Found it 🥳 - removing Wygwam (and then clearing all local browser caches) does fix the issue.
Presumably this is some kind of conflict between the initialisation code for Wygwam and RedactorX.
