### ISSUE TITLE
Undefined variable $memory_gain (stability branch)

### ISSUE THREAD

**Issue by croxton** [ExpressionEngine/ExpressionEngine#394]
https://github.com/ExpressionEngine/ExpressionEngine/blob/e3c42afffebbd3351498bb37309718e34ba9e11f/system/ee/legacy/libraries/Template.php#L3541

Looks like the code that defines `$memory_gain` was lost in a recent commit. Below the line referenced should presumably be:

```php
$memory_gain = $memory_usage - $last_memory;
```

**Comment by dougblackjr** [comment]
@croxton This should be fixed in here: https://github.com/ExpressionEngine/ExpressionEngine/pull/395#event-3219655720

If you pull `stability`, it should include the fix for this. Can you check?

**Comment by croxton** [comment]
All good!
