### ISSUE TITLE
7.4DP - RedactorX erases styling upon re-loading RTE content

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#3941]
**Description of the problem**
RedactorX is a good thing. However it appears to erase styling from RTE content when loading it into its edit window. 
You can add styling to a block of RTE text and it is saved when you save it.
However if you then re-open the RTE text field, all styling is removed from the loaded content: if you then save this field the saved content effectively has all styling removed.

**How To Reproduce**
These are described / illustrated in attached video clip.

**Screenshots / Videos / Template Code**
[Linked Video](https://www.icloud.com/iclouddrive/0e7yltO9L0nT-t2wWPVJXoF5A#Screen_Recording_2023-12-07_at_15.36)

**Environment Details:**
 - Version: EE7.4.0
 - PHP Version 8.1

**Possible Solution**
I think there is some general bug in the initialisation of RedactorX (see [here](https://github.com/ExpressionEngine/ExpressionEngine/issues/3939)), and unclear if this is related to this initialisation issue, or perhaps is a side-effect of the "HTML View" double-tap you need to do to work around the initialization bug.

**Comment by intoeetive** [comment]
I can partially replicate the issue in Firefox 120

If I apply formatting and then reload the page (without saving) the content shows with the formatting - however the database stays unmodified (as it should) - verified by checking in other browser.
So it looks like there's a sort of cache in Firefox.
The stand-alone examples on RedactorX website do not seem to have this issue

**Comment by jcogs-design** [comment]
I get exactly the same result when using Safari 17.1.2 - so I don't think suggesting this is a Firefox issue is valid here.
I could make / post a video of what is happening when using Safari if you need to see it.

**Comment by jcogs-design** [comment]
Removing Wygwam (which was also installed on the test system) **and clearing browser caches** fixes this issue. 🥳

**Comment by jcogs-design** [comment]
It appears to be caused by interference between the initialisation code for Wygwam (5.4.7) and RedactorX.
