### ISSUE TITLE
File Grid - Edit File icon going to Folder listing, not specific File details

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#3956]
When viewing a list of Images within a File Grid, clicking on the Edit File (pencil) icon takes me to a list of files, rather than the Edit File screen for that particular file.
I'm assuming that's not correct? Not sure.

EE 7.3.14
PHP 8.1

**Comment by intoeetive** [comment]
@ic360-com that is:
a) correct - edit pencil allows you to edit field content, which is "what file is selected"
b) going to be extended in 7.4, where we add "edit file info" button
