### ISSUE TITLE
Color of custom new role its not saved

### ISSUE THREAD

**Issue by avantiz** [ExpressionEngine/ExpressionEngine#3965]
**Description of the problem**

When you create a new custom color role in a new role, the custom color of the role is not saved, returning to #5D63F1.

Steps:

- Create a new role;
- Select a new custom color for this new role;
- Save.

**Environment Details:**
 - Version: 7.4 DP 36
 - PHP Version: Any supported
 - MySQL Version [e.g. 5.7]
 - OS: Ubuntu 22.04 LTS
 - Web Server: nginx

**Comment by intoeetive** [comment]
@avantiz thank you for reporting! We'll get if fixed in the release
