### ISSUE TITLE
Entry screen: Sort doesn't stick when filter added/removed

### ISSUE THREAD

**Issue by nep** [ExpressionEngine/ExpressionEngine#3968]
**Description of the problem**
The current sort column and order do not stick when you apply/remove a filter.

**How To Reproduce**
1. Go to the entry listing and sort by Title, Date, or a custom field. (It appears to drop for any sort)
2. Apply a filter, like Status = Open or choose a Category or apply a Date filter
3. Look and see that the sort order and column have fallen off.

**Error Messages**
No error message.

**Environment Details:**
 - Version: ExpressionEngine 7.3.14 and 6.0.6

**Possible Solution**
No idea. :)

**Additional context**
This is also an issue in the Members section, but it DOES work properly in the Files section of 7.3.14 so maybe you can pull from there?

**Comment by nep** [comment]
Does this also fix the similar issue happening in the Members section?

**Comment by intoeetive** [comment]
@nep I believe the member section as in to-be-released 7.4 does not have this problem
