### ISSUE TITLE
{count} not incremented in variables pairs

### ISSUE THREAD

**Issue by ssssct** [ExpressionEngine/ExpressionEngine#3971]
**Description of the problem**

When outputting an array from an add-on using `ee()->TMPL->parse_variables` the value of `{count}` inside the variable pair is always `1`, no matter how many results the loop outputs.

**How To Reproduce**

1. Create (and install) a simple add-on

```
public function test()
  {
    $vars['powers'] = array(
      array('power' => 'Poisonous Breath', 'scale' => 5),
      array('power' => 'Wealth', 'scale' => 7),
      array('power' => 'Flying', 'scale' => 6)
    );
    $variables = array();
    $variables[] = $vars;
    return ee()->TMPL->parse_variables(ee()->TMPL->tagdata, $variables);
  }
```

2. Create a template to use the addon

```
{exp:my_addon:test}
<ul>
  {powers}
  <li>{count} - {power}</li>
  {/powers}
</ul>
{/exp:my_addon:test}
```

3. The expected result should be:

```
1 - Poisonous Breath
2 - Wealth
3 - Flying
```

6. The actual result is 

```
1 - Poisonous Breath
1 - Wealth
1 - Flying
```

**Comment by ssssct** [comment]
After further testing, I believe none of the [Automatic Variables](https://docs.expressionengine.com/v6/development/legacy/libraries/template.html#automatic-variables)  are working.

Using the following template code:
```
<ul>
  {powers}
  <li>{count}/{total_results} - {switch="one|two|three"} - {power} </li>
  {/powers}
</ul>
```

The expected result should be:
```
1/3 - one - Poisonous Breath
2/3 - two - Wealth
3/3 - three - Flying
```

The actual result is:
```
1/1 - one - Poisonous Breath
1/1 - one - Wealth
1/1 - one - Flying
```

**Comment by intoeetive** [comment]
@ssssct what you see is the correct behaviour. The "automatic variables" are only built for top level of variables array. If you need to have those available for some pair variable, you'd need to do that yourself (also you might want to give some sort of prefix to those, otherwise you'll run into naming conflict)
