### ISSUE TITLE
{exp:member:custom_profile_data} gives PHP deprecation error 

### ISSUE THREAD

**Issue by ssssct** [ExpressionEngine/ExpressionEngine#3975]
**Description of the problem**

Using `{exp:member:custom_profile_data}` in a template gives a PHP deprecation error. 

**How To Reproduce**

1. Create a custom member field
2. Add the [Custom Profile Data Tag](https://docs.expressionengine.com/v6/member/custom-profile-data.html#custom-profile-data-tag) to a template
3. Visit the page
4. See error below

**Error Messages**

<pre><code>
Deprecated
Creation of dynamic property Member::$member_fields is deprecated
ee/ExpressionEngine/Addons/member/mod.member.php, line 2492

Severity: E_DEPRECATED
</code></pre>

**Environment Details:**

 - Version: 6.x
 - PHP Version 8.2
 - MySQL Version 5.7

**Comment by bryannielsen** [comment]
This should be resolved now in version 6.4.16
