### ISSUE TITLE
EE 7.3.14 - Accessing Parent relationships is no longer working

### ISSUE THREAD

**Issue by acutedeveloper** [ExpressionEngine/ExpressionEngine#3980]
**Description of the problem**

I have a clients website that is using {parents} tag in a template. 

We have 2 channels, fabrics and collections.

A fabric has a relationship field to a collection. On a collection template, it is using the parents tag to return fabrics related to that collection.

It was noted that the {parents} tag is returning duplicates of 1 entry.

My EE template code is as follows:

```
{exp:channel:entries channel="collections" url_title="{segment_2}" dynamic="no"}
    {parents}
         {parents:title}
    {/parents}
{/exp:channel:entries}

```

The result is, if there are 10 fabrics, it will loop 10 times, but show the title of one of the entries 10 times.

Strange thing is, if I use `{parents:entry_ids}`, it will list all of the correct IDs.

EE 7.3.14

**Comment by intoeetive** [comment]
@acutedeveloper checked and was not able to replicate with just this code.

I would assume there's some extra factor involved - perhaps you have a field or variable named `parents`? Caching? Embedded templates / layout?
