### ISSUE TITLE
PHP error in <7.4 Use of undefined constant STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3984]
When changing the outgoing email in Settings > Outgoing Email

Warning
Use of undefined constant STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT - assumed &#039;STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT&#039; (this will throw an Error in a future version of PHP)
ee/ExpressionEngine/Controller/Settings/Email.php, line 38
Severity: E_WARNING

Running php 7.3 EE v6.4 and I'd expect the same in ee 7.3.

**Comment by intoeetive** [comment]
Duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/3749
