### ISSUE TITLE
Inconsistent asynchronous saving of Member Roles settings

### ISSUE THREAD

**Issue by swierczek** [ExpressionEngine/ExpressionEngine#3989]
**Description of the problem**

When editing settings on a Member Role, some of the settings unexpectedly save without clicking the Save button. Presumably when it runs the asynchronous validation.

This is on EE 7.3.13.

**How To Reproduce**

Edit any Member Role, go to the CP Access tab, toggle some settings, don't click Save, and then reload the page. The settings will have saved, even though we explicitly didn't click Save.

For example, when the page first loads:
<img width="1552" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/2423727/c3e47071-2afe-43ad-aa22-eab88fa64942">

Then updating a few fields, on field blur you can see the async POST requests, presumably to validate the settings:
<img width="1552" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/2423727/7e69f3fa-6712-488a-82c4-763994c0984a">

And the POST response:
<img width="1552" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/2423727/07a004a5-ae39-49b3-9914-496424f7b2e7">

Without saving the Role, reload the page, and the settings haven't been updated yet:
<img width="1552" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/2423727/f46644a5-f092-401d-8ba3-5139ff9f0b75">

So far so good. But if I go to the `CP Access` tab and do something similar - toggle a few settings, see the async requests, and refresh the page without clicking Save...

Before:
<img width="1552" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/2423727/e3ce0122-4e37-4549-8031-c2ee74a9a3c2">

Toggling some settings - you can once again see the async POST request/response:
<img width="1552" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/2423727/a1f66a6a-e9f8-4491-a8b4-7d643e8d8da1">
<img width="1552" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/2423727/da699053-d190-400d-bf90-beb931ff3136">

But now, refreshing the page without clicking Save, the settings unexpectedly saved:
<img width="1552" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/2423727/d167a3f3-db30-4f2a-8696-1f719533c924">

This is especially problematic because you can accidentally save settings without knowing that you're doing it. Specifically, un/checking any `Channel access` settings also autosave, so it's very easy to add/remove access without intending to.

**Comment by bryannielsen** [comment]
This should be resolved now in versions 6.4.16 and 7.3.15
