### ISSUE TITLE
After updating to 5.3.1: Error when trying to save entry

### ISSUE THREAD

**Issue by bnetz** [ExpressionEngine/ExpressionEngine#399]
**Description of the problem**
I upgraded from 5.3.0 to 5.3.1 . When I create a new entry and try to save it, I cannot save due to an error in the "pages"-tab. I have to enter an URL in the field page-url, then the error vanishes and I can save. But I don't want to enter an URL there, because I don't want to become a blogpost a page.

**How To Reproduce**
Update your installation to 5.3.1

**Screenshot of error**
![200410_error_EE_531](https://user-images.githubusercontent.com/48646646/78981977-63663000-7b21-11ea-8722-a203d7b6efa0.jpg)

**Comment by bnetz** [comment]
stilistical changes in title

**Comment by robinsowell** [comment]
If you have either of those two fields filled in, the other field is required.  Here's the bug the fix addressed: https://github.com/ExpressionEngine/ExpressionEngine/issues/321

I did test to make sure that if I filled in nothing on Pages, I could still save, and I can.  But if either field has something in it, both fields need to have content.  

Or am I misunderstanding what's happening?

**Comment by bnetz** [comment]
What you see in the screenshot is the default-setting (at least for my installation). The default-template for pages is chosen, but the URI-field is empty. This has been for years. When I create a page I enter an URI and this results in the entry being a page; when I don't enter an URI it's a blog post.

When I upgrade to 5.3.1 I get the error; I rolled back to 5.3.0 and everything is fine, see animation attached.

![200410_ee_error-531](https://user-images.githubusercontent.com/48646646/79015597-62f38680-7b6d-11ea-9928-5441bcdbb545.gif)

**Comment by robinsowell** [comment]
AH- once you choose a template, you no longer get the 'Choose wisely' empty option.  And you must have a default template set for that channel.  I don't, so I wasn't running into the problem.

So, we definitely need to get the 'Choose wisely' option to always be available, and I'm wondering if we want to require a template if there's a uri, but NOT require a uri if there's a template.  I can see that one either way.

For the short term, can you switch the channel to not have a default?  And I'll hash out a fix next week.

**Comment by tr0llx4ls** [comment]
Hi,
same problem here.
Don't know how to switch the channel to not have a default. Can you tell us how to do it?
We have seen that if you fill the "Page's URI" field you can continue creating or editing the entry.
Hurry up with the fix please!

**Comment by bnetz** [comment]
Robin, I immediately have rolled back to 5.3.0, so no problem from my side. Would be nice if you fixed the problem.

**Comment by Sungodragon** [comment]
Yes, are starting as  5.3.1 as a base with MySQL 8 and PHP 7.4.4 so we cannot roll back.
Hoping for a hotfix soon.

**Comment by robinsowell** [comment]
OK, we've got a patch up here https://github.com/ExpressionEngine/ExpressionEngine/pull/401

Replace system/ee/EllisLab/Addons/pages/tab.pages.php with the new version and it should do the trick: https://raw.githubusercontent.com/ExpressionEngine/ExpressionEngine/b9d4df927bbce0e7105a6cc21bb41073ef1f370c/system/ee/EllisLab/Addons/pages/tab.pages.php

**Comment by tr0llx4ls** [comment]
It did the trick!
Thank you so much for the brevity
