### ISSUE TITLE
Add config for specifying Redis database

### ISSUE THREAD

**Issue by bryannielsen** [ExpressionEngine/ExpressionEngine#3997]
When creating a Redis connection it should be possible to choose a database through the configuration settings.  

Currently you can specify connection details in `config.php` 

```
$config['redis'] = array(
  'host' => '127.0.0.1',
  'password' => NULL,
  'port' => 6379,
  'timeout' => 0
);
```

It would be helpful if you could also specify a database to use:

```
$config['redis'] = array(
  'host' => '127.0.0.1',
  'password' => NULL,
  'port' => 6379,
  'timeout' => 0,
  'database' => 2
);
```

[The original post for this request can be found on the ExpressionEngine Forum](https://expressionengine.com/forums/topic/253818)

**Comment by intoeetive** [comment]
I think this might need implementation similar to https://github.com/ExpressionEngine/ExpressionEngine/pull/3716
