### ISSUE TITLE
Dropdown menu clipped if inside of a responsive table in a panel

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#3999]
**Description of the problem**

EE 7.4 beta (don't know if this is occurring in older versions)

The `.table-responsive` class inside of `.panel` is clipping drop-downs:
<img width="1323" alt="Screenshot 2024-01-12 at 3 09 46 PM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/53965/03c96ab9-3a14-4e16-a2f7-464d397d37e9">

If I add `overflow: visible` the dropdown content displays:
<img width="1339" alt="Screenshot 2024-01-12 at 3 10 50 PM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/53965/df0eedf8-ed98-4e85-b786-c59decdd7ad7">

Code used to render this template:
```
<div class="panel">
    <div class="panel-heading">
        <div class="title-bar">
            <h3><?= $cp_page_title ?></h3>
        </div>
    </div>
    <div class="table-responsive table-responsive--collapsible">
        <?= ee('CP/Alert')->getAllInlines() ?>
        <?php $this->embed('ee:_shared/table', $diagnosticsInfo); ?>
        <?php echo $pagination ?>
    </div>
</div>
```

**Comment by Yulyaswan** [comment]
Added changes here - https://github.com/ExpressionEngine/ExpressionEngine/commit/89c2875515baa7fadad9a6506fbe8644560a2718
