### ISSUE TITLE
7.4.0  Undefined array key "categories[cat_group_id_2]" in channel form

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#4019]
Installed fresh copy of 7.4.0 dp 42.  I made 1 of every fieldtype, then assigned them all to a newly created channel.  I did NOT assign them categories, but when I went back to edit the category tag, I found both existing categories WERE assigned to the channel.  Removing those fixed it.  I think there's probably an issue with how categories are assigned by default when you create a new channel, but I didn't dig in deep.  

In the CP, creating a new entry shows now errors.  But on the frontend using the channel entry form I get 

Undefined array key "categories[cat_group_id_2]"
ee/ExpressionEngine/Model/Content/Display/DefaultLayout.php, line 72

and

Call to a member function getId() on null
ee/ExpressionEngine/Model/Content/Display/LayoutTab.php:49

<img width="1170" alt="Screenshot 2024-01-29 at 2 39 57 PM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/1181219/c8f2b66b-f47c-4f80-ab99-92fba34ebd14">

Happens with even a simple form:

```
    {exp:channel:form channel="all_the_fields" return="forms/all/ENTRY_ID" entry_id="{segment_3}"}

        <label for="title">Title</label>
        <input type="text" name="title" id="title" value="{title}" size="50" maxlength="100" onkeyup="liveUrlTitle(event);">

        <label for="url_title">URL Title</label>
        <input type="text" name="url_title" id="url_title" value="{url_title}" maxlength="75" size="50">


        <input type="submit" name="submit" value="Submit">
    {/exp:channel:form}
```

**Comment by intoeetive** [comment]
@robinsowell this should be fixed now (you'd need to resave the channel though)
