### ISSUE TITLE
Can't create new grid fields, grid label doesn't appear next to exisiting grid fields

### ISSUE THREAD

**Issue by tyssen** [ExpressionEngine/ExpressionEngine#4026]
**Description of the problem**
I'm working on a site that has been upgraded to the latest version of EE from 2.10.3. Before the upgrade I used the playa/matrix importer module to convert the existing fields to grid/relationships.

All the fields exist, but next to the name of the grid fields, where it should say `(grid)` there is nothing, e.g.

![Screenshot 2024-02-05 at 3 39 11 pm](https://github.com/ExpressionEngine/ExpressionEngine/assets/370290/3e2efe37-e7dd-42bf-b41f-f5b264c275ad)
it shows the label for the matrix field but not the grid ones. The labels for the relationship fields which were created by the importer module are fine.

Also, I can't create new grid fields, because the option doesn't appear in the dropdown:

![Screenshot 2024-02-05 at 3 41 18 pm](https://github.com/ExpressionEngine/ExpressionEngine/assets/370290/4f405ba1-b3f2-4dd3-b30b-8c7a7441b8f3)
either when creating a new field or using the dropdowns that let you filter on specific fieldtypes.

In the database, each of the fields has `grid` in the `field_type` column in `exp_channel_fields` and there's also a row for grid in `exp_fieldtypes`.

**Environment Details:**
 - Version: 7.2.17
 - PHP Version: 8.1
 - MySQL Version: Mariadb 10.4
 - OS: MacOS 14.2.1
 - Web Server: DDEV

**Comment by intoeetive** [comment]
@tyssen it looks like a record for `grid` in `exp_fieldtypes` is missing. I see that it was introduced around EE 2.7, so perhaps something was missing in original installation.

Additionally, we do not support going straight from 2.10.3 directly, you should have upgraded to latest EE2 first (which is I believe 2.11.9)

Since this looks more like a support issue and not bug report, I'll close it - please shout back if you this this is still a bug and have a way to replicate it.

**Comment by tyssen** [comment]
> it looks like a record for grid in exp_fieldtypes is missing

I did mention in my original post that that exists.

Sorry, forgot to mention, I did upgrade to 2.11.9 first before then running the playa/matrix importer.

So if this isn't a bug, what are the options for getting it fixed? This client has just purchased a new license, is there no support included in that?

**Comment by intoeetive** [comment]
We do aim to make sure the customers are happy - that the website is up and running.

It's just that GitHub is not for support issues. We do monitor Slack and Forums and try to respond as we can (and also there's high chance to get advice from community there, if anyone has experienced similar issue). The CMS license fee does not include support plan, which we offer separately https://expressionengine.com/support

Now, back to your issue. We have the "Debug Fieldtypes" in Utilities section in the CP. If you run it, do you get any notices?
If it's still all good, double check the following
- a record for `grid` in `exp_fieldtypes` table
- `exp_channel_field` having correct values
- `exp_grid_columns` having correct values
- `ft.grid.php` present in system/ee/ExpressionEngine/Addons/grid
- there is no third-party add-on called Grid (I think there was one for EE2)
I also would enable logging errors https://docs.expressionengine.com/latest/troubleshooting/error-logging.html#error-logging-1 and check error logs both in EE and your server error logs

**Comment by tyssen** [comment]
Debug fieldtypes says no missing fieldtypes and lists all the ones used but also lists quite a few that are installed but unused.

- a record for `grid` in `exp_fieldtypes` table – yes
- `ft.grid.php` present in system/ee/ExpressionEngine/Addons/grid – yes
- `exp_channel_field` having correct values 
- `exp_grid_columns` having correct values – don't really know what I'm looking for here, but all the grid fields that were created by the importer module seem to work fine in both the front and back end.

I've enabled logging, and am getting this when trying to access the settings of any of the grid fields:

> Undefined array key "grid"
> ee/ExpressionEngine/Model/Content/FieldModel.php, line 536

**Comment by intoeetive** [comment]
I see you've reported your EE version as `7.2.17` - can you upgrade to latest 7.3.15?

**Comment by tyssen** [comment]
Done, same thing still happening.

**Comment by intoeetive** [comment]
what's the error in the logs now? (should be pointing to a different line)

**Comment by tyssen** [comment]
Yep, same error, line 564.

**Comment by intoeetive** [comment]
It seems like EE does not see the fieldtype as installed for some reason. I could suspect `grid/addon.setup.php` being corrupt but since you've just upgraded EE that is probably not the case

I would start debugging around lines 550-551 to see what it pulls to build the fieldtypes array and from there hopefully get an idea on why the grid is missing

**Comment by robinsowell** [comment]
Definitely hit us in support@expressionengine.com if you're still stuck, @tyssen .  We'll likely ask for superadmin login and if possible, ftp. May just be it's somehow not installed per the db.
