### ISSUE TITLE
bugged password, can't add new member

### ISSUE THREAD

**Issue by tcortellesi1** [ExpressionEngine/ExpressionEngine#403]
ExpressionEngine will not let me add new members. It prompts me to enter my password, then claims that my password is 'incorrect' despite me having used it just a few seconds ago to log in.

**Comment by intoeetive** [comment]
@tcortellesi1 somehow this issue came unnoticed.
I'll have to close it now and it's out-of-date and does not provide details required to replicate the bug.

However if you are still expiriencing same problem, please feel free to re-open having added more information.
