### ISSUE TITLE
Required field indicators missing inside Grid and Fluid Fields

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#4040]
**Description of the problem**
Simple fields that are marked as required don't always show an indicator to users, but sometimes do depending on how they're assigned.  Two examples:

1.  A standalone URL field:
- Assigned directly to the channel it works fine:
<img width="502" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/8193519/fa6e3f20-726c-4e26-b712-58c7cf734a80">

- Assigned directly to a Fluid Field does not:
<img width="735" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/8193519/a979f97b-16d2-4b39-9876-8b8481d9326c">

- Assigned to a Field Group, where the Field Group is used in a Fluid Field doesn't either:
<img width="532" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/8193519/0ec74903-093b-4841-a92d-dab23116f896">

2. A required field inside a Grid doesn't show the indicator no matter how it's assigned, even when the Grid is assigned directly to a channel.  Here, Form Handle is a required field and the validation does work, just the indicator isn't styled.  There is a <span class="required"> wrapped around the column heading, but it just isn't adding the asterisk:
<img width="545" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/8193519/e689cd93-836b-46d1-8aa0-7e327be9c42b">

**Comment by TomJaeger** [comment]
What version of EE are you currently running?

**Comment by pyrobob83** [comment]
@TomJaeger Sorry, I should've said - latest: 7.3.15

**Comment by intoeetive** [comment]
@pyrobob83 thank you for reporting this

The "required" toggle for the fields is only applicable when those are used in Channel Entries directly, not in Fluid fields.
Since this is behavior has been around for a while, we're unlikely to change it. However we are planning to give people more control on the fields within Fluid, so might add separate setting there.

We'll get the Grid columns issue addressed

**Comment by pyrobob83** [comment]
@intoeetive Ah, that makes sense about needing separate settings to make a field required.  Ever since sharing fields became a thing, being able to make it required in one place, but not in another has come up for me personally a few times and forced a separate field to be created.  In all the examples I can think of though, those were on fields assigned directly to channels (eg News summary being required but Blog summary being optional), so it feels like making that an option wherever a field is reused (whether directly in a channel, directly to a fluid field or as part of field group in a fluid).

Taking that idea a little further, and perhaps this needs to be a separate issue, I'd really like to see the ability to customize the required state, the label and the instructions (which I know has come up in discussions before) for anywhere a field is reused... that'd just be awesome.

CCing @TomJaeger just for visibility on that last part.
