### ISSUE TITLE
EE7.4.0 - Unable to Add Category Group to Existing Channel

### ISSUE THREAD

**Issue by dougblackjr** [ExpressionEngine/ExpressionEngine#4048]
**Description of the problem**

Upgraded site from EE7.3.x. In an existing channel, I'm unable to add a Category Group. Clicking the button does nothing.

**How To Reproduce**

1. Go to existing channel with no category groups.
2. Go to Categories tab.
3. Click Add group

**Environment Details:**
 - Version: 7.4.0
 - PHP Version 8.1.x
 - MySQL Version 8.x
 - OS: Linux
 - Web Server: nginx

**Comment by intoeetive** [comment]
@dougblackjr just to confirm, are you able to add news groups in categories section and then assign to channel?
