### ISSUE TITLE
EE 7.4: Field hints do not save to clipboard in Safari

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#4055]
**Description of the problem**
As title says, the new field hints, when clicked, do not save the field's short name to the clipboard in Safari.

**How To Reproduce**
1. Open any entry publish page in Safari. Doesn't need to have a custom field, this fails with the default Title field too.
2. Click the copy icon, note that it changes color and shows the checkbox icon
3. Try to paste the value somewhere else, note the value is not `{title}`, its likely the last thing you had in your clipboard.
4. Try another browser. In my case I used Firefox. The copy to clipboard worked and I was able to paste the value somewhere else.

**Environment Details:**
 - Version: 7.4

**Comment by bryannielsen** [comment]
Resolved in [7.5.0](https://github.com/ExpressionEngine/ExpressionEngine/releases/tag/7.5.0)
