### ISSUE TITLE
EE 7.4: conditionals within custom_profile_fields firing before custom member fields are parsed

### ISSUE THREAD

**Issue by jHards** [ExpressionEngine/ExpressionEngine#4057]
**Description of the problem**
Within `{custom_profile_fields}{/custom_profile_fields}` tags inside `{exp:member:edit_profile}{/exp:member:edit_profile}` tags, it seems that conditional logic is run before the values are parsed.

**How To Reproduce**
- See template code below

**Error Messages**
N/A

**Screenshots / Videos / Template Code**
If logged_in_member_group == 1 then this works:
<pre><code>{if logged_in_member_group == '1'}
     content
{/if}</code></pre>

However, this does not, even if m_field_id_1 exists:
<pre><code>{if field_name== 'm_field_id_1'}
     content
{/if}</code></pre>

But this does:
<pre><code>{if field_name== field_name}
     content
{/if}</code></pre>

Which suggests that the conditional tag is operating within `{custom_profile_fields}{/custom_profile_fields}` is firing but is run before `field_name` within the conditional tags is parsed.

**Environment Details:**
 - Version: 7.4

**Possible Solution**
N/A

**Additional context**
N/A

**Comment by intoeetive** [comment]
I can confirm that `{if field_name== 'm_field_id_1'}` does not work indeed, however `{if '{field_name}'== 'm_field_id_1'}` is working as expected

**Comment by jHards** [comment]
Thanks, that works for me!
