### ISSUE TITLE
E Notice - when creating new Low Variable / EE 6.4.16

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#4063]
**Description of the problem**
Created a new Low Variable in a new Variable Group.
Upon drawing the page to capture new variable definition, get an E Notice

**How To Reproduce**
As described above

**Error Messages**

<pre><code>
Notice
Undefined index: field_required

ee/ExpressionEngine/Addons/grid/ft.grid.php, line 845

    Severity: E_NOTICE
</code></pre>

**Screenshots / Videos / Template Code**
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/54404bf8-f1b9-4bb7-960e-9e08a6233c16)

**Environment Details:**
 - Version: 6.4.16
 - PHP Version 7.4.33

**Comment by intoeetive** [comment]
Sent this over to EEHabor team. Thank you
