### ISSUE TITLE
Field group(s) in Fluid field: current_group_short_name parsing issue when used in IF statement

### ISSUE THREAD

**Issue by larsschwarz** [ExpressionEngine/ExpressionEngine#4067]
When processing a Fluid field that contains both (regular fields and Field Groups) I'm proccesing the originally maintained order by using a combination of current_field_name and current_group_short_name. 

Here's some dummy code. Actually the field group name can be printed out just fine, but the respective IF statement using the same outputted field group name is never processed.

```
// Assume the entry has maintained 2 entries in the fluid: a) some regular field and content, some field group and content
{exp:channel:entries channel="my_channel" url_title="my_url_title" dynamic="no" show_future_entries="no"}

{my_fluid_field}

{my_fluid_field:current_field_name} // this prints the field name just fine
{my_fluid_field:current_group_short_name} // this prints the field group name (my_field_group) just fine

{if my_fluid_field:current_field_name=="my_field"}
// processed just fine
{if:elseif my_fluid_field:current_group_short_name=="my_field_group"}
// never processed even though the field group name matches the previously outputted field group name 
{/if}
{/my_fluid_field}

{my_fluid_field:my_field_group}
// processing the Field Group like this works fine
{/my_fluid_field:my_field_group}

{/exp:channel:entries}
```
Therefore if a Fluid contains a mixture of regular fields and Field Groups I don't see a way to maintain the original order as maintained in the Fluid, but I can only output both types (regular fields and Field Groups) separately. 

Tested with EE 7.4 and 7.4.1

**Comment by intoeetive** [comment]
The "group" variables are available only when used with field groups. So in your case, within `{my_fluid_field:my_field_group}` pair (one might find those useful when using template partial to display the field output)

Because field groups and fields in Fluid are different types of elements, we need to address them slightly different in the code, which results in the fact you can't just mix them in the templates

We would be happy though to hear about possible use cases and what improvement we could make. Please feel free to open Feature Request in Discussions

**Comment by larsschwarz** [comment]
Hey Yuri, thanks for the reply. Aren't those "possible use cases" obvious though? A user can maintain both elements in a Fluid and he can (re-)order/mix them as he/she likes so I'd simply expect that it is possible to output content maintained and sorted/ordered by the user the same way as he/she maintained that content? I'll file a feature request then.

**Comment by larsschwarz** [comment]
Here's the feature request with additional use-case infos and other suggestions for improvements:

https://github.com/ExpressionEngine/ExpressionEngine/issues/4071

**Comment by intoeetive** [comment]
Thank you for submitting that!

The use cases my be obvious when you work with a thing on a daily basis, but we'd like to collect the ideas / feature requests for next phase of Fluid field development (whenever that happends), so it's nice to have things written down as provided by real end user. Thanks again!

**Comment by TomJaeger** [comment]
Although these might be beyond where we are right now... I want to tag @bryannielsen on this one as well, since he has a few updates in the works currently.

**Comment by larsschwarz** [comment]
Thanks guys, but it seems I'm missing the actual use case of the current status then. 
If you cannot output data as maintained by the user, what's the actual use case of the feature to allow mixing Field Groups and regular fields in Fluids? 
Even if you had a Fluid with Field Groups only it seems impossible to output them in the same order as maintained?
