### ISSUE TITLE
Creating a new field shows irrelevant field options

### ISSUE THREAD

**Issue by swierczek** [ExpressionEngine/ExpressionEngine#4069]
**Description of the problem**
When creating a new field, selecting a different field type shows only the relevant options for that field type. But on page load, the default field (Text Input) also shows options related to Relationship fields. It's not clear what the side effects might be of saving the new Field with these extra options.

<img width="784" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/2423727/c0bf28d6-bf6f-4eee-9484-67694e775156">

**How To Reproduce**
1. Go to Fields
2. Click "New Field"
3. The selected field type should be "Text Input", but scrolling down shows fields for Relationship fields (and maybe others).
4. Change the field type to anything else, and then change it back to "Text Input". Scrolling down now only shows fields relevant to "Text Input"

**Environment Details:**
 - Version: EE v7.4.1

**Comment by intoeetive** [comment]
This usually happens when there is a PHP notice on page and Javascript can not properly hide / show fields.

Do you have any third-party fields installed?

If you "view HTML source" for the page, do you see any "Notice" or "Warning"?

**Comment by jcogs-design** [comment]
We have this too on a 7.4 site. No php errors. Unnecessary fields.
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/a4f6f651-8063-4ac5-8664-70ae765dfa4e)

For us the thing that flagged it up was actually the related inclusion of "0" as the default value for number of characters attribute (for the text input). If you don't spot this when you save the field - users cannot then add any values to this field (as max character count is 0).

**Comment by swierczek** [comment]
Current `7.dev` branch, no add-ons, no PHP notice/warning/errors in the source:

<img width="1840" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/2423727/66a9d883-aa28-4ef0-ad89-aa737acb1e1e">

**Comment by intoeetive** [comment]
If the errors exist, they should be somewhere in the middle or at the bottom .

Is this new install or upgrade? What is the PHP version?

**Comment by swierczek** [comment]
I searched the source for `notice`, `warning`, and `error` and didn't see anything outside of HTML classes that include those words. This was an upgrade, but I just wiped it clean and confirmed it happens with a new install too. PHP 7.4.
