### ISSUE TITLE
Deprecation errors from Pro Variables Ungrouped when using php > 8.0

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#4077]
**Description of the problem**
Have site running EE7.4.1
ProVariables installed.
When php version is either 8.1 or 8.2 get litter of deprecation errors when viewing the "ungrouped" group of pro variables.
So setting php version to 8.0 and errors go away.

**Error Messages**

<pre><code>
Deprecated
substr(): Passing null to parameter #1 ($string) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/types/type.pro_variables.php, line 131

    Severity: E_DEPRECATED

Deprecated
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/types/type.pro_variables.php, line 135

    Severity: E_DEPRECATED

Deprecated
explode(): Passing null to parameter #2 ($string) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/mcp.pro_variables.php, line 213

    Severity: E_DEPRECATED

Deprecated
substr(): Passing null to parameter #1 ($string) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/types/type.pro_variables.php, line 131

    Severity: E_DEPRECATED

Deprecated
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/types/type.pro_variables.php, line 135

    Severity: E_DEPRECATED

Deprecated
explode(): Passing null to parameter #2 ($string) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/mcp.pro_variables.php, line 213

    Severity: E_DEPRECATED

Deprecated
substr(): Passing null to parameter #1 ($string) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/types/type.pro_variables.php, line 131

    Severity: E_DEPRECATED

Deprecated
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/types/type.pro_variables.php, line 135

    Severity: E_DEPRECATED

Deprecated
explode(): Passing null to parameter #2 ($string) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/mcp.pro_variables.php, line 213

    Severity: E_DEPRECATED

Deprecated
substr(): Passing null to parameter #1 ($string) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/types/type.pro_variables.php, line 131

    Severity: E_DEPRECATED

Deprecated
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/types/type.pro_variables.php, line 135

    Severity: E_DEPRECATED

Deprecated
explode(): Passing null to parameter #2 ($string) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/mcp.pro_variables.php, line 213

    Severity: E_DEPRECATED

Deprecated
substr(): Passing null to parameter #1 ($string) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/types/type.pro_variables.php, line 131

    Severity: E_DEPRECATED

Deprecated
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/types/type.pro_variables.php, line 135

    Severity: E_DEPRECATED

Deprecated
explode(): Passing null to parameter #2 ($string) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/mcp.pro_variables.php, line 213

    Severity: E_DEPRECATED

Deprecated
substr(): Passing null to parameter #1 ($string) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/types/type.pro_variables.php, line 131

    Severity: E_DEPRECATED

Deprecated
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/types/type.pro_variables.php, line 135

    Severity: E_DEPRECATED

Deprecated
explode(): Passing null to parameter #2 ($string) of type string is deprecated

ee/ExpressionEngine/Addons/pro_variables/mcp.pro_variables.php, line 213

    Severity: E_DEPRECATED
</code></pre>

**Screenshots / Videos / Template Code**
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/1b050e73-1e3d-4757-a1fe-0638c2f5b0f3)

**Environment Details:**
 - Version: 7.4.1
 - PHP Version php 8.1 / 8.2

**Comment by intoeetive** [comment]
@jcogs-design thanks for the report!

it looks like some variables that are empty are actually holding NULL instead of empty string.

Have they been freshly created, or migrated from Low Variables, or imported?

Also, do the errors go away when you click "Save Variables"?

**Comment by jcogs-design** [comment]
Updated from EE 4.1 site.
Hitting save variables makes no difference.

**Comment by intoeetive** [comment]
@jcogs-design if you go to `exp_global_variables` table, do you have records that have NULL in `variable_data` column? It's set as NOT NULL in current EE version, but perhaps it hasn't always been like that

**Comment by intoeetive** [comment]
@jcogs-design never mind - wasn't reading it correctly. Re-saving variable settings (until you see the errors gone) should fix the thing for you. Will also provide a fix in the code however

**Comment by jcogs-design** [comment]
Bril - resaving several times did indeed clear the issue. Remarkable. Many thanks!
