### ISSUE TITLE
Undefined array key error relating to relationship field - EE 7.4.1

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#4079]
**Description of the problem**
Getting a block of warnings errors on multiple pages on a site newly updated from EE4 to EE7.4.1
Site is running php 8.0.
Warnings appear to relate to a missing index being accessed by the `entry` method in Parser.php. Am guessing the remaining warnings are cascaded from this issue. Have done limited poking around and a value is passed as `$id` in this line (39) but the array `$this->_entries` does not contain a key with this value. 
```
return $this->_entries[$id];
```

**Error Messages**

<pre><code>
Warning
Undefined array key 27

ee/legacy/libraries/relationship_parser/Parser.php, line 39

    Severity: E_WARNING

Warning
Trying to access array offset on value of type null

ee/legacy/libraries/relationship_parser/Parser.php, line 664

    Severity: E_WARNING

Warning
Undefined array key 27

ee/legacy/libraries/relationship_parser/Parser.php, line 39

    Severity: E_WARNING

Warning
Trying to access array offset on value of type null

ee/legacy/libraries/relationship_parser/Parser.php, line 424

    Severity: E_WARNING

Warning
Trying to access array offset on value of type null

ee/legacy/libraries/relationship_parser/Parser.php, line 430

    Severity: E_WARNING

Warning
Trying to access array offset on value of type null

ee/legacy/libraries/relationship_parser/Parser.php, line 468

    Severity: E_WARNING
</code></pre>

**Screenshots / Videos / Template Code**
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/903aa89a-394d-44ca-ad1c-2a93733eb704)

**Environment Details:**
 - Version: 7.4.1
 - PHP Version 8.0

**Comment by intoeetive** [comment]
@jcogs-design this appears to be caused by broken database. The entry_id 27 was removed from exp_channel_titles but the orphan record remains in exp_relationship table. You should be able to fix this site by removing that record

This (orphan record) does not happen when you delete entry in EE7, however the error should not show up - will work on a fix.

**Comment by intoeetive** [comment]
... or you can use the fix https://github.com/ExpressionEngine/ExpressionEngine/pull/4080

although keeping your database clean of orphan records should always be a nice idea

**Comment by jcogs-design** [comment]
Not a site I built so don't know back-story behind missing entries, but agree about trying to keep db clean.
In interim can confirm fix does the job nicely also.
