### ISSUE TITLE
Fatal error after upgrading to EEv7.4.2

### ISSUE THREAD

**Issue by itsrachelfish** [ExpressionEngine/ExpressionEngine#4096]
I attempted to upgrade from EEv5.4.3 to 6.4.13 and started encountering this error message when trying to view the `system` directory and login as admin. Issue persists even after upgrading to 7.4.2.

Was able to replicate this issue running PHP 7.2 as well as PHP 8.2.

```
Fatal error: Uncaught Error: Call to undefined method EllisLab\ExpressionEngine\Core\Provider::registerCookiesSettings() in /public_html/system/ee/legacy/libraries/Core.php:138 

Stack trace: 
#0 /public_html/system/ee/legacy/core/Controller.php(65): EE_Core->bootstrap() 
#1 /public_html/system/ee/legacy/core/Controller.php(76): Base_Controller->__construct() 
#2 /public_html/system/ee/legacy/core/Controller.php(102): EE_Controller->__construct() 
#3 /public_html/system/ee/EllisLab/ExpressionEngine/Controller/Error/FileNotFound.php(23): CP_Controller->__construct() 
#4 /public_html/system/ee/EllisLab/ExpressionEngine/Core/Core.php(255): EllisLab\ExpressionEngine\Controller\Error\FileNotFound->__construct() 
#5 /public_html/system/ee/EllisLab/ExpressionEngine/Cor in /public_html/system/ee/legacy/libraries/Core.php on line 138
```

**Comment by robinsowell** [comment]
It's using old files- when you did the upgrade, did you also manually replace the index.php and admin.php files?  You need to do that, and I'd go ahead and delete system/ee/ellislab as well.  

If that doesn't do it, try disabling extensions via the config.php file and let's just see if that's in play.

**Comment by itsrachelfish** [comment]
@robinsowell I noticed that I only see this error when I try to go to the old `/system/` directory to login to the admin control panel. When I use `admin.php` it works as expected. Should I delete the old system directory?

**Comment by robinsowell** [comment]
Closing this one out, as doing a 1-click via admin.php resolved it.  I'm still not sure what was going on there!
