### ISSUE TITLE
Date field- the time should default to 'now' rather than noon

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#4098]
Not sure if it's a bug or a feature request- but before, the time defaulted to 'now'.  Now, the time, if included, defaults to noon.

And users are requesting it work the way it used to as far as default.

**Comment by intoeetive** [comment]
@Yulyaswan I believe there has been a reason/limitation of why the change was made? Anyway, please have a look when you get some time

**Comment by Yulyaswan** [comment]
It wasn't change. The "Today" button works like it was before, and time input was a new feature without special requests about the default state.
I'll work to make changes to use `now` time by default
