### ISSUE TITLE
template layouts are broken in 7.4.2

### ISSUE THREAD

**Issue by jelle-burodeng** [ExpressionEngine/ExpressionEngine#4102]
When you have multi step layouts, {layout:set name="something"}bla{/layout:set}
doesn't work anymore

To reproduce:
template 1: dev/landing
{layout="dev/landing_2"}
{layout:set name="iets" value="bla"}
Template 2: dev/landing_2
{layout="dev/wrapper"}
{layout:set name="body_content"}
this is the body_content
{/layout:set}
Template 3: dev/wrapper
<!doctype html>
<html lang="nl">
  <head>
  </head>
  <body>
	Here the body_content should show:
    {layout:body_content}
  </body>
</html>

The layout:body content isn't set

**Comment by jcogs-design** [comment]
Can confirm same happens on an unrelated EE7.4.2 system I have running either php 8.1 or php8.2

**Comment by jcogs-design** [comment]
Had a quick look and seems to throw a warning relating to the value of `$item` in function call to `_parse_var_single` which is unset ... as it seems when the `parseLayoutVariables()` method of the `EE_Template class` parses the tag-pair form of `layout:set` it seems to get confused in a loop beginning at line 714 - concluding that `{layout:set name="blah"} ... {/layout:set}` is an attempt at recalling a layout variable called set ... and gets into a mess when it can't find it...
