### ISSUE TITLE
Edit profile tag, cannot access label of value/label pairs

### ISSUE THREAD

**Issue by jHards** [ExpressionEngine/ExpressionEngine#4106]
**Description of the problem**
Using variables within `exp:member:edit_profile` to try and access the selected option of a field with value/label pairs doesn't yield expected results.

**How To Reproduce**
`{my_field}` - yields the value
`{my_field:label}` - yields the value
`{label:my_field}` - tag not parsed
`{selected_option:my_field}` - tag not parsed
`{my_field:selected_option}` - tag parsed but shows blank
`{selected_option:my_field:label}` - tag not parsed
`{my_field:selected_option:label}` - yields the value

**Error Messages**
N/A

**Screenshots / Videos / Template Code**
N/A

**Environment Details:**
 - Version: 7.4.2

**Possible Solution**
N/A

**Additional context**
N/A

**Comment by intoeetive** [comment]
@jHards I see these field listed for Channel Form, but I don't see those for Profile Edit Form. While some of the functionality is now shared, it's not 100% replicate and we will not support in Member Forms everything that's currently in Channel Forms.

I believe you can get the selected field value by using just the field tag and then use it in conditionals or output as needed.

If you have a specific need, please open a feature request

**Comment by jHards** [comment]
Thanks @intoeetive, the overview states the [behavior is similar to Channel Form](https://docs.expressionengine.com/latest/member/edit-profile.html#overview), hence the assumptions.

I think the main issue here is that the docs aren't explicit with which components of the Channel Form are replicated. 
With tags that remain as unparsed it's easy to understand they are not working. However, adding tags that parse as blank, or worse, an incorrect value, is misleading.

To resolve my issue, is there a quick fix to address the tags within the `{exp:member:edit_profile}` tags but outside any `{custom_profile_fields}` tags - `{my_field:selected_option:label}` currently yields the value but [the docs](https://docs.expressionengine.com/latest/channels/channel-form/overview.html#selected_optionmy_field_namelabel) suggest that this is the wrong syntax.  The Channel Form docs, as referenced in the Member Edit Profile docs, suggest `{selected_option:my_field_name}` should return the selected value whilst `{selected_option:my_field_name:label}` should return the associated option label.

**Comment by intoeetive** [comment]
We'll add more clarification to the docs on this front. Thank you.

**Comment by jHards** [comment]
@intoeetive I'm not sure the doc update is sufficient. This would be ok if some of the Channel Form syntax works and others do not, but here there are some incorrect parsing - where is this coming from if not picked up in the Member form?

**Comment by intoeetive** [comment]
There has been a bug related to displaying the label which we're getting fixed in https://github.com/ExpressionEngine/ExpressionEngine/pull/4150

Other than that, I am not sure we can speak of incorrect parsing here. 

If a tag is not supported, or is of wrong syntax, you can't expect anything out of it.

**Comment by jHards** [comment]
Now on release 7.4.5, which incorporated #4150, I see the following behaviour:
`{my_field}` - yields the value
`{my_field:label}` - yields the <del>value</del> label
`{label:my_field}` - tag not parsed
`{selected_option:my_field}` - tag not parsed
`{my_field:selected_option}` - tag parsed but shows blank
`{selected_option:my_field:label}` - tag not parsed
`{my_field:selected_option:label}` - yields the <del>value</del> label

With the `{my_field}` and `{my_field:label}` tags now working I think we're good, thanks for the fix!
