### ISSUE TITLE
Can assign Category parent to itself

### ISSUE THREAD

**Issue by benoitlemay** [ExpressionEngine/ExpressionEngine#411]
**Description of the problem**
You can assign a category to itself (parenting). That cause an infinite loading white page.. Then cause a error on refresh. **_IMPORTANT_**. I was able to reproduce only IF the category group had parent AND children categories.

**How To Reproduce**

- Create a category
- You can assign the category parent to itself IF there's already parent/children in the category group 
- On refresh you will get the error and cannot access the category_group anymore.. you have to edit the exp_categories table and change the problematic category's parent to 0 

**Error Messages**

<pre><code>Cannot add tree node to itself.
ee/legacy/libraries/datastructures/Tree.php:244
Stack Trace: Please include when reporting this error
#0 ee/legacy/libraries/datastructures/Tree.php(123): EE_TreeNode->add(Object(EE_TreeNode))
#1 ee/legacy/libraries/datastructures/Tree.php(55): EE_Tree->_build_tree(Object(EllisLab\ExpressionEngine\Service\Model\Collection), Array)
#2 ee/EllisLab/ExpressionEngine/Model/Category/CategoryGroup.php(122): EE_Tree->from_list(Object(EllisLab\ExpressionEngine\Service\Model\Collection), Array)
#3 ee/EllisLab/ExpressionEngine/Controller/Categories/Categories.php(78): EllisLab\ExpressionEngine\Model\Category\CategoryGroup->getCategoryTree(Object(EE_Tree))
#4 [internal function]: EllisLab\ExpressionEngine\Controller\Categories\Categories->group('6')
#5 ee/EllisLab/ExpressionEngine/Core/Core.php(241): call_user_func_array(Array, Array)
#6 ee/EllisLab/ExpressionEngine/Core/Core.php(110): EllisLab\ExpressionEngine\Core\Core->runController(Array)
#7 ee/EllisLab/ExpressionEngine/Boot/boot.php(151): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request))
#8 index.php(152): require_once('...')
#8 index.php(152): require_once('...')
</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 5.3.0 AND 5.3.2
 - PHP Version 7.3 or 7.4
 - MySQL Version [e.g. 5.7]
 - Linux
 - Web Server:Apache

**Comment by ops-andy** [comment]
From Benoit's post in Slack: ![image](https://user-images.githubusercontent.com/55093827/80048887-7c86bd80-84df-11ea-98b3-36d0e3aaaba1.png)

@benoitlemay do you have any addons installed. If so, can you list them. I still cannot replicate this even with a category that has a parent and children unless I manually got into Dev Tools and enable the radio button.

**Comment by ops-andy** [comment]
@benoitlemay did you mean to close this?

**Comment by benoitlemay** [comment]
No my mistake...
Benoit Lemay
418.998.6481

**Comment by intoeetive** [comment]
I'm unable to replicate this either, but I can see that the backend validation for category parent was missing. It is added with the linked PR
