### ISSUE TITLE
Add template tags for GET variables

### ISSUE THREAD

**Issue by TomJaeger** [ExpressionEngine/ExpressionEngine#413]
**Is your feature request related to a problem? Please describe.**
Currently the EE template system requires a third-party add-on to use GET parameters from a URL in a template

**Describe the solution you'd like**
Would be nice to have GET variables natively in the template parser in a logical way.

FR created from conversation in EE Slack.

**Comment by stephengalbraith** [comment]
Definitely think this is a great idea and to keep it simple is likely best:
`{exp:get query_string="x" default="123"}`

(Depending on complexity of what this could or could not turn into, I could perhaps help / contribute to a native add-on)
