### ISSUE TITLE
Member Custom Fields - New Member

### ISSUE THREAD

**Issue by DalizPR** [ExpressionEngine/ExpressionEngine#4131]
It would be great if the window for **New Member**  would have the Custom Member Fields underneath the Register a New Member section. So you can fill out all the member details in one screen and not have to register a member and then edit it to fill out the custom member fields.

**Comment by intoeetive** [comment]
I believe the list of fields there are the fields that have "Visible on Registration" setting turned on.

However it might make sense for that setting to be considered only for front-end registrations maybe? We'll need to investigate this more

@robinsowell perhaps you have some input on this

**Comment by DalizPR** [comment]
Hi Youri,

The first is true, I enabled the Visible on Registration option and the fields showed up where I wanted them. Thanks!

At the front-end I register members with Visitor so that is why they wern;t enabled at the first place..
