### ISSUE TITLE
Trying to get property 'site_name' of non-object

### ISSUE THREAD

**Issue by swisol** [ExpressionEngine/ExpressionEngine#4143]
Updated EE5.2.2 site to 6.4.16. Getting 2 of these notices when editing a template, or a role, via CP. I have updated addons, except SEEO which I forgot to (so that's 1.8.1) but everything seems to work. No other areas showing this notice. 
No MSM, PHP 7.4, cleared caches, still getting the notices. Other sites updated ok on the same server plans...I'm stuck so hoping I can get some assistance. 

Notice
Trying to get property 'site_name' of non-object
ee/ExpressionEngine/Model/Template/TemplateGroup.php, line 174
Severity: E_NOTICE

Thanks
Andy

**Comment by intoeetive** [comment]
@swisol I have an impression that something is wrong in database.

Since you never had MSM, your only site_id should be `1`.

If you view `exp_template_groups` table, are there any records that have `site_id` set to value different than `1`?

**Comment by swisol** [comment]
Yes Yuri, there is a record with an id of 0. It looks like I have a template group for SEEO, mistakenly above the "default_site" folder. Could it be as simple as moving that within default_site and editing the id to 1 in the db?

**Comment by intoeetive** [comment]
Yes, that should get it fixed

**Comment by swisol** [comment]
That has resolved the issue! Thanks Yuri!
