### ISSUE TITLE
themes/ee/cform/css/eecms-cform.min.css overriding styles

### ISSUE THREAD

**Issue by ataucher** [ExpressionEngine/ExpressionEngine#4152]
Anywhere i'm using the exp:channel:form in my template, EE is injecting themes/ee/cform/css/eecms-cform.min.css which has some conflicting :root, body styles for font-family and font-size. It's causing me to add in CSS rules as !important to override.
Wouldn't say it's a bug, but not something I planned on having to wrestle with regarding EE when it comes to styling.
<img width="325" alt="Screenshot 2024-03-18 at 7 49 02 AM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/1093815/bcbce34d-3001-4c5c-926e-1d26a7c0f9a7">

**Comment by intoeetive** [comment]
Agree, these should probably be set for `cform` container, not body as a whole
