### ISSUE TITLE
Version check is busted

### ISSUE THREAD

**Issue by benjivm** [ExpressionEngine/ExpressionEngine#416]
**Description of the problem**
The version check feature at the footer of the CP is no longer working properly.

**How To Reproduce**
1. Click the version check button in the footer of the control panel
2. The progress bar stays in loading state forever
3. Developer tools shows errors (see below)

**Error Messages**
Dev-tools Console:
```js
SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data
```

Dev-tools Network Response for URL `/index.php?/cp/settings/general/version-check`:
```json
<div class="err-wrap notice">
	<h1>Notice</h1>
	<h2>Trying to access array offset on value of type bool</h2>
	<p>ee/EllisLab/ExpressionEngine/Controller/Settings/General.php, line 274</p>
	<ul>
		<li><b>Severity</b>: E_NOTICE</li>
	</ul>
</div>
["up-to-date"]
```

**Environment Details:**
 - Version: 5.3.2
 - PHP Version: 7.4.5
 - MySQL Version: 5.7.29
 - OS: Ubuntu Server 18.04
 - Web Server: nginx

**Possible Solution:**
It appears for some reason both the AJAX and non-AJAX responses are being sent (I think??), at least judging by a quick glance a [this method](https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/system/ee/EllisLab/ExpressionEngine/Controller/Settings/General.php#L258).

**Comment by bigrepository** [comment]
I've just upgraded from 5.3.1 to 5.3.2 and could not reproduce the problem. Then I changed the PHP Version for this vHost to **7.4.5** and got the exakt same result. So: I can confirm this. PHP **7.3.17** did work correctly.
