### ISSUE TITLE
Member column dropdown display for French (foreign) language packs

### ISSUE THREAD

**Issue by Biscuiterie975** [ExpressionEngine/ExpressionEngine#4167]
Hi everyone,

I use the French language pack (v.7.4.5) in EE's control panel. Foreign translation sometimes require more space (width) as words might get longer than the native English ones. In the new Member area (that includes great new features), there is the column icon dropdown menu that allows admins to chose whatever column they wish to display in the Member page setup. Its width is hard coded and looks to narrow. Names are partially hidden and non fully readable. Since there is room to enlarge the dropdown menu width, can you manage to provide a correction?

AU

![example](https://github.com/ExpressionEngine/ExpressionEngine/assets/109601150/0e82fc3f-e4fb-49ea-a94c-9110d423dcd6)

**Comment by intoeetive** [comment]
@Yulyaswan can you please fix that? The issue does not seem to be present in entry manager, just in member manager
