### ISSUE TITLE
Exception Caught No such property: 'TMPL' on EllisLab\ExpressionEngine\Legacy\Facade Facade.php:120.

### ISSUE THREAD

**Issue by pandaicoding** [ExpressionEngine/ExpressionEngine#418]
I use reinos for social media login add-ons to log in, but there are errors like below, which can help solve this problem :

Exception Caught
No such property: 'TMPL' on EllisLab\ExpressionEngine\Legacy\Facade
Facade.php:120

**Comment by intoeetive** [comment]
@sumari046696 the errors seem to be originated from the add-ons that you are using. We can't support those.
Please make sure you have compatible version and contact addon developer if the error persists
