### ISSUE TITLE
Pagination library is initialized before it is loaded in mod.member_memberlist

### ISSUE THREAD

**Issue by inconsiderate** [ExpressionEngine/ExpressionEngine#419]
**Description of the problem**
Inside a deprecation check for "old style pagination," the pagination library is initialized, but is not loaded. This causes a fatal exception.

**Possible Solution**
See these two lines:
https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/system/ee/EllisLab/Addons/member/mod.member_memberlist.php#L524
https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/system/ee/EllisLab/Addons/member/mod.member_memberlist.php#L528

Line 528 should be moved up, to avoid 524 throwing an exception.

**Comment by robinsowell** [comment]
Thanks inconsiderate!  (I question the accuracy of your name.)
