### ISSUE TITLE
Entry validation failure triggers mysql error if member relationship field present

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#4197]
EE 7.4.6.

I have a channel with only a member relationship field in it- all default values.

If I go to make a new entry and just save- so triggering a validation error for no title, etc. I get a mysql error.

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') DESC, `Member_members`.`screen_name` asc LIMIT 101'
```
Relevant bit of the query:
```
 WHERE Member_member_data.member_id = Member_members.member_id ORDER BY FIELD( Member_members.member_id, ) DESC, `Member_members`.`screen_name` asc LIMIT 101
```
> #0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('SELECT Member_m...')
#1 ee/legacy/database/DB_driver.php(262): CI_DB_mysqli_driver->_execute('SELECT Member_m...')
#2 ee/legacy/database/DB_driver.php(177): CI_DB_driver->simple_query('SELECT Member_m...')
#3 ee/legacy/database/DB_active_rec.php(1084): CI_DB_driver->query('SELECT Member_m...')
#4 ee/ExpressionEngine/Service/Model/Query/Select.php(60): CI_DB_active_record->get()
#5 ee/ExpressionEngine/Service/Model/DataStore.php(275): ExpressionEngine\Service\Model\Query\Select->run()
#6 ee/ExpressionEngine/Service/Model/DataStore.php(220): ExpressionEngine\Service\Model\DataStore->runQuery('Select', Object(ExpressionEngine\Service\Model\Query\Builder))
#7 ee/ExpressionEngine/Service/Model/Query/Builder.php(169): ExpressionEngine\Service\Model\DataStore->selectQuery(Object(ExpressionEngine\Service\Model\Query\Builder))
#8 ee/ExpressionEngine/Service/Model/Query/Builder.php(64): ExpressionEngine\Service\Model\Query\Builder->fetch(false)
#9 ee/ExpressionEngine/Addons/member/ft.member.php(180): ExpressionEngine\Service\Model\Query\Builder->all()
#10 ee/legacy/fieldtypes/EE_Fieldtype.php(325): Member_ft->display_field(Array)
#11 ee/legacy/libraries/api/Api_channel_fields.php(444): EE_Fieldtype->display_publish_field(Array)
#12 ee/ExpressionEngine/Model/Content/FieldFacade.php(292): Api_channel_fields->apply('display_publish...', Array)
#13 ee/ExpressionEngine/Model/Content/Display/FieldDisplay.php(83): ExpressionEngine\Model\Content\FieldFacade->getForm()
#14 ee/ExpressionEngine/View/publish/partials/publish_form.php(135): ExpressionEngine\Model\Content\Display\FieldDisplay->getForm()
#15 ee/ExpressionEngine/Service/View/View.php(137): include('...')
#16 ee/ExpressionEngine/Service/View/View.php(106): ExpressionEngine\Service\View\View->parse('...', Array)
#17 ee/ExpressionEngine/Service/View/View.php(165): ExpressionEngine\Service\View\View->render(Array)
#18 ee/ExpressionEngine/View/publish/entry.php(5): ExpressionEngine\Service\View\View->embed(Object(ExpressionEngine\Service\View\View))
#19 ee/ExpressionEngine/Service/View/View.php(137): include('...')
#20 ee/ExpressionEngine/Service/View/View.php(106): ExpressionEngine\Service\View\View->parse('...', Array)
#21 ee/legacy/libraries/View.php(40): ExpressionEngine\Service\View\View->render(Array)
#22 ee/legacy/libraries/Cp.php(344): View->render('publish/entry', Array, false)
#23 ee/ExpressionEngine/Controller/Publish/Publish.php(400): Cp->render('publish/entry', Array)
#24 [internal function]: ExpressionEngine\Controller\Publish\Publish->create(8)
#25 ee/ExpressionEngine/Core/Core.php(268): call_user_func_array(Array, Array)
#26 ee/ExpressionEngine/Core/Core.php(124): ExpressionEngine\Core\Core->runController(Array)
#27 ee/ExpressionEngine/Boot/boot.php(184): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))

**Comment by intoeetive** [comment]
@robinsowell not replicating it so far. What's your PHP version?
