### ISSUE TITLE
some links re-direct to homepage

### ISSUE THREAD

**Issue by subramanya-ss** [ExpressionEngine/ExpressionEngine#420]
**Description of the problem**
If I try to open some template under template group it will automatically re-direct me to homepage

**How To Reproduce**

1. Goto Templates section.
2. Under /templates Group I have home and inc.
3. Click on inc.
4. There I have template called top.
5. On clicking top it is re-directing me to dashboard page not the appropriate page.

This issue also occur in some other pages too.

**Error Messages**

<pre><code>

</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: [e.g. 5.0.1]
 - PHP Version [e.g. 7.1]
 - MySQL Version [e.g. 5.7]
 - OS: [e.g. Linux, macOS, Windows]
 - Web Server: [e.g. Apache, nginx, MAMP, etc.]

**Possible Solution**

**Additional context**

**Comment by robinsowell** [comment]
What other pages redirect?  And how is it doing it?  

So- go to the template manager, open up browser debugging and take a look at the network tab.  Now- hover over the 'top' link- copy it and paste it somewhere you won't lose it.  Click the link- watch the network debug.  We want to see is the problem the link itself being wrong (probably not) or if you're getting a redirect- and if so, what kind.  A 302, something else?  The browser debug will tell us.

I don't think it's a bug and I can't replicate it.  It might be an extension (try disabling extensions and see if it matters- I suspect probably not) or it sounds a wee bit like a server security filter.  But I would tend to expect those to happen on post.  Still- if a filter doesn't like something about the URL, it can indeed intercept it and send it elsewhere.  The browser debug may give us a hint.

**Comment by subramanya-ss** [comment]
Now I am not even able to open Template Manager section.

It is also re-directing me to homepage.

**Comment by robinsowell** [comment]
Try disabling all extensions- realizing this may break things on the frontend.  You can do it by overriding it in the system/user/config/config.php file- 

```$config['allow_extensions'] = 'n';```

If that doesn't do it, open up the browser debugger- see if you can get a screen cap of what's happening when you're redirected.

**Comment by intoeetive** [comment]
Closing this issue as looks specific to particular setup and we did not receive any further information. Please reopen if the issue persists
