### ISSUE TITLE
limit="30" not working for list of members

### ISSUE THREAD

**Issue by macwebcomputing** [ExpressionEngine/ExpressionEngine#4201]
**Description of the problem**

This code is not working 
`{exp:member:memberlist limit="30" orderby="join_date" sort="desc"  }`

Version 7.4.5 

Always displaying the full list of members

**Comment by bryannielsen** [comment]
@macwebcomputing I'm not seeing any issues with the `limit` parameter in my local tests.  Are there any query string parameters you're passing to the template as well?  If it's okay to share some of your template code I can try to take a deeper look at that too

**Comment by macwebcomputing** [comment]
attached full code 

```
`{exp:member:memberlist limit="25" orderby="join_date" sort="desc"  }
									<table>
									
				{member_rows}
				
<tr>
				<td>{exp:stringer:explode separator=" " string="{exp:stringer:uppercasefirst}{name}{/exp:stringer:uppercasefirst}"}{string1}{/exp:stringer:explode}</td><td>{exp:stringer:uppercasefirst}{member_city}{/exp:stringer:uppercasefirst}</td> <td>{exp:stringer:uppercase}{member_country}{/exp:stringer:uppercase}</td>
				
				</tr>
				{/member_rows}
		
				</table>
				{/exp:member:memberlist}
````

**Comment by intoeetive** [comment]
I can confirm that this is happening if `{paginate}` variable pair is not included into template
