### ISSUE TITLE
Color Picker bug when used as fieldtype in Grid

### ISSUE THREAD

**Issue by stigarildberntzen** [ExpressionEngine/ExpressionEngine#4207]
The Colorpicker do not show all the settings when using it in a grid filetype. I have to save the Grid filetype an edit it to gain access to all the settings.

1. Make a "New Field"
2. Choose "Grid" as filetype
3. Add "Colorpicker" in grid
4. The settings "Allowed Colors", "Default Color", "Swatches" will not show up, until you save the grid-field and edit it again.

Environment Details:
 - Version: [e.g. 5.0.1]
 - PHP Version 8.1
 - MySQL Version [e.g. 5.7]
 - OS: MacOS
 - Web Server: [e.g. Apache, nginx, MAMP, etc.]

**Comment by TomJaeger** [comment]
What version of ExpressionEngine is this in?

**Comment by stigarildberntzen** [comment]
Sorry, forgot to write it down.This is on versjon 7.4.5RegardsStigSendt fra min iPhone5. apr. 2024 kl. 15:45 skrev Tom Jaeger ***@***.***>:﻿
What version of ExpressionEngine is this in?
