### ISSUE TITLE
Getting e_wraning in preview mode when having an related entry with an members field

### ISSUE THREAD

**Issue by DalizPR** [ExpressionEngine/ExpressionEngine#4210]
Severity: E_WARNING
Warning
foreach() argument must be of type array|object, null given
ee/ExpressionEngine/Addons/member/ft.member.php, line 352

**Comment by shbchk** [comment]
Not sure if related, but I'm also getting this error in preview for an entry with related member field:

```
TypeError Caught
count(): Argument #1 ($value) must be of type Countable|array, string given
ee/ExpressionEngine/Addons/member/ft.member.php:433
```

**Comment by bryannielsen** [comment]
@DalizPR so the setup for this is editing an entry that has a relationship field to another entry which has a members field.  Is the members field on the related entry empty?  Also can you share a simplified version of the template that you're using for live preview?

**Comment by DalizPR** [comment]
The member field coming from the related entry is not empty. 

```
{opdracht_project:contactpersoon}
{contactpersoon:voornaam} {contactpersoon:achternaam}
   {/opdracht_project:contactpersoon}
```
Where {opdracht_project} is the relationship field and {contactpersoon} is the member field.

**Comment by DalizPR** [comment]
Also when listing a number of entries with the same tags i get this warning.

```
Warning
Undefined array key "field_id_126"
ee/legacy/libraries/channel_entries_parser/components/Custom_field.php, line 109
```

**Comment by DalizPR** [comment]
An other thing, not a bug but concerning the same member field. In the entries overview is can show this field in the grid but i can't seem to sort this by clicking on the table head for this field. Its probably missing the class `column-sort-header`
