### ISSUE TITLE
Replacement image uploads not updating CP thumbnails or on site frontend

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#4217]
When replacing existing images on a page, where the new file has the same filename as the old image...  either via editing an Entry directly...  or in the File Manager...  the visible thumbnails aren't updated to show the new image in the CP...  neither are the images updated on the frontend site.

This includes emptying the whole site Cache. I also don't have Template Caching switched on (yet).
It also includes when I use the "Resolve Conflict" function, to state that I wish to replace an existing image file.

My workaround to date, it to make sure I upload the image with a completely new filename (annoying).

EE 7.4.6
PHP 8.1

**Comment by bryannielsen** [comment]
@ic360-com I think I'm replicating this behavior when I upload a duplicate image through the Filemanager and choose the "Replace" option from the "Resolve Conflict" modal.  I see the old thumbnail in the file manager list but if I inspect the thumbnail and open that url in a separate window and refresh it looks correct.  Is this the behavior you're seeing too?

I just want to make sure you don't have a different issue where the replaced thumbnail is not actually being generated.  The error I'm seeing looks like a browser cache busting problem that we can try to address.

**Comment by ic360-com** [comment]
Hey Bryan,
Yes, I'm seeing that same behaviour... although yesterday when I was refreshing the image in the separate window, it wasn't playing ball. I'm also seeing the same behaviour when I replace an image from with the Edit Entry page.
Thanks.

**Comment by bryannielsen** [comment]
Hi Oliver, just wanted to let you know we have a fix that will take care of the control panel caching.  I think the front-end will be left up to you though, if you are replacing images like this a lot and want to keep the filenames the same I would recommend doing something similar to what we did in the CP and append the `modified_date` timestamp to your url.

That might look something like this:
```
{image}
    <img src="{url}?v={modified_date}" />
{/image}
```

**Comment by ic360-com** [comment]
Okay thanks Bryan.
To be fair, I think I'll probably do this as a default thing now, coz I can see clients coming to me - when they're trying to update blogs or products - saying things like, "I've changed the image in the CMS, but it's not updating on the site".
