### ISSUE TITLE
Member can't add a category

### ISSUE THREAD

**Issue by DalizPR** [ExpressionEngine/ExpressionEngine#4239]
Since updating to 7.4.6 one of my members (with almost full access) can't add a new category to an existing or new category group. Which was always possible.

The member in this role **can create** a new categorygroup but creating a category in that group is not possible. The system throws out an error:

_Error: You are not authorized to access this page_

Also, existing and previous made categories are no longer accessible

**Comment by intoeetive** [comment]
@DalizPR each category group has Permission tab which defines whether the members can manage categories in that group.

Prior to 7.4 there was a bug where these permissions were not always checked

You'd need to go though your category groups and assign proper permissions

**Comment by DalizPR** [comment]
Alright, this site just updated from 6 to 7.4.6, didn't notice this before. To bad I have to go through all catergygroups to enable the  permission when having a lot of groups. Thanks for pointing this out. 

Isn't it possible to set the permissions through the role setting options. The options for  **Channel categories**- _Users can perform all selected actions._  Create, Edit, Delete are checked.
