### ISSUE TITLE
Unable to Edit Entry instead its Giving Category, Categories Error!

### ISSUE THREAD

**Issue by paultz** [ExpressionEngine/ExpressionEngine#4243]
**Description of the problem**
 I am getting the below error when i try to edit and entry

**How To Reproduce**
1. Login to EE CMS
2. Go to Edit Entry
3. Click on Entry Title
4. See error below

**Error Messages**
<pre><code>
Exception Caught
SQLSTATE[42000]: Syntax error or access violation: 1104 The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay:
SELECT Category_categories.cat_id as Category__cat_id, Category_categories.site_id as Category__site_id, Category_categories.group_id as Category__group_id, Category_categories.parent_id as Category__parent_id, Category_categories.cat_name as Category__cat_name, Category_categories.cat_url_title as Category__cat_url_title, Category_categories.cat_description as Category__cat_description, Category_categories.cat_image as Category__cat_image, Category_categories.cat_order as Category__cat_order, Category_category_field_data.cat_id as Category__cat_id, Category_category_field_data.site_id as Category__site_id, Category_category_field_data.group_id as Category__group_id, Category_category_field_data.cat_id as Category__cat_id, Category_category_field_data.site_id as Category__site_id, Category_category_field_data.group_id as Category__group_id, Category_category_field_data.field_id_1 as Category__field_id_1, Category_category_field_data.field_ft_1 as Category__field_ft_1, Category_category_field_data.field_id_2 as Category__field_id_2, Category_category_field_data.field_ft_2 as Category__field_ft_2, C0_categories.cat_id as C0__cat_id, C0_categories.site_id as C0__site_id, C0_categories.group_id as C0__group_id, C0_categories.parent_id as C0__parent_id, C0_categories.cat_name as C0__cat_name, C0_categories.cat_url_title as C0__cat_url_title, C0_categories.cat_description as C0__cat_description, C0_categories.cat_image as C0__cat_image, C0_categories.cat_order as C0__cat_order, C0_category_field_data.cat_id as C0__cat_id, C0_category_field_data.site_id as C0__site_id, C0_category_field_data.group_id as C0__group_id, C0_category_field_data.cat_id as C0__cat_id, C0_category_field_data.site_id as C0__site_id, C0_category_field_data.group_id as C0__group_id, C0_category_field_data.field_id_1 as C0__field_id_1, C0_category_field_data.field_ft_1 as C0__field_ft_1, C0_category_field_data.field_id_2 as C0__field_id_2, C0_category_field_data.field_ft_2 as C0__field_ft_2, C1_categories.cat_id as C1__cat_id, C1_categories.site_id as C1__site_id, C1_categories.group_id as C1__group_id, C1_categories.parent_id as C1__parent_id, C1_categories.cat_name as C1__cat_name, C1_categories.cat_url_title as C1__cat_url_title, C1_categories.cat_description as C1__cat_description, C1_categories.cat_image as C1__cat_image, C1_categories.cat_order as C1__cat_order, C1_category_field_data.cat_id as C1__cat_id, C1_category_field_data.site_id as C1__site_id, C1_category_field_data.group_id as C1__group_id, C1_category_field_data.cat_id as C1__cat_id, C1_category_field_data.site_id as C1__site_id, C1_category_field_data.group_id as C1__group_id, C1_category_field_data.field_id_1 as C1__field_id_1, C1_category_field_data.field_ft_1 as C1__field_ft_1, C1_category_field_data.field_id_2 as C1__field_id_2, C1_category_field_data.field_ft_2 as C1__field_ft_2, C2_categories.cat_id as C2__cat_id, C2_categories.site_id as C2__site_id, C2_categories.group_id as C2__group_id, C2_categories.parent_id as C2__parent_id, C2_categories.cat_name as C2__cat_name, C2_categories.cat_url_title as C2__cat_url_title, C2_categories.cat_description as C2__cat_description, C2_categories.cat_image as C2__cat_image, C2_categories.cat_order as C2__cat_order, C2_category_field_data.cat_id as C2__cat_id, C2_category_field_data.site_id as C2__site_id, C2_category_field_data.group_id as C2__group_id, C2_category_field_data.cat_id as C2__cat_id, C2_category_field_data.site_id as C2__site_id, C2_category_field_data.group_id as C2__group_id, C2_category_field_data.field_id_1 as C2__field_id_1, C2_category_field_data.field_ft_1 as C2__field_ft_1, C2_category_field_data.field_id_2 as C2__field_id_2, C2_category_field_data.field_ft_2 as C2__field_ft_2, C3_categories.cat_id as C3__cat_id, C3_categories.site_id as C3__site_id, C3_categories.group_id as C3__group_id, C3_categories.parent_id as C3__parent_id, C3_categories.cat_name as C3__cat_name, C3_categories.cat_url_title as C3__cat_url_title, C3_categories.cat_description as C3__cat_description, C3_categories.cat_image as C3__cat_image, C3_categories.cat_order as C3__cat_order, C3_category_field_data.cat_id as C3__cat_id, C3_category_field_data.site_id as C3__site_id, C3_category_field_data.group_id as C3__group_id, C3_category_field_data.cat_id as C3__cat_id, C3_category_field_data.site_id as C3__site_id, C3_category_field_data.group_id as C3__group_id, C3_category_field_data.field_id_1 as C3__field_id_1, C3_category_field_data.field_ft_1 as C3__field_ft_1, C3_category_field_data.field_id_2 as C3__field_id_2, C3_category_field_data.field_ft_2 as C3__field_ft_2, CategoryGroup_category_groups.group_id as CategoryGroup__group_id, CategoryGroup_category_groups.site_id as CategoryGroup__site_id, CategoryGroup_category_groups.group_name as CategoryGroup__group_name, CategoryGroup_category_groups.sort_order as CategoryGroup__sort_order, CategoryGroup_category_groups.exclude_group as CategoryGroup__exclude_group, CategoryGroup_category_groups.field_html_formatting as CategoryGroup__field_html_formatting, CategoryGroup_category_groups.can_edit_categories as CategoryGroup__can_edit_categories, CategoryGroup_category_groups.can_delete_categories as CategoryGroup__can_delete_categories FROM (`exp_categories` as Category_categories, `exp_category_field_data` as Category_category_field_data) LEFT JOIN `exp_categories` AS C0_categories ON `C0_categories`.`parent_id` = `Category_categories`.`cat_id` LEFT JOIN `exp_category_field_data` as C0_category_field_data ON `C0_category_field_data`.`cat_id` = `C0_categories`.`cat_id` LEFT JOIN `exp_categories` AS C1_categories ON `C1_categories`.`parent_id` = `C0_categories`.`cat_id` LEFT JOIN `exp_category_field_data` as C1_category_field_data ON `C1_category_field_data`.`cat_id` = `C1_categories`.`cat_id` LEFT JOIN `exp_categories` AS C2_categories ON `C2_categories`.`parent_id` = `C1_categories`.`cat_id` LEFT JOIN `exp_category_field_data` as C2_category_field_data ON `C2_category_field_data`.`cat_id` = `C2_categories`.`cat_id` LEFT JOIN `exp_categories` AS C3_categories ON `C3_categories`.`parent_id` = `C2_categories`.`cat_id` LEFT JOIN `exp_category_field_data` as C3_category_field_data ON `C3_category_field_data`.`cat_id` = `C3_categories`.`cat_id` LEFT JOIN `exp_category_groups` AS CategoryGroup_category_groups ON `CategoryGroup_category_groups`.`group_id` = `Category_categories`.`group_id` WHERE Category_category_field_data.cat_id = Category_categories.cat_id AND ( `CategoryGroup_category_groups`.`group_id` = 10 AND `Category_categories`.`parent_id` = 0 ) LIMIT 18446744073709551615
ee/legacy/database/drivers/mysqli/mysqli_connection.php:114

Stack Trace: Please include when reporting this error
#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('SELECT Category...')
#1 ee/legacy/database/DB_driver.php(261): CI_DB_mysqli_driver->_execute('SELECT Category...')
#2 ee/legacy/database/DB_driver.php(176): CI_DB_driver->simple_query('SELECT Category...')
#3 ee/legacy/database/DB_active_rec.php(1083): CI_DB_driver->query('SELECT Category...')
#4 ee/ExpressionEngine/Service/Model/Query/Select.php(51): CI_DB_active_record->get()
#5 ee/ExpressionEngine/Service/Model/DataStore.php(275): ExpressionEngine\Service\Model\Query\Select->run()
#6 ee/ExpressionEngine/Service/Model/DataStore.php(220): ExpressionEngine\Service\Model\DataStore->runQuery('Select', Object(ExpressionEngine\Service\Model\Query\Builder))
#7 ee/ExpressionEngine/Service/Model/Query/Builder.php(152): ExpressionEngine\Service\Model\DataStore->selectQuery(Object(ExpressionEngine\Service\Model\Query\Builder))
#8 ee/ExpressionEngine/Service/Model/Query/Builder.php(65): ExpressionEngine\Service\Model\Query\Builder->fetch(false)
#9 ee/ExpressionEngine/Model/Category/CategoryGroup.php(207): ExpressionEngine\Service\Model\Query\Builder->all()
#10 [internal function]: ExpressionEngine\Model\Category\CategoryGroup->populateCategories(Object(ExpressionEngine\Model\Content\FieldFacade))
#11 ee/ExpressionEngine/Model/Content/FieldFacade.php(121): call_user_func(Array, Object(ExpressionEngine\Model\Content\FieldFacade))
#12 ee/ExpressionEngine/Model/Content/FieldFacade.php(481): ExpressionEngine\Model\Content\FieldFacade->ensurePopulatedDefaults()
#13 ee/ExpressionEngine/Model/Content/FieldFacade.php(356): ExpressionEngine\Model\Content\FieldFacade->initField()
#14 ee/ExpressionEngine/Model/Content/Display/FieldDisplay.php(67): ExpressionEngine\Model\Content\FieldFacade->getStatus()
#15 ee/ExpressionEngine/View/publish/partials/publish_form.php(92): ExpressionEngine\Model\Content\Display\FieldDisplay->getStatus()
#16 ee/ExpressionEngine/Service/View/View.php(137): include('...')
#17 ee/ExpressionEngine/Service/View/View.php(106): ExpressionEngine\Service\View\View->parse('...', Array)
#18 ee/ExpressionEngine/Service/View/View.php(165): ExpressionEngine\Service\View\View->render(Array)
#19 ee/ExpressionEngine/View/publish/entry.php(5): ExpressionEngine\Service\View\View->embed(Object(ExpressionEngine\Service\View\View))
#20 ee/ExpressionEngine/Service/View/View.php(137): include('...')
#21 ee/ExpressionEngine/Service/View/View.php(106): ExpressionEngine\Service\View\View->parse('...', Array)
#22 ee/legacy/libraries/View.php(40): ExpressionEngine\Service\View\View->render(Array)
#23 ee/legacy/libraries/Cp.php(337): View->render('publish/entry', Array, false)
#24 ee/ExpressionEngine/Controller/Publish/Edit.php(554): Cp->render('publish/entry', Array)
#25 [internal function]: ExpressionEngine\Controller\Publish\Edit->entry('344')
#26 ee/ExpressionEngine/Core/Core.php(266): call_user_func_array(Array, Array)
#27 ee/ExpressionEngine/Core/Core.php(122): ExpressionEngine\Core\Core->runController(Array)
#28 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#29 index.php(143): require_once('...')
#29 index.php(143): require_once('...')
</code></pre>

**Environment Details:**
 - Version: 6.4.16
 - PHP Version 7.2.9
 - MySQL Version 5.6.32
 - OS: Linux, Debian
 - Web Server: Apache

**Possible Solution**

**Additional context**

**Comment by intoeetive** [comment]
@paultz it looks like your `MAX_JOIN_SIZE` configuration for MySQL is too low.

Please raise it up (or talk to your hosting provider about doing that)

**Comment by paultz** [comment]
It seems to be tricky! as NETFIRMS shared hosting doesn't seem to support / increase MAX_JOIN_SIZE! is other way to fix this?

**Comment by intoeetive** [comment]
If you can lower down the number of nesting levels for categories, that should help

**Comment by paultz** [comment]
Ok, how do we go about lowering that?

**Comment by intoeetive** [comment]
That's on Categories page - or you're not able to access that as well?

We'll see if we can get a programmatic solution as well in the meantime

**Comment by paultz** [comment]
Categories can be viewed without an issue, however if there is programmatic solution i will be happy to..

**Comment by intoeetive** [comment]
@paultz for EE 7, you can add this to database configuration your `config.php`:
```
$config['database'] = array(
	'expressionengine' => array(
		...
		'MYSQL_ATTR_INIT_COMMAND' => 'SET SQL_BIG_SELECTS=1'
	),
);
```

I have tested and confirmed this to be working for your case

Unfortunately this configuration is not available for EE6

**Comment by paultz** [comment]
ok, let me upgrade EE and try the solution...

**Comment by paultz** [comment]
Upgraded to EE7 and implemented the solution and Its working fine now, thanks!
