### ISSUE TITLE
Structure: `{structure:page:url}` tag is not working if the page is accessed through `/group/template/entry_id` URL

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#4251]
EE 7.4.6

Steps to reproduce:

1. Add this code to your template:
```
structure:page:url: {structure:page:url}
```
2. Access the page using it's `/page_url`: tag works as expected.
3. Access the same page using the URL format `/group/template/entry_id`: tag renders blank

**Comment by bryannielsen** [comment]
@shbchk were you seeing this referenced in the docs somewhere?  I don't think these globals will automatically try to find a structure page given the third segment of a `template_group/template` url.  

But instead you should be able to do something like this:

```
Structure Page URI for Entry #{segment_3}: {structure:page_uri_for:{segment_3}}
```
