### ISSUE TITLE
Undefined index error from Pages module when Pages tab hidden in channel layout (5.3.2)

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#426]
**Description of the problem**
Saving a channel entry which has **neither** a template nor a page URL defined in the Pages module, results in a PHP notice when the Pages tab has been hidden using the channel publish layout:

<pre><code>
Undefined index: pages__pages_uri
ee/EllisLab/Addons/pages/tab.pages.php, line 155
Severity: E_NOTICE
</code></pre>

This looks to have been introduced in 5.3.2, as a consequence of https://github.com/ExpressionEngine/ExpressionEngine/pull/401

**How To Reproduce**
With a channel entry which does not use the Pages module (which has neither a template nor a URI defined using the Pages module):

Using the channel manager, create a publish layout for the channel. Include the Pages module tab in the layout. Edit/save the entry. This should work without error.

Modify the publish layout to hide the Pages module tab. Edit/save the entry. This should show the error above.

**Error Messages**
<pre><code>
Undefined index: pages__pages_uri
ee/EllisLab/Addons/pages/tab.pages.php, line 155
Severity: E_NOTICE
</code></pre>

**Environment Details:**
 - Version: 5.3.2
 - PHP Version: 7.033
 - OS: Ubuntu 16.04.14
 - Web Server: Apache 2

**Comment by PaulBaileyAtChan** [comment]
Addendum: It's likely this error also applies to saving channel entries which do use the Pages module, when the Pages publish layout tab is hidden (although that's less likely in practice, obv.). I just tried hiding the Pages tab for a channel which uses the Pages module, and hit the same error on saving. Basically: **hiding the Pages tab in the channel publish layout is resulting in errors on saving entries**.

**Comment by robinsowell** [comment]
You spotted the exact problem.  We've got a pull request in for a fix: https://github.com/ExpressionEngine/ExpressionEngine/pull/412

That should take care of it for you and it should be in the next release.  If you have any issues applying it, let me know.

**Comment by PaulBaileyAtChan** [comment]
Ah, my bad, I should have seen that. Thanks for letting me know.

**Comment by robinsowell** [comment]
LOL- technically it's my bad.  I created the bug ;)

**Comment by robinsowell** [comment]
Pull request was merged, closing.
