### ISSUE TITLE
Addon "Sitemap" cannot be completely uninstalled

### ISSUE THREAD

**Issue by bytebaby** [ExpressionEngine/ExpressionEngine#4261]
I'm a little desperate because I can't get the poorly programmed "Sitemap" add-on completely uninstalled. The result: When I create a new channel, I can neither post a new post nor create a field layout. The error message looks like this:

<img width="742" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/21154749/23ca4bc3-14bc-4f51-8617-5aa01f1b17b9">

As a test, I activated the addon again in the addon directory. The result is not surprising, because the database tables were deleted during uninstallation (I had to remove the addon because it doesn't run with PHP 8 and is no longer updated by the developer):

<img width="1176" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/21154749/ef9ebdcd-5b08-4b54-87af-468f17a2fea3">

I also searched all database tables to find the entry that ensures that a tab called "Sitemap" is automatically created in the editorial form when a new channel is created. Unfortunately without success

I sincerely ask for help. What could be done to finally eliminate this addon bug. Unfortunately, I also have the problem on two other customer sites that I took over.

Addendum: When I deactivate the tab with the layout manager, there are no error messages. I would do that after creating new channels, but I only then get around to creating a channel layout because the error messages (see above) occur.

<img width="560" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/21154749/f8fddd16-70ef-44b3-afe5-4948c0d48c4b">

 - EE 7.4.6
 - PHP 8.1

**Comment by intoeetive** [comment]
@bytebaby first, make sure the add-on is not listed in `exp_modules` table.

Secondly, make sure you still have the add-on files in user/addons folder (no need to install, just add the files) and edit your layouts. Make sure to delete the sitemap tab, not just hide it.

**Comment by bytebaby** [comment]
Wow, thanks, that works very well. But I don't see any way to delete the sitemap tab, the delete icon is missing. Is there another way?
<img width="298" alt="image" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/21154749/9d15f70e-2bde-493f-8fc5-2bf8a0a77208">

**Comment by intoeetive** [comment]
I think if you just save the layout, it might be gone... or it might be not. @robinsowell - got any better ideas?

**Comment by bytebaby** [comment]
If I simply save the layout, the tab stubbornly stays in its place (very clingy ;). If I create a new layout for the channel and then delete the old one, the tab also disappears. I am very glad! Thanks again!
