### ISSUE TITLE
Parsing of template partials which include line breaks results in inclusion of parse error? (5.3.2)

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#427]
**Description of the problem**
Parsing of a template partial which includes a line-break appears to include a PHP parse error notification at the end of the expansion of the partial. In most cases, this won't create a problem, because the error is then elided by later parsing, but it can be an issue, for example, if the partial is used as tag data for a non-trivial add-on.

**How To Reproduce**
This is not especially easy to see, since the PHP parse error appears as an EE comment, so is often elided by later stages of the main template parse. It's visible when grabbing the partial as tag data for an add-on, though.

For example, this works as expected:

```
{exp:mytest}
Hello
Goodbye
{/exp:mytest}
```

But create a template partial with exactly the same contents as the above example:

```
{exp:mytest}
{my_partial}
{/exp:mytest}
```

Examining the tag data inside the add-on shows, for example:

> Hello
> Goodbye{!-- ra:000000000f23febd00000000259783dc --}

Removing the line-break from the template partial gives no error:

> HelloGoodbye

Because hard-coded tag data doesn't create the parse error, and using a template partial without a line-break also doesn't create the error, it seems like the specific cause is the parsing of a template partial which includes a line-break.

**Environment Details:**
 - Version: 5.3.2
 - PHP Version: 7.033
 - OS: Ubuntu 16.04.14
 - Web Server: Apache 2

**Comment by robinsowell** [comment]
Hi Paul,

That's not indicative of an error, it's a placeholder, and meant to be replaced later on in the parsing.

Though it does seem odd that it's only there if there are multiple lines.  

I'm trying to think of how it could cause problems.  Is it causing an issue on your end?  It's not weird to have them- we do a lot of place holding as we parse through the templates.  The only bit that seems odd is the randomness.

**Comment by PaulBaileyAtChan** [comment]
Not a huge issue, but I'm playing with putting JSON in the tagdata and then decoding it in the add-on. Having it in there kills the JSON syntax. It's not hard to work around — I've added some simple code to remove it before the decode — but it's not clear why it should be in there in this situation.

**Comment by robinsowell** [comment]
Ah- I was wondering how you were even seeing the issue!

It does sound like a quirk in the parsing order.  But if you've got a working option, I'm going to leave it alone for now.  If it starts to prove troublesome, someone may need to take a deep dive into it.

**Comment by PaulBaileyAtChan** [comment]
Less concerned for me than someone else doing something similar, to be honest. Because, yes, this wasn't easy to diagnose. Do you feel able to mark it as confirmed?

**Comment by intoeetive** [comment]
@PaulBaileyAtChan can you share the portion of your addon that grabs the partial? I get a feeling like you do that before it's fully parsed

**Comment by PaulBaileyAtChan** [comment]
I can share the entire addon. This isn't the version that I use in practice on the site, but I kept it from when I was testing, to show the behaviour. It just grabs the tag data, then returns as a string, with the characters separated by spaces, so that the parse placeholder doesn't get elided later in the parse.

```
<?php

   if (!defined('BASEPATH')) exit('No direct script access allowed');


   class ChanTest
   {

      public $return_data = '';

      public function __construct()
      {

/* Grab the tagdata and return. */

         $result = '';
         $tagdata = ee() -> TMPL -> tagdata;
         for ($c = 0; $c < strlen($tagdata); $c++)
            $result .= $tagdata[$c] . " ";

         $this -> return_data = $result;

      }

   }

/* End of file pi.chantest.php */ 
/* Location: /system/user/addons/chantest/pi.chantest.php */
```

A typical call looks like:

```
{exp:chantest}
{test_partial}
{/exp:chantest}
```

With `{test_partial}` as:

`HelloGoodbye`

it gives:

`H e l l o G o o d b y e`

But with `{test_partial}` as:

```
Hello
Goodbye
```

it gives:

`H e l l o G o o d b y e { ! - - r a : 0 0 0 0 0 0 0 0 6 0 c 5 8 d 3 4 0 0 0 0 0 0 0 0 7 6 4 6 9 5 6 8 - - }`

I'm puzzled by your reply, though. My reading of the EE parse order is that partials are parsed way before addons. (?)

**Comment by intoeetive** [comment]
I tend to say this is not a bug. The `{!-- ra:...` stuff that you is what is called "Template Runtime Annotation". For single-line template code it's being skipped, but is being added when there are multiple lines (or at least, can be added).

It is being stripped off on the final stage - after everyone including addons are done with their work.

So for your particular case, you can get the clean input with this code:
`$tagdata = ee()->TMPL->parse_globals(ee()->TMPL->tagdata);`

**Comment by PaulBaileyAtChan** [comment]
I won't push this, but — with respect — it's hard to argue that this isn't inappropriate behaviour. The 'annotation' has no reason to be there at this stage, and the effect is to add housekeeping cruft to user data which then subsequently has to be removed.

So far as I can tell, your recommendation to run the data through `parse_globals` is only relevant because it happens to call `remove_ee_comments`, which cleans up the annotation. It works, but there's no reason why it should be necessary if the data needs no more parsing.

**Comment by intoeetive** [comment]
Noting that neither `parse_globals` not `remove_ee_comments` are currently described documentation - which is definitely what we need to get fixed
