### ISSUE TITLE
Mime type config doesn't affect .html files

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#4275]
weird one, but...

You can use a custom mime.php file in config to control what is, and what is not, allowed.

This worked fine with svg files- don't want to allow them, don't include them in the mime.php file.

It doesn't work with html files.  I commented out:

```
        'text/csv', // .csv
       // 'text/html', // .html, .htm
        'text/plain', // .log, .text, .txt
        'text/markdown', // .md
```
But can still upload an html file.  And I really can't spot why that's the case!

**Comment by intoeetive** [comment]
@robinsowell I'm not replicating this.

Did you override the whole `doc` section in `mimes.php`

There might also be chance that a specific HTML file is getting recognized as of different MIME? Though not very likely

**Comment by robinsowell** [comment]
Actually- you called it.  This particular file comes back as an image.  Other html files come back as html and altering the allowed mimes blocks them.  So... something different going on!
