### ISSUE TITLE
category_group within {categories} loop not limiting output to group

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#4276]
I'm trying output the Categories applied to an Entry... but only those categories within a specified Category Group.
There are multiple categories and multiple groups applied to an Entry, but I'm just trying to focus on a single group.

I was expecting this to work:
`{categories category_group="6"}
	{category_name}
{/categories}`

But I've had to resort to the following code instead:
`{categories show="32|33|34"}
	{category_name}
{/categories}`

EE 6.4.17
PHP 7.4

**Comment by bryannielsen** [comment]
@ic360-com I haven't tested this but I think you might need to just use [show_group](https://docs.expressionengine.com/v6/channels/entries.html#show_group) instead.

Let me know if that doesn't solve it for you!
