### ISSUE TITLE
count and total_results not working in {categories} loop

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#4277]
I'm trying to use the {count} an {total_results} variable within a {categories} loop, but both values are always rendering as '1'.
FYI: This is an Embedded template.

`{categories}
{count} {total_results}
{/categories}`

EE 6.4.17 and 7.4.6
PHP 7.4 and 8.1

**Comment by bryannielsen** [comment]
@ic360-com sorry for the delay!
I think you're getting the results from your {exp:channel:entries} loop, you'll need to use these variables instead - 
```
{categories}
    {category_count}
    {category_total_results}
{/categories}
```

Here's the [ExpressionEngine docs page for the {categories} variables](https://docs.expressionengine.com/latest/channels/entries.html#categories-tag-pair-variables)
