### ISSUE TITLE
Ability to group individual fields with a grid field

### ISSUE THREAD

**Issue by coltcox** [ExpressionEngine/ExpressionEngine#4281]
When building a site I often use a fluid field for a page to create "modules" and provide flexibility as to what content the client is able to add. This fluid field will often contain around a dozen or more different grid fields each with different fields getting displayed on the front end. In single item instances (a grid limited to a single row), this works great because it can contain both the fields needed for content and fields needed to modify the module. This customization might be something like changing the color scheme of the module, or adjusting the margin below the module. If the module is a collection of items (a grid with multiple rows) I lose the ability to add this customization because the fields are all now related to the looped content and not a single item. It would be nice if there was a way to create a group of fields that could be assigned to a fluid field row. This could be a combination of text fields, toggles, selects, and a single grid field for the content.

**Current Setup**
<img width="912" alt="current" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/11790007/13f88790-8aa2-438e-8531-ae795c3d9e17">

**Ideal Setup**
<img width="912" alt="ideal" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/11790007/63c0a7e9-e5a1-411a-9d1f-835c35e5bd2c">

**Comment by bryannielsen** [comment]
@coltcox thanks for sharing this idea!

Have you tried to setup a Field Group with a grid and then a few toggles and then use that group within your Fluid Field?

I think for your example it might look something like:

**Field Group** 
Name: Icon List
Fields:
- Icons (Grid)
    - Icon (File)
    - Text Content (RTE)
- Wide (Toggle)
- Dark BG (Toggle)
- Remove Bottom Padding (Toggle)
- Remove Bottom Margin (Toggle)

And then you would assign "Icon List" as a group available in your Fluid field.  

Let us know if that doesn't accomplish what you're looking for though!

**Comment by coltcox** [comment]
@bryannielsen I didn't realize this was possible, this is exactly what I needed. Thanks!

**Comment by bryannielsen** [comment]
Excellent!  Good luck with that and let us know if you run into any issues along the way!
