### ISSUE TITLE
Relationship Drop Down UI

### ISSUE THREAD

**Issue by jmathias** [ExpressionEngine/ExpressionEngine#43]
**Is your feature request related to a problem? Please describe.**
When a single relationship field appears in a Grid the UI is too big and makes it more difficult than intended to interact with that field.

**Describe the solution you'd like**
Allow the site builder to choose between the standard Relationship UI, and a Relationship in a Drop Down UI, with search. This could be a toggle option in the field create/edit forms.

**Describe alternatives you've considered**
In this case, none.

**Teachability, Documentation, Adoption, Migration Strategy**
This is a UI option, and not a feature so I think there would be very little in way of documentation. Perhaps adding a section to https://docs.expressionengine.com/latest/fieldtypes/relationships.html

>**Use Drop Down UI**
When set to on, the Relationship UI will use a Drop Down UI with a search filter. This is best for instances where the Relationship field appears inside another fieldtype, like Grid.
**Note**: This only applies to single Relationships, multiple relationships always use the standard UI.

I have it on good authority that this is a feature many people would use if available. And it should require no migration of data.

- [ ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by blue-dreamer** [comment]
I second this. If you have a grid with several columns and one or more relationship fields it can make editing quite cumbersome, sometimes requiring a lot of sideways scrolling.

**Comment by intoeetive** [comment]
Since the UI of Relationship field in EE6 has been changed, this issue does not appear to be relevant anymore.

We have noticed though there are certain other issues in Relationship field UI when used inside Grid, and we will work on getting those fixed.
