### ISSUE TITLE
Blacklist/Whitelist EE Addon: Clicking “Download EE Blacklist” gives a PHP Error

### ISSUE THREAD

**Issue by stevehaworth** [ExpressionEngine/ExpressionEngine#431]
Blacklist/Whitelist EE Addon. Clicking “Download EE Blacklist” gives a PHP Error:

Notice
Undefined offset: 0
ee/legacy/libraries/Xmlrpc.php, line 1388
Severity: E_NOTICE

Ironically, clicking ‘Report Bug’ in EE CP, the subsequent webpage at expressionengine.com (https://expressionengine.com/support/bugs/new) has a link on it to check ‘list of recently reported bugs’, which when clicked gives a 404.

PHP Version 7.0.33
EE v5.2.3 Build: 22/4/2020

**Comment by ops-andy** [comment]
resolved in EE6. Will be resolved in 5.4 as well on release.
