### ISSUE TITLE
Entry loses its category when modifying file grid fieldtype content of the entry.

### ISSUE THREAD

**Issue by pixiwooh** [ExpressionEngine/ExpressionEngine#433]
On a project (EE 5.3.2) I just noticed that every time I modify content of file grid fieldtype entry, it is like the entry loses the category (but the category checkbox is still well checked).
I noticed this while outputting entries by `{exp:channel:entries channel="my_channel" category="1"}`, the entry modified just disappears. To make it "come back" I have to go into the entry, uncheck and check again the category, then save and hourraaa my entry is back on the template.

Apparently someone has the same with entries loosing their status (see https://eecms.slack.com/archives/C04CUNNR9/p1589981498130100 ).

**Comment by intoeetive** [comment]
@pixiwooh I'm unable to replicate this so far. 
Is File Grid the only field in your entry, or you have other ones as well? And when you modify content - is that in this field, or just anything in the entry?
Lastly, what extensions do you have installed?

**Comment by intoeetive** [comment]
Closing as we did not get any updates on this issue
