### ISSUE TITLE
Odd behaviour with Fluid fields and Field groups on cloning an entry

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#4356]
**Description of the problem**
Have setup a number of Field Groups that are then referenced by a fluid field.
In normal use this allows me to define page content that re-uses a number of base level fields repeatedly in different field-group contexts. For example in this page you can see multiple instances of the "Fluid text plus image" field group.
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/b2a72a12-e693-4f00-a0aa-e6530e65393d)

However when this entry is 'cloned' you can see that the field group "Fluid text plus image" is broken by the process - what were blocks of three text fields followed by two images now has a series of incomplete / broken field groups (alternating between having two images and three text fields).  You can see similar breakage to the field group "Fluid client quotes element".
![image](https://github.com/ExpressionEngine/ExpressionEngine/assets/13821249/8605f1c2-ac42-45fa-90f5-d0082c75b05b)

**How To Reproduce**
As described above

**Environment Details:**
 - Version: 7.4.10
 - PHP Version 8.3
 - 
**Possible Solution**
Adding new instances of the field group from the fluid field fixes the issue on a per-fieldgroup basis, but it would be better if the cloning worked properly.

**Comment by intoeetive** [comment]
@bryannielsen could this be something related to #3865?

**Comment by bryannielsen** [comment]
@jcogs-design along the same lines as my response in #4443 I suspect that this issue is resolved in the latest version of 7.5.  I haven't been able to reproduce this behavior of the field group getting split on clone but if you are still seeing the issue please feel free to re-open this ticket
