### ISSUE TITLE
EE Warning re: file dimensions with SVG

### ISSUE THREAD

**Issue by ttmwebdesign** [ExpressionEngine/ExpressionEngine#4358]
**Description of the problem**
EE warnings shown with either debug=1 or 2 on the config.php file, on any page with an SVG that was uploaded into the file manager. One warning per SVG on the page:

```
Warning
Undefined array key 1
ee/ExpressionEngine/Model/File/FileDimension.php, line 123

Severity: E_WARNING
```

Looking at the SVG in file manager, I believe this is due to it having its dimensions as 'x px' or nothing is present at all, and not a numerical representation. See screenshots of the two examples.

**How To Reproduce**
1. Upload SVG.
2. Load front end page with SVG.
3. If logged in w/debug running, see warning, one for every SVG on the page uploaded & called by the fields from file manager.

**Error Messages**

<pre><code>
Warning
Undefined array key 1
ee/ExpressionEngine/Model/File/FileDimension.php, line 123

Severity: E_WARNING

</code></pre>
This is the extent of the warnings, even with debug=2 on config.php and debug=1 on index.php.

**Screenshots / Videos / Template Code**

<img width="673" alt="Screenshot-1" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/12754955/81417cea-4b69-4af2-9f02-f15f5c115f3b">
<img width="431" alt="Screenshot-2" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/12754955/70915b46-10fa-4007-b5c9-1657c7aad136">

**Environment Details:**
 - Version: 7.4.6
 - PHP Version 8.1 (both local/staging)
 - MariaDB Version  10.4.32 (local) // MySQL 8.x (staging)
 - OS: macOS (local) // Ubuntu 22.04 (staging)
 - Web Server: nginx (both)

**Possible Solution**
Since it only appears with debug on, it will of course be set to 0 for the client but it would be great to make it go away on local builds and staging when it's set to debug other than 0.

**Additional context**
n/a

Thanks!

**Comment by dougblackjr** [comment]
Can also confirm this is happening.

**Comment by intoeetive** [comment]
@ttmwebdesign @dougblackjr I wasn't able to replicate the issue, but the referenced PR should fix it. Perhaps you could check it out and add your approval if it works well

**Comment by dougblackjr** [comment]
@intoeetive Commented on the PR! Really, really good to hear from you Yuri!
