### ISSUE TITLE
Class 'ZipArchive' not found

### ISSUE THREAD

**Issue by maxibwoy** [ExpressionEngine/ExpressionEngine#4389]
Updating ... from 6.3.4 to 6.4.17 I'm getting this error "Class 'ZipArchive' not found"

**Comment by dougblackjr** [comment]
For the [ZipArchive class](http://www.php.net/manual/en/class.ziparchive.php) to be present, PHP needs to have the [zip extension](http://www.php.net/manual/en/book.zip.php) installed.

See [this page](http://www.php.net/manual/en/zip.installation.php) for installation instructions (both Linux and Windows).

On Debian and Ubuntu, you can usually install it with:

```
sudo apt update
sudo apt install php(your version)-zip
```

Replace your version with your version, like `sudo apt install php8.3-zip`

Then enable it in Apache or Nginx:

```
sudo systemctl restart apache2
sudo systemctl restart nginx
```
