### ISSUE TITLE
Pro variables - peculiar behaviour relating to conditionals ... 

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#4391]
**Description of the problem**
Have a block of template code that generates JCOGS Image processed images.
The whole block sits within a conditional that is based on the value of a pro_variable.
Seems that regardless of whether the condition within the conditional fires or not, the content of the code within the conditional is evaluated: we know this because the JCOGS Image debugging function reports the processing occurring - even if the template code enclosed within conditional is does not appear in the template output.

This is a problem because (in this case) the enclosed template code triggers some heavy-duty image processing that is (due to the pro_variables thing reported here) undertaken by the site regardless of whether it is needed or not. 

In general, including a pro_variable value in a conditional should not lead to the content of the conditional being pre-emptively evaluated and then discarded if not needed.

**How To Reproduce**
See code sample below.

**Screenshots / Videos / Template Code**
<pre><code>{if '{exp:pro_variables:single var="lv_home_carousel_youtube"}' == ''}
    <div class="slide image-fill">
        {exp:jcogs_img:image src='cats.jpg' width='768'}
    </div>
{/if}</code></pre>

Like this the content of the conditional is evaluated even if the enclosed template code is not then manifest within the HTML output from EE.

Change the code to this ... 
<pre><code>{if 'cats' == 'evil'}
    <div class="slide image-fill">
        {exp:jcogs_img:image src='cats.jpg' width='768'}
    </div>
{/if}</code></pre>

and the enclosed template code is no longer evaluated.

**Environment Details:**
 - Version: 7.4.11
 - PHP Version 8.1

**Additional context**
In the short term we have fixed this by putting the enclosed template code into an embed - if you do this then it appears that the embed is not evaluated as part of the conditional processing. vis... 
<pre><code>{if '{exp:pro_variables:single var="lv_home_carousel_youtube"}' == ''}
    {embed='stuff/image_stuff'}
{/if}</code></pre>
works as it should (but incurs an additional embed).

**Comment by blue-dreamer** [comment]
Does the same happen if you query the PV field directly?

```
{if lv_home_carousel_youtube == ""}
        {exp:jcogs_img:image src='cats.jpg' width='768'}
{/if}
```
PV early parsing must be enabled, and active on the lv_home_carousel_youtube field.

**Comment by intoeetive** [comment]
Whether it's Pro Variable or not, what EE template parser sees is a tag, in this case `exp:pro_variables:single` 

The tags are processed together, and EE will only know the results once all tags are processed.

The approach suggested by blue-dreamer should work - just as the approach with embeds that you used

Unfortunately there's no way to fix it without general rewriting of template parser, so I'll have to close this issue
