### ISSUE TITLE
Addon Control Panel Routes do not work with multiple segments

### ISSUE THREAD

**Issue by ee-forge** [ExpressionEngine/ExpressionEngine#4400]
**Description of the problem**
When an addon attempts to use a multi-segment route in the control panel (example:  /item/edit) the $id parameter is not preserved.  It is re-written to the `action` parameter and the `id` parameter is therefore lost.

**Comment by intoeetive** [comment]
@ee-forge can you specify some more details? Perhaps give an example. It's not quite clear what exactly the problem is vs what you're trying to achieve

**Comment by ee-forge** [comment]
@intoeetive I have a custom addon with control panel routes such as `/item/$id` and `/item/edit/$id` which seems should be a normal and allowable structure.  However the $id is being "stripped/lost" and the action (`edit`) is being passed forward to the controller route as the $id.  This seems to be occurring in the buildObject method of ExpressionEngine\Service\Addon\Mcp by it assuming the older Mcp/ folder approach first and as a result rewriting the $id on line 108.

**Comment by intoeetive** [comment]
This is expected. The named route variables are expecting the variable at a certain place.

That being said, you can use `ee()->uri->segment(3)` to get the value
