### ISSUE TITLE
php eecms upgrade from 5.4.3 to 6.4.17 fails

### ISSUE THREAD

**Issue by bdelamotte** [ExpressionEngine/ExpressionEngine#4402]
**Description of the problem**
I'm tried to update from 5.4.3 to 6.4.17. I am running the update manually via `php eecms upgrade -v` but I get this error: `Cannot rollback, updater microapp not found`. I had previously did a successful update from on 5.2.4 to 5.4.3 beforehand.  Site still works fine but is still the 5.4.3 version after running this so the upgrade failed.

**How To Reproduce**

**Error Messages**
Cannot rollback, updater microapp not found
<pre><code>
# php eecms upgrade -v
There is a new version of ExpressionEngine available: 6.4.17
Would you like to upgrade? (y/n): y
==> Preflight check...
==> Maximum execution time: 0
==> Memory limit: 256M
==> Checking file permissions needed to complete the update
==> Cleaning up upgrade working directory
==> Old zip archives found, deleting
==> Old extracted archives found, deleting
==> Checking free disk space
==> Free disk space (bytes): 8611041280
==> Downloading update...
==> Downloading update package
==> Unpacking update...
==> Unzipping package
==> Package unzipped
==> Verifying integrity of unzipped package
==> Package contents successfully verified
==> Checking server requirements of new ExpressionEngine version
==> Server requirements check passed with flying colors
==> Moving the updater micro app into place
==> Taking the site offline
Cannot rollback, updater microapp not found.
</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 5.4
 - PHP Version: 7.4
 - MySQL Version: 5.7
 - OS: Linux
 - Web Server: Apache

**Possible Solution**
The error is thrown in `ee/updater/eecms.phar/src/upgrade.php` on line 75.

```
74         if (! class_exists('ExpressionEngine\Updater\Service\Updater\Runner')) {
 75             exit('Cannot rollback, updater microapp not found.');
 76         }
```

So I checked if that class exists. It does in `ee/updater/ExpressionEngine/Updater/Service/Updater/Runner.php`.

So I tried to get around this by putting 
```
require_once('./updater/ExpressionEngine/Updater/Service/Updater/Runner.php');
```
in the code. 

But that doesn't work because every time you run the updater, it will try to overwrite the updater folder. 

**Additional context**

**Comment by intoeetive** [comment]
Since EE5 has reached its [end of life](https://expressionengine.com/support/version-support), we can't provide support on this issue

You can update using web interface, of you need to use CLI you can download latest version manually and use the new [Command Line Interface](https://docs.expressionengine.com/latest/cli/intro.html)
