### ISSUE TITLE
Open HTTP Redirection

### ISSUE THREAD

**Issue by ataucher** [ExpressionEngine/ExpressionEngine#4407]
Has the open HTTP redirection vulnerability been fixed in 7.4.11? I'm still seeing a "redirect warning" page which seems like it'd be pretty easy to still get past? For instance running **https://mywebsite.com/?URL=https://maliciouswebsite.com** i can get through.

This is in regards to the 7.3.15 vulnerability.
[https://bishopfox.com/blog/expressionengine-v-7-3-15-vulnerability](https://bishopfox.com/blog/expressionengine-v-7-3-15-vulnerability)

I've had many sites affected by this, specifically running google ads (since the traffic is obviously higher).

**Comment by bryannielsen** [comment]
@ataucher The items from the Bishop Fox link you referenced are resolved in 7.4.11 but if you wish to disable redirects from your site you can modify that behavior with this config variable [allow_url_redirects_from_site](https://docs.expressionengine.com/latest/general/system-configuration-overrides.html#allow_url_redirects_from_site)

**Comment by dougblackjr** [comment]
@ataucher I did the code around this. I always forget its there because I'm usually logged in. If you are still seeing this and you are in an incognito window, hit me up in the EE Slack.

**Comment by ataucher** [comment]
I get a 404 when testing in incognito mode. When not in incognito, i get this warning:
<img width="798" alt="Screenshot 2024-08-23 at 9 41 32 AM" src="https://github.com/user-attachments/assets/06266820-a70e-4f55-85a0-099dca53aa11">
