### ISSUE TITLE
Channels with Latin characters transform in entities in Channel's list name

### ISSUE THREAD

**Issue by avantiz** [ExpressionEngine/ExpressionEngine#4408]
**Description of the problem**

When you publish channels with Latin characters, the characters transform in entities (eg: "Ç"  changes "&ccedil;" in the Channels list, buts in the channel form edit page it's ok.

**How To Reproduce**

1. Create a new channel with a Latin character 
2. See the Channel names list

**Screenshots / Videos / Template Code**

<img width="647" alt="Screenshot 2024-07-29 at 23 18 08" src="https://github.com/user-attachments/assets/c49c6c0e-04d3-47c8-8843-e568f89d2f78">
<img width="600" alt="Screenshot 2024-07-29 at 23 18 19" src="https://github.com/user-attachments/assets/71ab01da-f359-4472-bbc1-557ffcbaafdb">
<img width="573" alt="Screenshot 2024-07-29 at 23 18 26" src="https://github.com/user-attachments/assets/0f247334-19ed-4741-8e63-eb6906c6e92c">

**Environment Details:**
 - Version: 7.4.11
 - PHP Version 8.2
 - MySQL Version 5.8
 - OS: MacOS / Ubuntu
 - Web Server: MAMP / nginx

**Comment by benoitlemay** [comment]
Any idea when this will be fixed?

**Comment by matthewjohns0n** [comment]
This issue is scheduled to be fixed in 7.5.6.
