### ISSUE TITLE
'Choose Existing' causes page to jump to the top

### ISSUE THREAD

**Issue by chrisdaviesweb** [ExpressionEngine/ExpressionEngine#4410]
ExpressionEngine v7.4.11
Testing in Firefox and Chrome
Specifically in file grid

Upon selection of the 'Choose Existing' button via a file grid field (may be other file fields), the page jumps to the top as the files overlay opens. If this is then closed, or a file selected, the user has to scroll back to the field which they are working on. This has become especially apparent when long entries with fluid fields are included.

**Comment by robinsowell** [comment]
See https://github.com/ExpressionEngine/ExpressionEngine/pull/4195
