### ISSUE TITLE
Warning Undefined array key “updating” ee/ExpressionEngine/Service/File/Usage.php, line 59

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#4417]
You can get an undefined array key warning when running File usage sync.

```
    protected function initializeFieldsAndTables()
    {
        $data = ee()->cache->get(self::CACHE_KEY);
        if ($data === false || $data['updating'] === false) {
            $this->buildFieldsAndTables();
            $this->cache();
        } else {
```
note- cache should '@return	mixed	value matching $id or FALSE on failure' so that bit should be ok.  Just the 'updating' check that may be unset.

SO the OR is correct option above, but somehow updating is simply not set sometimes.  Which... really makes no sense.  Maybe OLDER versions didn't including updating in the cache.  Money bet that's it.  Hrm- so I think we do need a new cache- do we need to clear existing before adding?

**Comment by intoeetive** [comment]
@robinsowell appears that content reindex and file usage reindex utilities were using same cache key. I have pushed the fix, and I think it's best if we can release it soon
