### ISSUE TITLE
Error running Tools - Content Reindex

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#4421]
Forum thread: https://expressionengine.com/forums/topic/254015/errors-when-going-to-tools-content-reindex-after-7.4.11-upgrade.  Read down- couple of issues going on. This one is:

TypeError Caught count(): Argument #1 ($value) must be of type Countable|array, null given ee/ExpressionEngine/Controller/Utilities/Reindex.php:47

Stack Trace: Please include when reporting this error 
0 ee/ExpressionEngine/Controller/Utilities/Reindex.php(47): count() 
1 [internal function]: ExpressionEngine\Controller\Utilities\Reindex->index() 
etc

I think the problem is similar to https://github.com/ExpressionEngine/ExpressionEngine/issues/4417

Service/Channel/Reindex has

```
    public function initialize()
    {
        $data = ee()->cache->get(self::CACHE_KEY);
        if ($data === false || $data['reindexing'] === false) {
            $fields = $this->getFields();
            $this->field_ids = $this->getFieldIdNames($fields);
            $this->entry_ids = [
                'all' => $this->getEntryIds($fields)
            ];
            if ($this->site_id != 'all') {
                $this->entry_ids[$this->site_id] = $this->getEntryIds($fields, $this->site_id);
            }
            $this->cache();
        } else {
            $this->field_ids = $data['field_ids'];
            $this->entry_ids = $data['entry_ids'];
            $this->reindexing = $data['reindexing'];
        }
    }
```
I think issue being intermittent is related to being cached.  And looking at it, 'all' isn't set in the else but over in the controller where the error comes from, it's looking for it:

```
        ee()->javascript->set_global([
            'reindex' => [
                'endpoint' => ee('CP/URL')->make('utilities/reindex/process')->compile(),
                'entries' => [
                    'all' => count($this->service->entry_ids['all']),
                    'one' => count($this->service->entry_ids[$this->service->site_id])
                ],
```
I didn't try a fix, because I'm not dead sure which is correct.

**Comment by intoeetive** [comment]
I agree that it's same issue as #4417 and #4428 should fix it as well. 

@robinsowell please close if you can confirm the fix to work
