### ISSUE TITLE
French characters encoded on Field name and/or Channel name

### ISSUE THREAD

**Issue by benoitlemay** [ExpressionEngine/ExpressionEngine#4464]
**Description of the problem**
On latest EE 7.4.11, when creating a new channel or field with french characters in the Name (éà etc).. The name is encoded.. see the screenshot attached.. 

![image](https://github.com/user-attachments/assets/5fc32d58-9a22-4ca7-94b3-46887556e8f8)

**Comment by benoitlemay** [comment]
Seems to be a duplicate of issue #4408.

**Comment by intoeetive** [comment]
@matthewjohns0n this is related to your commit #f64e95c - I'm not sure why it was made in first place, so letting you resolve the issue

**Comment by matthewjohns0n** [comment]
This issue is scheduled to be fixed in 7.5.6.
