### ISSUE TITLE
[EE7] "X Members" link attached to each role in Role Manager doesn't work correctly / as expected

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#4468]
The "X Members" tag displayed with each role in EE's role manager (see screenshot) is an active link, which seems intended to link to a display of just those members. But the link for each role is exactly the same, and just links to a full member list.

<img width="861" alt="Screenshot 2024-09-13 at 2 11 40 PM" src="https://github.com/user-attachments/assets/15cda31e-5a06-4c15-b749-57e856dd3449">

**Comment by shbchk** [comment]
And BTW, that number is not always correct
