### ISSUE TITLE
Suggest adding pass-through "class" attribute to {encode} tag, for CSS hook

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#4469]
I'd like to suggest adding support for a `class` attribute to the `{encode}` tag, to be passed through to the JS-encoded `<a>` tag, to allow better customization of formatting, etc. For example:

`{encode="example@email.com" class="my-class"}`

CSS **could** be attached to the `{encode}` tag using surrounding HTML, but this would provide a cleaner, simpler solution, and one which was easier to integrate with existing CSS.

**Comment by intoeetive** [comment]
We do already have this request, so closing this one. https://github.com/ExpressionEngine/ExpressionEngine/discussions/3218
