### ISSUE TITLE
Add Custom Fields to Bulk Edit

### ISSUE THREAD

**Issue by benoitlemay** [ExpressionEngine/ExpressionEngine#4485]
Would be nice to add our custom fields to the Bulk Edit functionnality...  
Sure we'll have to select entries from 1 channel only (or maybe not!?)..

**Comment by benoitlemay** [comment]
DUPLICATE

**Comment by intoeetive** [comment]
Similar to #4220 and will be resolved with https://github.com/ExpressionEngine/ExpressionEngine/pull/4273
