### ISSUE TITLE
Dark mode - usability issue

### ISSUE THREAD

**Issue by jelle-burodeng** [ExpressionEngine/ExpressionEngine#4492]
I really don't know how to accurately describe this, but site editors brought it to my attention that the suggestion below the input field is nearly unreadable in dark mode
![image](https://github.com/user-attachments/assets/5502d49b-1050-4efa-a0dc-2de394ce3420)

**Comment by intoeetive** [comment]
@bakin1999 I think this belongs to Tags add-ons

**Comment by bakin1999** [comment]
Yes, we will get a release out for the Tag add-on about this

**Comment by bakin1999** [comment]
Tag version 7.2.3 has now been released and has the fix for this
