### ISSUE TITLE
German umlauts like Ä ö etc are not displayed in lists

### ISSUE THREAD

**Issue by bytebaby** [ExpressionEngine/ExpressionEngine#4495]
No umlauts are displayed in the Channel Manager list, see screenshot.
<img width="1015" alt="Firefox 2024-09-27 14 02 28" src="https://github.com/user-attachments/assets/8fbcfc15-b2ac-4d2a-a4c6-650c2fe7f914">

The same error in field management
<img width="426" alt="Firefox 2024-09-27 14 07 32" src="https://github.com/user-attachments/assets/d1397508-cc4c-4028-a114-6b006ba711dc">

EE 7.4.11

**Comment by intoeetive** [comment]
@bytebaby thank you for the report. It's same issue as in https://github.com/ExpressionEngine/ExpressionEngine/issues/4464 so I'll close this one
