### ISSUE TITLE
Template search doesn't paginate properly for <h

### ISSUE THREAD

**Issue by nep** [ExpressionEngine/ExpressionEngine#450]
**Description of the problem**
When you search in templates for the < or > character, the template pagination links at the bottom of the first page of results encodes them as HTML characters, but then pagination doesn't work properly.

**How To Reproduce**
1. Have a site with a lot of templates. Go to the template manager: /system/index.php?/cp/design
2. Search for <h   ... get a lot of results 
3. Click on the Page 2 link or any other pagination link: /system/index.php?/cp/design/template/search&search=%26lt%3Bh&perpage=25&sort_col=template&sort_dir=asc&page=2
4. See error:  No Templates found.

**Error Messages**
No Templates found.

**Environment Details:**
 - Version: 5.3.2
 - PHP Version N/A
 - MySQL Version N/A
 - OS: N/A
 - Web Server: N/A

**Possible Solution**
Properly html-decode the < > . Or don't double encode it in the pagination links. Just be careful not to echo it out in the search box or "we found" section problematically.

**Comment by PaulBaileyAtChan** [comment]
+1 Have also found this to be a problem. A workaround which avoids pagination is to use the 'show' drop-down to show all results on one page (if practical), but it would be good to fix the search term encoding for pagination.
