### ISSUE TITLE
 E_NOTICE for ob_end_clean() and ob_end_flush()

### ISSUE THREAD

**Issue by wmurfee** [ExpressionEngine/ExpressionEngine#4515]
**Description of the problem**
This is an issue on EE 7.3+ with PHP 8.2+ with ob_end_clean() and ob_end_flush() located in View.php. I'm getting the errors below in my control panel when debugging. 

**Error Messages**
<pre><code>ob_end_clean(): Failed to delete buffer. No buffer to delete
ee/ExpressionEngine/Service/View/View.php, line 142
Severity: E_NOTICE
ob_end_flush(): Failed to delete and flush buffer. No buffer to delete or flush
ee/ExpressionEngine/Service/View/View.php, line 167
Severity: E_NOTICE</code></pre>

**Error Log**
ERROR - 2024-10-08 14:59:58 --> Severity: E_NOTICE  --> ob_end_clean(): Failed to delete buffer. No buffer to delete /var/www/html/admin/ee/ExpressionEngine/Service/View/View.php 142
ERROR - 2024-10-08 14:59:58 --> Severity: E_NOTICE  --> ob_end_flush(): Failed to delete and flush buffer. No buffer to delete or flush /var/www/html/admin/ee/ExpressionEngine/Service/View/View.php 167

**Environment Details:**
This is my local environment running DDEV, which is up to date.

**Possible Solution**
This seemed to fix it, or at least make the notice go away.

Error on admin/ee/ExpressionEngine/Service/View/View.php 142:
```
if (ob_get_level()) {
			ob_end_clean();
		}
```
Error on admin/ee/ExpressionEngine/Service/View/View.php 167:
```
 if (ob_get_level()) {
			ob_end_flush();
		}
```

**Comment by intoeetive** [comment]
@wmurfee would you mind trying the fix suggested in referenced pull request if it's also fixing the issue? https://github.com/ExpressionEngine/ExpressionEngine/pull/4524

**Comment by wmurfee** [comment]
@intoeetive Seems to have fixed the `ob_end_clean()` notice, but the ob_end_flush() notice is still showing:

```
Notice
ob_end_flush(): Failed to delete and flush buffer. No buffer to delete or flush
ee/ExpressionEngine/Service/View/View.php, line 171
Severity: E_NOTICE
```

**Comment by wmurfee** [comment]
@intoeetive also, not sure if this error is related, but it's in about the same place in the code:
```
Warning
Cannot modify header information - headers already sent by (output started at ee/ExpressionEngine/Service/View/View.php:168)
ee/ExpressionEngine/Boot/boot.common.php, line 478
```

**Comment by bryannielsen** [comment]
@wmurfee I've pushed another commit up to that PR branch to resolve an issue with failing tests.  Would you mind testing one last time and we'll get this into 7.5.2 if it looks good on your end.

**Comment by wmurfee** [comment]
@bryannielsen Just tested it, looks good on my end. No `ob_end_clean()` or `ob_end_flush()` errors.
