### ISSUE TITLE
Log all cookies consents (from logged-in AND logged-out users)

### ISSUE THREAD

**Issue by pixiwooh** [ExpressionEngine/ExpressionEngine#454]
Now that GDPR rules have been reenforced, we have to log every cookies consent (even the non logged-in users'ones), so we can prove we received it.

So my feature request for EE6 is : log all cookies consents (from logged-in and logged-out users) so we can stop to rely on third-party monthly-fee services to handle this.

The export of the consent list could look like this (.csv) : 

`DATE-TIME | CONSENT-ID | CONSENT-URL | CONSENT-PREFERENCES | CONSENT-STATISTICS | CONSENT-MARKETING | USER-IP-ANONYMIZED | USER-AGENT | IP-COUNTRY

2020-06-25T08:51:11.4970000 | Hj2VIYfCNdwpC4+bxDIkFMho3jyMJUE9WEcDDxOCb2uZXZoErbYf0w== | https://www.mywebsite.com | True | True | False | 94.109.0.0 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0 |  be`  

(inspired by what Cookiebot.com does)

**Comment by intoeetive** [comment]
@pixiwooh appears we already have issues for this https://github.com/ExpressionEngine/ExpressionEngine/issues/271 so I'll close this one as duplicate.

If you're willing to provide more details, please do it in the other thread (in particular, if you have anything to say on Derek's statement that logged out visitors do not have Personally Identifiable Information and so logging consents for those is not necessary)
