### ISSUE TITLE
Reloading CP page after session timed out throws PHP warning about undefined constant BASE

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#456]
**Description of the problem**
If you reload a page that was accessing a control panel page (e.g. with URL such as `https://domain.com/admin.php?/cp/fields&group_id=5`) a PHP warning is reported relating to an undefined contant (BASE) - vis:

> Warning
> Use of undefined constant BASE - assumed 'BASE' (this will throw an Error in a future version of PHP)
> 
> ee/legacy/core/URI.php, line 333
> 
>     Severity: E_WARNING

**How To Reproduce**
This can happen for example when returning to a page in a browser that was connected / logged in to an EE site CP and then was left for session to time out / expire.  The error appears on first refresh by browser, and then disappears when on next refresh the browser is directed to the CP log in screen.

**Error Messages**
> Warning
> Use of undefined constant BASE - assumed 'BASE' (this will throw an Error in a future version of PHP)
> 
> ee/legacy/core/URI.php, line 333
> 
>     Severity: E_WARNING

**Screenshots / Videos / Template Code**
![image](https://user-images.githubusercontent.com/13821249/86355976-6a559800-bc63-11ea-8e7a-dbbf489ac684.png)

**Environment Details:**
 - Version: 5.3.2
 - PHP Version 7.2.31
 - MySQL Version 5.7.30
 - OS: macOS 10.14.6
 - Web Server: Litespeed 7.6

**Possible Solution**
It appears that BASE is defined in /legacy/Core.php via private function `somebody_set_us_up_the_base()` and conjecture is that in refresh this library is not called, and so BASE is not set: the error links to a function `reformat` in legacy/URI.php.  A solution would be to trap for BASE not being set in the `reformat` function and if it is not set, trigger the setting of BASE to a value at that point.  The most direct way to do this would be to recast `somebody_set_us_up_the_base()` as a public function so that it could be accessed directly by the URI.php `reformat` function.

**Additional context**

**Comment by intoeetive** [comment]
We are planning to address this in the next EE6 beta release

**Comment by robinsowell** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
