### ISSUE TITLE
Keyboard navigation disappeared in Tag field

### ISSUE THREAD

**Issue by jelle-burodeng** [ExpressionEngine/ExpressionEngine#4567]
In the Tag addon previously you could select an item in the autocomplete list of the Tag field with the keyboard. However, not anymore, and users are forced to use a mouse
![image](https://github.com/user-attachments/assets/c2d736af-77e7-42f6-a108-8d9318cbd821)
Tag 7.2.3
EE 7.4.11

**Comment by bakin1999** [comment]
Thanks for letting us know about this.  I have just now released Tag version 7.2.4 which adds back in the ability to select the items from the keyboard. Updating to tags version 7.2.4 will fix this for you.

Just for future reference, you can report bugs/ask questions for EEHarbor add-ons to the help@eeharbor.com email

The issues page here is for ExpressionEngine core.

Thank you.
