### ISSUE TITLE
Entry cloning feature moves entry revisions to the new cloned entry

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#4583]
Entry cloning feature moves all the entry revisions to the new entry, leaving the original one without edit history.

EE 7.4.11

**Comment by TomJaeger** [comment]
@shbchk Any chance you would be willing to test this fix? 
https://github.com/ExpressionEngine/ExpressionEngine/pull/4592/files

**Comment by TomJaeger** [comment]
Fix for this was pushed live in 7.5.4 today.

**Comment by shbchk** [comment]
Thank you so much! Sorry, I didn't have a chance to test it, you guys were really quick :)
