### ISSUE TITLE
Removing a field from a fluid field group deletes the content if that same field is used in another field group assign to the the same fluid field

### ISSUE THREAD

**Issue by JimStrive** [ExpressionEngine/ExpressionEngine#4589]
Removing a 'Custom Field' from a fluid field deletes the content if that same field is used in another 'Custom field groups' assigned to the the same fluid field.

**Comment by TomJaeger** [comment]
Thanks for reporting this... If you could pass along the following it would be greatly appreciated!

1. EE Version
2. Add-ons Installed
3. Field-type this happened with.
4. PHP Version

**Comment by robinsowell** [comment]
I definitely see a problem trying to replicate in 7.5.3.

I have a fluid field with a blog content field assigned and a blog group assigned.  The blog content field is also in the group.  I go make an entry in the channel with that fluid field.  Then, I go edit the fluid field and remove the blog content field from the fluid field.  I leave the blog group.  When I reload the entry page, now I get a php error:

<img width="1624" alt="Screenshot 2024-11-12 at 4 03 04 PM" src="https://github.com/user-attachments/assets/f31bfe98-ad07-4fc3-aef5-937841b0e239">

<img width="1324" alt="Screenshot 2024-11-12 at 4 07 46 PM" src="https://github.com/user-attachments/assets/16989e10-f397-4c81-a8d3-964e2fcf8db7">

**Comment by TomJaeger** [comment]
@JimStrive any chance you would be willing to test this fix?
https://github.com/ExpressionEngine/ExpressionEngine/pull/4591/files

**Comment by TomJaeger** [comment]
Fix for this was pushed live in 7.5.4 today.
