### ISSUE TITLE
Calendar tag duplicates entries in the next year

### ISSUE THREAD

**Issue by JimStrive** [ExpressionEngine/ExpressionEngine#4590]
Calendar tag duplicates entries in the next year

**Comment by TomJaeger** [comment]
What version of ExpressionEngine is this in?

**Comment by robinsowell** [comment]
And can you give us a simplified version of the tag to test with?

**Comment by robinsowell** [comment]
Hrm- and with the default calendar, I'm definitely seeing some weird results.

Looks like this query:

```SELECT t.entry_id , exp_channels.channel_id FROM exp_channel_titles AS t LEFT JOIN exp_channels ON t.channel_id = exp_channels.channel_id WHERE t.entry_id != '' AND t.site_id IN ('1') AND t.entry_date <= 1731537148 AND (t.expiration_date = 0 OR t.expiration_date > 1731537148) AND t.channel_id IN (2) AND t.status = 'open' ORDER BY t.sticky desc, t.entry_date desc, t.entry_id desc LIMIT 0, 100

```
Note the entry date should have a beginning and end.

#system/ee/ExpressionEngine/Addons/channel/mod.channel_calendar.php L:342 Channel::build_sql_query() 

Digging into it.
