### ISSUE TITLE
Symbols in field names are rendered as HTML entities 

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#4599]
Symbols in field names are transformed into HTML entities (e.g., apostrophes become `&rsquo;`)

Field listing:
![Screenshot 2024-11-15 113934](https://github.com/user-attachments/assets/0946ac4e-4a60-4497-8235-66a460d5d48f)

Field settings:
![Screenshot 2024-11-15 113919](https://github.com/user-attachments/assets/827d4a7f-7fb7-4ae7-bfe6-b789a85c5888)

EE 7.5.3

**Comment by shbchk** [comment]
The same happens with image names:

![image](https://github.com/user-attachments/assets/f727a903-94bb-404d-9c7d-2192be64d191)

**Comment by benoitlemay** [comment]
Duplicate of issue https://github.com/ExpressionEngine/ExpressionEngine/issues/4408.
Any update on this?

**Comment by TomJaeger** [comment]
We have a fix in progress... We're just working to confirm we don't open the door for XSS

**Comment by matthewjohns0n** [comment]
This issue is scheduled to be fixed in 7.5.6.
