### ISSUE TITLE
Fallback for `:webp` modifier to prevent system crashes

### ISSUE THREAD

**Issue by intoeetive** [ExpressionEngine/ExpressionEngine#4617]
### Discussed in https://github.com/ExpressionEngine/ExpressionEngine/discussions/4572

<div type='discussions-op-text'>

<sup>Originally posted by **shbchk** November  5, 2024</sup>
### Suggest an idea for ExpressionEngine

In the development environment, when using the `:webp` modifier on images not present on the local server, the system throws the following exception:

```
Exception Caught
Cannot create a temp file from path: Mzk2L2VkaXRpb25zLzI0NjUvZmlsbXMvMTAyNTI3Ny9hY2Nlc3Nvcmllcy8xNTQwOTk2LnBuZw__.png
ee/ExpressionEngine/Library/Filesystem/Filesystem.php:1034
```

Please, add a fallback for cases where image files are missing on the server. Syncing all images locally is unrealistic and impractical for larger sites (currently >70GB for me). 

This would prevent dev crashes.</div>

**Comment by shbchk** [comment]
Thank you, Yuri!
