### ISSUE TITLE
sanitize_filename() can sometimes return empty strings, leading to other issues

### ISSUE THREAD

**Issue by mrw** [ExpressionEngine/ExpressionEngine#463]
**Description of the problem**

We use some add-ons that rely on EE's `sanitize_filename()` method. `sanitize_filename()` makes use of `preg_replace()` which returns `NULL` on errors, causing `sanitize_filename()` to eventually return/operate on an empty string.

**How To Reproduce**

You can see this by passing a string with an invalid character (e.g. `/some/uri/path/¬`) to the `sanitize_filename()` function. You'll get back an empty string.

**Environment Details:**

 - Version: 5.3.0
 - PHP Version 7.3.16
 - OS: Linux

**Additional context**

This impacted us because CE Cache static caching relies on it, and our homepage cache (empty string as the filename) was getting overwritten by a URL that somehow got an invalid string in it.

**Comment by intoeetive** [comment]
@mrw I think I need additional information on how to replicate this one. If I call `return ee()->security->sanitize_filename('/some/uri/path/¬');` in CP it returns `someuripath` which seems to be correct

**Comment by dougblackjr** [comment]
@intoeetive @mrw I have a [branch](https://github.com/dougblackjr/ExpressionEngine/tree/task/463-sanitize-filename) here that adds a test around filenames and this function. Test can be run at: `./vendor/bin/phpunit --filter SanitizeFilenameTest`

![Screenshot from 2021-04-12 13-14-53](https://user-images.githubusercontent.com/6020323/114434518-1a601600-9b91-11eb-85f8-f9752712a18b.png)

Currently this looks like it doesn't remove line breaks; am I correct in understanding that is the issue?
