### ISSUE TITLE
Expression Engine Logs me out and my work is lost

### ISSUE THREAD

**Issue by rouviere** [ExpressionEngine/ExpressionEngine#473]
**Description of the problem**
Each week I create an major entry for my blog at https://hobblecreek.us. These are lengthy entires with 12 to 15 photos for each entry. When I am most of the way through the entry Expression Engine will suddenly time out and the log in screen appears. Today when this happened, despite having saved the entry multiple times along the way, the entry was completely lost. This is a show-stopping problem and it has to be resolved.

**How To Reproduce**
1. Create > Entry
2. Type for two to three hours, adding photos along the way
3. Save regularly
4. Log in notice pops up

**Error Messages**

**Screenshots / Videos / Template Code**
![Screen Shot 2020-07-17 at 2 19 49 PM](https://user-images.githubusercontent.com/4437546/87828724-c7904280-c83a-11ea-9cb3-c2cfc01881c1.png)

**Environment Details:**
 - Version: 5.3.2
 - PHP Version 7.0.33
 - MySQL Version 5.0.12
 - OS: Mac
 - Web Server: Apache

**Possible Solution**
Make it so that EE won't time out.

**Additional context**
Control panel setting is set to cookies only.

This is a show-stopping problem. To spend so much time and then to have it time out while I am active in the control panel is frustrating beyond belief. This is a serious problem with Expression Engine.

**Comment by WITwebmaster** [comment]
Have a look at this thread
[https://github.com/ExpressionEngine/ExpressionEngine/issues/252]

**Comment by intoeetive** [comment]
@rouviere I see that you have already submitted simular report before: https://github.com/ExpressionEngine/ExpressionEngine/issues/218

I'm going to close this one, let's stick to communicating on the other one. Thanks!
