### ISSUE TITLE
Channel Form fields don't instantiate/display if they are assigned via a Field Group.

### ISSUE THREAD

**Issue by JasonBoothman** [ExpressionEngine/ExpressionEngine#475]
**Description of the problem**
I created a new 'Blog' field group, and assigned that field group to the 'Blog' channel. When working on the channel form, none of the custom fields will display. This seems to be specifically related to using field groups rather than assigned each field to a channel individually.

**How To Reproduce**
1. Create a channel field group.
2. Create a channel and assign the channel the created field group.
3. Create a channel form and try to display any of the custom fields. The code will not be parsed and the fields won't display.
4. Go back to the channel settings, de-select the field group, and assign each field to the channel individually (instead of the field group).
5. Go back to your pages and notice that your custom fields will now display in the channel form.

**Environment Details:**
 - Version: 5.3.2
 - PHP Version 7.3.9
 - MySQL Version 5.7.26
 - OS: macOS
 - Web Server: Apache via MAMP

**Comment by intoeetive** [comment]
@JasonBoothman I wasn't able to replicate this on EE 5.3.2
Can you make sure that your custom fields are indeed assigned to that fields group?
If so, can you think of any additional steps/conditions to replicate this issue?
