### ISSUE TITLE
Status changed on entry edit based on user permissions

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#477]
**Description of the problem**
Member group 'a' only has permission to post in 'Pending' status.  They post, superadmin checks it, switches status to 'open'.  Works fine.  But if the group 'a' edits, the status reverts to 'Pending'.  It shouldn't disallow an existing status based on the member's permissions.

**How To Reproduce**
See above

**Environment Details:**
 - Version: [e.g. 5.3.2]
 - PHP Version [e.g. 7.1]
 - MySQL Version [e.g. 5.7]
 - OS: [e.g. Linux, macOS, Windows]
 - Web Server: [e.g. Apache, nginx, MAMP, etc.]

**Comment by intoeetive** [comment]
@robinsowell I think this might be subject for discussion. I believe the idea behind this behaviour might be intentions - after member edits the entry, it's pending again and requires approval because the changes have been made

**Comment by intoeetive** [comment]
@TomJaeger need your input here

**Comment by intoeetive** [comment]
Same, or very similar issue, has been reported in https://github.com/ExpressionEngine/ExpressionEngine/issues/1877

Copying over my comment from there:

> In short, the situation might occur when member has permissions on the channel, but does not have permission to the status that the entry has. While this might be intentional, we probably need to show them a warning that the current status might be lost.
