### ISSUE TITLE
Spam stats on CP home page links to no results

### ISSUE THREAD

**Issue by nep** [ExpressionEngine/ExpressionEngine#48]
**Description of the problem**
On the CP homepage, it tells you how many comments are flagged as potential spam (see image).
When you click the link, it takes you to a page that doesn't list those spam entries.

**How To Reproduce**
1. Submit some comment spam
2. Look at the home page; take note of the number
3. See that the number doesn't match the results

**Error Messages**
No error messages.

**Screenshots / Videos / Template Code**
<img width="604" alt="screenshot 2018-12-13 16 19 42" src="https://user-images.githubusercontent.com/49483/49974067-e444f580-fef4-11e8-8789-29ba33f2a242.png">

<img width="932" alt="screenshot 2018-12-11 21 39 41" src="https://user-images.githubusercontent.com/49483/49974071-e6a74f80-fef4-11e8-96bf-9fb6abc17680.png">

**Environment Details:**
 - Version: 4.3.6
 - PHP Version  5.6.38
 - MySQL Version 
 - OS: 
 - Web Server: Apache

**Possible Solution**
None known

**Additional context**

**Comment by nep** [comment]
Yes, that's the URL it is linking to. 

I may have clicked "clear filters" before I took the screenshot to see if that helped. I have just doublechecked, and there's 0 spam without filters, and there's 0 spam with type=comment.

I believe that it might have to do with marking a comment as "spam" via the comment edit link, which offers Open, Closed, Pending and SPAM as statuses.  That appears to increment the number on the home page.

**Comment by derekjones** [comment]
Aha! Good catch! That's definitely a bug, it shouldn't be offering "SPAM" as a status there. Or, if it does, it needs to properly insert it into the spam queue. Thanks for digging @nep!

**Comment by intoeetive** [comment]
This is still an issue in EE6

**Comment by ops-andy** [comment]
This seems to have been resolved. 
tested on 6.0.3
![image](https://user-images.githubusercontent.com/55093827/112326164-acf45000-8c8a-11eb-94c4-f94f016c1835.png)
