### ISSUE TITLE
allow_extensions config override causes extensions to disappear from Add-ons

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#480]
**Description of the problem**
If an add-on is only an extension and the config override is used to disable extensions:

`$config['allow_extensions'] = 'n';`

Then on the Add-on page, the add-on simply doesn't show up at all.  Also, on the Utilities- Debug Extensions page, the list of Extensions is simply blank, which I find confusing.  Listed and some way to convey they're disabled via config would be nice.

Note- this does not happen if an extension is disabled via the database/debug extensions page.  Only if it's done by the config override and only if it's only an extension.

**How To Reproduce**
1. Put an extension folder in system/user/addons.  You don't need to install it.  It should show on the 'Add-ons' page.
2. Add the config override: `$config['allow_extensions'] = 'n';`
3. The add-on won't show in the list of Add-ons.

**Environment Details:**
 - Version: [e.g. 5.3.2]
 - PHP Version [e.g. 7.1]

**Comment by intoeetive** [comment]
We can't really show the information when extensions are disabled - the whole purpose of this config override is to prevent any extension code to execute.
But I have added warning to appears on Addons and Debug Extensions pages that would show when extensions are disabled

**Comment by robinsowell** [comment]
Makes sense- and as long as there's a note it should prevent the time suck that can happen otherwise!  Thanks!
