### ISSUE TITLE
Feature Request - Disable ability to edit templates globally or for specific users

### ISSUE THREAD

**Issue by inconsiderate** [ExpressionEngine/ExpressionEngine#481]
**Is your feature request related to a problem? Please describe.**
When our workflow involves committing code to a Git repository, clients may occasionally make their own small edits to templates without telling anyone. If we later update that same template and deploy through our workflow, we overwrite those small edits. This is annoying.

**Describe the solution you'd like**
I would like a way to disallow users from editing templates.
Proposal 1: `/cp/settings/template` A global toggle on the Template Settings page which turns off template editing for all users. 
Proposal 2: `/cp/members/groups/edit/5` A new section on the Member Group page which turns off template editing for specific user groups.

**Implementation**
If editing is disallowed, simply removing the Templates button from the CP seems like the simplest solution.

- [X] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
@inconsiderate I believe you can achieve the same by moving your users to dedicated group and have "Access template manager" unchecked in that group's settings

**Comment by inconsiderate** [comment]
That is true, but I would prefer a CP or config option that disabled template editing for everyone, including superadmins. It's not possible to change member group settings for superadmins.

**Comment by intoeetive** [comment]
I don't think we can afford disabling template editor for superadmins, as the template settings are only accessible through CP interface
