### ISSUE TITLE
Template partials and template variables should be included in EE CP template search

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#482]
**Is your feature request related to a problem? Please describe.**
When searching templates in the EE (5.3.2) control panel, template partials and template variables are not included in search results. There's no obvious reason why this should be the case: a user is just as likely to be interested in search hits from template partials and template variables as from regular templates.

**Describe the solution you'd like**
Content of template partials and template variables should be searched and listed in search results — perhaps with separate headings, for clarity.

**Comment by intoeetive** [comment]
@PaulBaileyAtChan while this is the case indeed for template search, template partials and vaiables also have their own search box, which is located in filters bar (next to "show 25" dropdown)

**Comment by PaulBaileyAtChan** [comment]
My bad, yes, I'd somehow looked past this. I'd probably go for a unified search in a perfect world, but what's already there definitely captures most of the functionality. Will close.
