### ISSUE TITLE
Channel layouts - can not edit or add a layout

### ISSUE THREAD

**Issue by paulcripps** [ExpressionEngine/ExpressionEngine#483]
**Description of the problem**

ExpressionEngine® CMS 5.3.2, years ago it was updated from 2.11 > 4, we are now running 5.3.2.

I've tried turning off extensions etc no joy.

When we navigate to Channels > Edit, then choose layouts, we can see layouts exist (from EE 2 days). Clicking to edit give us a partial screen with no CSS. 

This is the same for all channels and if we delete all layouts and try adding a new one.

Checking the screen in chrome, there's no dev errors in the console.

No errors in the error logs.

Screenshots show the problem.

**How To Reproduce**

1. Head to channel settings
2. Click layouts
3. Edit layout OR
4. Add layout
5. See screenshots for end results

**Error Messages**

None, see screensshots.

</code></pre>

**Screenshots / Videos / Template Code**

https://www.dropbox.com/s/tgqu2ju3n3mocxc/Screenshot%202020-07-29%2015.43.45.png?dl=0
<img width="587" alt="Screenshot 2020-07-29 15 43 45" src="https://user-images.githubusercontent.com/1560544/88929094-90298900-d271-11ea-8f8a-9ec0d2ea32f2.png">

<img width="1228" alt="Screenshot 2020-07-29 15 43 28" src="https://user-images.githubusercontent.com/1560544/88929098-91f34c80-d271-11ea-8ad5-99984c2a2b9b.png">

**Environment Details:**
 - Version: 5.3.2
 - PHP Version PHP Version 7.0.33
 - MySQL Version mysqlnd 5.6.47
 - OS: macOS
 - Web Server: Apache (MAMP locally)

**Possible Solution**

**Additional context**

**Comment by paulcripps** [comment]
Any thoughts? Anyone?

**Comment by intoeetive** [comment]
@paulcripps if you go to Network tab in browser developer console, are there any requests that have 404 or 500 http code?

**Comment by paulcripps** [comment]
This is now resolved, it was a legacy addon, didn't show up in the CP addon list, but the files were still on the server.

We removed it and that resolved it. Also upgraded matrix and removed a further old safecracker folder.
