### ISSUE TITLE
Beefed up warning when deleting a fieldtype that has entry data

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#484]
**Is your feature request related to a problem? Please describe.**
If you uninstall an add-on that has a fieldtype, or delete a fieldtype, the modal does pop up to require confirmation before deleting.  However, it doesn't warn you that you're going to lose entry data when the field(s) have content in it, and once the data is gone, it's gone.

**Describe the solution you'd like**
Add additional  information to the confirmation modal if entry data will be lost.

- [ ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
I think we could pull in the extra toggle, same way that we do for the files that are assigned to entries in EE7
