### ISSUE TITLE
Ability to specify allowed File types on the File field.

### ISSUE THREAD

**Issue by CreativePoweredGeek** [ExpressionEngine/ExpressionEngine#485]
**Is your feature request related to a problem? Please describe.**
I frequently have cases where I want to allow only certain file types to be uploaded through a file field in a publish or front-end channel form. My use cases are generally on the front end, but a solution that allows the limitation in the publish form in the Control Panel as well would be ideal. 

**Describe the solution you'd like**
When setting up a file field, I'd like to see the ability to specify the allowed file types (.jpg, .png, .pdf, etc) in the field set-up.

**Describe alternatives you've considered**
~ As a workaround, A javascript solution on the front end to accomplish this, but it does nothing to prevent an incorrect filetype from being uploaded in the Control panel.  
~ I have thought about this within the context of limiting the File upload directory instead, but I can see cases where one might want to allow any file type in a particular directory, but not in one of the file fields that feeds it.  
~ I wondered if BOTH might be good, but it seems to me that placing this ability in both locations could increase the opportunity for error and conflict to arise that might be difficult for a user to identify if they configured a directory & File field  with values in opposition to each other.

**Teachability, Documentation, Adoption, Migration Strategy**
To restrict a field to upload only certain filetypes, under the "Restrict to filetype" heading, check the boxes next to each filetype you would like to allow for this field. If left unchecked, the default is "all" (this could also possibly be a pipe delimited list of desired extensions) 

- [ X ] I am capable and would like to work on implementation of this feature if it is considered.  POSSIBLY

**Comment by robsonsobral** [comment]
Let's put some work on this? Could we have a visual guide for it?

**Comment by intoeetive** [comment]
We plan to put some effort to improve the file management in EE as a whole in the nearest time. This request will definitely be considered

**Comment by intoeetive** [comment]
In ExpressionEngine 7 is it possible to select allowed file types for each Upload Directory, as well as define custom file types.

I believe this is covering this need, so closing

**Comment by robsonsobral** [comment]
Does eecms7 allow filter files by extension?

**Comment by intoeetive** [comment]
EE7 supports filtering by File Type: https://docs.expressionengine.com/latest/control-panel/file-manager/upload-directories.html#allowed-file-types

There are several types built in, and you can also create custom types: https://docs.expressionengine.com/latest/config/config-files.html#allowed-mime-types
