### ISSUE TITLE
before_channel_entry_delete hook custom field data is empty

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#487]
**Description of the problem**
[Per the docs: ](https://docs.expressionengine.com/latest/development/extension-hooks/model/channel-entry.html#before_channel_entry_deleteentry-values)

<img width="930" alt="Screen Shot 2020-07-31 at 12 17 15 PM" src="https://user-images.githubusercontent.com/1181219/89055057-caedf880-d327-11ea-8b3b-a15c74e2da3e.png">

So it should be giving us the values of the fields in the entries to be deleted.

But- custom field values are empty.  As [discussed in the forum thread](https://expressionengine.com/forums/topic/252778/get-custom-field-entry-data-on-before_channel_entry_delete-hook), it looks like that data is wiped before it gets to the hook.  See 107 in file /system/ee/EllisLab/ExpressionEngine/Model/Content/ContentModel.php $this->deleteFieldData(); 

**How To Reproduce**

[text_ext 2.zip](https://github.com/ExpressionEngine/ExpressionEngine/files/5007977/text_ext.2.zip)

Attached is a starter extension for testing- basically dump out the params and see the lack of custom field data.

**Environment Details:**
 - Version: [5.3.2]
 - PHP Version [e.g. 7.1]

**Comment by albertopriore** [comment]
Does anyone have updates on this issue?

**Comment by intoeetive** [comment]
I have submitted pull request #512  that possibly fixes this. Honestly I don't quite like it because it's sort of hacky, but it solves the problem

**Comment by intoeetive** [comment]
The fix has been merged and released
