### ISSUE TITLE
Add a 'none' type option to the sticky parameter

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#488]
**Is your feature request related to a problem? Please describe.**
The [sticky parameter](https://docs.expressionengine.com/latest/channels/entries.html#sticky) has three valid options: no (don't sort stickies first) yes (default- do sort stickies first) and only (only include stickies in the results).  I'd like the opposite of 'only' - something like 'none' - omit all stickies.

Say you already displayed your stickied in a featured section up top and now you want to display the rest.  You can't easily eliminate the sticky entries.

**Comment by intoeetive** [comment]
Totally makes sense - I've seen few cases where this was needed
