### ISSUE TITLE
Channel::process_subcategories() running infinitely recursive

### ISSUE THREAD

**Issue by amphibian** [ExpressionEngine/ExpressionEngine#49]
**Description of the problem**
In some circumstances which I cannot exactly reproduce, `Channel::process_subcategories()` will run in an infinite loop when calling a `channel:entries` loop in a template, exhausting memory and killing the application.

**How To Reproduce**
Honestly not sure! It happens with some channel/entries, but not others.

**Error Messages**
<pre><code>
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /storage/avXXXXX/www/expressionengine/ee/EllisLab/Addons/channel/mod.channel.php on line 3509
</code></pre>

**Environment Details:**
 - Version: 5.0.2
 - PHP Version: 7.2.10
 - MySQL Version: 5.0.12
 - OS: Linux
 - Web Server: Apache

**Possible Solution**
Double-check that `$parent_id` is not in fact `0` before recursively running the method inside of `Channel::process_subcategories()`. This fixed the issue for me.

e.g. `Channel::process_subcategories()` at line 3506

```
if ($parent_id == $val[1] && $parent_id != 0)
{
    $this->cat_array[] = $val;
    $this->process_subcategories($key);
}

**Comment by kevincupp** [comment]
We don't really want to blindly add code to mask a problem that isn't understood. Looking at the code, I'm not sure how `$parent_id` would ever be `0`, unless you had a category with an ID of `0`. Could you check and see if you have that?

**Comment by amphibian** [comment]
I hear you. I did check for that, but alas I do not. No categories with IDs of `0`, and no entries in `category_posts` with `0` in the `cat_id` column. I also have no categories which have children (all `parent_id` columns are `0`).

**Comment by kevincupp** [comment]
Hmm, I imagine this would be a more common problem then, so there must still be something strange with your install. Do you have a support plan with us that you could give us access to this install?

**Comment by amphibian** [comment]
I'll do that Kevin.

**Comment by amphibian** [comment]
I did not, but things got in the way. Feel free to close this and if/when this pops up again on this install I'll file a support request and see if we can tackle it that way.

**Comment by kevincupp** [comment]
Ok sounds good 👍

**Comment by studiopatagon** [comment]
This issue is happening to me on an upgraded site, version 5.3.0. amphibian's fix does work!
