### ISSUE TITLE
Channel Form - Category Selection

### ISSUE THREAD

**Issue by nickpuglisi** [ExpressionEngine/ExpressionEngine#494]
**Description of the problem**
When using Channel Form, and selecting the Category Selection, using the tags specified in https://docs.expressionengine.com/latest/channels/channel-form/categories.html outputs an php error

**How To Reproduce**

1. 1. Create a Channel Form on frontend.
2. Add the Category Selection and save.
3. Template immediately errors out.

**Error Messages**

<pre><code>
{category_menu}
  <label for="categories">Categories</label>
  <select name="category[]" id="categories" size="4" multiple="multiple">
    {select_options}
  </select>
{/category_menu}

results in: 
Warning
Invalid argument supplied for foreach()
ee/EllisLab/Addons/channel/libraries/channel_form/Channel_form_lib.php, line 2214
Severity: E_WARNING
Warning
Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120)
ee/EllisLab/ExpressionEngine/Boot/boot.common.php, line 489
Severity: E_WARNING
</code></pre>

**Environment Details:**
 - Version: 5.3.2
 - PHP Version: 7.2
 - MySQL Version: 
 - OS: macOS
 - Web Server: Apache

**Comment by intoeetive** [comment]
@nickpuglisi I wasn't able to replicate this. Do categories/groups already exist in your system and are those assigned to your channel?

**Comment by intoeetive** [comment]
Closing this since we have not received any further information.

If anyone still has this issue with EE6, please reopen with more details.
