### ISSUE TITLE
Mount File Directories in Amazon S3

### ISSUE THREAD

**Issue by dgowing95** [ExpressionEngine/ExpressionEngine#495]
**Is your feature request related to a problem? Please describe.**

Currently File Directories have to be mapped to a local file path, meaning all file directory assets must exist on the same server as the expression engine installation. This makes it difficult to configure Expression Engine in a 'stateless' way that can be autoscaled.

**Describe the solution you'd like**

File Directories in the control panel should be mappable to AWS S3 buckets, EFS, or alternatives from Azure or Google Cloud.

**Describe alternatives you've considered**

There are addons that add this functionality, but have quirks in that they use custom file fields, and rely on external support. 

**Teachability, Documentation, Adoption, Migration Strategy**

- [x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment]
We have implemented this using [Cloud Files first-party add-on](https://expressionengine.com/add-ons/cloud-files)
