### ISSUE TITLE
File permissions issue on 5.0.0. Not reproducible on 4.3.6

### ISSUE THREAD

**Issue by bobural** [ExpressionEngine/ExpressionEngine#5]
Downloaded the new EE 5.0 and tried to install. I get the following error when accessing: https://my-website.com/admin.php 
"Your config file does not appear to be formatted correctly."

This does not happen with 4.3.6

And I've check file-system permissions... looks OK.

**Comment by WinkingFrog** [comment]
I've managed to reproduce this on both local, and live server installations. In fact I haven't managed to run the installer at all for a fresh v5.0.0 install. Upgrades from 4.x are working fine.

@ExpressionEngine/Maintainers this one probably deserves a look.

**Comment by kevincupp** [comment]
Yes, there is an issue with admin.php. You should be able to install by going to `/system` instead.

**Comment by WinkingFrog** [comment]
Yup, that works. Also forcing EE_INSTALL_MODE to TRUE allows the install to start, as mentioned in the readme for repo obtained installs.

**Comment by WinkingFrog** [comment]
It appears release 5.0.1 resolves this issue.

**Comment by kevincupp** [comment]
Yes, fixed via 8b828267db1bcd224f29841a5acfb0c924976738
