### ISSUE TITLE
Relationship Field tag should support "Disable" parameter

### ISSUE THREAD

**Issue by nep** [ExpressionEngine/ExpressionEngine#50]
The relationship field tag currently does not support the "disable" parameter:
https://docs.expressionengine.com/latest/fieldtypes/relationships.html#parameters

**Describe the solution you'd like**
I think it should. Relationships are often a place where additional queries are unnecessary -- you often don't need categories, pagination, etc.

**Describe alternatives you've considered**
None.

**Teachability, Documentation, Adoption, Migration Strategy**
Would be almost no additional UI or documentation needed.  There's no backwards incompatibility issues, and no problem with including the attribute by accident on older versions.

**Comment by intoeetive** [comment]
This has been added in ExpressionEngine 7: https://docs.expressionengine.com/latest/fieldtypes/relationships.html#optimizing-relationships-performance
