### ISSUE TITLE
Toggle field conditionals on frontend don't handle defaults correctly

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#510]
**Description of the problem**
Frontend conditionals don't correctly handle default values for entries that have not been saved with the field.

**How To Reproduce**

Per the cp instructions when creating a toggle field:

Default value
The default position of the toggle switch for this field when publishing new entries.
Note: If assigned to a channel with existing entries, those entries will be assigned this value.

So existing entries should all act as if they were assigned the default value.  

Make a new toggle field, set the default to 'on' and assign the field to a channel.  Go to edit an existing entry - the toggle field correctly displays as 'on'.  

Go make a template:

```{exp:channel:entries channel="blog" limit="4"}
<h3>{title}</h3>
{if ! show_me} I am hidden!{/if}
{/exp:channel:entries}
```
All existing entries show the 'I am hidden' text.  New entries set to 'on' work (nothing shows up) and new entries set to 'off' show the hidden message.  But it's incorrectly defaulting for entries that have not been explicitly set to off.

**Environment Details:**
 - Version: [e.g. 5.3.2]

**Comment by stinhambo** [comment]
This happens in EE 6.0.0 too. To set the toggle to off, I have to toggle on then off again.

**Comment by intoeetive** [comment]
When you add a field, there is this note:

> Note: If assigned to a channel with existing entries, those entries will be assigned this value.

which is definitely not true - it does not create new rows in `exp_channel_data_field_X` table. It **does** create those when you run search reindex, so I think we should just put a warning about "search reindex needed" after you add a field (since this can be memory consuming process that we run with AJAX)
