### ISSUE TITLE
increase the number of fields listed on field manager page in the CP

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#514]
The default of 10 items in a list often isn't sufficient; scrolling through a longer list is more efficient (and more useful, since I can look at and compare more items at a time) than paging through them.

A setting to customize this value would be great.

**Comment by bsrweb** [comment]
+1 to thsi feature request!

**Comment by CreativePoweredGeek** [comment]
+1 as well

**Comment by intoeetive** [comment]
what list is being referred here? The entries list is defaulting to 25 entries in EE 5.3, and I think it's same also for files and members

**Comment by murtaugh** [comment]
I'm looking at a new 5.3.2 install and the default is 10 for fields.

**Comment by murtaugh** [comment]
For both All Fields and fields within a group.

**Comment by intoeetive** [comment]
Ok, so it's about `Field Manager` page. Thank you

**Comment by intoeetive** [comment]
In EE6 and 7 the default is 25 in all paces where Perpage filter is being used; so we should consider this done
