### ISSUE TITLE
when you Save & Close a field in a group, bring me back to that field group

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#517]
The vast majority of the time, I am working on fields in groups. When I finish working on a field in a group, more often than not I want to return to the list of fields in that group, not the list of all fields (which, since it has no group labels, means I have to re-click into the group I'm working in).

It would also be useful to add group labels to the full list of fields, but not an ideal alternative solution to this issue because I usually have a lot of fields and groups.

**Comment by intoeetive** [comment]
Since the same request has already been submitted before https://github.com/ExpressionEngine/ExpressionEngine/issues/258 I'll have to close thise one as duplicate.

If you have further ideas on that front, please update that other thread.
