### ISSUE TITLE
Relationship fields have 'Include in search' option that doesn't do anything

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#518]
**Description of the problem**

<img width="408" alt="Screen Shot 2020-09-14 at 11 29 26 AM" src="https://user-images.githubusercontent.com/1181219/93105890-963ac400-f67d-11ea-8e47-5834716c7cda.png">

The search option doesn't seem to do anything.  It either needs to be removed or the related data needs to pull up the entry when searched.

**How To Reproduce**

**Environment Details:**
 - Version: [e.g. 5.3.2]

**Comment by gabbathehutt** [comment]
Yes, this is really frustrating.

**Comment by intoeetive** [comment]
We could hide the setting with JS, same as we do in https://github.com/ExpressionEngine/ExpressionEngine/pull/1984

**Comment by intoeetive** [comment]
The docs state Relationship field cannot be searched.

So makes absolute sense to just hide the setting
