### ISSUE TITLE
5.01: New Page entry doesn't show in Pages Manager

### ISSUE THREAD

**Issue by stinhambo** [ExpressionEngine/ExpressionEngine#52]
**Description of the problem**
If I create a new page, it doesn't show in the Pages Manager.

**How To Reproduce**
1. Go to Pages Manager page
2. Create new Page entry
3. Enter entry details
4. Save & Close
5. Nothing shows!

**Screenshots / Videos / Template Code**
https://share.vidyard.com/watch/KgYhAkLBegK16KLubJQCLh?

**Environment Details:**
 - Version: 5.01
 - PHP Version: 7.2.10
 - MySQL Version: 5.7.23
 - OS: MacOS
 - Web Server: MAMP (localhost:8888)

**Additional context**

**Comment by stinhambo** [comment]
Update: Page doesn't appear in Pages Manager if no template is assigned but no error shows to highlight this requirement.

**Comment by stinhambo** [comment]
Also updated to 5.02 and same issue applies.

**Comment by kevincupp** [comment]
You can select a default template for channels in the Pages settings.

**Comment by stinhambo** [comment]
Yes but that's not obvious and nothing stops you from submitting an entry if no template is chosen.

**Comment by kevincupp** [comment]
Yes, Pages are just regular entries and you should be able to submit entries without a template if you wish.
