### ISSUE TITLE
Fatal error: Uncaught Error: __clone method called on non-object in system\ee\legacy\libraries\Table.php:997

### ISSUE THREAD

**Issue by iHassan** [ExpressionEngine/ExpressionEngine#523]
**Description of the problem**
I'm trying to create pagination using Table library on a module. The table is showing fine if there is no pagination but when there is pagination then I'm getting the error.

I've used this method to set base url for pagination in my mcp class:
[https://docs.expressionengine.com/latest/development/legacy/libraries/table.html#set_base_urlurl](https://docs.expressionengine.com/latest/development/legacy/libraries/table.html#set_base_urlurl)

`ee()->table->set_base_url('C=addons_modules&M=show_module_cp&module=audit_pro');`

If I dump base_url variable in libraries\Table.php class, I can see that variable is setting properly and returning string.

**How To Reproduce**
Well you can recreate the issue by trying to create a table using `ee()->table->datasource('_datasource');` I guess? I'm not sure how I put this in reproducable steps.

**Error Messages**
**Fatal error:** Uncaught Error: __clone method called on non-object in G:\laragon\www\hbl-ee\system\ee\legacy\libraries\Table.php:997 Stack trace: #0 G:\laragon\www\hbl-ee\system\ee\legacy\libraries\Table.php(187): EE_Table->_create_pagination(Array) #1 G:\laragon\www\hbl-ee\system\user\addons\audit_pro\mcp.audit_pro.php(54): EE_Table->datasource('_datasource') #2 [internal function]: Audit_pro_mcp->index() #3 G:\laragon\www\hbl-ee\system\ee\EllisLab\ExpressionEngine\Controller\Addons\Addons.php(1662): call_user_func_array(Array, Array) #4 G:\laragon\www\hbl-ee\system\ee\EllisLab\ExpressionEngine\Controller\Addons\Addons.php(946): EllisLab\ExpressionEngine\Controller\Addons\Addons->getModuleSettings('audit_pro', 'index', Array) #5 [internal function]: EllisLab\ExpressionEngine\Controller\Addons\Addons->settings('audit_pro') #6 G:\laragon\www\hbl-ee\system\ee\EllisLab\ExpressionEngine\Core\Core.php(241): call_user_func_array(Array, Array) #7 G:\laragon\www\hbl-ee\system\ee\EllisLab\ExpressionEngine\Core\Core.php(110): EllisLa in **G:\laragon\www\hbl-ee\system\ee\legacy\libraries\Table.php** on line **997**

**Screenshots / Videos / Template Code**
Let me know if you need to take a look ay my mcp class.

**Environment Details:**
 - Version: **5.3.2**
 - PHP Version **7.3.13** also tested on **7.2.11**
 - MySQL Version **5.7.24**
 - OS: Windows
 - Web Server: WAMP (laragon)

**Possible Solution**
Well I'm pretty sure it has something to do with this code because I don't understand why you are trying to clone a string here on line 997 as base url is actually a string

```
// "Fixing" the URLs
foreach ($links as &$section)
{
	foreach ($section as &$link)
	{
		if (empty($link)) continue;

		$url = clone $this->base_url;

		$offset = str_replace('/', '', $link['pagination_url']);
		if ( ! empty($offset))
		{
			$url->setQueryStringVariable('tbl_offset', $offset);
		}

		$link['pagination_url'] = $url->compile();
	}
}
```

**Additional context**
N/A

**Comment by intoeetive** [comment]
@iHassan can you try this and let us know if that works:
replace the line that says
`$url = clone $this->base_url;`
with this code
```
if (is_object($this->base_url)) {
  $url = clone $this->base_url;
} else {
  $url = ee('CP/URL', $this->base_url);
}
```

**Comment by iHassan** [comment]
@intoeetive Thanks for the response!

This fix seems to work. Now the script is not breaking. But I think there's another issue somewhere in this library (If it's not an issue from my end).

So the docs state that we will get table html and pagination html like this:

```
$data = ee()->table->datasource('_datasource'); //dump pasted below
echo $data['table_html'];
echo $data['pagination_html'];
```

But I'm unable to get pagination_html data from this. My total rows are 6 and pagination limit is set to 2.
I've searched **pagination_html** in whole project directory but I can't find where this variable is initialized?

here is the dump of **$data**:


```
array(3) {
  ["rows"]=>
  array(2) {
    [0]=>
    array(10) {
      ["site_id"]=>
      int(1)
      ["member_id"]=>
      int(1)
      ["username"]=>
      string(7) "wpadmin"
      ["group_name"]=>
      string(11) "Super Admin"
      ["item_type"]=>
      string(19) "Control Panel Login"
      ["item_id"]=>
      NULL
      ["item_title"]=>
      NULL
      ["ip_address"]=>
      string(9) "127.0.0.1"
      ["timestamp"]=>
      string(17) "17-9-2020 4:23 PM"
      ["user_agent"]=>
      string(115) "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
    }
[1]=>
    array(10) {
      ["site_id"]=>
      int(1)
      ["member_id"]=>
      int(1)
      ["username"]=>
      string(7) "wpadmin"
      ["group_name"]=>
      string(11) "Super Admin"
      ["item_type"]=>
      string(13) "Entry Updated"
      ["item_id"]=>
      NULL
      ["item_title"]=>
      string(10) "test title"
      ["ip_address"]=>
      string(9) "127.0.0.1"
      ["timestamp"]=>
      string(17) "17-9-2020 2:52 PM"
      ["user_agent"]=>
      string(115) "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
    }
  }
 ["pagination"]=>
  array(5) {
    ["first_page"]=>
    array(1) {
      [0]=>
      array(2) {
        ["pagination_url"]=>
        string(152) "admin.php?/cp/C=addons_modules&M=show_module_cp&module=audit_pro&tbl_offset=https%3Ahbl-ee.testadmin.php%3Fcpaddonssettingsaudit_pro%26amp%3Bper_page%3D"
        ["text"]=>
        string(14) "‹ First"
      }
    }
    ["previous_page"]=>
    array(1) {
      [0]=>
      array(0) {
      }
    }
    ["page"]=>
    array(3) {
      [0]=>
      array(3) {
        ["pagination_url"]=>
        string(152) "admin.php?/cp/C=addons_modules&M=show_module_cp&module=audit_pro&tbl_offset=https%3Ahbl-ee.testadmin.php%3Fcpaddonssettingsaudit_pro%26amp%3Bper_page%3D"
        ["pagination_page_number"]=>
        int(1)
        ["current_page"]=>
        bool(true)
      }
      [1]=>
      array(3) {
        ["pagination_url"]=>
        string(153) "admin.php?/cp/C=addons_modules&M=show_module_cp&module=audit_pro&tbl_offset=https%3Ahbl-ee.testadmin.php%3Fcpaddonssettingsaudit_pro%26amp%3Bper_page%3D2"
        ["pagination_page_number"]=>
        int(2)
        ["current_page"]=>
        bool(false)
      }
      [2]=>
      array(3) {
        ["pagination_url"]=>
        string(153) "admin.php?/cp/C=addons_modules&M=show_module_cp&module=audit_pro&tbl_offset=https%3Ahbl-ee.testadmin.php%3Fcpaddonssettingsaudit_pro%26amp%3Bper_page%3D4"
        ["pagination_page_number"]=>
        int(3)
        ["current_page"]=>
        bool(false)
      }
    }
    ["next_page"]=>
    array(1) {
      [0]=>
      array(2) {
        ["pagination_url"]=>
        string(153) "admin.php?/cp/C=addons_modules&M=show_module_cp&module=audit_pro&tbl_offset=https%3Ahbl-ee.testadmin.php%3Fcpaddonssettingsaudit_pro%26amp%3Bper_page%3D2"
        ["text"]=>
        string(4) ">"
      }
    }
    ["last_page"]=>
    array(1) {
      [0]=>
      array(2) {
        ["pagination_url"]=>
        string(153) "admin.php?/cp/C=addons_modules&M=show_module_cp&module=audit_pro&tbl_offset=https%3Ahbl-ee.testadmin.php%3Fcpaddonssettingsaudit_pro%26amp%3Bper_page%3D4"
        ["text"]=>
        string(13) "Last ›"
      }
    }
  }
["table_html"]=>
  string(7005) "
... **table data is returning sucessfully here**

}
```

Do I need to create my own pagination html from now on using pagination Array returned above? Or is there any way I can get the pagination html as well like i'm getting the table html in reponse.

**Comment by intoeetive** [comment]
Do you have specific reason to use `ee()->table`and not `ee('CP/Table')`? https://docs.expressionengine.com/latest/development/services/table.html

`ee()->table` is legacy and should not really be used for the new code (also, we can't fully support it for the same reason)

**Comment by iHassan** [comment]
@intoeetive TBH the only reason I'm using `ee()->table` and not `ee('CP/Table')` is because I can't find the documentation for pagination for if I use `ee('CP/Table')`. The CP\Table docs only mention setting up the data but not the pagination and I really need to implement pagination as I'll have a lot of records.

**Comment by intoeetive** [comment]
This is because you need to use separate `CP/Pagination` service for pagination https://docs.expressionengine.com/latest/development/services/pagination.html

I must admin the documentation is missing complex examples, but you can find a lot of those in EE itself in first-party Addons folder

**Comment by iHassan** [comment]
Also if it's worth anything, I'm trying to convert the famous Audit Pro addon to the new version as author has abandoned the addon after v2. I'll migrate the addon, I'm planning to add it to add-on store for free so others can take benefit from it.

**Comment by iHassan** [comment]
Oh, that's a great idea, I did looked at the `CP\Pagiantion` service.  I'll try to look at the first-party Addons examples and see if I can work something out.
