### ISSUE TITLE
Previous month link not clickable in Channel Form datepicker

### ISSUE THREAD

**Issue by DesignWorkshop** [ExpressionEngine/ExpressionEngine#53]
**Description of the problem**
When using a date field within a grid the calender don't work properly when adding / editing entries using channel forms. 

Using the abbreviated month names in the top left and right of the calendar window you can navigate forward through the months but not backwards.

**Environment Details:**
 - Version: [e.g. 5.0.2]
 - PHP Version [e.g. 7.2.10]
 - MySQL Version [e.g. 5.7]
 - OS: [macOS]
 - Web Server: [MAMP]

**Comment by kevincupp** [comment]
Thanks, @DesignWorkshop. The original issue title was misleading, so I've investigated the issue further and found the datepicker is working fine, it's just the previous month link that is having issues, as you eventually noted, so I've updated the title. I'm also providing some sample code to reproduce the issue, which was left out of the report:

```
{exp:channel:form channel="test_bug"}
    <input type="text" name="entry_date" value="{entry_date}" rel="date-picker" data-timestamp="{entry_timestamp}">
{/exp:channel:form}
```

It looks like a CSS issue, we'll have @jmathias take a look. If you need to fix this in a pinch, you can give a high z-index to the `.date-picker-prev` class.

@jmathias It looks like an element is covering up that link:

<img width="288" alt="screen shot 2018-12-19 at 4 44 28 pm" src="https://user-images.githubusercontent.com/93695/50250304-68442500-03ae-11e9-92f5-3e4ccdb4f380.png">

**Comment by jmathias** [comment]
Does this only occur in Channel Form, or in the CP too?

**Comment by kevincupp** [comment]
@jmathias Just Channel Form, interestingly, the styles and markup look the same in the CP, as far as I can tell.

**Comment by jmathias** [comment]
Interesting. I'll see what I can do to get a fix in.
