### ISSUE TITLE
Timestamp.php on line 28

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#534]
Strict Standards: DateTime::__construct(): We selected 'Europe/Berlin' for 'CEST/2.0/DST' instead in /htdocs/foobar/system/ee/EllisLab/ExpressionEngine/Service/Model/Column/ColumnObject/Timestamp.php on line 28

This warning appears multiple times on single-entry pages.  

EE version 5.3.2
PHP Version 7.2.33

**Comment by intoeetive** [comment]
@silenz88 can you provide full error sreen or message (with backtrace, if available)? I have a feeling that this is related to certain add-on, not CMS in its core - can you narrow this down to certain field / tag / functionality?

**Comment by silenz88** [comment]
When I use 
```
{exp:channel:entries channel="blog" limit="1"}		
		{title}<br>
{/exp:channel:entries}	
```
I get 15 times the message above, no matter how high I set the entry-limit.

**Comment by intoeetive** [comment]
@silenz88 so do I understand correctly that you get this error on front-end, not CP?
What fieldtypes are used in your `"blog"` channel?

**Comment by silenz88** [comment]
Yes, front-end.
That is the only template-code. 
Changing which fields are displayed makes no difference.

Fieldtypes in that channel are 1x textarea and 1x grid.

Same result for other channels with orther fields.

**Comment by intoeetive** [comment]
Do you still get the error if you temporary disable extensions?

**Comment by silenz88** [comment]
No difference with
`$config['allow_extensions'] = 'n';`
in config.php.

According to the template debugger, extensions are no longer called.

**Comment by intoeetive** [comment]
I'm totally puzzled. Is this upgrade or new installation? If this is an upgrade, what EE version did you upgrade from?

**Comment by silenz88** [comment]
This is an upgrade from EE 2.11.9.
Actually even an empty template set to 'static' produces the same result.
<img width="400" alt="dt" src="https://user-images.githubusercontent.com/6132998/98046224-1c77b900-1e2a-11eb-96a5-0ff847629850.png">

**Comment by intoeetive** [comment]
This is probably an issue with your PHP config.
Please make sure you have `date.timezone = 'Europe/Berlin'` set in your `php.ini`
On certain hostings it is also reqired to have `.user.ini` file with same content

**Comment by silenz88** [comment]
date/time support | enabled
timelib version | 2017.09
"Olson" Timezone Database Version | 2018.9
Timezone Database | internal
Default timezone | Europe/Berlin

**Comment by intoeetive** [comment]
Can you try resaving EE date & time settings (in particular, the timezone) under General Settings?
Also if you are testing logged in, resave your profile's date & time settings as well

**Comment by silenz88** [comment]
No effect.

I did some digging. The timestamps that throw the error are unique in the whole database.
And they are all from the column 'create_date' in 'exp_consent_request_versions'.

int(1603490841) 
int(1600854822) 
int(1600948811) 
int(1600952719) 
int(1603456487)

**Comment by intoeetive** [comment]
Under the hood, ExpressionEngine's `Timestamp` class is using PHP's built-in `DateTime` class.

This error appears to be related to server (not EE) date & time settings being incorrect. There is a discussion and a range of possible solutions [here on StackOverflow](https://stackoverflow.com/questions/16765158/date-it-is-not-safe-to-rely-on-the-systems-timezone-settings)

Closing it as external by nature
