### ISSUE TITLE
Matrix file fields hide attached files when a user lacking file upload directory permissions edits entry

### ISSUE THREAD

**Issue by tommymcgahee** [ExpressionEngine/ExpressionEngine#539]
**Description of the problem**
When a user edits an entry with matrix file fields and user lacks permission to access the file fields' corresponding file upload directories, the entry appears to conform to the user's group permission set and "hides" the uploaded files. The entry saves in this state and the files are removed from the site but NOT deleted. Visually this removes the uploaded file icon from the upload buttons inside the entry if the user re-edits the entry. 

Another user with proper permissions can use entry versioning to restore the current version, which restores the attachments inside the entry.

Note: This entry has multiple matrix fields with file fields and ALL of them are affected on entry save. 

**How To Reproduce**

1. Create an entry with a matrix field -> text field and a second matrix field -> file field. Turn on entry versioning and attach a PDF. Save. 
2. Allow test user's member group to edit channel but NOT the associated file upload directory.
3. Test user edits matrix text field content and saves entry. Re-open entry and attached PDF should now be gone. The first matrix field is probably unimportant but this is how our entry is configured and what our user was doing to create the behavior. 
4. Second user, with file upload directory permissions, restores current versioned entry and attached PDFs should now be back. 

**Error Messages**
None

**Screenshots / Videos / Template Code**
None

**Environment Details:**
 - Version: 5.3.2
 - PHP Version 7.3
 - MySQL Version 5.7
 - OS: macOS
 - Web Server: Apache

**Possible Solution**

**Additional context**

**Comment by intoeetive** [comment]
@tommymcgahee can you confirm this is issue with Matrix field and not EE's Grid field? If so, would you mind sending this to help@eeharbor.com instead? Thank you!
