### ISSUE TITLE
Pages add-on isn't an option in Menu Manager.

### ISSUE THREAD

**Issue by stinhambo** [ExpressionEngine/ExpressionEngine#54]
Under 'Create Menu Item', the only add-on that can be added as a menu item is 'Comment'.

Shouldn't 'Pages' also be available?

* Ideally, the Pages link should be automatically be added under the Developer drop down as it's a fundamental section of the site build procedure.

**Comment by derekjones** [comment]
Currently only add-ons that have a meaningful menu will show up there. Technically, they are add-ons that implement the necessary menu API hooks to provide a menu. For items that would not have a meaningful or contextual drop-down, you can just use the URL to that add-on's control panel as a single item menu.

That said, I agree that any installed add-ons that _have_ a control panel page should be easier to insert there than having to cut and paste the URL manually.
