### ISSUE TITLE
"Name your site" text visible when sidebar closed

### ISSUE THREAD

**Issue by joshconner** [ExpressionEngine/ExpressionEngine#542]
"Name your site" text is still visible and cut off only when sidebar is closed on a site that doesn't yet have a Name set in the General Settings. Issue isn't present once a site name is applied.

<img width="332" alt="Screen Shot 2020-10-14 at 2 50 16 PM" src="https://user-images.githubusercontent.com/479358/96032709-11ce9300-0e2d-11eb-96c3-42644e2034d8.png">

**Comment by Yulyaswan** [comment]
I am closing the issue as it is no longer relevant. 

<img width="512" alt="Screenshot 2023-01-13 at 11 43 44" src="https://user-images.githubusercontent.com/23382425/212301887-b4e37250-6040-4c65-b589-13c12525156a.png">
<img width="565" alt="Screenshot 2023-01-13 at 11 43 53" src="https://user-images.githubusercontent.com/23382425/212301889-b1716611-7093-420c-aeba-38e1aa05fe22.png">
