### ISSUE TITLE
Toggle broken in bloq element (may just be a bloqs issue?_

### ISSUE THREAD

**Issue by frshjb373** [ExpressionEngine/ExpressionEngine#543]
When you click toggle in bloq element nothing happens...looks like the styling needs to be addressed as well.
![Screen Shot 2020-10-14 at 12 18 16 PM](https://user-images.githubusercontent.com/7178139/96035210-8f87a400-0e17-11eb-9f4c-e461e763e0cf.png)

**Comment by litzinger** [comment]
This is a Bloqs issue, not an EE issue. I'll be reviewing all my add-ons in the coming days and issuing updates so they're EE 6 compatible.

**Comment by litzinger** [comment]
Just noting this is already fixed for the next Bloqs release.
