### ISSUE TITLE
After Save of Entry - "Date" tab becomes "date"

### ISSUE THREAD

**Issue by stephengalbraith** [ExpressionEngine/ExpressionEngine#544]
When an entry is in the 'saved' state (either right after creation or after saving an entry) the "Date" tab goes lowercase to "date".

<img width="1181" alt="Screen Shot 2020-10-14 at 3 20 28 PM" src="https://user-images.githubusercontent.com/45797159/96035371-f06fa600-0e30-11eb-9027-52d24f1726dc.png">

<img width="1169" alt="Screen Shot 2020-10-14 at 3 20 40 PM" src="https://user-images.githubusercontent.com/45797159/96035374-f1083c80-0e30-11eb-9e3d-cdc15591a3fc.png">

**Comment by robinsowell** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
