### ISSUE TITLE
[grid] Delete row button working only on icon click, not to button.

### ISSUE THREAD

**Issue by MaxLazar** [ExpressionEngine/ExpressionEngine#545]
To delete a row needs to click precisely on the trash icon. If you click on the button outside of it, is no action or error.

![image](https://user-images.githubusercontent.com/925802/96038007-8bb64a80-0e34-11eb-8abd-00d1da7d2950.png)

**Comment by robinsowell** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
