### ISSUE TITLE
[grid] The color field panel overflow issue in the row

### ISSUE THREAD

**Issue by MaxLazar** [ExpressionEngine/ExpressionEngine#546]
The color field panel overflow issue in the grid row. macOS, Chrome/FF

![image](https://user-images.githubusercontent.com/925802/96038365-04b5a200-0e35-11eb-929c-48ae98701646.png)

**Comment by robinsowell** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
