### ISSUE TITLE
"Deprecated" error messages on the Control panel's Overview page

### ISSUE THREAD

**Issue by pixiwooh** [ExpressionEngine/ExpressionEngine#550]
Just installed EE 6.0.0-b.1 on a PHP 7.3.22 environment.

Login in. Redirected to the Control panel's Overview page and got these error messages on top of the page (Overview page only).

`
Deprecated
idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

ee/legacy/libraries/Typography.php, line 2602

    Severity: E_DEPRECATED

Deprecated
idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

ee/legacy/libraries/Typography.php, line 2602

    Severity: E_DEPRECATED

`

Please, see screenshot below.

![Screenshot_2020-10-15 Overview ExpressionEngine](https://user-images.githubusercontent.com/50106386/96127733-c67fb780-0ef4-11eb-9f09-ff6a3de1d0e8.png)

**Comment by intoeetive** [comment]
@pixiwooh thanks for the report!

Can you confirm 2 things:
- your PHP version is also reported by EE (in Utilities -> PHP Info) is 7.3.22
- the line 2602 in `system\ee\legacy\libraries\Typography.php` is the line that says 
```$parts['host'] = idn_to_ascii($parts['host'], 0, defined('INTL_IDNA_VARIANT_UTS46') ? INTL_IDNA_VARIANT_UTS46 : 0);```

**Comment by pixiwooh** [comment]
I confirm those 2 assertions Yuri.

**Comment by intoeetive** [comment]
@pixiwooh I had a look at this and it looks like rather there's an issue with your PHP version. It seems that your PHP build has been compiled with really old ICU library. In your phpinfo ICU version number should be greater than 4.6 - can you check that? (just to give you idea, in my installation of PHP 7.3.17 ICU version is 64.2)

**Comment by pixiwooh** [comment]
@intoeetive indeed the CIU version is 4.2.1 according to PHPinfo... weird, so it is a host matter? I'll reach out to host provider to ask.

**Comment by intoeetive** [comment]
Unless you have self-managed server, then you should talk to your hoster about that @pixiwooh

**Comment by pixiwooh** [comment]
I'm glad this is not a EE bug then ;) Thank you, I can't wait to use this new version on clients projects.
