### ISSUE TITLE
RTE doesn't work in Grid

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#551]
I'm testing out Bloqs in EE6, and the RTE field (the field formerly known as Wygwam) grid.js file is missing a lot of code compared to wygwam's grid.js file. It's missing the sorting, fluid, and clone destroy methods etc. I can only assume this is why it isn't working in a Grid field, and subsequently Bloqs.

**Comment by robinsowell** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
