### ISSUE TITLE
Grid row not added by default when setting 1 min for rows AND add row button hidden unless scrolled.

### ISSUE THREAD

**Issue by frshjb373** [ExpressionEngine/ExpressionEngine#553]
Grid field doesn't show a row even when specifying min/max 1 for field count. It must be added manually by clicking add new row. If several fields included in the grid, the "No rows created Add new row" is centered and may get pushed out of users view making it confusing to add new rows. The row should be there by default when 1 min/max is added to grid field, right?

![Screen Shot 2020-10-15 at 8 03 00 AM](https://user-images.githubusercontent.com/7178139/96148159-db405900-0ebc-11eb-8c98-1a03e519fb59.png)

**Comment by robinsowell** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
