### ISSUE TITLE
EE6 - Preview button shouldn't be always visible

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#557]
Preview button is visible even when preview has not been enabled for that channel.

Not all channels need a preview so it should only show when enabled.

**Comment by ops-andy** [comment]
![image](https://user-images.githubusercontent.com/55093827/96268009-82dd8a00-0f96-11eb-9103-f6e90351478d.png)
![image](https://user-images.githubusercontent.com/55093827/96268151-b3252880-0f96-11eb-9b79-b482bbc86a35.png)
