### ISSUE TITLE
EE6 - On the fly image tag pair?

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#558]
Using a tag pair to output an image complete with height/width/alt attributes, there's nothing mentioned in the docs about how to apply on the fly modifications.

For instance if I have my image tag pair how do I apply on the fly manipulations?

Example generic code:

```
{image}
	<img src="{url}" width="{width}" height="{height}" alt="{title}">
{/image}
```

**Comment by ops-andy** [comment]
This is already supported, we're going to update that in the docs and push that with the next beta release. We'll try and get some sample code here for you soon as well.

**Comment by blue-dreamer** [comment]
That's good to hear!
