### ISSUE TITLE
EE6 - Feature Request - Further options for native RTE

### ISSUE THREAD

**Issue by stephengalbraith** [ExpressionEngine/ExpressionEngine#559]
It would be nice to have more options for the native RTE, the ones I am specifically thinking of is the superscript and subscript formatting options.

**Comment by dankingsley** [comment]
Just to add a couple more specifics from me here too:
- would be helpful to have an edit source code button.
- when creating a link, it would be good to have options to be able to edit the target and select the type of link etc (email, url, Structure?!)

**Comment by litzinger** [comment]
Yeah, I noticed the link button was missing a lot of options that previous version of CKEditor had. We rely heavily on the hooks to add entries/pages to the link dropdown menu, populated by Structure. I like the minimal options, but the current link button is _too_ minimal :)

**Comment by avnerw** [comment]
A simple request for new RTE/CKEditor:

- Basic styling of paragraph tags, heading tags, and lists, blockquotes, etc. similar to what the native "Classic" theme of CKEditor 5 does.
- At the moment, at least from what I can see, there is no styled spacing between tags which can make editing difficult and visually not pleasing.

**Comment by robinsowell** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
