### ISSUE TITLE
RTE basic styles

### ISSUE THREAD

**Issue by avnerw** [ExpressionEngine/ExpressionEngine#562]
The new native RTE lacks basic styling for some tags, specifically related to spacing between tags, and some tags, like H1 has unconventional style applied. For example. If a number of paragraphs follow each other, there is no margin-bottom styling for the tag, so all paragraphs are visually not pleasing.

The same happens if a heading tag is followed by a paragraph, followed by a list style, followed by a blockquote, etc. This will make editing much harder. At least the minimum styling of the contents should be included like in the Classic theme of CKEditor 5.  See 3 screenshots below:

<img width="626" alt="Screenshot 2020-10-17 at 20 22 40" src="https://user-images.githubusercontent.com/17215743/96349237-fd9dc680-10b6-11eb-963e-27dac8c1c398.png">

Screenshot from CKEditor with Classic theme.
<img width="562" alt="Screenshot 2020-10-17 at 20 22 59" src="https://user-images.githubusercontent.com/17215743/96349231-f080d780-10b6-11eb-832e-1adb2f267842.png">

Also noticed that H1 tag is formatted like this:
<img width="451" alt="Screenshot 2020-10-17 at 20 27 15" src="https://user-images.githubusercontent.com/17215743/96349297-5a997c80-10b7-11eb-838d-9fcb8d49572b.png">

**Comment by robinsowell** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
