### ISSUE TITLE
EE6 - Relationship Multiple Selection toggle has no effect

### ISSUE THREAD

**Issue by skookie000** [ExpressionEngine/ExpressionEngine#563]
The "Allow multiple relationships?" toggle in the field setting for relationships has no effect and defaults to allow multiple relationships in the entry.

Steps to repeat:
- Create a relationship field, set to allow multiple relationships, save, verify in entry.
- Turn multiple relationships toggle off, save.
- Verify in entry that multiple entries can be added and saved.

EE6 beta 1.

**Comment by intoeetive** [comment]
Thank you for reporting this! The fix is planned for next beta release

**Comment by robinsowell** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
