### ISSUE TITLE
EE6 - Entry Modal Does not preserve dark mode

### ISSUE THREAD

**Issue by skookie000** [ExpressionEngine/ExpressionEngine#565]
Entry modal will appear in light mode even when dark mode is set.

Steps to reproduce:
- Put CP in dark mode.
- In edit list, select multiple entries to edit.
- Click edit dropdown, then submit.
- Get blinded by white.

This also works when adding a new entry via relationship modal.  I'm assuming all entry modals would have this issue.

EE 6 beta 1.

**Comment by intoeetive** [comment]
Thank you for reporting this! Fix will be provided in next EE6 beta release

**Comment by robinsowell** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
