### ISSUE TITLE
EE6 - Status is uppercase (cont.)

### ISSUE THREAD

**Issue by skookie000** [ExpressionEngine/ExpressionEngine#566]
Statuses are displayed as uppercase due to CSS, and not because they actually are.  Parts of the system works as case-sensitive, and getting the actual status casing means looking at the source or the database.  There's no functional value in having CSS make them all uppercase.

Statuses should be displayed as case-sensitive, exactly what's in the database.

Repeat of https://github.com/ExpressionEngine/ExpressionEngine/issues/246

**Comment by intoeetive** [comment]
Since this has already been reported, I'm going to close this one and add EE6 label to the other one. Thank you for reporting - we will look into how this can possibly be addressed
