### ISSUE TITLE
css not loaded on installation page

### ISSUE THREAD

**Issue by nix79** [ExpressionEngine/ExpressionEngine#567]
hi,
I've tried EE 6 installing it under a subdirectory but the css of installation page (admin.php) has an absolute path that does not consider the subdir so it is not loaded. in any case it is possible to proceed with the installation.

thanks

**Comment by intoeetive** [comment]
@nix79 thank you! This will be addressed in next beta release

**Comment by nix79** [comment]
> @nix79 thank you! This will be addressed in next beta release

great!

**Comment by robinsowell** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
