### ISSUE TITLE
Edit Partial Template - Content input field height

### ISSUE THREAD

**Issue by avnerw** [ExpressionEngine/ExpressionEngine#568]
The content input field for Partial Templates has an inline style height set of only 63px which is hardly enough to see any code in it. Suggest setting this to a larger min-height, like in EE5.  It also does not seem to be scrollable on an iPad Pro.

![Screen Shot 2020-10-19 at 12 56 02 PM](https://user-images.githubusercontent.com/17215743/96432055-09030600-120d-11eb-9123-f612afbbde0e.png)

**Comment by intoeetive** [comment]
Thank you! This will be addressed in next EE6 beta release

**Comment by robinsowell** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
