### ISSUE TITLE
A checkbox field's 'Check All' text doesn't actually 'check all'.

### ISSUE THREAD

**Issue by JasonBoothman** [ExpressionEngine/ExpressionEngine#571]
For any checkbox field if you click the checkbox next to the 'Check All' text, it will work as expected and check/uncheck all options. If, however, you click the 'Check All' text (which is linked), it will check the checkbox directly next to it, but won't actually trigger selecting/unselecting all the options.

A quick way to see this in action is to create a new member role.

1. Click 'Members'.
2. Click 'Member Roles'
3. Click 'New Role'.
4. Click the 'CP Access' tab.
5. Click the 'Check All' text multiple times and see how it ticks the checkbox directly next to it, but doesn't actually check/uncheck the options.

![check-all](https://user-images.githubusercontent.com/4921348/96473513-bf5fee80-11ff-11eb-9e59-219a7e0b9188.png)

**Comment by intoeetive** [comment]
This has been fixed in 6.0.1
