### ISSUE TITLE
EE6 - Show Entry type / Channel

### ISSUE THREAD

**Issue by inoatech** [ExpressionEngine/ExpressionEngine#573]
In the new EE6 edit entry screen, there is no indication of entry type / channel.

In EE5 this was indicated by breadcrumb nav above the entry form.

When dealing with more than a few channels, this is a really helpful indicator of where one is.
It'd be great if something like this could be restored.

**Comment by inoatech** [comment]
Maybe {Channel} could come between "ENTRIES" and "EDIT ENTRY" and also be a link to the filtered entries for the channel?

**Comment by ops-andy** [comment]
I'll submit this to be reviewed. You can see the channel entry is in via the Options tab (if it's not hidden by the channel's publish layout), but I can see where you're coming from and the missing breadcrumb
![image](https://user-images.githubusercontent.com/55093827/96606226-0b289b80-12c5-11eb-85d9-2c2eceae172e.png)

**Comment by ops-andy** [comment]
for reference EE5 Breadcrumb: 
![image](https://user-images.githubusercontent.com/55093827/96606374-3612ef80-12c5-11eb-9600-4f1126452652.png)
