### ISSUE TITLE
EE6 - Statuses with FFFFFF as highlight color become invisible

### ISSUE THREAD

**Issue by inoatech** [ExpressionEngine/ExpressionEngine#575]
In EE5, highlight color was used as background for statuses. If white was used, status text would still be black.

In EE6, statuses with FFFFFF as highlight color (or other light color?) become invisible when editing a channel.

Perhaps the problem is reversed in dark mode?

EE5:
<img width="166" alt="Screen Shot 2020-10-19 at 1 58 01 PM" src="https://user-images.githubusercontent.com/245898/96499547-305cd180-1213-11eb-8666-ba7476a22f4c.png">

EE6:
<img width="202" alt="Screen Shot 2020-10-19 at 1 58 22 PM" src="https://user-images.githubusercontent.com/245898/96499546-2fc43b00-1213-11eb-90cb-4eb28e47754b.png">

**Comment by ops-andy** [comment]
this was resolved in EE6 
![image](https://user-images.githubusercontent.com/55093827/102542214-74d3e480-407f-11eb-9781-dfd7d0683439.png)
