### ISSUE TITLE
Index page not editable in Template Manager

### ISSUE THREAD

**Issue by VarenSwaab** [ExpressionEngine/ExpressionEngine#577]
I'm logged in as Super Admin using the Template Manager to edit the default index template. When I try to save the edit I get an error:

Forbidden You don't have permission to access /***.php on this server.

I checked permissions on the file and it's 666 and the template folder 777. Other templates I create in the Template Manager in the same template group are perfectly editable. Just this one file. Can't figure out why... All templates have the same permissions and no other settings were involved.

I'm on Nexcess cloud, unix, php 7.3

**Comment by intoeetive** [comment]
@VarenSwaab is this new install or upgraded site? What's actually `***.php`? EE templates are saved as `.html` files, not `.php` so the error might be referring to something else

**Comment by VarenSwaab** [comment]
Yuri,

The site is a new install. The “***.php” is simply because I'm obscuring the real name of the file. The file being referenced in the error isn’t a template file, it’s the renamed “admin.php” file. 

Varen

**Comment by intoeetive** [comment]
@VarenSwaab I have a feeling that there's something with your settings that has not been migrated properly. Can you confirm that your `***.php` file (the one referenced in error) actually exists in site root directory and that it's the renamed `admin.php` from EE6 setup?
Also, when editing template, do you access the page via renamed `admin.php` or `/system/` (check what's actually displayed in browser address pane)

**Comment by VarenSwaab** [comment]
@intoeetive There was no migration since this is a fresh install in a fresh server space. I do have MSM setup but the domain I'm seeing this problem with is the main domain, not a satellite domain. 

When editing the template it's being accessed through the renamed admin.php template. This is the url with the actual file name redacted: https://*****.com/*****.php?/cp/design/template/edit/1

**Comment by VarenSwaab** [comment]
@intoeetive I updated to beta 2 and no change with this issue. It's not a big problem for me since I use an external editor but it does indicate that there is some sort of funkiness going on. If you want to pursue let me know.

**Comment by intoeetive** [comment]
I am unable to replicate this so far. Did you make any changes in `admin.php` file? (or any other EE files except `config.php`) Is there anything specific in the index template itself? 
Lastly, any addons installed that are not bundled with EE?

**Comment by VarenSwaab** [comment]
@intoeetive I made no edits to admin.php except for the path and MSM specific overrides. Everything else seems to be working so I assume those edits are valid. I spent quite a bit of time trying to figure out any specific abnormality to the index.php file itself and can't find any. I played with permissions, set everything to 777 and it still didn't work. I can edit all other template files in that site from the control panel except index.php, sql #1

**Comment by intoeetive** [comment]
@VarenSwaab my suspect it has something to do with your hosting environment, not EE in general.

When you go to `...system/user/templates/default_site/<default_group>/` - does it have `index.html` file and does that file have correct permissions?
Also please double check `$assign_to_config['cp_url']` value in `admin.php` site

**Comment by VarenSwaab** [comment]
I'm revisiting this topic because even after numerous reinstalls in my Nexcess account (supposedly tuned for EE), I still get the same error saying:

**Forbidden
You don't have permission to access /renamed_admin.php on this server.**

I'm now certain this isn't an MSM issue as my installs have been single site only. I also don't think this is a misconfiguration on my part as I've installed EE countless times over nearly 20 years and have never encountered this before. 

I have played around with permissions and, as I said above, changed permissions to 777 and the file operation will work sometimes and sometimes not. The only pattern I can see is that it tends to work when I have only a few characters of text in the file and when I paste in real html the operation fails.

I imagine that most people edit their templates with text editors and will never come across this issue. I invite others to attempt editing the very first index.php file created by the system when the first group is made and see if it happens to them.

I'm convinced this is a bug.

**Comment by intoeetive** [comment]
Thanks, we'll look at this once again. Is this EE6 only, or you also have this problem in EE5?

**Comment by ops-andy** [comment]
@VarenSwaab while many people use external editors, there are many many who do not. We plus we want to make sure everything works as expected.  
Trying to make sure I have everything replicated to test:
**EE Version:** this happens on all Beta versions of EE6 and Rc.1
**MSM site?** This happens on both MSM and single-site installs
**CP access url/:** https://[domain].com/[renamed admin].php
**Permissions:** /system/user/templates is set to 777 and all template files are 666
**Template with Errors:** this only happens on the index template in the template group set to be the site's default.
**Template Group name?**
 
**Web Server?** Apache or NGINX ?
**PHP Version?**

**Other Questions**
Do you have other templates in the same template group folder? If so can you edit those?
Are there any .htaccess files in the site root, templates folder, or anywhere else that might be preventing access?

**Comment by VarenSwaab** [comment]
As requested I'm restating this bug as mentioned in #828 

I've reported this bug during the beta but was unable to follow through. Unfortunately, it's still haunting me on an irregular basis. I'm hosting on Nexcess with a standard setup. PHP version is 7.3, EE version is 6.01.

The bug happens when trying to change the name of an existing template. It happens randomly and only affects a few of the templates but on those templates it happens each time. I recorded a screen video to show that when I try to change the name of a template named "new" it results in an error. I then show how I can successfully change the name of another template and have no issues.

I should note that sometimes these templates are open in my text editor over SSH but even if the template is closed the error still happens. It's not uncommon to get this error on freshly made templates that have never been opened in an editor.

https://user-images.githubusercontent.com/5083862/106397962-02b42680-63c5-11eb-9b70-4570b1539c8b.mov

**Comment by intoeetive** [comment]
We've been hearing from few people reports that had some inconsistency issues when using Nexcess.

I think what is happening here on video is some other server software - supposedly some of Nginx modules - is intercepting the "save " request and mis-interpreting it as hacking attempt, and thus blocking the request.

If you still seeing this issue, try reaching out to the hoster and talking to them.

I am closing this issue as external by nature.

**Comment by VarenSwaab** [comment]
Yuri, I think you're correct and it's related to hosting. I don't recall getting the error since 7.x so it seems to have corrected itself. Thanks.
