### ISSUE TITLE
Empty button in grid column when minimum rows condition is active.

### ISSUE THREAD

**Issue by JasonBoothman** [ExpressionEngine/ExpressionEngine#578]
If you set a minimum requirement to a grid field and only have the minimum rows for an entry, the trash icon disappears (as it should), but the button border still remains, leaving a blank button (see attachment screenshot).

![grid-minimum-rows](https://user-images.githubusercontent.com/4921348/96508136-24c7d580-1228-11eb-8fcf-e4096e929e54.png)

**Comment by intoeetive** [comment]
Thank you! We will fix this in next beta release

**Comment by intoeetive** [comment]
Fixed in [beta 2](https://docs.expressionengine.com/v6/installation/changelog.html#beta-2-release-october-22-2020)
