### ISSUE TITLE
Fluid field hooks

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#58]
**Is your feature request related to a problem? Please describe.**
3rd party add-ons, in this case Publisher, do not have a way to interact with or manage the I/O of data with Fluid fields. Fluid is similar to Grid and Relationships in that they store their data in different db tables, but it does not have hooks yet to interact with in a similar fashion.

**Describe the solution you'd like**
Add hooks to key data I/O points in Fluid's model and/or ft file. My WIP can be seen at https://github.com/litzinger/ExpressionEngine/commits/feature/fluid-field-hooks. Currently it appears the best points for inserting hooks are in Fluid's model file where it fetches data from exp_fluid_field_data, which stores all the assignments of which fields exist in a particular Fluid field in an entry, and then where it fetches data for each "row" or field assigned. Added example usages of 2 additional hooks, one for save and one for the update methods.

Current example of how to use the hooks:

```
public function fluid_field_get_all_data($entryId, $fluidFieldId)
    {
        /** @var CI_DB_result $fields */
        $fields = ee('db')->where([
            'fluid_field_id' => $fluidFieldId,
            'entry_id' => $entryId,
            'lang_id' => $this->request->getCurrentLanguage()->getId(),
            'status' => $this->request->getCurrentStatus(),
        ])->get('publisher_fluid_field_data');

        $collection = new EllisLab\ExpressionEngine\Service\Model\Collection();

        // Fudge a Collection of FluidField models
        foreach ($fields->result() as $field) {
            /** @var ChannelEntry $entryModel */
            $fluidFieldModel = ee('Model')->make('fluid_field:FluidField');
            $fluidFieldModel->fill((array) $field);

            $collection->add($fluidFieldModel);
        }

        return $collection;
    }

    public function fluid_field_get_field_data($fieldId, $fieldDataId)
    {
        $where = [
            'id' => $fieldDataId,
            'lang_id' => $this->request->getCurrentLanguage()->getId(),
            'status' => $this->request->getCurrentStatus(),
        ];

        $rows = ee('db')
            ->where($where)
            ->get('publisher_data_field_' . $fieldId)
            ->result_array();

        return $rows;
    }

public function fluid_field_add_field(FluidField $fluidField, $fieldTableName, $values)
    {
        $fieldTableName = str_replace('channel_data_field_', 'publisher_data_field_', $fieldTableName);

        // Publisher doesn't handle the format info
        $formatColumn = preg_grep('/field_ft_/', array_keys($values));
        unset($values[current($formatColumn)]);

        // Why is entry_id 0?
        $values['entry_id'] = $fluidField->entry_id;
        $values['lang_id'] = $this->request->getCurrentLanguage()->getId();
        $values['status'] = $this->request->getCurrentStatus();

        /** @var CI_DB_result $query */
        ee('db')->set($values)->insert($fieldTableName);
        $fieldDataId = ee()->db->insert_id(); // $query returns true, so can't do $query->insert_id();

        ee('db')
            ->set([
                'fluid_field_id' => $fluidField->fluid_field_id,
                'entry_id' => $fluidField->entry_id,
                'field_id' => $fluidField->field_id,
                'field_data_id' => $fieldDataId,
                'order' => $fluidField->order,
                'lang_id' => $this->request->getCurrentLanguage()->getId(),
                'status' => $this->request->getCurrentStatus(),
            ])
            ->insert('publisher_fluid_field_data');

        return false;
    }

    public function fluid_field_update_field(FluidField $fluidField, $fieldTableName, $values)
    {
        $fieldTableName = str_replace('channel_data_field_', 'publisher_data_field_', $fieldTableName);

        // Publisher doesn't handle the format info
        $formatColumn = preg_grep('/field_ft_/', array_keys($values));
        unset($values[current($formatColumn)]);

        // Why is entry_id 0?
        $values['entry_id'] = $fluidField->entry_id;
        $values['lang_id'] = $this->request->getCurrentLanguage()->getId();
        $values['status'] = $this->request->getCurrentStatus();

        $where = [
            'id' => $fluidField->field_data_id,
            'lang_id' => $this->request->getCurrentLanguage()->getId(),
            'status' => $this->request->getCurrentStatus()
        ];

        ee('db')
            ->set($values)
            ->where($where)
            ->update($fieldTableName);
    }
```

**Teachability, Documentation, Adoption, Migration Strategy**
I can update the docs when the code is complete. Writing docs first may not make sense in this case b/c the hook names, locations, etc have not been finalized.

- [x] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by kevincupp** [comment]
Sure, I guess if we have hooks for Grid and Relationships, we should have them for Fluid, too. I'd say go ahead and start a PR whenever you're ready and we can talk more specific implementation details.

**Comment by dougblackjr** [comment]
@litzinger Are you planning on PRing your changes here?

**Comment by litzinger** [comment]
Maybe, eventually. Some day. At this point the core might have undergone enough changes to where I might have to start over. You can probably close this though.

**Comment by dougblackjr** [comment]
@litzinger Ported your killer work into a branch and PRed. Thank you for this!

**Comment by litzinger** [comment]
How thoroughly was this tested? It's been so long since I've even worked on it.

**Comment by dougblackjr** [comment]
@litzinger It's adjusted for EE6 and the changes to the fluid fields. Tests forthcoming. Created a test extension for the moment.
[fluid_field_test.zip](https://github.com/ExpressionEngine/ExpressionEngine/files/6326336/fluid_field_test.zip)
