### ISSUE TITLE
Can't log in as member

### ISSUE THREAD

**Issue by frshjb373** [ExpressionEngine/ExpressionEngine#581]
Getting following error after trying to log in as user:

Exception Caught
There was a database connection error or a problem with a query. Log in as a super admin or enable debugging for more information.
mysqli_connection.php:117

Additionally, there is the option to login and redirect to "other." Why not just include a radio for CP homepage so super admin doesn't have to manually set that redirect link?

**Comment by intoeetive** [comment]
@frshjb373 we need just few more details to replicate and address this.
What permissions does the member have that you tried to log in as? (check Member Roles and Access Overview sidebar links in profile). What URL did you try redirect to?

Can you also try setting "Error Visibility" to "Visible to everyone" in Debugging & Output settings as well as setting `$debug = 1;` in `index.php` and `admin.php` and see if you get any more details in error message.

For the second one, "CP Home" is available as option for members that have CP access.

**Comment by frshjb373** [comment]
When I save Debugging & Output to "Visible to everyone" it just reverts back to Hidden option selected on save.

Regardless, after setting debugging in admin and index.php files, I'm getting the following stack trace...looks like it coule be related to @litzinger's simple grids or bloqs? 

```Exception Caught
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbname.exp_upload_no_access' doesn't exist:
SELECT `upload_id`, `upload_id` FROM (`exp_upload_no_access`, `exp_upload_prefs_roles`) WHERE `member_group` = 7 AND `role_id` IS NULL
ee/legacy/database/drivers/mysqli/mysqli_connection.php:117

Stack Trace: Please include when reporting this error
#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('SELECT `upload_...')
#1 ee/legacy/database/DB_driver.php(270): CI_DB_mysqli_driver->_execute('SELECT `upload_...')
#2 ee/legacy/database/DB_driver.php(180): CI_DB_driver->simple_query('SELECT `upload_...')
#3 ee/legacy/database/DB_active_rec.php(1206): CI_DB_driver->query('SELECT `upload_...')
#4 ee/legacy/models/file_upload_preferences_model.php(34): CI_DB_active_record->get_where('upload_prefs_ro...', Array)
#5 ee/legacy/models/file_upload_preferences_model.php(249): File_upload_preferences_model->get_file_upload_preferences(NULL, NULL, true)
#6 ee/legacy/libraries/File_field.php(797): File_upload_preferences_model->get_paths()
#7 user/addons/simple_grids/FieldTypes/FileField.php(18): File_field->parse_string('{filedir_6}1600...')
#8 user/addons/simple_grids/ft.simple_grid.php(179): BoldMinded\SimpleGrids\FieldTypes\FileField->replaceTag('value_prop_imag...', '{filedir_6}1600...')
#9 [internal function]: Simple_grid_ft->replace_tag(Array, Array, '\n ...')
#10 user/addons/bloqs/Controller/FieldTypeWrapper.php(219): call_user_func(Array, Array, Array, '\n ...')
#11 user/addons/bloqs/Controller/TagController.php(853): BoldMinded\Bloqs\Controller\FieldTypeWrapper->replace('tag', Array, Array, '\n ...')
#12 user/addons/bloqs/Controller/TagController.php(581): BoldMinded\Bloqs\Controller\TagController->replaceTag(Object(BoldMinded\Bloqs\Model\AtomDefinition), 32, 3, 23, Array, Array, '\n ...')
#13 user/addons/bloqs/Controller/TagController.php(385): BoldMinded\Bloqs\Controller\TagController->_renderBlockSection('<section class=...', Object(BoldMinded\Bloqs\Controller\TagOutputBlockContext), Array)
#14 user/addons/bloqs/Controller/TagController.php(229): BoldMinded\Bloqs\Controller\TagController->_renderBlockSections(Array, '\n\t {!-- ra:000...', Object(BoldMinded\Bloqs\Controller\TagOutputBlockContext), Array)
#15 user/addons/bloqs/ft.bloqs.php(569): BoldMinded\Bloqs\Controller\TagController->replace('\n\t {!-- ra:000...', Array, Array, Array)
#16 ee/legacy/libraries/api/Api_channel_fields.php(410): Bloqs_ft->replace_tag(' ', Array, '\n\t {!-- ra:000...')
#17 ee/legacy/libraries/channel_entries_parser/components/Custom_field_pair.php(193): Api_channel_fields->apply('replace_tag', Array)
#18 ee/legacy/libraries/channel_entries_parser/Parser.php(298): EE_Channel_custom_field_pair_parser->replace('\n {home_bloqs}...', Object(EE_Channel_data_parser), Array)
#19 ee/legacy/libraries/Channel_entries_parser.php(172): EE_Channel_data_parser->parse(Array, Array)
#20 ee/ExpressionEngine/Addons/channel/mod.channel.php(2847): EE_Channel_parser->parse(Object(Channel), Array, Array)
#21 ee/ExpressionEngine/Addons/channel/mod.channel.php(281): Channel->parse_channel_entries()
#22 ee/legacy/libraries/Template.php(1874): Channel->entries()
#23 ee/legacy/libraries/Template.php(1509): EE_Template->process_tags()
#24 ee/legacy/libraries/Template.php(605): EE_Template->tags()
#25 ee/legacy/libraries/Template.php(236): EE_Template->parse('{!-- ra:0000000...', false, 1, false)
#26 ee/legacy/libraries/Template.php(167): EE_Template->fetch_and_parse('', Array, false)
#27 ee/legacy/libraries/Core.php(649): EE_Template->run_template_engine('', '')
#28 ee/legacy/controllers/ee.php(63): EE_Core->generate_page()
#29 [internal function]: EE->index()
#30 ee/ExpressionEngine/Core/Core.php(268): call_user_func_array(Array, Array)
#31 ee/ExpressionEngine/Core/Core.php(118): ExpressionEngine\Core\Core->runController(Array)
#32 ee/ExpressionEngine/Boot/boot.php(160): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#33 index.php(174): require_once('...')
#33 index.php(174): require_once('...')

**Comment by intoeetive** [comment]
Yes, this is clearly related to one of those addons - so closing this issue as it's not directly related to EE6.

**Comment by litzinger** [comment]
@frshjb373 can you create a ticket on BoldMinded.com and include that call stack output? Thanks!

**Comment by litzinger** [comment]
@intoeetive I'll take a look at this, but the File field is being called just as it would be if it were a native EE field. It's not doing anything special: https://github.com/litzinger/file-field/blob/master/src/FileField.php#L79-L83

**Comment by litzinger** [comment]
Also, the actual error is about a missing EE db table

`Base table or view not found: 1146 Table 'dbname.exp_upload_no_access' doesn't exist`

**Comment by litzinger** [comment]
FWIW, I don't see the `exp_upload_no_access` table in my EE6 install either, but there are a lot of references to the `legacy/models/file_upload_preferences_model.php` model in the EE6 codebase. Is it possible that the `exp_upload_no_access` table didn't get properly created during the install process?

**Comment by litzinger** [comment]
I have 2 EE5 sites, both have the `exp_upload_no_access` table. Josh upgraded an EE5 site to EE6, and his EE5 install also had the `exp_upload_no_access` table. Is it possible the EE6 upgrade/install method is dropping this table when it shouldn't?

**Comment by intoeetive** [comment]
@litzinger `exp_upload_no_access` should not exist in EE, but looks like it wasn't completely removed (and functions properly deprecated). We'll work on that - thanks for catching!

**Comment by ops-andy** [comment]
resolved in beta-3: https://expressionengine.com/blog/expressionengine-6-public-beta-3
