### ISSUE TITLE
ft.toggle.php has an empty $info array

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#582]
**Description of the problem**
As the title says, the ft.toggle.php file has:

`var $info = array();`

It should be:

```
var $info = array(
        'name'	=> 'Toggle',
        'version'	=> '1.0.0'
    );
```

Bloqs is displaying the field option as `toggle`, not `Toggle` because of this. I can update Bloqs to fix the display, but still noting the inconsistency in the ft properties.

**Environment Details:**
 - Version: 5.3 & 6b

**Comment by intoeetive** [comment]
Thank you - we'll address this in beta 3.

**Comment by ops-andy** [comment]
resolved in beta-3: https://expressionengine.com/blog/expressionengine-6-public-beta-3
