### ISSUE TITLE
Error Caught on Edit Entry / Publishing Page

### ISSUE THREAD

**Issue by mcfarlandonline** [ExpressionEngine/ExpressionEngine#583]
EE 6.0.0-b.1
PHP Version 7.4.11
10.3.25-MariaDB

I updated from 5.3.2 to the EE6 beta, and everything looked good on the front and backend, until I tried to view or edit my entries. (Or even create a new one). I only have 3 channels, and all entries respond the same way. The interface is un-themed, but the appropriate fields still show up. 

This is the error message I'm getting: 

> Error Caught
> Call to a member function getIconUrl() on null
> ee/ExpressionEngine/Model/Content/FieldFacade.php:173
> 
> Stack Trace: Please include when reporting this error
> #0 ee/ExpressionEngine/Addons/fluid_field/views/filters.php(5): ExpressionEngine\Model\Content\FieldFacade->getIcon()
> #1 ee/ExpressionEngine/Service/View/View.php(142): include('...')
> #2 ee/ExpressionEngine/Service/View/View.php(107): ExpressionEngine\Service\View\View->parse('...', Array)
> #3 ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php(365): ExpressionEngine\Service\View\View->render(Array)
> #4 ee/legacy/fieldtypes/EE_Fieldtype.php(326): Fluid_field_ft->display_field('We finally made...')
> #5 ee/legacy/libraries/api/Api_channel_fields.php(410): EE_Fieldtype->display_publish_field('We finally made...')
> #6 ee/ExpressionEngine/Model/Content/FieldFacade.php(250): Api_channel_fields->apply('display_publish...', Array)
> #7 ee/ExpressionEngine/Model/Content/Display/FieldDisplay.php(70): ExpressionEngine\Model\Content\FieldFacade->getForm()
> #8 ee/ExpressionEngine/View/publish/partials/publish_form.php(83): ExpressionEngine\Model\Content\Display\FieldDisplay->getForm()
> #9 ee/ExpressionEngine/Service/View/View.php(142): include('...')
> #10 ee/ExpressionEngine/Service/View/View.php(107): ExpressionEngine\Service\View\View->parse('...', Array)
> #11 ee/ExpressionEngine/Service/View/View.php(170): ExpressionEngine\Service\View\View->render(Array)
> #12 ee/ExpressionEngine/View/publish/entry.php(3): ExpressionEngine\Service\View\View->embed(Object(ExpressionEngine\Service\View\View))
> #13 ee/ExpressionEngine/Service/View/View.php(142): include('...')
> #14 ee/ExpressionEngine/Service/View/View.php(107): ExpressionEngine\Service\View\View->parse('...', Array)
> #15 ee/legacy/libraries/View.php(40): ExpressionEngine\Service\View\View->render(Array)
> #16 ee/legacy/libraries/Cp.php(263): View->render('publish/entry', Array, false)
> #17 ee/ExpressionEngine/Controller/Publish/Edit.php(537): Cp->render('publish/entry', Array)
> #18 [internal function]: ExpressionEngine\Controller\Publish\Edit->entry('76')
> #19 ee/ExpressionEngine/Core/Core.php(268): call_user_func_array(Array, Array)
> #20 ee/ExpressionEngine/Core/Core.php(118): ExpressionEngine\Core\Core->runController(Array)
> #21 ee/ExpressionEngine/Boot/boot.php(160): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
> #22 public_html/adventure/edit.php(154): require_once('...')
> #22 public_html/adventure/edit.php(154): require_once('...')

![screencapture-adventure-meganmcfarland-edit-php-2020-10-21-11_47_51](https://user-images.githubusercontent.com/20441129/96769016-645f0080-1393-11eb-8b87-77f3b16f8bbe.png)
![screencapture-adventure-meganmcfarland-edit-php-2020-10-21-11_47_31](https://user-images.githubusercontent.com/20441129/96769037-6923b480-1393-11eb-95bc-50c998e991d1.png)

**Comment by intoeetive** [comment]
@mcfarlandonline what are the field options for you 'Fluid Content' field? Can you list them or add screenshot. If you can't access that page, screenshot from EE5 is good as well

**Comment by pyrobob83** [comment]
@intoeetive I'm getting this too, specifically when there's a Grid available to the Fluid where the Grid contains a File field.  Standalone File fields work fine in a Fluid and even Grids without a File column work fine - but a File inside a Grid inside a Fluid gives this error.  Hope that helps!

**Comment by mcfarlandonline** [comment]
@intoeetive , similar to @pyrobob83 , I'm also using a File Grid inside of the Fluid field. Other fields include a textarea, grid, and text input field. 

<img width="437" alt="Screen Shot 2020-10-22 at 8 35 21 AM" src="https://user-images.githubusercontent.com/20441129/96896135-04736300-1442-11eb-861b-e8bc6e5cf4ab.png">

<img width="256" alt="Screen Shot 2020-10-22 at 8 35 36 AM" src="https://user-images.githubusercontent.com/20441129/96896143-063d2680-1442-11eb-8b1d-7b77716c10fc.png">

**Comment by intoeetive** [comment]
@mcfarlandonline @pyrobob83 thank you! We'll deliver a fix in next EE6 beta release.

**Comment by ops-andy** [comment]
resolved in beta-3: https://expressionengine.com/blog/expressionengine-6-public-beta-3
