### ISSUE TITLE
RTE doesn't have option to view source code

### ISSUE THREAD

**Issue by dankingsley** [ExpressionEngine/ExpressionEngine#585]
Having just installed EE6 beta 2 and reviewed the added toolbar options for the RTE, there still isn't an option to edit the source code (a standard feature of Wygwam and other RTE's).

**Comment by intoeetive** [comment]
"View source" is not a thing in CKEditor 5. The developers have some strong reasons to not include that feature: https://github.com/ckeditor/ckeditor5/issues/592
If it'll be ever implemented, we will add it to RTE
