### ISSUE TITLE
INTL_IDNA_VARIANT_2003 is deprecated

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#586]
EE6.0.0-b.1 & EE6.0.0-b.2
Fresh EE install (started with b.1 and 1-clicked to b.2)

```
Deprecated
idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

ee/legacy/libraries/Typography.php, line 2602

    Severity: E_DEPRECATED
```

TJ suggests using INTL_IDNA_VARIANT_UTS46 instead and linked me to https://aaronparecki.com/2018/02/06/9/#:~:text=Apparently%20the%20idn_to_ascii%20function%20deprecated,default%20if%20none%20is%20specified

**Comment by intoeetive** [comment]
@pyrobob83 what PHP version are you on? Is `intl` installed and what is `ICU` version reported by `phpinfo`?

**Comment by pyrobob83** [comment]
PHP7.3.0 and intl is installed:

ICU version | 4.2.1
ICU TZData version | 2009j
ICU Unicode version | 5.1


The weird thing is line 2602 is already referencing INTL_IDNA_VARIANT_UTS46, just from within this if statment:

```
if (is_php('7.2'))
{
	$parts['host'] = idn_to_ascii($parts['host'], 0, defined('INTL_IDNA_VARIANT_UTS46') ? INTL_IDNA_VARIANT_UTS46 : 0);
}
else
{
	$parts['host'] = idn_to_ascii($parts['host']);
}
```

**Comment by pyrobob83** [comment]
Sorry, I should have also mentioned it's only showing on the EE6 'Overview' screen - I can't seem to find any other screen in the CP that displays this

**Comment by intoeetive** [comment]
Looks like you have PHP compiled with really old ICU version. INTL_IDNA_VARIANT_UTS46 has been introduced un ICU 4.6 which was long before PHP 7.3.
But - you are already second person reporting this issue, so we should probably look into more reliable solution than just checking PHP version

**Comment by ops-andy** [comment]
resolved in beta-3: https://expressionengine.com/blog/expressionengine-6-public-beta-3
