### ISSUE TITLE
{pagination_links} tag parameters do not work if line breaks exist

### ISSUE THREAD

**Issue by stephengalbraith** [ExpressionEngine/ExpressionEngine#589]
This is also likely an issue with EE5. Just for my own purposes I like to layout my EE tags with breaks for readability later. This has always been fine with Channel Entries tags.

So for example: `{pagination_links always_show_first_last="yes" page_padding="1"}` properly produces:

<img width="388" alt="Screen Shot 2020-10-22 at 10 00 47 PM" src="https://user-images.githubusercontent.com/45797159/96947797-17be1700-14b2-11eb-9d62-2fd0d8132515.png">

But: {pagination_links 
always_show_first_last="yes" 
page_padding="1"}

Produces:

<img width="482" alt="Screen Shot 2020-10-22 at 10 04 24 PM" src="https://user-images.githubusercontent.com/45797159/96947984-931fc880-14b2-11eb-8beb-1c497e4b9f42.png">

I tested this with just having a Channel with 8 entries and limiting each page to 1.

**Comment by ops-andy** [comment]
resolved in beta-3: https://expressionengine.com/blog/expressionengine-6-public-beta-3
