### ISSUE TITLE
Incorrect usage of insert_id()

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#59]
**Description of the problem**
While testing my Publisher integration with Fluid fields, I had to make a similar call to ->insert_id(), but, in Fluid's ft file, it's trying to call it on an ee('db') result, which returns true, not a query object. E.g. This does not appear to work:

```
$query = ee('db')->set($values)->insert($field_table_name);
$id = $query->insert_id();
```

I think it needs to be this instead:

```
ee('db')->set($values)->insert($field_table_name);
$id = ee()->db->insert_id();
```

**Comment by kevincupp** [comment]
What is the issue with EE exactly? Fluid doesn't do this, it calls `insert_id()` on the query, not on the result. See line 306 of ft.fluid_field.php.

**Comment by litzinger** [comment]
I ran the same query and $query is true, not an object to call a function on.

**Comment by kevincupp** [comment]
Yes, if you chain your methods as you have, that might happen, but Fluid isn't chaining the methods. You end up assigning a differen't value to `$query` by calling `insert()`, and so you're not getting what you expect.

**Comment by litzinger** [comment]
Ah, I see. Thanks.
