### ISSUE TITLE
Cannot delete grid row when there is only one row

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#590]
EE6.0.0-b.2

When you only have one grid row on a publish page you cannot delete it, the delete button is missing.

Steps to reproduce;

1. Create a Grid field and assign to a channel, I have File field, Text field and RTE fields for my test
2. Add a couple of grid rows
3. Delete any row, the delete button isn't displaying

**Comment by ops-andy** [comment]
resolved in beta-3: https://expressionengine.com/blog/expressionengine-6-public-beta-3
