### ISSUE TITLE
Channel Entry Field Rules/Conditional logic in channel entry

### ISSUE THREAD

**Issue by frshjb373** [ExpressionEngine/ExpressionEngine#592]
Ability to use conditional logic and rules for displaying/hiding fields in a channel entry.

Example attached from a different application...
![Screen Shot 2020-10-23 at 6 15 31 AM](https://user-images.githubusercontent.com/7178139/97008094-3eeb0780-14f7-11eb-8d7a-30462423a320.png)

**Comment by intoeetive** [comment]
Just to clarify - you are referring to using this in CP Publish Layouts, right @frshjb373 ?

**Comment by frshjb373** [comment]
Yes, I would imagine that would be the ideal place for permitted admin/dev to configure that logic.

**Comment by robsonsobral** [comment]
I guess, we could consider incorporating the [entry_type plugin](https://github.com/rsanchez/entry_type), instead of to start from zero.

**Comment by ricklecoat** [comment]
This would be a great addition to the CP's UX. It would avoid overly-cluttered publishing forms in the CP where a tonne of fields are displayed ‘just in case’ (even if they're collapsed, they still add visual clutter). 

As a quick use-case scenario: I'm currently whipping up a quick EE site for myself to keep track of job applications; I would want the 'Date applied' field to **only** show in the publish form if that entry’s _status_ was set to 'Applied'; similarly the 'Interview date' field should only show up if the status of that application entry was set to 'Interview scheduled'.

**Comment by mkinberg** [comment]
+1 for this feature

**Comment by intoeetive** [comment]
[Conditional fields](https://docs.expressionengine.com/latest/control-panel/field-manager/conditional-fields.html) have been implemented
