### ISSUE TITLE
Live Preview button visible when no Preview URL set; error when clicking "preview" button not visible unless page is scrolled all the way up

### ISSUE THREAD

**Issue by tjdraper** [ExpressionEngine/ExpressionEngine#594]
The Preview button should be hidden when no preview URL is set as in EE 4/5.

However, I'm assuming this is a decision that's been made to show it and give an error instead, which is what happens now, so secondarily, when entry is scrolled, and "Preview" is clicked, the error is not shown until you scroll back to the top of the screen.

<img width="1196" alt="Screen Shot 2020-10-24 at 12 36 42 PM" src="https://user-images.githubusercontent.com/3803475/97088325-ab4c3080-15f5-11eb-9ca2-559f4ddb92e5.png">
<img width="1196" alt="Screen Shot 2020-10-24 at 12 36 45 PM" src="https://user-images.githubusercontent.com/3803475/97088329-b0a97b00-15f5-11eb-89cf-cbe1f4a12e53.png">
<img width="727" alt="Screen Shot 2020-10-24 at 12 37 00 PM" src="https://user-images.githubusercontent.com/3803475/97088332-b3a46b80-15f5-11eb-9a8b-2bdfc4196f79.png">
<img width="727" alt="Screen Shot 2020-10-24 at 12 37 02 PM" src="https://user-images.githubusercontent.com/3803475/97088333-b606c580-15f5-11eb-98d1-199086dd3ba3.png">

**Comment by ops-andy** [comment]
resolved in beta-3: https://expressionengine.com/blog/expressionengine-6-public-beta-3
