### ISSUE TITLE
EE6 - 1-Click Updater fails at Preflight Check

### ISSUE THREAD

**Issue by WinkingFrog** [ExpressionEngine/ExpressionEngine#595]
Attempting to update from b1 to b2 using the 1-Click Updater I get the following message...

```
Update Stopped 
Oops, looks like the updater couldn't complete.
We stopped on Preflight check.
Cannot get contents of path, the path is invalid: /ee/
Troubleshoot, then Continue
Or, return to the control panel.
ExpressionEngine
©2020 Packet Tide LLC
```

Originally I suspected this was a paths issue as I had moved the system folder outside the root, but having moved it back the same error was found.

This is on a MAMP Pro local development server

**Comment by ops-andy** [comment]
@WinkingFrog Thanks for submitting this. I've been unable to replicate as of yet even when moving my system folder above the public root. Before running the 1-click updat, did you ensure your paths were correct in Settings -> URL and Path Settings?
If not, can you ensure those are correct, if changes need to be made, make those then try the 1-click updater again.

**Comment by intoeetive** [comment]
I haven't been able to replicate this either

**Comment by WinkingFrog** [comment]
Had the same problem with the beta 3 to beta 4 update. This turned out to be an issue with the Themes Path. I noticed in the control panel that the path was set to '/' by default (on my installation anyway), and when I set it correctly the update ran as expected.

Not sure if this is something that is a result of moving the system folder, or an issue with the default value EE creates in config at install.

**Comment by jrhawk01** [comment]
I have encountered the exact same problem attempting to upgrade from 5.3.2 to 5.4.2.  I am also using a Mamp Pro testing server on my Mac and can verify that all of the information in the URL & Path Settings is correct.

**Comment by PontusMadsen** [comment]
Same here.

After moving to new server, the 1-Click Updater fails at Preflight Check.
Going from 6.4.3 to 6.4.4.
Even tho I've changed the default base_path to the new server path, it shows up as the old server's path in the Updater error message. 

This on a live site, hosted on EE nexcess.

**Comment by intoeetive** [comment]
I am replicating it - assuming it's of same origin that @PontusMadsen 's issue was.

If you migrate the site between hosts and your `theme_folder_path` (assuming also other path settings) in database is wrong, the site will be functioning without any issues (at least most of the operations)

However it appears that 1-click update is actually relying on the values saved in database, so if you never save your URL & Path Settings page, you will get Preflight check error.
