### ISSUE TITLE
EE6 - Broken Docs Link

### ISSUE THREAD

**Issue by skookie000** [ExpressionEngine/ExpressionEngine#596]
Developer log says:
"MemberGroup model has been removed from ExpressionEngine 6. Please use Role model instead."
Role Model links to https://docs.expressionengine.com/v6/development/v6-addon-migration.html#required-changes that is 404.

Side note, I have no idea what generated this message.  Some additional context of where/what triggered this would be helpful.

**Comment by skookie000** [comment]
v6 beta 2.

**Comment by ops-andy** [comment]
resolved in beta-3: https://expressionengine.com/blog/expressionengine-6-public-beta-3
