### ISSUE TITLE
MSM allows duplicate channel creation

### ISSUE THREAD

**Issue by VarenSwaab** [ExpressionEngine/ExpressionEngine#597]
Honestly not sure if this is a feature or a bug but MSM is allowing for the creation of identical channel names (both long name and short name) in different sites. I'm new to MSM so I don't want to assume this is a bug but it seems like a bad idea and completely unnecessary to allow different sites identical channel names.

**Comment by intoeetive** [comment]
According to the [docs](https://docs.expressionengine.com/latest/msm/code.html#specifying-multiple-sites-prepare-for-a-head-trip) you can have channel with same name on different sites. This has been done on purpose.
