### ISSUE TITLE
Registering Member from CP fails if custom member field is marked as required, but does not appear in publish form

### ISSUE THREAD

**Issue by stephengalbraith** [ExpressionEngine/ExpressionEngine#598]
I went to go register a new member from the CP and it kept failing on just the basic form:

<img width="1184" alt="Screen Shot 2020-10-25 at 1 58 15 PM" src="https://user-images.githubusercontent.com/45797159/97115006-60e8b380-16ca-11eb-9525-89a19434b517.png">

No error was actually appearing and then I realized that one of the custom fields I made was marked as required:

<img width="908" alt="Screen Shot 2020-10-25 at 1 58 28 PM" src="https://user-images.githubusercontent.com/45797159/97115014-752cb080-16ca-11eb-9c3c-aaed2b5d060a.png">

When I removed the field from being required, the form submitted properly.

I am assuming the form is checking for custom fields, but not displaying them in the registration process from the CP leading to a generic error.

So steps to reproduce:

1. Create a custom member field, mark it as a required field.
2. Try to register a new member from the CP - admin.php?/cp/members/create

**Comment by ops-andy** [comment]
I was able to replicate.

**Comment by intoeetive** [comment]
This has been fixed in beta 3 release
