### ISSUE TITLE
"No Fields found. Add New"  ... EE-4.3.6

### ISSUE THREAD

**Issue by jeraldjohnson** [ExpressionEngine/ExpressionEngine#6]
Hi I'm using ExpressionEngine 4.3.6. 
My workflow is such that I create the templates, then Channels, then field groups and then fields. All titled appropriately so that its easy to locate them. I've noticed that when i create a channel and then use the field tab to create the field groups and fields for that particular channel  it works pretty ok. I get the correct functionality on the front end of the website. If I go to the developer drop down and select fields it shows my field groups on the left  and all fields on the right, however, if I select one of the field groups the right side shows "No Fields found. Add New"  as opposed to showing the fields i created. 
I've attached an image showing this. 
![1](https://user-images.githubusercontent.com/12180171/48679479-259cec00-eb67-11e8-98b1-771159b8bc65.png)
![2](https://user-images.githubusercontent.com/12180171/48679480-26358280-eb67-11e8-8888-da411b70e8c2.png)

**Comment by kevincupp** [comment]
Did you assign the fields to the field group? If not, then they will not appear when you click the field group. Remember, fields can exist outside of field group unless you explicitly add them to a group.

**Comment by jeraldjohnson** [comment]
Thanks for the reply. My assumption was that creating and adding the fields to the groups via the "Channel Manager" view would've allowed them to be present when you navigate to the "Fields" under the "Developer" drop down menu and click on the "Field Group" on the left.

**Comment by jeraldjohnson** [comment]
That explains a lot. Thanks for the info. Appreciate it.

**Comment by jeraldjohnson** [comment]
That explains a lot. Thanks for the info. Appreciate it.
