### ISSUE TITLE
Auto-updater not accounting for database table name prefix

### ISSUE THREAD

**Issue by jHards** [ExpressionEngine/ExpressionEngine#60]
**Description of the problem**
I am trying to run the auto updater from /admin.php to update from 4.3.6 to 5.1.0 and the updater cannot complete the database backup. It seems to be looking for default tables names but not considering a prefix used during the installation process.

**How To Reproduce**
1. Run the auto-updater whilst using a database table prefix
2. See error below

**Error Messages**
![image](https://user-images.githubusercontent.com/17785714/50351260-3db9af80-0507-11e9-8bac-4ad5c690fa4e.png)

**Environment Details:**
 - Version: 4.3.6
 - PHP Version 7.1
 - OS: Linux

**Possible Solution**
I assume it's a simple fix of pulling the database prefix stored in the settings and if present, include in the SQL update code.

**Comment by kevincupp** [comment]
Sorry @jHards, I think I see what's going on there, we'll get a fix in soon!
