### ISSUE TITLE
No such property: 'status_model' on EllisLab\ExpressionEngine\Legacy\Facade

### ISSUE THREAD

**Issue by mladen-dordevic** [ExpressionEngine/ExpressionEngine#602]
**Description of the problem**
_check_for_data_errors function within Api_channel_entries class is trying to run get_disallowed_statuses method of status_model without loading status_model.

**Error Messages**

<pre><code>
Exception Caught
No such property: 'status_model' on EllisLab\ExpressionEngine\Legacy\Facade
ee/EllisLab/ExpressionEngine/Legacy/Facade.php:120

Stack Trace: Please include when reporting this error
#0 ee/EllisLab/ExpressionEngine/Legacy/Facade.php(30): EllisLab\ExpressionEngine\Legacy\Facade->get('status_model')
#1 ee/legacy/libraries/api/Api_channel_entries.php(823): EllisLab\ExpressionEngine\Legacy\Facade->__get('status_model')
#2 ee/legacy/libraries/api/Api_channel_entries.php(111): Api_channel_entries->_check_for_data_errors(Array)
#3 ev/ee2_modules/iris_util/libraries/Auto_create_calendar_entry.php(55): Api_channel_entries->save_entry(Array, 7, 6645, false)
#4 ev/ee2_modules/iris_util/ext.iris_util.php(100): Auto_create_calendar_entry->create(Object(EllisLab\ExpressionEngine\Model\Channel\ChannelEntry), Array)
#5 ee/legacy/libraries/Extensions.php(222): Iris_util_ext->hook_submit(Object(EllisLab\ExpressionEngine\Model\Channel\ChannelEntry), Array)
#6 ee/legacy/libraries/Extensions.php(117): EE_Extensions->call_class('Iris_util_ext', 'after_channel_e...', Array, Array)
#7 [internal function]: EE_Extensions->call('after_channel_e...', Object(EllisLab\ExpressionEngine\Model\Channel\ChannelEntry), Array)
#8 ee/EllisLab/ExpressionEngine/Service/Model/Model.php(665): call_user_func_array(Array, Array)
#9 [internal function]: EllisLab\ExpressionEngine\Service\Model\Model->EllisLab\ExpressionEngine\Service\Model\{closure}('after_channel_e...', Object(EllisLab\ExpressionEngine\Model\Channel\ChannelEntry), Array)
#10 ee/EllisLab/ExpressionEngine/Service/Model/Model.php(616): call_user_func_array(Object(Closure), Array)
#11 [internal function]: EllisLab\ExpressionEngine\Service\Model\Model->EllisLab\ExpressionEngine\Service\Model\{closure}()
#12 ee/EllisLab/ExpressionEngine/Service/Event/Emitter.php(141): call_user_func_array(Object(Closure), Array)
#13 [internal function]: EllisLab\ExpressionEngine\Service\Event\Emitter->emit('afterSave')
#14 ee/EllisLab/ExpressionEngine/Library/Data/Entity.php(654): call_user_func_array(Array, Array)
#15 [internal function]: EllisLab\ExpressionEngine\Library\Data\Entity->emit('afterSave')
#16 ee/EllisLab/ExpressionEngine/Service/Model/Model.php(858): call_user_func_array('parent::emit', Array)
#17 ee/EllisLab/ExpressionEngine/Service/Model/Query/Update.php(51): EllisLab\ExpressionEngine\Service\Model\Model->emit('afterSave')
#18 ee/EllisLab/ExpressionEngine/Service/Model/DataStore.php(282): EllisLab\ExpressionEngine\Service\Model\Query\Update->run()
#19 ee/EllisLab/ExpressionEngine/Service/Model/DataStore.php(248): EllisLab\ExpressionEngine\Service\Model\DataStore->runQuery('Update', Object(EllisLab\ExpressionEngine\Service\Model\Query\Builder))
#20 ee/EllisLab/ExpressionEngine/Service/Model/Query/Builder.php(71): EllisLab\ExpressionEngine\Service\Model\DataStore->updateQuery(Object(EllisLab\ExpressionEngine\Service\Model\Query\Builder))
#21 ee/EllisLab/ExpressionEngine/Service/Model/Model.php(366): EllisLab\ExpressionEngine\Service\Model\Query\Builder->update()
#22 ee/EllisLab/ExpressionEngine/Model/Content/ContentModel.php(225): EllisLab\ExpressionEngine\Service\Model\Model->save()
#23 ee/EllisLab/ExpressionEngine/Controller/Publish/AbstractPublish.php(376): EllisLab\ExpressionEngine\Model\Content\ContentModel->save()
#24 ee/EllisLab/ExpressionEngine/Controller/Publish/Edit.php(527): EllisLab\ExpressionEngine\Controller\Publish\AbstractPublish->saveEntryAndRedirect(Object(EllisLab\ExpressionEngine\Model\Channel\ChannelEntry))
#25 [internal function]: EllisLab\ExpressionEngine\Controller\Publish\Edit->entry('6326')
#26 ee/EllisLab/ExpressionEngine/Core/Core.php(241): call_user_func_array(Array, Array)
#27 ee/EllisLab/ExpressionEngine/Core/Core.php(110): EllisLab\ExpressionEngine\Core\Core->runController(Array)
#28 ee/EllisLab/ExpressionEngine/Boot/boot.php(151): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request))
#29 hq/admin.php(153): require_once('...')
#29 hq/admin.php(153): require_once('...')
</code>
</code></pre>

**Environment Details:**
 - Version: [e.g. 5.3.2]
 - PHP Version [e.g. 7.1]

**Possible Solution**
Load model before using it: legacy/api/Api_channel_entries.php
<code>ee()->load->model('status_model');</code>

add before line 822

**Additional context**

**Comment by ops-andy** [comment]
@intoeetive can you confirm/followup on this, please.

**Comment by intoeetive** [comment]
I was able to see the issue in EE 5.3.2 (does not exist in EE6). We will provide fix in next 5.x release
