### ISSUE TITLE
styling issue on template routes dropdown - needs padding on left of list items

### ISSUE THREAD

**Issue by frshjb373** [ExpressionEngine/ExpressionEngine#604]
<img width="1187" alt="Screen Shot 2020-10-30 at 3 42 21 AM" src="https://user-images.githubusercontent.com/7178139/97696050-38faa680-1a62-11eb-8802-ef26eaa9b95e.png">

**Comment by frshjb373** [comment]
@intoeetive looks like same styling issue in file dropdown in @litzinger's Simple Tables & Grid with a file field.

**Comment by intoeetive** [comment]
This is fixed in [EE 6 beta 3](https://expressionengine.com/blog/expressionengine-6-public-beta-3)
