### ISSUE TITLE
Errors creating new field

### ISSUE THREAD

**Issue by VarenSwaab** [ExpressionEngine/ExpressionEngine#605]
I was trying to create a new field using Reinos Maps Fieldtype and got the following error. I'm using EE6 beta 2 and Maps Fieldtype 2.1.3 (updated today). 

Exception Caught

Unknown field MemberGroup.group_id

ee/ExpressionEngine/Service/Model/Query/Select.php:789

Stack Trace: Please include when reporting this error

#0 ee/ExpressionEngine/Service/Model/Query/Select.php(631): ExpressionEngine\Service\Model\Query\Select->translateProperty('group_id')
#1 ee/ExpressionEngine/Service/Model/Query/Select.php(618): ExpressionEngine\Service\Model\Query\Select->applyFilter(Object(ExpressionEngine\Service\Database\Query), Array)
#2 ee/ExpressionEngine/Service/Model/Query/Select.php(116): ExpressionEngine\Service\Model\Query\Select->applyFilters(Object(ExpressionEngine\Service\Database\Query), Array)
#3 ee/ExpressionEngine/Service/Model/Query/Select.php(48): ExpressionEngine\Service\Model\Query\Select->buildQuery()
#4 ee/ExpressionEngine/Service/Model/DataStore.php(282): ExpressionEngine\Service\Model\Query\Select->run()
#5 ee/ExpressionEngine/Service/Model/DataStore.php(228): ExpressionEngine\Service\Model\DataStore->runQuery('Select', Object(ExpressionEngine\Service\Model\Query\Builder))
#6 ee/ExpressionEngine/Service/Model/Query/Builder.php(144): ExpressionEngine\Service\Model\DataStore->selectQuery(Object(ExpressionEngine\Service\Model\Query\Builder))
#7 ee/ExpressionEngine/Service/Model/Query/Builder.php(63): ExpressionEngine\Service\Model\Query\Builder->fetch()
#8 user/addons/reinos_maps_fieldtype/Service/SettingsHelper.php(87): ExpressionEngine\Service\Model\Query\Builder->all()
#9 user/addons/reinos_maps_fieldtype/ft.reinos_maps_fieldtype.php(790): Reinos\MapsFieldtype\Service\SettingsHelper->get_membergroups(Array, 'reinos_maps_fie...')
#10 user/addons/reinos_maps_fieldtype/ft.reinos_maps_fieldtype.php(854): Reinos_maps_fieldtype_ft->_display_settings(Array)
#11 ee/legacy/libraries/api/Api_channel_fields.php(410): Reinos_maps_fieldtype_ft->display_settings(Array)
#12 ee/legacy/libraries/Grid_parser.php(698): Api_channel_fields->apply('display_setting...', Array)
#13 ee/ExpressionEngine/Addons/grid/libraries/Grid_lib.php(1099): Grid_parser->call('display_setting...', Array)
#14 ee/ExpressionEngine/Addons/grid/ft.grid.php(552): Grid_lib->get_settings_form('reinos_maps_fie...')
#15 ee/ExpressionEngine/Addons/grid/ft.file_grid.php(61): Grid_ft->getSettingsVars()
#16 ee/legacy/libraries/api/Api_channel_fields.php(410): file_grid_ft->display_settings(Array)
#17 ee/ExpressionEngine/Model/Content/FieldFacade.php(257): Api_channel_fields->apply('display_setting...', Array)
#18 ee/ExpressionEngine/Model/Content/FieldModel.php(72): ExpressionEngine\Model\Content\FieldFacade->getSettingsForm()
#19 ee/ExpressionEngine/Controller/Fields/Fields.php(624): ExpressionEngine\Model\Content\FieldModel->getSettingsForm()
#20 ee/ExpressionEngine/Controller/Fields/Fields.php(295): ExpressionEngine\Controller\Fields\Fields->form(Object(ExpressionEngine\Model\Channel\ChannelField))
#21 [internal function]: ExpressionEngine\Controller\Fields\Fields->create('2')
#22 ee/ExpressionEngine/Core/Core.php(268): call_user_func_array(Array, Array)
#23 ee/ExpressionEngine/Core/Core.php(118): ExpressionEngine\Core\Core->runController(Array)
#24 ee/ExpressionEngine/Boot/boot.php(160): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#25 html/sm-cp.php(154): require_once('...')
#25 html/sm-cp.php(154): require_once('...')

**Comment by intoeetive** [comment]
This error is originating from `Reinos\MapsFieldtype\Service\SettingsHelper->get_membergroups()` function. Please report it to the developer - or if there is more recent version, upgrade the add-on.

Having said that, in next beta we'll provide better error for cases like this reporting allowing people to easier identify the add-on that's causing issues
