### ISSUE TITLE
dialogue not opening to add file in File Manager > File Upload

### ISSUE THREAD

**Issue by frshjb373** [ExpressionEngine/ExpressionEngine#606]
Unless I'm missing something, the dialogue box, "Choose File" field is not opening a dialogue box when clicked from the File Manager. Tested in latest Chrome and Safari on Mac.

**Comment by intoeetive** [comment]
In the file manager, the "Choose File" dialog is a stand-alone page, not a popup. This is same behaviour that of EE5 and it has not been changed.

**Comment by frshjb373** [comment]
@intoeetive, attaching console screenshot.
![Uploading Screen Shot 2020-11-02 at 8.53.26 AM.png…]()

**Comment by ops-andy** [comment]
per screenshot, @frshjb373 is having an issue with the actual OS file selector not opening.

**Comment by frshjb373** [comment]
@ops-andy, confirmed it was a chrome ext. causing issue.
