### ISSUE TITLE
2x Fluid Field usability improvment feature requests:

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#614]
Feature Requests for Fluid Fields to improve UX:

1.  Add faster way to collapse individual fields - eg: add 'collapse' button alongside settings cog and + buttons or introduce double-click on sub-field titles to expand/collapse individual sub-fields (or both?!).  Right now there's a two-step process: click settings cog then click collapse - which is very cumbersome when trying to collapse a bunch, but not all.

2.  Always show the "+" / "Add Field" button so you can add sub-fields underneath even while collapsed.  Right now you have to expand a sub-field before you can add another sub-field below it.

**Comment by intoeetive** [comment]
Both issues have been addressed in EE7 Fluid field UI
