### ISSUE TITLE
File selection issue from a File Grid field inside a Fluid Field

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#615]
EE6.0.0-b3 has issues with a File Grid inside a Fluid Field:

Steps to replicate:
1. Setup a File Grid field and make that available to a Fluid Field and make that available to a channel
2. Edit an entry and try to either select an existing file (file manager does pop up, but does nothing) or upload a new one (error thrown & file not selected, but it does get uploaded)

Error shown in File Manager modal when uploading new image:
```{"file_id":20,"site_id":1,"title":"jellyfish.jpg","upload_location_id":8,"mime_type":"image\/jpeg","file_name":"jellyfish.jpg","file_size":73370,"description":"","credit":"","location":"","uploaded_by_member_id":1,"upload_date":1604682915,"modified_by_member_id":1,"modified_date":1604682915,"file_hw_original":"768 1024","path":"http:\/\/example.com\/images\/uploads\/jellyfish.jpg","thumb_path":"http:\/\/example.com\/images\/uploads\/_thumbs\/jellyfish.jpg","isImage":true,"isSVG":false}```

**Comment by intoeetive** [comment]
This has been fixed in 6.0.0
