### ISSUE TITLE
RTE Toolbar doesn't render from inside a Grid Field that's inside a Fluid Field

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#616]
In 6.0.0-b3, there's an issue with the RTE toolbar not rendering, but only when inside a Grid Field inside a Fluid Field:

![EE6 0 0-b3_RTE_inside_Grid_inside_Fluid](https://user-images.githubusercontent.com/8193519/98399092-29113280-201f-11eb-911d-1065a230ef2e.jpg)

I tested this with a standalone Rich Text field assigned both directly to the channel and as the only sub-field in my Test Fluid Field and everything worked fine there.

**Comment by ops-andy** [comment]
resolved in v6-beta4
