### ISSUE TITLE
After changing a field type from EEHarbor's "Assets" to "File" field type still showing Asset field in edit entry.

### ISSUE THREAD

**Issue by frshjb373** [ExpressionEngine/ExpressionEngine#618]
When creating a field and saving as Assets and then modifying that field and converting it back to a "File" field, the field is still an Assets field and dialogue box when adding a new image. 
![Screen Shot 2020-11-06 at 12 19 40 PM](https://user-images.githubusercontent.com/7178139/98411177-7515a480-202a-11eb-9037-dc8fa68cf23c.png)
![Screen Shot 2020-11-06 at 12 20 08 PM](https://user-images.githubusercontent.com/7178139/98411179-75ae3b00-202a-11eb-9772-2868dc41923e.png)

**Comment by ops-andy** [comment]
resolved in v6-beta4
