### ISSUE TITLE
Channels >  Publish Layouts save is required for new field to show in entry

### ISSUE THREAD

**Issue by frshjb373** [ExpressionEngine/ExpressionEngine#620]
After creating a new field and adding to a field group that's already selected in a channel, if a publish layout exists for that channel, you have to save the publish layout first before that new field shows in the entry. This wasn't the case in ee5 so not sure if this a bug or new behavior.

**Comment by frshjb373** [comment]
It was a text input field on a publish layout for "super admin" user group. I was logged in as super admin when creating the field and saving it to channel.

**Comment by ops-andy** [comment]
@frshjb373 I still can't replicate this. Is this happening consistently? can you see the attached screen recording and let me know if I'm trying to replicate this correctly? 
![field_issue](https://user-images.githubusercontent.com/55093827/98682261-b9a68600-2331-11eb-9193-3a7af4cbf03b.gif)

**Comment by intoeetive** [comment]
Closing as it has been 2 years since the report and received no further information
