### ISSUE TITLE
Control Panel Entries hover menu overflow

### ISSUE THREAD

**Issue by mladen-dordevic** [ExpressionEngine/ExpressionEngine#625]
In the Control Panel  hovering over "Entries" item in the lefthand side menu shows a quick channel list. This list does not scroll, so having 30+ channels, or small height window, it will cut off the top section of the list including the "View All" item. Scrolling moves the background instead of channel list.

EE 6.0.0-b.3

**Comment by intoeetive** [comment]
Thank you for the report. However I'm going to close this one, since we already have issue for this https://github.com/ExpressionEngine/ExpressionEngine/issues/572 , which we'll take care of.
