### ISSUE TITLE
Entries list sort_col param not preserved on the next page

### ISSUE THREAD

**Issue by mladen-dordevic** [ExpressionEngine/ExpressionEngine#626]
Control Panel listing Entries: when sorting by column other that Date, url param sort_col is not preserved when switching to the next page using pagination.

For example, sorting entries by entry_id will dynamically update url:
admin.php?/cp/publish/edit&search_in=titles_and_content&perpage=25&sort_col=column_entry_id&sort_dir=asc

but pagination url don't preserve that parameter.

EE 6.0.0-b.3

**Comment by intoeetive** [comment]
Fixed in [EE 6 beta 4](https://expressionengine.com/blog/expressionengine-6-beta-4)
