### ISSUE TITLE
Drop-down menus (select/options) not keyboard-friendly

### ISSUE THREAD

**Issue by Yvan256** [ExpressionEngine/ExpressionEngine#63]
All the drop-down menus in the control panel are not keyboard-friendly, i.e. you cannot navigate to a drop-down via [TAB].

The stylized drop-downs also take a lot more room and are harder to read as zebra-style lists.

It would be nice to have either a per-user setting or at least a system-wide setting to use regular HTML select/options.

**Comment by intoeetive** [comment]
As of EE6.0.3 I was able to successfully navigate over Entry Edit page that included several dropdowns. All were manupulatable wihout mouse.

Closing this issues as it seems to be not relevant anymore
