### ISSUE TITLE
MSM: Site Switcher does not redirect to the proper CP URL

### ISSUE THREAD

**Issue by rowansentesy** [ExpressionEngine/ExpressionEngine#638]
**Description of the problem**
When following the documentation here: https://docs.expressionengine.com/latest/msm/overview.html 
for a client EE install with 3 MSM sites, we noticed that there were some notable issues related to image uploads in entries not being shown or behaving properly due to cross-domain limitations. 
I went through the process of setting up the 'site_name' and 'cp_url' in the index.php and admin.php files as documented.
However, when I use the site switcher, I am unable to switch to the proper cp_url as defined in the above files. The site switcher appears to use session variables to switch sites, and when switching, the themes folders and base_path / base_url get messed up. 

I would expect that if explicitly provided, the switch_to site switcher should redirect the user to the full domain set in the cp_url.

**How To Reproduce**
Setup separate domains for different sites
Follow documentation, and add the 
```
$assign_to_config['site_name'] = 'domain2_short_name';
$assign_to_config['cp_url']    = 'http://domain2.com/admin.php';
```
Use site switcher, and domain remains the same, but site name changes.

**Error Messages**

```
Access to font at 'https://SITE2.com/themes/ee/asset/fonts/fontawesome-webfont.woff2' from origin 'https://SITE1.ca' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Environment Details:**
 - Version: 5.3.2
 - PHP Version 7.0.33-0ubuntu0.16.04.16
 - MySQL Version: mysqlnd 5.0.12-dev
 - OS: OSX & Chrome
 - Web Server: Linux cbk-droplet-1 4.4.0-193-generic #224-Ubuntu SMP
--

**Possible Solution**
Create a config override option to be set for the multiple sites instead of in the index.php & admin.php
If this is set, replace the ".nav-sites ul.nav-sub-menu li a" hrefs to be the full url including domain of the site if different from the current site. 

'$redirect = $member->getCPHomepageURL($site_id);'
https://github.com/ExpressionEngine/ExpressionEngine/blob/705dfbe6c06c7bc860d252940d7a09861f756369/system/ee/legacy/libraries/Cp.php#L1109

'getCPHomepageURL'
https://github.com/ExpressionEngine/ExpressionEngine/blob/705dfbe6c06c7bc860d252940d7a09861f756369/system/ee/EllisLab/ExpressionEngine/Model/Member/Member.php#L555

- add logic here to check for cp_url defined for provided site_id. 
- override the URLs of sites using the Config cp url, don't use the member or member group default

**Comment by robinsowell** [comment]
The site switcher has never been intended to actually switch the domain/base url when used.  As you note, it's setting a cookie and then using that to determine which site's info to show on the current base url.  We could consider that a feature request, though.  It's basically a different way of approaching site switching.  I know the developers have been looking into some alternatives, as there can be similar problems with live preview.

But for now, it's working as intended.  However, we really don't want resources blocked!  There are two ways to approach it.  One- just have the cp on one domain, don't put an admin.php everywhere, everyone has the same cp url and cp theme.  This is typically how I do it, but it doesn't work for every situation.

In cases where you really do want a cp on the different domains and still need switching the the cp, you're going to need allow access.  This article has a [good discussion](https://u.expressionengine.com/article/cross-origin-resource-sharing-cors) of how that might be done.
