### ISSUE TITLE
Error Uploading tiff Files in File Manager

### ISSUE THREAD

**Issue by jaredchesebro** [ExpressionEngine/ExpressionEngine#639]
### Description of the problem
Uploaded a tiff file in file manager and got an error.

### How To Reproduce
1. Try uploading a tiff image to a directory in file manager.

### Error Messages
```
Cannot Upload File
Thumbnail could not be created for the image. Please make sure the thumbnail directory is writable.
```

### Screenshots
**Error:**
![error](https://user-images.githubusercontent.com/21958491/99122141-a524f080-25b2-11eb-9114-658377272c9d.png)

**File Directory Settings:**
![settings](https://user-images.githubusercontent.com/21958491/99122150-a8b87780-25b2-11eb-996f-c66db1819c12.png)

**Thumbnail Generation Settings:**
![thumb-generation-settings](https://user-images.githubusercontent.com/21958491/99122338-ffbe4c80-25b2-11eb-805d-26292e6cc9c7.png)

### Environment Details
 - **Version:** 5.3.2
 - **PHP Version:** 7.3
 - **MySQL Version:** 5.7
 - **OS:** macOS Catalina
 - **Web Server:** Apache/MAMP

### Possible Solution
Upload tiff files without thumbnail generation similar to file mime types [e.g. zip, txt, pdf, etc]

### Additional Context
Using GD2 to generate thumbnails. Looking at [GD php documentation](https://www.php.net/manual/en/image.requirements.php) it seems like tiff is not supported. Also, have heard issue from someone else trying ImageMagick to generate thumbnails.

**Comment by intoeetive** [comment]
Thank you for the report. This will be fixed in EE6 RC1
