### ISSUE TITLE
Empty save in fields, channels, add-on settings

### ISSUE THREAD

**Issue by carolinecblaker** [ExpressionEngine/ExpressionEngine#642]
Env- new install on vagrant/homestead PHP 7.3

Control panel:
Saving existing entries, field preferences, channel preferences, and add-on settings have all yielded false saves - where I thought it saved, the system moved along like it saved, but I had to go back and re-make the same changes again, only to have it save finally the second time.

First:
Created new channel, channel did not exist. Once each for 2 channels.

Second:
Created new channel (second time per above,) had no fields. Added fields, which saved, but the channel did not save with those fields even though I hit save. Once each for 2 channels.

Third:
Added preferences to add-on that did not save, once.

Fourth:
Edited existing entry, edit did not save.

**Comment by ops-andy** [comment]
@carolinecblaker is this something that you can reproduce every time or does it randomly happen?

**Comment by intoeetive** [comment]
Will have to close it as we did not receive any further information
