### ISSUE TITLE
Show Entry Link on Entry and Entries listing 

### ISSUE THREAD

**Issue by avnerw** [ExpressionEngine/ExpressionEngine#645]
Problem: A content editor cannot easily access the published entry's link anywhere, neither on the Entry edit page, or on the Entries listing page. The Preview feature is great, but a direct link to the published link, if it exists publicly, will be a very nice  enhancement that is probably easy to implement.

Here are some screenshots of how this can be shown:

**Entry page before, without external link **:

![Screenshot 2020-11-17 at 10 04 27](https://user-images.githubusercontent.com/17215743/99367197-53d27500-28c2-11eb-8c82-572746cb6624.png)

**Entry page with external link**:

![Screenshot 2020-11-17 at 10 25 13](https://user-images.githubusercontent.com/17215743/99367249-6351be00-28c2-11eb-8080-4c7c9b2e1dcc.png)

**Entries listings**:

Showing link to published content if it exists
![Screenshot 2020-11-17 at 10 31 19](https://user-images.githubusercontent.com/17215743/99367338-81b7b980-28c2-11eb-98a4-60090cf633db.png)

**Comment by intoeetive** [comment]
While we can't reliably get entry URL using default setup (as preview URL could be different from actual URL for this entry) we can certainly get that info if Pages or Structure is installed
