### ISSUE TITLE
Image upload failure with error

### ISSUE THREAD

**Issue by tymrtn** [ExpressionEngine/ExpressionEngine#649]
**Description of the problem**
I recently upgraded from EE 1.x all the way to EE 5.32. Non-image files upload without issue, but when using the File Manager to upload images, I encounter a PHP library error and it fails to complete the upload:
<img width="961" alt="Screen Shot 2020-11-20 at 4 25 38 PM" src="https://user-images.githubusercontent.com/4305058/99819161-64e3e600-2b4f-11eb-8332-8e52b942e22e.png">

**How To Reproduce**
1. Go to File Manager
2. Verify Main Upload Directory is selected
3. Click Upload File
4. Select an image file and click Upload

**Error Messages**
<pre><code>Fatal error: Uncaught Error: Call to undefined method EE_Image_lib::image_process_() in ~/htdocs/system/ee/legacy/libraries/Image_lib.php:350 Stack trace: #0 ~/htdocs/system/ee/legacy/libraries/Filemanager.php(1386): EE_Image_lib->resize() #1 ~/htdocs/system/ee/legacy/libraries/Filemanager.php(411): Filemanager->create_thumb('~ap/...', Array) #2 ~/htdocs/system/ee/legacy/libraries/Filemanager.php(2117): Filemanager->save_file('~/ap...', 1, Array) #3 ~/htdocs/system/ee/legacy/libraries/Filemanager.php(1141): Filemanager->_upload_file(Array, 'file') #4 ~/htdocs/system/ee/EllisLab/ExpressionEngine/Service/File/Upload.php(299): Filemanager->upload_file('1', 'file') #5 ~/htdocs/system/ee/EllisLab/ExpressionEngine/Controller/Files/Files.php(138): EllisLab\ExpressionEngine\Service\File\Upload->uploadTo('1') #6 [internal function]: EllisLab\ExpressionEngine\Controller\Files\Fil in ~/htdocs/system/ee/legacy/libraries/Image_lib.php on line 350

</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 5.3.2
 - PHP Version 7
 - MySQL database (8.0.21)
 - OS: MacOSX Catalina
 - Web Server: Apache

**Possible Solution**

**Additional context**

**Comment by intoeetive** [comment]
@tymrtn please go to Settings -> Content & Design in the CP and select image resizing protocol that is used on your server. It looks like this setting "got lost" somewhere in the upgrade process.

**Comment by intoeetive** [comment]
@tymrtn I'm assuming the above fixed your problem, so closing this issue. If you still expirience the problem, please reopen it

**Comment by tymrtn** [comment]
Yes, that worked actually. Thanks!
