### ISSUE TITLE
Add drag and drop file upload to the File Manager

### ISSUE THREAD

**Issue by dankingsley** [ExpressionEngine/ExpressionEngine#65]
**Describe the solution you'd like**
The nice new drag and drop file upload is only available when adding or editing entries - I think it should also be part of the File Manager.

**Comment by jmathias** [comment]
Thanks Dan, We agree, and have plans for this, just not implemented yet.

**Comment by Yvan256** [comment]
In the meantime, you should be able to drag and drop files on the "Choose files" button itself since it's a built-in functionality of browsers.

**Comment by stasiup** [comment]
Should also work as File Field in the Channel Form. I would really need it.

**Comment by rmaclemale** [comment]
For us, this is most applicable for ADA 508 requirements for images.  My users LOVE having drag and drop upload of images available, but we use the file description field for alt, so it'd be nice to somehow include that in a field when people drag and drop files (especially images) inside a channel entry.  We do have a workaround.

**Comment by intoeetive** [comment]
This has been implemented for the new File Manager in ExpressionEngine 7
