### ISSUE TITLE
"Collapse" checkbox in Publish Layouts does not work

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#654]
I checked several "Collapse" checkboxes in Publish Layout, but that doesn't affect my entry form at all.

**Comment by shbchk** [comment]
One:
![1](https://user-images.githubusercontent.com/12234507/100088786-b9de6f80-2e61-11eb-82c1-00e9dbf7a206.png)

And two:
![2](https://user-images.githubusercontent.com/12234507/100088783-b945d900-2e61-11eb-9e55-bc1ff80d13a7.png)

**Comment by intoeetive** [comment]
This has been fixed in EE 6.0.0 release
