### ISSUE TITLE
Edit relationship field entries directly from a channel entry

### ISSUE THREAD

**Issue by acutedeveloper** [ExpressionEngine/ExpressionEngine#656]
**Is your feature request related to a problem? Please describe.**
To help improve workflow, for a relationship field, It would be useful to see a option to edit a relationship entry directly from the channel entry you are linking from.

**Describe the solution you'd like**
For there to be a button that will allow editing of a entry item within the relationship field next to the current delete button.

**Comment by intoeetive** [comment]
@ajohnson what do you think about this?

I think we could implement it similarly to how we do it when clicking "new entry" button in relationship selection dropout.

**Comment by ajohnson** [comment]
@intoeetive Good idea. I added this to the Core team's queue.
