### ISSUE TITLE
Unable to locate the model you have specified: rte_toolset_model in matrix field

### ISSUE THREAD

**Issue by tyssen** [ExpressionEngine/ExpressionEngine#657]
I'm just testing out the 6b4 upgrade on a local version of a site (running PHP 7.0) and so far things seem fine except when I try to edit a page that contains a matrix field with an RTE.

On an edit page that has one of those fields, the page renders (unstyled) until it reaches the matrix field and then there is:

> Unable to locate the model you have specified: rte_toolset_model

If I try and edit the field itself, I get the same message.

**Comment by intoeetive** [comment]
This is problem with Matrix, not EE. We will address it in the EE6-compatible Matrix version in the nearest future.
