### ISSUE TITLE
Scroll issue in the relation field when scrolling the web page.

### ISSUE THREAD

**Issue by Bhavin9898** [ExpressionEngine/ExpressionEngine#660]
When the relation field popup is opened then scroll the web page then that time relation field popup is also moving with page. I don't know this effect is right or wrong but if it is wrong then we should solve it.

Video is attached here.
[New Entry_ Contact _ ExpressionEngine.zip](https://github.com/ExpressionEngine/ExpressionEngine/files/5612061/New.Entry_.Contact._.ExpressionEngine.zip)

**Comment by ops-andy** [comment]
@Bhavin9898 apparently this is expected as all the other similar type menus behave the same way. thanks
