### ISSUE TITLE
Can not update Beta 3 to Beta 4 

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#662]
Hello!

All i see when i click the button is: 
_Updating EE6 from 6.0.0-b.3 to 6.0.0-b.4
Downloading update..._
And thats it.

PHP 7.1.33 / MySQL 5.6 

Here is the video: https://drive.google.com/file/d/1H71ZdLCbC--cefBEcQ6agSDfSi2C7W-y/view?usp=sharing

**Comment by intoeetive** [comment]
Sometimes download takes a while.
Can you try once again but having your browser dev console open and check if you get any error in there?

**Comment by shbchk** [comment]
Yes, it took a while, but finally updated. Thank you!
