### ISSUE TITLE
'Show Extra Publish Controls' channel setting should be removed

### ISSUE THREAD

**Issue by ricklecoat** [ExpressionEngine/ExpressionEngine#664]
**Description of the problem**
Not a bug really, just a leftover setting from earlier versions that is now redundant and should be removed from the CP UI, as it does nothing.

**How To Reproduce**
1. View a Channel's publishing form; it will have the usual array of green Save buttons (and maybe a blue Preview button) at the top and at the bottom.
2. In that Channel’s settings, toggle the 'Show Extra Publishing Controls' switch to the opposite setting of whatever is was set to.
3. Revisit the Channel's publishing form. There's no change. 
4. The switch in the Channel's settings is left over from EE3 or 4, but the conditional code that it controls (that hides or shows the extra publishing buttons) is apparently now gone, so extra publishing controls are always shown regardless of the setting switch's state. 

**Error Messages**
None

**Screenshots / Videos / Template Code**
None

**Environment Details:**
 EE 5.4 — However, judging from the conversation on Slack (see link below) this occurs, and would be expected to occur, on all environments.

**Additional context**
Slack thread: (https://eecms.slack.com/archives/C04CUNNR9/p1606663941018700)

**Comment by intoeetive** [comment]
Closing this, as the control is not present in EE6 and EE5 is only receiving security updates
