### ISSUE TITLE
Member roles CP access 'Access footer helper links' -> New Ticket Has no effect

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#667]
~Field "Access footer helper links" suggests "Choose which links this role can access in the CP footer." - EE6 doesn't have footer links.~

~Might need to update this to reflect the new UI and where these links can be found.~

Updated: New Ticket option under Cp Footer Links has no effect on Member Roles

**Comment by ops-andy** [comment]
We still have footer links in the sidebar footer that is affected by these options. However, I've noticed that the "New Ticket" option doesn't seem to affect anything.

With "New Ticket" selected:
![image](https://user-images.githubusercontent.com/55093827/101377188-82b78780-387f-11eb-8fde-0440058c0002.png)

Without "New Ticket" selected:
![image](https://user-images.githubusercontent.com/55093827/101377253-9662ee00-387f-11eb-9de5-bd67fb339670.png)

**Comment by intoeetive** [comment]
This has been fixed in EE 6.0.0
