### ISSUE TITLE
EE 6 RTE field enhancements

### ISSUE THREAD

**Issue by aasun** [ExpressionEngine/ExpressionEngine#669]
Two feature requests for the new RTE field in EE 6:

1. Add a "source" button to reveal the HTML source of the field contents to allow for custom HTML editing.

2. Add the ability to restrict the height of the field.  Otherwise, long text requires constant scrolling from mid/bottom back to top to be able to click the formatting buttons to apply formats.  It's virtually unusable like this.  Even with the height of the field set to 200 or 400, it does not limit to that height if the contents of the field are longer.

**Comment by OtherAliasNash** [comment]
I would back the: Add a "source" button to reveal the HTML source of the field. This has always featured in previous versions and other field types of this nature. Not an enhancement but a requirement from my perspective. Would really need the "source" button back....please :)

**Comment by intoeetive** [comment]
Unfortunately "view source" is not yet possible with CKEditor 5: https://github.com/ExpressionEngine/ExpressionEngine/issues/585

**Comment by pstalker-oxford** [comment]
Please do reinstate the </> 'view code' button. This was a critical function of versions 5 and earlier, particularly for checking for formatting errors. Now I feel I am working blind. I understand that this a consequence of upgrading to CKEditor 5. In EE could we have the option of reverting to CKEditor 4?

**Comment by intoeetive** [comment]
[Wygwam](https://eeharbor.com/wygwam) is built on CKEditor 4, so you may consider that

**Comment by pstalker-oxford** [comment]
Great suggestion. I had forgotten about Wygwam, which I see I last purchased in 2014. Thanks for your help.

**Comment by bron-yr-aur** [comment]
I've just installed EE6.0.3 for a new site build. Is there really no "view code" option in EE now? I was about to post a bug report because I couldn't get the code view to work (the button in the RTE is still there). This is a critical feature of any CMS for me and a huge disappointment if it is a functionality no longer available in a native installation of EE (which I've been using commercially since 2). Installing Wygwam is not much of a solution IMO.

**Comment by intoeetive** [comment]
While it is still not possible to have "view source" functionality in CKEditor 5, it now offers feature of inserting arbitrary HTML, which we believe will cover some people's needs.

It will be included in next release.
