### ISSUE TITLE
Problems with avatars

### ISSUE THREAD

**Issue by Yvan256** [ExpressionEngine/ExpressionEngine#67]
Problem #1: the avatar_width and avatar_height columns in the database are not added/updated when adding/modifying/removing an avatar.

Steps I tried:
1. picking an avatar from the default set
2. uploading my own avatar (PNG)
3. uploading my own avatar (GIF)
4. uploading my own avatar (I tried with both JPG and JPEG extensions)

In all four cases, the avatar_width and avatar_height values are never saved in the database and stay empty (NULL).

When inputing values manually into the database, the avatar_width and avatar_height variables work as they should in a template.

Problem #2: when deleting my avatar via the control panel, the avatar files on the server and the avatar_width and avatar_height columns in the database are not being deleted and still contain the values I added manually.

After my tests, the avatar directory has the following files in it:
avatar_1_1.png
avatar_1_2.png
avatar_1_3.png
avatar_1_4.png
avatar_1.gif
avatar_1.jpeg
avatar_1.png

And the "images/avatars/_thumbs" sub-directory has these files:
Yvan256.gif
Yvan256.jpeg
Yvan256.jpg
Yvan256.png

It would be nice if the system could remove the associated custom/uploaded avatar files from the server when a user's avatar is removed via the control panel.

Please note that I only tried these steps with myself (Super Admin).

System:
EE version 5.1.1
PHP version 7.0.33

**Comment by intoeetive** [comment]
Some of these are only relevant for EE5

The other ones will be fixed with https://github.com/ExpressionEngine/ExpressionEngine/pull/1685
