### ISSUE TITLE
Website online?

### ISSUE THREAD

**Issue by clif-ave** [ExpressionEngine/ExpressionEngine#670]
Settings => Website online? Always on regardless of changing. No error message, just success "Preferences updated". Noticed this with beta1 and continues to beta 4. Using current versions of chrome and firefox on current windows 10.

**Comment by intoeetive** [comment]
Please check whether you have this setting set as config override in `config.php` file.
In this case, even though the updated configuration is saved to the database, the convig override takes precedense and will be used. This is true for any setting that is available as config override.
