### ISSUE TITLE
RTE: URL to file_dir replacement

### ISSUE THREAD

**Issue by fccotech** [ExpressionEngine/ExpressionEngine#671]
EE 5.3.4 In the RTE addon, file ft.rte.php line 524 this is executed on the to-be-saved data: 

`$data = str_replace($d['url'], "{filedir_{$d['id']}}", $data);`

This wil replace an URL to a corresponding upload location filedir_ tag.

This pretty trivial,  what happens if an upload location has the URL "/" -> it will replace all HTML tags.

My suggestion would be to only replace url's with a full URL schema (http/https)

**Comment by ops-andy** [comment]
Just as a note, I was not able to replicate any issues in EE6 with the new RTE field. @fccotech if you get a chance, please test with the new 6.0-beta and let me know if you can still replicate the issue. If so, can you please provide some screenshots to help us replicate. thanks
