### ISSUE TITLE
[6.0.0-b.4] Entry bulk edit styles looks not accurate

### ISSUE THREAD

**Issue by MaxLazar** [ExpressionEngine/ExpressionEngine#673]
[6.0.0-b.4] Entry bulk edit styles looks not accurate
![image](https://user-images.githubusercontent.com/925802/101236348-90fa7d80-369e-11eb-8370-3bb654f32f80.png)

**Comment by PaulBaileyAtChan** [comment]
Can't help mentioning the clunkiness of "1 selected entries" and "Editing 1 entries", as well as the dodgy number agreement of "Any fields submitted will overwrite that field's stored content". Scope for lots of copy-editing polish here.
