### ISSUE TITLE
CP Categories Manager - UI Style Issue

### ISSUE THREAD

**Issue by stephengalbraith** [ExpressionEngine/ExpressionEngine#675]
When adding categories to parents, left padding seems to be missing on children of parent categories.

<img width="257" alt="Screen Shot 2020-12-05 at 5 07 45 PM" src="https://user-images.githubusercontent.com/45797159/101266408-8c74aa00-371c-11eb-8145-193f56ec1bcb.png">

EDIT: then on Entries Manager, padding is needed between the category options and Add Category button (grey line hits directly on top of button)

<img width="323" alt="Screen Shot 2020-12-05 at 5 11 51 PM" src="https://user-images.githubusercontent.com/45797159/101266448-fd1bc680-371c-11eb-8fc1-8e61e1400a1b.png">

EE 6.0.0-b.4

**Comment by TomJaeger** [comment]
FYI Fix for this has been merged into release 6.0.0 branch
