### ISSUE TITLE
Crop type in Image Manipulation issue

### ISSUE THREAD

**Issue by helmi-pts** [ExpressionEngine/ExpressionEngine#676]
I tested EE6 beta 4 by upgrading from EE5.4.

If I already have an existing Crop type settings in Files, {my_image:crop} will output cropped but not resized image. Updating the crop value and resyncing the folder doesn't seem to have any effect.

To mitigate this, create another Crop type setting and {my_image:crop_2} will output the image correctly. (which is cropped and resized).

**Comment by intoeetive** [comment]
This has been fixed in EE 6.0.0 release
