### ISSUE TITLE
EE6: Add member_group id parameter in Registration Form Tag

### ISSUE THREAD

**Issue by helmi-pts** [ExpressionEngine/ExpressionEngine#677]
This request is not part of a problem or bug, but rather a nice thing to have.

**Describe the solution you'd like**
It would be nice and practical to have something like

`{exp:member:registration_form member_group="12"}`

so that we can control which member group a user can register to on the frontend. For example, we can have a customer registration form page and also a supplier registration form page.

**Comment by intoeetive** [comment]
This is possible as of now by using `primary_role` parameter
