### ISSUE TITLE
XID constant not generating in chrome.

### ISSUE THREAD

**Issue by jude-lobo** [ExpressionEngine/ExpressionEngine#678]
**Description of the problem**
I have created a custom addon, in which there are forms. The `<input type="hidden" name="XID" value="{XID_HASH}" />` input field does not generate the XID token in the DOM, so when submitting the form it gives the usual "This form has expired" error.

This issue however only occurs in Chrome, works fine on Firefox.

**How To Reproduce**

1. Create a form, with the above mentioned XID field.
2. Submit the form in chrome.

**Error Messages**
"This form has expired, please refresh and try again."

**Environment Details:**
 - Version: 5.3.2
 - PHP Version 7.3.13
 - MySQL Version  : 5.7.24
 - OS: Windows.
 - Web Server: Apache

**Comment by ops-andy** [comment]
@Instabash can you share your add-on code that generates the form? I'm not able to replicate in Chrome on EE 5.3.2
![image](https://user-images.githubusercontent.com/55093827/101487374-1777bf00-392c-11eb-99c8-05155bebcbee.png)

**Comment by jude-lobo** [comment]
> @Instabash can you share your add-on code that generates the form? I'm not able to replicate in Chrome on EE 5.3.2
> ![image](https://user-images.githubusercontent.com/55093827/101487374-1777bf00-392c-11eb-99c8-05155bebcbee.png)

OK, this is the code that is used in the .mcp file:

```
public function add_city()
{
    return $this->show_view($view = 'add_city', $withSidebar = true);
}
private function show_view($view = 'index', $withSidebar = true, $viewData = [])
{
    if ($withSidebar) {
        $this->sidebar();
    }
    return ee('View')->make($this->moduleName . ':' . $view)->render($viewData);
}
```

And this is the html in my view file:
```
<form action="<?php echo ee('CP/URL', 'addons/settings/form_module/add_city_submit'); ?>" method="post">
     <div class="form-group">
          <label for="exampleFormControlInput1">City Name</label>
          <input name="city_name" autocomplete="off" required type="text" class="form-control" id="city_name" />
      </div>
      <input type="hidden" id="xid" name="XID" value="{XID_HASH}" />
      <br>
      <button type="submit" id="formSubmitBtn" class="btn btn-primary">Submit</button>
</form>
```

**Comment by intoeetive** [comment]
`{XID_HASH}` is the variable for EE template engine, it is not supposed to be parsed by View service.

You can get current token using `ee()->csrf->get_user_token()` however for CP requests this is not needed at all, all security checks are being handled automatically.
