### ISSUE TITLE
[6.0.0-rc.1] Current avatar is erased if Save Setting and do not choose a new avatar file in CP profile

### ISSUE THREAD

**Issue by MaxLazar** [ExpressionEngine/ExpressionEngine#679]
[6.0.0-rc.1] Current avatar is erased if Save Setting and do not choose a new avatar file in CP profile 

MacOs, Chrome 86.0.4240.198, PHP 7.3.8

![1208215153cstj2](https://user-images.githubusercontent.com/925802/101567921-bb4e8280-399f-11eb-84d2-d9d5626e431c.gif)

**Comment by intoeetive** [comment]
This has been fixed in EE 6.0.0 release
