### ISSUE TITLE
EE 6 Grid JS is doing weird things to my field type markup

### ISSUE THREAD

**Issue by tjdraper** [ExpressionEngine/ExpressionEngine#680]
When using Ansel in a grid field in EE6, EE appears to be doing strange things to the markup of my field. My field uses tables and my suspicion is that EE6's grid JS is being way too broad with its selectors and selecting the markup in my field type as well as its own when adding rows etc. We've actually had similar problems to this before and Kevin Cupp got to the bottom of it and fixed it in EE's grid JS back in the day.

Since it can be a difficult issue to describe and debug (and believe me, I've spent hours coming over the code and debugging and trying to make sure it wasn't something I was doing wrong), I've recorded a video of what's going on which you can view here: https://vimeo.com/488780813/22310e57c0

**Comment by intoeetive** [comment]
This has been fixed in EE 6.0.0

**Comment by tjdraper** [comment]
Confirmed.
