### ISSUE TITLE
"Save Template Revisions" label inconsistency

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#682]
I've noticed an inconsistency in the template revisions settings:
![upto5](https://user-images.githubusercontent.com/12234507/101680626-046f0700-3a72-11eb-94cd-d2cea9b9e414.png)

**Comment by intoeetive** [comment]
This already has been addressed in `6.dev` branch: 
![image](https://user-images.githubusercontent.com/752126/126301605-49e55da7-4958-4b31-a5c0-f90f76c5defb.png)
