### ISSUE TITLE
"Website online?" Yes, and i can't change this

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#686]
I'm kind of surprised that i will be the first to report this. 
[See for yourself](https://drive.google.com/file/d/1l9iE1bHZRXiDV3cCK2yjNVfxjgY0cqlI/view?usp=sharing)

_rc1
PHP Version 7.1.33
MySQL 5.6_

**Comment by TomJaeger** [comment]
Thanks for submitting this, along with the video.

Any chance you can confirm it's not set in your config file (and that the config file has permissions to be written from PHP)?

Running a series of tests locally as well.

**Comment by shbchk** [comment]
$config['is_system_on'] = 'y';
config.php is set to 644

**Comment by ops-andy** [comment]
we've confirmed this now. The config item is being set during the 1-click update.

**Comment by dougblackjr** [comment]
@shbchk Was this an upgrade from a previous version?

**Comment by shbchk** [comment]
Yep. From Beta 4.

**Comment by dougblackjr** [comment]
@shbchk Did you have the `$config['is_system_on'] ` set to `'y'` when you ran the upgrade? Just wanted to check if this was adding this to the config during the upgrade process

**Comment by shbchk** [comment]
I'm not sure about this particular update, sorry. Maybe it was set with previous update from beta 3 to beta 4.

But i know for a fact that i didn't set it in config.php in the first place, always used toggle in CP

**Comment by dougblackjr** [comment]
@shbchk It looks like this behavior was removed in EE6. Was this an upgrade from an EE5 or earlier version?

**Comment by shbchk** [comment]
No, it was clean EE6 install at the beginning
