### ISSUE TITLE
Cannot Create New Entries in 2 Channels (losing the Channel in the Entry Form)

### ISSUE THREAD

**Issue by mightywiley** [ExpressionEngine/ExpressionEngine#687]
**Description of the problem**

I've been creating entries in the two affected Channels for several months without a problem. Several days ago I began hitting an error on Submit with two Channels. Apparently the "Channel" parameter is lost. On the Options tab there is no Channel below the words "Channel this entry should be submitted to." 

**How To Reproduce**
1. In the CP choose 'Create' and then select one of the two affected Channels
2. Click on the Options tab to see the missing Channel 
3. Additionally, you can fill in the required fields and click Submit, at which point the Options tab turns red and reads "This field is required." below "Channel this entry should be submitted to."

**Error Messages**
<pre><code>This field is required.</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 5.1.2
 - PHP Version 7.1
 - MySQL Version 5.6
 - OS: Linux
 - Web Server: nginx

**Possible Solution**
n/a

**Additional context**
At the same time these Channels lost their 'Create' ability, two Statuses went missing. I've since manually added-back the Statuses. I have confirmed that no Member/Super Admin deleted the Statuses.

![error](https://user-images.githubusercontent.com/75496223/101803984-1cc93b00-3adf-11eb-96e8-daf183eebff9.png)
![missing-channel](https://user-images.githubusercontent.com/75496223/101804004-218def00-3adf-11eb-867b-a389c1e5eed2.png)

**Comment by ops-andy** [comment]
this was resolved in 6.0.3
