### ISSUE TITLE
CSS templates transferred with MIME type text/html

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#688]
Just noticed a warning in Chrome Console:

> Resource interpreted as Stylesheet but transferred with MIME type text/html: "url_here".

Using CSS templates, linking them as CSS:
`<link rel="stylesheet" type="text/css" media="all" href="{stylesheet='template_group/css_template'}" />`

Those CSS templates is set to CSS type.

_rc1
PHP Version 7.1.33
MySQL 5.6_

**Comment by shbchk** [comment]
By the way, manual describes only CSS templates. What about linking other types — JS, for example?

**Comment by shbchk** [comment]
If i link CSS template without {stylesheet} variable, MIME warning doesn't appear.
`<link rel="stylesheet" type="text/css" media="all" href="/template_group/css_template" />`

**Comment by intoeetive** [comment]
I'm not getting this error in Chrome 87. Could it be that you have some rules on server side (globally or in .htaccess), or load balancer, that's messing the headers?
`/index.php?css=site/style.v.1607676746` and `index.php/site/style` are both served with header
`Content-Type: text/css;charset=UTF-8`

**Comment by shbchk** [comment]
You should try to embed it in a template with {stylesheet='template_group/css_template'} variable, not accessing it directly

**Comment by intoeetive** [comment]
Exactly what I did.
Is this any different from what you had?
```
<link rel="stylesheet" type="text/css" media="all" href="{stylesheet='site/style'}" />
<link rel="stylesheet" type="text/css" media="all" href="{path='site/style'}" />
```

**Comment by shbchk** [comment]
I have a very standard virtual hosting, and i believe there is nothing can mess with the headers.
[Here](https://drive.google.com/file/d/171lwbhzu0M_zov5aL71vwYMJjuf2E7Y7/view?usp=sharing) is the screencast

**Comment by intoeetive** [comment]
Thank you for the screencast - I was able to replicate this when using hidden template (prefixed with `_`)

**Comment by intoeetive** [comment]
Upon some investigation, I am going to classify this as "not a bug".

Since the template is hidden, it should not be accessible with a direct link or via `{path=}` variable. The default template (or 404) is served, and it has content type of `text/html`

It is also correct that hidden templates are still available with `{stylesheet=}` tag, as it's processing things differently.

https://docs.expressionengine.com/latest/templates/overview.html#hidden-templates

**Comment by shbchk** [comment]
But template is not hidden — underscore was in template_group name, not template itself. 

Anyway, after renaming template_group from '_css' to 'css-group' the issue still here. 

UPD: [new screencast](https://drive.google.com/file/d/1fFOV8g4fw3QwSJ2juqL89v8a46yZm6cJ/view?usp=sharing)

**Comment by intoeetive** [comment]
Can you try opening the link that Chrome is showing you in the new tab? I noticed you have a rule for `index.php` removal and my suspect is that it does not respect `?css=` in URL

**Comment by shbchk** [comment]
.htaccess:
https://paste.ofcode.org/sBGR2RMgWaTCku3DEtg3hW   

When i open that link in the new tab, nothing happens. I mean there is no warnings and content-type is correct text/css;charset=UTF-8.

**Comment by intoeetive** [comment]
So you do get correct file contents when opening in new tab?
What if you remove/disable `.htaccess` - do you still get that error?

**Comment by shbchk** [comment]
My hosting provider went down, so I made clean install on different server. And you are right — the problem lies with the htaccess file. 

I got it from EE installation manual: https://docs.expressionengine.com/v6/installation/best-practices.html#removing-indexphp-from-your-urls

So maybe it needs some editing?

**Comment by shbchk** [comment]
Grand Finale:
> In the Control Panel, go to Settings --> URL and Path Settings, set Website index page to blank (empty), and click Submit.

It did the trick, no more console warnings.

Thanks all :)
