### ISSUE TITLE
File Grid validation fails after removing image

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#690]
You can save an entry without image if it was removed from file grid. Validation fails in this case.
![screenshot](https://user-images.githubusercontent.com/12234507/101896337-e90f1380-3bb9-11eb-9aeb-1332b33d5663.png)

**Comment by ops-andy** [comment]
confirmed this seems to be a bigger issue with File grid validation. I was able to set the minimum rows 1 in the field, yet an entry saved successfully with 0 rows being added.
