### ISSUE TITLE
File Grid Upload Times Out - Only Uploads Five Images

### ISSUE THREAD

**Issue by mcfarlandonline** [ExpressionEngine/ExpressionEngine#693]
EE 6.0.0-rc.1
PHP Version 7.4.13
10.3.27-MariaDB

I have a File Grid field within a Fluid Field. When I try to bulk upload images to this File Grid field, it times out after uploading 5 images, and shows no more progress on the 6th image onward. The File Grid field also doesn't error-out or save the 5 images that finished uploading. I then have to reload the entry page and manually insert the 5 images that finished uploading. 

This wasn't an issue for me in EE 5 for me, (I could bulk upload 100+ photos in a single drag-and-drop), and I haven't changed any settings with the File Grid upload field. I've also re-checked my PHP settings and maxed out on upload/time/memory settings. (See screenshot below). Also, all of these images I'm trying to upload are under 700KB.

Any ideas?
![screenshot](https://user-images.githubusercontent.com/20441129/102040046-6dab8e80-3d80-11eb-888c-322290078cc4.png)

**Comment by ops-andy** [comment]
Thanks for reporting. I've been able to replicate this.

**Comment by intoeetive** [comment]
This seems to happen with any File Grid on drag&drop upload, not isolated to Fluid

**Comment by ops-andy** [comment]
fixed in 6.0.1
