### ISSUE TITLE
Add Option To Stack Fields Inside Grid Row

### ISSUE THREAD

**Issue by jaredchesebro** [ExpressionEngine/ExpressionEngine#694]
**Is your feature request related to a problem? Please describe.**
The grid UI is degraded when user has added more than 3 - 4 fields in a grid field. When using a screen sized between tablet and laptop the lack of a horizontal scrollbar is also an issue.

![Screen Shot 2020-12-14 at 4 11 54 PM](https://user-images.githubusercontent.com/21958491/102151461-cc781300-3e27-11eb-81bd-e085951fc70c.png)

**Describe the solution you'd like**
Either permanently change the grid UI to stacked fields or add an option to grid fields that would allow the developer to decide whether the fields stack or display in row similar to how the grid currently displays on mobile. If displayed in row add horizontal scrollbar.

Here's a video example of stacked:
https://youtu.be/GUM54p8jCeQ

**Teachability, Documentation, Adoption, Migration Strategy**
The feature would be applied based on the options the user selected when creating their grid field.

**Comment by avnerw** [comment]
I experienced this as well. Working on an 12.9" iPad Pro, a Grid Field with more than 4 columns that goes beyond the margins of the normal CP layout becomes annoying. So I used the [MX CP CSS & JS Addon](https://expressionengine.com/add-ons/mx-cp-css-js) by Max Lazar to change the CSS breakpoint of 768px for Grid Fields to a higher value.  But an option settings would probably be the better way to handle this UI issue.

**Comment by blairliikala** [comment]
I like everything about this idea.

**Comment by mustafa-online** [comment]
That would be great 🥇 

@jaredchesebro , Can you share your code please? I need it

**Comment by dankingsley** [comment]
Yes please! It would be great to have the option to set vertical or horizontal when creating a grid field - it's a constant frustration for my clients, and would be a pretty simple fix I expect (since it already stacks on mobile).

**Comment by troxellwebdesign** [comment]
Agree this option would be great, a vast improvement!!!

**Comment by brentcwilson** [comment]
Adding my support to this request. The horizontal squishing of fields significantly degrades the authoring experience, and thus detracts from the usability of Grid fields.

**Comment by TomJaeger** [comment]
Figure I'll just drop this here.... Coming in V7
![Screen Shot 2022-07-14 at 12 50 31 PM](https://user-images.githubusercontent.com/422821/179036625-bcfa399e-5732-4e68-8209-d896deca05a7.png)

**Comment by brentcwilson** [comment]
I appreciate the update, @TomJaeger!
