### ISSUE TITLE
RTE field Heading 1, Heading 2, Heading 3 output the wrong tags

### ISSUE THREAD

**Issue by aasun** [ExpressionEngine/ExpressionEngine#695]
While editing with the RTE field in the EE CP, choosing Heading 1 outputs an <h2> tag on the template.  Heading 2 outputs an <h3> tag, and Heading 3 outputs an <h4> tag.

No errors are produced, just the wrong tags are used.  That paragraph style dropdown only shows headings 1, 2, and 3 options.

I can see where this is happening in the CK editor library.
/themes/ee/rte/scripts/ckeditor.js 

Line 5, character 706085 starting with the "ck-heading-paragraph" you can see heading1 uses h2, heading2 uses h3, and heading3 uses h4.

**Comment by intoeetive** [comment]
This behavior is default as provided by CKEditor 5. We did not change that, as it looks like their team had strong reasons to do it that way - unless EE community makes us think otherwise.

**Comment by pyrobob83** [comment]
I understand not allowing H1 tags in an RTE since you should only ever have one per page and you can use either the entry Title or a custom text field for that... but to call an H2 "Heading 1" doesn't make sense to me at all.  Can we customize this somewhere that's not hacking the core files?

**Comment by ops-andy** [comment]
fixed in 6.0.1
