### ISSUE TITLE
Login with email for login form

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#700]
For some applications, a username doesn't make sense. Also, some people prefer to login with an email.
It will be great to have this option for login form.

**Comment by VarenSwaab** [comment]
I agree, it also makes for better options when using a social login service. I'd like to see this feature too.

**Comment by shbchk** [comment]
Giving only one choice (username and not email) is kind of outdated website behaviour, i agree. It needs updating, preferably along with the social sign-ins :)
