### ISSUE TITLE
Cannot search files from the entry file picker

### ISSUE THREAD

**Issue by acutedeveloper** [ExpressionEngine/ExpressionEngine#702]
When I am editing a entry that has a file field type. I am unable to search files that have been uploaded.

**Version of EE**
6.0.0

**Steps to reproduce**
Ensure you have uploaded files. Duh! On a entry file field click "Choose from existing". In the modals search field, type a known term.

**Expected behaviour**
When a term is entered the list should show a list of filtered results.

**Actual behaviour**
Nothing!

<img width="999" alt="Screenshot 2020-12-19 at 17 49 55" src="https://user-images.githubusercontent.com/2130276/102699803-aabfc700-423f-11eb-81c0-499a2ae6a095.png">

**Comment by intoeetive** [comment]
This has worked well on my test.
@acutedeveloper can you confirm you have pressed `Enter` upon entering the search term? If you did, was there any kind of javascript error in browser's console?

**Comment by DalizPR** [comment]
I came across the same issue, only when using Safari on a mac. Just updatet to 6.0.4 issue is still there.
Console is empty.

Issue occurs in the file fields aswell as the File Manager.
![Schermafbeelding 2021-05-20 om 15 56 29](https://user-images.githubusercontent.com/19518007/118991431-07a4e200-b984-11eb-804d-a2d61659d19d.png)

**Comment by ops-andy** [comment]
@acutedeveloper  if you have a chance, can you please checkout Yulya's branch here: https://github.com/Yulyaswan/ExpressionEngine/tree/feature/6.x/search-in-safari and see if that resolves your Safari issues. 
thanks
