### ISSUE TITLE
Adding a comment FORM to a channel does not work

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#704]
not matters the settings of a channel, always this message displayed

"Commenting is not available in this channel entry."  
(commenting is enabled for the channel)

I even enabled Comments for the members role.

**Comment by intoeetive** [comment]
I have not been able to replicate this.

Note that this might be affected with "Comment expiration" setting for channel.

If you are positive this is related to a bug in EE, please provide more details on how to replicate it.

**Comment by digicali** [comment]
Comments are enabled for the site
Comments are enabled for the channel
Comments are enabled for the Members role
What else to check?

**Comment by intoeetive** [comment]
In your Channel preferences, look for "Comment expiration" - it it's set and entry is "too old", the comments will not be accepted

**Comment by digicali** [comment]
The settings was at 0 by default, removing it = still the same

**Comment by digicali** [comment]
It's actually always coming back to 0

**Comment by digicali** [comment]
Precision : the channel is displayed on a site B and created on site A with the correct tag site="'

**Comment by digicali** [comment]
Code 
`{exp:comment:form channel="ch_tickets" site="sitename" return="tickets" entry_id="{segment_2}"}`

**Comment by intoeetive** [comment]
If you add to the tempate (within your `exp:comment:form` tag) following tags, what do you see?
`{if comments_expired}comments_expired{/if}`
`{if comments_disabled}comments_disabled{/if}`
`{comment_expiration_date}`

And also within`{exp:channel:entries}` tag
`{comment_expiration_date}`

**Comment by digicali** [comment]
For channel, nothing is displayed
For comments section: comments_disabled is displayed.

**Comment by digicali** [comment]
I fixed the issue. I had to enable commenting for site B. Sorry for the report but not obvious that you need to enable comments on a site B if a channel and comments are managed by site A

**Comment by intoeetive** [comment]
Good, glad to hear you have it working now.
