### ISSUE TITLE
Detecting addons with old members management

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#706]
If an addon is installed with previous member management, the option to install it should be disabled
with a warning message to upgrade to a recent version.
Same when you upgrade a site from ee5 to ee6, all addons having old members management should be disabled before the upgrade.
otherwise, I have the feeling it can create a mess.
By installing Simple Registration addon, I already experimented an issue.

**Comment by intoeetive** [comment]
Unfortunately we don't see a solution that would be both working and not return false positive / false negative results.

If you have any suggestions for the actual algorythm that you could share, please do so.

**Comment by digicali** [comment]
I will recommend a big change like adding a setting to addon to make them ee6 compliant. It EE6 is a new big start, it make sense for better reliability. When, you upgrade a site, you should also disable all addons before applying the update. wordpress was a mess in the past because of this kind of problem.

**Comment by intoeetive** [comment]
Considering the time that has passed since EE6 with the Roles system has been released, we can close this issue
