### ISSUE TITLE
CP Templates No Longer Syncing with Database

### ISSUE THREAD

**Issue by nickpuglisi** [ExpressionEngine/ExpressionEngine#707]
Since upgrading to EE6 (worked fine in EE5+), the template manager in CP no longer syncs, and is showing an almost cached version of my templates.

The template files, which are saved as files, are still showing old revisions and NOT what is in the Control Panel. Something as easy as on my domain I have a blank folder called /dev/ and I wrote "hello" (no formatting or HTML) and it shows active in the CP, but on the frontend shows the old code. 

EE6.0.0 / Ubantu / php 7.4.3 / mySQL 8.0.22

**Comment by intoeetive** [comment]
So just to confirm, you can see the same content in CP and in template file, but not on site front-end pages?

Can you try clearing your caches? And does the content still remain unsynchronized after you hit "save template" in CP?

Lastly, are you by chance using some load balancer or CDN?

**Comment by nickpuglisi** [comment]
Hey @intoeetive - Basically I save the content in CP, and it saves to the database but does not update (or read) the file located in system/user/templates. Those are almost frozen in time... 

Yes, I cleared all EE caches, and my browser/DHCP cache. 

I'm using BitBucket, no load balancer. My gitignore does not have any EE customizations.

**Comment by intoeetive** [comment]
So is your site actually hosted with BitBucket?

On tranditional hostings, I would suggest to check directory/file permissions, however I'm not sure what is the corresponding act on BitBucket. I would think that since the directory is not gitignored, BitBucket prevents your app (EE) from writing to it, but that's purely my guess.

I would suggest that you investigate this on BitBucket front (or open support ticket with them) and if there will be any important information then update this issue.

At this point, there is no sufficient information to replicate (or even confirm) this bug, but I'm keeping the issue open for further details.

**Comment by nickpuglisi** [comment]
No, it's hosted in a DigitalOcean droplet. I checked file permissions and the folder is chmod 777'ed, so that shouldn't be an issue? I can certainly add it to gitignore and see if it works.

**Comment by intoeetive** [comment]
Unless you have auto-deploy running like every minute, not having folder in gitignore shouldn't be an issue

Does the system work vice versa, e.g. if you update the file, you can see the changes reflected in control panel.

Also, can you clarify this: "I have a blank folder called /dev/" - do you refer to template group in CP or anything else?

And just in case, double check that you don't have `save_tmpl_files` set to `n` in your `config.php`

**Comment by nickpuglisi** [comment]
I have `save_tmpl_files` set to y in config. 

Yeah, gitignore did nothing. 

For reference – 

/dev/ is just a template folder, I edited /dev/index/ from the Control Panel, and it's showing some very old version of the code (from like weeks ago).

**Comment by nickpuglisi** [comment]
Also confirmed all files/folders in /user/templates are 777.

**Comment by intoeetive** [comment]
What's the full path to the folder you are checking?

**Comment by nickpuglisi** [comment]
Was able to find the issue; when upgrading to EE6, I had to force the push from Bit to sync the new files back (since the upgrade occurred on the server and not locally... which it _should_ have). In doing so, it reset ALL file permissions, including the directories being properly 777'ed but not the html files within :-|
