### ISSUE TITLE
SQLSTATE[HY000]: General error: 1116 Too many tables; MySQL can only use 61 tables in a join:

### ISSUE THREAD

**Issue by CharlottesvilleMedia** [ExpressionEngine/ExpressionEngine#708]
Just upgraded 5.4 to 6.0 and getting this when trying to load site index:

SQLSTATE[HY000]: General error: 1116 Too many tables; MySQL can only use 61 tables in a join:
SELECT t.entry_id, t.channel_id, t.forum_topic_id, t.author_id, t.ip_address, t.title, t.url_title, t.status, t.view_count_one, t.view_count_two, t.view_count_three, t.view_count_four, t.allow_comments, t.comment_expiration_date, t.sticky, t.entry_date, t.year, t.month, t.day, t.edit_date, t.expiration_date, t.recent_comment_date, t.comment_total, t.site_id as entry_site_id, w.channel_title, w.channel_name, w.channel_url, w.comment_url, w.comment_moderate, w.channel_html_formatting, w.channel_allow_img_urls, w.channel_auto_link_urls, w.comment_system_enabled, m.username, m.email, m.screen_name, m.signature, m.sig_img_filename, m.sig_img_width, m.sig_img_height, m.avatar_filename, m.avatar_width, m.avatar_height, m.photo_filename, m.photo_width, m.photo_height, m.role_id, m.member_id, wd.*, md.* , exp_member_data_field_1.*, exp_member_data_field_2.*, exp_member_data_field_3.*, exp_member_data_field_4.*, exp_member_data_field_5.*, exp_member_data_field_6.*, exp_member_data_field_8.*, exp_channel_data_field_9.field_id_9, exp_channel_data_field_9.field_ft_9, exp_channel_data_field_10.field_id_10, exp_channel_data_field_10.field_ft_10, exp_channel_data_field_11.field_id_11, exp_channel_data_field_11.field_ft_11, exp_channel_data_field_12.field_id_12, exp_channel_data_field_12.field_ft_12, exp_channel_data_field_13.field_id_13, exp_channel_data_field_13.field_ft_13, exp_channel_data_field_14.field_id_14, exp_channel_data_field_14.field_ft_14, exp_channel_data_field_15.field_id_15, exp_channel_data_field_15.field_ft_15, exp_channel_data_field_16.field_id_16, exp_channel_data_field_16.field_ft_16, exp_channel_data_field_17.field_id_17, exp_channel_data_field_17.field_ft_17, exp_channel_data_field_18.field_id_18, exp_channel_data_field_18.field_ft_18, exp_channel_data_field_19.field_id_19, exp_channel_data_field_19.field_ft_19, exp_channel_data_field_20.field_id_20, exp_channel_data_field_20.field_ft_20, exp_channel_data_field_21.field_id_21, exp_channel_data_field_21.field_ft_21, exp_channel_data_field_22.field_id_22, exp_channel_data_field_22.field_ft_22, exp_channel_data_field_23.field_id_23, exp_channel_data_field_23.field_ft_23, exp_channel_data_field_24.field_id_24, exp_channel_data_field_24.field_ft_24, exp_channel_data_field_25.field_id_25, exp_channel_data_field_25.field_ft_25, exp_channel_data_field_26.field_id_26, exp_channel_data_field_26.field_ft_26, exp_channel_data_field_27.field_id_27, exp_channel_data_field_27.field_ft_27, exp_channel_data_field_28.field_id_28, exp_channel_data_field_28.field_ft_28, exp_channel_data_field_29.field_id_29, exp_channel_data_field_29.field_ft_29, exp_channel_data_field_30.field_id_30, exp_channel_data_field_30.field_ft_30, exp_channel_data_field_31.field_id_31, exp_channel_data_field_31.field_ft_31, exp_channel_data_field_32.field_id_32, exp_channel_data_field_32.field_ft_32, exp_channel_data_field_33.field_id_33, exp_channel_data_field_33.field_ft_33, exp_channel_data_field_34.field_id_34, exp_channel_data_field_34.field_ft_34, exp_channel_data_field_35.field_id_35, exp_channel_data_field_35.field_ft_35, exp_channel_data_field_36.field_id_36, exp_channel_data_field_36.field_ft_36, exp_channel_data_field_37.field_id_37, exp_channel_data_field_37.field_ft_37, exp_channel_data_field_38.field_id_38, exp_channel_data_field_38.field_ft_38, exp_channel_data_field_39.field_id_39, exp_channel_data_field_39.field_ft_39, exp_channel_data_field_40.field_id_40, exp_channel_data_field_40.field_ft_40, exp_channel_data_field_41.field_id_41, exp_channel_data_field_41.field_ft_41, exp_channel_data_field_42.field_id_42, exp_channel_data_field_42.field_ft_42, exp_channel_data_field_43.field_id_43, exp_channel_data_field_43.field_ft_43, exp_channel_data_field_44.field_id_44, exp_channel_data_field_44.field_ft_44, exp_channel_data_field_45.field_id_45, exp_channel_data_field_45.field_ft_45, exp_channel_data_field_46.field_id_46, exp_channel_data_field_46.field_ft_46, exp_channel_data_field_47.field_id_47, exp_channel_data_field_47.field_ft_47, exp_channel_data_field_48.field_id_48, exp_channel_data_field_48.field_ft_48, exp_channel_data_field_49.field_id_49, exp_channel_data_field_49.field_ft_49, exp_channel_data_field_50.field_id_50, exp_channel_data_field_50.field_ft_50, exp_channel_data_field_51.field_id_51, exp_channel_data_field_51.field_ft_51, exp_channel_data_field_52.field_id_52, exp_channel_data_field_52.field_ft_52, exp_channel_data_field_53.field_id_53, exp_channel_data_field_53.field_ft_53, exp_channel_data_field_54.field_id_54, exp_channel_data_field_54.field_ft_54, exp_channel_data_field_55.field_id_55, exp_channel_data_field_55.field_ft_55, exp_channel_data_field_56.field_id_56, exp_channel_data_field_56.field_ft_56, exp_channel_data_field_57.field_id_57, exp_channel_data_field_57.field_ft_57, exp_channel_data_field_58.field_id_58, exp_channel_data_field_58.field_ft_58 FROM exp_channel_titles AS t LEFT JOIN exp_channels AS w ON t.channel_id = w.channel_id LEFT JOIN exp_channel_data AS wd ON t.entry_id = wd.entry_id LEFT JOIN exp_members AS m ON m.member_id = t.author_id LEFT JOIN exp_member_data AS md ON md.member_id = m.member_id LEFT JOIN exp_member_data_field_1 ON m.member_id = exp_member_data_field_1.member_id LEFT JOIN exp_member_data_field_2 ON m.member_id = exp_member_data_field_2.member_id LEFT JOIN exp_member_data_field_3 ON m.member_id = exp_member_data_field_3.member_id LEFT JOIN exp_member_data_field_4 ON m.member_id = exp_member_data_field_4.member_id LEFT JOIN exp_member_data_field_5 ON m.member_id = exp_member_data_field_5.member_id LEFT JOIN exp_member_data_field_6 ON m.member_id = exp_member_data_field_6.member_id LEFT JOIN exp_member_data_field_8 ON m.member_id = exp_member_data_field_8.member_id LEFT JOIN exp_channel_data_field_9 ON t.entry_id = exp_channel_data_field_9.entry_id LEFT JOIN exp_channel_data_field_10 ON t.entry_id = exp_channel_data_field_10.entry_id LEFT JOIN exp_channel_data_field_11 ON t.entry_id = exp_channel_data_field_11.entry_id LEFT JOIN exp_channel_data_field_12 ON t.entry_id = exp_channel_data_field_12.entry_id LEFT JOIN exp_channel_data_field_13 ON t.entry_id = exp_channel_data_field_13.entry_id LEFT JOIN exp_channel_data_field_14 ON t.entry_id = exp_channel_data_field_14.entry_id LEFT JOIN exp_channel_data_field_15 ON t.entry_id = exp_channel_data_field_15.entry_id LEFT JOIN exp_channel_data_field_16 ON t.entry_id = exp_channel_data_field_16.entry_id LEFT JOIN exp_channel_data_field_17 ON t.entry_id = exp_channel_data_field_17.entry_id LEFT JOIN exp_channel_data_field_18 ON t.entry_id = exp_channel_data_field_18.entry_id LEFT JOIN exp_channel_data_field_19 ON t.entry_id = exp_channel_data_field_19.entry_id LEFT JOIN exp_channel_data_field_20 ON t.entry_id = exp_channel_data_field_20.entry_id LEFT JOIN exp_channel_data_field_21 ON t.entry_id = exp_channel_data_field_21.entry_id LEFT JOIN exp_channel_data_field_22 ON t.entry_id = exp_channel_data_field_22.entry_id LEFT JOIN exp_channel_data_field_23 ON t.entry_id = exp_channel_data_field_23.entry_id LEFT JOIN exp_channel_data_field_24 ON t.entry_id = exp_channel_data_field_24.entry_id LEFT JOIN exp_channel_data_field_25 ON t.entry_id = exp_channel_data_field_25.entry_id LEFT JOIN exp_channel_data_field_26 ON t.entry_id = exp_channel_data_field_26.entry_id LEFT JOIN exp_channel_data_field_27 ON t.entry_id = exp_channel_data_field_27.entry_id LEFT JOIN exp_channel_data_field_28 ON t.entry_id = exp_channel_data_field_28.entry_id LEFT JOIN exp_channel_data_field_29 ON t.entry_id = exp_channel_data_field_29.entry_id LEFT JOIN exp_channel_data_field_30 ON t.entry_id = exp_channel_data_field_30.entry_id LEFT JOIN exp_channel_data_field_31 ON t.entry_id = exp_channel_data_field_31.entry_id LEFT JOIN exp_channel_data_field_32 ON t.entry_id = exp_channel_data_field_32.entry_id LEFT JOIN exp_channel_data_field_33 ON t.entry_id = exp_channel_data_field_33.entry_id LEFT JOIN exp_channel_data_field_34 ON t.entry_id = exp_channel_data_field_34.entry_id LEFT JOIN exp_channel_data_field_35 ON t.entry_id = exp_channel_data_field_35.entry_id LEFT JOIN exp_channel_data_field_36 ON t.entry_id = exp_channel_data_field_36.entry_id LEFT JOIN exp_channel_data_field_37 ON t.entry_id = exp_channel_data_field_37.entry_id LEFT JOIN exp_channel_data_field_38 ON t.entry_id = exp_channel_data_field_38.entry_id LEFT JOIN exp_channel_data_field_39 ON t.entry_id = exp_channel_data_field_39.entry_id LEFT JOIN exp_channel_data_field_40 ON t.entry_id = exp_channel_data_field_40.entry_id LEFT JOIN exp_channel_data_field_41 ON t.entry_id = exp_channel_data_field_41.entry_id LEFT JOIN exp_channel_data_field_42 ON t.entry_id = exp_channel_data_field_42.entry_id LEFT JOIN exp_channel_data_field_43 ON t.entry_id = exp_channel_data_field_43.entry_id LEFT JOIN exp_channel_data_field_44 ON t.entry_id = exp_channel_data_field_44.entry_id LEFT JOIN exp_channel_data_field_45 ON t.entry_id = exp_channel_data_field_45.entry_id LEFT JOIN exp_channel_data_field_46 ON t.entry_id = exp_channel_data_field_46.entry_id LEFT JOIN exp_channel_data_field_47 ON t.entry_id = exp_channel_data_field_47.entry_id LEFT JOIN exp_channel_data_field_48 ON t.entry_id = exp_channel_data_field_48.entry_id LEFT JOIN exp_channel_data_field_49 ON t.entry_id = exp_channel_data_field_49.entry_id LEFT JOIN exp_channel_data_field_50 ON t.entry_id = exp_channel_data_field_50.entry_id LEFT JOIN exp_channel_data_field_51 ON t.entry_id = exp_channel_data_field_51.entry_id LEFT JOIN exp_channel_data_field_52 ON t.entry_id = exp_channel_data_field_52.entry_id LEFT JOIN exp_channel_data_field_53 ON t.entry_id = exp_channel_data_field_53.entry_id LEFT JOIN exp_channel_data_field_54 ON t.entry_id = exp_channel_data_field_54.entry_id LEFT JOIN exp_channel_data_field_55 ON t.entry_id = exp_channel_data_field_55.entry_id LEFT JOIN exp_channel_data_field_56 ON t.entry_id = exp_channel_data_field_56.entry_id LEFT JOIN exp_channel_data_field_57 ON t.entry_id = exp_channel_data_field_57.entry_id LEFT JOIN exp_channel_data_field_58 ON t.entry_id = exp_channel_data_field_58.entry_id WHERE t.entry_id IN (12)ORDER BY FIELD(t.entry_id, 12)
ee/legacy/database/drivers/mysqli/mysqli_connection.php:117

Stack Trace: Please include when reporting this error
#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query()
#1 ee/legacy/database/DB_driver.php(270): CI_DB_mysqli_driver->_execute()
#2 ee/legacy/database/DB_driver.php(180): CI_DB_driver->simple_query()
#3 ee/ExpressionEngine/Addons/channel/mod.channel.php(248): CI_DB_driver->query()
#4 ee/legacy/libraries/Template.php(1874): Channel->entries()
#5 ee/legacy/libraries/Template.php(1509): EE_Template->process_tags()
#6 ee/legacy/libraries/Template.php(605): EE_Template->tags()
#7 ee/legacy/libraries/Template.php(236): EE_Template->parse()
#8 ee/legacy/libraries/Template.php(167): EE_Template->fetch_and_parse()
#9 ee/legacy/libraries/Core.php(649): EE_Template->run_template_engine()
#10 ee/legacy/controllers/ee.php(63): EE_Core->generate_page()
#11 [internal function]: EE->index()
#12 ee/ExpressionEngine/Core/Core.php(268): call_user_func_array()
#13 ee/ExpressionEngine/Core/Core.php(118): ExpressionEngine\Core\Core->runController()
#14 ee/ExpressionEngine/Boot/boot.php(162): ExpressionEngine\Core\Core->run()
#15 index.php(174): require_once('...')
#15 index.php(174): require_once('...')

**Comment by intoeetive** [comment]
Woof. Can you confirm the CP shows your ExpressionEngine version as 6.0.0?

Can you post the contents of your site index template (particularly interested in `exp:channel:entries` call)

**Comment by intoeetive** [comment]
@CharlottesvilleMedia can you try changing the line 2498 in `mod.channel.php` from 
`$chunks = array_chunk($fields, 50);` to `$chunks = array_chunk($fields, 40);` (this is not final fix, just wondering if that makes the SQL error go away)

And, we really need to know how your `exp:channel:entries` tag looks like in order to get this fixed

**Comment by CharlottesvilleMedia** [comment]
It's definitely 6.0.0. After your first note I went through my template and cleaned up all my code paying careful attention to the exp:channel:entries tags and I'm no longer getting that error (this is without making the php edit you suggested in your second message). I'm not exactly sure what fixed it, but I'm grateful for your prompt attention to this issue, Yuri. спасбо!

**Comment by intoeetive** [comment]
Ok - if you by chance have the initial template version saved as revision, I'd be grateful, otherwise - we'll dig internally. Thanks!

**Comment by ops-andy** [comment]
fixed in 6.0.1
