### ISSUE TITLE
EEv6 UI Improvement - Add a way to remove references to EE Support from CP

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#710]
I would like to globally turn off advertisements for software support from companies other than my own. 

My clients have had me on retainer (some for over 16 years) to provide EE software support, and any links advertising other support alternatives have not only been confusing in the past, but they could also seem as though they were competing with me for business.

I can appreciate why this may be a great addition to EE's CP in promoting the wonderful support team now at Packet Tide, but my clients are busy people that may not understand what's really going on here. They're already paying for support.

I would love some way to turn advertisements off and/or remove them altogether from the CP.

<img width="945" alt="Screen Shot 2020-12-21 at 3 56 46 PM" src="https://user-images.githubusercontent.com/6145078/102833327-ab726d80-43a5-11eb-8a47-757949323dc9.png">

**Comment by frshjb373** [comment]
Plus one to this...

**Comment by ops-andy** [comment]
This won't be included in EE Core. It will however be a feature in EE Pro along with other customizing CP features.
