### ISSUE TITLE
Upgrading from EE6 RC to EE6.0.0 and system go offline at next connection

### ISSUE THREAD

**Issue by ebeauchamps** [ExpressionEngine/ExpressionEngine#713]
I am on MAMP 5.7 with PHP 7.4.2
I upgraded from within the app from EE6 RC to EE6.0.0
The CP was displayed
I did not change any settings
I logged out
I closed MAMP
I started MAMP again
I visited my local site
The site is OFFLINE

What can I do rather than installing again?
Thanks

EDIT:
I can access the CP....
Probably related to PR #711

**Comment by dougblackjr** [comment]
@ebeauchamps This should be addressed in #711. But to clarify, are you saying you can't access your admin panel either?

**Comment by ebeauchamps** [comment]
No I cannot

**Comment by ebeauchamps** [comment]
oops, sorry I can, my bad!!!!!!!!!
OK, I changed the setting back to ONLINE

**Comment by dougblackjr** [comment]
You should be able to access it in your general settings (https://ee6.test/admin.php?/cp/settings/general)
![Screenshot from 2020-12-22 12-16-38](https://user-images.githubusercontent.com/6020323/102915337-9fdb8100-444f-11eb-8bce-e2ed6f1aa8ec.png)

**Comment by ebeauchamps** [comment]
Leaving it opened waiting for the PR
Thanks @dougblackjr

**Comment by ops-andy** [comment]
fixed in 6.0.1
