### ISSUE TITLE
Color Picker events are not fired on Grid settings page

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#714]
When trying to define a Color Picker field as a Grid column, the React component's events are not triggered when you add a new column. The same thing happens in Bloqs (since it's very similar to Grid). This is the JS I added to Bloqs so I can add a Color Picker field:

```
$('input[name^="grid[cols]"]').change(function () {
        if($(this).val() !== 'colorpicker') {
            return;
        }

        // (╯°□°）╯︵ ┻━┻
        setTimeout(function () {
            $('.fields-keyvalue', '[data-fieldtype="colorpicker"]').miniGrid({grid_min_rows:0,grid_max_rows:''});
            ColorPicker.renderFields()
        }, 100);
    })
```

Once the Grid field is saved with a Color Picker column, and the settings page reloads, the Color Picker kicks in.

I had someone else confirm this was an issue as well.

**Comment by ops-andy** [comment]
fixed in 6.0.1
