### ISSUE TITLE
form_class tag not working for registering and login forms

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#716]
When the tag form_class is added, it's not followed.
Even when you add the tag include_assets="no"
Works fine with channels.

**Comment by intoeetive** [comment]
The parameters work well in login form.

And - they are not available on member registration, so you can't expect them to work. Also not mentioned anywhere on the docs (Channel Form is completely different thing unrelated to members)

However I'm keeping this issue as feature request to add those parameters to member forms other than login.
