### ISSUE TITLE
Members link on sidebar navigation doesn't appear when creating a new user role

### ISSUE THREAD

**Issue by frshjb373** [ExpressionEngine/ExpressionEngine#717]
The members link is missing from sidebar when logged in as a newly created user role that allows for creating members. When accessing path manually in URL, `/cp/members` I can get to the members page fine so doesn't look like a permission issue. Please let me know if you would like me to dm and/or email screenshots of user role and/or setup.

**Comment by ops-andy** [comment]
fixed in 6.0.1
