### ISSUE TITLE
Issues with posting emojis

### ISSUE THREAD

**Issue by valsopi** [ExpressionEngine/ExpressionEngine#719]
Having trouble posting emojis on fields.

![image](https://user-images.githubusercontent.com/10436870/103010982-772fb600-4539-11eb-9df4-c65c817d39c4.png)

**Version:**
EE 6.0.0 (however it does happen on EE 5.x.x, tried it). It's an upgrade from 5.x (and 5 was from 3).

**Environment:**
ubuntu 18.04, nginx, php 7.2, MySQL 5.7

**Comment by intoeetive** [comment]
@valsopi what field type is that field ID 51?
Also, what collation does `exp_channel_data_field_51` have? (`utf8mb4_unicode_ci` is the expected one)

**Comment by intoeetive** [comment]
Closing as we did not receive any further feedback
