### ISSUE TITLE
Minor: "member group(s)" keys remaining in language files

### ISSUE THREAD

**Issue by ebeauchamps** [ExpressionEngine/ExpressionEngine#720]
31  occurrences of "member_group" found in 16 files

![Capture d’écran 2020-12-23 à 19 42 00](https://user-images.githubusercontent.com/1823359/103027925-0f886380-4557-11eb-9373-8093b8ef5082.png)

![Capture d’écran 2020-12-23 à 19 42 23](https://user-images.githubusercontent.com/1823359/103027930-11eabd80-4557-11eb-84a9-6068535d56c0.png)

**Comment by intoeetive** [comment]
We're going to keep the keys related to `member_group` in case there are third-party add-on using those
