### ISSUE TITLE
Entries nav sidebar showing "0" in list

### ISSUE THREAD

**Issue by frshjb373** [ExpressionEngine/ExpressionEngine#721]
Looks like when channel named using number (i.e. "404", name of that channel is showing as "0" in sidebar)

![Screen Shot 2020-12-23 at 1 14 02 PM](https://user-images.githubusercontent.com/7178139/103037546-f1077580-4520-11eb-829a-272a198517ee.png)

**Comment by ops-andy** [comment]
fixed in 6.0.1
