### ISSUE TITLE
[i18n]: untranslatable strings are visible in Access Overview

### ISSUE THREAD

**Issue by ebeauchamps** [ExpressionEngine/ExpressionEngine#722]
EE 6.0.0
PHP 7.4.2 running locally on MAMP
I am displaying the CP in French
Looking at the Access Overview within my profile, I can still see English words were I only expect French in the ADD-ONS section
- Consent
- Relationships
I do not find those 2 keys to be translated, I think they are both missing.

![Capture d’écran 2020-12-23 à 22 22 02](https://user-images.githubusercontent.com/1823359/103037999-87618880-456d-11eb-9861-d5863eb08db8.png)

**Comment by intoeetive** [comment]
@ebeauchamps would you mind adding the following:
```
'consent_module_name' => 'Consentement',
```
to`consent_lang.php` and 
```
'relationship_module_name' => 'Relations',
```
to `fieldtypes_lang.php` (if that makes no difference, then add to `content_lang.php` or `settings_lang.php`)

**Comment by ebeauchamps** [comment]
consent_lang.php updated: OK
settings_lang.php updated: OK (no dice with either fieldtypes_lang or content_lang)

Please add those in a future released.

Thanks!

**Comment by intoeetive** [comment]
Thanks! 
We'll try to include this into next minor release
We might end up putting `relationship_module_name` in dedicated file, so you might need to move your translation then.
