### ISSUE TITLE
[i18n] - missing key in the new Jump menu

### ISSUE THREAD

**Issue by ebeauchamps** [ExpressionEngine/ExpressionEngine#725]
This key "**More than 10 results found, please refine your search**" cannot be found and therefore cannot be translated into my language

![Capture d’écran 2020-12-24 à 13 08 02](https://user-images.githubusercontent.com/1823359/103087840-1e1f5b00-45e9-11eb-8bc8-7d825d8b8f32.png)

FWIW, I am also experiencing non-recurring problems where the Jump menu is displayed in English though my settings are set to French. Looking forward to confirming this.

**Comment by intoeetive** [comment]
Thanks - will be resolved when https://github.com/ExpressionEngine/ExpressionEngine/pull/726 gets merged (or you can pull that branch straigt away)

FYI, I added `6.x` branch to https://github.com/EllisLab/EE-Language-French/tree/6.x (which is currently just branched off `master` so has no EE6 strings). Please submit pull request there when you think translation is in good shape.

Thank you very much for your work!

**Comment by ebeauchamps** [comment]
Thanks. I should be able to commit the French translation for 6.0.0 in a few hours (Happy Christmas!)

**Comment by ops-andy** [comment]
fixed in 6.0.1
