### ISSUE TITLE
Upload Images

### ISSUE THREAD

**Issue by ODDCODE** [ExpressionEngine/ExpressionEngine#729]
When I tried to upload more than 8 images, it will only upload 5, and throw a message with letter and number. 

{"file_id":30,"site_id":1,"title":"SBDYODC001B4-4.jpg","upload_location_id":6,"mime_type":"image\/jpeg","file_name":"SBDYODC001B4-4.jpg","file_size":430520,"description":null,"credit":null,"location":null,"uploaded_by_member_id":1,"upload_date":1609391343,"modified_by_member_id":1,"modified_date":1609475298,"file_hw_original":"590 1000","path":"http:\/\/localhost:8888\/exp\/sbwebsite\/themes\/user\/site\/default\/assets\/img\/product\/SBDYODC001B4-4.jpg","thumb_path":"http:\/\/localhost:8888\/exp\/sbwebsite\/themes\/user\/site\/default\/assets\/img\/product\/_thumbs\/SBDYODC001B4-4.jpg","isImage":true,"isSVG":false}

**Comment by intoeetive** [comment]
This looks like the same issue as https://github.com/ExpressionEngine/ExpressionEngine/issues/693
If you could post the message you've got into that thread, we'd highly appreciate!
