### ISSUE TITLE
Correct Doc URLs in the CMS

### ISSUE THREAD

**Issue by Caleydon** [ExpressionEngine/ExpressionEngine#730]
I found out randomly in the EE code that URLs pointed on EE online documentation doesn't exists because they are changed. Please see an example below.

File: /system/ee/installer/config/config_tmpl.php

Doc URL: https://docs.expressionengine.com/latest/general/system_configuration_overrides.html
It shoulld be new one: https://docs.expressionengine.com/latest/general/system-configuration-overrides.html

I think revision of the doc URLs through whole CMS should be revisited. It's nothing critical but the URLs in the language files should be corrected first.

**Comment by ops-andy** [comment]
fixed in 6.0.1
