### ISSUE TITLE
Control panel font doesn't support foreign languages characters

### ISSUE THREAD

**Issue by Caleydon** [ExpressionEngine/ExpressionEngine#732]
I am working on Slovak translation of the EE. I found out the font family used in the Control panel doesn't support a special characters for foreign languages. In my case it should support Latin extended charset. But for the other future EE CP translations it could be bigger problem.

![special-characters](https://user-images.githubusercontent.com/2806752/103134683-4ecbc700-46b3-11eb-8e8c-77b929676a75.png)

**Comment by intoeetive** [comment]
I can't replicate this, seems to looks fine to me: 
![image](https://user-images.githubusercontent.com/752126/103136562-23080b80-46ca-11eb-869b-47844ded69ca.png)

If you inspect element in browser's console and navigate to "computed styles" - what does it say about actual fonts used (at the very bottom)?
![image](https://user-images.githubusercontent.com/752126/103136590-63678980-46ca-11eb-8b9a-2bcb9a5e36e2.png)

**Comment by intoeetive** [comment]
I'm closing this since we did not receive any further updates or confirmation. Please reopen with more details if you still experience the issue
