### ISSUE TITLE
[i18n] - New Jump menu remains displayed in English even if user is set to another language

### ISSUE THREAD

**Issue by ebeauchamps** [ExpressionEngine/ExpressionEngine#733]
EE6.0.0
PHP 7.4.2 on MAMP

My User, a Super Admin, is set to view the CP in French, but General setting remains set to English: the Jump Menu is then displayed in English (at 90%). 

![Capture d’écran 2020-12-25 à 19 53 25](https://user-images.githubusercontent.com/1823359/103140781-2d86cd00-46eb-11eb-870b-61b081da6e2b.png)

![Capture d’écran 2020-12-25 à 19 54 15](https://user-images.githubusercontent.com/1823359/103140784-324b8100-46eb-11eb-838d-2f1867a3fa91.png)

Then, If I change the general language setting of the CP to French, I get the Jump menu to be displayed in French. But it should take into account the user's setting, shouldn't it?

**Comment by ops-andy** [comment]
fixed in 6.0.1
