### ISSUE TITLE
php escapeshellarg()

### ISSUE THREAD

**Issue by nix79** [ExpressionEngine/ExpressionEngine#735]
hi,
updating from 5.4.0 to ee 6 there is this message:
Warningescapeshellarg() has been disabled for security reasonsee/ExpressionEngine/Library/Filesystem/Filesystem.php, line 288
Severity: E_WARNING{"messageType":"success","message":"Cleaning up","nextStep":"selfDestruct"}

I'm on a shared hosting where they can't enable escapeshellarg()

**Comment by ops-andy** [comment]
fixed in 6.0.1
