### ISSUE TITLE
[i18n] - repository: committing language files to the main repo (here) instead of EllisLab's

### ISSUE THREAD

**Issue by ebeauchamps** [ExpressionEngine/ExpressionEngine#736]
Right now, we still have to commit our language files to the extra-old Ellis Lab (!) repo.

I suggest that you should accept language files for 6.x to be committed to the main ExpressionEngine repo (in /user/language/)

**Comment by TomJaeger** [comment]
Thanks for passing this along.  We've had a few conversations on it internally.  We're aiming to formally cross the bridge Jan 2021 (when we're back in the office).

If you have other thoughts or ideas on this front, we would love to hear them!

**Comment by ebeauchamps** [comment]
The nice thing with the current EllisLab repo is that the English language files are isolated form other changes. So as a translator, you can very easily follow the changes made to the lang files. If you add tag or commit comparison, you can indeed pinpoint immediately to the changes that are to be conducted to your own files. But for that, you will have to create another repo dedicated to the English language files.

Another idea is to simultaneously add or delete the language keys in the English language files and in the other locales (for those included in /user/language/). When adding them, you could have a php script calling upon the Google Translate API in order to provide at least a basic translation (75% of the time it should be acceptable).

But the difficulty arise when a word, a sentence, is edited (corrected) in the English files. As a translator, you don't want to miss this, and I am not sure GT will be of any help for you in such a case. That's why a dedicate repo is of great help: you can miss of few update (say 6.0.5 and 6.1) and still compare the latest English version (say 6.1.5) with the one you based your work on (say 6.0.0) and then find all the changes you will have to make in your "own" files.

**Comment by intoeetive** [comment]
Moving discussion into https://github.com/ExpressionEngine/ExpressionEngine/discussions/2930
