### ISSUE TITLE
logged_in_role_id not working in templates yet

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#742]
The docs for v6 look correct: https://docs.expressionengine.com/latest/templates/conditionals.html#logged_in_role_id

In a template, I had to use {logged_in_group_id} in my conditional to get things working though.

{if logged_in_group_id == '10' OR logged_in_group_id == '17'} display something {/if}

**Comment by intoeetive** [comment]
Thanks for the report @PDXMan1 

This appears to be both code error and error in the docs (the correct variable name would be `logged_in_primary_role_id`). We'll get this fixed for 6.0.1 release, meanwhile you can still use `logged_in_group_id` variables, it's not being removed in 6.x

**Comment by ops-andy** [comment]
fixed in 6.0.1
