### ISSUE TITLE
Entry preview doesn't display split 50/50 column split screen properly when fields like grid are very wide.

### ISSUE THREAD

**Issue by frshjb373** [ExpressionEngine/ExpressionEngine#743]
Large grid fields in entry causing preview to display the entire edit entry page and not splitting 50/50 as it should. Happy to provide more details if needed.

**Comment by ops-andy** [comment]
@frshjb373 can you just send over screenshot?

**Comment by intoeetive** [comment]
This is duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/576
