### ISSUE TITLE
When selecting a directory for the RTE to use (custom toolset), it randomly selects another directory

### ISSUE THREAD

**Issue by jphansen80** [ExpressionEngine/ExpressionEngine#744]
**Description of the problem**
When selecting a directory for the RTE to use (custom toolset), it randomly selects another directory.

**How To Reproduce**

1. Go to Addons > RTE Editor
2. Select a toolset
3. Select an Upload Directory
4. Open a channel entry and use the "New Image or File" dialog; it shows the incorrect upload directory

**Additional context**
On one iteration I got the "Member Photos" as my Upload Directory. Upon opening the dialog box, it showed existing files: the files in the root (/) of my web server.

**Comment by jphansen80** [comment]
I can provide a video of reproducing the bug upon request.

**Comment by intoeetive** [comment]
@jphansen80 which ExpessionEngine version do you have? It it is EE6, is it the released 6.0.0 or one of the betas?

**Comment by jphansen80** [comment]
Hi Yuri,

It's the released EE6 6.0.0.

Jimmy
________________________________

**Comment by ops-andy** [comment]
fixed in 6.0.1

**Comment by jphansen80** [comment]
Nice, thanks!

Jimmy
________________________________
