### ISSUE TITLE
Count is not displayed right value when two channels are displayed on the same page

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#747]
I have two channels displayed on one page.
The result of the first channel is always displaying 1 for count because the second channel only find one record.
Maybe I do not use the clear method to display the number of records for a channel but the documentation about is confusing.

**Comment by intoeetive** [comment]
@digicali can you post the template code you have so we replicate the error. Thanks!

**Comment by digicali** [comment]
Example
this first code display the number of news 
` <span class="badge badge-pill badge-light">{exp:channel:entries channel="ch_blog" }{if count == absolute_results} {count}{/if}{/exp:channel:entries}
                                                    </span>`
                                                    and this second code display the content of one specific record
                                                    
                                                    `{exp:channel:entries channel="ch_blog" entry_id="{segment_2}"}
                                                    Details of the blog
                                                    {/exp:channel:entries}`
                                                    
When both code are on the same page, the first code always display 1 as a result that is not logical.

**Comment by intoeetive** [comment]
If you have `{segment_2}` set to entry ID that I would say this is expected behaviour. Try adding `dynamic="no"` to the first `exp:channel:entries` call

**Comment by digicali** [comment]
Thanks, it's working but still not logical for me :-)

**Comment by intoeetive** [comment]
`{exp:channel:entries}` tag is designed to dynamically "catch" the entry by checking for entry ID or url_title in the URL. If it's found, single entry is displayed, so you'll get just one loop of the tags. If you want it to loop through all entries, you need to specify `dynamic="no"`
