### ISSUE TITLE
Checkbox fields not working correctly from grid within fluid fields

### ISSUE THREAD

**Issue by MatthewJLewis** [ExpressionEngine/ExpressionEngine#75]
Might well be related to this: https://github.com/ExpressionEngine/ExpressionEngine/issues/74

Using a Checkbox field, within a File Grid field that is part of a Fluid field, does not work as expected. Specifically, the tag pair does not work at all, and using `{field_name}` simply returns a comma-separated list of the values of every box that was checked for the entry. I have not been able to find a way to get just a single value from the list.

**Comment by kevincupp** [comment]
Checkboxes look to be working fine inside Grid inside Fluid. Can you provide the template tags you are using? Why do you delete the issue template in your issues? Steps to reproduce and sample code would save us both time.

**Comment by MatthewJLewis** [comment]
Apologies; I was confused about how to access checkboxes.

I'll try to be more verbose with any additional issues in the future.
