### ISSUE TITLE
Duplicate queries 

### ISSUE THREAD

**Issue by maneeshblr** [ExpressionEngine/ExpressionEngine#751]
Environment: 
EE Version: 6.0.0 (upgraded from 3.5.11)
PHP 5.6.39
MySQL 5.7.31
Web Server: Apache 2.4.6 
OS: Centos 7

I enabled Debugging in the Administration Control Panel to root cause some of the severe performance issues in EE6.0.0 where server started crashing during peak traffic hours every day. This never happened for many years that EE3.x was running. The first clue is that there are lot more queries run the EE compared to older versions. 

At the bottom of each page, it says that there is a 3x duplicated query and a 2x duplicated query. Please check and advise if this is so.

Thanks.

**Query 1 (duplicated 3x) **

SELECT Permission_permissions.permission_id as Permission__permission_id, Permission_permissions.role_id as Permission__role_id, Permission_permissions.site_id as Permission__site_id, Permission_permissions.permission as Permission__permission
    FROM (`exp_permissions` as Permission_permissions)
    WHERE  ( 
    `Permission_permissions`.`site_id`  =  1
    AND `Permission_permissions`.`role_id`  IN (1) 
    ) 
    LIMIT 18446744073709551615

#system/ee/legacy/libraries/Session.php L:639 ExpressionEngine\Model\Member\Member::getPermissions() 

#system/ee/ExpressionEngine/Model/Member/Member.php L:1260 

ExpressionEngine\Model\Member\Member::getPermissions() #system/ee/ExpressionEngine/app.setup.php L:276 

ExpressionEngine\Model\Member\Member::getPermissions()
---

** Query 2 (duplicated 2x)**
SELECT ee_m_ChannelField_channel_fields.field_id as ee_m_ChannelField__field_id, ee_m_ChannelField_channel_fields.site_id as ee_m_ChannelField__site_id, ee_m_ChannelField_channel_fields.field_name as ee_m_ChannelField__field_name, ee_m_ChannelField_channel_fields.field_label as ee_m_ChannelField__field_label, ee_m_ChannelField_channel_fields.field_instructions as ee_m_ChannelField__field_instructions, ee_m_ChannelField_channel_fields.field_type as ee_m_ChannelField__field_type, ee_m_ChannelField_channel_fields.field_list_items as ee_m_ChannelField__field_list_items, ee_m_ChannelField_channel_fields.field_pre_populate as ee_m_ChannelField__field_pre_populate, ee_m_ChannelField_channel_fields.field_pre_channel_id as ee_m_ChannelField__field_pre_channel_id, ee_m_ChannelField_channel_fields.field_pre_field_id as ee_m_ChannelField__field_pre_field_id, ee_m_ChannelField_channel_fields.field_ta_rows as ee_m_ChannelField__field_ta_rows, ee_m_ChannelField_channel_fields.field_maxl as ee_m_ChannelField__field_maxl, ee_m_ChannelField_channel_fields.field_required as ee_m_ChannelField__field_required, ee_m_ChannelField_channel_fields.field_text_direction as ee_m_ChannelField__field_text_direction, ee_m_ChannelField_channel_fields.field_search as ee_m_ChannelField__field_search, ee_m_ChannelField_channel_fields.field_is_hidden as ee_m_ChannelField__field_is_hidden, ee_m_ChannelField_channel_fields.field_fmt as ee_m_ChannelField__field_fmt, ee_m_ChannelField_channel_fields.field_show_fmt as ee_m_ChannelField__field_show_fmt, ee_m_ChannelField_channel_fields.field_order as ee_m_ChannelField__field_order, ee_m_ChannelField_channel_fields.field_content_type as ee_m_ChannelField__field_content_type, ee_m_ChannelField_channel_fields.field_settings as ee_m_ChannelField__field_settings, ee_m_ChannelField_channel_fields.legacy_field_data as ee_m_ChannelField__legacy_field_data
FROM (`exp_channel_fields` as ee_m_ChannelField_channel_fields)
LEFT JOIN `exp_channel_field_groups_fields` as ee_m_ChannelFieldGroup_ee_m_ChannelField_channel_field_groups_fields ON `ee_m_ChannelFieldGroup_ee_m_ChannelField_channel_field_groups_fields`.`field_id` = `ee_m_ChannelField_channel_fields`.`field_id`
WHERE `ee_m_ChannelFieldGroup_ee_m_ChannelField_channel_field_groups_fields`.`group_id` =  1
LIMIT 18446744073709551615

#system/ee/ExpressionEngine/Addons/channel/mod.channel.php L:2488 ExpressionEngine\Model\Channel\Channel::getAllCustomFields()

**Comment by maneeshblr** [comment]
On a fresh installation on Ubuntu 18.04.7 and PHP 7.2.24, here are the duplicate queries:

Site Homepage
Duplicate Queries (ee6p0p0)
    3 ×
    SHOW COLUMNS FROM `exp_member_data`

    #system/ee/ExpressionEngine/Service/Model/MetaDataReader.php L:166 ExpressionEngine\Model\Content\VariableColumnGateway::getFieldList()

    4 ×
    SELECT Permission_permissions.permission_id as Permission__permission_id, Permission_permissions.role_id as Permission__role_id, Permission_permissions.site_id as Permission__site_id, Permission_permissions.permission as Permission__permission FROM (`exp_permissions` as Permission_permissions) WHERE ( `Permission_permissions`.`site_id` = 1 AND `Permission_permissions`.`role_id` IN (1) ) LIMIT 18446744073709551615

    #system/ee/legacy/libraries/Session.php L:639 ExpressionEngine\Model\Member\Member::getPermissions() #system/ee/legacy/libraries/Session.php L:684 ExpressionEngine\Model\Member\Member::getPermissions() #system/ee/ExpressionEngine/Model/Member/Member.php L:1260 ExpressionEngine\Model\Member\Member::getPermissions() #system/ee/ExpressionEngine/app.setup.php L:276 ExpressionEngine\Model\Member\Member::getPermissions()

    2 ×

    SELECT Member_members.member_id as Member__member_id, Member_members.role_id as Member__role_id, Member_members.username as Member__username, Member_members.screen_name as Member__screen_name, Member_members.password as Member__password, Member_members.salt as Member__salt, Member_members.unique_id as Member__unique_id, Member_members.crypt_key as Member__crypt_key, Member_members.authcode as Member__authcode, Member_members.email as Member__email, Member_members.signature as Member__signature, Member_members.avatar_filename as Member__avatar_filename, Member_members.avatar_width as Member__avatar_width, Member_members.avatar_height as Member__avatar_height, Member_members.photo_filename as Member__photo_filename, Member_members.photo_width as Member__photo_width, Member_members.photo_height as Member__photo_height, Member_members.sig_img_filename as Member__sig_img_filename, Member_members.sig_img_width as Member__sig_img_width, Member_members.sig_img_height as Member__sig_img_height, Member_members.ignore_list as Member__ignore_list, Member_members.private_messages as Member__private_messages, Member_members.accept_messages as Member__accept_messages, Member_members.last_view_bulletins as Member__last_view_bulletins, Member_members.last_bulletin_date as Member__last_bulletin_date, Member_members.ip_address as Member__ip_address, Member_members.join_date as Member__join_date, Member_members.last_visit as Member__last_visit, Member_members.last_activity as Member__last_activity, Member_members.total_entries as Member__total_entries, Member_members.total_comments as Member__total_comments, Member_members.total_forum_topics as Member__total_forum_topics, Member_members.total_forum_posts as Member__total_forum_posts, Member_members.last_entry_date as Member__last_entry_date, Member_members.last_comment_date as Member__last_comment_date, Member_members.last_forum_post_date as Member__last_forum_post_date, Member_members.last_email_date as Member__last_email_date, Member_members.in_authorlist as Member__in_authorlist, Member_members.accept_admin_email as Member__accept_admin_email, Member_members.accept_user_email as Member__accept_user_email, Member_members.notify_by_default as Member__notify_by_default, Member_members.notify_of_pm as Member__notify_of_pm, Member_members.display_signatures as Member__display_signatures, Member_members.parse_smileys as Member__parse_smileys, Member_members.smart_notifications as Member__smart_notifications, Member_members.language as Member__language, Member_members.timezone as Member__timezone, Member_members.time_format as Member__time_format, Member_members.date_format as Member__date_format, Member_members.include_seconds as Member__include_seconds, Member_members.profile_theme as Member__profile_theme, Member_members.forum_theme as Member__forum_theme, Member_members.tracker as Member__tracker, Member_members.template_size as Member__template_size, Member_members.notepad as Member__notepad, Member_members.notepad_size as Member__notepad_size, Member_members.bookmarklets as Member__bookmarklets, Member_members.quick_links as Member__quick_links, Member_members.quick_tabs as Member__quick_tabs, Member_members.show_sidebar as Member__show_sidebar, Member_members.pmember_id as Member__pmember_id, Member_members.cp_homepage as Member__cp_homepage, Member_members.cp_homepage_channel as Member__cp_homepage_channel, Member_members.cp_homepage_custom as Member__cp_homepage_custom, Member_member_data.member_id as Member__member_id, Member_member_data.member_id as Member__member_id FROM (`exp_members` as Member_members, `exp_member_data` as Member_member_data) WHERE Member_member_data.member_id = Member_members.member_id AND ( `Member_member_data`.`member_id` = 1 ) LIMIT 1

    #system/ee/legacy/libraries/Core.php L:455 Cp::set_default_view_variables() #system/ee/ExpressionEngine/Controller/Homepage/Homepage.php L:22 ExpressionEngine\Controller\Homepage\Homepage::redirectIfNoSegments()

    2 ×

    SELECT RoleSetting_role_settings.id as RoleSetting__id, RoleSetting_role_settings.role_id as RoleSetting__role_id, RoleSetting_role_settings.site_id as RoleSetting__site_id, RoleSetting_role_settings.menu_set_id as RoleSetting__menu_set_id, RoleSetting_role_settings.mbr_delete_notify_emails as RoleSetting__mbr_delete_notify_emails, RoleSetting_role_settings.exclude_from_moderation as RoleSetting__exclude_from_moderation, RoleSetting_role_settings.search_flood_control as RoleSetting__search_flood_control, RoleSetting_role_settings.prv_msg_send_limit as RoleSetting__prv_msg_send_limit, RoleSetting_role_settings.prv_msg_storage_limit as RoleSetting__prv_msg_storage_limit, RoleSetting_role_settings.include_in_authorlist as RoleSetting__include_in_authorlist, RoleSetting_role_settings.include_in_memberlist as RoleSetting__include_in_memberlist, RoleSetting_role_settings.cp_homepage as RoleSetting__cp_homepage, RoleSetting_role_settings.cp_homepage_channel as RoleSetting__cp_homepage_channel, RoleSetting_role_settings.cp_homepage_custom as RoleSetting__cp_homepage_custom FROM (`exp_role_settings` as RoleSetting_role_settings) WHERE ( `RoleSetting_role_settings`.`role_id` = 1 AND `RoleSetting_role_settings`.`site_id` = 1 ) LIMIT 1

    #system/ee/legacy/libraries/Cp.php L:102 ExpressionEngine\Model\Member\Member::getCPHomepageURL() #system/ee/ExpressionEngine/Controller/Homepage/Homepage.php L:78 ExpressionEngine\Model\Member\Member::getCPHomepageURL()

    2 ×

    SELECT MenuItem_menu_items.item_id as MenuItem__item_id, MenuItem_menu_items.parent_id as MenuItem__parent_id, MenuItem_menu_items.set_id as MenuItem__set_id, MenuItem_menu_items.name as MenuItem__name, MenuItem_menu_items.data as MenuItem__data, MenuItem_menu_items.type as MenuItem__type, MenuItem_menu_items.sort as MenuItem__sort, Set_menu_sets.set_id as Set__set_id, RoleSettings_role_settings.id as RoleSettings__id, RoleSettings_role_settings.role_id as RoleSettings__role_id, RoleSettings_role_settings.site_id as RoleSettings__site_id, RoleSettings_role_settings.menu_set_id as RoleSettings__menu_set_id, Children_menu_items.item_id as Children__item_id, Children_menu_items.parent_id as Children__parent_id, Children_menu_items.set_id as Children__set_id, Children_menu_items.name as Children__name, Children_menu_items.data as Children__data, Children_menu_items.type as Children__type, Children_menu_items.sort as Children__sort FROM (`exp_menu_items` as MenuItem_menu_items) LEFT JOIN `exp_menu_sets` AS Set_menu_sets ON `Set_menu_sets`.`set_id` = `MenuItem_menu_items`.`set_id` LEFT JOIN `exp_role_settings` AS RoleSettings_role_settings ON `RoleSettings_role_settings`.`menu_set_id` = `Set_menu_sets`.`set_id` LEFT JOIN `exp_menu_items` AS Children_menu_items ON `Children_menu_items`.`parent_id` = `MenuItem_menu_items`.`item_id` WHERE ( `RoleSettings_role_settings`.`role_id` = 1 ) ORDER BY `MenuItem_menu_items`.`sort`, `Children_menu_items`.`sort` LIMIT 18446744073709551615

    #system/ee/ExpressionEngine/View/_shared/dashboard/dashboard.php L:14 EE_Menu::generate_menu() #system/ee/ExpressionEngine/Service/Sidebar/Navigation/NavigationSidebar.php L:187 ExpressionEngine\Service\Sidebar\Navigation\NavigationCustomSection::render()

    2 ×

    SHOW COLUMNS FROM `exp_channel_data`

    #system/ee/ExpressionEngine/Service/Model/MetaDataReader.php L:166 ExpressionEngine\Model\Content\VariableColumnGateway::getFieldList()

    3 ×

    SELECT ee_m_ChannelEntry_channel_titles.entry_id as ee_m_ChannelEntry__entry_id, ee_m_ChannelEntry_channel_titles.site_id as ee_m_ChannelEntry__site_id, ee_m_ChannelEntry_channel_titles.channel_id as ee_m_ChannelEntry__channel_id, ee_m_ChannelEntry_channel_titles.author_id as ee_m_ChannelEntry__author_id, ee_m_ChannelEntry_channel_titles.forum_topic_id as ee_m_ChannelEntry__forum_topic_id, ee_m_ChannelEntry_channel_titles.ip_address as ee_m_ChannelEntry__ip_address, ee_m_ChannelEntry_channel_titles.title as ee_m_ChannelEntry__title, ee_m_ChannelEntry_channel_titles.url_title as ee_m_ChannelEntry__url_title, ee_m_ChannelEntry_channel_titles.status as ee_m_ChannelEntry__status, ee_m_ChannelEntry_channel_titles.status_id as ee_m_ChannelEntry__status_id, ee_m_ChannelEntry_channel_titles.versioning_enabled as ee_m_ChannelEntry__versioning_enabled, ee_m_ChannelEntry_channel_titles.view_count_one as ee_m_ChannelEntry__view_count_one, ee_m_ChannelEntry_channel_titles.view_count_two as ee_m_ChannelEntry__view_count_two, ee_m_ChannelEntry_channel_titles.view_count_three as ee_m_ChannelEntry__view_count_three, ee_m_ChannelEntry_channel_titles.view_count_four as ee_m_ChannelEntry__view_count_four, ee_m_ChannelEntry_channel_titles.allow_comments as ee_m_ChannelEntry__allow_comments, ee_m_ChannelEntry_channel_titles.sticky as ee_m_ChannelEntry__sticky, ee_m_ChannelEntry_channel_titles.entry_date as ee_m_ChannelEntry__entry_date, ee_m_ChannelEntry_channel_titles.year as ee_m_ChannelEntry__year, ee_m_ChannelEntry_channel_titles.month as ee_m_ChannelEntry__month, ee_m_ChannelEntry_channel_titles.day as ee_m_ChannelEntry__day, ee_m_ChannelEntry_channel_titles.expiration_date as ee_m_ChannelEntry__expiration_date, ee_m_ChannelEntry_channel_titles.comment_expiration_date as ee_m_ChannelEntry__comment_expiration_date, ee_m_ChannelEntry_channel_titles.edit_date as ee_m_ChannelEntry__edit_date, ee_m_ChannelEntry_channel_titles.recent_comment_date as ee_m_ChannelEntry__recent_comment_date, ee_m_ChannelEntry_channel_titles.comment_total as ee_m_ChannelEntry__comment_total, ee_m_ChannelEntry_channel_data.entry_id as ee_m_ChannelEntry__entry_id, ee_m_ChannelEntry_channel_data.channel_id as ee_m_ChannelEntry__channel_id, ee_m_ChannelEntry_channel_data.site_id as ee_m_ChannelEntry__site_id, ee_m_ChannelEntry_channel_data.entry_id as ee_m_ChannelEntry__entry_id, ee_m_ChannelEntry_channel_data.site_id as ee_m_ChannelEntry__site_id, ee_m_ChannelEntry_channel_data.channel_id as ee_m_ChannelEntry__channel_id FROM (`exp_channel_titles` as ee_m_ChannelEntry_channel_titles, `exp_channel_data` as ee_m_ChannelEntry_channel_data) WHERE ee_m_ChannelEntry_channel_data.entry_id = ee_m_ChannelEntry_channel_titles.entry_id AND `ee_m_ChannelEntry_channel_titles`.`entry_id` = 4 LIMIT 18446744073709551615

    #system/ee/ExpressionEngine/Service/View/View.php L:107 ExpressionEngine\Service\View\View::parse()

    3 ×

    SELECT Channel_channels.channel_id as Channel__channel_id, Channel_channels.site_id as Channel__site_id, Channel_channels.channel_name as Channel__channel_name, Channel_channels.channel_title as Channel__channel_title, Channel_channels.channel_url as Channel__channel_url, Channel_channels.channel_description as Channel__channel_description, Channel_channels.channel_lang as Channel__channel_lang, Channel_channels.total_entries as Channel__total_entries, Channel_channels.total_records as Channel__total_records, Channel_channels.total_comments as Channel__total_comments, Channel_channels.last_entry_date as Channel__last_entry_date, Channel_channels.last_comment_date as Channel__last_comment_date, Channel_channels.cat_group as Channel__cat_group, Channel_channels.deft_status as Channel__deft_status, Channel_channels.search_excerpt as Channel__search_excerpt, Channel_channels.deft_category as Channel__deft_category, Channel_channels.deft_comments as Channel__deft_comments, Channel_channels.channel_require_membership as Channel__channel_require_membership, Channel_channels.channel_max_chars as Channel__channel_max_chars, Channel_channels.channel_html_formatting as Channel__channel_html_formatting, Channel_channels.channel_allow_img_urls as Channel__channel_allow_img_urls, Channel_channels.channel_auto_link_urls as Channel__channel_auto_link_urls, Channel_channels.channel_notify as Channel__channel_notify, Channel_channels.channel_notify_emails as Channel__channel_notify_emails, Channel_channels.comment_url as Channel__comment_url, Channel_channels.sticky_enabled as Channel__sticky_enabled, Channel_channels.comment_system_enabled as Channel__comment_system_enabled, Channel_channels.comment_require_membership as Channel__comment_require_membership, Channel_channels.comment_moderate as Channel__comment_moderate, Channel_channels.comment_max_chars as Channel__comment_max_chars, Channel_channels.comment_timelock as Channel__comment_timelock, Channel_channels.comment_require_email as Channel__comment_require_email, Channel_channels.comment_text_formatting as Channel__comment_text_formatting, Channel_channels.comment_html_formatting as Channel__comment_html_formatting, Channel_channels.comment_allow_img_urls as Channel__comment_allow_img_urls, Channel_channels.comment_auto_link_urls as Channel__comment_auto_link_urls, Channel_channels.comment_notify as Channel__comment_notify, Channel_channels.comment_notify_authors as Channel__comment_notify_authors, Channel_channels.comment_notify_emails as Channel__comment_notify_emails, Channel_channels.comment_expiration as Channel__comment_expiration, Channel_channels.search_results_url as Channel__search_results_url, Channel_channels.rss_url as Channel__rss_url, Channel_channels.enable_versioning as Channel__enable_versioning, Channel_channels.max_revisions as Channel__max_revisions, Channel_channels.default_entry_title as Channel__default_entry_title, Channel_channels.title_field_label as Channel__title_field_label, Channel_channels.url_title_prefix as Channel__url_title_prefix, Channel_channels.max_entries as Channel__max_entries, Channel_channels.preview_url as Channel__preview_url FROM (`exp_channels` as Channel_channels) WHERE ( `Channel_channels`.`channel_id` IN (2) ) LIMIT 18446744073709551615

    #system/ee/ExpressionEngine/Service/View/View.php L:107 ExpressionEngine\Service\View\View::parse()

    3 ×

    SELECT ee_m_ChannelField_channel_fields.field_id as ee_m_ChannelField__field_id, ee_m_ChannelField_channel_fields.site_id as ee_m_ChannelField__site_id, ee_m_ChannelField_channel_fields.field_name as ee_m_ChannelField__field_name, ee_m_ChannelField_channel_fields.field_label as ee_m_ChannelField__field_label, ee_m_ChannelField_channel_fields.field_instructions as ee_m_ChannelField__field_instructions, ee_m_ChannelField_channel_fields.field_type as ee_m_ChannelField__field_type, ee_m_ChannelField_channel_fields.field_list_items as ee_m_ChannelField__field_list_items, ee_m_ChannelField_channel_fields.field_pre_populate as ee_m_ChannelField__field_pre_populate, ee_m_ChannelField_channel_fields.field_pre_channel_id as ee_m_ChannelField__field_pre_channel_id, ee_m_ChannelField_channel_fields.field_pre_field_id as ee_m_ChannelField__field_pre_field_id, ee_m_ChannelField_channel_fields.field_ta_rows as ee_m_ChannelField__field_ta_rows, ee_m_ChannelField_channel_fields.field_maxl as ee_m_ChannelField__field_maxl, ee_m_ChannelField_channel_fields.field_required as ee_m_ChannelField__field_required, ee_m_ChannelField_channel_fields.field_text_direction as ee_m_ChannelField__field_text_direction, ee_m_ChannelField_channel_fields.field_search as ee_m_ChannelField__field_search, ee_m_ChannelField_channel_fields.field_is_hidden as ee_m_ChannelField__field_is_hidden, ee_m_ChannelField_channel_fields.field_fmt as ee_m_ChannelField__field_fmt, ee_m_ChannelField_channel_fields.field_show_fmt as ee_m_ChannelField__field_show_fmt, ee_m_ChannelField_channel_fields.field_order as ee_m_ChannelField__field_order, ee_m_ChannelField_channel_fields.field_content_type as ee_m_ChannelField__field_content_type, ee_m_ChannelField_channel_fields.field_settings as ee_m_ChannelField__field_settings, ee_m_ChannelField_channel_fields.legacy_field_data as ee_m_ChannelField__legacy_field_data FROM (`exp_channel_fields` as ee_m_ChannelField_channel_fields) LEFT JOIN `exp_channels_channel_fields` as ee_m_Channel_ee_m_ChannelField_channels_channel_fields ON `ee_m_Channel_ee_m_ChannelField_channels_channel_fields`.`field_id` = `ee_m_ChannelField_channel_fields`.`field_id` WHERE `ee_m_Channel_ee_m_ChannelField_channels_channel_fields`.`channel_id` = 2 LIMIT 18446744073709551615

    #system/ee/ExpressionEngine/Model/Channel/Channel.php L:607 ExpressionEngine\Model\Channel\Channel::__get()

    3 ×

    SELECT exp_channel_titles.entry_id as ee_m_ChannelEntry__entry_id, ee_m_ChannelEntry_field_id_5.field_id_5 as ee_m_ChannelEntry__field_id_5, ee_m_ChannelEntry_field_id_5.field_ft_5 as ee_m_ChannelEntry__field_ft_5, ee_m_ChannelEntry_field_id_6.field_id_6 as ee_m_ChannelEntry__field_id_6, ee_m_ChannelEntry_field_id_6.field_ft_6 as ee_m_ChannelEntry__field_ft_6, ee_m_ChannelEntry_field_id_7.field_id_7 as ee_m_ChannelEntry__field_id_7, ee_m_ChannelEntry_field_id_7.field_ft_7 as ee_m_ChannelEntry__field_ft_7, ee_m_ChannelEntry_field_id_8.field_id_8 as ee_m_ChannelEntry__field_id_8, ee_m_ChannelEntry_field_id_8.field_ft_8 as ee_m_ChannelEntry__field_ft_8, ee_m_ChannelEntry_field_id_9.field_id_9 as ee_m_ChannelEntry__field_id_9, ee_m_ChannelEntry_field_id_9.field_ft_9 as ee_m_ChannelEntry__field_ft_9, ee_m_ChannelEntry_field_id_10.field_id_10 as ee_m_ChannelEntry__field_id_10, ee_m_ChannelEntry_field_id_10.field_ft_10 as ee_m_ChannelEntry__field_ft_10 FROM (`exp_channel_titles`) LEFT JOIN `exp_channel_data_field_5` AS ee_m_ChannelEntry_field_id_5 ON `ee_m_ChannelEntry_field_id_5`.`entry_id` = `exp_channel_titles`.`entry_id` LEFT JOIN `exp_channel_data_field_6` AS ee_m_ChannelEntry_field_id_6 ON `ee_m_ChannelEntry_field_id_6`.`entry_id` = `exp_channel_titles`.`entry_id` LEFT JOIN `exp_channel_data_field_7` AS ee_m_ChannelEntry_field_id_7 ON `ee_m_ChannelEntry_field_id_7`.`entry_id` = `exp_channel_titles`.`entry_id` LEFT JOIN `exp_channel_data_field_8` AS ee_m_ChannelEntry_field_id_8 ON `ee_m_ChannelEntry_field_id_8`.`entry_id` = `exp_channel_titles`.`entry_id` LEFT JOIN `exp_channel_data_field_9` AS ee_m_ChannelEntry_field_id_9 ON `ee_m_ChannelEntry_field_id_9`.`entry_id` = `exp_channel_titles`.`entry_id` LEFT JOIN `exp_channel_data_field_10` AS ee_m_ChannelEntry_field_id_10 ON `ee_m_ChannelEntry_field_id_10`.`entry_id` = `exp_channel_titles`.`entry_id` WHERE `exp_channel_titles`.`entry_id` IN (4)

    #system/ee/ExpressionEngine/Service/View/View.php L:107 ExpressionEngine\Service\View\View::parse()

**Comment by intoeetive** [comment]
The performance issues with duplicate queries have been addressed in ExpressionEngine 7. The changes will also be backported to 6.4.0
