### ISSUE TITLE
File Manager Modal Caching Issues on Entry Edit Screen

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#752]
The client-side caching of the files that show in the File Manager popup from File or File Grid fields when editing an entry doesn't allow the File Manager list/thumbnails to update after various changes and because it's a modal, not even a hard refresh helps.  For example:

1) After dragging images (single or multiples) into a File Grid, the image(s) is/are uploaded, but clicking "Choose Existing" right afterwards doesn't immediately show the newly upload images as available:

https://user-images.githubusercontent.com/8193519/103563065-62c4b500-4e79-11eb-877b-ebe8aaf0bd42.mp4

2) After deleting images via the main file manager, deleted images still appear in the modal when editing entries, but selecting them doesn't do anything since the image is gone:

https://user-images.githubusercontent.com/8193519/103563431-fdbd8f00-4e79-11eb-9b36-0de80959431e.mp4

**Comment by intoeetive** [comment]
On my testing, I was able to replicate this; however the cached popup is getting replaced by up-to-date version in less than a second

We do need to improve the loading of modals though; as such, classifying it as enhancement

**Comment by pyrobob83** [comment]
Hey Yuri,
Thanks for looking into this - I'd actually forgotten I'd opened an issue for this and I think we may have just recently found the culprit, which was overzealous expiry headers being set in our site-wide .htaccess.  I have more testing to do to confirm, but I'll try and do that soon and remember to update this issue.

Thanks!

**Comment by intoeetive** [comment]
I believe this is not relevant anymore with the new File Manager in EE7. Feel free to reopen if you face the issue again
