### ISSUE TITLE
File list doesn't refresh after sync

### ISSUE THREAD

**Issue by stinhambo** [ExpressionEngine/ExpressionEngine#755]
**ExpressionEngine ver:** 6.0.0

**Expected behaviour:** File list should refresh after successful file sync, Sync buttons should disappear.

**Current behaviour:** After sync, Sync Client Logos title remains, Sync Files buttons remain and file list doesn't show unless you refresh the page or you click on the left hand folder link.

**Comment by intoeetive** [comment]
The Sync UI has changed in ExpressionEngine 7, so this issue is no longer relevant
