### ISSUE TITLE
PHP specs check

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#758]
Some hosting providers put the value of memory_limit = -1 (unlimited)
Some when you try to EE6 checker on it, it says  

ExpressionEngine Server Compatibility Wizard
Oops, there was an error

To complete the wizard check, the following error(s) must be addressed:
>= 32 MB Memory Allocated to PHP is required.

**Comment by intoeetive** [comment]
@digicali thanks for catching - that's an interesting one!

Would you by chance be willing also to work on providing a fix for this? You could start by forking off https://github.com/ExpressionEngine/ExpressionEngine/tree/6.dev branch and then submitting pull request against it.
