### ISSUE TITLE
Brittle JS selectors in new File Field code

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#76]
**Description of the problem**
This isn't a bug per-se, but pointing out some potentially brittle code. There are several lines of code in the new File Field code that can break down pretty easily by finding DOM elements with the first() selector, or sibling(). E.g.

https://github.com/ExpressionEngine/ExpressionEngine/blob/ea47b5f94d4b8e6b2c898af1a856a278c03fc807/themes/ee/asset/javascript/src/fields/file/file_field_drag_and_drop.es6#L48

https://github.com/ExpressionEngine/ExpressionEngine/blob/ea47b5f94d4b8e6b2c898af1a856a278c03fc807/themes/ee/asset/javascript/src/fields/file/cp.js#L17-L18

For example, Bloqs as you know leverages a lot of native Grid functionality and has it's own view files that closely mimic Grid's views, but has some additional code in them, such as hidden fields to save Bloqs specific data. In my case I had a couple of hidden fields inside an div that was rendering a File field. These JS selectors broke down b/c it found the first hidden element, regardless of what it was, and assumed it was the correct thing to be selecting. I was able to fix the issue by moving the hidden fields in the Bloqs' view files to the end of the divs.

**Environment Details:**
 - Version: 5.1.2

**Possible Solution**
Add more specific class selectors to these critical elements that events and DOM modifications are being applied to so there is no chance it will select the wrong element. For example, instead of writing:

```
input_value: fileField.find('input:hidden').first(),
```

Change it to

```
input_value: fileField.find('.some-unique-selector'),
```

This could easily affect other 3rd party devs who may choose to use native services down the road. If EL decides to refactor the HTML views the JS will need to be updated accordingly b/c the selectors are relying on DOM order of elements too much.

**Comment by kevincupp** [comment]
We're not too jazzed about the reason of add-ons changing our markup being a need to do this, we want to discourage that, but we'll make the change for our sake in case of a refactor, as you said. I've been wanting to rewrite the File UI as a React component to mitigate some of this, there's too much manual/procedural DOM manipulation and duplicated view logic between server and client side there.

**Comment by litzinger** [comment]
Bloqs doesn't change any EE markup, it just has view files that share similar markup as Grid/Fluid to visually display the fieldtype (styleguide and all), but has its own hidden fields, which were causing the problem when a File field was inside of a block (similar to a Grid row). I was able to circumvent this issue by just moving my hidden fields to a different spot in the markup.

After seeing your commit I could/should have submitted a PR... didn't realize how minimal the changes were... thought I'd have to poke around in a lot more files to change it.
