### ISSUE TITLE
Channel Form: Select "Relationships" Not Saving

### ISSUE THREAD

**Issue by nickpuglisi** [ExpressionEngine/ExpressionEngine#762]
Hey there, 

Noticing this issue from EE5 and now EE6. When using Channel Form and using the provided code to supply with a single-selection from a Relationship. 

Using this code: 
`<select name="my_field_name" id="my_field_name">
        {options:my_field_name}
            <option value="{option_value}"{selected}>{option_name}</option>
        {/options:my_field_name}
    </select>`

And replacing **my_field_name** with my actual relationship field, upon submitting it does nothing and does not save front-end or backend.

**Comment by stephengalbraith** [comment]
The docs should be an answer to your question given the code you provided: https://docs.expressionengine.com/latest/channels/channel-form/fields.html#relationship-field

`<select name="my_field_name[data][]" id="my_field_name">
  {options:my_field_name}
    <option value="{option_value}"{selected}>{option_name}</option>
  {/options:my_field_name}
</select>`

the name of the relationship field should be accepting an array: "my_field_name[data][]"

**Comment by intoeetive** [comment]
Thanks @stephengalbraith !

@nickpuglisi can you confirm that solves your issue?
