### ISSUE TITLE
Icons missing on addons page

### ISSUE THREAD

**Issue by kippenblinky** [ExpressionEngine/ExpressionEngine#763]
Just installed EE 6.0 and when I go to the Addons page all the icons are missing.
![Screen Shot 2021-01-07 at 15 22 56](https://user-images.githubusercontent.com/45204314/103904480-9c0d5700-50fd-11eb-9b1c-059606399899.png)

**Comment by intoeetive** [comment]
@kippenblinky I was only able to replicate this issue when having `index.php` poiting to wrong system directory path. Is this by chance your issue as well?

If not, can you tell us more about your setup (e.g. fresh install or update, where is the system directory, whether you renamed any files, is this MSM etc.)

**Comment by kippenblinky** [comment]
That was the issue. Thanks
