### ISSUE TITLE
URL in comments is neither shown nor editable (in CP)

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#766]
**Description of the problem**
Title says it. 

There is a bullet point below the mail address, but the URL is not shown.

The possibility to edit the URL is a feature that once existed and everyone asks about.

**Comment by silenz88** [comment]
Concerns EE5, btw.

**Comment by silenz88** [comment]
Also applies to EE6

**Comment by intoeetive** [comment]
This has been fixed in EE6
