### ISSUE TITLE
Setting the 'search excerpt' field in a Fluid field

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#767]
In the channel settings, you can select a Fluid field to use as the 'search excerpt'.  When you do, it will combine all of the fluid field's field's data to make the excerpt, which is likely not desirable.

For example, I had an entry with a fluid field that had to textareas and a grid with several text fields.   My excerpt looked like:

`I have booty in my content Some more fluid content. tradd ct stuff||seriouslies|mind|`

The pipe separated is the content of the grid field.

On possible solution would be to show all of the fields in the grid field in the excerpt selection and you select on of those, rather than the whole fluid field.  Which still leaves you with the issue of having multiple fields, but one possibility would be to just use the first field of that type and no others.

In any case, the current behavior can be problematic.

**Comment by intoeetive** [comment]
I think we should only allow fields that hold text-like data to be used as search excerpt. Not ones that hold array-like data, such as Fluid, Grid, Relationship, or even Checkboxes.

And maybe just the ones that are marked as searchable.

@bryannielsen I'd like to hear your thoughts on this too
