### ISSUE TITLE
CP login > Label on submit button is not translated after submit

### ISSUE THREAD

**Issue by appricosa** [ExpressionEngine/ExpressionEngine#768]
Refers to file
**system/ee/ExpressionEngine/View/account/login.php** line 34

I have been trying to translate the "authenticating ..." label that show up during the login process.
Editing the CP translation file had no effect, so I had a closer look at the login template.

`<fieldset class="last">
			<?=form_submit('submit', $btn_label, 'class="'.$btn_class.'" data-work-text="authenticating..." tabindex="4" '.$btn_disabled)?>
		</fieldset>`

As you can see, the label "authenticating..." is outside of any lang()-Function and is just entered as plain text, no wonder it doesn't change on language switch.

It does work however, after I change that line to the following:

`<?=form_submit('submit', $btn_label, 'class="'.$btn_class.'" data-work-text="'.lang('authenticating').'" tabindex="4" '.$btn_disabled)?>`

**Comment by ops-andy** [comment]
fixed in 6.0.1
