### ISSUE TITLE
Search Templates field is missing when you open a template

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#774]
I do not know if it's a bug or not so I'm creating this feature request.
I was nice in version 5 to search in templates from an opened template. The field is now gone when you open one.

**Comment by ops-andy** [comment]
@digicali the current implementation of this is to simply press ctl+f (cmd+f) to open the search bar.

![image](https://user-images.githubusercontent.com/55093827/114090118-019beb80-9885-11eb-91ad-7fac871e82a6.png)
