### ISSUE TITLE
Update resize_crop EE 6 image manipulation for more control in creating a sized thumbnail for template use.

### ISSUE THREAD

**Issue by aasun** [ExpressionEngine/ExpressionEngine#778]
This is a repost of the original feature request updated now that EE6 has a resize_crop image manipulation.
https://github.com/ExpressionEngine/ExpressionEngine/issues/79

**Is your feature request related to a problem? Please describe.**
In responsive, mobile-first design, it's often desirable to have images that are the same proportion to one another. In many "listing" types of pages, responsive layouts can end up looking very wonky on certain displays if the entry images are not consistently the same width and height. The new resize_crop image manipulation for EE 6 is a step in the right direction, but the size only resizes the image to "contain" within the defined size, where it should have an option to "fill" within the defined size.

**Describe the solution you'd like**
Just add an additional parameter to specify this behavior to scale the image to fill that width/height... then the crop would simply crop off the extra.. (that extra would only be top/bottom or left/right).

**Describe alternatives you've considered**
I have used CE Image for years and years for this functionality, as it uses the default file field, and operates on the templet.  This is not always ideal, as the initial template load can be bogged down the first time a sized/cropped image is created.  And,  it seems to be no longer supported/developed (though it does work with EE6 for now).  You can also use Ansel and Channel Images for this workflow. But those are much larger add-ons and entire file field replacements.  So, they aren't the best fit for this simple manipulation/thumbnail creation.

**Comment by intoeetive** [comment]
@aasun since we already have issue on GitHub for this, can you post this as comment on https://github.com/ExpressionEngine/ExpressionEngine/issues/79 instead? I'll have to close this one as duplicate.

And would you by chance be willing/capable to work on this if it gets formal approval?
