### ISSUE TITLE
Unable to use One Click Update in EE 5.4

### ISSUE THREAD

**Issue by tymrtn** [ExpressionEngine/ExpressionEngine#779]
**Description of the problem**
No One Click Update available in EE5.4 install

**How To Reproduce**
1. Update to EE5.4 from EE5.3.2
2. Observe absence of Update button.

**Screenshots / Videos / Template Code**
Screenshot: https://share.getcloudapp.com/qGulWONR

**Environment Details:**
 - Version: 5.4
 - PHP Version 7.1

**Comment by intoeetive** [comment]
Thanks for reporting this @tymrtn 
We have seen this issue when "New version check" is set to Manual. In that mode, you can only get update link by clicking "Check Now" button in CP settings.
We don't qualify this as a bug, so closing the issue.
If you disagree, please reopen with more comments.
Thank you!

**Comment by tymrtn** [comment]
Is this documented? I can't find anything about it anywhere.

**Comment by intoeetive** [comment]
Not really. The only mention is this: https://docs.expressionengine.com/latest/control-panel/settings/general.html#new-version-auto-check
