### ISSUE TITLE
Exception when I delete a member

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#783]
When i get spammers trying to register with some kind of username, I got this exception if I want to remove them

Exception Caught
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'recent_member' at row 1:
UPDATE `exp_stats` SET `total_members` = 90, `recent_member` = 'Your Prize to 5OOOO USD!\n https://johr.page.link/SCPw', `recent_member_id` = 199
ee/legacy/database/drivers/mysqli/mysqli_connection.php:117

Stack Trace: Please include when reporting this error
#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('UPDATE `exp_sta...')
#1 ee/legacy/database/DB_driver.php(270): CI_DB_mysqli_driver->_execute('UPDATE `exp_sta...')
#2 ee/legacy/database/DB_driver.php(180): CI_DB_driver->simple_query('UPDATE `exp_sta...')
#3 ee/legacy/database/DB_active_rec.php(1477): CI_DB_driver->query('UPDATE `exp_sta...')
#4 ee/legacy/libraries/Stats.php(276): CI_DB_active_record->update('stats', Array)
#5 ee/ExpressionEngine/Model/Member/Member.php(488): EE_Stats->update_member_stats()
#6 [internal function]: ExpressionEngine\Model\Member\Member::onAfterBulkDelete(Array)
#7 ee/ExpressionEngine/Service/Model/Model.php(885): forward_static_call_array('static::onAfter...', Array)
#8 ee/ExpressionEngine/Service/Model/Query/Delete.php(130): ExpressionEngine\Service\Model\Model::emitStatic('afterBulkDelete', Array)
#9 ee/ExpressionEngine/Service/Model/Query/Delete.php(97): ExpressionEngine\Service\Model\Query\Delete->deleteCollection(Object(ExpressionEngine\Service\Model\Collection), Object(ExpressionEngine\Service\Model\MetaDataReader))
#10 ee/ExpressionEngine/Service/Model/DataStore.php(282): ExpressionEngine\Service\Model\Query\Delete->run()
#11 ee/ExpressionEngine/Service/Model/DataStore.php(258): ExpressionEngine\Service\Model\DataStore->runQuery('Delete', Object(ExpressionEngine\Service\Model\Query\Builder))

**Comment by ops-andy** [comment]
fixed in 6.0.1
