### ISSUE TITLE
Warning about unsaved changes

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#785]
Noticed that EE doesn't warn you about unsaved changes when you leave or close the page.

**Comment by shbchk** [comment]
Thanks for accepting , Yuri!

**Comment by shbchk** [comment]
Hmmm. Issue is closed, but i still can leave (or accidently close) the publish page when there is unsaved changes

**Comment by intoeetive** [comment]
The issue has been closed automatically because the code has been merged into main branch. It is however still pending release

**Comment by shbchk** [comment]
Okay, thanks for clarification, Yuri!
