### ISSUE TITLE
Page moves to the top after saving new entry in a relationships modal

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#786]
... so you have to scroll down to the field again. Here is the video:
https://drive.google.com/file/d/1FnGF_LN2naMobdI0skPUSyBdnlGcotmy/view?usp=sharing

**Comment by intoeetive** [comment]
@Yulyaswan can you check whether this is still an issue in latest EE? (and if not, close it)

**Comment by Yulyaswan** [comment]
Yes, it's still here. Will work on it
