### ISSUE TITLE
Textarea row height ignored by new UI

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#789]
Textarea row height (as set in field preferences) is being totally ignored in Edit/New Entry. 

The default height is used regardless of settings forcing my content publishers to keep having to stretch text-areas taller to work on content.

This is extra challenging now that the font in those windows is nice and big.

Let me know if you have any questions.

**Comment by intoeetive** [comment]
The "height" parameter for the field configuration is really representing the minimal height of the field (when there is little or no content)

As the editor keeps adding content the height is increasing so it might become too big indeed.

Do you feel like there's a need for a separate "max-height" setting? Or switch to make the field fixed or flexible height?

**Comment by PDXMan1** [comment]
Hi Yuri,

We like being able to set the min-height for a text area based on the type of content we anticipate it will be used for. 

If you look at this event calendar posting, the Street Address field is only a few lines tall, the Cost of Event field is a little taller, and the Long Description field is the tallest. 

We like being able to give our clients enough height to add the typical amount of information that will go in each field, but not make the field too short (as then they have to scroll or stretch it to see what they've entered), and not too tall (as then the entry page becomes too tall when there are several fields).

In EE v6.0.x, all text areas are displaying the same height, and that's too high for a Street Address, and not high enough for the Long Description fields. It's also making some entry edit pages really long, with lots of scrolling.

I think the way it's worked in EE in the past was just fine, only EE v6.0.x isn't honoring the height settings when the site has been updated from v3, v4 or v5.

Does that help answer your question?

![screencapture-wvdo-or-org-edit-php-2021-02-02-11_58_56](https://user-images.githubusercontent.com/6145078/106655342-1343d880-654e-11eb-80fa-0098473c110f.png)

Thanks for looking into this for us!

- Kurt

**Comment by intoeetive** [comment]
@PDXMan1 I think I might have confused textarea with RTE here.

I can't replicate this issues with Textareas. I created 2 textarea fields, of height 10 and 20, and they are displayed like that.

Can you confirm your issue (same height for every field) is with textarea fields? Does this happen with new textarea fields or only with those migrated from older EE version?

**Comment by PDXMan1** [comment]
Hi Yuri,

The Event Location textarea is set to 60 rows and the Event Description textarea is set to 16 rows. The Contact Information textarea is set to 6 rows. If you look at the attached screenshot, they are all the same height in the UI. These are new fields and the HTML is correct:

`textarea name="field_id_23" cols="90" rows="60" value="" dir="ltr" class="" data-markitup="yes" `

I'm guessing that there's some java-script that resizing the field height after the field loads.

![screencapture-salemacademy-org-new-edit-php-2021-02-15-10_34_35](https://user-images.githubusercontent.com/6145078/107982775-82bbbe00-6f79-11eb-822f-60dc6a00eb77.png)

**Comment by intoeetive** [comment]
Thank you - I have been able to replicate this with HTML Buttons added (that was the missing puzzle piece)
