### ISSUE TITLE
Edit publish layout: do not refresh the page on tab deletion

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#791]
When you delete a tab, the page refreshes without saving changes. This is very frustrating, as you can lose a lot of work without warning or confirmation.

**Describe the solution you'd like**
Best solution: Allow tab deletion without refreshing the page or submitting the form.
Alternative solution: Insert a confirmation that lets the user know they're about to refresh the page and may lose un-saved work.

**Comment by intoeetive** [comment]
@Yulyaswan is this something you can work on? The reload only happens if you add a tab and delete it prior to saving the layout, so I think this is Javascript issue
