### ISSUE TITLE
Edit publish layout: allow tab renaming

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#792]
Because I can't rename existing tabs, I have to delete existing tabs, then create a new one. This means I have to move fields out of the existing tab, create a new tab, then move fields into the new one (or alternatively create the new tab first, then move fields to it, then delete the old one).

**Describe the solution you'd like**
Allow users to rename tabs.

**Comment by shbchk** [comment]
I second that 
https://github.com/ExpressionEngine/ExpressionEngine/issues/685

**Comment by intoeetive** [comment]
I'm closing the other issue (https://github.com/ExpressionEngine/ExpressionEngine/issues/685) as this one has more details.

If we give this approval, would any of you be willing to work on this feature?

**Comment by shbchk** [comment]
I'd love to, but i have no such skills =\

**Comment by intoeetive** [comment]
@Yulyaswan is this something you could work on? I think we'd need a pencil icon and open modal upon click, however I'm not sure if editing tab name before saving would not cause data loss...
