### ISSUE TITLE
Edit publish layout: add "note" or "section title" objects

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#793]
Sometimes tabs aren't sufficient for organizing fields in a publish layout. 

I really like the features of the Publish Notes addon (https://github.com/amphibian/publish_notes.ee_addon) — namely allowing me to place arbitrary chunks of text into a publish form — but the workflow and UX aren't great. (This is no fault of the addon dev — the workflow they've created is the best it can be given the nature of the features they're working with.)

**Describe the solution you'd like**
When editing a publish layout, I'd like to be able to add notes or section titles in the same way that you can add tabs. The notes and section titles would be positionable like fields, but only available to the layouts they exist in.

**Comment by intoeetive** [comment]
I have two ideas around that:
- on edit layout page, add textarea on top of each tab that would contain "tab notes"
- introduce "instructions" fieldtype that could be placed anywehere on the page and hold non-editable instuctions

**Comment by murtaugh** [comment]
Right on, that’s so cool!

I bet there are more ways to engage with content creators, but this is great — as a Crouton user, I really wanted to be able to see at a glance where each recipe comes from.


— Tim

**Comment by intoeetive** [comment]
This will be resolved with adding "Notes" fieldtype in EE 6.3.0
