### ISSUE TITLE
Wrong ACT value being passed to native email form

### ISSUE THREAD

**Issue by blue-dreamer** [ExpressionEngine/ExpressionEngine#794]
**Description of the problem**

The wrong ACT value being passed to the ACT field using native email form:

`<input type="hidden" name="ACT" value="{AID:Email:send_email}" />`

**How To Reproduce**

Email form is added inside a channel entries tag (single entry), I'm passing the entry Title as the email Subject in a hidden field.

The single entry template is cached.

**Error Messages**

No error message but on submit get a white screen. Email does not send.

** Basic template code **

```
{exp:channel:entries channel="services" disable="{tv_disable}" limit="1" require_entry="yes" status="not closed"}

  <h1>{title}</h1>

	<h2>Enquiry form</h2>
	{exp:email:contact_form user_recipients="no" recipients="REDACTED" charset="utf-8"}
	<input type="hidden" id="subject" name="subject"  value="{title} enquiry">
		<p>
			<label for="name">Your name <span class="required">*</span></label>
			<input type="text" id="name" name="name" value="" required>
		</p>
		<p>
			<label for="from">Email address <span class="required">*</span></label>
			<input type="email" id="from" name="from" value="{member_email}" required>
		</p>
		<p>
			<label for="message">Message <span class="required">*</span></label>
			<textarea id="message" name="message" required></textarea>
		</p>
		<p><button type="submit" class="btn btn-pri btn-m">Send message</button></p>
	{/exp:email:contact_form}

{/exp:channel:entries}
```

**Environment Details:**
EE5.4.0
PHP7.2

**Comment by intoeetive** [comment]
This could be related to missing record for `send_email` in `exp_actions` table.

Closing this issue as we did not get any reliable way to replicate this
