### ISSUE TITLE
Validate Status in Api_channel_entries issue

### ISSUE THREAD

**Issue by erwingeiger** [ExpressionEngine/ExpressionEngine#80]
**Description of the problem**
When I try to update an entry with the Channel Entries API I get an error: "No such property: 'status_model' on EllisLab\ExpressionEngine\Legacy\Facade"
I found out the problem was within the 'Validate Status' section of the function _check_for_data_errors
The following query will trigger the error: 
`$query = ee()->status_model->get_disallowed_statuses(ee()->session->userdata('group_id'));`

status_model is not loaded. 

**Possible Solution**
Add the following code: `ee()->load->model('status_model');`

**Comment by kevincupp** [comment]
What version of ExpressionEngine is this for? As of ExpressionEngine 4, the legacy Channel Entries API isn't viable for inserting/updating entries as it doesn't account for the new database schema. It's recommended you use the `ChannelEntry` model instead.

**Comment by erwingeiger** [comment]
@kevincupp ow okay. Yes it is for version 4/5. I will try to use the new functions
