### ISSUE TITLE
Missing database row when upgrading

### ISSUE THREAD

**Issue by mediagirl** [ExpressionEngine/ExpressionEngine#801]
I upgraded an EE install from EE 2.x to EE 6 today and came across a bug.

After the upgrade, logging into the control panel as the SuperAdmin user (member_id = 1) produced this error:
`Call to a member function getAllRoles() on null`

I resolved the error by adding a new row into the exp_member_data table with the value of "1".

**Comment by intoeetive** [comment]
@mediagirl Can you check if record is present in `exp_member_data` on EE2 site database before the upgrade?

**Comment by mediagirl** [comment]
I just checked and the row for member_id 1 IS NOT in the EE2 database table.

**Comment by intoeetive** [comment]
That should not be the case normally. 
But we'll consider doing sanity check on members when performing upgrade to ensure records that are already missing will be re-created.
As such, classifying this as feature request

**Comment by mediagirl** [comment]
Ah, got it. I'm not sure why the row wasn't present in that table previously. Thank you for taking a look.
