### ISSUE TITLE
Edit Relationships with Channel form - Few issues

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#804]
I'm using the code below to edit the relationship assigned to an entry.

1. first issue, bug:  The order is not saved when the field is edited. Always keep the same order
2. How to display only items in the relationships section that are open? cannot find a way
3. How to display the content of a field in the relationship section. cannot find a way. 
4. How to display the relationships that are owned by the current user. Right now, data from other users is also displayed.

```
{exp:channel:form channel="channel_name"  entry_id="{segment_2}" }
{options:fd_relation_field}
                                                  
<input type="text" class="form-control form-control-sm" name="fd_relation_field[sort][]" value="{option_order}" />
<input type="checkbox" class="custom-control-input" id="customCheck{option_value}" name="fd_relation_field[data][]" value="{option_value}" {checked}/>
<label class="custom-control-label" for="customCheck{option_value}">{option_name}</label> 
<br><br>
                                                     
{/options:fd_relation_field}
{/exp:channel:form}
```

**Comment by digicali** [comment]
Update, we solved the problem with a tricky solution but the ticket should move as feature request to make it more simple. What we did? we replaced the title of relationships with custom tags to handle all cases :-)

**Comment by digicali** [comment]
Update: there are stil issue with the order field. Detected something. If the items are not assigned yet, values of order field are skipped. Also, many times, when you just want to change the order, it just doesn't work. You enter values and save but still the previous order.

**Comment by intoeetive** [comment]
It appears that support for `sort` input on relationship was removed back in 2016 (!) - https://github.com/ExpressionEngine/ExpressionEngine/commit/fba32c6b630c55d6291e9b7d9e86ef4ce95c0db7

The sorting order is set based on the order `data` is POSTed (so you might need some JS if you need to change that)

And docs have not been updated on this 

We need to either remove it from the docs, or add support for it back again, or provide another solution

**Comment by intoeetive** [comment]
@Yulyaswan do you think you could write an example for Relationship field implementation for Channel Form using SortableJS? For our user guide. Something that would look a bit similar to how it looks in the CP, with screenshots etc
