### ISSUE TITLE
CSS Bug with Control Panel in 6.0.1

### ISSUE THREAD

**Issue by dpkingjr** [ExpressionEngine/ExpressionEngine#811]
After fresh install of 6.0.1 control panel has RED background color on several pages. When looking at the CSS inspector in Chrome 87, I can see a button class that looks to be over-broad. See attachment.
![2021-01-24_13-51-19](https://user-images.githubusercontent.com/362308/105748536-47951480-5f10-11eb-998f-747b82c72ae2.png)

**Comment by intoeetive** [comment]
@grimsmath this must be caused by one of your Chrome extensions. Can you let us know which ones you have installed? And whether disabling any of those is helping to solve the issue?

**Comment by dpkingjr** [comment]
Found it. It was a browser extension.

**Comment by intoeetive** [comment]
@grimsmath can you tell us which one was that?

**Comment by dpkingjr** [comment]
It is this extension: 
![2021-01-25_13-42-39](https://user-images.githubusercontent.com/362308/105750840-38639600-5f13-11eb-99e5-34495e19ad11.png)

**Comment by dpkingjr** [comment]
I just uninstalled it and the problem went away. Re-installed it to see if the problem came back and it did.

**Comment by intoeetive** [comment]
Thank you! We'll investigate to see if we can avoid conflicts

**Comment by intoeetive** [comment]
This has also been reported in https://github.com/ExpressionEngine/ExpressionEngine/issues/629
Fix will be provided in next release
