### ISSUE TITLE
Cannot Login after changing cookie domain

### ISSUE THREAD

**Issue by digicali** [ExpressionEngine/ExpressionEngine#813]
Maybe the cookie domain field should be validated to be a domain. is it mandatory?
I put just a name on cookie domain that was not related to the website.
Like MySuperCookie
And then after saving and editing few other things, I was logged out.
Impossible to login again. No matters the browser, clearing cache, cookies, etc.
I had to go to the database and edit the cookie domain field as an empty field to be able to login again.
Maybe adding the settings to config.php can help

**Comment by ops-andy** [comment]
you can already set the cookie domain via Config System Override. https://docs.expressionengine.com/latest/general/system-configuration-overrides.html#cookie_domain .
Feel free to let us know if you have any issues with that.
