### ISSUE TITLE
Replace obsolete captcha with Google captcha

### ISSUE THREAD

**Issue by benya** [ExpressionEngine/ExpressionEngine#822]
Captcha which is now practically useless in our time. It is better to replace it with Google or any other analogue

**Comment by jcogs-design** [comment]
If we are going to do this, it would be even more functional to see if the "snaptcha" addon can be integrated with EE6 - and so side-step the need for catpcha's completely!  

https://putyourlightson.com/plugins/snaptcha-ee

**Comment by blue-dreamer** [comment]
Whatever Captcha system is used it should be privacy focused and not leak data to 3rd parties outside the EE ecosystem.  Many countries now have privacy laws we must adhere to so we shouldn't be forced to use products such as Google's captcha or similar.

A "Snaptcha" type system would be perfect, it would be 1st party code and respects privacy.

**Comment by benya** [comment]
Not without reason it should be Google captcha.

You just need to improve this captcha as it is.

Bots can easily bypass it.

For example, you can replace it with the hidden field "honeypot"

> We say the submission will “fail”, but that’s not exactly true. On the front end it will appear that the form was submitted successfully. However, nothing will get saved and no emails will be sent. This is the key to tricking bots into believing everything went smoothly.

This option works for me on another CMS, and it catches spam many times better than the captcha from EE.
