### ISSUE TITLE
Communicate page in CP, checkboxes disabled

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#823]
Odd one- so on Communicate page, only my Superadmin and my member group are selectable to mail to:

<img width="426" alt="Screen Shot 2021-01-27 at 3 26 28 PM" src="https://user-images.githubusercontent.com/1181219/106049394-105f6880-60b4-11eb-9140-72cd952528b1.png">

I'm not sure why.  I'm also thinking maybe just don't show guest and banned, as it can be confusing.  But then folks get confused if it's not there.  Likewise, pending we may want to allow- could see it either way.

**Comment by intoeetive** [comment]
Roles that have no members belonging to them are disabled in this list. I don't know the logic behind this decision, but no reason to change either.

**Comment by robinsowell** [comment]
Ah- it was that member model bug: https://github.com/ExpressionEngine/ExpressionEngine/pull/868.  I had some groups where the members only had a primary role, and they weren't showing.  Running the update while on that branch solved it.
