### ISSUE TITLE
{exp:stats} tag doesn't work

### ISSUE THREAD

**Issue by benya** [ExpressionEngine/ExpressionEngine#824]
I wanted to display the number of records on the site.

`{exp:stats channel="new"}{total_entries}{/exp:stats}`

and for some reason it shows me the number 23, although in fact in channel 359 there are records

When I go to the statistics module (Tools -> Utilities -> Statistics: ) and there I update the slider, then the site will temporarily show the correct number of entries in the channel, but this is only until I add a new entry to the channel, after that it will show 23 again

**Comment by intoeetive** [comment]
There has been inconsitency here indeed - `{total_entries}` is supposed to represent number of entries that are not closed and not expired.
So the CP action did not generate right results, your correct number is 23.
This will be fixed in next EE release
