### ISSUE TITLE
A random bug editing template name results in failure

### ISSUE THREAD

**Issue by VarenSwaab** [ExpressionEngine/ExpressionEngine#828]
I've reported this bug during the beta but was unable to follow through. Unfortunately, it's still haunting me on an irregular basis. I'm hosting on Nexcess with a standard setup. PHP version is 7.3, EE version is 6.01.

The bug happens when trying to change the name of an existing template. It happens randomly and only affects a few of the templates but on those templates it happens each time. I recorded a screen video to show that when I try to change the name of a template named "new" it results in an error. I then show how I can successfully change the name of another template and have no issues.

I should note that sometimes these templates are open in my text editor over SSH but even if the template is closed the error still happens. It's not uncommon to get this error on freshly made templates that have never been opened in an editor. 

https://user-images.githubusercontent.com/5083862/106212460-88df2b80-617f-11eb-8401-e668968c731c.mov

**Comment by intoeetive** [comment]
@VarenSwaab is this basically same issue that https://github.com/ExpressionEngine/ExpressionEngine/issues/577 ? If so, would you mind adding this video and text as comment on that issue instead?

**Comment by intoeetive** [comment]
Thanks for posting to the other thread! Closing this one as duplicate
