### ISSUE TITLE
exp:search:search_results excerpt tag displaying “xhtml” (as in the field formatting choice)

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#83]
exp:search:search_results excerpt tag displaying “xhtml” (as in the field formatting choice) when there are fewer than 50 words to display AND the textarea (or other field) is within a Fluid field and followed by a Grid.

Fluid Field
- text area (with fewer than 50 words to display)
- grid

We have a fluid field and within it is a textarea followed by a grid field.

Since EE’s Channel settings only show the fluid field as a Search excerpt choice, we couldn’t select the textarea field specifically. When there’s not enough text in the textarea, EE is merging its content with the next field-type in the fluid field (in our case a grid) and it’s wrapping the grid's content with “xhtml” at the beginning and end. 

I think this may have to do with how grid field data is stored, and that EE’s excerpt tag is stripping away html from the grid field that is exposing “xhtml”.

One solution could be changing the channel settings so that we can target a search excerpt field that's within a fluid field, that's also the first of that field type in the entry. So the first textarea, but not the second or third.

What we're doing as a workaround at the moment is using the streeng addon to remove the two "xhtml" instances bookending the search results.

**Comment by derekjones** [comment]
Is the Grid field also searchable? Can you clarify what you mean by being wrapped by `xhtml`, i.e. post a real-world search excerpt as it's being output for you? The searchable data is concatenated in a field that can be easily queried against for accurate results, and the excerpt is built from that. If the literal word "xhtml" is being included there, it makes me wonder if you have a column in your Grid field that is storing that as literal content?

Hopefully those questions can clarify what's going on, but in general it would be best if the issue is described in a way that any contributor has enough information to reproduce the problem. Thanks!

**Comment by PDXMan1** [comment]
Hi Derek, Internally, you may reference support Ticket #98683. I think this screenshot will show you what's up. 
![screen shot 2019-01-08 at 6 33 53 pm](https://user-images.githubusercontent.com/6145078/50872427-8f21c580-1374-11e9-9f5d-88abba0d7b23.png)

**Comment by PDXMan1** [comment]
There may be two parts to this conversation, what's included in searches and what's included in the search excerpt. I may want EE to search every field's content within a fluid field, but that doesn't mean I want every field's content in the search result's excerpt. Nor do I want pipes and "xhtml" showing up as you see in the search result output in the screenshot. That help?

**Comment by derekjones** [comment]
Yes, thanks @PDXMan1. Though the community doesn't benefit from information in internal support tickets. With ExpressionEngine open-source, that's a separate service from the development of the application, and we want to make sure that issues in the public repository are conveyed in a way that any capable contributor can pick up the flag. GitHub issues are not just for EllisLab folk, in other words. Your clarifications are thus appreciated, and I agree it looks like this is 1 part bug (xhtml and piped fields in the output), and 1 part feature request: customizing what fields contribute to the auto-generated `{excerpt}` variable.

That said, both of those could be avoided while retaining your desired feature of fields being searchable without being displayed, if you used only the custom fields you intend to display in the search results. Variable modifiers such as `:limit` can help you with making the content more SERP-friendly.

**Comment by intoeetive** [comment]
Just noting that this is part of larger issue with Fluid fields being used for search excerpt:
https://github.com/ExpressionEngine/ExpressionEngine/issues/767

**Comment by intoeetive** [comment]
It's been a while, but found that is happens if you have a textarea that is not searchable by itself in Fluid that is searchable. I believe the non-searchable fields should not be included in Fluid excerpt
