### ISSUE TITLE
Can't have an RTE and a Wygwam field in the same channel

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#833]
Pretty sure it's a ckeditor collision, as they're using different versions.  In which case...I'm not sure which is actually 'buggy' if either.  It might be handled best by documenting it in Wygwam for v6?

**Comment by intoeetive** [comment]
I'd say for the time being it's best to just add note in Wygwam docs. @TomJaeger - any thoughts here?

**Comment by intoeetive** [comment]
We got this reported in https://github.com/ExpressionEngine/ExpressionEngine/issues/2559 as well. 

I was able to confirm this is collision of CKeditor 4 and CKEditor 5 - you can't have those on same page.

Added this to Wygwam docs: https://github.com/packettide/wygwam/pull/50
