### ISSUE TITLE
ee-sidebar__section-label Developer displaying for empty section.

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#839]
While doing a screen share with a new client this week, I noticed that the section label "Developer" was displayed in the new sidebar with nothing under it. 

When a member's member role doesn't have access to any of the developer tools in EE, perhaps that section label could/should be removed.

**Comment by intoeetive** [comment]
@PDXMan1 can you let us know what EE version you have been using. 
And a copy or screenshot of "Access overview" page for user would be really helpful, if possible (found under Profile -> Administration -> Access overview )

**Comment by PDXMan1** [comment]
Happened in EE v6.0.0 and now in EE v6.0.1 - New install. 
![screencapture-netraising2-edit-php-2021-02-02-11_37_13](https://user-images.githubusercontent.com/6145078/106653352-89930b80-654b-11eb-8160-497ab418bd5c.png)
Didn't even know "Access overview" existed. Nice page.
