### ISSUE TITLE
Email notifications not sent as HTML

### ISSUE THREAD

**Issue by Havsvik** [ExpressionEngine/ExpressionEngine#84]
The auto generated emails (like Forgot password) is not sent as HTML although the setting "Mail format" is set as HTML. The emails that are sent still have the header `Content-Type: ⁨text/plain; charset=utf-8⁩`.

The HTML used to test this:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
 <title>Demystifying Email Design</title>
 <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body style="margin: 0; padding: 0;">
<table border="1" cellpadding="0" cellspacing="0" width="100%">
 <tr>
  <td>
   Hello!
  </td>
 </tr>
</table>
</body>
</html>
```
**Details:**
 - EE version: 5.1.2

----

Any idea why this happens?

**Comment by derekjones** [comment]
Yep, known issue that should be fixed. Those blocks of code simply aren't adding the format preference. It's low hanging fruit, but since it is not backwards compatible (email appearance suddenly changing after an update) it will need to target the `release/6.0.0` for Semver compliance. Thanks!

**Comment by kdesigns** [comment]
Next to this, it would be great to have these templates function like any other template in term of tag parsing.
There is an old add-on that still works that I use called 'parsemail' (https://devot-ee.com/add-ons/parsemail).
I have this add-on installed, then I use an {embed} tag in the forgot password template to include a 'normal' template_group/template to build an email with header/footer/body etc. This way I can re-use my email header/footer and stay DRY.

**Comment by derekjones** [comment]
Agreed, and in fact some of the new modules we're building use a mechanism that allows that (our live [forums](https://expressionengine.com/forums) are using this method, for instance).

**Comment by intoeetive** [comment]
This has been fixed in EE6
