### ISSUE TITLE
The page switcher does not work in search

### ISSUE THREAD

**Issue by benya** [ExpressionEngine/ExpressionEngine#840]
Ignored {paginate} page switch on search results page

```
{exp:search:search_results channel="news" limit="5"}

<p>{title}</p>

<hr>

{paginate}
<p>Page {current_page} of {total_pages} pages {pagination_links}</p>
{/paginate}

{/exp:search:search_results}
```

**Comment by intoeetive** [comment]
According to the [docs](https://docs.expressionengine.com/latest/add-ons/search/simple.html#results) there is no "limit" or "channel" parameter for `search_results` tag. Instead, you need to set parameters on the form tag itself.
