### ISSUE TITLE
Add editable field instructions for the first column in a File Grid

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#843]
Right now, you can only add instructions to the overall File Grid field and **_additional_** columns you add, but there's no way to add specific instructions within the table headers for that first 'File' column, so adding image dimensions for example looks unbalanced and might be missed:

![image](https://user-images.githubusercontent.com/8193519/106521586-ae2faa80-649b-11eb-9865-c8b7f0a7bc54.png)

Could we please be able to add both instructions for the overall field **and** the first row separately?

**Comment by intoeetive** [comment]
Starting with EE 6.3, you can use Notes fieldtype for this

**Comment by pyrobob83** [comment]
@intoeetive I don't see how Notes solves this issue as a 'Notes' field would insert any content above the entire File Grid field.  The request I had was to allow us to add instructions specific to the 'File' column under the word "File", eg:
![image](https://user-images.githubusercontent.com/8193519/187694574-b9ee3eec-8e9b-48c3-915e-42c961002aa0.png)

I understand you wouldn't see that if the File Grid allowed 0 rows and was empty, but it'd still be nice to have the option for the scenarios where at least 1 row is required (which I use regularly).

**Comment by intoeetive** [comment]
@pyrobob83 sorry, I probably did not read your description well enough.

My suggestion was to use Notes as column in Grid, but when I went to make a screenshot I realized that it's not available as Grid column. This is probably something that we need to work on.

But I also see that your request is about a different things. Thanks for the explanation - and reopening

**Comment by pyrobob83** [comment]
Thanks @intoeetive  - yes, adding a Notes field as a column in the grid wouldn't help either.

I can't think of a single instance where I'd use a Notes field as one of the File Grid (or regular Grid) columns though since each column already has the Instructions available (except the File column in a File Grid, which is my issue)... so I wouldn't say you need to worry about making Notes available to Grid/File Grid.

**Comment by intoeetive** [comment]
I have looked into this and making this possible would require too much effort and at the same break the easiness of setting up File Grid field. Getting the instructions in first column is possible if instead of File Grid you use Grid with File being first column

**Comment by pyrobob83** [comment]
Thanks @intoeetive - using a regular grid loses the ability to drag & drop multiple files at once in order to create the rows so it's not a great solution, but I understand if it's not worth the time to find a way to accommodate this.  Thanks for looking into it.
