### ISSUE TITLE
Channel layout categories tag, unparsed cat group name

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#845]
Go to 'Layouts' for a channel, make a new layout, go to the 'categories' tab and the cat group name doesn't display properly:

<img width="610" alt="Screen Shot 2021-02-02 at 2 48 11 PM" src="https://user-images.githubusercontent.com/1181219/106654126-b5bb8600-6565-11eb-8cf7-7a5c3a6d454b.png">

**Comment by intoeetive** [comment]
@robinsowell what do you think would be correct to put in there? For custom fields, we use short field name, but for categories there is no equivalent.

The group name is being displayed correctly in place of "Categories" if you have multiple groups assigned

**Comment by robinsowell** [comment]
I'd probably go with 'Cat Group Name' myself.  So mirror what we do with multiples.

But here's what it was in v5, just says 'categories' and that seems fine too:

<img width="559" alt="Screen Shot 2021-07-28 at 4 30 41 PM" src="https://user-images.githubusercontent.com/1181219/127391790-43005bea-0d8e-486f-a688-452ddb15395e.png">

But purely left to me, I'd make it match what it does with multiple groups and show the name.

</completely not helping at all>
