### ISSUE TITLE
PHP Notice for empty image fields when listing entries in cp

### ISSUE THREAD

**Issue by tewells** [ExpressionEngine/ExpressionEngine#848]
PHP 7.4.2

Control panel > Content > Entries

The following notice is displayed for each entry in Channels that contain an image field that has no data:

A PHP notice is displayed:
Notice
Trying to access array offset on value of type bool
ee/ExpressionEngine/Addons/file/ft.file.php, line 961

Severity: E_NOTICE

The code at fault is the following:
`$out = '<a href="' . $this->replace_tag($field_data) . '" target="_blank">' . $field_data['title'] . '</a>';`

specifically this array value $field_data['title'] is referenced with no check that it is set.

**Comment by TomJaeger** [comment]
Just to confirm.  Is this in ExpressionEngine 6.0.1 ?

**Comment by tewells** [comment]
Yes ExpressionsEngine 6/6.0.1
