### ISSUE TITLE
EE 6.0.1 Url and Path Settings Bug

### ISSUE THREAD

**Issue by yzs247** [ExpressionEngine/ExpressionEngine#850]
Hi! The bug being reported is when you navigate to the settings page>general>url and path settings

In this page I can confirm that under the 'Website index page' has empty slot and if you write down index.php, it will say it is saved but still ita an empty slot.

I have tried to save other options such as change from selected hyphen to underscore and I click save and it was updated.

So the bug here is the option 'website index page' still empty box even if updated with how many text you input on the box resaving it.

Which means template view cant work which means EE 6.0.1 wont work if a new user uses it.

**Comment by intoeetive** [comment]
@yzs247 this migh be the case when your `config.php` file is not writable but you have `$config['index_page'] = '';` set in it. 
Can you check that is the case?
You need to have config.php file writable when changing system settings

**Comment by intoeetive** [comment]
We have been able to replicate this in certain environments. The fix is coming
