### ISSUE TITLE
EE 6.0.1 CP DatePicker - not filtering on change for calendar.

### ISSUE THREAD

**Issue by stephengalbraith** [ExpressionEngine/ExpressionEngine#851]
Browser: Safari 14.0.1; Chrome 88.0.4324.96
PHP: 7.3.11
EE: 6.0.1

I was using the CP DatePicker Filter in an an Addon and noticed it wasn't working. So I went to try it on the Entries listing at /admin.php?/cp/publish/edit and saw it didn't work as expected there either.

When you go to the date filter and want to select a custom date, the calendar drops down normally, but when you select a date the filter does not apply. I tried to hit "Enter" as well to see if it would submit and it did not.

On Chrome the above functionality works as expected and the filter gets applied. **However,** on both Chrome and Safari, if there is a date filter applied the dropdown then does not dropdown on click to change the filter to something else.

There were no errors in my console for this either and no other visible error reporting.

(I tried to take a screen capture but it didn't work unfortunately).

**Comment by stephengalbraith** [comment]
@intoeetive thank you for accepting - I should also add that with the built-in Username filter, if a filter is applied there is no option to remove it like the others (circular badge with an x) - screenshot below. Not sure if this needs another issue opened or not.

<img width="337" alt="Screen Shot 2021-02-05 at 12 43 04 PM" src="https://user-images.githubusercontent.com/45797159/107069302-c52e0f80-67af-11eb-9b9e-177a94832ebb.png">

**Comment by intoeetive** [comment]
That's looks like a separate thing - would you mind creating another issue?

**Comment by ops-andy** [comment]
@stephengalbraith   if you have a chance, can you please checkout Yulya's branch here: https://github.com/Yulyaswan/ExpressionEngine/tree/feature/6.x/search-in-safari and see if that resolves your Safari issues. 
thanks

**Comment by stephengalbraith** [comment]
@ops-andy I set up a new EE install locally, replaced those two .js files in the pull request. The filtering aspect works.

However, once a date is selected, the dropdown doesn't show to change it. It must be firing something (the caret arrow swaps with each click), but not showing the menu.
