### ISSUE TITLE
Comment module, URL-field

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#852]
**Description of the problem**

Since it seems that in EE5 the URL-field no longer exists in the member-profiles (although one is created as custom field when updating from 2.x), **ee()->session->userdata('url')** seems to no longer be a thing.

Hence the user guide needs to be updated here:
https://docs.expressionengine.com/latest/development/legacy/libraries/session.html#user-data-information
and also here:
https://docs.expressionengine.com/latest/comment/form.html

Furthermore, and **that is a bug**, the userdata-url is still used in the comments-module but not working anymore.

- You cannot prepopulate the url-field for logged-in users in the comment-form.

- Logged-in users _cannot post a comment with their URL_, even if they fill out the field manually. If a non logged-in user fills out the field, the url _is_ saved.

**Environment Details:**
 - Version: 5.3.2, likely previous an future versions

**Comment by intoeetive** [comment]
This is likely related to https://github.com/ExpressionEngine/ExpressionEngine/issues/766
