### ISSUE TITLE
webp modifier generates the image using one of the thumbs rather than the original image

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#854]
Guy kept having his {file:webp} images constrained to 750, even though his images were bigger than that.  I couldn't replicate- untill I created a directory file manipulation, and then mine were constrained as well.

**Comment by intoeetive** [comment]
@robinsowell we had this (or similar) issue when directory manipulation was named identical to built-in manipulation ('webp' in this case). This has been fixed in 6.0.1. Can you confirm it same issue - or the images are restricted in size if you have ANY manipulation?

**Comment by jcogs-design** [comment]
Can confirm happening for me too... - have multiple image manipulations defined and it appears to be picking the last one in the list to apply to the image (EE 6.0.6)
