### ISSUE TITLE
The filter/search fields aren't working in Safari

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#861]
The filter/search fields do not work in Safari. Nothing happens when you enter text or hit enter. The dropdown filters work.

**How To Reproduce**

1. Create at least two fields or entries.
2. Try to use the filter/search box.

<img width="635" alt="Screen Shot 2021-02-05 at 2 34 22 PM" src="https://user-images.githubusercontent.com/308752/107080412-3f19c500-67bf-11eb-8f0a-6478970de804.png">

There are no errors in the UI or the console.

**Environment Details:**
 - Version: 6.0.1
 - PHP Version  7.3.26
 - MySQL Version MySQL 5.7.29
 - OS: macOS (latest)
 - Web Server: Apache
 - Browser: Safari 14

**Comment by intoeetive** [comment]
This is going to be fixed with https://github.com/ExpressionEngine/ExpressionEngine/issues/192
