### ISSUE TITLE
Image file fields: display thumbnails in their native aspect ratio

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#867]
I have an entry type that allows for multiple versions of an image to be uploaded. (Manipulations aren't sufficient because of the use cases of the images.) These images have different aspect ratios, and when editing an entry it's unhelpful to work with a series of square thumbnails that give no indication of the uploaded image's aspect ratio.

As an example — all of these images have different aspect ratios, and it would be very helpful if the thumbnails in the publish form reflected that.

<img width="768" alt="Screen Shot 2021-02-08 at 4 15 04 PM" src="https://user-images.githubusercontent.com/308752/107282328-d03fa480-6a28-11eb-831e-1ea379094ec9.png">

**Describe the solution you'd like**
I'd like to be able to define global manipulations via the Content & Design settings. The current thumbnail settings would be the default global manipulation.

Or, via the field editor, I'd like to be able to select a specific manipulation to show in the publish form.

**Comment by andruskalkun** [comment]
Same issue – we have site with extra wide images (like banners) with logotypes on right edge. No way to see if right one has been uploaded

**Comment by intoeetive** [comment]
In ExpressionEngine 7 image thumbs are displayed in original ration. Closing this issue
