### ISSUE TITLE
EE6.0.1, 6.0.2...php 7.3.2+ issue, invalid if 1gb is selected, shows error on ee wizard under memory limit

### ISSUE THREAD

**Issue by yzs247** [ExpressionEngine/ExpressionEngine#870]
![Screenshot_2021_0209_231919](https://user-images.githubusercontent.com/57147963/107391723-f30aaf80-6b33-11eb-8af2-7a3939b775c1.png)
I have to select that inorder to get approval from ee wizard, anything above, will be shown as 32mb memory limit required.

Now that i changed it, i was able to see the index.php under website index page from url_settings.

Im using 6.0.2 now

**Comment by yzs247** [comment]
Im using it as trial but will use it for now, default is 1G.

**Comment by intoeetive** [comment]
I wasn't able to replicate this yet.
Are you doing fresh install, regular update or 1-click update?
Can you also create a file with this code, access it in the browser and let is know the output?
`<?php var_dump(ini_get('memory_limit')); ?>`

**Comment by yzs247** [comment]
I did a fresh install of 6.0.2 and it was same as 6.0.1, so i checked the ee docs, found the ee wizard, tried it, and the problem apparently was the 32mb limit required, so I checked where to changed that on the Cpanel, found the php info, default memory limit 1G, and change that below the default value, then I resetted ee wizard again which made it ok

**Comment by intoeetive** [comment]
Thank you for clarifying that this is problem during installation and not update.

Can you still let us know the output of that code I sent above? (as code or screenshot)

**Comment by yzs247** [comment]
https://yvez.me/index.php/home/check.php

Ok i have again index.php problem i jst found out now, myb its the latest php version?, now it doesnt like 768m...

I have to rechange it now to recheck.

**Comment by yzs247** [comment]
Here is a video...

Part 1
https://youtu.be/kb0KRioyHbI

Part 2 w/ ee wizard confirmation
https://youtu.be/u6R6YcjoRdo

Btw, i have to type in index.php/ on browser from that last comment...video will up soon in 15mins.

**Comment by yzs247** [comment]
I will also ask the hosting dept

**Comment by intoeetive** [comment]
The issue should be irrelevant as of today
