### ISSUE TITLE
EE v6 CP is consistently not loading correctly after upgrades or updates.

### ISSUE THREAD

**Issue by PDXMan1** [ExpressionEngine/ExpressionEngine#872]
So when we run an EE v6.0.x upgrade and/or update, we get kind of knocked out of the CP right at the end of the process. 

1. When there's only ONE EE site running in the hosting account, then the CP doesn't fully render without refreshing the browser.

2. Where there are TWO or more installs of EE (like an EE v3.x running out of the webroot and an EE v6.x in a sub-folder) Then we have to clear out all site cookies, or attempts to reach the EE v6 admin.php address send us to the 404 page of the EE v3 install (outside of the sub-directory).

We've been working this way to do website replacements for many years, and have never run into either of these issues prior to EE v6. These two things have now happened consistently with each and every EE v6 upgrade and update. This time when I ran the update the EE v6.0.2, I had Chromes tools open to see what was going on. This update was for a site in a sub-folder of the webroot, and there is a live site running our of the webroot.

This screenshot shows a bit of the unstyled CP at the top, and the list of files that aren't loading. In this case, edit.php is a renamed admin.php.

<img width="750" alt="Screen Shot 2021-02-09 at 10 41 02 AM" src="https://user-images.githubusercontent.com/6145078/107411481-6cb68500-6ac3-11eb-9c5f-db6a204210ba.png">

Of course, since the CP is unstyled, I don't get the opportunity to tell EE that the site should be "ON" (there's no dialog box), and any attempts to get to the CP somehow turn the site "OFF" (some of which are live sites), which then takes some time to correct as the CP is unstyled at first. 

I'm eager to figure out if this is an EE updater scripting issue, or if I need to disable some security setting during updates or turn off some form of file caching... or what?

**Comment by intoeetive** [comment]
So are you saying only the initial load has this problem, and after hitting refresh it's working as it should?

What version did you upgrade from? Was it midified in any way (mayb using master config or modified index/admin files, etc)?

Are the theme folder path / URL settings correct?

**Comment by PDXMan1** [comment]
If there's only ONE install of EE at the domain, then yes, I refresh/reload the CP and it then renders as expected (except that it's then also tuned off the live site).

If there are TWO installs of EE at the same domain (with the EE6 one in a sub-directory), then I get a 404 from the EE install in the webroot, not the EE in the sub-directory that was receiving the update. I have to clear cookies for the whole domain at this point to get back to the CP of the EE6 site in the sub-directory, so I can turn the live site back on again.

I've had this issue both with upgrades from EE3, EE4, EE5 to EE6, and with updates of EE 6.0.0 to EE 6.0.1 and now EE 6.0.2.

All path / URL settings are correct. The sites run fine, and once I'm back into the CP after an update, the CP works as expected. This is happening on a half-dozen different sites/domains/hosting accounts.

Could "Hot Linking" RewriteCond be causing this?

Or maybe the "admin.php" file got hard-coded somewhere in the updater or something?

We've managed 80 to 160+ EE websites a year for nearly 18 years now, and I've never seen this kind of thing before. That said, I'm known to run into the most obscure of bugs at times. Thanks for helping me think through this one.

**Comment by intoeetive** [comment]
What kind of "Hot Linking" RewriteCond are you speaking about here?

What is your session type set to (cookies/session)? Is it different for CP and site or is it the same?

**Comment by intoeetive** [comment]
@PDXMan1 if you still have this issue with those sites, can you check if there's a mismatch between some path settings as set in `config.php` and as set in `exp_config` table in database (you would need to browse the database to actually see those)

**Comment by PDXMan1** [comment]
I don't think we've run into this for at least a year. Since this was posted over two years ago, we've updated all our sites from php7.x to php8.x so it could have been something to do with older php. We've not made any other major changes to our hosting setup, and all our sites are now in later builds of EE 6 or 7. We may never know the cause of this.
