### ISSUE TITLE
Auto Login & Remember Me Bug - remember_me_ttl config variable not being used

### ISSUE THREAD

**Issue by rowansentesy** [ExpressionEngine/ExpressionEngine#873]
**Description of the problem**
A client was asking us to extend session length to be indefinite (i.e. 1 year) and we added the 'auto_login' parameter to the front-end forms, and also set the 'remember_me_ttl' config parameter to be 1 year. However, we noticed that the remember cookie and the exp_remember_me table did not reflect the 1 year setting we wanted. We investigated the issue and traced it to the file /ee/legacy/libraries/Remember.php

**How To Reproduce**
1. On a front-end login form, add a hidden input 
`<input type="hidden" name="auto_login" value="1" />`
2. In your config file (system/user/config/config.php) add `$config['remember_me_ttl'] = 60 * 60 * 24 * 365;`
3. Clear cookies in browser
4. Open login form, login
5. Check cookies, especially the 'remember' cookie, Expires date will not show desired date set in config variable.
6. Check exp_remember_me table, expiration date for session will not show desired date set in config variable.

**Environment Details:**
 - Version: [e.g. 5.3.2]
 - PHP Version [e.g. 7.2.34]
 - MySQL Version [e.g. mysqlnd 5.0.12-dev]
 - OS: [e.g. macOS]
 - Web Server: [e.g. Docker Linux/unix]

**Possible Solution**
In system/ee/legacy/libraries/Remember.php, change line 37 from:
`$this->expiry = (isset($params['remember_me_ttl'])) ? $params['remember_me_ttl'] : $this->expiry;`
To:
<pre><code>if (ee()->config->item('remember_me_ttl') !== null && ctype_digit(ee()->config->item('remember_me_ttl'))){
    $this->expiry = ee()->config->item('remember_me_ttl');
}
else{
    $this->expiry = (isset($params['remember_me_ttl'])) ? $params['remember_me_ttl'] : $this->expiry;
}</code></pre>

Also, the documentation should be updated to include the 'remember_me_ttl' config override. It exists, but is poorly documented, and from my testing, is not being read for the actual expiration date in the 'remember' functionality.

**Additional context**
We also noticed the discrepancy between 'auto_login' on front-end login forms, and 'remember_me' in CP login forms. Why are these different? It is confusing when sleuthing the code, but if documented properly, might not need to be changed.

**Comment by intoeetive** [comment]
@rowansentesy thank you for looking into this and reporting!

We have core config file related to this, `system\ee\ExpressionEngine\Config\remember.php` - did you check whether it's value is respected? (I have some doubts there, but thought I'd ask before digging too deep into the code)
If yes, you should be able to create `system/user/config/remember.php` with the desired value.

We'd still need to update documentation on this however, but hopefully at least this provides a way to do the things.

**Comment by intoeetive** [comment]
I have tested this and can confirm that setting the value in `system/user/config/remember.php` does the job. Labelling as "needs documentation"
