### ISSUE TITLE
Automatically log out from ee

### ISSUE THREAD

**Issue by ErhanGuneyKaradag** [ExpressionEngine/ExpressionEngine#874]
Operating system : windows 10
Explorer                : Chrome

I log into the control panel and open the website in a new window. I press f12 and change the view to mobile view (ctrl + shift + m). and refresh the page that appears as mobile with f5. When this happens, I log out from the control panel.

[
I videoed the problem and uploaded it to youtube as an unlisted](https://youtu.be/qGgxSGx-Mrk)

i am new this bug reports. 
please forgive my writing format

**Comment by swierczek** [comment]
I don't think this should be considered a bug in EE - this is a side-effect of changing your browser view to Responsive/Mobile. That changes the User-Agent string (and therefore the fingerprint of the device), and therefore counts as a new session. You can confirm by viewing the exp_sessions table after logging in normally and then again in a responsive or mobile view. "iPhone X" mode gives you a UA like `Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/` which is different than the UA of Chrome on Windows.

**Comment by intoeetive** [comment]
@swierczek thank you very much on detailed explanation!
