### ISSUE TITLE
Disappearing Avatars

### ISSUE THREAD

**Issue by EverCherCreative** [ExpressionEngine/ExpressionEngine#875]
Avatar is disappearing on a daily basis. When editing Profile page of Super Admin, upload & saving of avatar works just fine (meaning, I get no errors), but if I log out and leave, then return, the avatar is gone from my profile page and must be re-uploaded. This has happened half a dozen times now. 

EE Version 6.0.2; however, this was happening before the update as well. 

Windows 10 Professional (Up to date)
Google Chrome (Up to date)

**Comment by VarenSwaab** [comment]
I've also had the same experience as EverCherCreative.

**Comment by intoeetive** [comment]
Is the avatar gone just from the avatar edit page, or it also does not show up in top right corner?

**Comment by EverCherCreative** [comment]
Morning! It's disappeared from all instances of visibility within EE - when I first log into the CP, it's missing from the upper right-hand corner, as well as from the "Members" box in the CP dashboard. When I navigate to my profile, it is also gone from that page, where I then must re-upload it. 

Additionally, I cannot get an avatar to display on the posts page using the current avatar tag system. I don't know if the two are related, but thought I'd mention it.  Thanks!

**Comment by intoeetive** [comment]
It this fresh EE6 install or was it updated from EE5 (or older version)?
In the upper-right, do you see default icon or broken image?

**Comment by EverCherCreative** [comment]
This is a fresh install. Rather, I upgraded my fresh 6.0.1 install to 6.0.2 via the CP update link. As I mentioned, however, this issue was happening in 6.0.1 as well. 

When the avatar is freshly uploaded, it absolutely displays as normal in the upper right corner, as well as in the "Members" block. Then, at random times, whether I've logged out or am still logged in & working on the site, it just vanishes and the avatar upload process must be repeated. (YES, I am saving!) 

When it vanishes, there's a broken image both in the upper right corner & in the "Members" block. 

Hope this helps! :)

**Comment by intoeetive** [comment]
I wonder if you have some software outside of EE going to your avatars directory and cleaning it up.

Can you go to CP -> Utilities -> Query Form and run this query
`SELECT id, site_id, name, server_path, url FROM `exp_upload_prefs` WHERE name='Avatars'`
what does it output?

And purely as a guess, is there a chance someone is also using same EE account on the other computer at same time?

**Comment by EverCherCreative** [comment]
Hello again! Zero chance that this is being used on another computer. I don't even have the site online, nor are there any members except myself as the site admin.

Ran the QUERY, and here's what was output:


id | site_id | name | server_path | url
 1 | 1 | Avatars | {base_path}images/avatars/ | {base_url}images/avatars/

Thanks for the help! (I will be AFK for the next few hours, but will check back when I return.)

**Comment by rjpdev** [comment]
I'm having this issue as well and it is quite frustrating when I have to go through and update member profiles for any reason because I *always* forget that it's going to happen (been using EE since v2), and it causes a small panic attack as I re-download and re-upload the image.

I am experiencing this on fresh EE6+ installs, and upgraded EE5-EE6 sites.

Also naming them 1.jpg, 2.jpg, etc. isn't ideal. Why rename them at all? Our members are authors - but their actual avatars don't give any SEO juice because of the naming convention and limitations (separate issue I know). Filename is tiny, tiny thing, but it all adds up.

**Comment by intoeetive** [comment]
Are those single-site or MSM installs?

Also, did you notice any correlation with user actions? E.g. avatar disappears after entry update, or setting change, or profile update etc

**Comment by rjpdev** [comment]
Both single sites and MSMs.

No correlation with any user actions.

No matter what actions precede editing, when I save the member profile via the control panel, the avatar is removed.

**Comment by intoeetive** [comment]
Is "disappearing avatar" still a thing that people are experiencing - or did other updates that we made fix it?

**Comment by rjpdev** [comment]
I just ran a test on 6.4.11, seems to be working fine now.

- I uploaded the avatar, made a change to the bio, avatar remains.
- I navigated away from the members page, then back again, updated bio + username, avatar remains.
- I logged completely out, cleared cookies, then went back in and updated the bio, avatar remains.

Not sure about 7.x+ or < 6.4.11 but 6.4.11 seems to be in good shape at least.

**Comment by intoeetive** [comment]
@rjpdev thank you very much for checking and confirming!
