### ISSUE TITLE
Emojis truncate comments

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#877]
**Description of the problem**

Posting emojis in comments truncates the comment text at the first emoji. 

**Environment Details:**
 - Version: 5.4.0 updated from 2.11.9
 - Collation of tables is utf8_unicode_ci

**Comment by intoeetive** [comment]
Hi @silenz88 - please see this troubleshooting paragraph in the docs: https://docs.expressionengine.com/latest/troubleshooting/installation.html#emoji-support
