### ISSUE TITLE
"New Entry" button on edit list screen should be dynamic

### ISSUE THREAD

**Issue by nep** [ExpressionEngine/ExpressionEngine#88]
**Is your feature request related to a problem? Please describe.**
When you are on the MAIN edit listing, the "New" button (blue, top right) gives access to add to any channel.  Then, when you go to a CHANNEL edit listing, the "New" button is specific to that channel.

However in either case, if you switch the channel listed via the filter, the "New" button remains unchanged, offering a NEW entry of the original listing type, not the current channel listing. That means, you could be viewing only "blog" entries, but the "New" button will be for a different channel.

<img width="752" alt="screenshot 2019-01-11 17 01 31" src="https://user-images.githubusercontent.com/49483/51065530-8faf9b80-15c2-11e9-91e9-453ee19125c7.png">

<img width="257" alt="screenshot 2019-01-11 17 01 02" src="https://user-images.githubusercontent.com/49483/51065531-8faf9b80-15c2-11e9-81ac-672f7026ae8b.png">

**Describe the solution you'd like**
I think the New button should dynamically update based on the "channel" filter, and if the filter is removed, it should offer the "full" version. Note: The header over the table ("All Blog entries") does already update dynamically.

**Describe alternatives you've considered**
It could just always be the static "full" version with the dropdown if you change the filter -- but let's be fancy.

**Teachability, Documentation, Adoption, Migration Strategy**
No documentation changes needed.

**Comment by intoeetive** [comment]
Confirming this is still an issue in EE6

**Comment by intoeetive** [comment]
As of EE6, it is possible to create new entry in any channel by clicking "+" icons in Entries menu in sidebar nav.
![image](https://user-images.githubusercontent.com/752126/130761989-3e199129-eb31-438a-b64d-fe74254b3a89.png)
However keeping this open for further consideration

**Comment by Yulyaswan** [comment]
I'm closing the issue because it's already fixed (on video EE6.4.4)

https://user-images.githubusercontent.com/23382425/212308399-006b3885-cbca-4ab4-8237-71b26e511fab.mov
