### ISSUE TITLE
Guest Slowness -> Fetch Template triggering FileSynced onAfterLoad for all templates user has access to

### ISSUE THREAD

**Issue by joaovideosmart** [ExpressionEngine/ExpressionEngine#885]
Good Morning all,

We carried the upgrade of Expression Engine from v 2.9 to 6.0.2, after a few addons upgrades, the website was running fine. One funny thing, is that, if we are logged in on the website everything runs quick and works like a charm, but if a no logged user clicks (site visitor) through the website it takes an average of 10 seconds to open any page.

We have cleared cache, checked folder permissions, optimize tables, check all addons again, but no luck.

From what it seems, if you are logged in as super admin the number of queries to the database is an average of 50 simultaneous queries, whilst for a no logged user, it does an average of 400 queries to the database when you open a simple page.

After some troubleshooting we found out the issue occurs at legacy\libraries\Template.php -> fetch_template(), more specifically model\Template\Template.php.
fetch_template() is calling getAssignedTemplateGroups() getting all templates user has access to (which doesn’t occur if you are a superadmin) and then to all templates user access to it triggers Template.onAfterLoad (from FileSyncedModel) which then triggers one call per template to the db.
At first sight seems to be an issue with EE6 itself, but it could also be some setting/ configuration on our side that is triggering this behaviour.

We are using EE 6.0.2 with mysql 5.6 running on nginx 1.14.0 with php 7.2 and Ubuntu 18.04.3 LTS.

Thanks.

**Comment by intoeetive** [comment]
Thank you for debugging this @joaovideosmart !
We'll get this fixed in next EE release

**Comment by joaovideosmart** [comment]
> Thank you for debugging this @joaovideosmart !
> We'll get this fixed in next EE release

thanks @intoeetive
