### ISSUE TITLE
Relationship field not functioning.

### ISSUE THREAD

**Issue by kippenblinky** [ExpressionEngine/ExpressionEngine#889]
Ive set up a relationship field called "Related" with a shart name "xxx" and set it to relate from channel "forestillinger"

![field](https://user-images.githubusercontent.com/45204314/107784187-6f2b1000-6d4b-11eb-8773-134e97bc72f8.jpg)

I go to an entry which is in "kalender" and related 4 entries from "forestillinger".

![Screenshot 2021-02-12 at 15 53 39](https://user-images.githubusercontent.com/45204314/107784339-9a156400-6d4b-11eb-9d37-3499b27a3156.png)

I then use this code to output the related entries:

```
{exp:channel:entries channel="kalender" status="" disable="categories|category_fields|member_data|trackbacks"show_future_entries="yes" show_expired="yes"}
{xxx}
 {xxx:title}<br>
{/xxx}
{/exp:channel:entries}
```
Nothing is outputted??

If I use  `{xxx:title}` outside the relationships field pair it outputs the first entry title.

Expressionengine 6.0.2

**Comment by intoeetive** [comment]
@kippenblinky is there a chance the related entries are future or expired?

Relationships do not inherit parameters from `exp:channel:entries` tag and you need to pass them [separately](https://docs.expressionengine.com/latest/fieldtypes/relationships.html#parameters).

**Comment by intoeetive** [comment]
Closing as we did not get any further updates (and also Relationship field received updates since this has been reported)
