### ISSUE TITLE
Search function shows PHP errors after updating to 5.1.2 from 3.5.17 via 4.3.8.

### ISSUE THREAD

**Issue by bron-yr-aur** [ExpressionEngine/ExpressionEngine#89]
**Description of the problem**

After updating EE from 3.5.17 to 4.3.8 then one-click update to 5.1.2, the front end of the website shows PHP warnings (when logged in as super-admin) when using the search function. The search function uses the simple_form code supplied in the EE user guide. This was originally an EE 2.7 website so the code used would date back to that time.

**How To Reproduce**

**Error Messages**

<pre><code>
Warning
Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' (this will throw an Error in a future version of PHP)
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
Warning
idn_to_ascii() expects parameter 3 to be int, string given
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
Warning
Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' (this will throw an Error in a future version of PHP)
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
Warning
idn_to_ascii() expects parameter 3 to be int, string given
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
Warning
Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' (this will throw an Error in a future version of PHP)
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
Warning
idn_to_ascii() expects parameter 3 to be int, string given
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
Warning
Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' (this will throw an Error in a future version of PHP)
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
Warning
idn_to_ascii() expects parameter 3 to be int, string given
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
Warning
Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' (this will throw an Error in a future version of PHP)
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
Warning
idn_to_ascii() expects parameter 3 to be int, string given
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
Warning
Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' (this will throw an Error in a future version of PHP)
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
Warning
idn_to_ascii() expects parameter 3 to be int, string given
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
Warning
Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' (this will throw an Error in a future version of PHP)
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
Warning
idn_to_ascii() expects parameter 3 to be int, string given
ee/legacy/libraries/Typography.php, line 2566

Severity: E_WARNING
</code></pre>

**Environment Details:**
 - Version: 5.1.2
 - PHP Version 7.3
 - MySQL Version 5.7.24
 - Web Server: Apache

**Additional context**

The template code being used for the search function is below (note that this is an excerpt, the rest of the template marks up parts of the website).

<code>{exp:search:simple_form channel="not home_page|misc_content" no_result_page="search/no-results" result_page="search/results" search_in="everywhere" paginate="bottom" results="20"}
  <div class="input-group">
      <input type="text" class="form-control" placeholder="Search for..." value="" name="keywords" id="keywords">
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search holkham-glyphicon"></span></button>
      </span>
    </div>{/exp:search:simple_form}
</code>

The search results template code is:
<pre><code>
<div class="col-sm-7 col-sm-offset-4 main-copy">
       <p>Your search for <i>{exp:search:keywords}</i> found the following {exp:search:total_results} results:</p>
{exp:search:search_results}
<p><strong><a href="{auto_path}">{if blog_title !=""}{blog_title} | Blog{/if}{if subtitle !=""}{subtitle} | {/if}{main_title}</a></strong><br/><b>URL:</b> {auto_path}</p>
 {paginate}
        <p style="margin-top: 25px;">Page {current_page} of {total_pages} pages {pagination_links}</p>
    {/paginate}{/exp:search:search_results}
                </div></code>

**Comment by derekjones** [comment]
Your server's ICU lib is extremely out of date. That constant has been available for many versions in PHP, and UTS 46 Unicode IDNA Compatibility Processing was added ICU 4.6, [released in 2010](http://site.icu-project.org/download/46). Do you know if you are running a standard linux distro or similar? Your very first line of PHP Info (System) can often indicate that.

For an immediate fix, I'd contact your server administrator and ask them to update the ICU libs. But if there's a common distro that's still being deployed and supported we may need to use a workaround.

**Comment by bron-yr-aur** [comment]
That's interesting and surprising. The server was only set up about three years ago and had a number of updates run only recently (PHP and MySQL were updated at my request plus the Plesk interface that I have access to was updated to the current version). Where about would I find the ICU libs? As you've gathered I'm not a tech wizard.

**Comment by derekjones** [comment]
In Developer > Utitilies > PHP Info, do a search on the page for "ICU version". And also go ahead and paste the top line, "System", please. Thanks!

**Comment by bron-yr-aur** [comment]
Many thanks Derek. Yes, the ICU version (hadn't heard of it until now) does seem to be old:
ICU version 4.2.1
ICU TZData version 2009j
ICU Unicode version 5.1 

System: Linux 19628a.th.timico.net 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Jan 4 17:31:22 UTC 2018 x86_64

**Comment by derekjones** [comment]
Likely RedHat or CentOS, they tend to hang on to server libs for a looooong time, but also make updates and patches available reliably.

**Comment by bron-yr-aur** [comment]
Yes, CentOS, Derek. It seems that there might be a "bug" in the particular Plesk PHP7+ compilation on my server. [https://talk.plesk.com/threads/intl-ext-compiled-against-old-icu.346937/](https://talk.plesk.com/threads/intl-ext-compiled-against-old-icu.346937/).
Clearly I should get the server people to update the ICU but in the event that they are slow doing so or there is some issue preventing them updating it, is there anything I can do at the EE end to prevent this? The problem is not a show stopper – the front end search function still works as before and the PHP warnings only appear to me when logged in as super admin and doing a search (which  is not something I would do very often) – but it's one of those niggling things that, once seen, I'd like to resolve.

Thanks for your help.

**Comment by derekjones** [comment]
Sure, one potential workaround would be in your `system/user/config/config.php` file (so it would affect both front and back-end requests), to add temporarily:

```
if ( ! defined('INTL_IDNA_VARIANT_UTS46'))
{
    define('INTL_IDNA_VARIANT_UTS46', INTL_IDNA_VARIANT_2003);
}
```

That _should_ allow PHP to silently use the deprecated and obsolete 2003 variant until your admins can get the ICU libs updated on the server.

**Comment by bron-yr-aur** [comment]
Thank you, Derek, much appreciated. I may end up trying that. Does it need to go anywhere specifically in the config.php or should I just tack it onto the end (before the "/* End of file...." line)?

Incidentally, would it be a really bad idea to turn off the PHP intl extension altogether (which I can do via the Plesk interface)?

**Comment by derekjones** [comment]
Anywhere that you’ll remember to remove it after fixing the underlying issue.

Disabling the intl extension is [highly unrecommended](https://docs.expressionengine.com/latest/installation/requirements.html#php-extensions-recommended) as you will lose expected functionality.

**Comment by bron-yr-aur** [comment]
Hi Derek, looks like INTL_IDNA_VARIANT_2003 isn't very popular either.  I added the temporary code but that too threw up some PHP warnings. :smile:

<pre><code>Deprecated
idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

ee/legacy/libraries/Typography.php, line 2566

    Severity: E_DEPRECATED

Deprecated
idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

ee/legacy/libraries/Typography.php, line 2566

    Severity: E_DEPRECATED

Deprecated
idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

ee/legacy/libraries/Typography.php, line 2566

    Severity: E_DEPRECATED

Deprecated
idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

ee/legacy/libraries/Typography.php, line 2566

    Severity: E_DEPRECATED

</code></pre>

**Comment by derekjones** [comment]
Yeah I was afraid of that. Like I said, PHP 7.2 deprecated using the 2003 variant as the default because it is long obsolete. I’d just put pressure on the host to update those libs.
