### ISSUE TITLE
Issue with relationship output on different browsers? 

### ISSUE THREAD

**Issue by paultz** [ExpressionEngine/ExpressionEngine#898]
**Description of the problem**

**Error Messages**

Iust white screen!

<pre><code>
{exp:channel:entries status="open|featured" channel="smp" limit="5" disable="member_data|pagination"}
  {newl_cag_reports}
    <p>{newl_cag_reports:title}]]></p>
     <p>{newl_cag_reports:url_title_path='reports/view'}</p>
     <p>{newl_cag_reports:url_title_path='reports/view'}#When:{newl_cag_reports:gmt_entry_date format="%H:%i:%sZ"}</p>
      <p>{newl_cag_reports:gmt_entry_date format="%Y-%m-%dT%H:%i:%s%Q"}</p>
  {/newl_cag_reports}
{/exp:channel:entries}
</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: [e.g. 5.3.0]
 - PHP Version [e.g. 7.2]
 - MySQL Version [e.g. 5.7]

**Possible Solution**

**Additional context**

**Comment by kippenblinky** [comment]
This could be the same issue that I'm experiencing : [(/issues/889)]

**Comment by intoeetive** [comment]
I will have to close this as it does not contain sufficient details to replicate. It also has been a while since it has been reported, and we have made significant updates to Relationship field processing since, so it is not relevant.
