### ISSUE TITLE
No Such Property "Session"

### ISSUE THREAD

**Issue by tylonius** [ExpressionEngine/ExpressionEngine#90]
**Description of the problem**
I'm having a similar issue to this one: https://expressionengine.com/support/bugs/22050/TemplateGroup-w-Template-No-such-property-session-on-EllisLabExpressionEngineLegacyFacade

I'm running the wCloner plugin and it's not working. According to the developer, a 500 server error is preventing an EE javascript from loading. When I try to load it myself, I get this error:

> Exception Caught
>No such property: 'session' on EllisLab\ExpressionEngine\Legacy\Facade
ee/EllisLab/ExpressionEngine/Legacy/Facade.php:107

>Stack Trace: hide details
>#0 ee/EllisLab/ExpressionEngine/Legacy/Facade.php(22): EllisLab\ExpressionEngine\Legacy\Facade-get('session')
>#1 ee/legacy/libraries/Functions.php(63): EllisLab\ExpressionEngine\Legacy\Facade->__get('session')
>#2 user/addons/wcloner/ext.wcloner.php(53): EE_Functions->fetch_site_index()
>#3 [internal function]: wcloner_ext->add_wcloner_js()
>#4 ee/legacy/libraries/Extensions.php(243): call_user_func_array(Array, Array)
>#5 ee/legacy/libraries/Extensions.php(138): EE_Extensions->call_class('Wcloner_ext', 'cp_js_end', Array, Array)
>#6 ee/legacy/controllers/cp/javascript.php(193): EE_Extensions->call('cp_js_end')
>#7 ee/legacy/controllers/cp/javascript.php(123): Javascript->_ext_scripts()
>#8 [internal function]: Javascript->load()
>#9 ee/EllisLab/ExpressionEngine/Core/Core.php(189): call_user_func_array(Array, Array)
>#10 ee/EllisLab/ExpressionEngine/Core/Core.php(94): EllisLab\ExpressionEngine\Core\Core-runController(Array)
>#11 ee/EllisLab/ExpressionEngine/Boot/boot.php(151): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request))
>#12 admin.php(143): require_once('...')
>#12 admin.php(143): require_once('...')

**How To Reproduce**
Opening any Channel Listing to edit and/or duplicate entries produces this error and prevents the cloner from functioning.

**Screenshots / Videos / Template Code**
<img width="1122" alt="screen shot 2019-01-15 at 12 11 43 pm" src="https://user-images.githubusercontent.com/1054903/51199566-16b38b00-18c5-11e9-88aa-bebd18954a93.png">

**Environment Details:**
 - Version: 3.5.17
 - PHP Version 7.1
 - MySQL Version 5.1.73
 - OS: Linux
 - Web Server: Apache

**Comment by kevincupp** [comment]
EE 3 has [been retired](https://expressionengine.com/blog/version-3-end-of-life), we recommend upgrading. But either way, the Javascript controller is meant to be low-overhead, so it does not load certain libraries like the session library. If it needs to be loaded, the developer can load it from their add-on.

**Comment by tylonius** [comment]
We’re aware of that. There are some issues with a couple of the third-party plugins that the site uses (primarily CartThrob) that are preventing the client from upgrading.

The plugin developer (Willow Light Studio - https://devot-ee.com/add-ons/wcloner)  is actually the one that referred us to EE.

Is there nothing you can do to help us?

ty

**Comment by derekjones** [comment]
CartThrob is compatible with the latest version, and as Kevin pointed out, the third-party addon can make those resources available at that time if necessary. There isn’t anything that can be done from the application side.

**Comment by derekjones** [comment]
This could cascade into other errors but it’s worth a shot trying to add to the top of `add_wcloner_js()` in the cloner addon:

    ee()->load->library(‘session’);
