### ISSUE TITLE
EE6 Upgrade: Searchable Grid - Search Reindex Warning

### ISSUE THREAD

**Issue by EGM-WEB** [ExpressionEngine/ExpressionEngine#904]
Sites I've upgraded (From EE5 and EE3) to EE6 have a weird bug. Works like This

1. Create New Field (admin.php?/cp/fields)

2. Select Grid Field Type (admin.php?/cp/fields/create)
3. Choose Searchable
![FieldType](https://user-images.githubusercontent.com/79169691/108118002-f5e93100-705a-11eb-9b22-c6c336b6b1e7.PNG)

4. Add Fields (Don't even have to select them as searchable)
![TestField](https://user-images.githubusercontent.com/79169691/108118087-131dff80-705b-11eb-997d-6a98ab676267.PNG)

5. Save

6. 502 Error pops
![502](https://user-images.githubusercontent.com/79169691/108118144-29c45680-705b-11eb-8504-c715723022e9.PNG)

7. Reload page (admin.php?/cp/fields/create)

8. Search Reindex warning
![Reindex](https://user-images.githubusercontent.com/79169691/108118160-30eb6480-705b-11eb-9385-e86abdc67032.PNG)

9. Click "Run the search reindex tool"

10. Run Reindex (admin.php?/cp/utilities/reindex)
![Run](https://user-images.githubusercontent.com/79169691/108118185-3779dc00-705b-11eb-9d69-fb53f1c857d1.PNG)

11. Reindex Complete
![Success](https://user-images.githubusercontent.com/79169691/108118205-3cd72680-705b-11eb-9c82-67167b182cb9.PNG)

Everything is fine then...field is 100% searchable...

**Comment by intoeetive** [comment]
@EGM-WEB do you have access to server error logs to see what went wrong?

Are you including any specific column types into the Grid or just text? Do you have any EE extensions enabled?

**Comment by intoeetive** [comment]
Closing as we did not receive any further information
