### ISSUE TITLE
MSM Toggle in Menu bar resulting in 'You are not authorized to access this page'

### ISSUE THREAD

**Issue by melbazany** [ExpressionEngine/ExpressionEngine#908]
Using ExpressionEngine 6.0.3 with Multiple Site Manager turned on. In 5.4.0, there was no issue with this toggle.

When a Content Administrator is logged into any of the sites, they can individually access the domain/admin.php pages to log into each of the sites. However, if they try to toggle between the sites using the top menu bar links, it results in no access:

![Screen Shot 2021-02-17 at 10 51 42 AM](https://user-images.githubusercontent.com/75503142/108229972-479ec380-710e-11eb-8603-b6e9b3932c26.png)
![Screen Shot 2021-02-17 at 10 51 49 AM](https://user-images.githubusercontent.com/75503142/108229953-42da0f80-710e-11eb-833d-dca951f9b801.png)

Console shows a 403 forbidden error.

The Content Administrators have a Role assigned that has Access CP toggled to on; can confirm that the row for the role_id is found in the exp_permissions table in the DB.

Can confirm that Settings > Security & Privacy > Allow multiple sessions? is toggled on as well.

PHP Version 7.3.23-2+ubuntu16.04.1+deb.sury.org+1
Apache/2.4.18 (Ubuntu)

**Comment by troxellwebdesign** [comment]
Same issue here. Have MSM running and created an Admin role, created user and assigned to Admin role. When testing the user can't switch between sites gives the same error. The mutli_login_sites config is added.

Another issue - User can login to each site separately by domain, but they only haves access to the entries on either one or the other domain, whichever sites role management I saved last.

**Comment by ops-andy** [comment]
confirmed
