### ISSUE TITLE
Faulty date picker?

### ISSUE THREAD

**Issue by bytebaby** [ExpressionEngine/ExpressionEngine#909]
Hi.
I have the update from 6.0.2 to 6.0.3 for various customers, but the datepicker shows the variables for ONE customer, see screenshot. What could be wrong with this website? I deleted caches (including the browser cache). I have set the German and English language packages, but the error remains. What can I do?

![cal](https://user-images.githubusercontent.com/21154749/108261029-56639580-7163-11eb-988f-55a0ec7e1629.png)

**Comment by intoeetive** [comment]
@bytebaby which page is where you see this?

Do you have same issue in English and German?

Also, any chance some file did not upload properly? (specifically wondering about `calendar_lang.php` but could also some something else)

**Comment by bytebaby** [comment]
Yes, same issue in English and German. I also checked the file permissions and calendar_lang.php

But now I've just found the solution. I uninstalled the Channel Images add-on before upgrading, from 5 to 6, but then forgot to delete the folders. I have now done that and now the date display is working properly again. Strange isn't it? :-)

**Comment by intoeetive** [comment]
So which page is where you see this? Entry edit, entry listing, anything else?

**Comment by joshconner** [comment]
> So which page is where you see this? Entry edit, entry listing, anything else?

I'm having the same issue, it's when I edit the entry date, expiration date, or even a date custom field.

**Comment by ops-andy** [comment]
we've had another report of this and are able to replicate it locally.

**Comment by ops-andy** [comment]
This appears to be an issue with Solspace Calendar. 
@joshconner @bytebaby can you please confirm that updating Solspace Calendar resolves this issue.

**Comment by joshconner** [comment]
@ops-andy the update for Solspace Calendar fixed the issue for me.
