### ISSUE TITLE
Date Picker Error

### ISSUE THREAD

**Issue by ashleymspencer** [ExpressionEngine/ExpressionEngine#910]
When picking a date if the date isn't available in the next month then the date selector field picks the next month. 
So- 1/31, Feb has no 31, if you choose a date in Feb, it's going to add a month.  If you start with 1/28, Feb. is fine. 
Please see this video since the bug is very obscure and hard to describe via writing.

https://user-images.githubusercontent.com/78441696/108268500-995d4300-713a-11eb-8b71-fc450e9f07fc.mp4

**Comment by ops-andy** [comment]
replicated in v6.0.3
