### ISSUE TITLE
Not all channel form fields render with {custom_fields} loop

### ISSUE THREAD

**Issue by VarenSwaab** [ExpressionEngine/ExpressionEngine#912]
I have a channel with two field groups associated with it. In the front-end channel form, when I use the {custom_fields} loop to render the all the fields, only fields from one of the field groups render. The odd thing is that the titles of the fields in the second group display but the actual field inputs do not. 

EE 6.03
PHP 7.3
MySQL 5.0

`{exp:channel:form channel="sightings" json="yes" id="publishForm" entry_id=""}		
		
<div class="form-group boxed title-group">
	<div class="input-wrapper">
		<label class="label" for="title">Title</label>
		<input type="text" value="{title}" name="title" class="form-control" id="title" placeholder="Hot guy with mask on T-line" onkeyup="liveUrlTitle(event);">
	</div>
</div>

<div class="form-group boxed">
	<div class="input-wrapper">
		<label class="label" for="url_title">URL Title</label>
		<input type="text" value="{url_title}" name="url_title" class="form-control" id="url_title" placeholder="">
	</div>
</div>

{custom_fields}
<label for="{field_name}">{if required}* {/if}{field_label}</label>
{field_instructions}
{formatting_buttons}

{if error}
  <p class="error">{error}</p>
{/if}

{if text}
  <input type="text" dir="{text_direction}" id="{field_name}" name="{field_name}" value="{field_data}" maxlength="{maxlength}" size="50">
{/if}

{if multiselect}
  <select id="{field_name}" name="{field_name}[]" multiple="multiple">
	{options}
	  <option value="{option_value}"{selected}>{option_name}</option>
	{/options}
  </select>
{/if}

{/custom_fields}

<hr>
</div>
<div class="mt-2">
	<button type="submit" class="btn btn-primary btn-lg btn-block">Done</button>
</div>

{/exp:channel:form}
`

**Comment by intoeetive** [comment]
@VarenSwaab did you check if you have any conditionals missing for the fields that you actually have? I tried using `{custom_fields}{display_field}{/custom_fields}` and fields from both groups are being displayed.

**Comment by ops-andy** [comment]
@VarenSwaab where you able to review this anymore?
