### ISSUE TITLE
Field landing target fails to appear in empty tab when dragging field in channel publish layout screens (CP)

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#913]
If you create a new tab in a publish layouts screen in CP, when dragging an existing field from another tab to that newly created tab, when view switches to the new tab (drag field, then hover over tab label), no 'landing target' is shown for the new field within the tab.
The absence of a landing target makes it tricky to add the first field to an otherwise empty tab: if you don't hit the right part of the view (somewhere near the tab itself) the drag partially fails - the dragged field ends up at the top of the tab you were dragging it from.  
Once one field is in place, the landing target appears as normal.

**Comment by intoeetive** [comment]
@jcogs-design is this problem that you face in EE5 or EE6?

**Comment by jcogs-design** [comment]
Apologies - EE 6.0.2/3.
