### ISSUE TITLE
Confirming member deletion quickly can delete their entries

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#914]
**Description of the problem**
I just ran into an issue when testing member deletion in a local environment. I selected a member to delete, and the modal popped up, then I clicked confirm, but the JS that displays the options to re-assign the member's entries to another member had not initiated/completed yet, so it deleted all the entries assigned to that member.

**Environment Details:**
 - Version: 5.4

**Possible Solution**
Set the confirm button to disabled by default, probably with css, then let the JS enable it so there can be no accidental clicking of the confirm button before the re-assign entries option appears.

**Comment by ops-andy** [comment]
testing in 6.0.3 "Reassign the member's entries to:" was the default option and a password is required to delete the member. 
Closing this as it seems resolved in current version
