### ISSUE TITLE
PHP Err Notice when fluid field element is empty

### ISSUE THREAD

**Issue by jamesseavers** [ExpressionEngine/ExpressionEngine#92]
When a fluid field is left empty, a PHP notice appears if logged in a a Super Admin.

**How To Reproduce**
1. Leave a fluid field blank, like a rich text editor field.
2. Visit the page in a browser to see the warning.

**Error Messages**
ee/EllisLab/ExpressionEngine/Model/Content/FieldFacade.php, line 290

**Environment Details:**
 - Version: 5.1.2
 - PHP Version 7.1
 - MySQL Version 5.4
 - OS: macOS
 - Web Server: Apache

**Comment by derekjones** [comment]
Please include the full error message, not just the filename and line number. Include the stack trace as well please, thanks!

**Comment by jamesseavers** [comment]
Sorry, I haven’t got them and the client sorted the error by removing the field. Add the field back in doesn’t reproduce it!

It was a notice in a production environment so no stack trace I’m afraid.

If I remember correctly, the error was an undefined index on field_id_19 (the field that was empty).

Sorry, I’ll do better next time!


Kind regards,

James

****

James Seavers AKA The Code Guru
SYMPHONY ONLINE

w: http://www.symphonyonline.co.uk
e: james@symphonyonline.co.uk
p: 01380 722142

*****************************************************
w = website  |  e = email  |  p = phone number

**Comment by derekjones** [comment]
Ok thanks James, if you see it again, just reopen this issue with the details, thank you.

**Comment by jamesseavers** [comment]
Will do.

Kind regards,

James

****

James Seavers AKA The Code Guru
SYMPHONY ONLINE

w: http://www.symphonyonline.co.uk
e: james@symphonyonline.co.uk
p: 01380 722142

*****************************************************
w = website  |  e = email  |  p = phone number
