### ISSUE TITLE
strpos() Non-string needles error

### ISSUE THREAD

**Issue by johnnydanger** [ExpressionEngine/ExpressionEngine#920]
I'm attempting to upload MP3 files to a directory on the server—via a File field inside a File Grid if that matters. The error is:

Deprecated
strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior
ee/ExpressionEngine/Library/Mime/MimeType.php, line 114
Severity: E_DEPRECATED

I tried rolling back the server to PHP 7.2 but had issues getting it to work.  At this time I've been unable to find a work around.  I've tried directly uploading the files to the server as well, but receive the same error when trying to sync the file directory.

<img width="879" alt="Needles" src="https://user-images.githubusercontent.com/3619241/109537715-1316fa00-7a74-11eb-89ae-b40415c3dd79.png">

**Comment by johnnydanger** [comment]
Disregard.  I decided to dig deeper and found that there was no MIME type specified in the MP3 file header, which would explain the issue.  Other MP3 files working fine.  File issue, not code issue, thanks.

**Comment by robsonsobral** [comment]
Hi, @ops-andy . I think you should open this issue again. It isn't a matter of the file do not have a MIME type, but the way the type is tested, [using a boolean as second parameter of `strpos()`](https://github.com/ExpressionEngine/ExpressionEngine/blob/b1d679b6c0d47ef432982be89c6b8b62bacc2b9a/system/ee/ExpressionEngine/Library/Mime/MimeType.php#L114):

```php
//try another method to get mime
if ($mime == 'application/octet-stream') {
    $file_opening = file_get_contents($path, false, null, 0, 50);//get first 50 bytes off the file
    if (strpos($file_opening, 'RIFF' === 0) && strpos($file_opening, 'WEBPVP8' !== false)) {
        $mime = 'image/webp';
    }
}
```

Should it not be this way?

```php
//try another method to get mime
if ($mime == 'application/octet-stream') {
    $file_opening = file_get_contents($path, false, null, 0, 50);//get first 50 bytes off the file
    if (strpos($file_opening, 'RIFF') === 0 && strpos($file_opening, 'WEBPVP8') !== false) {
        $mime = 'image/webp';
    }
}
```
