### ISSUE TITLE
Template Editor font size adjustment

### ISSUE THREAD

**Issue by ic360-com** [ExpressionEngine/ExpressionEngine#921]
Being a little bit old school, I generally like to edit Templates using the built-in Editor, rather than export to files.
I'm finding the font size for the Template code a little bit too large.

Would it be possible to add a Setting to the Template Settings for controlling the font size?

I realise I can use the browser font sizing, but obviously this changes all the font sizes (including the menus) when it's just the Template code size I'd like to control.

**Comment by intoeetive** [comment]
We are going to add `codemirror_fontsize` system configuration override for this. I think setting it to value like `0.9rem` would make font size more in line with the rest of text in CP
