### ISSUE TITLE
[EE6] Fluid field with multiple file fields = image duplication

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#922]
EE 6.0.3

Create a file field, add an image field to it.

Go to create an entry.  In the fluid field, choose your file field, drag over an image.  Click to add another file field, it's already got that image in it.

**Comment by PhilBrienesse** [comment]
Also experienced having a grid field (with file fields within it) which is within a fluid field upload images no issue. When i add a new simple file field (not within a grid) to my fluid field and then add an image to that it replaces the images which were in the grid fields so all images within the fluid are the same. If I add images within the grid field though it does not replace all images in the fluid field.
