### ISSUE TITLE
Upgrade still available post-upgrade

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#934]
I upgraded from 6.0.2 to 6.0.3, and the About Panel is still showing an update is available.

<img width="348" alt="Screen Shot 2021-03-05 at 5 21 56 PM" src="https://user-images.githubusercontent.com/308752/110180279-7c31a100-7dd7-11eb-90ad-29737e026f34.png">

Clicking to update again seems to do nothing but refresh you to the CP home page.

**Comment by TomJaeger** [comment]
If you go into your cache folder and delete the "current_version" file and refresh the CP do you still get this message?

**Comment by murtaugh** [comment]
I just checked for the first time since I posted this and it eventually cleared up on its own.

**Comment by TomJaeger** [comment]
Awesome, glad to hear it!
