### ISSUE TITLE
Can't assign custom menu to Role/Group

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#935]
v6.0.3

[Video describes scenario](https://www.dropbox.com/s/fak7jm55z8qebxp/cant-assign-menu-to-role.gif?dl=0)

**Comment by ops-andy** [comment]
@litzinger are you getting any JS errors or anything and have you tried in a browser with extensions disbaled? I cannot replicate what you're showing.
![Peek 2021-03-08 13-32](https://user-images.githubusercontent.com/55093827/110365250-cd79a480-8012-11eb-9a1c-a7925014d93d.gif)

**Comment by litzinger** [comment]
No console errors - tried this in Safari

**Comment by litzinger** [comment]
Same in Firefox

**Comment by litzinger** [comment]
I wasn't able to replicate this in a separate environment, so I'll dig into the original env to see if an add-on is causing the behavior(?)

**Comment by litzinger** [comment]
I couldn't replicate this in a separate environment, but I also disabled all extensions in the original environment, and the issue still occurs ¯\_(ツ)_/¯

**Comment by litzinger** [comment]
Worth noting the environment this is happening on is one that was upgraded from EE5. The environment that I can't replicate it on, is a clean EE6 install.

**Comment by litzinger** [comment]
This is an odd behavior. The first option saves fine, every time, when selected alone. When I select the 2nd one, save, the 3rd one shows as saved/selected. Then I re-save without making any changes, suddenly the 4th one shows as saved/selected, then save again without making any changes, the 5th one shows as saved/selected. I've replicated this numerous times... it just cascades down to the next option.

![saving-meu-set](https://user-images.githubusercontent.com/53965/111178958-9c045a00-8579-11eb-90cb-af9fcbc66876.gif)

**Comment by litzinger** [comment]
While step debugging, I get to this getDirty() check, which is where it returns early before executing the updates

```
class Update extends Query
{
    public function run()
    {
        $builder = $this->builder;
        $object = $builder->getExisting();

        if (! $object) {
            $object = $this->store->make(
                $builder->getFrom(),
                $builder->getFacade()
            );
        }

        $backup = $object->getOriginal();
        $this->prepObject($object);

        // Do not save if the object isn't dirty. We cannot do this in the model
        // because the query builder can accept set() calls. Plus, we always want
        // to cascade to children.
        if (! $object->getDirty()) {
            return;
        }
```

**Comment by ops-andy** [comment]
I've tried replicating on an upgrade EE5 site to no avail. I'm going to keep this open though and see if anyone else can replicate it.

**Comment by robinsowell** [comment]
I can't replicate either- it must be something ... just really odd.  I can't figure how it would error in that particular cascade.  And nothing else on the site is weird?  I sort of think environmental or something 'off' a bit in the database, but I really can't think of anything that would cause it to goober in the way it is goobering.

**Comment by litzinger** [comment]
I think this has something to do with the `id` and `role_id` columns in the `role_settings` table. I tried updating a menu set and assigning it to what is role_id 10, but the `role_settings` table showed the `menu_set_id` column updated the `role_id` 9, not 10, so it's updating the wrong row... is it using the wrong primary key? 

It seemed like it should have updated `id` 9, b/c it was supposed to assign it to `role_id` 10, but instead it updated `id` 8 because it's `role_id` was 9. This would explain the weird off by 1 errors in my original video.

![Screen Shot 2021-04-05 at 11 58 04 AM](https://user-images.githubusercontent.com/53965/113600932-5251e100-9606-11eb-952c-c5a1f3680314.png)

**Comment by intoeetive** [comment]
Since we could not replicate it and got no further reports in more recent EE versions, closing it out.

If the bug persists, please comment and we'll reopen
