### ISSUE TITLE
Link to Config overrides is missing

### ISSUE THREAD

**Issue by stpruss** [ExpressionEngine/ExpressionEngine#940]
In the config.php file,  the link to the list of Config overrides produces a 404 page.

**Comment by PDXMan1** [comment]
This might be the new one: https://docs.expressionengine.com/latest/general/system-configuration-overrides.html

**Comment by TomJaeger** [comment]
Just ran a fresh install and it appears to be present on line 5 of the config file.  @stpruss any chance you can try replicating again?

**Comment by ops-andy** [comment]
This was fixed in a previous commit (https://github.com/ExpressionEngine/ExpressionEngine/commit/017885de1c112742c8dbbb545c6c3ba1ff58d7a4) as well as a redirect added to the docs.expressione.com site.
thanks
