### ISSUE TITLE
Fluid field not working properly EE 6.0.3

### ISSUE THREAD

**Issue by pixelman** [ExpressionEngine/ExpressionEngine#943]
working on a new project with EE 6.0.3
I want to use the fluid fieldtype in a channel called 'portfolio'
But what worked in EE5 does not in EE6.
I started from scratch so I didn't upgrade or use third party add-ons.

So after my channel, I made 3 fields.

- media > file grid
- contentBox > RTF textarea
- layout > fluid

I added both fields to the fluid fieldtype.
In the control panel everything works fine.
But my template does some strange rendering.
This is the fluid field code I used.
 
```
<div class="container">
   {exp:channel:entries channel="portfolio" }

      {layout}
            
         {layout:media}
         <!-- media -->
          {media}
             <img src="{media:file:large}" />
          {/media}
         {/layout:media}
            
         {layout:contentBox}
            <!-- contentBox -->
            {contentBox}
         {/layout:contentBox}
      
      {/layout}
   {/exp:channel:entries}
</div>

```

What happens is that the if I use only one of the fields they work fine, but when I render both fieldtypes in the template. 
I get these EE tags in my output. Like it can't handle or render both. See screenshots.

<img width="1117" alt="Screenshot 2021-03-11 at 13 48 42" src="https://user-images.githubusercontent.com/221232/110789957-bdf79700-8270-11eb-8074-fb009345cd02.png">

<img width="460" alt="Screenshot 2021-03-11 at 13 48 05" src="https://user-images.githubusercontent.com/221232/110789970-c0f28780-8270-11eb-863e-96b9c7b81dcd.png">

<img width="1671" alt="Screenshot 2021-03-11 at 13 47 05" src="https://user-images.githubusercontent.com/221232/110789973-c223b480-8270-11eb-9b19-8d103c7f8f1f.png">

**Comment by CreativePoweredGeek** [comment]
HI, 
I think your Code for Media is incorrect since it is a Grid.

{layout:media}
   {content}
       {content:file:large}
   {/content}
{/layout:media}

BTW… You should join the Slack Chanel…. lots of good answers tothis sort of stuff there.
Hope that helps

Russ

**Comment by stephengalbraith** [comment]
I would also avoid using {layout} as a field name as this is a native EE variable and tag pair for templates which could likely be causing the issue

**Comment by pixelman** [comment]
> HI, I think your Code for Media is incorrect since it is a Grid. {layout:media} {content} {content:file:large} {/content} {/layout:media} BTW… You should join the Slack Chanel…. lots of good answers tothis sort of stuff there. Hope that helps Russ
> […](#)

Thank you very much, this seems to do the solution ;)

**Comment by pixelman** [comment]
> I would also avoid using {layout} as a field name as this is a native EE variable and tag pair for templates which could likely be causing the issue

thanks for the advice… :)
