### ISSUE TITLE
File Product Search 

### ISSUE THREAD

**Issue by ODDCODE** [ExpressionEngine/ExpressionEngine#947]
Uploaded over 1000 images to the file. Enter the name and number of the image and press enter, nothing came back. It was still all the images. Not searching the database.

**Comment by TomJaeger** [comment]
@ODDCODE Thanks for getting in touch about this one.

We had two people run multiple tests on this one and have been unable to replicate it.  Just to confirm.  Did you hit the sync files button?  Also, just to confirm is this is EE 6.0.3?

**Comment by ODDCODE** [comment]
Tom, thank you for your follow up. I am currently on the latest version.  The search function is working when I select the list format but not when the images are displayed.

**Comment by ops-andy** [comment]
@ODDCODE I've been testing this and have also been unable to replicate. I've got a little over 1000 images in a folder. I've tried searching in both list view and in thumbnail view, and have not had any issues. 
Can you review the attached screenrecording and see if I'm missing something? 
If not, do you get any console errors or anything else there? Maybe also review the Network tab in dev console to see if you're getting any 500 errors or something there as well. 
thanks.
![eecore-1073_2](https://user-images.githubusercontent.com/55093827/112181011-69d6a600-8bd2-11eb-8d9e-dada2f97eb64.gif)

**Comment by ODDCODE** [comment]
Yes, I hit the button. Now the search is working.

Thank You.

**Comment by ODDCODE** [comment]
Oh...Would you know when the pro will be released?

**Comment by ops-andy** [comment]
We're hoping to be done with everything and in to testing by the end of the month.  🤞🤞🤞 We'll  update the community on planned release date and such after that. Thanks!
