### ISSUE TITLE
RTE link button in Matrix field produces incorrect output

### ISSUE THREAD

**Issue by tyssen** [ExpressionEngine/ExpressionEngine#949]
When adding a link to text in an RTE field in a matrix, the output on the front end is coming out like `href="{page_7176}"`. 

When hovering over the link in the control panel so the little pop-under appears with the link, and you click *Open link in a new tab*, that actually brings up the correct page. It's only when you visit the page on the front end that the link comes out incorrectly.

RTE fields not inside a matrix work OK. 

The site is running EE 6.0.3 and Matrix 3.3.0. PHP 7.0.33.

**Comment by bakin1999** [comment]
Thanks for the report. This is working fine in the latest release of Matrix. If you still have any issues, let us know at [help@eeharbor.com](mailto:help@eeharbor.com). In future all Add-Ons support should be sent there.
