### ISSUE TITLE
Update EE6 to remove all persistent cookies in default state

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#955]
**Is your feature request related to a problem? Please describe.**
EE mostly uses session based cookies, but sets a number of "Strictly Necessary" cookies that are "persistent" beyond the session.  These are flash (1 day), last_activity (1 year), last_visit (1 year), remember (2 weeks),  visitor_consents (1 year).

The presence of these persistent cookies trips a wire in GDPR - for each of these cookies it is necessary for the developer to provide justification for the need for the persistent cookie and report that the cookie cannot be linked to user activity.  Sometimes these justifications are not heard sympathetically - if the 'strictly necessary' determination is not accepted then these cookies must only be set if a visitor to the site from a GDPR country actively consents.

There is no mechanism in EE either to adjust the duration of these cookies, or to link their creation to active consent.

**Describe the solution you'd like**
An option in EE CP to set the duration of all cookies to be session based by default.

If there are functional benefits to be gained by making any of the cookies have a longer life, this should be a choice that can be made by users and set using the consent features of EE.

**Describe alternatives you've considered**
There are no alternative solutions right now.

**Teachability, Documentation, Adoption, Migration Strategy**
How this gets documented depends on the solution that is adopted.
Provided switching to session duration cookies is not something that breaks EE, there should be no migration issues.

**Comment by blue-dreamer** [comment]
Yes the cookie issue is becoming more and more important in meeting various laws across the globe. More and more governments are introducing privacy/cookie laws of various strengths so we need the ability to be able to micro manage all EE cookies to meet requirements.

Ideally a fresh EE install wouldn't set any cookies by default (aside from CP related cookies which fall under strictly necessary), we'd then be able to enable them as needed with parameters as JCogs suggests, either via the Consent module or implied consent (which can sometimes be fine). 

We need to stay as current as possible with laws. If EE doesn't adapt here it could soon prevent new developers coming on board?

**Comment by jcogs-design** [comment]
building on @blue-dreamer comment there may be a case for EE to put itself at the extreme end of the compliance spectrum since it seems different countries enforce privacy regulations differently - discussion in Slack suggests that GDPR in Belgium and Germany is more stringently enforced than in UK - e.g. apparently logs of all consent decisions (even ones where consent is anonymously declined) are required. Not sure how we find / define the boundary conditions, but probably makes sense for an assumption of 'implement the more private case as a default' and 'keep better logs' options should be general principles to inform decisions.

**Comment by Sungodragon** [comment]
I too would like to disable non essential cookies, 
exp_last_activity,exp_last_visit and exp_tracker
It is marked as 'Enhancement' as there is advanced functionality for handling various cases.

The essential requirement is to disable non-essential cookies irrespective of other advanced functionality.
If a separate issue to have this essential requirement is better, then I can open that issue.
We need this essential requirement of disabling at the earliest.
