### ISSUE TITLE
No longer a link to the custom CP homepage

### ISSUE THREAD

**Issue by amphibian** [ExpressionEngine/ExpressionEngine#959]
In EE5, when a member/member group had a custom CP homepage set, a link to that destination would appear alongside the link to the vanilla CP overview:

<img width="84" alt="Screen Shot 2021-03-24 at 2 30 46 PM" src="https://user-images.githubusercontent.com/53333/112372264-901d4400-8cad-11eb-822b-23448dd9344a.png">

While the old interface certainly is not the best, I _do_ think it's important to have a way to get back to the custom homepage outside of a fresh login. IMO it's confusing for a client to click "home/overview" and end up somewhere different than they do when they login.

(I use this feature in Dashboard Analytics, which I'm currently updating for EE6.)

**Comment by ops-andy** [comment]
This makes sense, especailly since the breadcrumb home button respects the users "Default CP homepage" setting
