### ISSUE TITLE
Add first-party functionality to add notes, instructions, details, content on entry publish pages.

### ISSUE THREAD

**Issue by aasun** [ExpressionEngine/ExpressionEngine#961]
**Is your feature request related to a problem? Please describe.**
There are times when I want to add significant information, instructions, details, or reference materials to an entry publish form for content managers.  The individual field "Instructions" that appear on the publish form is not sufficient, since it is attached to a specific field.  In the past, I've used an add-on like "Publish Notes" to accomplish this.  

**Describe the solution you'd like**
It would be great to have the ability to to add any type of custom content to be displayed on a channel entry publish form as a first-party feature.  It should also be able to be managed in the Publish Layout, just like all other fields and tabs can be.

**Describe alternatives you've considered**
Used third-party add-ons like "Publish Notes"

**Comment by ops-andy** [comment]
duplicates #793
