### ISSUE TITLE
[EE6] Multiple CP keyword search boxes are unresponsive in (MacOS) Safari

### ISSUE THREAD

**Issue by PaulBaileyAtChan** [ExpressionEngine/ExpressionEngine#965]
Multiple keyword search boxes in the EE6 control panel are unresponsive in (MacOS) Safari. The Javascript console doesn't show any errors or warnings. The unresponsive search boxes include (but might not be limited to):

Channels
Files
Members
Member Roles

In each case, the keyword searches work as expected in Chrome and Firefox, and the corresponding searches worked without problems using Safari with EE5 (5.4.2). NB: keyword search boxes for Entries and Templates in EE6 *do* work with Safari — although the Entries keyword search is somewhat glitchy (and isn't part of this issue!).

EE 6.0.3
Safari 14.0.3
MacOS 11.2.3

**Comment by PaulBaileyAtChan** [comment]
Note that, in the Entry Manager, the additional filter boxes within the Channel ('filter channel'), Category ('filter categories'), Date ('custom date'), and Author ('filter authors') dropdowns are also unresponsive in MacOS Safari, I assume for the same reason/s. Honestly, it's almost as if this stuff was never tested in Safari. :-/

**Comment by aasun** [comment]
I have the same issue searching for files using the full file manager, and the file manager overlay in the entry edit form.  Search is not working at all.  Type in a keyword, hit return, nothing/no change. Chrome and Firefox works no issue.

Using EE 6.0.6 and still having these problems.
MacOS 11.4
Safari 14.1.1

**Comment by aasun** [comment]
checking in on this.  This is a significant issue for Mac users that use Safari..  Searching in the CP just doesn't work.

**Comment by ops-andy** [comment]
@aasun @PaulBaileyAtChan if you guys have a chance, can you please checkout Yulya's branch here: https://github.com/Yulyaswan/ExpressionEngine/tree/feature/6.x/search-in-safari and see if that resolves your Safari issues. 
thanks

**Comment by PaulBaileyAtChan** [comment]
Initial testing looks good, yes. FWIW, this is after just grafting the two JS changes into EE6.0.6. I didn't install the entire fork.
