### ISSUE TITLE
Entries > Categories variable pair > {active} tag not working

### ISSUE THREAD

**Issue by rowansentesy** [ExpressionEngine/ExpressionEngine#966]
I encountered a bug and have isolated it, and thought I would share the info with the EE team.

It appears that the {active} tag is not working as documented on this page: 
[https://docs.expressionengine.com/latest/channels/entries.html#active](https://docs.expressionengine.com/latest/channels/entries.html#active)

My template code:
```
{exp:channel:entries
channel="businesses" 
limit="10"
}
    <h2>{title}</h2>
    {categories}
        {if active}THIS category is Active{/if}<br/>
        <a href="{path='site/category_bug'}">{category_name}</a>
    {/categories}

{/exp:channel:entries}
```

This issue persists when 'Category URL' is Titles and IDs.

I would expect the 'THIS category is Active' text to appear when I've clicked on the category href. 

Screenshot: 
https://www.dropbox.com/s/hsgpmoqvav4p9bo/Screen%20Shot%202021-03-26%20at%205.28.26%20PM.png?dl=0

Either the documentation should be updated, or the {active} variable should be debugged.

Environment:
ExpressionEngine 6.0.3

Thanks!
Rowan

**Comment by ops-andy** [comment]
@rowansentesy thanks for taking the time to report your findings. I'm unable to replicate in 6.0.3 though.
I currently am using the code
```
{exp:channel:categories channel='{layout:ch}' style='linear'}
    <li><a href="{path='blog/category/{category_url_title}'}">{category_name} {if active} ACTIVE {/if}</a></li> 
   
{/exp:channel:categories}
```
Which produces a url such as `https://ee60testing.test/index.php/blog/category/personal`

And a menu like this:
![image](https://user-images.githubusercontent.com/55093827/112891957-bfb1bf00-90a6-11eb-8155-70f0772b7212.png)

Just to be sure have you set the Category URL Segment in your  URL and Path Settings? https://docs.expressionengine.com/latest/control-panel/settings/urls.html#category-url-segment

Mine currently like this: 
![image](https://user-images.githubusercontent.com/55093827/112892104-e96ae600-90a6-11eb-8403-238a2752bcbc.png)

thanks!

**Comment by intoeetive** [comment]
The documentation is wrong here. `active` variables is NOT available inside `{categories}` pair in `{exp:channel:entries}` (but listed in the docs). It is however available inside `{exp:channel:categories}` (but not listed in the docs)
