### ISSUE TITLE
Display the full file path/URL in the file manager

### ISSUE THREAD

**Issue by aasun** [ExpressionEngine/ExpressionEngine#971]
**Is your feature request related to a problem? Please describe.**
Clients will regularly want to use a direct URL for a file that is uploaded in the file manager.  To use it for an email or other purpose. But, there is no easy way to get the full URL because the file manager doesn't display this information.

**Describe the solution you'd like**
Add a "link" button under the "manage" column that will just open up the file in a new window/tab so they can copy/paste that URL for use elsewhere

**Describe alternatives you've considered**
I've created an EE template to load and display all files in the upload directories so they can browse and find the one they want.. But that is cumbersome, at best.

![Screen Shot 2021-03-30 at 5 02 00 PM](https://user-images.githubusercontent.com/5115281/113071656-120fe000-917a-11eb-9ce9-47f305d9c781.png)

**Comment by intoeetive** [comment]
Just as a note, link button is already present when you view the file details popup (e.g. click file name or pencil icon)

**Comment by ops-andy** [comment]
adding to what Yuri mentioned, this is the link button when you open the edit dialog. Clicking it will open the file in a new tab where you can copy the URL, or you can use the "Copy Link address" option in most browsers when right-clicking on the icon.
This feature was missing in v5 (maybe even 3-5), but was something we definitely wanted to have back in there for v6.

![image](https://user-images.githubusercontent.com/55093827/113199103-ba827a80-9234-11eb-87de-55bd08c5397e.png)

thanks.

**Comment by aasun** [comment]
Ah!  Perfect. Missed that.  Thanks!
