### ISSUE TITLE
Wrong limit on Entry Manager page when Categories column present

### ISSUE THREAD

**Issue by diarbyrag** [ExpressionEngine/ExpressionEngine#987]
I have a test site running ee 6.0.3, imported data using Zealous Web's Import / Export addon, had a few problems and they are now fixed, however before I reinstalled the updated version I deleted the 31 entries from the first import, cleared all caches and then installed the new version of the app and imported the 31 entries again which had been altered slightly to include statuses and URL_titles.

Imported all 31 perfectly apart from the fact that the channel entries page (cp/publish/edit) only shows 13 entries when it is set to show 25, the drop down set to show 50 only shows 25, set to 75 shows them all, the weird bit is the last option says show all 62 entries, there are only 31 ?

**Comment by diarbyrag** [comment]
Have just tried something different with this issue, I have two channels, one is empty, the other is the test with 31 entries, if I select the actual channel it displays 25 as it should but if I select view all entries it then only shows 13 as above

**Comment by ops-andy** [comment]
@diarbyrag thanks for reporting all this. It's a little tough to replicate and fulyl grok what's going on here. Can you provide some screenshots and or video recordings that help visualize what you're explaning. 
thanks.

**Comment by diarbyrag** [comment]
Hi, yes it is a bit confusing, apologies but anyway hope this works better

In my test site I have 2 channels, education & eat_drink,

There are 31 entries in education and none in eat_drink.

Now the screenshots

01/ click the entries tab in the sidebar and all it shows are 13 entries when it ought to show 25 ?

02/ click the entries tab in the sidebar then click the drop down at the bottom to choose number of entries to show and it offers to show all 62 items when there are only 31 in total ( original 31 were deleted )

03/ click view all and set it so show 50 entries and click view all it shows 25 entries when it ought to show all 31 as there are not 50 anyway ?

04/ however, click the education channel entries tab and it shows 25 as it should.

05/ just to show there are no entries in the eat_drink channel

Tried it in Firefox dev and safari and it does the same so not a browser cache problem I assume.

As I said I have cleared all the ee cache files via the CP.

[screengrabs.pdf](https://github.com/ExpressionEngine/ExpressionEngine/files/6243412/screengrabs.pdf)

**Comment by intoeetive** [comment]
This might be an issue with the import add-on you are using. Try going to your database and checking whether number of records in `exp_channel_data` is matching number of records in `exp_channel_titles`

**Comment by diarbyrag** [comment]
Hi Yuri, thanks for the speedy reply, screengrabs of exp_channel_data & exp_channel_titles results. they both appear to show 31 entries as far as i can see.
I'm no expert on databases I'm afraid so I appreciate all the help.
If you need more please let me know

![Screen Shot 2021-04-01 at 14 20 22](https://user-images.githubusercontent.com/2118777/113300742-25e05100-92f6-11eb-8582-ae9fff0bd2eb.png)
![Screen Shot 2021-04-01 at 14 22 06](https://user-images.githubusercontent.com/2118777/113300746-27117e00-92f6-11eb-96c2-cf228a130b3b.png)

**Comment by intoeetive** [comment]
That looks correct. However you are mentioning "had a few problems" - and I think there might be still someting corrupt.

Would it be possible for you sping up new testing site, do the same import and see if you still have the issue?

**Comment by diarbyrag** [comment]
will do, might not get chance till Sunday but I’ll let you know, thanks
very much Yuri


Gary

*************************************
Gary Braid
01625 560065
07798 743208
*************************************

**Comment by diarbyrag** [comment]
Hi Yuri,

I was checking out my test site today and studying the problem, this is
what I discovered and not sure if that is meant to be correct behavior in
ee6.

Screengrabs attached. I think mystery solved but not sure which behavior is
correct.


In the education channel, there are now 32 entries.

(1) If I set ee to show 25 entries as is the default it shows 13 entries by
Title BUT with the Categories selected to show in the listing there are 25
Categories entries.



(2) Now if I remove the Categories in the listing it shows 25 entries by
Title



So if that is normal behavior then there is no bug, however I always
thought that the entries were only listed by title as one entry can be in
several categories but it is still really only one entry ?

The fact it showed more entries than there are is just that ee appears to
count the categories as separate entries hence 32 actual entries but 65
virtual ones ( one entry is in three categories , all others are in two )

Have I set something wrong in the CP perhaps.

Appreciate your time, let me know what you think.

Thanks
Gary

*************************************
Gary Braid
01625 560065
07798 743208
*************************************

On 1 April 2021 at 16:20:33, Gary Braid ***@***.***) wrote:

will do, might not get chance till Sunday but I’ll let you know, thanks
very much Yuri


Gary

*************************************
Gary Braid
01625 560065
07798 743208
*************************************

**Comment by diarbyrag** [comment]
Hi Yuri,

Have just checked my main clients website, he only has a couple of products
which are in two categories and the entries listing page does the same
thing.

Shows 22 entries with 25 categories not 25 entries by title.

So maybe ee is set to list by entries by categories not just entries by
title ?

Gary

*************************************
Gary Braid
01625 560065
07798 743208
*************************************

**Comment by intoeetive** [comment]
Looks like the screenshots did not come through. Can you post those again?

**Comment by diarbyrag** [comment]
In the education channel, there are now 32 entries.

(1) If I set ee to show 25 entries as is the default it shows 13 entries by
Title BUT with the Categories selected to show in the listing there are 25
Categories entries.
[with Categories](https://user-images.githubusercontent.com/2118777/113837472-ca92e080-9785-11eb-95dc-8fec1a82cea3.png)

(2) Now if I remove the Categories in the listing it shows 25 entries by
Title
[without categories](https://user-images.githubusercontent.com/2118777/113837583-e72f1880-9785-11eb-80f3-98cc1dd31075.png)

So if that is normal behavior then there is no bug, however I always
thought that the entries were only listed by title as one entry can be in
several categories but it is still really only one entry ?

The fact it showed more entries than there are in the drop down menu at the bottom is just that ee appears to
count the categories as separate entries hence 32 actual entries but 65 virtual ones ( one entry is in three categories , all others are in two )

next time will post in github, replying by email doesn't seem to work

**Comment by intoeetive** [comment]
I'm still unable to replicate this :(

Just to confirm, "Categories" column represent categories, not the custom field named "categories"?

If you add and entry via Control Panel and don't assign it to any category, would it still not show when Categories column is present?

**Comment by diarbyrag** [comment]
I’ll try that later but you are welcome to login to the test site if that
is easier. It is on the actual server, just not online.


Gary

*************************************
Gary Braid
01625 560065
07798 743208
*************************************

**Comment by diarbyrag** [comment]
Hi Yuri,
Didn't think this would be so hard to explain, might have got it this time.

In the CP I have selected the education channel which contains 32 single entries, some of which are in two or three different categories.

So...

I selected to show the categories in the drop down to the right.

I selected to list alphabetically by title

Default at the bottom says show (25)

The panel lists 13 entries by title not 25 out of 32.

Now ...

Image 1 >> if you count the categories in the list it = 25.

Image 2 >> I removed two categories from Adlington entry so it has no category attached to it. The list then shows 24 categories but does not show the category of primary with the Hollinhey entry at the bottom, however with the first one empty (counted as one) ee then shows 24 category entries by removing primary from the last one = 25

Image 3 >> I removed two categories from Adlington & Bollonbrook entries so they have no categories attached to them, the list then shows 23 categories with two empty, primary is now showing on the last one = 25

Visually it looks wrong as I expected ee to list entries just by title, it is quite common to add an entry with different categories to enable customers to find something by different routes ?

In the scheme of things it is no big deal but if it then lists entries but removes categories from view then that can be confusing.

I would much prefer ee to always list the entries by title and disregard however many categories that entry is in ??

Let me know, I'm sorry if I have caused you any grief, I just found this behavior a bit bizarre .

Gary

[ee_listing.pdf](https://github.com/ExpressionEngine/ExpressionEngine/files/6272248/ee_listing.pdf)

**Comment by intoeetive** [comment]
@diarbyrag - thank you, I can see this now. We will look for possible solutions (this might be more generic problem as a whole, so might take time)

**Comment by diarbyrag** [comment]
Hi Yuri, as I said it’s not a problem as such, just looked wrong, thanks
for taking time to investigate with me. I love ee and it is better than
ever. cheers Gary


Gary

*************************************
Gary Braid
01625 560065
07798 743208
*************************************

**Comment by diarbyrag** [comment]
nice one Yuri, can’t wait to see it work. well done to the ee team again


Gary

*************************************
Gary Braid
01625 560065
07798 743208
*************************************
