### ISSUE TITLE
TypeError: directory is undefined 

### ISSUE THREAD

**Issue by studionigh** [ExpressionEngine/ExpressionEngine#991]
I have a channel that uses both grids and relationship fields.  I have a problem in the cp where the relationship fields are not loading.  I have checked and mod_security is not an issue.
https://www.dropbox.com/s/ua6u2syyatjvzqh/Screen%20Shot%202021-03-31%20at%203.39.03%20PM.png?dl=0

In addition, each time I save the entry all of the grid fields add a blank row.  I am unable to delete the rows after they are created.
https://www.dropbox.com/s/p090te2ainly8c2/Screen%20Shot%202021-03-31%20at%203.46.24%20PM.png?dl=0  

Here are the errors I get:
https://www.dropbox.com/s/w0hzmbyfrexs0mo/Screen%20Shot%202021-03-31%20at%203.41.25%20PM.png?dl=0

Help!

**Comment by TomJaeger** [comment]
I can't tell 100% from the screenshots.  What version of EE is this running?

It would also be good to know what version of PHP your currently running. 

It would also be great to know if your running MSM?

**Comment by studionigh** [comment]
Yeah, sorry, that would be helpful.  EE 6.0.3 and PHP 7.0. I am running MSM on a few subdomains.

**Comment by ops-andy** [comment]
@studionigh few more questions:
* is this a fresh install or an upgrade. If this is an upgrade have you tried downloading a fresh copy of 6.0.3 and manually copying the `themes/ee` folder over. A lot of Javascript issues are caused because of the themes folder being corrupted. Also, if this one an upgrade, ensure that the `themes/ee` folder is copied over to each of your MSM site's web_root folders.
* have you tried disabling extensions and seeing if this problem still persists? `$config['allow_extensions'] = 'n';` https://docs.expressionengine.com/latest/general/system-configuration-overrides.html#allow_extensions

**Comment by studionigh** [comment]
This is an upgrade. I have updated `themes/ee` with fresh files, and added the same to the subdomains.  I also tried disabling the extensions with no avail.  I notice that when I load an entry that already has a relationship field filled, then I do not get this error. Only on new entries, and or entries that do not have the relationship field filled.  Here is another screenshot of the error from Chrome:

![Screen Shot 2021-04-01 at 10 10 27 AM](https://user-images.githubusercontent.com/182628/113319432-0554ce80-92d7-11eb-99cb-6602121e36a8.png)

**Comment by ops-andy** [comment]
unfortunately I still have not been able to replicate this. I'm going to see if anyone else can and follow up.

**Comment by studionigh** [comment]
This is where the error happens, on line 2051: 
![Screen Shot 2021-04-01 at 10 54 32 AM](https://user-images.githubusercontent.com/182628/113320946-b6a83400-92d8-11eb-9a7e-9daa05b999bd.png)
And here, on line 2001: 
![Screen Shot 2021-04-01 at 10 54 46 AM](https://user-images.githubusercontent.com/182628/113320962-bad45180-92d8-11eb-8d0e-f5c4451af2aa.png)

**Comment by robinsowell** [comment]
Are you using file fields and are any of them from a different MSM site?  In other words- file upload directories are MSM site specific.  So you can't use a file from site a in site b's channel or it will likely cause problems in the cp.

**Comment by studionigh** [comment]
Yes, the channel has file fields but no, there are no cross file directories.

**Comment by studionigh** [comment]
SOLVED:  Somehow, during the upgrade?? one of the file fields in this channel did not have a directory associated with it.  The "Allowed Directory" was basically NULL. normally it would default to "All", but was blank.  Thanks for all the help!!!

**Comment by ops-andy** [comment]
awesome. Glad to hear you go this resolved.
