### ISSUE TITLE
Protect column names to resolve issue of mySQL miss interpreting column names as functions

### ISSUE THREAD

**Issue by dave-agilepixel** [ExpressionEngine/ExpressionEngine#997]
in system/ee/legacy/libraries/Template_router.php

line 84

ee()->db->order_by('order, group_name, template_name', 'ASC');

should be 

ee()->db->order_by('`order`, `group_name`, `template_name`', 'ASC');

as "order" can be miss interpreted by mySQL as it's a function as well as a column name

**Comment by intoeetive** [comment]
@dave-agilepixel thank you for the suggestion!

Internally, the parameters are being passed through `escape_identifiers` function, which should take care of what you report as potential issue.

I'm going to close the ticket, please reopen if you see this as real issue and can describe scenario where this generates an error or unexpected behaviour.
